### ISSUE TITLE
After launching UTM, ios freezes on killing services, respring, etc.

### ISSUE THREAD

**Issue by obbcth** [utmapp/UTM#104]
Version 0.3, ios 13.3, Jailbroken. (iPad Air 3)

I started UTM app and do nothing. Exited with x close button.
Few minutes later, I tried to kill another services not related with UTM, and the device freezes. (UTM also does not work properly. Just shows white screen.)

This also happens when I tried to respring and restart.
I think the close button does not work properly, or the ios bugs still happen somewhere.

**Comment by osy86** [comment]
I haven’t tested the X button on a jailbroken device. Maybe someone else can comment if it’s worked for them?

**Comment by WongIong** [comment]
Mine is 11 pro max, 13.3, jb
I haven't faced this problem
But I can't access the internet. I have manually set up DNS, LAN IP. But still can't access it.
Windows 7, set these inside the system, keep empty from VM’s network setting.

**Comment by ThatsNiceGuy** [comment]
The X button works perfectly on my iPad Pro 11” on 13.3 jailbroken with unc0ver

**Comment by obbcth** [comment]
If no one faced this problem, it might be related with my device (Air 3) blank screen issue.

**Comment by miuirussia** [comment]
No, I have same problem

**Comment by obbcth** [comment]
I will close it now. If anyone can reproduce this issue, please re-open it. I haven't faced this problem since v1.0.

**Comment by ThatsNiceGuy** [comment]
Still exists on iPad Pro 11” 2020. On iPadOS 13.4.1
It happens if you force quit the app in any way without using the X button
Sideloaded RC1.0 with AltStore

**Comment by obbcth** [comment]
@ThatsNiceGuy This problem occurs after closing with X button.
You mean is #32 .
