### ISSUE TITLE
No documentation on how to simulate various mouse click events

### ISSUE THREAD

**Issue by Halo-Michael** [utmapp/UTM#110]
No documentation on how to simulate various mouse click events, I still don't know how to simulate a right mouse click event. The general method should be long press to simulate the right mouse button click event, however this doesn't seem to be the case in UTM.

**Comment by ThatsNiceGuy** [comment]
This was documented in the faq on the website iirc.
To right click, tap with two fingers at the same time

**Comment by arjanvlek** [comment]
How to drag with the left mouse button preses? Tapping twice then dragging seems not to work

**Comment by ThatsNiceGuy** [comment]
I’m not sure if this was intended, but tapping (once) and holding for mouse dragging no longer works for me. I can no longer drag windows around
