### ISSUE TITLE
[qemu] add qemu_efi.fd for aarch64 boot to UEFI

### ISSUE THREAD

**Issue by luke-rabbit** [utmapp/UTM#111]
VMs Start with Black Screen

**Comment by osy86** [comment]
Can you explain this more?

**Comment by luke-rabbit** [comment]
I want to run win 10 arm or linux arm.
I tried a lot of arguments, But black screen after vm starts.

**Comment by osy86** [comment]
Not sure what that has to do with the title of this issue. Send a pull request if you have a fix.

**Comment by osy86** [comment]
Not sure if that pull request was meant to be closed?

**Comment by luke-rabbit** [comment]
sorry，I did wrong.
