### ISSUE TITLE
’I thought’ Bluetooth issue 

### ISSUE THREAD

**Issue by WongIong** [utmapp/UTM#116]
I have two devices that have installed UTM.
iPad Air 3
iPhone 11 Pro Max

My iPad has been cleared the whole Bluetooth paired list days ago, I thought that was an accident from Apple id.

But I found that today, my iPhone has also this situation, all paired devices have been cleared.
Then I checked my other iPhones, the Bluetooth paired list is still there.

So, maybe there is something will reach a bug then clear the Bluetooth paired devices.

All iDevices are jailbroken.

**Comment by osy86** [comment]
I don’t think it’s UTM related. The code is sandboxed and runs on non-jb devices so it cannot modify any system settings.

**Comment by WongIong** [comment]
Ok, thanks
