### ISSUE TITLE
A problem with the mouse in UTM

### ISSUE THREAD

**Issue by WindowsBetaTest** [utmapp/UTM#118]
The mouse can't convey click instruction well.
When I click on the screen, the mouse will shake.

**Comment by cs-sugar** [comment]
Touch screen, that is, click for one second or less, the mouse will move to the click position at the same time, and then left click the click position at the same time; click for one second or less, and then drag is left drag; click for more than three seconds to move the mouse to the click position at the same time, then make a drop, and then right click at the same time (similar to the remote control of windows and sunflower on Microsoft touch screen). Pencil touch is to use the pen light point to move the mouse to the position where the pen clicks at the same time, and then press the left key at the same time. Press hard to move the mouse to the position where the pen clicks at the same time, and then make a drop sound, and then right click at the same time. I hope this will take effect in version 0.5. Thank you.

**Comment by WindowsBetaTest** [comment]
I have some suggestions:

Click the screen with one finger = click the mouse

Click the screen with two fingers = right click the mouse

Two fingers moving up and down at the same time = mouse wheel rolling

Drag screen with three fingers = adjust screen size and position

**Comment by cs-sugar** [comment]
En,thank you. But the apple pencil.

**Comment by cs-sugar** [comment]
Sure.

**Comment by cs-sugar** [comment]
Sure. Thank you.

**Comment by cs-sugar** [comment]
I hope this will take effect in version 0.5.

**Comment by osy86** [comment]
@cs-sugar I have this issue open in case anyone else wishes to work on it. It is not in the milestone for 0.5 or any future release.

**Comment by osy86** [comment]
@WindowsBetaTest I cannot reproduce this issue. Can you upload a video?

**Comment by WindowsBetaTest** [comment]
This problem seems to be fixed in v0.5

**Comment by WindowsBetaTest** [comment]
I think this problem still exists.

**Comment by osy86** [comment]
Please upload a video showing the issue.

**Comment by WindowsBetaTest** [comment]
Please wait.

**Comment by WindowsBetaTest** [comment]
[WP_2020.zip](https://github.com/utmapp/UTM/files/4366901/WP_2020.zip)

**Comment by WindowsBetaTest** [comment]
Sorry,the video I took with the lumia 950xl may look upside down.

**Comment by WindowsBetaTest** [comment]
It seems that this problem only occurs in Windows XP (Maybe the driver).
