### ISSUE TITLE
Crash when hitting play button

### ISSUE THREAD

**Issue by Matoo69** [utmapp/UTM#119]
iPhone 11 pro max,iOS 13.3.1 
Try all version the same problem i create win xp,7 and when hitting play button app just crash,i try 1cpu,ram change and nothing pls help

**Comment by osy86** [comment]
Please try this special build https://mega.nz/#!Zh5mFAhA!k8krwJjhSOfh_y0MyAlfz301g82R1G23o9QiwWM9q6Q
Tell me if you see a message on startup.

**Comment by osy86** [comment]
Duplicate of #95

**Comment by Matoo69** [comment]
Yes i se the message on startup but the same problem :/

**Comment by osy86** [comment]
The same message as the other user or a different one?

**Comment by Matoo69** [comment]
Do you mean at startup when i try to create and open vw like windows or the message when i first open UTM when install??

**Comment by Matoo69** [comment]
When install UTM app and first time open j got msg ( if you force close the app you must reboot phone etc...) but when i create win on UTM and everything set ut i hit play button and APP just crash,hit me back to the home screen instant.
