### ISSUE TITLE
Support specifying the CPU

### ISSUE THREAD

**Issue by osy** [utmapp/UTM#1197]
Not really a good use case, but maybe expose as an advanced system setting.

**Comment by osy** [comment]
@conath maybe this becomes useful now that installing macOS requires setting the x86 CPU to emulate right?

**Comment by conath** [comment]
Yes, this would be useful because one of the extra arguments used is `-cpu Penryn,+ssse3,+sse4.1,+sse4.2`. In addition it would be nice to be able to specify the amount of threads per CPU core. (`-smp cpus=4,cores=2,threads=2,sockets=1` gives two physical cores with two logical cores each).

**Comment by osy** [comment]
Setting the thread count is only useful in hypervisor mode (where it defaults to the number of threads per core your host machines has). In TCG it doesn't make a difference.
