### ISSUE TITLE
Clipboard sharing not working

### ISSUE THREAD

**Issue by ankushnarula** [utmapp/UTM#1204]
Under the QEMU tab, checking the  _Advanced_ option doesn't enable the ability to edit settings and also disables scrolling of the QEMU arguments list.

UTM 2.0.3 (13) on macOS 11.01 arm64

Reproduce:

1. Create an Ubuntu ARM64 virtual machine [as described on this UTM wiki page](https://github.com/utmapp/UTM/wiki/Install-Ubuntu-ARM64-on-Apple-M1).
2. Save changes
3. Edit the saved machine
4. On the QEMU tab, enable the Advanced option box
5. Attempt to scroll or edit the QEMU arguments list

![utm-vm-settings-qemu-advanced](https://user-images.githubusercontent.com/68403/101123411-d5185000-35c2-11eb-8429-1dea18b0a606.gif)

**Comment by ankushnarula** [comment]
FYI, I came across this bug because I'm having difficulty using `qemu-guest-agent` on the Ubuntu guest (with desktop installed).

I've never used QEMU before and so my current theory is that the default setting of: 
  `-device virtserialport,chardev=qga0,name=com.redhat.spice.0` 

needs to be changed to: 
`-device virtserialport,chardev=qga0,name=org.qemu.guest_agent.0`

Because when attempting to start the service in the guest it times out because it can't access the device.

I'd like to be able to test this theory from the UI.

**Comment by osy86** [comment]
Advanced mode means it throws out all the arguments except a few mandatory ones and you manually specify *every* argument. It’s really only useful for debugging or creating a highly custom .utm for distribution.

If you want to have copy/paste and resolution changing and other stuff I would install `sudo apt install spice-vdagent spice-webdavd`.

**Comment by ankushnarula** [comment]
I'm running into a similar problem with a very similar error message:

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/68403/101126782-2b3cc180-35ca-11eb-922c-ccccac5efb36.png">

**Comment by osy86** [comment]
@ankushnarula Did you enable sharing from settings?

**Comment by osy** [comment]
Hijacking this issue to track clipboard sharing issue on macOS.

**Comment by fjwillemsen** [comment]
On UTM 3.2.4 on M1 Pro with Ubuntu 22.04 LTS server I can't get clipboard sharing to work. I have checked the box in the VM setup and installed spice-vdagent as per [the guide here](https://mac.getutm.app/gallery/ubuntu-20-04). I had to manually start the service, but even though it says it is active (attached screenshot), it doesn't work. 
<img width="746" alt="image" src="https://user-images.githubusercontent.com/6725103/190108695-5d3625b9-a6f5-4c88-9b9d-44f0280593c3.png">
What am I doing wrong here?

**Comment by ktprograms** [comment]
In the Ubuntu desktop, in a shell, run `spice-vdagent` (note that this doesn't end in "d" like with the service).

You can also see how to add it to the GNOME autostart commands. It needs to run in an Xorg environment (not the TTY)

**Comment by fjwillemsen** [comment]
Thank you for your response. Upon doing so, I got the following error: 
<img width="623" alt="image" src="https://user-images.githubusercontent.com/6725103/190182281-9087f9b0-9378-4988-8c36-c5878413bba4.png">

**Comment by fjwillemsen** [comment]
I had the choice between "Ubuntu" and "Ubuntu on XOrg", this happened on "Ubuntu". But I just tried again and it works, so I suppose it's alright now - thanks for your help!

**Comment by fjwillemsen** [comment]
@vinn2010 if I remember correctly, by going to Xorg and doing what @ktprograms suggested.

**Comment by erzakiev** [comment]
> In the Ubuntu desktop, in a shell, run `spice-vdagent` (note that this doesn't end in "d" like with the service).
> 
> You can also see how to add it to the GNOME autostart commands. It needs to run in an Xorg environment (not the TTY)

Thanks for the response. So there is no way to set up copy-pasting with utm-virtualized ubuntu 22.04 LTS **SERVER** version (without GUI)?

**Comment by ktprograms** [comment]
No, it requires an X11 GUI environment

**Comment by just-doit** [comment]
Just so I understand this correctly. There is NO clipboard sharing between macOS and the console?
I can't believe that...

**Comment by ktprograms** [comment]
> I can't believe that...
In theory someone could write a program to read from the spice port and inject keypresses, but it's not been done yet.

Anyway, if you don't have a need for a GUI (hence being in a console), just use a serial port display, you can copy/paste from that since it's just like a Terminal.app.

**Comment by just-doit** [comment]
> Anyway, if you don't have a need for a GUI (hence being in a console), just use a serial port display, you can copy/paste from that since it's just like a Terminal.app.

You're right, of course, and I'm currently doing it that way, too.

**Comment by godblesslancek** [comment]
Thank you, the solution of installing ubuntu-gnome-desktop over a vanilla Ubuntu ARM64 VM worked like a charm for me, the clipboard now works when doing `Ctrl^+Maj+V` .

What worked for me 
 Enable "Clipboard sharing"
`sudo apt install ubuntu-gnome-desktop`
`reboot`

What didn't work for me
 Enable "Clipboard sharing"
`sudo apt install spice-vdagent`
`reboot`

Not sure why installing gnome desktop environment did the trick, though.

**Comment by ChilledAlpaca** [comment]
> Just so I understand this correctly. There is NO clipboard sharing between macOS and the console? I can't believe that...

https://serverfault.com/questions/874309/virt-manager-spice-copy-paste-doesnt-work
says that a serial has to be created, 
for me it did the job. I got a terminal window, to work in and to paste for my macOS host

**Comment by smayer97** [comment]
https://github.com/utmapp/UTM/releases/tag/v4.6.1

"Copy/paste synchronization between macOS 15 guest and host now works when the guest tools are installed (from the CD icon in the toolbar)."
Earlier guests are not supported due to a bug in Apple's VirtIO drivers.

**Comment by smayer97** [comment]
There is a workaround for any macOS older than 15 Sequoia (not to be confused with macOS 10.15 Catalina)... using Screen Sharing.
"To have copy-paste enabled in UTM for macOS with ARM64 M1 or M2, you can connect to your guest OS via "Screen Sharing"". See [simple instructions](https://stackoverflow.com/a/73948781/8884051)
