### ISSUE TITLE
Slow disk I/O on Ubuntu 20.04.1 VM + MacBook Pro M1

### ISSUE THREAD

**Issue by huming2207** [utmapp/UTM#1206]
**Describe the bug**

Firstly, great thanks for your work! 

Somehow the disk I/O is very slow on my Ubuntu 20.04.1 VM with MacBook Pro M1. It takes a long time to install after a fresh installation of the Ubuntu and then followed by `apt dist-upgrade`, especially when it upgrades the initramfs. It may take up to 9 minutes:

![image](https://user-images.githubusercontent.com/4463497/101223026-2453a300-36df-11eb-8161-b3cc96863625.png)

I've roughly tested the disk I/O via `dd`. Here's the result:

![image](https://user-images.githubusercontent.com/4463497/101222111-2ddc0b80-36dd-11eb-835d-ab2eec7f53bb.png)

command used: `time sh -c "dd if=/dev/zero of=test.bin bs=100k count=1k && sync"` or `time sh -c "dd if=/dev/zero of=/tmp/testfile bs=100k count=1k && sync"`

The window on the left is the VM's result, and on the right is the macOS native result.

For `hdparm -Tt /dev/vda` it gives me: 

![image](https://user-images.githubusercontent.com/4463497/101221925-d473dc80-36dc-11eb-84c0-2ae959080736.png)

By the way, the hardware hypervisor is enabled:

![image](https://user-images.githubusercontent.com/4463497/101222262-87dcd100-36dd-11eb-8c83-4c79fe588a24.png)

**Version**
2.0.13

**Additional context**
I'm using Ubuntu 20.04.1, host device is MacBook Pro M1, 16GB, 1TB SSD with macOS 11.0.1

Meanwhile, the VM is using Btrfs:

![image](https://user-images.githubusercontent.com/4463497/101223147-7268a680-36df-11eb-8450-dc86bd0e6d15.png)

Maybe that's the troublemaker? I will try installing with Ext4 again later.

**Comment by huming2207** [comment]
Now I'm trying to install Ubuntu 20.04.1 server again. Everything stays the same except the filesystem changed to Ext4. It's a bit faster but still stuck at `update-initramfs` for 5-ish minutes...

**Comment by huming2207** [comment]
Looks like `-accel` is `tcg`, not `hvf`, even I enabled using hardware hypervisor:

![image](https://user-images.githubusercontent.com/4463497/101226133-9f20bc00-36e7-11eb-907f-3825b5271988.png)

**Comment by osy86** [comment]
Try unchecking and checking again?

**Comment by huming2207** [comment]
@osy86 Yea it looks good this time:

![image](https://user-images.githubusercontent.com/4463497/101226620-29b5eb00-36e9-11eb-9ed0-037f8933edf2.png)

Try booting up now...

**Comment by huming2207** [comment]
@osy86 MUCH better:

![image](https://user-images.githubusercontent.com/4463497/101226732-8a452800-36e9-11eb-8b46-2d3af947861b.png)

**Comment by huming2207** [comment]
Here's a quick test with HVF actually enabled and then compile Nodejs master (with `make -j8`):

![image](https://user-images.githubusercontent.com/4463497/101227366-b366b800-36eb-11eb-9f64-bcd81b50c420.png)

Compared to my Ryzen desktop, it takes 10-11 minutes while my MBP M1 takes about 9-10 natively. For a VM, it works really well! Again, thanks for your great work!

**Comment by osy86** [comment]
Frankly I’m amazed you didn’t immediately delete because you were running a slow binary translation instead of virtualization.

**Comment by huming2207** [comment]
> Frankly I’m amazed you didn’t immediately delete because you were running a slow binary translation instead of virtualization. 

Yes. I'm trying to get Docker working on it. Like this guy did: https://finestructure.co/blog/2020/11/27/running-docker-on-apple-silicon-m1-follow-up

Now the VM is up, we can get Docker on and set up the rest of the stuff.

Meanwhile, I'd also suggest UTM can provide a similar function (or maybe just a perbuilt VM?) for Docker users. It may be the only way to get Docker somewhat working until Docker itself and those images I need officially support Apple Silicon platforms.

**Comment by huming2207** [comment]
@osy86 I mean, it would be really nice to have some features like this:

- A "Docker host" in a lightweight prebuilt VM, maybe a Debian, or Ubuntu but rip off the Snap stuff.
- UTM itself has a "Docker mode", that loads the "Docker host VM" on one click, and hide at background. Users can also set port forwarding or SSH into it for advanced config.
- User also install a "Docker client" and configure the default context that makes it speak with the "Docker host" inside of that VM.

**Comment by osy86** [comment]
I think Docker has their own plans for M1 virtualization. UTM is more of a virtualbox/libvirt replacement for Macs and the focus is on general users.

**Comment by huming2207** [comment]
@osy86 Yes I understood. But maybe a hide in background (to the status bar on top right) function for UTM may be a nice-to-have idea.

**Comment by XciD** [comment]
Could we provide a docker-machine driver for UTM ?
