### ISSUE TITLE
Referencing files in the utm container from custom qemu parameters

### ISSUE THREAD

**Issue by gklka** [utmapp/UTM#1207]
**Describe the bug**
Reference to files in the .utm container from the custom parameters does not work. If I import an ISO file to the utm container, then the config file will contain something similar to "/path/to/Images/Images/file.iso". I suppose the first part will be replaced to the actual path.

When I add the files but use custom qemu parameters, the same pattern will not be replaced, so I am not able to access the iso file I added to the container.

I also tested by adding the real filesystem URL of the file, which works nice, but prevents me to move the utm container to an iOS device or another computer.

**Version**
Version 2.0.13 (13)

**To Reproduce**
1. Create a new VM
2. In "Drives" click "Import drive"
3. Select an ISO file (in the example: morphos-3.14.iso)
4. Go to QEMU tab
5. click "Advanced: Bypass configuration"
6. Add -cdrom
7. Add "/path/to/Images/Images/morphos-3.14.iso"
8. fill in the other parameters unrelated to this test but needed to run the machine
9. Save
10. Hit run

**Expected behavior**
qemu to find the iso file

**Screenshots**
<img width="1012" alt="Screen Shot 2020-12-05 at 0 36 59" src="https://user-images.githubusercontent.com/866694/101225561-0d3a9400-3692-11eb-92cc-104858ff6ec8.png">
<img width="1012" alt="Screen Shot 2020-12-05 at 0 37 03" src="https://user-images.githubusercontent.com/866694/101225566-10ce1b00-3692-11eb-8b5a-e3e8e180af19.png">
<img width="1012" alt="Screen Shot 2020-12-05 at 0 37 07" src="https://user-images.githubusercontent.com/866694/101225570-13307500-3692-11eb-9945-8aea8a6a8bb6.png">
![Screen Shot 2020-12-05 at 0 37 21](https://user-images.githubusercontent.com/866694/101225575-162b6580-3692-11eb-8463-5660d385b771.png)

**Additional context**
The error message I've got:

```
qemu-system-ppc: -cdrom /path/to/Images/Images/morphos-3.14.iso: Could not open '/path/to/Images/Images/morphos-3.14.iso': No such file or directory
```

**Comment by osy86** [comment]
There is no path replacement. The advanced feature is only for debugging. If there’s a use case you need that requires it, please file a new ticket requesting a feature.

**Comment by gklka** [comment]
So I have to write absolute paths, that is the only way? Perhaps when the path doesn't start with a `/` it should be treated as a relative path from the container, right?

**Comment by osy86** [comment]
No it would be relative to the QEMU binary path.
