### ISSUE TITLE
Not a bug (I think) but app won’t open.

### ISSUE THREAD

**Issue by DaggersForLife** [utmapp/UTM#1210]
**Describe the bug**
Well it’s not a bug I think but the app won’t open. I can tap it on my Home Screen but it doesn’t open. There isn’t even an app opening animation. I installed it using Filza + App Sync Unified For iOS 14

**To Reproduce**
1. Try opening the app. It won’t work

**Crash log**
“If the app crashed, you need a crash log. To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here.” Sorry but it didn’t crash and I can’t get the log since it won’t open

**Debug log**
“For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the bottom of the configuration options is `Debug Log`. Turn it on and save the VM. After you experience the issue, quit the VM and re-launch UTM. Open the VM settings again and select `Export Log...` and attach it here.” Like I said I can’t open the app

**Upload VM**
“If possible, upload the `.utm` you are experiencing an issue with. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.” Not possible

**Comment by DaggersForLife** [comment]
Hey guys I installed this command line package called “open” so I command lined it and it said “com.utmapp.UTM could not be opened. Reason: Security Policy Error”

**Comment by DaggersForLife** [comment]
Maybe it could be another verification step?

**Comment by DaggersForLife** [comment]
![26CCFEDE-9736-4CEB-B379-CEC59E29C4B3](https://user-images.githubusercontent.com/69256931/101287309-6a942980-37e7-11eb-8043-0d4934301242.jpeg)

**Comment by IIWare** [comment]
2 solutions:

1. type in `su` and if it's asking you for password, put password `alpine`

2. if the previous solution doesn't work then do` sudo <command>`
example: `sudo open com.utmapp.UTM`

hope this helps.

**Comment by osy86** [comment]
The current instructions for jailbroken devices is out of date. See the discussions in #537
