### ISSUE TITLE
UTM does not detect jailbreak on iOS 14.2

### ISSUE THREAD

**Issue by brunocastello** [utmapp/UTM#1211]
I've just updated to the latest UTM version for iOS/iPadOS.

iPad Pro 2017 12.9-inch, running iPadOS 14.2, jailbroken with checkra1n. I've installed the latest UTM version. Now every time I open UTM, I am being nagged by a pop-up complaining about iOS version not supporting running VMs while unmodified and telling me that I have to be jailbroken or running with a remote debugger attached.

However, the VMS do run as expected - I tested a MSDOS 6.22/Win 3.11 VM and it ran as expected.

The funny part is that **I am jailbroken** and running Cydia as well. Do I need any update for my jailbreak or is it just a UTM bug? Previous UTM versions after I jailbroke my iPad did not complain.

**Comment by IIWare** [comment]
what did you install UTM.ipa with? (the reason why I am asking is because, sometimes, app installers doesn't give jailbreak detection or ios version access to ipa apps being installed, so the UTM ipa app can't detect if the system is jailbroken or not or the system ios version.)

**Comment by Vishram1123** [comment]
Sorry if I sound like I am advertising, but one solution is to uninstall UTM the way you installed it, and add my Cydia repo ([https://vishram1123.gitlab.io/utm-cydia/](https://vishram1123.gitlab.io/utm-cydia/)) to Cydia, and then install the UTM package from there.

**Comment by osy** [comment]
@brunocastello how did you install it on your jailbroken iPad? It should have detected the `dynamic-codesigning` entitlement.

**Comment by brunocastello** [comment]
> @brunocastello how did you install it on your jailbroken iPad? It should have detected the `dynamic-codesigning` entitlement.

Hi, I used latest stable Xcode. The process was the same since the very first UTM version:

First I resign the IPA with my provisioning profile on iOS App Signer, I have an Apple Developer (paid) account with development certificates. Once the IPA is resigned, I load Xcode, Devices and Simulators, connect my iPad Pro, then drag and drop the IPA file where it should be in that Xcode window. Wait a few minutes and the app is installed. This was the first time I was nagged by that pop-up window when opening UTM on my iPad.

My certificate and provisioning files are set to expire in january or february 2021 (I have more than one). I was planning to set up a new one only when they expire, should be the end of January 2021. I used the same provisioning file for every previous UTM install. I tried a different one later but no luck with that pop-up.

Still, my machines are working as expected on UTM. I just keep being nagged by that pop-up every time I first load UTM.

**Comment by brunocastello** [comment]
Just installed the latest version of UTM right now and the issue still persists. And I am also still able to use to the VM despite this. Did you change something which would require a change in my dev certificates, I mean, a new provisioning file with some different setting? This started to happen with previous version.

**Comment by KhazanGu** [comment]
> > @brunocastello how did you install it on your jailbroken iPad? It should have detected the `dynamic-codesigning` entitlement.
> 
> Hi, I used latest stable Xcode. The process was the same since the very first UTM version:
> 
> First I resign the IPA with my provisioning profile on iOS App Signer, I have an Apple Developer (paid) account with development certificates. Once the IPA is resigned, I load Xcode, Devices and Simulators, connect my iPad Pro, then drag and drop the IPA file where it should be in that Xcode window. Wait a few minutes and the app is installed. This was the first time I was nagged by that pop-up window when opening UTM on my iPad.
> 
> My certificate and provisioning files are set to expire in january or february 2021 (I have more than one). I was planning to set up a new one only when they expire, should be the end of January 2021. I used the same provisioning file for every previous UTM install. I tried a different one later but no luck with that pop-up.
> 
> Still, my machines are working as expected on UTM. I just keep being nagged by that pop-up every time I first load UTM.

I get the same issue and even I can't launch the virtual machine. It crashes every time when I try to activate it.

**Comment by IIWare** [comment]
> > > @brunocastello how did you install it on your jailbroken iPad? It should have detected the `dynamic-codesigning` entitlement.
> > 
> > 
> > Hi, I used latest stable Xcode. The process was the same since the very first UTM version:
> > First I resign the IPA with my provisioning profile on iOS App Signer, I have an Apple Developer (paid) account with development certificates. Once the IPA is resigned, I load Xcode, Devices and Simulators, connect my iPad Pro, then drag and drop the IPA file where it should be in that Xcode window. Wait a few minutes and the app is installed. This was the first time I was nagged by that pop-up window when opening UTM on my iPad.
> > My certificate and provisioning files are set to expire in january or february 2021 (I have more than one). I was planning to set up a new one only when they expire, should be the end of January 2021. I used the same provisioning file for every previous UTM install. I tried a different one later but no luck with that pop-up.
> > Still, my machines are working as expected on UTM. I just keep being nagged by that pop-up every time I first load UTM.
> 
> I get the same issue and even I can't launch the virtual machine. It crashes every time when I try to activate it.
> I install UTM on my iPhone X with iOS 14.2 and no jailbreak.

@brunocastello's issue is that the message in UTM keeps on popping up in UTM, but the VM's are working.

your issue is that the VMs crash when starting them.

**Comment by KhazanGu** [comment]
> > > > @brunocastello how did you install it on your jailbroken iPad? It should have detected the `dynamic-codesigning` entitlement.
> > > 
> > > 
> > > Hi, I used latest stable Xcode. The process was the same since the very first UTM version:
> > > First I resign the IPA with my provisioning profile on iOS App Signer, I have an Apple Developer (paid) account with development certificates. Once the IPA is resigned, I load Xcode, Devices and Simulators, connect my iPad Pro, then drag and drop the IPA file where it should be in that Xcode window. Wait a few minutes and the app is installed. This was the first time I was nagged by that pop-up window when opening UTM on my iPad.
> > > My certificate and provisioning files are set to expire in january or february 2021 (I have more than one). I was planning to set up a new one only when they expire, should be the end of January 2021. I used the same provisioning file for every previous UTM install. I tried a different one later but no luck with that pop-up.
> > > Still, my machines are working as expected on UTM. I just keep being nagged by that pop-up every time I first load UTM.
> > 
> > 
> > I get the same issue and even I can't launch the virtual machine. It crashes every time when I try to activate it.
> > I install UTM on my iPhone X with iOS 14.2 and no jailbreak.
> 
> @brunocastello's issue is that the message in UTM keeps on popping up in UTM, but the VM's are working.
> 
> your issue is that the VMs crash when starting them.

You are correct, I have the same issue the message in UTM keeps on popping up in UTM too.

**Comment by osy** [comment]
@brunocastello Uninstall UTM and try installing from the new repo https://cydia.getutm.app/ (add to Cydia/Sileo). Then see if the error still shows up.

**Comment by brunocastello** [comment]
> @brunocastello Uninstall UTM and try installing from the new repo https://cydia.getutm.app/ (add to Cydia/Sileo). Then see if the error still shows up.

Tried it. Error does not show up, However I am not able to edit UTM settings on iOS Settings.app and an UTM folder does not show up in Files so I couldnt move back my VMs because the folder is missing. I will revert back to previous UTM. Next month I will have to do a new provisioning file anyway, the certificate will expire between january and february. If you could show me anything I could change when I create my new certificate later, that would be great.

**Comment by osy** [comment]
@brunocastello Have you tried AltStore + AltDaemon?

**Comment by brunocastello** [comment]
Not yet. It’s 4AM now, gonna try later. Thanks

**Comment by osy** [comment]
@brunocastello Try the latest build https://github.com/utmapp/UTM/actions/runs/453385049 and use the arm64 UTM.xcarchive with iOS App Signer. This hopefully fixes the jailbreak detection.

Separately, I still want you to test AltStore + AltDaemon to see if that works booting VMs with checkra1n. If that works, I'm going to scrap the Cydia package stuff because honestly it's riddled with issues.

**Comment by brunocastello** [comment]
> @brunocastello Try the latest build https://github.com/utmapp/UTM/actions/runs/453385049 and use the arm64 UTM.xcarchive with iOS App Signer. This hopefully fixes the jailbreak detection.
> 
> Separately, I still want you to test AltStore + AltDaemon to see if that works booting VMs with checkra1n. If that works, I'm going to scrap the Cydia package stuff because honestly it's riddled with issues.

I tried the AltStore + AltDaemon solution first and it did not fix the issue. 

But your latest build (the xcarchive one) works! Great work, osy!

**Comment by osy** [comment]
@brunocastello So AltStore + AltDaemon + jailbroken works on iOS 14, correct? If so I think I'm going to remove the Cydia stuff because there's a lot of issues.

**Comment by brunocastello** [comment]
> @brunocastello So AltStore + AltDaemon + jailbroken works on iOS 14, correct? If so I think I'm going to remove the Cydia stuff because there's a lot of issues.

AltStore + AltDaemon does load UTM fine but with the warning message about the jailbreak, same fashion as Cydia solution, but I forgot to test this one with a VM. The xcarchive build this time I tested and does work flawlessly now.

Simply put, IMO I think you should forget the Cydia stuff anyway, because even DOSPad (a.k.a iDOS2 from litchie) on Cydia (or any other app from there that I can remember since day one) suffers from the same issues (no folder on Files and no screen in settings.app to configure).

**Comment by ThatsNiceGuy** [comment]
Maybe handle it like the jailbroken version of DolphiniOS, dump a folder in ~/Documents (like quite literally in the iOS filesystem in the `mobile` user) named UTM with configuration file and VMs. and have the configuration inside the app itself
