### ISSUE TITLE
Screen Resolution change not saved across restarts

### ISSUE THREAD

**Issue by MrMacintoshBlog** [utmapp/UTM#1213]
If a different screen resolution is picked in the boot options (example 1024x768) the setting will take for that boot but if you restart the VM it does not keep the setting.

It looks like we need to create a plfash image to store nvram settings.

This pull was created for ACVM to address the issue.

https://github.com/KhaosT/ACVM/pull/12

**Comment by osy** [comment]
Latest build support changing resolution in the guest (with the proper drivers).
