### ISSUE TITLE
tag: allocate 386856960 bytes for jit buffer: Invalid argument

### ISSUE THREAD

**Issue by yaboinextd00r** [utmapp/UTM#1214]
1. Bug Description
so i was gonna launch Mac OS X 10.5 with the correct settings and then i run into a Qemu error
2. Qemu error 
![image0](https://user-images.githubusercontent.com/73263612/101413221-fddc7480-3937-11eb-923f-7dd3b1d5df0c.png)
3. How to reproduce
not sure if other users of UTM are facing the same issue as I am, every time I launch a VM it would give me this error
4. Attempts
I have attempted to launch my VMS and change the amount of allocating more ram and then trying to launch but I still face the same issue

**Comment by osy** [comment]
Your config file seems to be corrupted or you put in wrong values (like a super large number for JIT size). You can post your .utm here and I can tell you what's wrong. Or it's easier if you just create a new VM from scratch with default settings.

**Comment by yaboinextd00r** [comment]
Had to put it in mega.nz [](https://mega.nz/folder/Nw5HhIgI#VTiIXFi9en8KZeT5adZjew)

**Comment by yaboinextd00r** [comment]
[file](https://mega.nz/folder/Nw5HhIgI#VTiIXFi9en8KZeT5adZjew)
