### ISSUE TITLE
[Feature] Add option to auto-generate drive parameters when using manual QEMU arguments setting

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#1216]
**Describe the bug**
If I enable `Advanced: bypass configuration and manually specify arguments` in QEMU settings, my VM doesn't boot because the Drives configuration is not passed to QEMU anymore.
Additionally on iOS, if I manually specify the drive path as an argument, the VM doesn't boot (maybe because the drive file isn't opened for read/write by the app; and the path can't be outside the sandbox).

**Proposed Fix**
It could be fixed by showing another toggle if the `Advanced: …` is set: `Automatically add Drive and Sharing arguments according to configuration`.

**Work already in progress**
I am already in the process of implementing the proposed fix. Here's a screenshot showing the added toggle:
![QEMU-args-drives - 1](https://user-images.githubusercontent.com/12073163/101612458-f2a64900-3a0a-11eb-95ad-426cfaa794b1.jpeg)

**Comment by osy** [comment]
There’s been a couple of proposals to improve the custom args page and my feeling is that the advanced args is only for debugging (testing qemu basically). If there’s anything you want to do that isn’t possible, there should be a direct UI way of doing it.

**Comment by conath** [comment]
I was trying to get a macOS 10.11 VM set up but it needed custom arguments. On second thought, maybe it would have been sufficent to put these arguments at the end as Custom Arguments. More generally I do think it's a bummer that (AFAIK) no VM can be booted with entirely custom arguments on iOS.

**Comment by osy** [comment]
Looking far ahead I want UTM to not be completely married to QEMU. There could be options for other backends so I don’t want all these .utm floating around that depend on qemu arguments.

**Comment by conath** [comment]
That's fair. I'll go ahead and close this but leave a hint for future reference. Here's how to include the drive configuration when using the custom QEMU arguments setting:

In UTM, the QEMU arguments are built on the fly when the VM starts. So to force UTM to include a set of configuration arguments even with the custom toggle enabled, go to file `/Managers/UTMQemuSystem.m` and in `startWithCompletion` add the necessary calls in an `else` block:
```objc
- (void)startWithCompletion(void (^)(BOOL, NSString * _Nonnull))completion {
    [self argsRequired];
     if (!self.configuration.ignoreAllConfiguration) {
         [self argsFromConfiguration];
+    } else {
+        // add args for drives and sharing because those are impossible to type
+        [self argsForDrives];
+        [self argsForSharing];
     }
     [self argsFromUser];
     [self startQemu: …];
…
```
