### ISSUE TITLE
Touchscreen input option does not work

### ISSUE THREAD

**Issue by Shawnjoseph2001** [utmapp/UTM#122]
The option to use a touchscreen as the input device in Android x86 4.3 and possibly other OS's does not work. A workaround is to use the trackpad input option.

**Comment by osy86** [comment]
I think touchscreen input will be a future option. But it requires client side support. I don't know if android x86 has it.

**Comment by cs-sugar** [comment]
There should be.

**Comment by Shawnjoseph2001** [comment]
If it does not work, the touchscreen support should be labeled as experimental or non-working within the app.

**Comment by osy86** [comment]
Sir the app is labeled as experimental.

**Comment by cs-sugar** [comment]
Emm. But I’m not a Sir.


| |
彩虹小糖
|
|
邮箱：abcd2890000456@126.com
|

签名由 网易邮箱大师 定制

On 03/10/2020 10:52, osy86 wrote:

Sir the app is labeled as experimental.

**Comment by osy86** [comment]
Replying to OP.

**Comment by ThatsNiceGuy** [comment]
The touchscreen input option does not work as expected in windows 10 with the SPICE drivers installed. I touch on screen and the input that the OS receives is completely inaccurate. Can provide a video if needed, but i feel this is an issue that should be fixed
