### ISSUE TITLE
qemu-system-aarch64: VCPU supports less PA bits (36) than requested by the memory map (40)

### ISSUE THREAD

**Issue by kuestess** [utmapp/UTM#1221]
**Describe the bug**
On an M1 Mac, `qemu-system-aarch64: VCPU supports less PA bits (36) than requested by the memory map (40)` error received when starting arm64 machine (specifically the Archlinux Arm VM from the gallery).

**Version**
2.0.14.  Was working without error under 2.0.13

**To Reproduce**
Start VM ('Force slower emulation even when hypervisor is available unchecked)

**Expected behavior**
Error not received, machine starts as usual.

**Additional context**
Seems to have been introduced with latest release (2.0.14), reverting to 2.0.13 solves.

**Comment by osy** [comment]
The machine properties gets populated automatically. You may have created the VM in a lower version. Try creating a new VM and importing your old drive.

**Comment by kuestess** [comment]
@osy Thanks for the quick response - that took care of it.  VM is much snappier now!
