### ISSUE TITLE
Vm crash on start

### ISSUE THREAD

**Issue by DonBo13127** [utmapp/UTM#1223]
When i start the virtual machine utm crash immediately... Can you help me please?

**Comment by rylyguy** [comment]
How did you install utm. That’s most likely the problem.

**Comment by DonBo13127** [comment]
I’ ve installed from iOS ninja

**Comment by rylyguy** [comment]
That’s it. That installs with the wrong type of certificate. Install it with altstore. Or if you’re jailbroken altstore+altdaemon.

**Comment by IIWare** [comment]
I hope I don't sound like promoting someone else, but you can also add the unofficial UTM repo, vishram1123.gitlab.io/utm-cydia if you don't know what UTM you can install from the repo, choose UTM, not UTM-Legacy, more info will be in the repo.

**Comment by Vishram1123** [comment]
But you should wait as at the moment the packages are broken and I haven't gotten around to fixing them... sorry

**Comment by rylyguy** [comment]
> I hope I don't sound like promoting someone else, but you can also add the unofficial UTM repo, thanks to @Vishram1123 for making the repo, the repo is: http://vishram1123.gitlab.io/utm-cydia if you don't know what UTM you can install from the repo, choose UTM, not UTM-Legacy, more info will be in the repo.

Yes but as you said it’s unofficial. I was just telling them the official way. And also they didn’t say if they are jailbroken or not.

**Comment by DonBo13127** [comment]
I have installed the official release now and i have other problem...
https://github.com/utmapp/UTM/issues/1225

**Comment by DonBo13127** [comment]
I have installed the official ipa and the vm always crash on start...

**Comment by KhazanGu** [comment]
I get the same issue, I registered a beta account and downloaded the AltStore beta version. 

I installed the UTM app via AltStore, I downloaded the android 9.0 UTM into the File app, unzip the image .zip file and add the config into UTM. It crashes every time when I activate the virtual machine.

I use an iPhone X on iOS 14.2 and without jailbreak.

**Comment by osy** [comment]
This is not a support forum, you can join the discord for help.

**Comment by Jiriceeeek** [comment]
Whats the discord?
