### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by DonBo13127** [utmapp/UTM#1225]
Hello How are you? Can you help me for to solve my problem please? 
![22DCB9EF-C35C-42FE-BB80-44B079F5F8D8](https://user-images.githubusercontent.com/73437211/101993315-d11eb900-3cb9-11eb-9bac-5650ef8b0b63.png)

**Comment by rylyguy** [comment]
This is what occurs every time you start up the app. You should be able to ignore it. But what device are you on. And what iOS version.

**Comment by DonBo13127** [comment]
I have iphone 6S Plus and ios 14.2

**Comment by rylyguy** [comment]
Oh. On a 6S you’ll have to do a tethered launch. So every time you want to open the app you’ll have to use a computer.

**Comment by DonBo13127** [comment]
Thanks but how i can do this with windows?

**Comment by rylyguy** [comment]
> Thanks but how i can do this with windows?
https://github.com/utmapp/UTM/pull/487/files/d8b7813fcf8922f524eb8bae2bc63d7c65087acc

**Comment by osy** [comment]
Not a bug and this is not a support forum. You can join the discord for help.
