### ISSUE TITLE
Remove port forward setting

### ISSUE THREAD

**Issue by ufolux** [utmapp/UTM#1226]
I want to remove my port forward setting, but I can't see any way to delete this config. 

![image](https://user-images.githubusercontent.com/4060594/102037488-3aa8df80-3e00-11eb-9675-1c34b806a5bd.png)

**Comment by osy** [comment]
Slide to the left and press delete.

**Comment by ufolux** [comment]
@osy Sorry I forgot to mention, I'm using the macOS version of UTM. The version number is 2.0.14 (14)

**Comment by osy** [comment]
Good catch I don’t think there’s a way.

**Comment by IIWare** [comment]
As far as I know, you can download the source code of utm, and then remove the setting by modifying the source code, and it's removed

**Comment by piyh** [comment]
Port forwarding is append only and there's no way to delete rules you add? This is a major functionality gap!

**Comment by Advait1306** [comment]
What did I just stumble upon, there's no way to remove a port forward? 😭

**Comment by ksingh-nvda** [comment]
Seeing the same issue with UTM v4.7.5. 

A hack that worked was to edit ~/Library/Containers/com.utmapp.UTM/Data/Documents/config.plist

**Comment by rivanjuthani** [comment]
so how do we actually delete this? the file ~/Library/Containers/com.utmapp.UTM/Data/Documents/config.plist is empty for me.

**Comment by jos-eph** [comment]
Confirmed that this is still an issue on 4.7.5 (118). My `config.plist` was also empty, and I had to restore an image from a Time Machine backup.

**Comment by rivanjuthani** [comment]
I just had to remove the network adapter and then add it again.

**Comment by jorenl** [comment]
FYI still having this issue, but my config was in  ~/Library/Containers/com.utmapp.UTM/Data/Documents/VM-NAME.utm/config.plist

**Comment by mtangoo** [comment]
can't believe such a basic thing (plus edit) is missing!
