### ISSUE TITLE
Cannot set up guest memory ‘pc ram’: cannot allocate memory

### ISSUE THREAD

**Issue by joker3492** [utmapp/UTM#1229]
Hi guys!
I’m new here.
I have installed UTM on my iPhone 8 jailbreak iOs 14.2.
When I star my VM Android 9 there is that error.
I attached screen for help me.
I’m sorry for my English 🥲
![9D198962-D8C0-467B-86DB-2D0006CC7434](https://user-images.githubusercontent.com/76042980/102204411-1f0a0b80-3eca-11eb-94aa-c1f2f455a054.png)

**Comment by IIWare** [comment]
Hi joker3492, welcome to github.
have you tried decreasing the ram?

**Comment by joker3492** [comment]
Yes! The app crash.

**Comment by osy** [comment]
Error is due to using too much RAM.
