### ISSUE TITLE
Start Virtual Machine Fail

### ISSUE THREAD

**Issue by barryblueice** [utmapp/UTM#124]
![B23999C9-A41F-4F67-8DE7-C95C5B4A079C](https://user-images.githubusercontent.com/44601454/76394946-47039600-63b1-11ea-9e0d-24927393838c.png)
When I open the virtual machine, it always says “qemu exited from an error”.

**Comment by osy86** [comment]
Your settings are wrong. There is a future plan for a more detailed error message. For now, you can run it attached to Xcode debugger to see the full error message in the console.

**Comment by barryblueice** [comment]
> Your settings are wrong. There is a future plan for a more detailed error message. For now, you can run it attached to Xcode debugger to see the full error message in the console.

Thanks, I reinstalled  the app, and this problem was work out. But when I want to start the VM, It will crash, and you have to shut down the process in the background or restart the iPad.
