### ISSUE TITLE
UTM doesn’t load?

### ISSUE THREAD

**Issue by noelbryan** [utmapp/UTM#127]
I am on ios 13.3, and on an iphone XR. I installed this through appcake, and it’s just a blank screen. I also tried to install it through my Mac, but it’s also just a blank white screen when I open the app. The app just never does anything.

**Comment by osy86** [comment]
Reboot your device, make sure you're running v0.4

**Comment by noelbryan** [comment]
> Reboot your device, make sure you're running v0.4

I did reboot it, and i’m running 0.4, the latest version.

**Comment by WindowsBetaTest** [comment]
You can try using altstore & altstore patcher to install UTM.

**Comment by noelbryan** [comment]
it’s working now after I did that, thanks!
