### ISSUE TITLE
Could not connect to 127.0.0.1: Connection refused

### ISSUE THREAD

**Issue by obbcth** [utmapp/UTM#130]
![localhost](https://user-images.githubusercontent.com/12216587/76540855-16615080-64c6-11ea-9353-22d222babfbe.jpg)

Input option : trackpad, server.
(This issue is from the another community, so I exactly don't know about this configuration. Maybe iPad Air 3 ios 13.4.)

**Comment by osy86** [comment]
Please post the non-working .utm file. I cannot reproduce it.

**Comment by obbcth** [comment]
https://cloud.naver.com/fileLink.nhn?filekey=UFos1eGssx%2BpXR6ogMTYCRE3WA%2BL0NTexfFC%2FSak20uYHoeyQaKGIl3ZTFQ44RwrYxRHB2rpfZ49SIPn1Db7Ogg%3D

Here it is. (Archived with zip, click 내려받기 to download.)

**Comment by obbcth** [comment]
[debug.log](https://github.com/utmapp/UTM/files/4362470/debug.log)
[config.plist.txt](https://github.com/utmapp/UTM/files/4362471/config.plist.txt)

Debug log and Config file.

**Comment by osy86** [comment]
debug.log looks corrupted. The utm boots fine on my device. Is this running on a jailbroken device?

**Comment by osy86** [comment]
Wondering if this may be a localization issue. Do you still get the error if you set your language and locale to english?

**Comment by obbcth** [comment]
I sent this message to him and will give you feedback when I receive an answer.
BTW I'm also a Korean, and I didn't have any problems.

+ Issued device is not jailbroken.

**Comment by obbcth** [comment]
He set language English and region US, and it does not solve the problem.

**Comment by obbcth** [comment]
He used Appcake to install UTM. So I think it duplicates #95. 
Now he tries to install app with new ways, so I will give you feedback when he finished it.

**Comment by osy86** [comment]
Is this still an issue?

**Comment by obbcth** [comment]
I'm also waiting his feedback. (link : https://cafe.naver.com/virtualroid/2035 )
My guess is, he used appcake to install UTM, so this bug is related with #95.
Still not works on ios 13.3 non-jailbroken using appcake installer (or somewhat cloud signing.)
