### ISSUE TITLE
Store and load VMs outside of the app sandbox

### ISSUE THREAD

**Issue by osy** [utmapp/UTM#132]
Use bookmarks to store VMs outside of the sandbox.

**Comment by cs-sugar** [comment]
> Use `UIDocumentBrowserViewController` to allow accessing a VM directly from iCloud. So you can sync a VM across multiple devices.

Not only iCloud，and the USB Flash Drive and the other Drives to read in the file app can also be used the vm.

**Comment by osy86** [comment]
Okay changed title

**Comment by professorIsaac** [comment]
I would be so beneficial for low memory users that you can run a vm without running out of internal storage especially using usbs so please do not mark it as low priority.

**Comment by osy86** [comment]
You are free to implement it and send a pull request. I am free to prioritize features I find interesting.

**Comment by cs-sugar** [comment]
The. UTM file can be selected by using the sharing function of the system. It can be started from the external memory by writing the cache. The UTM software folder and UTM temp folder are established in the UTM folder in my iPad directory of the file application. UTM software is used to save the local system. UTM temp is the cache of the external memory. After each shutdown or pause of the virtual machine, the pop-up "do you want to save this change?"? Please select xxx.utm to save "xxx.utm is an external UTM file. After selecting the UTM file,

**Comment by cs-sugar** [comment]
The. UTM file can be selected by using the sharing function of the system. It can be started from the external memory by writing the cache. The UTM software folder and UTM temp folder are established in the UTM folder in my iPad directory of the file application. UTM software is used to save the local system. UTM temp is the cache of the external memory. After each shutdown or pause of the virtual machine, the pop-up "do you want to save this change?"? Please select xxx.utm to save "xxx.utm is an external UTM file. After selecting the UTM file, or after shutting down the virtual machine，automatically delete TMP cache in UTM temp.

**Comment by cs-sugar** [comment]
In this way, it can be started in the external memory

**Comment by cs-sugar** [comment]
It's better to use iPad hard disk or other network disks as RAM to expand the ram of virtual machine to support the physical RAM owned by iPad or iPhone. You can add a floppy disk icon beside the + sign in the upper right corner of virtual machine to set the highest and lowest virtual ram. When the ram of virtual machine exceeds the ram of device, virtual RAM will be started automatically To prevent the device memory from running out of white screen, and add a button to force the use of virtual ram, but it needs to be marked that the system that forces the use of virtual RAM will run slowly, and it needs to be marked that after the forced use of virtual memory is turned on, other memory occupation will turn to disk occupation except JIT cache, which will be automatically cleared when it is turned off, and whether the switch is not turned on or off The virtual RAM disk usage is automatically cleared.

**Comment by conath** [comment]
Possibly related: #2451

**Comment by sarimarton** [comment]
Yes yes yes, I'm, too, waiting for this feature so much (sorry to bump it).
