### ISSUE TITLE
Spice graphics drivers cause BSODs in WinXP

### ISSUE THREAD

**Issue by arjanvlek** [utmapp/UTM#137]
I started getting bsods quite often when opening Firefox or installing a game. 

Turns out it’s caused by the QXL drivers (Installed from https://www.spice-space.org/download/windows/spice-guest-tools/spice-guest-tools-latest.exe). See the screenshots of Bluescreenview. 

![B184A3BC-E9AA-42F9-81E3-A5AEE436824B](https://user-images.githubusercontent.com/10106652/76679433-b6130180-65e0-11ea-9563-3e46481c71be.png)
![5E6B079E-92E0-447F-A02C-F884585F05C8](https://user-images.githubusercontent.com/10106652/76679436-ba3f1f00-65e0-11ea-85d4-ba8999f31575.png)

Video: https://share.icloud.com/photos/0UIYXD0_aREdv1eGLOU8mltWQ

**Comment by osy86** [comment]
I don't think this is unique to UTM. Seems like an issue with QXL/SPICE/QEMU. Maybe try lowering the memory and core count.
