### ISSUE TITLE
How to set up internet, audio, graphics driver

### ISSUE THREAD

**Issue by nfsvsgta** [utmapp/UTM#138]
Hey guys. M pretty much noob here but how can I get internet, audio, graphics to work. I saw some one running a 3D game on xp. Is it a driver we need?

**Comment by ThatsNiceGuy** [comment]
You will need to install the SPICE driver to get graphics working. Only thing is that transferring this file to the VM is kind of tedious due to shared folders not being functional yet.
As a workaround, I just made an ISO image of the driver so I could install it. Find it [here](https://drive.google.com/file/d/1zXKvn3AIPXS9IUFMwwtDPXdp2dKxRsGb/view?usp=drivesdk), then download and add it to your virtual machine in UTM just like you would add an operating system ISO

**Comment by nfsvsgta** [comment]
Super bro! I’ll try it out and let you know how it goes. Thanks !!!

**Comment by nfsvsgta** [comment]
its installed! I tried on windows 7 home premium 64 bit. The graphics driver are in but i think i need to install directx since when i run "purble place" it says that my graphics driver does not support 3d acceleration. also is there a seperate driver i need to install for audio?

**Comment by osy86** [comment]
Yes, 3D graphics acceleration is not supported. By qemu. So it will probably never be supported. The only games you can run are Software Rendering only games. If you see anything about OpenGL or DirectX you cannot run it.

**Comment by nfsvsgta** [comment]
Thanks. Still pretty cool regardless. Audio is still not up for some reason and the internet as well even though I think it installed something for internet

**Comment by ThatsNiceGuy** [comment]
> 3D graphics acceleration is not supported by QEMU

Oh man that explains why an OpenGL game I was trying to play was running at less than a frame per second

**Comment by obbcth** [comment]
I didn’t try, but WineD3D would help this problem. It works as a wrapper for Direct3D calls, and relies on OpenGL for the actual rendering job.
https://www.nongnu.org/wined3d/

**Comment by brunocastello** [comment]
> > 3D graphics acceleration is not supported by QEMU
> > Software Rendering
> 
> Oh man that explains why an OpenGL game I was trying to play was running at less than a frame per second

Why not apply this patch? https://github.com/kjliew/qemu-3dfx

I know this patch is far from complete, but I've read this has had some good results recently.

**Comment by osy86** [comment]
Because we’re not on linux.

**Comment by TheAwesome98-Real** [comment]
> Because we’re not on linux.

Using iPhone OS won’t make a difference

**Comment by tendajidevelopscrap** [comment]
> > > 3D graphics acceleration is not supported by QEMU
> > > Software Rendering
> > 
> > 
> > Oh man that explains why an OpenGL game I was trying to play was running at less than a frame per second
> 
> Why not apply this patch? https://github.com/kjliew/qemu-3dfx
> 
> I know this patch is far from complete, but I've read this has had some good results recently.

HOW DO YOU EVEN DOWNLOAD OR START WITH THIS THING

**Comment by TheAwesome98-Real** [comment]
> > > > 3D graphics acceleration is not supported by QEMU
> > > > Software Rendering
> > > 
> > > 
> > > Oh man that explains why an OpenGL game I was trying to play was running at less than a frame per second
> > 
> > 
> > Why not apply this patch? https://github.com/kjliew/qemu-3dfx
> > I know this patch is far from complete, but I've read this has had some good results recently.
> 
> HOW DO YOU EVEN DOWNLOAD OR START WITH THIS THING

bro what 💀
