### ISSUE TITLE
qemu-system-aarch64: -qmp tcp:localhost:4000,server,nowait: address resolution failed for localhost:4000: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by ak476565** [utmapp/UTM#1400]
**Describe the bug**
ubuntu-20.04.1-live-server-arm64
UTM  v2.0.14

**To Reproduce**
After configuring the virtual machine parameters, click start，then 

<img width="791" alt="截屏2020-12-18 上午9 05 27" src="https://user-images.githubusercontent.com/3871722/102562362-df356500-4111-11eb-802a-d0bfb48b2836.png">
<img width="886" alt="截屏2020-12-18 上午9 18 02" src="https://user-images.githubusercontent.com/3871722/102562401-f5dbbc00-4111-11eb-8c36-7b1d784b2138.png">
<img width="870" alt="截屏2020-12-18 上午9 18 28" src="https://user-images.githubusercontent.com/3871722/102562423-01c77e00-4112-11eb-9105-d2a8e8e87507.png">
<img width="889" alt="截屏2020-12-18 上午9 18 59" src="https://user-images.githubusercontent.com/3871722/102562463-1572e480-4112-11eb-89e5-92ff5e38615a.png">

 crash.

**Crash log**
qemu-system-aarch64: -qmp tcp:localhost:4000,server,nowait: address resolution failed for localhost:4000: nodename nor servname provided, or not known

Thanks a million！

**Comment by osy** [comment]
Please enable debug logging (QEMU -> Debug Log) and share the debug log.

**Comment by ak476565** [comment]
debug log:
Running:&nbsp; -L "/Volumes/UTM 1/UTM.app/Contents/Resources/qemu" -S -qmp tcp:localhost:4000,server,nowait -nographic -chardev pipe,id=term0,path=/var/folders/x2/w6zj71md4lsg7r7n78zhfgf40000gn/T/ubuntu.terminal -serial chardev:term0 -smp cpus=8,sockets=1,cores=8,threads=1 -machine virt-5.2,highmem=off -accel tcg -bios "/Volumes/UTM 1/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd" -device ramfb -boot order=d -m 1024 -name ubuntu -device qemu-xhci -device usb-tablet -device usb-mouse -device usb-kbd -drive if=virtio,media=disk,id=drive0,file=/Users/cyy/Documents/ubuntu.utm/Images/disk-0.qcow2 -device usb-storage,drive=drive1,removable=true -drive if=none,media=cdrom,id=drive1 -device virtio-net-pci,netdev=net0 -netdev user,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid D7468F7C-8066-4B90-889E-5A9E18502126 -rtc base=localtime
qemu-system-aarch64: -qmp tcp:localhost:4000,server,nowait: address resolution failed for localhost:4000: nodename nor servname provided, or not known







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "utmapp/UTM"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月18日(星期五) 上午10:13
收件人:&nbsp;"utmapp/UTM"<UTM@noreply.github.com&gt;;
抄送:&nbsp;"耀"<347049587@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [utmapp/UTM] qemu-system-aarch64: -qmp tcp:localhost:4000,server,nowait: address resolution failed for localhost:4000: nodename nor servname provided, or not known (#1400)





 
Please enable debug logging (QEMU -&gt; Debug Log) and share the debug log.
