### ISSUE TITLE
Clicks don’t work on ppc machine running Mac OS X 10.0

### ISSUE THREAD

**Issue by brunophilipe** [utmapp/UTM#145]
I am able to move the mouse but clicking doesn’t do anything. Installing the same image on QEMU on a macOS host works fine.

I built from master, and changed VGA mode from “qxl” to “std”. I’m not sure if that’s related. The ppc machine would not boot on “qxl” mode.

See: https://twitter.com/brunophilipe/status/1238817200317837314?s=21

**Comment by bryankeller** [comment]
The problem is that there's no delay between the click down and click up event. Instead of using a tap gesture recognizer, we should use touchesBegan and touchesEnded. A quick fix is to use a dispatch after to make the click up event happen a little bit later.

**Comment by brunophilipe** [comment]
I can confirm adding a `dispatch_after` call fixes this issue. Should I open a PR with this as a hot fix?

**Comment by pixelomer** [comment]
I made a simple tweak to fix this problem and add a few features. My implementation might not be the best but it does the job. [UTM-Patches on Github](https://github.com/pixelomer/UTM-Patches)

**Comment by pixelomer** [comment]
In my opinion, using `touchesBegan` and `touchesEnded` isn't a good solution, because as far as I know, there isn't a way to know whether a user is about to move the cursor or perform a click when `touchesBegan` is called.

**Comment by saagarjha** [comment]
I hope you can forgive me for asking, but why did you make what appears to be a Theos tweak instead of just a normal patch?

**Comment by pixelomer** [comment]
I wanted to get something working as soon as possible and I didn't want to wait 2 hours to build the dependencies.

**Comment by osy86** [comment]
FYI you don’t need to build it, you can download prebuilt artifacts for sysroot. If you submit a patch it’ll also get auto-built.

**Comment by saagarjha** [comment]
You can try using [the GitHub Actions build artifacts](https://github.com/utmapp/UTM#easy). Building the whole sysroot doesn't take that long either; it's like half an hour?
