### ISSUE TITLE
.img and .bin support 

### ISSUE THREAD

**Issue by professorIsaac** [utmapp/UTM#149]

**Comment by osy86** [comment]
Please explain?

**Comment by professorIsaac** [comment]
That img files can be used like iso files on UTM

**Comment by osy86** [comment]
Does it not work?

**Comment by professorIsaac** [comment]
No it doesn’t try yourself

**Comment by osy86** [comment]
You can add them to the vm. But depending on the file format qemu may or may not support it. There’s no standard for .img or .bin so you need to know the actual file format.
