### ISSUE TITLE
ARM64 VM error: No 'PCI' bus found for device 'virtio-gpu-pci'

### ISSUE THREAD

**Issue by siuying** [utmapp/UTM#153]
**Describe the bug**
For ARM64 machine, I get error "QEMU exited from an error: qemu -device virtio-gpu=pci: No 'PCI' bus found for device 'virtio-gpu-pci'

**To Reproduce**
1. Create a ARM64 based CPU and choose Pi 3. 
2. Start the VM. 

Look like I should not enable PCI GPU for pi, but I cannot find how to do it.

**Comment by siuying** [comment]
@osy86  thanks!

**Comment by siuying** [comment]
@osy86 now I get "-device rtl8139,netdev=net0: No 'PCI' bus found for device 'rtlk8139'"

**Comment by osy86** [comment]
I see, I will have to hide that arg as well.

**Comment by osy86** [comment]
You can disable network to get rid of the error. Also it seems like the raspi3 target is not stable and won't really work anyways.
