### ISSUE TITLE
UTM crashes when loading X?

### ISSUE THREAD

**Issue by kenan1099** [utmapp/UTM#159]
UTM crashes when loading GUI on AntiX 19.
256MB ram
10GB hdd
Live cd
All settings default.
[UTM.cpu_resource-2020-03-21-124054.zip](https://github.com/utmapp/UTM/files/4362646/UTM.cpu_resource-2020-03-21-124054.zip)

**Comment by osy86** [comment]
What device are you on? Is it jailbroken? Also your log isn't a crash log but a freeze log from a different time I think.

**Comment by kenan1099** [comment]
I’m on 13.3 jailbroken iPhone 7
Maybe it’s just a freeze?
Idk what causes it because sometimes it turns on sometimes not

**Comment by leeeboo** [comment]
I have the same problem.
iPad Pro 2020 12.9
App ver:0.7
iOS 13.4
Windows7 works good
Linux console works good
Linux GUI(Ubuntu & xorg on arch) crash(stack for a long time and iPad restart)

**Comment by osy86** [comment]
Still need a crash log or I can't do anything.

**Comment by osy86** [comment]
One of you should upload the .utm file that you're experiencing the issue in and directions for reproducing the crash. Otherwise this ticket will be closed.

**Comment by leeeboo** [comment]
> One of you should upload the .utm file that you're experiencing the issue in and directions for reproducing the crash. Otherwise this ticket will be closed.

I updated to 0.8. it works ok
