### ISSUE TITLE
Improved pointer support on iOS 13.4

### ISSUE THREAD

**Issue by saagarjha** [utmapp/UTM#160]
Since iOS 13.4 has improved cursor support, perhaps we should rethink some of the interactions if the user has a mouse or trackpad connected. For example, hiding the cursor and disabling some of the gestures (as they are now handled by the hardware) might be a good idea.

**Comment by osy86** [comment]
Is there any API to detect if a mouse is connected?

**Comment by saagarjha** [comment]
I don't think it's dropped yet. I wonder when the next Xcode beta will be out…

**Comment by itselijahciali** [comment]
I know that it's supposed to snap to buttons, so theoretically somebody could make a program to detect the Windows cursor status, and report it to the app, and the app places a control there. Of course, we could just wait for an API...

**Comment by osy86** [comment]
FYI #176 will track work supporting cursor inside the VM. This issue is for better handling for trackpad to navigate UTM.

**Comment by conath** [comment]
I implemented cursor handling in the VM list view, VM metal view toolbar and (for #176) the actual cursor movement. :)
