### ISSUE TITLE
Implement virgil3d support for GPU paravirtualization

### ISSUE THREAD

**Issue by osy** [utmapp/UTM#161]
https://virgil3d.github.io

**Comment by professorIsaac** [comment]
This only works with Linux so there is no need for now but it in the site it said they will support windows direct3d drivers so it could be enough for working on.

**Comment by osy86** [comment]
No offense but you’re not the project manager. Please refrain from commenting on various issues with your idea of what should or shouldn’t be done. It’s fine to suggest ideas but don’t go on multiple issues and pretend you have authority. If you were a contributor I would be more willing to accept suggestions and ideas.

**Comment by ExenalEurope** [comment]
Is this easy to implement ?

**Comment by osy86** [comment]
No it’s pretty freaking hard.

**Comment by professorUnknown** [comment]
Nobody appreciates devs these days opening a github issue is 1,000x easier than actually doing it.

**Comment by ExenalEurope** [comment]
There was this app ages ago Called "Exagear" it only translates API calls; there's no built-in emulator to convert x86 instructions for ARM processors. ExaGear is a paid emulator for Android that attempts to solve this problem, by adding an x86 emulator to a modified version of Wine. 

Does android just handle that stuff better than iOS?

**Comment by osy86** [comment]
WINE is a different thing. For one it only emulates Windows because it’s a high level emulator that intercepts Windows system calls. QEMU is a low level emulator that emulates an entire system (cpu, memory, disk drives, etc). You gain accuracy and flexibility and lose performance and specialized optimization (like D3D translation). If you want a HLE for iOS look at iSH which is like WINE but is Linux for iOS.

**Comment by ExenalEurope** [comment]
iSH is only a small linux distro with musl. Cant really emulate any Windows games on it. UTM is the closest to run games. I guess Ill wait for accelerated graphics support.

**Comment by Questandachievement7Developer** [comment]
I think HL 1 allows software rendering if i remembered correctly

**Comment by ExenalEurope** [comment]
Does UTM support OpenGL?

**Comment by osy86** [comment]
This is the last I’ll say on this because it’s off topic and I’m tired of dealing with people who quote from sources they absolutely do not understand. I used iSH as an example of what you can do with HLE. It’s the same concept as WINE but for Linux syscalls not Windows syscalls. It’s just an example of something that UTM cannot and will not ever do. Linux or Windows syscalls emulation. That’s why WINE can do 3D acceleration on Android/Linux. QEMU for macOS/iOS (and this is very important so read it carefully): _**does not emulate a GPU**_ and therefore cannot support D3D. If you have a game like half life that does not use GPU then yes it will work but nothing past the 90s use sw rendering anymore.

This topic of this issue if you cared to read it is to implement the apis to support GPU emulation. Which, as I’ve told you, is a lot of work.

**Comment by ExenalEurope** [comment]
"tired of dealing with people who quote from sources they absolutely do not understand"
There is literally one person who said something in this issue ticket who quoted once.

And yes, I understand it is hard work to implement apis to GPU emulation, but with joint effort it could be achieved. And I'm sure I'm not the only one who wants D3D Support on UTM.

**Comment by everythings-gonna-be-alright** [comment]
OMG. I can't run Hard Truck 2 on my iPhone without 3D accelerator support.
I almost was ready to say that my iPhone it's not useless thing.

**Comment by rylyguy** [comment]
If you really want 3D acceleration. I recall Osy saying to someone in the discord that thought it would be easy to implement. “Stop complaining and start coding my dude”

**Comment by HahaMeGoesBeLikeBRRRRRRRR** [comment]
> This only works with Linux so there is no need for now but it in the site it said they will support windows direct3d drivers so it could be enough for working on.

In the site? more like S I K E‌ ‌ ‌ T H A T S ‌ ‌ T H E ‌ ‌ W R O O O O O O O O N G ‌ ‌ N U M B E R ! OOOOOOOOHHHHHHHHHHHHHHHHHHHHHH

**Comment by osy** [comment]
Integrate changes from https://gist.github.com/akihikodaki/87df4149e7ca87f18dc56807ec5a1bc5

**Comment by akihikodaki** [comment]
Actually I implemented OpenGL support for ui/cocoa, and it does not allow to use egl-headless, which performs OpenGL operations and rasterizes frames for displays without OpenGL support, including SPICE used by UTM.

Fortunately it requires a few change to allow egl-headless work on macOS. Here is my change which I used to test Virgil 3D with Mesa swrast: akihikodaki/qemu@bba111b22e6fc9d8e98e9c9efc4d46d82ebb5c6c

Note that I used it with Mesa swrast. To enable hardware acceleration, you may have to modify `qemu_egl_init_dpy_surfaceless` to use ANGLE. It is just a experimental patch so please don't assume it just works.

**Comment by osy** [comment]
Thank you I will look into it!

**Comment by tkreind** [comment]
There's a convenient homebrew formula now that works in my testing. Not sure the changes have made it upstream but it should be possible to include this version early if not. [https://github.com/knazarov/homebrew-qemu-virgl](https://github.com/knazarov/homebrew-qemu-virgl)

**Comment by osy** [comment]
Changes implemented in v2.2. Some notes:

* egl-headless + ANGLE was pretty straightforward but I wasn't satisfied with the solution because it rendered offline to a framebuffer on GPU -> framebuffer is copied to the CPU -> CPU buffer is sent to SPICE client -> SPICE client renders it by copying it back to the GPU. Although this is the only way if running a VM remotely, the movement of data back and forth from GPU to CPU is unnecessary.
* On Linux, SPICE uses dmabuf to pass a pointer to GPU data so no copying was needed. On macOS we don't have dmabuf, but we have IOSurface which has a similar mechanism. ANGLE also supports rendering to IOSurface. So we added IOSurface rendering to QEMU's spice-display.
* In order to be compatible with SPICE libraries (without having to modify the APIs), we wrap IOSurfaceID into a file descriptor by passing it through a pipe. On macOS, we have to use `kIOSurfaceIsGlobal` to pass IOSurfaceID across process boundaries. On iOS, everything is in one process so that's not needed. A better solution would use mach ports or XPC but it would be a lot of work to integrate that into QEMU.
