### ISSUE TITLE
Copy words from macbook to iPad using shared clipboard with werid word sometimes

### ISSUE THREAD

**Issue by TangMonk** [utmapp/UTM#163]
**Describe the bug**
for example I copy the xp key "DP7CM-PD6MC-6BKXT-M8JJ6-RPXGJ" from mac to ipad, the first "DP7CM" comes to "DP&CM"

**To Reproduce**

1. copy "DP7CM-PD6MC-6BKXT-M8JJ6-RPXGJ"  from macbook
2. paste in UTM
3. it be comes  (screenshot)
![IMG_0006](https://user-images.githubusercontent.com/3498786/77274924-ffa2d100-6cf1-11ea-85d2-3495887cac70.PNG)

**Comment by osy86** [comment]
Oh I messed up the timing of the shift key.

**Comment by TangMonk** [comment]
Aha, this might shift key issue
