### ISSUE TITLE
[Question] How to get navigation bar back after hide?

### ISSUE THREAD

**Issue by TangMonk** [utmapp/UTM#167]
**Describe the Question**
I hide the top navigation bar in UTM, there is a notice alert message box shows to me, But I close the message box uncareful, So I did not see the message clearly. So, How can I get the navigation bar back?

**Comment by mthirdcool** [comment]
3 fingers swipe down

**Comment by mthirdcool** [comment]
swipe down with 3 fingers

**Comment by TangMonk** [comment]
> swipe down with 3 fingers

Thanks!
