### ISSUE TITLE
QMP server - Connection Refused bug.

### ISSUE THREAD

**Issue by fredyshox** [utmapp/UTM#172]
**Describe the bug**
Related to pull request that I'm currently working on #113 
https://github.com/utmapp/UTM/blob/c7ddf50e007a72c8bc719667d4afd9dfa86385fa/Managers/UTMVirtualMachine.m#L239-L255

When the code between `_qemu_system startWithCompletion:` and `_qemu connect`, executes quickly enough (in my case serial console connection don't take much time), `UTMJSONStream` will fail to connect with Connection Refused error, because it is happening before qemu manages to start QMP server. In my code I duct taped it using `NSThread sleep`, but it's not perfect solution 😄.

**Possible solution**
One possible solution is to design reconnection mechanism in `UTMJSONStream`. 
https://github.com/utmapp/UTM/blob/c7ddf50e007a72c8bc719667d4afd9dfa86385fa/Managers/UTMJSONStream.m#L53-L70
- Specify number of trials in `connect`
- Retry `_inputStream/_outputStream open`, after receiving `NSStreamEventErrorOccurred` and Connection refused `NSError` until number of trials is exceeded or `NSStreamEventOpenCompleted` is received.

**Comment by osy86** [comment]
Thanks this may also be the issue in #130

**Comment by osy86** [comment]
Apple's API really sucks here. Why can't they return an error immediately if the connection fails? The code becomes real messy if we have to implement some state to track "are we retrying connection".
