### ISSUE TITLE
Auto remove spam

### ISSUE THREAD

**Issue by spookyahell** [utmapp/UTM#1741]
Remove spam automatically.
Damn that would be nice...

**Comment by GetTheGuy66** [comment]
HowDareYou? YouAreSuchAFkn𝕔𝔲𝕟𝓽ForSayingThatNowGoHaveᔕᗴ᙭WithPrestonPlayz

**Comment by GetTheGuy66** [comment]
HahahaSpookyDislikedHisOwnCommentLMFAO

**Comment by spookyahell** [comment]
> HowDareYou? YouAreSuchAFkn𝕔𝔲𝕟𝓽ForSayingThatNowGoHaveᔕᗴ᙭WithPrestonPlayz

Bot say what?

**Comment by GetTheGuy66** [comment]
YourAȡίςķşùςķέŕ

**Comment by GetTheGuy66** [comment]
👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬👎🤬

**Comment by spookyahell** [comment]
> YourAȡίςķşùςķέŕ

Yo mama is what?
