### ISSUE TITLE
[Configuration] Delete VM

### ISSUE THREAD

**Issue by utmapp** [utmapp/UTM#18]
Support deleting a VM

**Comment by kylergibson** [comment]
Just in case you or someone is not aware, I believe that you can go into the files app->on my iPad -> UTM, and delete the vms from there. Maybe this is not the official way to do it, but it seems to work. I apologize if I’m wrong, but just trying to help.

**Comment by utsavo-afk** [comment]
does completely delete all files and storage associated with vm? im not clear on that and its not mentioned in docs
