### ISSUE TITLE
Support of vmware and virtualbox harddisks 

### ISSUE THREAD

**Issue by boy13epic** [utmapp/UTM#185]
Like vdi and vmdk and vhd

**Comment by boy13epic** [comment]
- [ ] 

1. 

-

**Comment by osy86** [comment]
Not supported by qemu. You can convert it to qcow2 on your computer. Google for instructions.

**Comment by ZeppLu** [comment]
> Not supported by qemu. You can convert it to qcow2 on your computer. Google for instructions.

On my macbook, qemu runs pretty well with vmdk
```
   -device virtio-blk,backend_defaults=on,drive=harddisk
   -drive id=harddisk,if=none,format=raw,file="/path/to/disk.vmdk",format=vmdk
```
