### ISSUE TITLE
Select network device to emulate

### ISSUE THREAD

**Issue by osy86** [utmapp/UTM#186]
We currently force `rtl8139` but it's not supported by all OS and targets. Implement a selector for all possible devices.

**Comment by obbcth** [comment]
A little bit far from this topic, adding a form to set DNS server can solve networking problems. (#49)
So users don't have to maunally change it in guest os.
https://wiki.qemu.org/Documentation/Networking
> You can specify the guest-visible virtual DNS server address with -netdev user,id=n0,dns=addr

![screen-6](https://user-images.githubusercontent.com/12216587/77912473-99a7e200-72cd-11ea-9242-36b9a3e12a77.jpg)
I recommend the way to implement as Limbo Emulator did.
