### ISSUE TITLE
The QEMU monitor of Windows 10(Version>1909)will display incorrect color when startup.

### ISSUE THREAD

**Issue by WindowsXAlpha** [utmapp/UTM#197]
My system is pc-i440fx-4.2.
 #80 slow problem seems to have been solved
It seems that there is no such problem in UTM v0.3

**Comment by osy86** [comment]
I'm not sure I understand the problem. Please attach a video.

**Comment by WindowsBetaTest** [comment]
please wait

**Comment by WindowsBetaTest** [comment]
[IMG_1601.zip](https://github.com/utmapp/UTM/files/4435287/IMG_1601.zip)

**Comment by osy86** [comment]
I'm not sure why this happens but it does not appear to be a UTM issue. If you run the same disk image on QEMU on OSX, you can probably see the same thing.

**Comment by osy86** [comment]
Closing due to issue not being in UTM.

**Comment by xXBannedXx** [comment]
For people who still have this issue, try reducing the hard drive space, it solved the issue for me. When I first used 50 GB I got this issue, but after I changed it to 15 GB it worked fine.
