### ISSUE TITLE
Add support for location tracking to increase background time

### ISSUE THREAD

**Issue by ntindle** [utmapp/UTM#201]
Using location tracking, you can keep UTM alive in the background, longer.

**Comment by osy86** [comment]
You can also use audio playback for unlimited background since we’re not playing by AppStore rules.

**Comment by Leask** [comment]
Location tracking is better because the audio playback API will result in conflict with other music apps. Really love this feature, I want to run a Linux in the background so I can finish all my works only on my iPad Pro.

**Comment by osy86** [comment]
Are you sure? I thought a silent audio track would not interfere?

**Comment by Leask** [comment]
Developers have to use the Background Audio API to keep their apps running in the background: https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/creating_a_basic_video_player_ios_and_tvos/enabling_background_audio . If you use this API to play audio, no matter how long the audio file is or event a silent audio file, iOS will let you monopolize the audio playback UI. If another app needs it, the previous app which using it has to release. So only one app can use Background Audio API at the same time.

**Comment by osy86** [comment]
I see, then location tracking it is.

**Comment by ntindle** [comment]
Or perhaps both with a selector? I’m not sure which would be better?

________________________________

**Comment by Leask** [comment]
> I see, then location tracking it is.

Can’t wait for the next milestone.

**Comment by osy86** [comment]
I'm trying to implement this right now and it seems like iOS really does not like the amount of memory usage in a background app. Even though it's fine in the foreground, it seems like the app gets killed for using that much memory in the background.

**Comment by ntindle** [comment]
@tbodt did you run into this issue?

**Comment by tbodt** [comment]
No, but I wouldn't be surprised if iSH has this problem and it doesn't typically show up because iSH doesn't typically use a whole lot of memory.

**Comment by osy86** [comment]
Actually, it might be because I had the debugger attached. I have the iPad in sleep mode without a debugger for a few hours now and it hasn't been killed yet.

**Comment by osy86** [comment]
So it does die after a while. Usually 10mins-1hour in

> Fatal RESOURCE_NOTIFY trigger for UTM [24326] (48000183333 nanoseconds of CPU usage over 56.00s seconds, violating limit of 48000000000 nanoseconds of CPU usage over 60.00s seconds)

So background tasks cannot hoard the CPU.
