### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by filfat** [utmapp/UTM#208]
Now that an AltStore version exists it would be great if github actions automatically builds and deploys a nightly version on each commit to master.

**Comment by osy86** [comment]
Bad idea. Why would unstable dev builds be seeded to people? Developers can side load it. Testers get beta and release builds just as God intends.

**Comment by filfat** [comment]
@osy86  I’d argue that nightly builds are an extremely common practice and actively promotes testing on upcoming version and newly implemented features resulting in the actual release being more stable.

Some examples of projects doing nightly builds:
  *  every alpine package under the /edge repos (the same goes for pretty much any other distro).
  *  reactos: https://reactos.org/getbuilds/.
  *  waterfall, paperspigot: https://papermc.io/ci/job/Paper/.
  *  node, npm, nextjs, react etc.
  *  or pretty much any other open source application/package/service.

On top of that, proper git practice disallows unstable commits from ever entering the master branch, they should be placed under a “dev” or “dev-$version” branch (which should also provide nightly builds).

Yes, you should actively discourage most users from using the nightly builds by labeling them as such, highly unstable experimental builds for gathering feedback and bug reports.

I also have a hard time seeing a how a god has anything to do with how semver or releases works. Provided he exists he’s probably too busy with the immense amount of prayers related to COVID-19 right now to care about how you release software.

**Comment by saagarjha** [comment]
> On top of that, proper git practice disallows unstable commits from ever entering the master branch, they should be placed under a “dev” or “dev-$version” branch (which should also provide nightly builds).

I should note that this is *one* proper Git practice, not the *only* proper Git practice.

**Comment by osy86** [comment]
Probably it’s possible to implement an unstable repo. But then we also need to automatically release after every commit. Frankly I don’t think it’s worth doing considering the fact that releasing unstable builds only increases work for me as more people will run into known issues.
