### ISSUE TITLE
Black screen for aarch64 with 2.0.15

### ISSUE THREAD

**Issue by Nanoc-ice** [utmapp/UTM#2080]
A12x iPad 2018 iOS v14.2 
UTM v2.0.15
Installed with paid developer cert using iOS App Signer
X86_64 work fine as long as shared directory is not toggled on for linux VMs(otherwise black screen also, but don’t know if that is different from this issue).

On aarch64 VM (Debian from the VM repository and the Arch ARM vm that I have added a GUI elements to), when booting it doesn’t show the initial boot screen, instead the screen remains black.  NOTE: setting the sharing doesn’t seem to matter with this architecture.

Debug log:
[debug.log](https://github.com/utmapp/UTM/files/5726077/debug.log)

**Comment by jdjingdian** [comment]
running on Xs Max，iOS 14.3，UTM v2.0.15，aarch64 don't work the same as you.

**Comment by HelloIAmTheBoiCalledSeGuymkszxg** [comment]
ok, ҭђἔᾗ ṩҭὄῥ вἷҭƈђἷᾗʛ and ɠ๏ ɠєt д ʟіғе, you fꝁn Ɲɠ卂!

**Comment by osy** [comment]
This is an issue with the old UEFI firmware included with the prebuilt vm. Have you tried waiting a long time in the black screen? I think once it boots past UEFI it should still work. I’ll try to add an exception for old UEFI firmware to work if needed.

**Comment by Nanoc-ice** [comment]
Can the old UEFI firmware be replaced with a newer version ... without having to (re)create the VM?

**Comment by FuocomanSap** [comment]
> Can the old UEFI firmware be replaced with a newer version ... without having to (re)create the VM?
> 
> Also, waited 30 minutes on the black screen to see if it would get past the UEFI boot and no go.

Same for me.
iPad 2020
IOS: 14.3

**Comment by leonboe1** [comment]
Same here.

**Comment by HahaMeGoesBeLikeBRRRRRRRR** [comment]
*Satan has joined the chat*

**Comment by LuigiPiccoli17** [comment]
Same here

**Comment by haeteyhuo54LOLXDHAHA** [comment]
ĐɆ₳Ⱡ ₩ł₮Ⱨ ł₮ łĐłØ₮₴!

**Comment by Vishram1123** [comment]
I had the same problem with PowerPC Mac99. iOS 14.2

**Comment by 0h-no-oo-oo-her-0b-r11-ne-is-behind-you** [comment]
ˢᵗᶠᵘ ᶠᵏⁿᶦᵍ ᵇᵗᶜʰ ʸ'ᵃˡˡ ʰᵃᵛᵉ ⁿᵒ ˡᶦᶠᵉ >:(

**Comment by wolfoo2931** [comment]
Have the same problem, any chance to publish 2.4.2 for shipping this fix?
Thanks for this awesome software.
