### ISSUE TITLE
[Enhancement] To this repo, add an issue that has rules that tells people what to do when there are spam issues.

### ISSUE THREAD

**Issue by IIWare** [utmapp/UTM#2085]
yesterday, I saw that there were 500+ spam issues with bad words and a few people commented on spam issues and one made an issue about the spam thread, but then you deleted all the spam issues, and then the few people that commented has been accidentally banned from this repo, so to let others know what to do with the spam issues there could be a pinned issue for this repo (made by you) and then the pinned issue contains rules to do when there are spam issues, so that no one will get banned by accident, this issue is just an enhancement to this repo, thanks.

**Comment by osy** [comment]
https://github.com/osy/HaC-Mini/issues/340#issuecomment-734376188
