### ISSUE TITLE
Gallery site for virtual machines

### ISSUE THREAD

**Issue by kkk669** [utmapp/UTM#2086]
Currently, https://getutm.app/gallery/ is used in the following lines.

https://github.com/utmapp/UTM/search?q=https%3A%2F%2Fgetutm.app%2Fgallery%2F

However, that page returns 404. I believe it should be https://getutm.app/vms/.

**Comment by osy** [comment]
No, it’s not implemented yet. There’s a lot of higher priority work to be done.

**Comment by kkk669** [comment]
Okay, I understand. Then, should I close this issue? Thanks.

**Comment by osy** [comment]
No keep I’ll keep it open until it’s done.

**Comment by HahaMeGoesBeLikeBRRRRRRRR** [comment]
Gallery site? more like G A L L E R Y   S I K E

**Comment by 0sy-is-ssucch-a-s-st-puid-idio-t-l-l-l** [comment]
Gallery site? more like G A L L E R Y ‌ ‌ S I K E ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !

**Comment by thammarith** [comment]
I opened a small PR to solve this issue (#2248)

**Comment by kkk669** [comment]
Hi @thammarith, your PR is probably wrong because @osy said https://getutm.app/vms/ and https://getutm.app/gallery/ were different things in https://github.com/utmapp/UTM/issues/2086#issuecomment-749444215. Moreover, you've missed my first comment because there are three files that includes https://getutm.app/gallery/.

**Comment by thammarith** [comment]
@kkk669 Oh, I see now. Thank you for your correction. I'll close my PR.

**Comment by osy** [comment]
Gallery is done and /vms/ is now deprecated.
