### ISSUE TITLE
Executables in the released IPAs do not have the executable bit set

### ISSUE THREAD

**Issue by pixelomer** [utmapp/UTM#209]
Probably not a huge issue but I wanted to point it out.

What the released IPAs look like: <img width="707" alt="released" src="https://user-images.githubusercontent.com/37103802/78231105-fe845780-74da-11ea-8607-dcf41a833803.png">

What I would've expected: <img width="738" alt="expected" src="https://user-images.githubusercontent.com/37103802/78231115-00e6b180-74db-11ea-8086-034c8ffae6dd.png">

**Comment by osy86** [comment]
Isn’t this true for every IPA?

**Comment by osy86** [comment]
What problems are you experiencing?

**Comment by pixelomer** [comment]
> Isn’t this true for every IPA?

As far as I now, no, every IPA needs to have the executable bit set for its executables.

> What problems are you experiencing?

The only problem I experienced is that I can't move the app as-is into /Applications or use AppSync to install it on a jailbroken device. This issue doesn't seem to affect sideloading tools or AltStore.
