### ISSUE TITLE
Prevent creating something with an invalid name

### ISSUE THREAD

**Issue by obbcth** [utmapp/UTM#210]
We should block creating images with an invalid name like "abc/def.img".

Also happens on creating VMs.

**Comment by osy86** [comment]
Error checks and input validation in config setting in general is needed.

**Comment by morrowa** [comment]
This doesn't appear to be fixed. I tried to name a VM "macOS w/Nix" and it failed to create saying it couldn't find `Nix.utm`.

**Comment by osy** [comment]
It might be reintroduced in a new change. Can you make a new issue?

**Comment by morrowa** [comment]
Filed as #4385 
Thanks!
