### ISSUE TITLE
Specify directory for VM(s) on macOS

### ISSUE THREAD

**Issue by ankushnarula** [utmapp/UTM#2108]
Each time I create a VM, it defaults to storing the `.utm` package in the `~/Documents` directory.  I see no setting to alter this default.  Am I missing something here?

Also, I've tried moving the `.utm` package elsewhere.  But when I re-open from Finder, it appears to re-create itself in  `~/Documents`.  

Normally this wouldn't be a problem, but I use iCloud for my Documents folder and it is suboptimal to have the VM being copied up to iCloud as it is modified.

Being able to specify a default directory for VM storage would be very helpful - as would the ability to move VMs.

**Comment by ThatIsGetterThatsTheBestOne10293** [comment]
your andrupka's 𝑓𝑐,𝑘!𝑢𝑛𝑔 𝑐𝑙𝑜𝑛𝑒!!!

**Comment by osy** [comment]
Right now it has to run from ~/Documents. In the future, it will be sandboxed and it will run from its own sandbox and #1205 is tracking an enhancement that will allow running from anywhere outside the sandbox. The ~/Documents limitations is only temporary.
