### ISSUE TITLE
App ceases up on iOS 14.3

### ISSUE THREAD

**Issue by fhildfshjkdsaiojsga** [utmapp/UTM#2142]
**Describe the bug**
When you use iOS 14.3, UTM does not start the VM. It happens even on new VM’s without any disks. Tested with an Android 4.4 VM and a blank VM.

**To Reproduce**
1. Use UTM on iOS 14.3
2. Play any VM.

**Debug log**
I cannot pull a debug log because the app ceases up when you press play.

**Upload VM**
Happens with all VMs, no need to upload a VM file here.

**Comment by haeteyhuo54LOLXDHAHA** [comment]
𝚜𝚑.𝚞𝚝-𝚞.𝚙 𝚊𝚗𝚍 𝚐𝚘 𝚐𝚎𝚝.;𝚊,𝚕𝚒𝚏𝚎,!𝚗𝟷𝚐𝚐𝚊!

**Comment by osy** [comment]
Did you install with AltStore? Are you jailbroken? What model is your device and do you know if it has a chip A12 or newer?

**Comment by fhildfshjkdsaiojsga** [comment]
AltStore, non jailbroken, iPad Pro 12.9 inch (3rd generation) Wi-Fi Only.

**Comment by Vishram1123** [comment]
I had this same problem when updating from 2.0.14 to 2.0.15, so you have to export the machine as a .UTM with the button in the bottom center, convert that .UTM to .zip, extract it, delete the old VM, and create the new vm with the same configuration, replacing the drive.

**Comment by fhildfshjkdsaiojsga** [comment]
You can also restart your device to see if a restart fixes it.

**Comment by 0h-no-oo-oo-her-0b-r11-ne-is-behind-you** [comment]
ˢᵗᶠᵘ ʸ'ᵃˡˡ ᶠᵏ.ᶦⁿ ⁿ.ᵍᵃˢ 👎👎👎👎👎🤬🤬🤬🤬🤬🤬

**Comment by osy** [comment]
@fhildfshjkdsaiojsga did you test with 2.0.16?

**Comment by woswos** [comment]
UTM works perfectly for me on non-jailbroken iOS 14.3 at A14. I installed it using AltStore.
