### ISSUE TITLE
Add some new function advise.

### ISSUE THREAD

**Issue by cs-sugar** [utmapp/UTM#216]
Please add an external memory to start the virtual machine function and the external memory read-write function. Make use of the external memory function of IOS 13. The UI interface is similar to that in the video, and the prompt interface after connecting the U disk is similar to that in the picture. Is that ok? If it can be realized, I'm very honored.
[advice.zip](https://github.com/utmapp/UTM/files/4425341/advice.zip)

**Comment by boy13epic** [comment]
good idea sugar

**Comment by cs-sugar** [comment]
En，but do not jailbreaken. Yes？

**Comment by cs-sugar** [comment]
Do not jailbreaken and implement these functions.

**Comment by osy86** [comment]
Not possible due to iOS sandbox restrictions.

**Comment by cs-sugar** [comment]
Emm

**Comment by cs-sugar** [comment]
> Not possible due to iOS sandbox restrictions.
I think it can be implemented with file application permission of IOS 13 without breaking the original sandbox mechanism.

**Comment by cs-sugar** [comment]
> Not possible due to iOS sandbox restrictions.

I think it can be implemented with file application permission of IOS 13 without breaking the original sandbox mechanism.

**Comment by osy86** [comment]
That’s tracked in #132
