### ISSUE TITLE
Add support for unjailbroken devices 

### ISSUE THREAD

**Issue by boy13epic** [utmapp/UTM#218]

**Comment by cs-sugar** [comment]
I can't jailbroken my devices.

**Comment by boy13epic** [comment]
me too

**Comment by boy13epic** [comment]
Im 13.3.1

**Comment by cs-sugar** [comment]
Im 13.4.5 (17F5034c) the beta software.

**Comment by cs-sugar** [comment]
In fact, it's OK. You only need the permission of file application similar to IOS 13.

**Comment by cs-sugar** [comment]
The virtual machine can read the external device and start the external device without prison break.

**Comment by cs-sugar** [comment]
However, this function cannot be implemented in IOS 12 and below systems.

**Comment by cs-sugar** [comment]
Because there is no permission to read the external USB device.

**Comment by cs-sugar** [comment]
I'm sorry for saying so much.

**Comment by osy86** [comment]
Please read https://getutm.app/install/
