### ISSUE TITLE
Enable virtfs on macOS host

### ISSUE THREAD

**Issue by tiiiecherle** [utmapp/UTM#2184]
Thanks for this really nice project.

It would be nice if virtfs could be enabled in the next build for macOS as it helps a lot sharing folders to linux guests with p9 mounts.

Thanks

**Comment by osy** [comment]
Can be implemented once support is in QEMU

**Comment by tiiiecherle** [comment]
o.k., thanks ;)

**Comment by 4ntoine** [comment]
Any update on that? Any suggestion on how to share the dir with max performance between host macOS or Linux and guest os Linux (supported by UTM)?

**Comment by 4ntoine** [comment]
Getting "virtfs support is disabled" message for UTM 2.2.4

**Comment by omfdzg** [comment]
Hi, sadly I have same issue. And It's really important for me.

**Comment by amboar** [comment]
I'm on an M1 under Monterey using UTM `3.2.4 (58)`. Instead of `fsdev support is disabled` I get `qemu-aarch64-softmmu: -virtfs local,path=tmp/share,mount_tag=share,security_model=mapped-xattr: cannot initialize fsdev 'share': failed to open '/tmp/share': Operation not permitted`.

**Comment by thouseef** [comment]
> I'm on an M1 under Monterey using UTM `3.2.4 (58)`. Instead of `fsdev support is disabled` I get `qemu-aarch64-softmmu: -virtfs local,path=tmp/share,mount_tag=share,security_model=mapped-xattr: cannot initialize fsdev 'share': failed to open '/tmp/share': Operation not permitted`.

I'm also getting the same error on M1 using UTM `3.2.4`: 
qemu-aarch64-softmmu: -virtfs local,path=/Users/thouseefh/workspace,security_model=none,mount_tag=workspace: cannot initialize fsdev 'workspace': failed to open '/Users/thouseefh/workspace': Operation not permitted

**Comment by zachlatta** [comment]
Hi there, just to chime in. It looks like as of March 2022, virtfs support is included in the Homebrew version of QEMU: https://github.com/Homebrew/homebrew-core/commit/a70f2f6967e4459a921a947ab5060d3af8034853

I wonder if this these patches could be added to the QEMU version included with UTM to enable virtfs?

**Comment by Atemu** [comment]
@zachlatta these shouldn't be necessary as UTM already ships QEMU v7.

**Comment by zachlatta** [comment]
@Atemu: it looks like Homebrew ships with QEMU v6 with some patches that make it virtfs work - https://github.com/Homebrew/homebrew-core/commit/a70f2f6967e4459a921a947ab5060d3af8034853#diff-5fe005c786b1e905434aaa353962cc6a58b0a6431e7f9a785076f0ad5f277a3dR54-R108

**Comment by Atemu** [comment]
@zachlatta 

>     # The following patches add 9p support to darwin.  They can
>     # be deleted when qemu-7 is released.

https://github.com/Homebrew/homebrew-core/commit/a70f2f6967e4459a921a947ab5060d3af8034853#diff-5fe005c786b1e905434aaa353962cc6a58b0a6431e7f9a785076f0ad5f277a3dR54-R55

**Comment by zachlatta** [comment]
Ah... I'm sorry. Thank you for the correction!

**Comment by elmehdibadaoui** [comment]
Solved ! by an easy steps On UTM 

1. Close the emulator with problem
2. Select the emulator on UTM interface
3. On the shared directory (Clear) and Save
4. Re-choose an Shared directory (in my case Download)
5. You can now Run your emulator

<img width="968" alt="image" src="https://github.com/utmapp/UTM/assets/34130096/536c465f-845b-45d1-a1d7-e8c399482c61">
