### ISSUE TITLE
[Feature request] Use PreferenceLoader bundle to instead of Settings.bundle

### ISSUE THREAD

**Issue by Halo-Michael** [utmapp/UTM#2185]
For jailbroken devices, installing UTM to /Applications will invalidate Settings.bundle. But we can add a PreferenceLoader bundle to replace it. Both of them store preference files in the /private/var/mobile/Library/Preferences path, so the main program does not need to be changed.

**Comment by Halo-Michael** [comment]
I don't know how to modify the labels so...

**Comment by osy** [comment]
Honestly the more I deal with it the more I'm disliking everything about jailbroken app install and management. I may just revert the whole Cydia support. Does AltStore + AltDaemon work for everyone or is there really a need for Cydia?

**Comment by Halo-Michael** [comment]
A device can only install three apps signed by free account at the same time. Altstore and a jailbreak app has already occupied two locations. In addition, appsync does not work on iOS14, so installing it in /Applications is the best choice.

**Comment by osy** [comment]
The problem with /Applications is that in addition to the preference issue there's also: no integration with Files app, VMs not backed up automatically or deleted automatically when uninstalled, permission issues with ~/Documents on some devices, etc. I'm not really keen to have to work around all these issues and more as they arise. Probably the ideal solution would be to use AppSync for iOS 14 (there's unofficial forks).

**Comment by Halo-Michael** [comment]
Add entitlement
<key>com.apple.private.security.no-container</key>
<true/>
<key>com.apple.security.iokit-user-client-class</key>
<array>
	<string>AGXDeviceUserClient</string>
	<string>IOHDIXControllerUserClient</string>
	<string>IOSurfaceRootUserClient</string>
</array>
Will change NSHomeDirectory() from sandbox to /var/mobile (or /var/root, depends on the binary owner), this may be convenient for users to manage data without the need to search in the path composed of random uuids. In addition, you can write a postrm/prerm script to automatically delete the stored virtual machine and other files after uninstalling the program (if necessary)

**Comment by Halo-Michael** [comment]
Please refer to:
https://github.com/Samgisaninja/SuccessionRestore/blob/master/Template/DEBIAN/prerm

**Comment by Halo-Michael** [comment]
> Please refer to:
> https://github.com/Samgisaninja/SuccessionRestore/blob/master/Template/DEBIAN/prerm

This ensures that archived files are deleted when the program is uninstalled, but not when the program is updated

**Comment by osy** [comment]
UTM now uses AppSync so this is no longer needed.
