### ISSUE TITLE
Can‘t worked on iPadOS14.3,A12

### ISSUE THREAD

**Issue by Longtianmu** [utmapp/UTM#2194]
Describe the bug
My device is iPad mini 5 with iPadOS14.3(18C66),A12 chip
The app is signed and can be opened
But it says that my device isn’t supported.
The Version of UTM is 2.0.16

To Reproduce
1. Click the UTM app

No VM can be started

**Comment by osy** [comment]
You’re using altstore?

**Comment by Longtianmu** [comment]
> You’re using altstore?

Actually I use a sign app from China

**Comment by osy** [comment]
That doesn’t work. Read https://getutm.app/install/
