### ISSUE TITLE
"Could not connect to AltServer" when installing it onto my iPad

### ISSUE THREAD

**Issue by yanzhang0219** [utmapp/UTM#221]
iPadOS version: iOS 13.4.5 developer beta
iPad Pro 10.5-inch
macOS version: 10.15.3

![image](https://user-images.githubusercontent.com/11582667/78413927-86975980-75ce-11ea-8a3b-6920639a6446.png)

Thank you.

**Comment by osy86** [comment]
This is not a UTM bug. Please contact AltServer's developers.
