### ISSUE TITLE
Adopt UITouch pointer events to improve pointer interaction

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#223]
According to Apple's Docs, the pointer support API will change  "in a future release", as outlined in [UIApplicationSupportsIndirectInputEvents](https://developer.apple.com/documentation/bundleresources/information_property_list/uiapplicationsupportsindirectinputevents?changes=latest_minor&language=objc):

> UIApplicationSupportsIndirectInputEvents is a compatibility affordance to ease the adoption of indirect input for a UIKit application. In a future release, this new behavior will become the default and this key will no longer be consulted.

We should consider implementing this API already, which would additionally make scrolling and two finger tap gestures possible (#214). This requires touch screen mode from #195, which has been implemented, so we're all good to go on this one.

**Comment by osy86** [comment]
I cannot figure out how `UIEventTypeScroll` works. I was not able to get it in `gestureRecognizer:shouldReceiveEvent` or find it in `touchesBegan:withEvent` for both physical mouse scroll wheel and two finger swipe gesture on touchpad.

**Comment by conath** [comment]
To recognize pointer scrolling, you need to use UIPanGestureRecognizer and set its allowedScrollTypesMask to UIScrollTypeMaskAll. [Hard to find in the docs!](https://developer.apple.com/documentation/uikit/uipangesturerecognizer/3538978-allowedscrolltypesmask?changes=latest_minor&language=objc)
