### ISSUE TITLE
Can't install MacOSX on UTM

### ISSUE THREAD

**Issue by none-null-blank** [utmapp/UTM#226]
I imported the dmg file. Then I start the virtual machine. But MacOS X can't always find the dmg file (the disk must be selected to install MacOS X), but minivmac can import the file to MacOS 7.

**Comment by obbcth** [comment]
Qemu doesn't support dmg, so you should convert it by img or iso.

**Comment by none-null-blank** [comment]
But when I import the img file, MacOS also cannot find any disk

**Comment by none-null-blank** [comment]
UTM version:0.7
