### ISSUE TITLE
Gallery: Windows 7 template uses wrong system type

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2274]
The Windows 7 template on the gallery uses the 1996 PC system. It should be the `Standard PC (Q35 + ICH9, 2009) (alias of pc-q35-3.2)` system instead.

**Comment by osy** [comment]
Not just the template maybe q35 should be the default for all x86 vms? Currently I use the “pc” config which is the 1996 one. That’s also the default qemu uses without any additional args.
