### ISSUE TITLE
Cannot import image

### ISSUE THREAD

**Issue by Andrupka** [utmapp/UTM#2275]
When I try importing 1 image i get this error. All other images import just fine
<img width="1012" alt="Снимок экрана 2021-01-19 в 16 57 59" src="https://user-images.githubusercontent.com/74910987/105044447-cbb24c80-5a77-11eb-80b2-e4d065e406d3.png">
Intel iMac, UTM 2.0.18

**Comment by IIWare** [comment]
Rename the file, see if that works.

**Comment by osy** [comment]
It’s a bug where if you make a new image or import and don’t save then then next time you try to make the same file it’ll show this. I’ll fix it next update but yeah renaming it works too.

**Comment by conath** [comment]
As a temporary workaround, @Andrupka you can remove the ghost image file with the following steps:
- open Finder and use the ⇧ ⌘ G Go to Folder… command
- paste `~/Library/Containers/com.utmapp.UTM/Data/Documents` and click **Go**
- right click on the VM file that shows the error and select **Show package contents**
- click Images folder and delete the image file from there

**Comment by Andrupka** [comment]
thanks!!! all replies helped

**Comment by Andrupka** [comment]
Wait, I did not do any of these steps, but it somehow imported! WTF?
