### ISSUE TITLE
Default units to Gigabytes

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2278]
I believe UTM would be more approachable if storage and RAM units would be presented in GB by default.

**Comment by osy** [comment]
Maybe for storage but for RAM I think MB is fine because we support older OS with 256MB or 512MB of RAM.

**Comment by osy** [comment]
For adding storage, maybe a dropdown with MB/GB? And automatically changing the value when the units change?

**Comment by conath** [comment]
> Maybe for storage but for RAM I think MB is fine because we support older OS with 256MB or 512MB of RAM.

That‘s true. Maybe we can leave the slider to user MB internally and set the default to 1024 MB. Then make the text field automatically change units from GB (default) to MB when the slider is dragged to lower than 1024 MB.

> For adding storage, maybe a dropdown with MB/GB? And automatically changing the value when the units change?

I like that idea!

**Comment by osy** [comment]
I have default RAM at 512MB because it’s the most compatible for all devices.
