### ISSUE TITLE
[iOS] Return to Home Screen after a guest powers off

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2279]
Whenever a guest VM is powered off in UTM on iOS, the app exits to the home screen. This impractical for several reasons:
- it looks to the user as if UTM has crashed when it has in fact exited without error
- need to relaunch the app every time to test different VM configuration
- limits use of UTM in Split View because UTM exiting causes iPadOS to go back to the home screen
- the app still appears in the app switcher despite it actually not running anymore (least important point)

The very first of these points can be addressed by calling `[UIApplication suspend]` instead of `exit(0)`. This results in a graceful animation to the Home Screen. UTM may then call `exit(0)` when in the background. 

Code example [from StackOverflow](https://stackoverflow.com/a/17802404/4236245):

```objc
-(void)doExit
{
        // animate to home screen
        UIApplication *app = [UIApplication sharedApplication];
        [app performSelector:@selector(suspend)];

        // wait 2 seconds while app is going background
        [NSThread sleepForTimeInterval:2.0];

        // exit app when app is in background
        exit(0);
    }
}
```

Resolving the issue entirely, meaning returning to the VM list after the VM powers down, seems more challenging to implement. Currently when a VM is started, a new ViewController [takes over](https://github.com/utmapp/UTM/blob/b943d1a9d4ef7bb0d387982272209ca20f5fcd87/Platform/iOS/UTMDataExtension.swift#L65) the key `UIWindow` and (as far as I can tell) no reference is kept to the VM list view. 

So to implement going back either a `NavigationController` of sorts must be introduced to be able to navigate back, or the VM list view must be re-created after the VM powers down and a new `UIWindow` created that shows the list.

**Comment by osy** [comment]
Due to #6 there's no way to start a second VM in the same address space. But I can try to implement the graceful exit.
