### ISSUE TITLE
Improve keyboard event handling in iPadOS 13.4

### ISSUE THREAD

**Issue by brunocastello** [utmapp/UTM#228]
EDIT: I accidentally added the bug label. I am not sure how it happened and I am not sure how to remove it.

**Describe the bug**
When using the iPad Pro Smart Cover Keyboard (or even the iOS screen virtual keyboard), some games on MSDOS 6.22 don’t recognize the keyboard keys in certain situations. For example, MicroProse’s F1GP (1991), the keys work naturally within the menu screens, but when I go to race, the game simply does not recognize the keys to control the car (A, Z, < and >). I can’t play DOOM either, the character does not move because the game also does not recognize the controls (but within the menu screens they do). It’s a strange behavior and I believe it has something to do with the low level instructions or something like that?

Also, in certain situations, while I am typing, one key or another gets stuck forever and the VM crashes. 

Another strange situation: If I do multitasking (example: UTM and Safari). While UTM is on background (not seen) and I am on Safari typing or clicking, if I go back to UTM it repeats by itself the same moves (at least on my VM, running MSDOS 6.22 & Windows 3.11, it did while I was on Windows). I cannot stop it, I have to force close it and hard reboot the iPad.

Mouse issues? I use the MSDOS MOUSE.COM to provide a PS/2 mouse for DOS level games, it works for all games except Carmen Sandiego. Windows has its own. The only issue is that after attempting to run Carmen Sandiego, the game is playable, but without mouse. And after playing it, the mouse stops working for all games and also Windows. I have to reboot to have it working again. I changed the mouse.com version various times, I have even tried CuteMouse (a lightweight version), but the same issues reappear. It does not happen on DOSBox and iDOS2/DOSPad for iOS. While on my VMWare VM, just running the game crashes the VM and forces reboot.

And on an unrelated note, just for comparison, I do not get these problems while using iDOS2/DOSPad on iPad Pro. Except, the mouse issue 

But for other several (good) reasons, I’d like to use UTM instead of iDOS2. These issues made me think they have something to do with the implementation of keyboard and mouse for UTM. I’d suggest to look on iDOS2/DOSPad (litchie’s github) for how its implemented. I know its very old code (iOS 10), but it still works as of today and as intended.

**To Reproduce**
Just run a VM with MSDOS 6.22 and Windows 3.11. Games tested: Where In The World Is Carmen Sandiego (1991 version), DOOM, MicroProse F1 Grand Prix, and MicroProse Grand Prix 2.
**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/4435791/debug.log)

**Upload VM**
Well, my VM has a 2GB hard disk so I do not have any viable place to upload it.

**Comment by brunocastello** [comment]
The situation has improved with the latest version released. It can now recognize the keypress, but it cannot recognize the long keypress yet. For example, in GPRIX game, I need to hold the A key to accelerate the car. It sees I'm doing that, but apparently thinks I'm not pressing long enough to accelerate? Other example is DOOM - I need to repeatedly press a key to move the character in the game instead of holding the key.

Both iPad Smart Cover Keyboard and Apple Magic Keyboard used, both showed the same behavior. I can see progress, though not there yet.

**Comment by brunocastello** [comment]
The issue worsened with the Release Candidate version. I have a MSDOS 6.22 + Windows 3.11  VM, after the boot when I get to the command prompt, the keyboard no longer works. It's the apple smart cover keyboard btw. I'll try to roll back to previous version to find out if it comes back.

**Comment by osy86** [comment]
Can you open a new issue? I think it’s a problem only in legacy input mode.

**Comment by brunocastello** [comment]
> Can you open a new issue? I think it’s a problem only in legacy input mode.

Sure. Give me a few minutes and I'll do it.

**Comment by osy86** [comment]
Also attach the .utm so it’s easier for me to reproduce the issue.
