### ISSUE TITLE
Option to enable right mouse click using control or command + click

### ISSUE THREAD

**Issue by tiiiecherle** [utmapp/UTM#2287]
It seems right mouse click on a (single click configured mouse) is not possible on macOS host using qemu guests.

I am able to right click using my touchpad on the macBook with a two-finger-click.

It would be nice to have an option to enable a "more macOS native way" to have a right click available inside the guests using control or command + left click.

If it is not possible to implement as a feature option it would be nice to know how to enable this with a qemu option. I was looking around and could not find a solution.

Thanks

**Comment by osy** [comment]
Right now right click is handed by macOS native APIs. I assume you have a magic mouse? If so you can set up right click in system preferences just like how you can set up right click for trackpads.

**Comment by tiiiecherle** [comment]
Thanks, this option is disabled on purpose as we all use control Keyboard click + mouse click to have a right mouse click.
It would be nice to see this implemented as option or always enabled as this works on all macs regardless if using mouse, internal or external trackpad. 
Can this be enabled with a qemu option?
Thanks

**Comment by tiiiecherle** [comment]
@osy Thanks a lot. 
Works in Windows10.
Unfortunately it does not work in Archlinux guest. Two Finger Trackpad click works but ctrl+click does not work.
Thanks for reopening the issue and looking into it again.

**Comment by osy** [comment]
Is this console mode?

**Comment by tiiiecherle** [comment]
@osy ok, I just re-checked. It is working everywhere but on the right click on the desktop in openbox to bring up the menu.
It works in every app using openbox but it does not work using it clicking on the desktop.
I use the same vdi image in virtualbox and it works without re-configuring anything.
I had a look at the configuration and the options. Everything seems fine.
Do you think it's something you can fix?
I searched and tried different solutions but could not get it to work to click on the desktop and bring up the openbox menu.

**Comment by tiiiecherle** [comment]
I case my previous post was not clear. In general the right mouse click using control+ click works in linux.
But it does not work bringing up the openbox menu when clicking on the desktop.

**Comment by tiiiecherle** [comment]
Two-Finger click on the trackpad on the desktop works and brings up the openbox menu.

**Comment by osy** [comment]
I suspect what’s happening is the Ctrl+Right click is being inhibited by open box. I translate Ctrl+left click to ctrl+right click but because I can’t stop the Ctrl event from firing before the left click is translated, you get Ctrl+right click. Is there anything you can do on the VM to check raw mouse+keyboard inputs and see if this is the case? If so I don’t know if there’s a good way around it without delaying keyboard events.

**Comment by tiiiecherle** [comment]
Sorry, I don't know how to check that. Would it help to just use command + click instead of control + click? This is the way it works on virtualbox.

**Comment by osy** [comment]
It doesn’t change the fact that Linux will see both the keyboard key AND the mouse click. I would advise you to configure Linux to ignore the Ctrl key. I’m sure there’s someone out there who’s done that.

Cmd key probably works because it happens to be ignored by default. Anyways all this is outside the scope of UTM/QEMU and I advise you seek help from openbox support community.

**Comment by tiiiecherle** [comment]
I searched through a lot of possibilities tonight and could not find a solution after hours. Would it be a lot of work to duplicate the control + click option and also allow command + click? I think a lot of people are used to use this who used virtualbox before.
I would really like to see if this is working. Thanks a lot.
Appreciating all the great work.

**Comment by osy** [comment]
Sorry I’m not going to make a new feature for every edge use case. This is definitely possible to do on Linux side. You can ask for help there.
