### ISSUE TITLE
TempleOS doesn't work

### ISSUE THREAD

**Issue by Xe** [utmapp/UTM#2289]
**Describe the issue**
I tried to run [TempleOS](http://templeos.org) and Adam crashed while it was trying to prompt for the I/O port number of the CD drive.

**Configuration**
* UTM Version: Version 2.0.19 (19)
* OS Version: macOS 11.1
* Intel or Apple Silicon?  Apple Silicon

![Screen Shot 2021-01-27 at 3 53 20 PM](https://user-images.githubusercontent.com/529003/106052632-c8dadb80-60b7-11eb-926f-e1e30d305dad.png)

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/5882938/debug.log)

**Upload VM**
No need, you can replicate this with the .iso file from TempleOS.org

Bizarrely enough this works fine on the iPad version.

**Comment by osy** [comment]
Ah I found out the issue. You need to use `pc` instead of `q35` (which was the new default machine type).
