### ISSUE TITLE
qemu: Property ‘.vmport’ not found

### ISSUE THREAD

**Issue by obbcth** [utmapp/UTM#229]
ios 13.3 non-jailbroken, 0.8 ver using Altstore to install.
Set architecture PowerPC (with mac99), and error occurs. (Not happens on x86-64)

[debug.log](https://github.com/utmapp/UTM/files/4435844/debug.log)

+ Maybe related to #130 because of the last line of debug.log

**Comment by osy86** [comment]
Fixed in cf6268ee8920289d01d5d23361d1c125d54f10d9
