### ISSUE TITLE
When launching Debian 10.4 (Xfce) with console mode, UTM crashed

### ISSUE THREAD

**Issue by Zireael775333728** [utmapp/UTM#2291]
UTM 2.0.19
IOS 14.3
https://mac.getutm.app/gallery/debian-10-4-xfce

**Comment by cuj** [comment]
The macOS UTM Virtual machines gallery is for mac, and the VMs are configured for it to work with the macOS version of UTM only.

**Comment by osy** [comment]
That’s literally not true.

**Comment by osy** [comment]
@Zireael775333728 Can you try v2.0.18 and let me know if you see the same issue?

**Comment by Zireael775333728** [comment]
@osy Yes, same issue. Also when I enable the directory sharing of Debian 10.4 (Minimal) and turn it on, UTM crashed. Both 2.0.19 and 2.0.18

**Comment by osy** [comment]
Can you post a crash log? If you don’t know how refer to the issue template you deleted when you created the issue.

**Comment by Zireael775333728** [comment]
@osy It doesn't make a crash log, the latest one is three days ago
[UTM.wakeups_resource-2021-01-28-142152.ips.synced.txt](https://github.com/utmapp/UTM/files/5899433/UTM.wakeups_resource-2021-01-28-142152.ips.synced.txt)

**Comment by Zireael775333728** [comment]
@osy I found that my utm.ipa is resigned by @js-john , so today I tried the github-released utm.ipa (both 2.0.19 and 18), it also crashed.  (js-john fixed an issue on cpu multicore and names it 2.0.20)

**Comment by Zireael775333728** [comment]
@osy And here's the debug log of the two issues. (Under 2.0.18)
[debug_xfce_command_mode.log](https://github.com/utmapp/UTM/files/5899450/debug_xfce_command_mode.log)
[debug_minimal_directory_sharing.log](https://github.com/utmapp/UTM/files/5899451/debug_minimal_directory_sharing.log)

**Comment by js-john** [comment]
> @osy I found that my utm.ipa is resigned by @js-john , so today I tried the github-released utm.ipa (both 2.0.19 and 18), it also crashed. (js-john fixed an issue on cpu multicore and names it 2.0.20)

I just pulled the latest code for and archived an ipa. I didn't fixed that bug, osy did.
