### ISSUE TITLE
UTM Deletes disk images/iso files from a VM before a warning message pops up.

### ISSUE THREAD

**Issue by cuj** [utmapp/UTM#2294]
**Describe the issue**
UTM seems to be deleting disk images from a virtual machine before a warning message pops up, that means that no matter what button I click on in the warning message (yes) (no) it deletes disk images anyways.
here is a video describing the bug:

https://user-images.githubusercontent.com/66434686/106258539-0150f580-622f-11eb-8834-5373f06fca9f.MP4

**Configuration (required)**
* UTM Version: 20.1.9
* OS Version: 13.6.1
* Device Model: iPhone X (iPhone10,6)
* Is it jailbroken: yes. (name jailbreak used)? checkra1n.
* How did you install UTM? using cydia (cydia.getutm.app)

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here.

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the bottom of the configuration options (or at the top of the `QEMU` page) is `Debug Log`. Turn it on and save the VM. After you experience the issue, quit the VM and re-launch UTM. Open the VM settings again and select `Export Log...` and attach it here.

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by osy** [comment]
So the popup says

> Do you want to **also** delete the disk image data? If yes, the data will be lost. Otherwise, you can create a new drive with the existing data.

Meaning that if you press No, then the data will stay but the drive link (for QEMU) will be removed. You can then create a new drive and select that same image. Yes, it's confusing I know and for this exact reason, the iOS 14 UI fixes this and makes it less confusing.

**Comment by cuj** [comment]
@osy maybe the bug could be fixed for iOS 13 users who jb without computer.

So if the user decides to delete the disk image, a message box pops up without the disk image being removed from the list of disks of a vm.

If the user clicks on (yes), the disk image gets deleted and removed from the list of disks.

If the user clicks on (no), nothing will happen to the disk image.

I hope this bug can be solved for iOS 13 users who wants to jb without computer.

**Comment by osy** [comment]
Sorry as announced before there will not be any updates to the old UI as it is not supported. I agree it was confusing but that’s why I redesigned it for iOS 14.
