### ISSUE TITLE
Can not get debian netinst image after clicking install grub menu

### ISSUE THREAD

**Issue by dbz2k** [utmapp/UTM#2295]
**Describe the issue**
The iso boots, and shows the grub menu, and one you hit the enter button there is just a black screen with like a blinking cursor. It never makes it further than that.

ISO USED: https://cdimage.debian.org/debian-cd/current/arm64/iso-cd/debian-10.7.0-arm64-netinst.iso

**Configuration**
* UTM Version: 2.0.18
* OS Version: 11.1 
*  Apple Silicon: M1 

**Crash log**
No Crash Log

**Debug log**

**Comment by osy** [comment]
Can you try using console mode? It may not have the right drivers.

**Comment by osy** [comment]
Closing since it is an issue with the guest OS.
