### ISSUE TITLE
Where is the Disk Image?

### ISSUE THREAD

**Issue by XP-Luna** [utmapp/UTM#2298]
Hallo community,

I just created a new virtual machine and I want to move the .dmg-file into another directory, but I can´t find it. Where is it located?

XP-Luna

**Comment by conath** [comment]
The VMs are stored in `~/Library/Containers/com.utmapp.UTM/Data/Documents/`. You can right click the `.utm` file and click "Show Package Contents" to see the contained files (configuration property list and `Images` folder with the disk images).

To quickly get to a VM's `.utm` file in Finder, open UTM and right click (control-tap or two finger tap on Trackpad) on a VM in the list. Then click Show in Finder.

**Comment by XP-Luna** [comment]
Thank you very much!

**Comment by artnattapong** [comment]
can we move the standard config of this directory to other places.

thank you

**Comment by conath** [comment]
@artnattapong This would require significant development efforts. Please create a new Issue with the feature request template and describe your use case in detail. Thanks!

**Comment by Danathar** [comment]
Has anybody tried moving the vm image and then soft-linking to it at the new path?

**Comment by conath** [comment]
@Danathar As of the latest UTM, moving VMs to other locations is a feature. Right click the VM and select “Move…” https://github.com/utmapp/UTM/releases

**Comment by shufanhao** [comment]
@conath thank you. That works. 

Why somtimes I didn't find move option. I do see move option once. 
<img width="565" alt="image" src="https://user-images.githubusercontent.com/11540660/216742732-4c55eee7-1623-4123-9b1f-d585c4d2aa35.png">

**Comment by conath** [comment]
Maybe this VM has already been moved?

**Comment by justinclift** [comment]
As a data point, for UTM 4.3.5 (onwards?) the folder which images are kept in now appears to be `~/Library/Containers/UTM/Data/Documents/`.

Slightly different, but confusing if you're not aware and go looking for it.

**Comment by MDanihy** [comment]
~/Library/Containers/UTM/Data/Documents/ doesn't have the virtual saved there either.  Must have changed again for 4.4.5

**Comment by MDanihy** [comment]
Another annoying aspect is if I remove a virtual it doesn't seem to delete the actual drive.  My HD drive is filling up and I cannot find where these things are stored.

**Comment by justinclift** [comment]
@MDanihy For the "hard drive is filling up" situation, you could instead look for a tool that shows what part of the drive is using the most disk space.

~~If nothing else works, then even repeated use of `sudo du -sh * .[a-z]* .[A-Z]* | grep G | sort -n` from the root directory onwards should tell you what directories are using the most space.~~

Use [gdu](https://github.com/dundee/gdu) for this.  It's available in Homebrew: https://formulae.brew.sh/formula/gdu

**Comment by xerc** [comment]
PATH @ MacOS 14.4 UTM 4.5.3  `~/Library/Containers/com.utmapp.UTM/Data/Documents/`

**Comment by stinder91** [comment]
I have 4.5.4 UTM and the path is under ~/Library/Containers/com.utmapp.UTM/Data/Documents/Virtual Machine.utm/Data/

**Comment by hcguersoy** [comment]
I'm on macOS 15.2, running UTM 4.6.4 and there is no directory `~/Library/Containers/com.utmapp.UTM` but `~/Library/Containers/com.utmapp.QEMUHelper`. This doesn't contain any VM.

**Comment by justinclift** [comment]
@hcguersoy As a data point, on my M1 Mac Mini it has both of those directories:

```
$ ls -la ~/Library/Containers/com.utmapp.*      
/Users/jc/Library/Containers/com.utmapp.QEMUHelper:
total 64
drwx------@   4 jc  staff    128 27 Dec 13:12 .
drwx------  389 jc  staff  12448 29 Jan 14:57 ..
-rw-r--r--    1 jc  staff  30204 27 Dec 13:12 .com.apple.containermanagerd.metadata.plist
drwx------@  12 jc  staff    384 12 Sep 19:48 Data

/Users/jc/Library/Containers/com.utmapp.UTM:
total 80
drwx------@   4 jc  staff    128 29 Jan 20:18 .
drwx------  389 jc  staff  12448 29 Jan 14:57 ..
-rw-r--r--    1 jc  staff  37391 29 Jan 20:18 .com.apple.containermanagerd.metadata.plist
drwx------@  12 jc  staff    384 12 Sep 19:28 Data
```

The `com.utmapp.UTM` one has the VM in it, at least judging by the disk usage of that directory:

```
$ du -sh ~/Library/Containers/com.utmapp.*
 32K	/Users/jc/Library/Containers/com.utmapp.QEMUHelper
 17G	/Users/jc/Library/Containers/com.utmapp.UTM
```

17G matches up with the single VM I have on this Mac Mini. :smile:

**Comment by fsc-eriker** [comment]
Could this be documented somewhere? I was unable to find it in the UTM documentation.
