### ISSUE TITLE
BSOD with error code 0x000000A5 BIOS ACPI error

### ISSUE THREAD

**Issue by XP-Luna** [utmapp/UTM#2299]
Hello again,

I just wanted to install Windows XP, but every time I get a BSOD with the error code 0x000000A5. I tried different ways and settings and I also tried to download the package on getutm.app. I´m using a M1 MacBook Air. Thanks a lot.

XP-Luna

**Comment by fuding** [comment]
me too

**Comment by XP-Luna** [comment]
Is there no solution to this? It also makes no diffenrence if you use XP x64 or x86.

**Comment by osy** [comment]
Can you try changing the emulated system to q35 from pc?

**Comment by XP-Luna** [comment]
Changed it from the standard q35 to q35 2.10 and it seems to work now, thank you!

**Comment by osy** [comment]
I updated https://github.com/utmapp/vm-downloads/releases/download/windows-template/windows-xp-x64-utm.zip with the working config.

**Comment by Liam314839** [comment]
in x64 edition, set system to "i440fx (pc)", disable usb, force ps/2 controller, and set cpu type to core 2 duo
