### ISSUE TITLE
[UTM] Crash in rebuildVertices

### ISSUE THREAD

**Issue by osy86** [utmapp/UTM#23]
Sometimes the app will crash in
```
        [_texture replaceRegion:region
                    mipmapLevel:0
                      withBytes:(const char *)_canvasData + (NSUInteger)(rect.origin.y*_canvasStride + rect.origin.x*pixelSize)
                    bytesPerRow:_canvasStride];
```

**Comment by realmayus** [comment]
Is there any workaround? Does this only happen with specific OSes?

**Comment by osy86** [comment]
The workaround is to restart. It’s a software bug, it just needs to be fixed.

**Comment by haveamission** [comment]
Restart the app, or the machine?

**Comment by osy86** [comment]
App first, then if you run into #32 the device

**Comment by The-SamminAter** [comment]
Restarted the app, problem #32 still occurred.
Restarted the device, re-jailbroke, problem #32 still occurred.
