### ISSUE TITLE
Switch control + click for right mouse click to VM based, not global

### ISSUE THREAD

**Issue by tiiiecherle** [utmapp/UTM#2300]
Hey,

thanks for the new feature here
[https://github.com/utmapp/UTM/issues/2287](https://github.com/utmapp/UTM/issues/2287).

For everyone who is looking for a solution, I found one regarding linux to use control + click or command + click as right mouse click in a linux guest. Perhaps it can be added to a wiki...

1    install xbindkeys and xdotool

2   create `~/.xbindkeysrc`
# using command
```
"sleep .05 && xdotool keyup Super_L && sleep 0.05 && xdotool click 3"
  Mod4 + b:1
# using control
"sleep .05 && xdotool keyup Control_L && sleep 0.05 && xdotool click 3"
  Control + b:1
```

3   testing
`xbindkeys -v`

4 running
`xbindkeys &`

Unfortunately using control+click does not work as long as the global option "Hold control for right click" is activated in UTM.

As this was my first intention when opening the other feature request it would be best and most flexible to make the option available as of per VM in the "Input" Section and not globally for all VMs.

That would be great and solving all problems with Linux and Windows guests.

Thanks a lot.

**Comment by osy** [comment]
As stated in the other issue, the use case is limited so the feature request is rejected.
