### ISSUE TITLE
Blue Screen when installing Windows 8.1 or 10

### ISSUE THREAD

**Issue by hellojsna** [utmapp/UTM#2303]
**Describe the issue**
A clear and concise description of what the issue is. **Windows 8.1 and 10 installer keep showing BSOD
IRQL_NOT_LESS_OR_EQUAL**
<img width="1312" alt="Screenshot 1" src="https://user-images.githubusercontent.com/49427963/106995594-92414700-67c2-11eb-8612-bce347318493.png">
<img width="1136" alt="Screenshot 2" src="https://user-images.githubusercontent.com/49427963/106995602-966d6480-67c2-11eb-8395-89794c38a727.png">

**Configuration**
* UTM Version: **2.0.20**
* OS Version: **macOS Big Sur 11.2**
* Intel or Apple Silicon? **Intel**

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open Console.app, go to `Crash Reports`, and find the latest entry for either QEMU, QEMUHelper, or qemu-\*. Right click and choose `Reveal in Finder`. Attach the report here.

**Debug log**
```
Running:  -L /Users/jsna/Desktop/UTM.app/Contents/Resources/qemu -S -qmp tcp:127.0.0.1:4000,server,nowait -spice port=4001,addr=127.0.0.1,disable-ticketing,image-compression=off,playback-compression=off,streaming-video=off -cpu host -smp cpus=12,sockets=1,cores=6,threads=2 -machine q35, -accel hvf -accel tcg,tb-size=2048 -vga qxl -global PIIX4_PM.disable_s3=1 -global ICH9-LPC.disable_s3=1 -boot order=d -m 8192 -soundhw ac97 -name "Windows 10" -device usb-ehci -device usb-tablet -device usb-mouse -device usb-kbd -drive "if=ide,media=disk,id=drive0,file=/Users/jsna/Library/Containers/com.utmapp.UTM/Data/Documents/Windows 10.utm/Images/disk-0.qcow2,cache=writethrough" -drive "if=ide,media=cdrom,id=drive1,file=/Users/jsna/Library/Containers/com.utmapp.UTM/Data/Documents/Windows 10.utm/Images/Win10_20H2_v2_Korean_x64.iso,cache=writethrough" -device rtl8139,netdev=net0 -netdev user,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid C417730B-E2BE-4DB3-90D1-85B0711F853D -rtc base=localtime
libqemu-x86_64-softmmu.utm.dylib: warning: '-soundhw ac97' is deprecated, please use '-device AC97' instead
libqemu-x86_64-softmmu.utm.dylib: warning: global PIIX4_PM.disable_s3=1 not used

```

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by hellojsna** [comment]
I also tried Windows 7 from gallery
but it was same.
<img width="1070" alt="Screenshot 3" src="https://user-images.githubusercontent.com/49427963/107000651-958d0080-67cb-11eb-94ad-114629ad2c93.png">

with error code: 0x0000000A

**Comment by Andrupka** [comment]
My own win7 install worked fine, then the wait cursor became yellow from blue and then started bsoding on boot :(

**Comment by Andrupka** [comment]
Same

**Comment by osy** [comment]
Can those of you running into this problem try changing the system from "q35" to "pc" and see if it's the same?

**Comment by steveharman** [comment]
Same here.  Tried changing System to "pc" and it made no difference.

**Comment by fooozhe** [comment]
same

**Comment by conath** [comment]
Same for me. Windows 10 x64 version 20H2, ISO straight from Microsoft.

**Comment by mariobrostech** [comment]
Same issue installing Windows 7, 8.1, and 10 using all original ISOs from Microsoft

**Comment by conath** [comment]
It seems to be Hypervisor-related. I tried installing Windows 10 x64 version 20H2 from ISO twice with identical setup, except one time I used the TCG emulator ("Force Slow Emulation") and the other time I used the HVF (Hypervisor Framework). Install worked fine with the former but crashed with the Blue screen with HVF.

**Comment by mariobrostech** [comment]
Hi @conath,

I tried this with Windows 7 and ended up with a black screen following the installation. It does, however, seem to get further into the install process before the VM blanks out, so it seems that your hypervisor theory seems to, at minimum, make the installation get a bit further than it otherwise would.

**Comment by conath** [comment]
This issue has been superseded by #2368 (that one contains more up to date info).
