### ISSUE TITLE
SATA Drive Interface

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2305]
Please add the SATA option to disk drive interfaces.

**Comment by Vishram1123** [comment]
ACHI (SATA) is the default option when using a q35 machine. It will show as IDE, but QEMU will treat it as SATA.

Source: [https://stackoverflow.com/questions/48351096/how-to-emulate-a-sata-disk-drive-in-qemu](https://stackoverflow.com/questions/48351096/how-to-emulate-a-sata-disk-drive-in-qemu)

**Comment by conath** [comment]
Indeed, SATA is the default interface for q35 machines in _QEMU_. However, the way UTM generates its QEMU parameters means that the drive interface is IDE even for q35 machines (no AHCI controller device is added at all). This is consistent with the UTM drives UI, which has IDE as the default interface (and no SATA option at this time).
![Screenshot of Windows 7 Device Manger from UTM VM showing IDE controller and hard drive](https://user-images.githubusercontent.com/12073163/107572914-265d4500-6bed-11eb-9568-a11e7b94e5a2.jpeg)

**Comment by Vishram1123** [comment]
Oh, I didn't think about that. For now, however, you could use delete the drive from the UTM GUI and point directly to the drive like so: `-drive id=disk,file=IMAGE.img,if=none -device ahci,id=ahci -device ide-drive,drive=disk,bus=ahci.0`

**Comment by conath** [comment]
That's a good workaround, thanks for the hint! To use it on iOS it needs to be adapted (because we can't point to the image file directly). Here's a little guide:

To use SATA instead of IDE, choose "none" interface when you configure the drive, then go to QEMU tab and look at the generated `-drive` parameter. For a VM with just one drive, it will read 
```text
-drive
if=none,media=disk,id=drive0,file=…
```
Note the part after `id=`, in this case it's `drive0`. We can use that to attach this drive to the VM with a SATA port.

First we add this line as new argument at the bottom:

`-device ahci,id=ahci`

This adds an [AHCI](https://en.wikipedia.org/wiki/Advanced_Host_Controller_Interface) device to the VM, effectively adding SATA ports. Now we can connect the drive to this SATA port. Add another new argument:

`-device ide-drive,drive= drive0,bus=ahci.0`

See how we used the same `drive0` as noted earlier. If you're using multiple drives, you need to change this and also change the `bus=ahci.0` to `bus=ahci.1` or `bus=ahci.2` or `bus=ahci.3`… 

If you type the arguments correctly, your VM will now see the virtual disk as a SATA drive. Note that when I tested it with a 1996 PC running a previously installed copy of Windows XP, I encountered repeated BSOD during boot. I am not sure if the problem is the 1996 PC machine type, Windows XP or that I didn't install with this configuration.

**Comment by Vishram1123** [comment]
That workaround works on macOS as well! Ingenious

**Comment by osy** [comment]
@conath I've looked into it some more and it does seem like q35 transparently remaps if=ide to SATA https://bugzilla.redhat.com/show_bug.cgi?id=946993

I've tried it by changing from 'pc' to 'q35' and seeing in device manager the drive listed under a SATA controller. Are you sure you don't have any extraneous options that might be changing this?

I was in the process of adding explicit support for SATA but it gets messy really fast because you have 6 SATA channels and you have to manually map the drive to each one. Then if you have > 6 SATA drives, you have to create a new controller... Quickly this becomes a lot of code. I'm not sure the use case justifies the work if Q35 defaults to SATA.

**Comment by conath** [comment]
Oh dear, you are entirely correct. I was mistakenly assuming that my Windows 7 32 bit VM is using the Q35 system. It's actually set to the 1996 system, so it has the IDE controllers. I have edited my comment above to correct this. Since creating this issue I have installed a q35 VM and can confirm that it uses the AHCI controller by default.

So now that we know for sure that q35 machines use the AHCI controller, we have a mismatch between the UI and what actually gets generated for the virtual machine hardware. And we have different behavior for both machines despite the same drive parameters. And, what if somebody wants to use IDE for a drive in a Q35 system?

**Comment by osy** [comment]
From what I linked it seems like that’s the intended behaviour. So it’s still technically IDE it’s just over a SATA bus.

**Comment by conath** [comment]
I have read the linked thread now and I believe I understand it. `q35` uses IDE via SATA (AHCI). `pc` uses IDE. 

Is it possible to use true SATA drives in QEMU? Without AHCI?

**Comment by osy** [comment]
I’m not sure but if performance is the issue you should use virtio with the drivers included in the spice tools installer which is a paravirtualized driver.

**Comment by brunocastello** [comment]
You should use -device ide-hd instead of -device ide-drive.

**Comment by conath** [comment]
That is true, note that this thread dates to before `ide-drive` was [removed(https://github.com/qemu/qemu/commit/b50101833987b47e0740f1621de48637c468c3d1#diff-ee6ad545edcf7a23d20c14c2df7248d849a40fa7950bd405b6a058e5649f577a) from QEMU. UTM now generates `ide-cd` and `ide-hd`.

**Comment by brunocastello** [comment]
Yeah, my fault. Oh wait, ide-cd? now that is something I didn't see. Thank you!

Anyway, this doesn't solve his issue, Snow Leopard boot still stops at ACPI error. Since he's using a hackintosh method to boot (custom bios and OpenCore) I assume that he needs an ACPI table (probably a DSDT) to work around. However, I can't remember how, because it has been nearly seven years since my last Chimera/Clover hackintosh, and I have never used OpenCore before.

**Comment by aliagowani** [comment]
I am trying to figure this out and am new to this. Is this supposed to allow me to plug my SATA (SSD drive)? If so, I am quite new to this and would appreciate any help on how to do this.

**Comment by aliagowani** [comment]
I am really having troubles trying to figure this out. I have a SSD that is in a SATA enclosure connected via USB. How do I get UTM to recognize it? I really appreciate the help.

**Comment by conath** [comment]
@aliagowani You will want to use the USB sharing feature, then. This thread is about _virtual_ SATA devices.

**Comment by aliagowani** [comment]
Thanks @conath I did enable the USB sharing feature and when I select the USB drive from the icon on top of the window, it no longer shows up in my MacOS but it also does not show up in UTM. I am using a WinPE bootcd so perhaps the SATA drivers are not loaded in Windows 10?

When I do the same with a flash drive, it loads properly in UTM. 

Do you by chance have any other suggestions on what I can do?

**Comment by aliagowani** [comment]
Was able to resolve it on my end; needed to align the different version of USB to the USB device.
