### ISSUE TITLE
RAM Problem. CRITICAL! PLEASE FIX!

### ISSUE THREAD

**Issue by StupidRepo** [utmapp/UTM#2306]
**Describe the issue**
Whenever you set the ram to something and boot your VM, it does not use the ram you set.

I have reported this in the discord server (Sir Twitchy#9989) but no one is online since it's dead (sorta).

I have tried changing the ram of an android vm but it is so slow and still takes 10 minutes to boot no matter what I do. EVEN IF I CHANGE THE RAM IN THE CONFIG FILE TO 9379GB!

**Configuration**
UTM Version: Latest
OS Version: 11.0
Apple Silicon

**Crash log**
None

**Debug log**
None?

**Upload VM**
[Kill me.utm.zip](https://www.dropbox.com/s/ided93cimbyo2ri/Kill%20me.utm.zip?dl=1)

**Comment by osy** [comment]
Boot speed is unrelated to ram. Plus android is unsupported. If you’re able to boot windows or Linux and it shows the wrong amount of ram, feel free to reopen this.
