### ISSUE TITLE
GUI field to specify -cpu options

### ISSUE THREAD

**Issue by tiiiecherle** [utmapp/UTM#2307]
I'm trying to set the following options using the GUI:
`-cpu host,vendor=GenuineIntel,+hypervisor,+invtsc,kvm=on,+fma,+avx,+avx2,+aes,+ssse3,+sse4_2,+popcnt,+sse4a,+bmi1,+bmi2`

I don't know where options like `vendor=GenuineIntel,kvm=on` could be added. It would be nice to have a field/box to add those like for the machine options.

Thanks

**Comment by osy** [comment]
> vendor=GenuineIntel

Explain why you need this? That should be default when selecting an Intel cpu to emulate.

> kvm=on

KVM is a Linux only feature. You won’t find it on macos.

**Comment by tiiiecherle** [comment]
I found the line looking around for the best way to use `-cpu host` on my MacBook Pro as the coffee lake processor
`sysctl -a | grep machdep.cpu.brand_string
machdep.cpu.brand_string: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz`
is not available in qemu and `-cpu host` always crashes win10 guests.

I think it would be a good config addition to have that field for whatever extra parameters can be specified for `cpu -host`.

Additionally what settings for `-cpu` for my processor do you think is recommended?

**Comment by Vishram1123** [comment]
When I was emulating macOS Mojave on my M1 Mac mini, `kvm-on` and `vendor=GenuineIntel` did do something, as OpenCore didn't boot without it. Plus, when I was emulating PowerPC on my phone, the Advanced options showed a menu to pick a cpu.

**Comment by conath** [comment]
> I'm trying to set the following options using the GUI:
> `-cpu host,vendor=GenuineIntel,+hypervisor,+invtsc,kvm=on,+fma,+avx,+avx2,+aes,+ssse3,+sse4_2,+popcnt,+sse4a,+bmi1,+bmi2`
> 
> I don't know where options like `vendor=GenuineIntel,kvm=on` could be added. It would be nice to have a field/box to add those like for the machine options.

You can simply take your entire `-cpu` line and add it as a custom argument at the bottom in the QEMU tab. It will override whatever UTM generated.

**Comment by osy** [comment]
@Vishram1123 choose Penryn as your CPU. I looked into the QEMU code and found that it defaults to AMD (when no CPU is specified). If you force GenuineIntel, it will still use other params from the default AMD CPU (stepping, etc) and is unreliable. Setting it to a specific CPU is better supported.
