### ISSUE TITLE
WebDAV sharing not working if VM name has spaces embedded in it.

### ISSUE THREAD

**Issue by Nanoc-ice** [utmapp/UTM#2319]
iPad 2018 12.9 
UTM 2.0.20
IOS 14.2
Not jailbroken
Installed with share from Mac

The problem was with WebDAV sharing on a Arch linux VM (x86_64).  I have three VMs that are all configured roughly the same (ie, 2 manjaro and 1 mabox which is derived from manjaro) and one shares just fine and the other two do not.  I have spent months trying to determine why the other two would not connect to the share.  I finally looked at the QEMU start command and noticed the name the VM had spaces in it that were not escaped.  I changed the names of the VMs so that they would not contain any spaces and those 2 other VMs are now able to connect to the WebDAV server.  I don’t know if this effects Windows guests or not as I don’t run any Windows VMs.   Either a bug or an FYI.

**Comment by osy** [comment]
Can you post your debug.log which should show the full command line? I believe spaces should be escaped but I'm also not sure how WebDAV affects this.

**Comment by Nanoc-ice** [comment]
Here is the qemu command line:
qemu-system-x86_64 -L /private/var/containers/Bundle/Application/89EF69DA-F82C-41E9-B400-CF60486FD02C/UTM.app/qemu -S -qmp tcp:127.0.0.1:4444,server,nowait -spice port=5930,addr=127.0.0.1,disable-ticketing,image-compression=off,playback-compression=off,streaming-video=off -smp cpus=2,sockets=1,cores=2,threads=1 -machine q35,vmport=off -accel tcg,thread=multi,tb-size=256,split-wx=on -vga qxl -global PIIX4_PM.disable_s3=1 -global ICH9-LPC.disable_s3=1 -m 1024 -name "Archlinux - mabox" -device usb-ehci -device usb-tablet -device usb-mouse -device usb-kbd -drive "if=ide,media=disk,id=drive0,file=/var/mobile/Containers/Data/Application/5A5EB40B-CB08-4977-B3E8-8BDC96E9B4CC/Documents/Archlinux - mabox.utm/Images/mabox.img,cache=writethrough" -device rtl8139,netdev=net0 -netdev user,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -device virtserialport,chardev=charchannel1,id=channel1,name=org.spice-space.webdav.0 -chardev spiceport,name=org.spice-space.webdav.0,id=charchannel1 -uuid C979A22B-1C9A-4899-BD96-72BF0B5D3FD4 -rtc base=localtime

Hmm, actually it was the drive that gave me the hint.  I have tried this on an ARM VM (Arch) that had the same naming issue and it didn’t work.  So, I will close this as a red herring and continue to search for the issue.  BTW is there any way to reset the WebDAV server, and know that it was really reset?  Also, multiple VMs can be sharing the same directory at the same time, as long as only 1 VM is actually running at a time?

**Comment by osy** [comment]
There’s no way to separately reset WebDAV. Multiple VMs can share the same directory even if all are running at the same time.

**Comment by Nanoc-ice** [comment]
Ok, thanks for the extra information.
