### ISSUE TITLE
Update dependencies to latest version

### ISSUE THREAD

**Issue by osy** [utmapp/UTM#232]
This will be low priority unless there's a reason to do this (security issue maybe). Right now, for some GNU dependencies, the latest version removes autoconf and only use meson. So we use the last version with autoconf out of laziness (since the script is designed to work with autoconf). It shouldn't be too much effort to get it working with meson as well.

- [x] QEMU 5.0.0

**Comment by osy86** [comment]
QEMU updated to v5.1, will track other libraries.

**Comment by osy** [comment]
Closing this issue, will open a new issue for any specific version update.
