### ISSUE TITLE
USB drives always generate with removable=false

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2320]
Steps to reproduce:

1. Create a VM
2. Go to config => drives
3. Create a new removable drive, hit done
4. Change the new drive's Image Type to Disk Image and Interface to USB
5. Save
6. Go to Config => QEMU and see the issue.

**Issue:**

The generated QEMU parameter is as follows:

`-device usb-storage,drive=driveX,removable=false`

When it should be:

`-device usb-storage,drive=driveX,removable=true`

This issue prevents the VM from starting because QEMU rejects the config (error "Device needs media, but drive is empty" regardless of if an image has been selected with the Browse option). I have verified that manually specifying the `removable=true` resolves the issue.

**Comment by osy** [comment]
Is this a new bug introduced in .21? I’ve definitely had it working before.

**Comment by conath** [comment]
I'm not sure when it was introduced but I've experienced this for a while. Only happens with drives set to removable in the UI. If you import a disk image and change it to USB it works fine.
