### ISSUE TITLE
Warn before quitting with ⌘Q 

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2321]
**Describe the issue**
I am running a macOS VM and I press the keyboard shortcut ⌘ Q to quit an application in the VM, or ⌘ W to close a window. However, the shortcut is not passed into the VM (even when the mouse is captured). Instead, UTM immediately exits. This is very annoying because you lose all unsaved data and pressing ⌘Q/W is extremely common for macOS users.

**Configuration**
* UTM Version: latest
* OS Version: latest
* Intel or Apple Silicon? Intel

**Suggestion**

When ⌘ Q/W is encountered while a VM is still running, an alert should appear with the option to pause the VM, Exit and Cancel (continuing to run the VM as if ⌘ Q/W wasn't pressed).

**Comment by cuj** [comment]
I guess another solution is to make UTM have a host key just like virtualbox, so shift is the host key, so if you press cmd+shift+q it will input cmd+q into the vm.

**Comment by osy** [comment]
@conath any idea how to do this? I know Chrome has something where you have to confirm Cmd+Q or hold it.

**Comment by conath** [comment]
This may help: https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428642-applicationshouldterminate

**Comment by osy** [comment]
This also seems relevant: https://stackoverflow.com/questions/64993265/swiftui-and-appkit-use-close-dialog-to-ask-if-the-app-is-allowed-to-quit

**Comment by StupidRepo** [comment]
@osy `I know Chrome has something where you have to confirm Cmd+Q or hold it.`

It's actually Opera not Chrome.

**Comment by conath** [comment]
Chrome does have it, it's an option in the "Chrome" menu ("Warn Before Quitting".

**Comment by StupidRepo** [comment]
Ok, I went on Parallels Desktop, told them their app was CRAP and told people to get a refund and use UTM lol

**Comment by osy** [comment]
Reading more on this, seems like Key Equivalent Handling (menu/button shortcuts) are always handled before the event is sent to the key window -> first responder -> my view. So Cmd+Q, Cmd+W, Cmd+N for example won't be seen by the app. The way around it is to use https://developer.apple.com/documentation/appkit/nsevent/1534971-addlocalmonitorforeventsmatching which will require a bit of refactoring on the current window controller.

I'm thinking of the following rules:

1) When mouse is captured, always send all keys to VM except the release key combo.
2) When mouse is not captured, throw alert when Cmd+Q or Cmd+W prompting the user to either pause the VM (if available) or stop it.
3) Any other Key Equivalents will still be handled when not captured. This makes us a good macOS citizen.

**Comment by Oreilles** [comment]
> 
> 
> @osy `I know Chrome has something where you have to confirm Cmd+Q or hold it.`
> 
> It's actually Opera not Chrome.

Chrome has it too, and it's beyond annoying - but can be disable fortunately. It should just show a confirmation window with the option to not ask ever again, like literally every mac app.

**Comment by JayBrown** [comment]
There's also this: https://commandqapp.com/

**Comment by aem111607** [comment]
Edge also has it, it seems like most chromium browsers do

**Comment by codethief** [comment]
@osy Your commit message says

> If mouse is not captured, we always warn for Cmd+Q.

However, that doesn't seem to be the case on my machine: When the mouse is not captured, Cmd+Q immediately pauses & closes the VM. Has anything changed here since this ticket was resolved? See also https://github.com/utmapp/UTM/issues/5513 .
