### ISSUE TITLE
[iOS] Crash when rearranging drive downwards in the list

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2322]
**Describe the issue**
Crash when rearranging drives. To reproduce, create a VM and go to Configuration → Drives. Add two removable drives. Now tap Edit, then drag the top drive below the second drive. Crash.

**Configuration**
* UTM Version: latest
* OS Version: latest
* Device Model: iPad Pro 11" 2018
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? Xcode

**Crash location**
Crash is in NSArray due to index out of bounds. The index where the moved drive is inserted needs to be decremented by one if it is moved past its old position. (e. g. moved from first to second spot, meaning down)
Call stack is:
[`VMConfigDrivesView.swift` line 113](https://github.com/utmapp/UTM/blob/53deefa64a7b0e39cb8503b6d8aa18bdc8d2632f/Platform/iOS/VMConfigDrivesView.swift#L113) (moveDrives) [by the way, is that a typo? it only moves one drive]
[`UTMConfiguration+Drives.m` line 194](https://github.com/utmapp/UTM/blob/53deefa64a7b0e39cb8503b6d8aa18bdc8d2632f/Configuration/UTMConfiguration%2BDrives.m#L194) (moveDrive)

<img width="1111" alt="index" src="https://user-images.githubusercontent.com/12073163/108549575-9bb3ce80-72ed-11eb-80a1-7e47d77595bf.png">

**Comment by osy** [comment]
SwiftUI `.onMove` supports multiple items even though I don't know how that is done on the UI side.
