### ISSUE TITLE
Images IOS location

### ISSUE THREAD

**Issue by Tsumiicode** [utmapp/UTM#2324]
* UTM Version: latest 
* OS Version: 14.3 IOS 
* Device Model: IPhone 7 a1660
* Is it jailbroken (name jailbreak used)? Sileo Checkrain
* How did you install UTM? Sileo repo

Where are disks stored in iOS because I need to delete stuff
Please help I’m running out of storage and I keep getting a error saying iso already in directory “Images”

**Comment by osy** [comment]
> I keep getting a error saying iso already in directory “Images”

Are you trying to import the same ISO twice? Post a screenshot of your drives setting page.

They are stored in your /var/mobile/Documents if you're jailbroken.

**Comment by Tsumiicode** [comment]
I can’t find it anywhere in the documents folder it’s what should the
folder be called?

**Comment by osy** [comment]
It should be the name of your VM with extension .utm

**Comment by Tsumiicode** [comment]
No there’s nothing to do with utm in it

**Comment by Tsumiicode** [comment]
Did some digging found it at

/var/mobile/Containers/Data/Application/13213638-A171-4110-883A-3E0A8F700C58/Documents

**Comment by Tsumiicode** [comment]
And also I tried installing windows xp and it was really slow and wouldn’t
pick up my keyboard
