### ISSUE TITLE
Block error when launching Manjaro ISO image [macOS]

### ISSUE THREAD

**Issue by StupidRepo** [utmapp/UTM#2325]
**Describe the issue**
If I try to launch a Manjaro ISO file, it gives me [this error](https://i.ibb.co/nMBKpsn/Screenshot-2021-02-22-at-11-10-18.png)
(Sometimes it crashes, here is the error in text if you don't want to visit the image: `drive0, #block147: Input/output error`)

**Configuration**
* UTM Version: 2.0.21 (From About page)
* OS Version: 11.1
* Intel or Apple Silicon? Apple Silicon

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open Console.app, go to `Crash Reports`, and find the latest entry for either QEMU, QEMUHelper, or qemu-\*. 
Right click and choose `Reveal in Finder`. Attach the report here. 
[UTM_2021-02-22-111337_MyMBP.crash.zip](https://github.com/utmapp/UTM/files/6021553/UTM_2021-02-22-111337_MyMBP.crash.zip)

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the top of the `QEMU` page is `Debug Log`. Turn it on and save the VM. After you experience the issue, open the VM settings again and select `Export Log...` and attach it here. [debug.log](https://github.com/utmapp/UTM/files/6021542/debug.log)

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by StupidRepo** [comment]
Bump

**Comment by StupidRepo** [comment]
lol

**Comment by LightningRhino** [comment]
I experienced the same problem.
But I was able to install Arch with the calamares installer from here:
https://sourceforge.net/projects/blue-arch-installer/
Maybe you want to give it a try.

**Comment by StupidRepo** [comment]
Ok, thanks!
