### ISSUE TITLE
How can I help fund you without going through the apple app store

### ISSUE THREAD

**Issue by mkmik** [utmapp/UTM#2332]
Nice app; I'd like to give you some money without going through the apple app store. Do you have a patreon or github sponsors or a bitcoin address or something like that?

**Comment by bartgrantham** [comment]
I currently support iTerm on patreon with monthly support.  I've already bought UTM on the App Store, but if it meant that I'd be able to seamlessly run the stuff listed in the menus (Alpha, PowerPC, etc.) sooner rather than later, I'd be happy to throw some bucks toward UTM as well.

**Comment by js-john** [comment]
You are rich.😄
