### ISSUE TITLE
Ubuntu 20 AArch64 image from gallery can't boot on Apple M1 "BdsDxe: failed to load Boot0001"

### ISSUE THREAD

**Issue by djwhatle** [utmapp/UTM#2333]
_I figured out a workaround, see [below](https://github.com/utmapp/UTM/issues/2333#issuecomment-786307182)_

**Describe the issue**
Followed [directions from gallery](https://mac.getutm.app/gallery/ubuntu-20-04) to install Ubuntu 20 AArch64. Resulted in this error:

(Note, I had same result trying to install Fedora 33 AArch64 in the same way)

```
BdsDxe: failed to load Boot0001 "UEFI misc device" [...]
```

![image](https://user-images.githubusercontent.com/7576968/109175331-b2c24880-7753-11eb-9ade-dfccc0fefcab.png)

Eventually goes to this screen

![image](https://user-images.githubusercontent.com/7576968/109175380-bb1a8380-7753-11eb-916f-4a5b54d480d3.png)

**Configuration**
* UTM Version: v2.0.22 (have also tested v2.0.21, v2.0.15, same result) 
* OS Version: macOS 11.1 (since upgraded to 11.2.1, same result)
* Intel or Apple Silicon? Apple M1 (Air, 16GB RAM)

**Crash log**
N/A

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/6043940/debug.log)

**Upload VM**
[config.plist.txt](https://github.com/utmapp/UTM/files/6043944/config.plist.txt)

**Comment by scubachristopher** [comment]
Same issue, same hardware.

**Comment by F4zii** [comment]
Same here

**Comment by F4zii** [comment]
Same here, can also confirm this happens on other arm64 virtual machines

**Comment by djwhatle** [comment]
@scubachristopher @F4zii I was able to overcome this issue by:

1) Disabling the network adapter temporarily to remove the step of waiting for PXE boot timeout
2) Typing `exit` at the UEFI shell and then navigating to the USB boot device manually

See attached video for the sequence that worked for me.

https://user-images.githubusercontent.com/7576968/109203157-d1373c80-7771-11eb-91aa-d8dc24969b66.mov

**Comment by scubachristopher** [comment]
@djwhatle  -- you're the man!

**Comment by Vishram1123** [comment]
...or you can spam `esc` on boot to go into the boot manager and choose QEMU USB Harddisk

**Comment by F4zii** [comment]
Nice! that works, but now im just stuck at this screen
<img width="912" alt="image" src="https://user-images.githubusercontent.com/44242259/109226234-133e9d80-77c7-11eb-8b0c-9a0c7e00812e.png">

**Comment by osy** [comment]
In Drives, change the Interface from VirtIO to NVMe. I think there might be a problem in the EFI drivers. I'll look more into it.

**Comment by djwhatle** [comment]
> In Drives, change the Interface from VirtIO to NVMe. I think there might be a problem in the EFI drivers. I'll look more into it.

I actually tried this, I don't think the drive was recognized at that point. 
 
> EDIT: oh this is before installing Ubuntu? So it's failing to boot from the ISO?

Yes, failing to boot from ISO unless you manually select the USB drive for boot through boot manager.

For some reason after I got Ubuntu installed finally [(by following these steps)](https://github.com/utmapp/UTM/issues/2333#issuecomment-786129411), default network connection wasn't working. I tried to swap it out for an intel network adapter but that failed to start the VM.

**Comment by djwhatle** [comment]
> Nice! that works, but now im just stuck at this screen
I got past this screen by waiting a few seconds, but YMMV.

**Comment by djwhatle** [comment]
So the winning combination for me that resulted in Ubuntu 20 installed with internet working:
- Follow all instructions in [gallery](https://mac.getutm.app/gallery/ubuntu-20-04)
- _Don't disable_ the network connection
- Mash ESC at startup
- Use boot maanger -> USB to boot from ubuntu image.

Seems to be working

**Comment by osy** [comment]
I think the problem is at some point I updated the OVMF to a newer version that broke support for `-boot order=d` argument. Or `-boot order=d` never worked in OVMF and we got lucky before in an older version of QEMU which happened to make the USB disk drive default. Either way I'll have to update the arguments to use `bootorder` directly which should be more stable.

**Comment by osy** [comment]
Reopening because after testing on a M1 mac, the error persists even after the fix. Even weirder, I went back to 2.0.15, which was used to create the guide and I'm now getting the same error there as well! But on Intel Macs, there's no issue. On M1 Mac with force emulation, it's still broken!

Even weirder, I go into EFI shell and use `bcfg boot dump` and see that on Intel Macs, I see both the virtio and usb devices in the right order. On M1 Macs, the usb device is missing. I honestly don't know what's going on... As bizarre as it sounds, I have to guess that macOS 11.1 or newer had something that broke this even though it's something within the emulator...

Does anyone have a M1 mac running macOS 11.0? That's the version I was on when the guide was created.

**Comment by osy** [comment]
I updated the guide for a workaround: https://mac.getutm.app/gallery/ubuntu-20-04#troubleshooting

In the meantime I will continue to investigate why the emulated USB disk drive is not seen as a boot device on ARM64 builds of QEMU.

**Comment by Vishram1123** [comment]
The EFI stub issues always persist; it will take a while, but it will boot. This happens on all ARM Linux distributions. I tested with Manjaro, Debian (.UTM package), and Ubuntu


PS: USB gets pushed to the end of the list, with UEFI Misc Device (1/2) in the way.

**Comment by conath** [comment]
I am able to boot an aarch64 VM from a USB CD drive on my iPad Pro, however I am using a custom compiled OVMF EFI. I've attached it here. The files are named "High Res" because I modified the resolutions available in the OVMF configuration to include up to 8K. 
[OVMF High Res.zip](https://github.com/utmapp/UTM/files/6071616/OVMF.High.Res.zip)
To use this EFI image as your VM's firmware, attach the …EFI file as first disk, …VARS file as second disk. Set both interfaces to `pflash`/ PC System Flash.

**Comment by osy** [comment]
I was able to debug the failure by logging from EDK2. There is a race condition in QEMU's (emulated) USB device reset and OVMF enumerating the boot options. M1 macs are too fast and can enumerate the boot options before QEMU sets up the device. This race condition is why it occurs for some people and not others and also why it stops appearing if you enable debug logging.

Without thinking too hard how to prevent the race, the hack around is to have a 1 second wait between the device enumeration and boot option enumeration.

https://github.com/utmapp/edk2/commit/bca86ecf2e1124c8a931b0dbfc276c7280df35c7

**Comment by HenkPoley** [comment]
Is this patch in UTM 2.0.25 ? (since my network isn't working, I think not)

**Comment by osy** [comment]
This issue isn’t about network?

**Comment by labcerouno** [comment]
> In Drives, change the Interface from VirtIO to NVMe. I think there might be a problem in the EFI drivers. I'll look more into it.
> 
> EDIT: oh this is before installing Ubuntu? So it's failing to boot from the ISO?

It's happened to me after installing. I changed from VirtIO to NVMe and it worked!

**Comment by NosillaCast** [comment]
Hi - followed the instructions in the troubleshooting section and when I enter `fs0:\efi\boot\bootaa64.efi` into the  UEFI Interactive Shell (and the mapping table says `SF0: Alia(s) :CD0D0A::blk1:`), the Shell responds with `Command Error Status: Unsupported`.

M1 Mac mini running macOS Big Sur 11.4, and pointing to the Ubuntu Server download from the support article at https://mac.getutm.app/gallery/ubuntu-20-04

What am I missing?

**Comment by hva314** [comment]
I ran into the same issue when installing Kali Linux on host Macbook M1, Big Sur. 

Apparently, boot sequence was looking for the missing file `startup.nsh`.

At EFI cli, you can type `fs0:\efi\[your_OS]\grubx64.efi` to boot. You can use tab completion to figure out the directory.
In my case: `fs0:\efi\kali\grubx64.efi`.

When on the OS, hope onto `root` and create the file `startup.nsh` manually. 
`echo '\EFI\kali\grubx64.efi' > /boot/efi/EFI/kali/startup.nsh"`(change the name accordingly)

**Comment by conath** [comment]
Thanks @hva314 for this solution, however just to make sure: are you using the ARM version of Kali or the x86_64 version? The ARM bootloader file is `bootaa64.efi`, not `grubx64.efi`.

**Comment by NosillaCast** [comment]
> Hi - followed the instructions in the troubleshooting section and when I enter `fs0:\efi\boot\bootaa64.efi` into the UEFI Interactive Shell (and the mapping table says `SF0: Alia(s) :CD0D0A::blk1:`), the Shell responds with `Command Error Status: Unsupported`.
> 
> M1 Mac mini running macOS Big Sur 11.4, and pointing to the Ubuntu Server download from the support article at https://mac.getutm.app/gallery/ubuntu-20-04
> 
> What am I missing?

I went through the installation process from scratch for what I think is the third time, and this time did not get dumped into UEFI Interactive Shell, and it proceeded to function properly. Wish I could identify what I did differently, but I can't.

**Comment by conath** [comment]
> > Hi - followed the instructions in the troubleshooting section and when I enter `fs0:\efi\boot\bootaa64.efi` into the UEFI Interactive Shell (and the mapping table says `SF0: Alia(s) :CD0D0A::blk1:`), the Shell responds with `Command Error Status: Unsupported`.
> > M1 Mac mini running macOS Big Sur 11.4, and pointing to the Ubuntu Server download from the support article at https://mac.getutm.app/gallery/ubuntu-20-04
> > What am I missing?
> 
> I went through the installation process from scratch for what I think is the third time, and this time did not get dumped into UEFI Interactive Shell, and it proceeded to function properly. Wish I could identify what I did differently, but I can't.

Does it continue to work after you’ve shut it down once? (Close the VM window and start it again with the Play button) 
That’s usually when the auto-boot breaks, if it is dependent on EFI NVRAM variables.

**Comment by NosillaCast** [comment]
>Does it continue to work after you’ve shut it down once? (Close the VM window and start it again with the Play button)
That’s usually when the auto-boot breaks, if it is dependent on EFI NVRAM variables.

Yes, it works consistently after shutdown.

**Comment by parth2210** [comment]
UTM I was able to install on my new MacBook M1 pro, but ultimately it comes down to this screen 

![](https://user-images.githubusercontent.com/7576968/109175380-bb1a8380-7753-11eb-916f-4a5b54d480d3.png)
 
 And I am unable to exit from it since it does not recognize my Keyboard or trackpad.
 Any help please?

**Comment by sumedhreddy90** [comment]
> @scubachristopher @F4zii I was able to overcome this issue by:
> 
> 1. Disabling the network adapter temporarily to remove the step of waiting for PXE boot timeout (not sure about this step, seems I don't have internet connectivity after install even when adding network adapter later)
> 2. Typing `exit` at the UEFI shell and then navigating to the USB boot device manually
> 
> See attached video for the sequence that worked for me.
> 
>  successful_boot.mov

Tried the same but the screen pops and closes within a second not sure whats the issue

**Comment by yimingshan666** [comment]
> Hi - followed the instructions in the troubleshooting section and when I enter `fs0:\efi\boot\bootaa64.efi` into the UEFI Interactive Shell (and the mapping table says `SF0: Alia(s) :CD0D0A::blk1:`), the Shell responds with `Command Error Status: Unsupported`.
> 
> M1 Mac mini running macOS Big Sur 11.4, and pointing to the Ubuntu Server download from the support article at https://mac.getutm.app/gallery/ubuntu-20-04
> 
> What am I missing?


I have the same problem. Did you solve it?

**Comment by Henrb** [comment]
Hello, I had the case for the installation of kali linux arm for mac m1 download on download site, you have to go to the uefi settings and manually launch the launch file, launch> echap bios> boot maintenance manager > boot for files, find the file to install on the hard drive in the location "grubaa64.efi"
thanks google trad, Regards henrb.

**Comment by steezeburger** [comment]
@Henrb just to expound on your answer, once the vm is booted and you are presented with the `Shell>`, you can type `exit` to get back to the menu that shows the `Boot Maintenance Manager` then `Boot from File`.

From here you can navigate to `kali/grubaa64.efi` as mentioned.

**Comment by DHEERAJ-JR** [comment]
> @scubachristopher @F4zii I was able to overcome this issue by:
> 
> 1. Disabling the network adapter temporarily to remove the step of waiting for PXE boot timeout (not sure about this step, seems I don't have internet connectivity after install even when adding network adapter later)
> 2. Typing `exit` at the UEFI shell and then navigating to the USB boot device manually
> 
> See attached video for the sequence that worked for me.
> 
>  successful_boot.mov

GOD!!

**Comment by tiagovalePT** [comment]
I'm trying to do this on my MB Pro with a M1 pro and i can't manage to do it. Every time i click on the file to boot it simply opens a black screen and instantly comes back to the menu. Is anyone having the same error?

**Comment by tmusername** [comment]
I think I am having the same error, @tiagovalePT . I'm guessing it's the problem that @osy mentioned and linked to a solution. I'm too much of a newb to understand how to execute that code in this context.

**Comment by richlife98** [comment]
@djwhatle 

I met a similar issue and fail to install Ubuntu20.04 in a VM/KVM on Raspberry Pi 3. I plan to install Ubuntu 20.04 Server in KVM on Raspberry Pi3. **I follow the instructions and video but the issue can't be resolved**.  Besides, there is no FS0.

##Can't start the Ubuntu installation process

https://user-images.githubusercontent.com/61045849/142564327-bca0286c-a68a-4d1a-bd1f-da59e6992ec9.mp4


![1](https://user-images.githubusercontent.com/61045849/142564537-da040a37-958b-4a7d-97ad-a54e335da990.JPG)

![2](https://user-images.githubusercontent.com/61045849/142564549-5de551b4-d89c-44b1-bfa1-0ee03ab6e4a9.jpg)

Here are the conditions and environment:
1. HW: Raspberry Pi 3 with Ubuntu 20.04 Server OS
2. OS iso installed in KVM: ubuntu-20.04.3-live-server-arm64.iso

Does anyone meet the same issue?? how to fix it??

Thanks for help very much

> @scubachristopher @F4zii I was able to overcome this issue by:
> 
> 1. Disabling the network adapter temporarily to remove the step of waiting for PXE boot timeout (not sure about this step, seems I don't have internet connectivity after install even when adding network adapter later)
> 2. Typing `exit` at the UEFI shell and then navigating to the USB boot device manually
> 
> See attached video for the sequence that worked for me.
> 
>  successful_boot.mov

**Comment by bablf** [comment]
> Does anyone meet the same issue?? how to fix it??

Same issue here

**Comment by hedeesaa** [comment]
@richlife98 
I'm facing the same problem here, did you've found the solution?

**Comment by tmusername** [comment]
In case it's helpful to anyone else:  I had mistakenly been trying to use the wrong iso. I was trying to install the AMD version of Ubuntu, when it's the ARM version that's required. A silly mistake, but thankfully an easy one to correct.

**Comment by bablf** [comment]
this [video](https://www.youtube.com/watch?v=-XFNUeWhsIQ ) helped me resolve the issue. For me the problem was also the wrong iso version. The one linked in the description solved my problem.

**Comment by ShilvySusan** [comment]
Hi all,

I am getting the same issue as the header. Please let me know, if there is a fix other than the previous comments in this loop. Please see the attached picture of error.

![Screenshot 2022-03-11 at 18 49 02](https://user-images.githubusercontent.com/69473633/157922357-122cb127-570a-4a0f-855d-3ab37df76452.png)

**Comment by tinywolf3** [comment]
> Hi all,
> 
> I am getting the same issue as the header. Please let me know, if there is a fix other than the previous comments in this loop. Please see the attached picture of error.
> 
> ![Screenshot 2022-03-11 at 18 49 02](https://user-images.githubusercontent.com/69473633/157922357-122cb127-570a-4a0f-855d-3ab37df76452.png)

I have same problem.

**Comment by readable-ko** [comment]
@ShilvySusan @tinywolf3 
I was having the same problem in my case, but after about 5 minutes i got out from that screen and its working well.

**Comment by null0333** [comment]
> Hi all,
> 
> I am getting the same issue as the header. Please let me know, if there is a fix other than the previous comments in this loop. Please see the attached picture of error.
> 
> ![Screenshot 2022-03-11 at 18 49 02](https://user-images.githubusercontent.com/69473633/157922357-122cb127-570a-4a0f-855d-3ab37df76452.png)

same problem here, ive tried waiting but it doesnt get past this screen
it was working for a while on kernel version 5.04.0-99 but the newer kernel versions > 5.04.0-100 doesnt seem to work 
i read in a different thread that this could be due to force stopping the VM causes drive corruption maybe ?

**Comment by UriZafrir** [comment]
I suggest a permanent fix in #4002

**Comment by August90dd** [comment]
> I suggest a permanent fix in #4002

This is work for me! see more: https://linuxhint.com/use-uefi-interactive-shell-and-its-common-commands/

**Comment by simonhuwiler** [comment]
> > Does anyone meet the same issue?? how to fix it??
> 
> Same issue here

Same problem here. From one of the other day, all VMs (Ubuntu 20.04 on Mac M1) stopped working. They run properly on console mode, but not on Full Graphics. Did not update mac nor UTM. They stopped working since I tried to launch them while mac was not connected to a docking station.

**Comment by valerii-chirkov** [comment]
I solved the issue with downloading Ubuntu Server 22.04 for ARM, it seems that I either was trying to install amd version or the iso just not compatible for now.

**Comment by Welin-Chen** [comment]
I spent 4 hr try to solve this problem.
Finally I success!
I use wrong Ubuntu install iso file, apple m1 ARM need to install another vision
download link as follow:
[m1 download](https://ubuntu.com/download/server/arm)
hope can help you guys!

**Comment by All3yp** [comment]
Anyone have this other problem? I do not have a **fs0**

![Uploading Captura de Tela 2022-10-04 às 19.48.38.png…]()

**Comment by SimonCK666** [comment]
> Nice! that works, but now im just stuck at this screen <img alt="image" width="912" src="https://user-images.githubusercontent.com/44242259/109226234-133e9d80-77c7-11eb-8b0c-9a0c7e00812e.png">

Hi,

I also met this problem. AND STUCK ON THIS PAGE.
Do you have any suggestions for solving this?

Best

**Comment by KACHII-a** [comment]
> UTM I was able to install on my new MacBook M1 pro, but ultimately it comes down to this screen 
> 
> 
> 
> ![](https://user-images.githubusercontent.com/7576968/109175380-bb1a8380-7753-11eb-916f-4a5b54d480d3.png)
> 
>  
> 
>  And I am unable to exit from it since it does not recognize my Keyboard or trackpad.
> 
>  Any help please?

Hi, were you able to get past this? I'm having the same problem

**Comment by akbarjon2000** [comment]
I am fed up facing problems in Mac. I also have the same problem!!!

**Comment by Welin-Chen** [comment]
have you try use the install file as follow?
download link as follow:
[m1 download](https://ubuntu.com/download/server/arm)

**Comment by Welin-Chen** [comment]
> install [m1 download](https://ubuntu.com/download/server/arm)

**Comment by Woodo-VIRNECT** [comment]
I solved the issue with downloading Ubuntu Server 20.04 

1. https://cdimage.ubuntu.com/releases/20.04/release/
2. download iso file : ubuntu-20.04.5-live-server-arm64.iso

**Comment by wscgogogo** [comment]
I solved this problem on arm architecture.follow this steps,it's worked for me.
1. You need to mount iso as usb file,add part like this when you execute 'virsh edit "virtualmachine"'
    <disk type='file' device='cdrom'> 
      <driver name='qemu' type='raw'/> 
      <source file='/data/iso/CentOS-7-aarch64-Minimal-2009.iso'/> 
      <target dev='vdb' bus='usb'/> 
      <readonly/> 
      <address type='usb' bus='0' port='1'/> 
    </disk>
2. You can try to execute boot manually with command 'fs0:\efi\[osname]\bootaa64.efi',but usually failed with permission.
3. You need type exit to use bios,in bios use "Device Manager" -> "Secure Boot" to close secure boot.

**Comment by wscgogogo** [comment]
in first step,xml like 
<img width="519" alt="image" src="https://github.com/utmapp/UTM/assets/32636617/896af4dc-02e0-4e56-89ac-f86c11f5cf02">

**Comment by raaed9** [comment]
This worked for me.
