### ISSUE TITLE
Broken Sidebar with macOS 11.3 Beta 1(20E5172i) and newer

### ISSUE THREAD

**Issue by khronokernel** [utmapp/UTM#2335]
Issue is replicable both on Intel and Apple Silicon, both running macOS 11.3 Beta 1(20E5172i) and Beta 2(20E5186d):

* Hardware:
  * Apple Silicon: M1 MacBook Pro
  * Intel: i9-7920X with RX 5700XT
* UTM version: All versions affected(tested 2.0.18-2.0.22)
<img width="506" alt="Screen Shot 2021-02-25 at 9 18 04 AM" src="https://user-images.githubusercontent.com/48863253/109195187-71cc3300-7757-11eb-9713-f1025052a6e5.png">

Creating a new Virtual Machine resolves this issue temporarily for the newest item(s). However when the app is closed for a period of time and then reopened, the UI is broken again:

| Creating new VM | Reordering VMs(doesn't resolve) | Creating other new VMs |
| :--- | :--- |  :--- |
| <img width="1012" alt="Screen Shot 2021-02-25 at 9 21 56 AM" src="https://user-images.githubusercontent.com/48863253/109195247-84df0300-7757-11eb-8ee2-f4c0a6d24582.png"> | <img width="1012" alt="Screen Shot 2021-02-25 at 11 02 31 AM" src="https://user-images.githubusercontent.com/48863253/109196553-113df580-7759-11eb-91a6-418eeade7722.png"> | <img width="1012" alt="Screen Shot 2021-02-25 at 11 14 06 AM" src="https://user-images.githubusercontent.com/48863253/109198536-90342d80-775b-11eb-8062-94848e7dd692.png"> |

**Comment by osy** [comment]
Once again bitten in the ass by being the only developer to adopt SwiftUI for mac...

**Comment by osy** [comment]
This is really frustrating, I can't seem to find a workaround for this bug. FB9030128 is filed with the following minimally reproducible example:

```swift
struct ContentView: View {
    var body: some View {
        NavigationView {
            List {
                ForEach(0..<10) { i in
                    Text("Item \(i)")
                        .frame(height: 50)
                }
            }
            .listStyle(SidebarListStyle())
        }
    }
}
```

**Comment by osy86** [comment]
ikr, Once again bitten in the ass by being the only developer to adopt SwiftUI for mac...

**Comment by osy** [comment]
This is fixed in macOS 11.4 beta 1.

**Comment by khronokernel** [comment]
Was able to verify this myself, 11.4 Beta 1 on my M1 MacBook Pro is working correctly. Seeing as this is resolved, closing

**Comment by gklka** [comment]
Since I wasn't able to find this issue in the bug reporter let there be some tags for search: sidebar cropping, crop issue.
