### ISSUE TITLE
Add notes to vm

### ISSUE THREAD

**Issue by tpetry** [utmapp/UTM#2336]
When creating some test vms locally or wanting to distrubute them to e.g. students for some exercises it's really helpful to add some notes to the vm.

So a simple free text notes field for every vm would be really great to write down some settings to change, some hints or even login passwords.

**Comment by conath** [comment]
You can add notes to a VM by opening the VM Settings, then tap on Information and tap under the "Notes" text. Depending on if you're on iOS or macOS it might look like there isn't a text field there, but there is and you can type something. This will show up on the VM details screen.
<img width="1253" alt="Bildschirmfoto 2021-02-26 um 12 24 04" src="https://user-images.githubusercontent.com/12073163/109294465-867afa80-782d-11eb-8bad-1ab9baef5a2d.png">

**Comment by tpetry** [comment]
Sorry, despite my glasses i was blind and didn't see it oO
