### ISSUE TITLE
Booting Debian takes forever!

### ISSUE THREAD

**Issue by raadfhaddad** [utmapp/UTM#2340]
the OS takes forever to boot
After restarting the VM it starts from installation steps (the beginning)

Any suggestions for this problem?

**Comment by osy** [comment]
I think after the installation completes, you need to remove the disk (unmount the iso) and then restart it. Otherwise it will boot from the ISO again.

**Comment by osy** [comment]
Also the issues page is not a support forum. Please check out the [Discord][1] for help.

[1]: https://discord.gg/UV2RUgD
