### ISSUE TITLE
Improve Documentation for Running Windows ARM on Mac

### ISSUE THREAD

**Issue by PhotoNomad0** [utmapp/UTM#2342]
**Describe the issue**
A clear and concise description of what the issue is. **BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Configuration**
* UTM Version: 2.0.22 (22)
* OS Version: Big Sur
* Intel or Apple Silicon? Apple Silicon

Was having a problem that the Windows ARM drive would get corrupted sometimes on shutdown.

I found a tip that works around the problem.  On https://gist.github.com/niw/e4313b9c14e968764a52375da41b4278#running-windows-10-on-arm, under item 9.  It recommends to Convert VHDX downloaded Windows image to qcow2 format:

```
It seems that VHDX often gets broken while it is being used, so probably it is better to convert it to qcow2 format before using it.

qemu-img convert -p -O qcow2 ~/Downloads/Windows10_InsiderPreview_Client_ARM64_en-us_21286.VHDX ~/Downloads/Windows10_InsiderPreview_Client_ARM64_en-us_21286.qcow2
```

So far I have not seen any corruption of the windows drive in the qcow2 format.

Suggest updating the instructions at https://github.com/utmapp/UTM/wiki/Install-Windows-ARM64-on-Apple-M1 to add this suggestion, but it requires that the user also install qemu to convert the image.  Or even better would be for UTM to automatically do the conversion from VHDX format when it is imported.

**Comment by conath** [comment]
I agree, disk image conversion would be a great feature. And I'll add that I'd love to be able to resize an existing qcow2 image #16.

**Comment by osy** [comment]
Updated the guide at https://mac.getutm.app/gallery/windows-10-arm will continue to track the compression feature in #16

**Comment by PhotoNomad0** [comment]
@osy Thanks.  I found an easier way than installing qemu using Homebrew (it's complicated for Mac M1 users using Rosetta and all).  You can use the qemu-img in the App: `/Applications/ACVM.app/Contents/Resources/qemu-img`
