### ISSUE TITLE
Language Settings

### ISSUE THREAD

**Issue by teddue** [utmapp/UTM#2344]
**Describe the issue**
My OS is set to German. The UTM App has a Korean User Interface. How can I change it to English?

**Configuration**
* UTM Version: Latest (AppStore)
* OS Version: Big Sur 11.2.1
* Intel or Apple Silicon? Apple Silicon

**Comment by conath** [comment]
I can't reproduce this. My system:

* UTM Version: Latest App Store (2.0.22)
* OS Version: Big Sur 11.2.2
* Intel or Apple Silicon? Intel
* Locale: German (Germany)

As a workaround you could try adding English to your *Bevorzugte Sprachen* list in System Preferences, reboot and then see if the issue persists.
