### ISSUE TITLE
Generate MAC address for network interfaces and allow to specify MAC

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2346]
It seems to me like the MAC address used for the virtual network interface changes when UTM is restarted. This causes guests to "forget" their previous network configuration, which is very annoying in the long term. I was able to reproduce this with Windows 10 and Ubuntu 20.04 guests, using multiple network adapters. 

Current workaround is to disable networking in the Config, then add the needed network parameters as extra QEMU arguments, and include a MAC address there. The following arguments add a RTL8139 device with a fixed MAC address. The downside of the workaround is that the port forwarding UI is unavailable if networking is disabled.

```log
-netdev user,id=net0
-device -device rtl8139,netdev=net0,mac=XX:XX:XX:XX:XX:XX
```

It would be great if a fixed MAC address could be auto-generated and if it could be changed from the Network configuration.

**Comment by osy** [comment]
I don't see a reason for changing the MAC address for now (I hesitate to put too much options into the GUI which could be confusing). Can revisit if a need arises.
