### ISSUE TITLE
iPhone 12 | A14 / iOS 14.1 (Unc0ver JB) | UTM broken

### ISSUE THREAD

**Issue by 0n1cOn3** [utmapp/UTM#2350]
Hi

When you wanna create a new VM, the + and the edit button won‘t do anything. It‘s a fresh install:

**Configuration**
* UTM Version: 2.0.22
* OS Version: iOS 14.1
* Device Model: iPhone 12
* Is it jailbroken?: Yes, Unc0ver 6.0.0
* How did you install UTM?: by Cydia Repository 

**Crash log:**
Not available...
**Debug log:**
Not available...
**Upload VM:**
Not necessarily

**Others:**

https://user-images.githubusercontent.com/27576311/109423025-41e29100-79de-11eb-99b9-b610f74bc989.MP4

@

**Comment by slavicweebofficial** [comment]
Is this the .deb?

**Comment by 0n1cOn3** [comment]
> Try installing the ipa via filza

Same effect ;(

**Comment by osy** [comment]
@0n1cOn3 Can you uninstall the UTM DEB and then install https://cydia.akemi.ai/?page/net.angelxwind.appsyncunified With AppSync Unified installed, AirDrop the UTM IPA and it should be installed (no altstore needed). Then see if that works?

**Comment by tolikes** [comment]
![Uploading 19E436C3-BF45-4D9D-A05E-5B38B61F0198.png…]()

**Comment by tolikes** [comment]
IPhone 11 iOS 14.2 (unc0ver jailbroken) the app no work

**Comment by Vishram1123** [comment]
I have had this problem on both the IPA and the DEB; something about the corners of the screen is weird; I had to spam on the + button to make it work, or I had to put it in landscape mode and click the big + button.

**Comment by osy** [comment]
I tried UTM on a fresh iOS 14.3 system and don’t see this. I think some tweak is messing up the UI. Try disabling all tweaks and try again.
