### ISSUE TITLE
TCG accelerator parameter generated in addition to HVF when just HVF would suffice

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2354]
When using UTM a x86_64 VM on my Intel Mac mini, it generates both `-accel hvf` and `-accel tcg …` though just `-accel hvf` would suffice. 

* UTM Version: latest
* OS Version: latest
* Intel or Apple Silicon? Intel

The code responsible is [`argsFromConfiguration` in `UTMQemuSystem.m`](https://github.com/utmapp/UTM/blob/54153f76eeeec34b04c2b8cc1c3a22aae9a5dd5c/Managers/UTMQemuSystem.m#L493). It checks if it should use the hypervisor and then puts the TCG parameter, anyway.

```objc
    if (self.useHypervisor) {
        [self pushArgv:@"-accel"];
        [self pushArgv:@"hvf"];
    }
    [self pushArgv:@"-accel"];
    [self pushArgv:[self tcgAccelProperties]];
```

Is this necessary? I changed the code to this…

```objc
    if (self.useHypervisor) {
        [self pushArgv:@"-accel"];
        [self pushArgv:@"hvf"];
    } else {
        [self pushArgv:@"-accel"];
        [self pushArgv:[self tcgAccelProperties]];
    }
```

 … and a Windows 10 x64 install ISO started up just fine.

**Comment by osy** [comment]
The issue here is if the target doesn’t support HVF it will automatically fall back to TCG. Of course I can manually check for this but I didn’t want to think of all the edge cases.

**Comment by conath** [comment]
Ok that's sensible. So it doesn't cause a performance penalty to have the additional `-accel tag` parameter there?

**Comment by osy** [comment]
No it gets ignored by qemu.
