### ISSUE TITLE
macOS as guest on macOS host

### ISSUE THREAD

**Issue by MalEbenSo** [utmapp/UTM#2360]
Please add the option to run macOS as the guest OS on macOS.

E. g. to run Big Sur (Apple Silicon) and Mojave (x86) on Big Sur (Apple Silicon).

**Comment by conath** [comment]
I found these instructions for booting a macOS Recovery image in UTM. You can try following the steps and then install macOS. However from my experience, the kind of emulation that makes x86_64 guests work in Apple Silicon UTM is too slow to handle modern macOS. [unofficial instructions](https://khronokernel.github.io/apple/silicon/2021/01/17/QEMU-AS.html)

**Comment by Vishram1123** [comment]
Using [this](https://github.com/kholia/OSX-KVM) guide, I managed to cobble together a "working" macOS Mojave vm inside my M1 Mac, but the internet was horrible (I could not use the recommended adapter as UTM does not have KVM), and it was generally slow. macOS Big Sur running in Virtualbox on my Surface was faster. I can't say I would recommend it.

**Comment by osy** [comment]
Since we are using QEMU as a backend, we are limited to what's possible with QEMU. With the unofficial instruction linked above, it is possible to install macOS, but it is really not recommended as the emulation is too slow. I really don't recommend trying to run anything newer than Windows 7 (in emulation mode). Plus macOS makes extensive use of GPU acceleration which cannot be emulated.

**Comment by MalEbenSo** [comment]
Thanks for the recommendations. 

I was obviously mistaken in the nature of Apple's virtualization framework in macOS. 
I assumed it would facilitate VMs much like a hypervisor and that the VM would not differ from real hardware. So at least running Big Sur (Apple Silicon) on Big Sur (Apple Silicon) would be straight-forward. 
Well, I just learned something.

**Comment by MalEbenSo** [comment]
The two links provided mostly discuss macOS guests on a virtual x86_64 platform.

For completeness sake here is one link that discusses [the (sad) state of running an M1 VM on M1 hardware](https://forums.macrumors.com/threads/is-it-possible-to-run-a-macos-virtual-machine-on-m1-yet.2272694/).

**Comment by natevw** [comment]
@osy Can you clarify? You seem to have answered about emulation (cross-architecture) support including:

> Plus macOS makes extensive use of GPU acceleration which cannot be emulated.

What about when the host and guest are same? Is there no path forward to run M1 guest in an M1 host hypervisor?

**Comment by osy** [comment]
Any GPU acceleration requires guest support. In this case either Apple has to release drivers for virtualization or someone has to reverse them.

**Comment by derzahla** [comment]
What if no GPU acceleration is needed?  Is that possible today?

**Comment by natevw** [comment]
@derzahla I could be wrong, but my understanding of "macOS makes extensive use of GPU acceleration" is that recent releases do need it.

**Comment by derzahla** [comment]
Hm, interesting.  You would think that could be turned off.  is there anyway to test it?  Since I dont think UTM even gives you the option currently to bypass the architecture emulation layer and present M1 hardware to the VM

**Comment by conath** [comment]
> I dont think UTM even gives you the option currently to bypass the architecture emulation layer and present M1 hardware to the VM

Correct, because there is no such technology is available in macOS Big Sur. It is coming in the next release of macOS, Monterey, later this year and may be offered as an option in UTM then (this is not a promise, as I am not working on that myself).

**Comment by derzahla** [comment]
So is there currently a way to run Big Sur M1 VMs with any product?

**Comment by MalEbenSo** [comment]
Not that I am aware of. 

Not the usual candidates: Parallels, VMware, Oracle. 

Big disappointment in the light of Apple‘s statement, that they understand the importance of virtualization.
