### ISSUE TITLE
Unable to scroll console-only (headless) distros 

### ISSUE THREAD

**Issue by 8thHalfHour** [utmapp/UTM#2362]
**Describe the issue**
A clear and concise description of what the issue is. **BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

When I run any Linux distro headless (primary examples: Alpine Linux v3.13 and Puppy Linux v9.5), I am unable to scroll back beyond the current screen. This is a real issue because when I run a search for a package and the list is longer than one screen, for example, I cannot view anything that came before it. For now, I am sending the searches to text files, which is less than desirable. Am I missing a configuration option? 

**Configuration (required)**
* UTM Version: (How do I find this in the app?)
* OS Version: iPadOS v14.3
* Device Model: iPad Pro 12.9” 2018
* Is it jailbroken (name jailbreak used)? Not jailbroken 
* How did you install UTM? AltStore

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here.

No crash occurred.

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the bottom of the configuration options (or at the top of the `QEMU` page) is `Debug Log`. Turn it on and save the VM. After you experience the issue, quit the VM and re-launch UTM. Open the VM settings again and select `Export Log...` and attach it here.

[UMT-Alpine-Log-030321](https://gist.github.com/8thHalfHour/a72d335002320b7e9a66c529c7cad5bb)

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since GitHub has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

I am unsure how to get to the `config.plist`.

**Comment by osy** [comment]
What happens when you try to pan the screen with your fingers? On my ArchLinux install it scroll fine.

**Comment by 8thHalfHour** [comment]
That’s interesting. I an unable to do so. My fingers on the screen does nothing. I tried two fingers, one finger, and three fingers — sliding them does nothing. I also tried with Apple Pencil 2, but same result. I can take a screen capture vid and link it here? Ooof, now that I think about it, though, I’m not sure you’d be able to see what my fingers are doing that way. I could take a regular video, then? If that would be helpful? Or is there anything else I can give you? I will also try Arch and Ubuntu and see if they also experience an issue. So far, I’ve only worked with Alpine and Puppy. 👍🏻

**Comment by 8thHalfHour** [comment]
With the very tiny distros like Alpine, I boot to tty0 only unless/until I install a desktop environment. Could that be an issue for scrolling the screen history?

**Comment by osy** [comment]
@8thHalfHour I just realized looking at your logs that you are not in Console Only mode (Display -> Type -> Console Only). Since you are emulating a VGA that the VM is outputting to and there's no mouse/tablet device being emulated, there is no way for your touch inputs to work. This is as expected and is exactly what would happen if you run this OS on a real computer (you won't get anything from the mouse). You can either install an OS with a GUI (such as Debian or Ubuntu) or use Console Only mode which emulates a terminal instead of VGA (so you can scroll with your fingers).

**Comment by 8thHalfHour** [comment]
Hi, @osy. I was just coming here to let you know that there is no issue with Debian, Ubuntu, and Arch Linux; they scroll correctly. I will attempt to install a GUI environment in Alpine and see if that changes anything. Will it mess up the installation if I switch between console-only and vga modes in the VM? Also, why do you suppose my machine not emulating a mouse in Alpine and Puppy?  (Thank you for your help with this!)
