### ISSUE TITLE
Can't click with Bluetooth Mouse when guest uses PS/2 input

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2363]
When running a guest with a PS/2 mouse, iPadOS pointer interactions stop working. 
This means one must click-and-drag to move the guest's pointer and (left-) clicking the VM doesn't register as a click in the guest.

**Configuration (required)**
* UTM Version: latest
* OS Version: latest
* Device Model: iPad Pro 11"
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? Xcode

VM: create a VM with the 1996 PC system, that includes a PS/2 pointing device and keyboard by default.

**Comment by osy** [comment]
So currently we use a USB tablet device to send absolute coordinates to the VM. For legacy PS/2 emulation we can only send delta coordinates and we cannot query the current mouse position either. It should be possible to translate touch events on the trackpad directly to mouse deltas.
