### ISSUE TITLE
Image size doesn’t match size reported in guest

### ISSUE THREAD

**Issue by Nanoc-ice** [utmapp/UTM#237]
Using UTM version 0.6 and 0.7 with Manjaro linux guest, I have a 10G image.  While inside the guest I look at the space used and it reports 4.5G and when I look at the UTM image outside (Via Files) it has it as 8.15G.  As I have added and removed packages since installing the guest it seems, maybe, the space is not freed.  

Since it takes a bit of time to start up, I use the suspend and resume most of the time.  Would suspend represent some of the size when looking at it from the Files app?

Or, there were times where the app crashed when the guest was running/suspended and it had to reboot.  Would there be some remnants left in there that would make it increase?

Is it possible to free up that space or is this the way that it has to be?

**Comment by osy86** [comment]
This isn’t a UTM issue. It’s a qemu issue and exists with any VM. When you specify 10GB all that means is that the image won’t be larger than 10GB. Different file systems, fragmentation, hidden files, and a lot of other factors affect the size of the file. If size is an issue, make a smaller disk image.
