### ISSUE TITLE
mprotect failed: Permission denied

### ISSUE THREAD

**Issue by ouchkernel** [utmapp/UTM#2370]
I have tried serval different bootable linux x86_64 ISO and I keep getting `mprotect failed: Permission denied` in the debug.log. During the boot it's also showing `Boot failed:  Could not read from CDROM  (code 0003).

```
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: warning: global PIIX4_PM.disable_s3=1 not used
```

**Comment by osy** [comment]
What OS? What device? Please include the information from the issue template.

**Comment by ouchkernel** [comment]
> What OS? What device? Please include the information from the issue template.

I have tried Ubuntu, Fedora, Oracle Linux with Nvme, IDE and VirtIO. where can I find the issue template?

**Comment by osy** [comment]
When you clicked on “new issue” it asked you if you are creating a new issue for macos or iOS. Then it prefills the issue with a template. You either deleted all that or you chose “blank issue” which means nobody can help you.
