### ISSUE TITLE
Error in v2.0.23 with two IDE drives

### ISSUE THREAD

**Issue by PhotoNomad0** [utmapp/UTM#2382]
**Describe the issue**
I see an error when launching a VM in v2.0.23 with two IDE drives.  It says only one IDE supported. Did not see this error in v2.0.22.

<img width="267" alt="Screen Shot 2021-03-14 at 8 22 48 PM" src="https://user-images.githubusercontent.com/14238574/111089654-29589780-8503-11eb-8ae3-f111582870a4.png">

**Configuration**
* UTM Version: v2.0.23
* OS Version: MacOS Big Sur 11.3 Beta (20E5196f)
* Apple Silicon

**Debug log**
Running:  -L /Applications/UTM.2.0.23.app/Contents/Resources/qemu -S -qmp tcp:127.0.0.1:4000,server,nowait -vga none -spice port=4001,addr=127.0.0.1,disable-ticketing,image-compression=off,playback-compression=off,streaming-video=off -device qxl-vga -smp cpus=3,sockets=1,cores=3,threads=1 -machine q35,vmport=off -accel tcg,thread=multi,tb-size=1536 -global PIIX4_PM.disable_s3=1 -global ICH9-LPC.disable_s3=1 -m 6144 -device intel-hda -device hda-duplex -name "Windows 10" -device usb-ehci -device usb-tablet -device usb-mouse -device usb-kbd -device ide-hd,drive=drive0,bootindex=0 -drive "if=none,media=disk,id=drive0,file=/Users/blm/Library/Containers/com.utmapp.UTM/Data/Documents/Windows 10.utm/Images/disk-0.qcow2,cache=writethrough" -device ide-cd,drive=drive1,bootindex=1 -drive if=none,media=cdrom,id=drive1 -device e1000e,mac=62:6F:23:50:1A:26,netdev=net0 -netdev user,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -device virtserialport,chardev=charchannel1,id=channel1,name=org.spice-space.webdav.0 -chardev spiceport,name=org.spice-space.webdav.0,id=charchannel1 -uuid B63440F6-8BFD-4E99-AB79-5465AC323398 -rtc base=localtime
libqemu-x86_64-softmmu.utm.dylib: -accel tcg,thread=multi,tb-size=1536: warning: Guest expects a stronger memory ordering than the host provides
This may cause strange/hard to debug errors
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: qemu_mprotect__osdep: mprotect failed: Permission denied
libqemu-x86_64-softmmu.utm.dylib: -device ide-cd,drive=drive1,bootindex=1: Can't create IDE unit 1, bus supports only 1 units

**Upload VM**
[config.plist.zip](https://github.com/utmapp/UTM/files/6137990/config.plist.zip)

**Comment by osy** [comment]
Fixed in ac8021226c9538bd4009d3274521912275230fe6

**Comment by ProBlox42R** [comment]
b
