### ISSUE TITLE
Error in v2.0.23 with NVMe drive

### ISSUE THREAD

**Issue by PhotoNomad0** [utmapp/UTM#2383]
**Describe the issue**
I see an error when launching a VM in v2.0.23 with a NVMe drives.  Did not see this error in v2.0.22.

<img width="271" alt="Screen Shot 2021-03-14 at 8 42 02 PM" src="https://user-images.githubusercontent.com/14238574/111090449-24e1ae00-8506-11eb-8e07-6709b5f9f650.png">

**Configuration**
* UTM Version: v2.0.23
* OS Version: MacOS Big Sur 11.3 Beta (20E5196f)
* Apple Silicon

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/6138039/debug.log)

**Upload VM**
[config.plist.zip](https://github.com/utmapp/UTM/files/6138042/config.plist.zip)

**Comment by braeden-slatyer** [comment]
I can confirm I get the same issue on my Apple Silicon system
