### ISSUE TITLE
Error in v2.0.24 booting from NVMe drive

### ISSUE THREAD

**Issue by PhotoNomad0** [utmapp/UTM#2385]
**Describe the issue**
When booting a VM in v2.0.24 boot disk on NVMe drive is not found:

![Screen Shot 2021-03-16 at 8 41 51 AM](https://user-images.githubusercontent.com/14238574/111311068-25786280-8634-11eb-90d8-cdaed2698318.png)

**Boots correctly in v2.0.22**

**Configuration**
* UTM Version: v2.0.24
* OS Version: MacOS Big Sur 11.3 Beta (20E5210c)
* Apple Silicon

**Crash log**
N/A

**Debug log**
Running:  -L /Applications/UTM.app/Contents/Resources/qemu -S -qmp tcp:127.0.0.1:4002,server,nowait -vga none -spice port=4003,addr=127.0.0.1,disable-ticketing,image-compression=off,playback-compression=off,streaming-video=off -device virtio-ramfb -cpu cortex-a72 -smp cpus=4,sockets=1,cores=4,threads=1 -machine virt,highmem=off -accel hvf -accel tcg,tb-size=2048 -bios /Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd -boot order=d -m 8192 -device intel-hda -device hda-duplex -name "Windows For Arm" -device qemu-xhci -device usb-tablet -device usb-mouse -device usb-kbd -device nvme,drive=drive0,serial=drive0 -drive "if=none,media=disk,id=drive0,file=/Users/blm/Library/Containers/com.utmapp.UTM/Data/Documents/Windows For Arm.utm/Images/Windows10_InsiderPreview_Client_ARM64_en-us_21286.qcow2,cache=writethrough" -device usb-storage,drive=drive1,removable=true,bootindex=0 -drive if=none,media=cdrom,id=drive1 -device virtio-net-pci,mac=EE:F6:46:EE:0F:01,netdev=net0 -netdev user,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid 2B1FA9CA-ECC4-4382-86F7-F139288CC15C -rtc base=localtime

**Upload VM**
[config.plist.zip](https://github.com/utmapp/UTM/files/6149014/config.plist.zip)

**Comment by conath** [comment]
This issue was also reported by someone on the UTM Discord server. Their Debug Log is attached (though it only contains the QEMU command).
[debug.log](https://github.com/utmapp/UTM/files/6152714/debug.log)

**Comment by simonerancati** [comment]
When you start the VM press esc to open the bios, then go into boot manager and select "UEFI QEMU NVMe Ctrl drive0 1" and Windows should now boot. You have to do this every time you boot the VM.
