### ISSUE TITLE
UTM MacOS under App Store can run on Mac mini i5 but not Mbp 2019 i9

### ISSUE THREAD

**Issue by kwccoin** [utmapp/UTM#2389]
**Describe the issue**
I use the Debian (both minimum and the xfce).  

I run the usually apt-get update/upgrade first.  The i9 default cannot run UTM (as it has 8 cores.  I adjust it to 1/2/4.  1 is very slow and 2 is acceptable and 4 is ok.  But none of i9 can run upgrade, it just hang there.  My i9 has 32GB memory.

May I stress that macmini i5 is ok.  I can even do build-essentials and compile c/c++/asm etc. under i5, which has 64 GB memory.

**Configuration**
* UTM Version: 2.0.22(22)
* OS Version: macOS Big Sur 11.2.2
* Intel or Apple Silicon? Intel

**Crash log**
There is no crash; the system just hang

**Debug log**
done see attached 

**Upload VM**
done see attached but need to add a file extension .txt

For the actual terminal command it is here:

apt-get update ok

```debian@debian:~$ sudo apt-get update
[sudo] password for debian: 
Sorry, try again.
[sudo] password for debian: 
Sorry, try again.
[sudo] password for debian: 
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Reading package lists... Done
```

but I can't show the log of the "sudo apt-get upgrade" but it works for awhile until it can't

see screen dump when it freeze:

<img width="1037" alt="Screenshot 2021-03-17 at 7 32 48 PM" src="https://user-images.githubusercontent.com/7194447/111461064-b562fd00-8757-11eb-9c79-6ea114e4cb99.png">

[debug.log](https://github.com/utmapp/UTM/files/6156005/debug.log)

[config.plist.txt](https://github.com/utmapp/UTM/files/6156030/config.plist.txt)

**Comment by osy** [comment]
One thing you can try is to select a CPU in the System settings (advanced). Choose something older like Haswell. That way both your machines will be emulating the same CPU.
