### ISSUE TITLE
Can't disable CPU Flag in UI

### ISSUE THREAD

**Issue by mikegrima** [utmapp/UTM#2395]
**Describe the issue**
Hello!

There is a QEMU issue with Ubuntu installations on some mac hardware where you need to set the following CPU setting: `-cpu host,-rdtscp`. Unfortunately, there doesn't appear to be a good way to do this via the UTM UI. For more details on this particular issue, see this https://bugs.launchpad.net/qemu/+bug/1894836. Bascially, there is no easy way to keep everything the same, but add a `-rdtscp` flag.

The alternative is to set the CPU to `qemu64`, but this may result in poorer performance.

**Configuration**
* UTM Version: 2.0.24 (24)
* OS Version: MacOS Big Sur 11.2.3
* Intel or Apple Silicon? Intel

**Crash log**
No crash

**Debug log**
No other logs

**Upload VM**
The following `config.plist` is what I have that, so far works really well. I would prefer to use the host option though if I could: 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ConfigurationVersion</key>
	<integer>2</integer>
	<key>Debug</key>
	<dict/>
	<key>Display</key>
	<dict>
		<key>ConsoleFont</key>
		<string>Menlo</string>
		<key>ConsoleFontSize</key>
		<integer>12</integer>
		<key>ConsoleTheme</key>
		<string>Default</string>
		<key>DisplayCard</key>
		<string>qxl-vga</string>
		<key>DisplayDownscaler</key>
		<string>linear</string>
		<key>DisplayUpscaler</key>
		<string>linear</string>
	</dict>
	<key>Drives</key>
	<array>
		<dict>
			<key>ImageType</key>
			<string>cd</string>
			<key>InterfaceType</key>
			<string>ide</string>
			<key>Removable</key>
			<true/>
		</dict>
		<dict>
			<key>ImagePath</key>
			<string>disk-0.qcow2</string>
			<key>ImageType</key>
			<string>disk</string>
			<key>InterfaceType</key>
			<string>virtio</string>
		</dict>
	</array>
	<key>Info</key>
	<dict>
		<key>Icon</key>
		<string>ubuntu</string>
		<key>IconCustom</key>
		<false/>
	</dict>
	<key>Input</key>
	<dict>
		<key>InputLegacy</key>
		<false/>
	</dict>
	<key>Networking</key>
	<dict>
		<key>NetworkCard</key>
		<string>rtl8139</string>
		<key>NetworkCardMAC</key>
		<string>42:31:67:B8:31:26</string>
		<key>NetworkEnabled</key>
		<true/>
	</dict>
	<key>Printing</key>
	<dict/>
	<key>Sharing</key>
	<dict>
		<key>ClipboardSharing</key>
		<true/>
	</dict>
	<key>Sound</key>
	<dict>
		<key>SoundCard</key>
		<string>AC97</string>
		<key>SoundEnabled</key>
		<true/>
	</dict>
	<key>System</key>
	<dict>
		<key>Architecture</key>
		<string>x86_64</string>
		<key>BootDevice</key>
		<string>cd</string>
		<key>CPU</key>
		<string>qemu64</string>
		<key>CPUCount</key>
		<integer>6</integer>
		<key>ForceMulticore</key>
		<true/>
		<key>JITCacheSize</key>
		<integer>0</integer>
		<key>Memory</key>
		<integer>4096</integer>
		<key>SystemUUID</key>
		<string>647EF957-FA35-4411-B2D6-52621EF1720B</string>
		<key>Target</key>
		<string>q35</string>
	</dict>
</dict>
</plist>
```

On another note, **thank you all so much for this project!** This has finally satisfied my itch for a proper OSS VM solution on MacOS.

**Comment by osy** [comment]
Hmm this will be tricky to implement in the UI (without cluttering). If anyone has a good idea, please let me know.

**Comment by mikegrima** [comment]
I think one way to do it is to make each checkbox have 3 states, a `+`, `-`, and an empty state.

**Comment by osy** [comment]
1) Not sure that’s possible with standard controls on macos.
2) Not sure that’s possible with swiftui
3) What about iOS?

**Comment by mikegrima** [comment]
I do see a mixed checkbox: https://developer.apple.com/design/human-interface-guidelines/macos/buttons/checkboxes/

**Comment by osy** [comment]
Yes but that’s not +, -

**Comment by mikegrima** [comment]
Another alternative is if we can do a line-item override in the QEMU settings.

**Comment by conath** [comment]
@mikegrima have you tried adding the `-cpu host,-rdtscp` as an added line in the QEMU arguments page of the VM settings? It should override the auto-generated line, if I remember correctly.

**Comment by mikegrima** [comment]
I just installed the latest version of UTM on homebrew (2.1.2), and did a fresh install of ubuntu (set to x86_64) and everything just worked out of the box without me having to do anything special. So I think this can be closed.

On a totally un-related side note, is there a way to force UEFI? Looking at a lot of cloud images, many appear to only support UEFI only.

**Comment by conath** [comment]
@mikegrima Ypu can import the fd file in the Drives section of the VM configuration, then change its type to BIOS.
