### ISSUE TITLE
Create self contained VM with  disk image in bundle rather than Container

### ISSUE THREAD

**Issue by hstriepe** [utmapp/UTM#2397]
On macOS I would prefer the VM descriptor files and disk in a bundle in the regular file system instead of a container. I am not using the App Store. This is how VMware and Parallels work.

**Comment by hotdang-ca** [comment]
I'd second this; As I have just the 256GB m1 model, I run all my VMs off of a USB4 drive.

**Comment by Xodiced** [comment]
I also run my VM's off an external SSD. I would love if we could specify where to save the virtual disk at.  ATM I am waiting for this to be implemented before I can switch to UTM, which I am eagerly waiting to do.

**Comment by osy** [comment]
Should be addressed in #1205
