### ISSUE TITLE
Cannot create ramdisk

### ISSUE THREAD

**Issue by Majhool** [utmapp/UTM#240]
![E4585A30-39A6-415A-883D-D918B3DF437B](https://user-images.githubusercontent.com/44234479/78774765-d181ea00-799d-11ea-9c47-c3ec36475c35.png)

I’m use linux-5.6.3.tar.xz

**Comment by osy86** [comment]
This is a QEMU error. Suggestion: get a debug log and look at the qemu command and try to run it on your computer. You'll get the same error and then you can debug the issue.
