### ISSUE TITLE
Trackpad scroll super fast in guest OS

### ISSUE THREAD

**Issue by RobMaskell** [utmapp/UTM#2400]
**Describe the issue**
I have a POP_OS linux VM running in a UTM VM on a Intel Mac book Pro. In the guest OS the trackpad scrolling is ridiculously quick, the setting in the guest OS to control it doesn't have much effect.

Is there any Spice / QEMU setting that would help with this?

**Configuration**
* UTM Version: 2.0.25 (25)
* OS Version: 11.2.3
* Intel or Apple Silicon? Intel

**Crash log**
No crashes

**Debug log**
No debugs

**Upload VM**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ConfigurationVersion</key>
	<integer>2</integer>
	<key>Debug</key>
	<dict>
		<key>DebugLog</key>
		<true/>
	</dict>
	<key>Display</key>
	<dict>
		<key>ConsoleFont</key>
		<string>Menlo</string>
		<key>ConsoleFontSize</key>
		<integer>12</integer>
		<key>ConsoleTheme</key>
		<string>Default</string>
		<key>DisplayCard</key>
		<string>qxl-vga</string>
		<key>DisplayDownscaler</key>
		<string>linear</string>
		<key>DisplayFitScreen</key>
		<true/>
		<key>DisplayUpscaler</key>
		<string>linear</string>
	</dict>
	<key>Drives</key>
	<array>
		<dict>
			<key>ImagePath</key>
			<string>disk-0.qcow2</string>
			<key>ImageType</key>
			<string>disk</string>
			<key>InterfaceType</key>
			<string>ide</string>
		</dict>
	</array>
	<key>Info</key>
	<dict>
		<key>Icon</key>
		<string>ubuntu</string>
		<key>IconCustom</key>
		<false/>
	</dict>
	<key>Input</key>
	<dict>
		<key>InputLegacy</key>
		<false/>
	</dict>
	<key>Networking</key>
	<dict>
		<key>NetworkCard</key>
		<string>rtl8139</string>
		<key>NetworkCardMAC</key>
		<string>F6:3A:C0:6E:7C:F9</string>
		<key>NetworkEnabled</key>
		<true/>
	</dict>
	<key>Printing</key>
	<dict/>
	<key>Sharing</key>
	<dict>
		<key>ClipboardSharing</key>
		<true/>
	</dict>
	<key>Sound</key>
	<dict>
		<key>SoundCard</key>
		<string>AC97</string>
		<key>SoundEnabled</key>
		<true/>
	</dict>
	<key>System</key>
	<dict>
		<key>Architecture</key>
		<string>x86_64</string>
		<key>BootDevice</key>
		<string>hdd</string>
		<key>CPU</key>
		<string>default</string>
		<key>CPUCount</key>
		<integer>4</integer>
		<key>JITCacheSize</key>
		<integer>0</integer>
		<key>Memory</key>
		<integer>4096</integer>
		<key>SystemUUID</key>
		<string>F14DEF77-59EE-4FF4-8BD0-121C894E89DA</string>
		<key>Target</key>
		<string>q35</string>
	</dict>
</dict>
</plist>
```

**Comment by RobMaskell** [comment]
Worth noting that this makes the VM really not great (unusable) for coding in my IDE of choice, scrolling code and logs is crazy fast. Also it doesn't happen with the same guest OS in other virtualisation apps

**Comment by osy** [comment]
The problem is that scrolling is emulated by sending a many scroll-up button emulated presses while iOS has a continuous Y delta. So different OS interprets it differently. It can probably be configured in the guest OS (how fast to interpret the scrolls). I tuned the speed to Windows so it probably doesn't work well on other OSes. Maybe we should add a slider in the options to configure the scroll speed.

**Comment by RobMaskell** [comment]
Thanks for the response, I did use the guest OS (Linux in this case) settings to set the scroll speed to the minimum speed and it barely made a difference

**Comment by sylvoie** [comment]
Hello,

I'm on iMac an have the same issue with Apple Magic Mouse. No option to manage the mouse wheel scroll speed in guest OS!

The only solution found is "imwheel" but not easy to configure.

Someone have any suggestion?

Thank's

**Comment by RobMaskell** [comment]
Thank you, much more usable in 2.1.1

**Comment by ianling** [comment]
I am having the same issue again in 3.1.5 -- scrolling is extremely fast on a magic mouse and makes anything that requires scrolling borderline unusable. This is on an Ubuntu guest and M2 host.

**Comment by Licanueto** [comment]
Same here on 4.4.4, M1 host and Debian+Mate guest. I'm resorting to scrolling using the arrow keys :upside_down_face:

**Comment by erikschul** [comment]
@osy Perhaps a simple solution would be to add a custom setting for a scroll factor?

in https://github.com/utmapp/UTM/commit/f2cf98fceab13f0941325496b7c9c8c706e19988

you use `inputDelegate?.mouseScroll(dy: event.deltaY, button: NSEvent.pressedMouseButtons.inputButtons())`

maybe you could use `dy = event.deltaY * someFactor` where `someFactor` is a decimal like `0.87` configurable in UTM for the specific VM?
