### ISSUE TITLE
AppleSpell being triggered?

### ISSUE THREAD

**Issue by rossburton** [utmapp/UTM#2404]
I might be entirely mistaken, but I'm running a job inside UTM which causes a lot of output and AppleSpell is showing as taking 50% CPU in the Activity Monitor.

Is the spell checker running on the console?

Feel free to tell me I'm an idiot but there's pretty strong correlation between this job running and the CPU usage...

**Comment by osy** [comment]
This all goes through Apple's WKWebView apis so I'm not surprised if they do something weird like run spell checker on all the output. Maybe there's some way to disable it for a webpage?

**Comment by rossburton** [comment]
I've no idea how the terminal is implemented but maybe it just needs `spellcheck=false` added to the right elements?

**Comment by osy** [comment]
Hmm, the following is set for the terminal area:

```js
  this.screen_ = doc.createElement('x-screen');
  this.screen_.setAttribute('contenteditable', 'true');
  this.screen_.setAttribute('spellcheck', 'false');
  this.screen_.setAttribute('autocomplete', 'off');
  this.screen_.setAttribute('autocorrect', 'off');
  this.screen_.setAttribute('autocapitalize', 'none');
```

**Comment by osy** [comment]
I tried to do `cat /dev/random | xxd` and it crashed the webview. Will have to find out what happened there.
