### ISSUE TITLE
sound drive & scroll speed 

### ISSUE THREAD

**Issue by amirmoheb** [utmapp/UTM#2418]
I have m1 mbp and I install UTM and then windows 64 arm version installing goes fine and I install spice tools too 
network Everything works perfectly but there are 2 issues 
1- I don't have any sound drive sounds don't work & i tried changing drive through the "edit" section of VM make no difference.
2- the scroll is too fast and it's reverse of its usual work in macOS .
my macOS version is 11.2.3
my utm version is 2.0.25
and i'm on mac silicon

**Comment by RobMaskell** [comment]
I noticed the scroll speed issues too https://github.com/utmapp/UTM/issues/2400 doesn't happen with the same guest OS inn other VM technologies and make IDEs almost impossible to use

**Comment by osy** [comment]
Seems to be tracked in #2400 and #2448
