### ISSUE TITLE
[help]I can't shutdown ipad when utm crashed

### ISSUE THREAD

**Issue by JessyKol** [utmapp/UTM#242]
Hi, crash occurred when I have updated the latest version of 0.8. Now I can't do anything with it. It shows white screen, and I even can't reboot or shutdown. How should I do? Just wait for the battery running out of power? Be anxious! 

Can anyone help me?

**Comment by JessyKol** [comment]
IPad Pro with version 13.4.1

**Comment by fomalsd** [comment]
press vol up, vol down, then hold power button until apple logo shows

**Comment by JessyKol** [comment]
> press vol up, vol down, then hold power button until apple logo shows

It doesn't work, I have tried more than 10 times. It only lock and unlock, and siri works but no app can be open.

**Comment by JessyKol** [comment]
The utm shows white screen, and can't be switched to desktop or any other apps(and settings)

**Comment by fomalsd** [comment]
just make sure you quickly press up+down then keep holding the power button for a really long time and don’t release it until logo shows

**Comment by JessyKol** [comment]
> just make sure you quickly press up+down then keep holding the power button for a really long time and don’t release it until logo shows

It really doesn't work... I don't know why the version 0.8 makes so big bug (maybe ipados's bug)

**Comment by JessyKol** [comment]
I guess wether the system panel or function is restricted when the bug occurs

**Comment by JessyKol** [comment]
> > just make sure you quickly press up+down then keep holding the power button for a really long time and don’t release it until logo shows
> 
> It really doesn't work... I don't know why the version 0.8 makes so big bug (maybe ipados's bug)

**Comment by JessyKol** [comment]
Leave it just running out of power
Maybe only this method.
