### ISSUE TITLE
Two problems 

### ISSUE THREAD

**Issue by sunluckyz** [utmapp/UTM#2426]
Here the description:
I install the utm2.0.25 version in cydia,my iOS version is 14.2 and it’s already jailbroken.when I use a 32-bit system and only if when my architecture is chosen as x64,it won’t start with the choose of x86.

By the way,in some newly released utm version, the performance of the simulation is degraded,in fritz beachmark,my win 7 used to run a higher score such as 0.38 in older version of utm such as utm2.0 beta 9,but in some newer version，there was a significant decline in running score can only reach about 0.18.

**Comment by ty-yqs** [comment]
Different iOS versions might have different results. Are you sure that you ran UTM on the same iOS version?

**Comment by osy** [comment]
The decline in performance may be from the change of QEMU version and that can't be helped. Hopefully a future version will improve performance again. Regarding the architecture, that may also be a QEMU issue or maybe your 32-bit OS has a 64-bit booter (32-bit only systems are really old and may not be supported).
