### ISSUE TITLE
UTM 2.0.25: No working slirp IPv6 DNS in guest, with working IPv6 DNS on host

### ISSUE THREAD

**Issue by HenkPoley** [utmapp/UTM#2429]
**Describe the issue**
Installed Ubuntu Server 20.04.2 ARM64 using this guide: https://mac.getutm.app/gallery/ubuntu-20-04

Not even `ping 1.1.1.1` works. Tried different network cards, and with 'VMWare Paravirtualized Ethernet v3' I see at least vmxnet3 module is loaded in dmesg on the guest. So something is happening.

With the default virtio-net-device  I don't see anything in particular in dmesg. But `ping 1.1.1.1` -> 'ping: connect: Network is unreachable'.

It does have apt caches, so I think must have at some point a working network (during the installer?). But I can't ping during the installer.

**Configuration**
* UTM Version: 2.0.25
* OS Version: 11.2.3 (20D91)
* Apple Silicon

**Crash log**
No crash

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/6273483/debug.log)

Only seems to show the command line to start QEMU.

**Upload VM**
[config.plist.txt](https://github.com/utmapp/UTM/files/6273504/config.plist.txt)

**Comment by osy** [comment]
ping isn’t supposed to work. Try changing the DNS settings if you can’t connect to the internet. See #2353

**Comment by HenkPoley** [comment]
Okay, no ICMP, so `ping` nor `ping6`.

I opened a discussion here: https://github.com/utmapp/UTM/discussions/2435

Something I noticed is that a DNS request from Safari on the host machine goes to 92.168.178.51 (the host's IPv4 address) and then 192.168.178.1 (my router's IPv4 address)

But from the VM (guest) it goes to IPv6 2001:981:9c35:1:a90c:18e8:bf22:caa2 (host temporary/privacy  IPv6) and then to 0:0:fd00::2e3a:fdff (I don't know what/which machine this is)

```
Capturing on 'Wi-Fi: en0'
1116  1044  10.244460 192.168.178.51 → 192.168.178.1 DNS 71 Standard query 0xaee2 HTTPS example.com
 1045  10.244487 192.168.178.51 → 192.168.178.1 DNS 71 Standard query 0xbfcf AAAA example.com
 1046  10.244553 192.168.178.51 → 192.168.178.1 DNS 71 Standard query 0x43b6 A example.com
 1052  10.263920 192.168.178.1 → 192.168.178.51 DNS 99 Standard query response 0xbfcf AAAA example.com AAAA 2606:2800:220:1:248:1893:25c8:1946
 1053  10.265697 192.168.178.1 → 192.168.178.51 DNS 87 Standard query response 0x43b6 A example.com A 93.184.216.34
 1058  10.343510 192.168.178.1 → 192.168.178.51 DNS 127 Standard query response 0xaee2 HTTPS example.com SOA ns.icann.org
-- ^^ Safari -- vv UTM Guest 1st getent --
1619  1536  27.065703 2001:981:9c35:1:a90c:18e8:bf22:caa2 → 0:0:fd00::2e3a:fdff DNS 91 Standard query 0xcd07 AAAA example.com
1754  1688  37.077824 2001:981:9c35:1:a90c:18e8:bf22:caa2 → 0:0:fd00::2e3a:fdff DNS 91 Standard query 0xcd07 AAAA example.com
1866  1817  47.091914 2001:981:9c35:1:a90c:18e8:bf22:caa2 → 0:0:fd00::2e3a:fdff DNS 91 Standard query 0x90a1 A example.com
1951  1929  57.111205 2001:981:9c35:1:a90c:18e8:bf22:caa2 → 0:0:fd00::2e3a:fdff DNS 91 Standard query 0x90a1 A example.com
```

**Comment by HenkPoley** [comment]
I think the IPv6 DNS server is accidentally read with 4 bytes offset.

**Comment by conath** [comment]
This is great info, thank you. This might be the key to fixing #2353. Do you know in which layer of the "stack" of things that comprise UTM this byte offset error might be located? libslirp or QEMU or UTM's interface with QEMU?

Regarding #2435, the nonsense things in the VM network config GUI is a typo in the [Swift frontend](https://github.com/utmapp/UTM/blob/808c731b2343b8cb192283c53514a0b408fbf047/Platform/Shared/VMConfigNetworkView.swift#L93) and has on meaning for the actual VM config.

**Comment by HenkPoley** [comment]
If you want to debug this I would start printing the (hexdump of) the IP address, the IP version (4/6), the source code filename, and the line number everywhere it is passed.

**Comment by PhotoNomad0** [comment]
I've been using network card type `virtio-net-pci` with Ubuntu ARM64. I can browse and do updates.  I see that`rtl8139` also works (from the setup link above), but `virtio-net-device` does not work for me.

**Comment by HenkPoley** [comment]
That _might_ be an entirely different issue. My VMs use rtl8139, but then need the DNS override since my actual DNS resolver on my model has an IPv6 address, but this address is mangled when UTMs slirp tries to talk to to it.

You could also try looking at the issue with `brew install wireshark` & then `sudo tshark | grep example.com`

**Comment by PhotoNomad0** [comment]
> I've been using network card type `virtio-net-pci` with Ubuntu ARM64. I can browse and do updates. I see that`rtl8139` also works (from the setup link above), but `virtio-net-device` does not work for me.

FYI - I must have been testing with older version of UTM when I wrote this.  With 2.0.25 running Ubuntu ARM, I cannot get `virtio-net-pci` nor `rtl8139` networking to work.  Still running on 2.0.22.

**Comment by osy** [comment]
Can you test with IPv6 disabled (use only IPv4 on the guest)? The way it's supposed to work is that slirp sets up a VLAN that is only visible to the guest VM (it sees `10.0.2.3` on the emulated network card and uses macOS APIs to directly try to resolve and then respond). It should work with IPv6 as well, but it's easier to debug the issue with just IPv4.

**Comment by brunocastello** [comment]
I believe that I might have a similar issue with #2407, because on Windows For Workgroups 3.11 after upgrading UTM from 2.0.22, network no longer works. Its still working though for macOS 9 and Windows 98SE. I had to roll back to 2.0.22 and stick to it until a fix is available. However, I have no clue on what's happening or changed between 2.0.22 -> 2.0.27.

**Comment by HenkPoley** [comment]
Sure, if you have an IPv6 DNS server that the host connects to, then the slirp DNS resolver that the guest sees, will send out requests from the host to an IPv6 address that contains only some of the bytes of the actual DNS server addresses.

**Comment by conath** [comment]
It is worth noting that with the upcoming 2.2.0 update, one can switch to Shared or Bridged networking to bypass this issue entirely and get working DNS.
