### ISSUE TITLE
UTM will boot no isos

### ISSUE THREAD

**Issue by jroemer551** [utmapp/UTM#2432]
https://user-images.githubusercontent.com/82119662/113928492-e49be580-97bc-11eb-9099-553850bc8421.MP4

Will not boot any iso spite the settings or iso

jailbreak: taurine
Installed with ReProvision 
iOS 14.3
Latest ver of UTM

**Comment by conath** [comment]
Hi, how did you set up your VM's drives? Make sure to have the CD drive as a "Removable" drive (don't import), then start the VM and tap the CD button to select the ISO file.

**Comment by brandonros** [comment]
> Hi, how did you set up your VM's drives? Make sure to have the CD drive as a "Removable" drive (don't import), then start the VM and tap the CD button to select the ISO file.

![image](https://user-images.githubusercontent.com/8949910/115075632-5e248980-9ec9-11eb-9aa4-9c14a37bef0f.png)

any tips?

**Comment by brandonros** [comment]
I see

![image](https://user-images.githubusercontent.com/8949910/115075740-8d3afb00-9ec9-11eb-8e3a-5b3c660beb3b.png)

You have to pick the .ISO here

**Comment by jroemer551** [comment]
I fixed it, the iso I was using was uefi bootable only not bios bootable. > Hi, how did you set up your VM's drives? Make sure to have the CD drive as a "Removable" drive (don't import), then start the VM and tap the CD button to select the ISO file.

**Comment by brandonros** [comment]
Maybe disallow importing ISOs in the future. It correctly knew I meant "CD/DVD ROM Image" but it didn't auto-tick removable.

**Comment by conath** [comment]
> I see
> 
> ![image](https://user-images.githubusercontent.com/8949910/115075740-8d3afb00-9ec9-11eb-8e3a-5b3c660beb3b.png)
> 
> You have to pick the .ISO here

You can also start the VM, then click the CD button in the toolbar to select the ISO. Then restart the VM and it will work.

**Comment by osy** [comment]
Issue seems to be solved but improvement to removable drive selection UI will be improved in the future.
