### ISSUE TITLE
USB passthrough does not work in UTM, but is possible with QEMU(?)

### ISSUE THREAD

**Issue by cobbm** [utmapp/UTM#2439]
I'm using the latest UTM 2.0.25, MacOS Big Sur on an M1 Macbook Air 2020. 
My guest OS is Windows XP SP3 and was installed using the configuration from the UTM Gallery.
I need to use a piece of software only supported by Windows XP with a USB FTDI serial-to-usb device. 
I'm trying to pass USB from the host to guest by adding the following additional QEMU argument to the VM in UTM:

`-usb -device usb-host,productid=0x6001,vendorid=0x0403`

I have tried adding the command on one 'line' and also split by spaces (as it appears the generated QEMU argument list is built this way - with no luck).

When I start the VM, I get the following error:

`libqemu-x86_64-softmmu.utm.dylib: -device usb-host,productid=0x6001,vendorid=0x0403: 'usb-host' is not a valid device model name`

While trying to get this working, I have built a version of QEMU from source, and I can use the argument above to successfully boot the XP guest and pass the USB device through, so it is theoretically possible to support USB passthrough, although it seems UTM's version of QEMU does not allow it?
For some reason, my version of QEMU built from source is so slow and is unusable. It takes about 15 minutes to boot to desktop (!!!) and is unusably slow. UTM's emulation is MUCH faster and is more than usable - I'd also much prefer using UTM for the GUI. 

Is there any way to enable USB passthrough in UTM? Or can I rebuild UTM's QEMU with USB passthrough support?

**Comment by osy** [comment]
Duplicate of #46

**Comment by cobbm** [comment]
Sorry, I'm not sure how this is a dupelicate of #46. I'm talking about the MacOS app, not the iOS app.

**Comment by muddog** [comment]
Same issue here. Any solution for M1 UTM/QEMU to passthrough a USB device?

**Comment by osy** [comment]
The issue was closed because #46 tracked the progress for integrating libusb into UTM. It was originally phrased for iOS because there was no macOS version at the time. It has now been implemented in v2.1.1 and should work by enabling it in the configuration (Sharing) and selecting your usb device from the toolbar.

**Comment by equivalent** [comment]
@osy 
> should work by enabling it in the configuration (Sharing) and selecting your usb device from the toolbar

sorry I have no idea how to enable  this, trying everything in the interface. Can you pls elaborate on this ?

**Comment by equivalent** [comment]
ah ok I've found it. Took me a while to find that button
<img width="892" alt="Screenshot 2022-03-01 at 23 34 13" src="https://user-images.githubusercontent.com/721990/156433309-e4d458a5-3775-47ea-93cf-9bfea281173b.png">

**Comment by osy** [comment]
FYI in the next release it will be moved to Input.

**Comment by dhirajftcsolar** [comment]
Same thing I am looking for so that from M1 MAC USB tty can ported inside the VM and from there to inside docker container.

**Comment by rafaeltoth** [comment]
How's it working in UTM/QEMU? 
I saw that FTDI released VCP drivers for Windows Arm. but much of embedded drivers are still x86 only.
Did you guys managed to get x86 usb drivers working?

**Comment by dhirajftcsolar** [comment]
Yes it worked perfectly

**Comment by rafaeltoth** [comment]
You used via x86 or windows arm?

**Comment by davibe** [comment]
I did everything mentioned here. I do not see my device listed in the usb device ( a keyboard )

**Comment by davibe** [comment]
> I did everything mentioned here. I do not see my device listed in the usb device ( a keyboard ). I am using 3.2.3 (57) on a M1 max MacBook Pro

**Comment by osy** [comment]
There’s been an usb issue that’s being fixed in the next release. For now try 3.1.5

**Comment by pfremm** [comment]
Any updates on this issue?  I am on 3.2.4.  I share the device, but I don't see it ever become available in my linux guest with lsusb.

**Comment by ballo** [comment]
This does not work for me with a ath9k Atheros 802.11n USB device using QEMU 7.1.0.

The driver will load but there are varioiius errors that prevent the device from being made depending how the wind blows.

Guest Linux dmesg log:
[   25.135311] usb 3-3: new high-speed USB device number 2 using xhci_hcd
[   25.286005] usb 3-3: New USB device found, idVendor=0cf3, 
idProduct=9271, bcdDevice= 1.08
[   25.286020] usb 3-3: New USB device strings: Mfr=16, Product=32, 
SerialNumber=48
[   25.286023] usb 3-3: Product: USB2.0 WLAN
[   25.286025] usb 3-3: Manufacturer: ATHEROS
[   25.286027] usb 3-3: SerialNumber: 12345
[   25.288842] usb 3-3: can't set config #1, error -71
UTM log:
Running:  -L /Applications/UTM.app/Contents/Resources/qemu -S -qmp tcp:
127.0.0.1:4000,server,nowait -nodefaults -vga none -spice 
"unix=on,addr=/Users/ball/Library/Group 
Containers/WDNLXAD4W8.com.utmapp.UTM/36789C18-E6FC-4A58-B549-6B00E11C96AF.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off" 
-device virtio-ramfb -cpu host -smp cpus=4,sockets=1,cores=4,threads=1 
-machine virt, -accel hvf -accel tcg,tb-size=256 -drive 
if=pflash,format=raw,unit=0,file=/Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd,readonly=on 
-drive 
"if=pflash,unit=1,file=/Users/ball/Library/Containers/com.utmapp.UTM/Data/Documents/ParrotOS 
arm64 KDE.utm/Images/efi_vars.fd" -boot menu=on -m 1024 -device intel-hda 
-device hda-duplex -name "ParrotOS arm64 KDE" -device 
nec-usb-xhci,id=usb-bus -device usb-tablet,bus=usb-bus.0 -device 
usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device 
qemu-xhci,id=usb-controller-0 -chardev 
spicevmc,name=usbredir,id=usbredirchardev0 -device 
usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 
-chardev spicevmc,name=usbredir,id=usbredirchardev1 -device 
usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 
-chardev spicevmc,name=usbredir,id=usbredirchardev2 -device 
usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 
-device usb-storage,drive=cdrom0,removable=true,bootindex=0,bus=usb-bus.0 
-drive if=none,media=cdrom,id=cdrom0 -device 
virtio-blk-pci,drive=drive0,bootindex=1 -drive 
"if=none,media=disk,id=drive0,file=/Users/ball/Library/Containers/com.utmapp.UTM/Data/Documents/ParrotOS 
arm64 KDE.utm/Images/data.qcow2,discard=unmap,detect-zeroes=unmap" -device 
virtio-net-pci,mac=26:62:F6:DE:8E:59,netdev=net0 -netdev 
vmnet-shared,id=net0 -device virtio-serial -device 
virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev 
spicevmc,id=vdagent,debug=0,name=vdagent -device 
virtserialport,chardev=charchannel1,id=channel1,name=org.spice-space.webdav.0 
-chardev spiceport,name=org.spice-space.webdav.0,id=charchannel1 -uuid 
36789C18-E6FC-4A58-B549-6B00E11C96AF -rtc base=localtime -device 
virtio-rng-pci
qemu-aarch64-softmmu: warning: Spice: playback:0 (0x12c8d6140): setsockopt 
failed, Operation not supported on socket
qemu-aarch64-softmmu: warning: Spice: record:0 (0x12c8d61e0): setsockopt 
failed, Operation not supported on socket

**Comment by ballo** [comment]
FWIW the same exact OS can use the exact same USB device via Parallels Desktop (although the video freezes so that's also a no-go, hopefully a bug in the kernel module that will be fixed in the future)

**Comment by vimtut0r** [comment]
> While trying to get this working, I have built a version of QEMU from source, and I can use the argument above to successfully boot the XP guest and pass the USB device through, so it is theoretically possible to support USB passthrough, although it seems UTM's version of QEMU does not allow it? For some reason, my version of QEMU built from source is so slow and is unusable. It takes about 15 minutes to boot to desktop (!!!) and is unusably slow. UTM's emulation is MUCH faster and is more than usable - I'd also much prefer using UTM for the GUI.

@cobbm How exactly did you compile QEMU with usb support? I tried building it, but still ended up with the same issue.

**Comment by c-goes** [comment]
I'm using UTM 4.0.9 from App Store and I can't connect an external USB SSD (NVMe) to a Linux VM regardless of the USB. Here is the kernel log with USB 2.0 selected, the error with USB 3.0 is similar.
<img width="604" alt="Bildschirm­foto 2022-11-13 um 22 34 58" src="https://user-images.githubusercontent.com/23212798/201545724-4c1efcf6-afc0-4bde-b731-bc700630df32.png">

**Comment by zburgermeiszter** [comment]
I'm experiencing the same issues with a Samsung T7 USB SSD.

When the device is plugged into the Lenovo L32p-30 which has a USB HUB operating in USB 2.0 mode, the SSD is properly recognised.

<img width="1911" alt="Screenshot 2023-04-21 at 14 20 35" src="https://user-images.githubusercontent.com/5986229/233646728-be397740-6d38-403c-8c48-e8b9bceb2cf7.png">

But when the same drive is plugged directly into the Macbook it fails to detect the drive:
<img width="1911" alt="Screenshot 2023-04-21 at 14 21 44" src="https://user-images.githubusercontent.com/5986229/233646742-d80e6ba9-1f8c-40fb-9257-919b62711a65.png">

The UTM USB sharing mode in both cases is USB 2.0.

**Comment by AlanVK2ZIW** [comment]
June 2023 New Mac mini M2 here, UTM Ver 4.2.5 (81) 
VM: Debian from the UTM list.
Two USB devices: C-Media CM108 for sound, FTDI serial for radio programming,
on a SATECHI stand-hub for the Mac mini. (plugs into the FireWire port)
Both available to other Mac software.
VM settings -> Input: USB2  
VM dmesg and lsusb, nothing found (except keyboard, mouse etc.)

**Comment by mx1up** [comment]
> I'm experiencing the same issues with a Samsung T7 USB SSD.

same problem here with same device

**Comment by marshalleq** [comment]
All I'm trying to do, is to see a Time Machine USB drive in the guest OS so that I can restore some files.  The method above to use sharing does not seem to work.  Just adding a note here so that this use case is visible.

**Comment by nan0tEch** [comment]
would be a killer feature if i could use UTM to install any linux / freebsd iso via UTM on an external SSD and boot that SSD in UTM to do some more config / setup. Where when i'm done i could put the drive in a machine and boot that SSD. Or just test learn how to work with such a distro.

**Comment by alexander-zolkin** [comment]
> > ah ok I've found it. Took me a while to find that button <img alt="Screenshot 2022-03-01 at 23 34 13" width="892" src="https://user-images.githubusercontent.com/721990/156433309-e4d458a5-3775-47ea-93cf-9bfea281173b.png">
> 
> It's not the same for me...
> 
> <img alt="image" width="1012" src="https://private-user-images.githubusercontent.com/7412935/287220376-a9582b94-27bd-4a71-bf60-96a32dd8263c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjI4NDEsIm5iZiI6MTcwMTQyMjU0MSwicGF0aCI6Ii83NDEyOTM1LzI4NzIyMDM3Ni1hOTU4MmI5NC0yN2JkLTRhNzEtYmY2MC05NmEzMmRkODI2M2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDFUMDkyMjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTg3ZGY4MTJmODgyMjBhMzNkMjAxMWZiZWY1ZDk5YjlhNGNjYWU3MDZhZjg1MjZjOTdkZTM4Y2UyZWUwODgwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ev3ZFgH9PJXAXvlD6oth9q6BBl6vTbFA7ab9CbOiqag">
> How I can turn on USB sharing here?

Oh, I see, this is because Apple virtualisation...

**Comment by ballo** [comment]
Update (for my use case): UTM is now worse than ever before. The kmod loads but no device ever shows. Tried with two different distros of linux. CPU load also goes crazy high

**Comment by c-goes** [comment]
With Windows VM, it's only possible read files but to copy files to the USB SSD. Windows only shows the error message that the file is too large for the filesystem (which is not true, tested with NTFS and exFAT).

**Comment by lattice0** [comment]
Option does not appear for me, macOS guest, latest UTM. I can only see shared directories just like alexanderer

**Comment by Ambiophonique** [comment]
Same issue here. I’m using UTM 4.6.4 on MacOS Sequoia 15.3.1 on a machine with an Apple Silicon chip.

I don’t manage to use my USB-to-serial cable.

I checked the box "Share USB devices from host". It didn’t work.

I added `-device usb-host,vendorid=0x1234,productid=0x5678` in the QEMU arguments. It didn’t work.

Nothing changes when I plug or unplug the USB-to-serial cable in `dmesg` or `lsusb`.

I also tried to add `-serial /dev/tty.usbserial-0001` to the QEMU command but it makes QEMU crash.

`QEMU error: QEMU exited from an error : qemu-aarch64-softmmu: -serial /dev/tty.usbserial-0001: could not connect serial device to character backend '/dev/tty.usbserial-0001'`

**Comment by yonghi** [comment]
just now i fixed the same problem ,i run x86/64 Windows 7 on my mac mini m2,i uncheck the usb3 support which is contained in the INPUT section and it can be passed successfully.so maybe it is the USB protocol version problem.you can try usb2.

**Comment by ballo** [comment]
> just now i fixed the same problem ,i run x86/64 Windows 7 on my mac mini m2,i uncheck the usb3 support which is contained in the INPUT section and it can be passed successfully.so maybe it is the USB protocol version problem.you can try usb2.

this comment is likely highly misleading due to not mentioning what devices were tested

**Comment by kushalShukla-web** [comment]
> > > ah ok I've found it. Took me a while to find that button <img alt="Screenshot 2022-03-01 at 23 34 13" width="892" src="https://user-images.githubusercontent.com/721990/156433309-e4d458a5-3775-47ea-93cf-9bfea281173b.png">
> > 
> > 
> > It's not the same for me...
> > <img alt="image" width="1012" src="https://private-user-images.githubusercontent.com/7412935/287220376-a9582b94-27bd-4a71-bf60-96a32dd8263c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjI4NDEsIm5iZiI6MTcwMTQyMjU0MSwicGF0aCI6Ii83NDEyOTM1LzI4NzIyMDM3Ni1hOTU4MmI5NC0yN2JkLTRhNzEtYmY2MC05NmEzMmRkODI2M2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDFUMDkyMjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTg3ZGY4MTJmODgyMjBhMzNkMjAxMWZiZWY1ZDk5YjlhNGNjYWU3MDZhZjg1MjZjOTdkZTM4Y2UyZWUwODgwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ev3ZFgH9PJXAXvlD6oth9q6BBl6vTbFA7ab9CbOiqag">
> > How I can turn on USB sharing here?
> 
> Oh, I see, this is because Apple virtualisation...

<img width="888" height="633" alt="Image" src="https://github.com/user-attachments/assets/549891bf-95ca-4317-800f-a711f2eac44d" />

Here i dont find that option USB 3.0 (XHCI) support
