### ISSUE TITLE
CD/DVD image shows as hard disk in VM

### ISSUE THREAD

**Issue by wjk** [utmapp/UTM#2442]
**Describe the issue**  
I am trying to install ReactOS onto my UTM-based VM. I have built a ReactOS installer ISO file, and loaded it into UTM with the “Import Drive” command. However, even though the image type says “CD/DVD (ISO) image”, it appears in ReactOS setup as a UniATA hard drive (see below screenshot).

Furthermore, ReactOS Setup is refusing to install onto the qcow image I created, claiming it could not create a partition. This is even though Setup lists the disk as “New (Unformatted)” and that I can create and destroy partitions using the Setup program without issue. I do not know if this problem is related to the CD-drive bug mentioned above, so my apologies if I filed one issue for two bugs.

<img width="832" alt="Screenshot" src="https://user-images.githubusercontent.com/1915951/114605746-6631be80-9c68-11eb-9d59-1e07f1a21613.png">

**Configuration**  
* UTM Version: 2.0.25 (Mac App Store)
* OS Version: macOS Big Sur 11.2.3
* Intel or Apple Silicon? Intel

**Debug log**  
[debug.log](https://github.com/utmapp/UTM/files/6306030/debug.log)

**Upload VM**  
[config.plist](https://github.com/utmapp/UTM/files/6306035/config.plist.txt)

**Comment by conath** [comment]
This is a known issue. Please do not "Import" the ISO image. Instead, create a new removable drive. Then save the Configuration and click the CD button in the VM details to select the ISO as a virtual CD/DVD.

**Comment by wjk** [comment]
There is no CD button in the VM details. Please see below screenshots.

<img width="1012" alt="Screenshot" src="https://user-images.githubusercontent.com/1915951/115047871-f0676600-9ea6-11eb-8720-7c15a773a537.png">

<img width="1012" alt="Screenshot 2" src="https://user-images.githubusercontent.com/1915951/115047950-0b39da80-9ea7-11eb-9bac-1a4528767aa6.png">

**Comment by conath** [comment]
Please read my message again:

> Please do not "Import" the ISO image. Instead, create a new removable drive. Then save the Configuration and click the CD button in the VM details to select the ISO as a virtual CD/DVD.

After you delete the imported CD and create a removable drive, then there will be a CD button.

**Comment by wjk** [comment]
Oh, _that’s_ how you do it! I didn’t realize you needed to check the “Removable” checkbox to create a CD/DVD drive. You might want to update your documentation to make this clearer. I’m going to close this issue now, as my problem has been solved. Thanks so much!

**Comment by conath** [comment]
You're welcome and thanks for the feedback. The UI around this will be improved in a future version.
