### ISSUE TITLE
No sound card generated on macOS

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2448]
This issue collects information around a sound problem on M1 Macs running UTM 2.0.25 on macOS Big Sur 11.2.3.
It appears that virtual machines on these hosts don't recognize any sound cards, regardless of which sound card is chosen in the VM configuration. (so far all reports received are running various Windows operating systems)

**Configuration**
* UTM Version: 2.0.25
* OS Version: macOS Big Sur 11.2.3
**Apple Silicon**

More information will be added in the comments.

EDIT: the source of this bug has been discovered. See the latest comments.

**Comment by conath** [comment]
Issue #2418 is a partial duplicate of this issue. The user reports no sound devices showing in their Windows 10 ARM install, despite trying multiple different sound card settings in the VM configuration.

**Comment by conath** [comment]
On Discord, UTM user **wiley207** reports the same problem of "no audio device" when using a Windows XP virtual machine on an M1 Mac:
> So it seems with the current version of UTM for MacOS, on Big Sur 11.2.3, Windows XP machines created will not have a working sound card

**Comment by conath** [comment]
Similarly, another Discord UTM user (with a Spanish expletive as a username) reports no audio in their Windows 10 VM, their host computer is a M1 Mac mini on 11.2.3.

**Comment by conath** [comment]
Discord member dionz9 reports "no sound" in their Ubuntu VM on M1 MacBook Air.

**Comment by conath** [comment]
The bug seems to have been introduced with [d6ccf4d](https://github.com/utmapp/UTM/commit/d6ccf4db9bb538717d926223f9499b8797bbace0)

**Comment by osy** [comment]
@conath can you test e1c18e18b5933d1fdc16281769d971a90069c34d ?

**Comment by conath** [comment]
Tested using a Windows 7 32 bit guest in a q35 x86_64 machine, running using Hypervisor on an Intel Mac mini. Intel HDA and AC97 work fine!
