### ISSUE TITLE
usb-host error on macOS

### ISSUE THREAD

**Issue by dekefake** [utmapp/UTM#2452]
M1 Macbook Pro, macOS Big Sur

`libqemu-x86_64-softmmu.utm.dylib: -device usb-host,vendorid=0x0403,productid=0xfa24: 'usb-host' is not a valid device model name`

USB Passthrough does not seems to work on macOS. VM does not start when `-device usb-host,vendorid=0x0403,productid=0xfa24` is used as extra args. I'm running a Windows XP VM.

[VM_configs.zip](https://github.com/utmapp/UTM/files/6337713/VM_configs.zip)

**Comment by osy** [comment]
USB is not supported on UTM v2.0 but is a planned feature for UTM v2.1
