### ISSUE TITLE
Virtualization on iPad Pro with Apple Silicon M1

### ISSUE THREAD

**Issue by kosmonavtika** [utmapp/UTM#2458]
The M1 chip in the latest Macs support virtualization instructions, and since the new iPad Pros (2021) use the same silicon, the instructions should be available for the new iPads as well.

I'd like to request implementation of virtualization support on M1 iPad Pros, if possible.

**Comment by osy** [comment]
Not possible until Apple lets us use hypervisor.framework.

**Comment by xerz-one** [comment]
Out of curiosity, is this possible under jailbreak, even if it doesn't come out of the box on iPadOS?
