### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by crazywhalecc** [utmapp/UTM#246]
**Describe the bug**
When I installed windows XP, my timezone inside this vm is correct but time is still GMT+0.

**To Reproduce**
Install XP.
My iPad Timezone is Hong Kong(GMT+8), XP Timezone is also GMT+8, but time is 8 hours behind. I set my time, and after I restart my vm, it returned.

**Comment by brunocastello** [comment]
using the QEMU argument -rtc base=localtime fixes this.
