### ISSUE TITLE
Cannot pause VMs when running with Hypervisor

### ISSUE THREAD

**Issue by lulor** [utmapp/UTM#2464]
**Describe the issue**
The option to pause any VM is always greyed out. This happens even with fresh VMs downloaded form the gallery

**Configuration**
* UTM Version: 2.0.26
* OS Version: macOS 11.2.3
* Intel or Apple Silicon? Apple Silicon

[debug.log](https://github.com/utmapp/UTM/files/6378369/debug.log)

**Comment by lulor** [comment]
@conath thank you for the explanation, I was afraid it was an error on my end

**Comment by minusf** [comment]
would it be possible to have a tooltip over the disabled button or any kind of note inside the app?

**Comment by billhuey** [comment]
This is an old case. Is there a specific bug report outlining the low level bits with the ARM emulation regarding this issue ?

**Comment by conath** [comment]
This was addressed in other issues, including #3303. Just tested with UTM 4 beta and I am able to pause HVF VM as long as it does not use NVMe storage (#3918) or VirGL graphics card (-gl).
