### ISSUE TITLE
Windows 10 for ARM mouse scroll inverted

### ISSUE THREAD

**Issue by tkreindler** [utmapp/UTM#2468]
**Describe the issue**
Mouse scroll inverted in Windows 10 for ARM image. I've tried reversing the flip flop wheel entry in the registry but for some reason even that didn't work. Reproducible when using Logitech mouse connected via USB to MacBook Pro with M1.

**Configuration**
* UTM Version: 2.0.25 
* OS Version: Big Sur 11.2.3
* Apple Silicon

**Upload VM**
Attatched as txt since plist isn't allowed.
[config.txt](https://github.com/utmapp/UTM/files/6380198/config.txt)

**Comment by yeetusdeletus69** [comment]
that's actually just how it is even in the real native bootcamp for intel Macs

**Comment by TheAlienDrew** [comment]
> **Describe the issue**
> Mouse scroll inverted in Windows 10 for ARM image. I've tried reversing the flip flop wheel entry in the registry but for some reason even that didn't work. Reproducible when using Logitech mouse connected via USB to MacBook Pro with M1.
> 
> **Configuration**
> 
> * UTM Version: 2.0.25
> * OS Version: Big Sur 11.2.3
> * Apple Silicon
> 
> **Upload VM**
> Attatched as txt since plist isn't allowed.
> [config.txt](https://github.com/utmapp/UTM/files/6380198/config.txt)

@tkreind That's the norm for Mac devices when using non-Mac mice. There is no fix for that, other than changing the scroll settings within MacOS itself. https://www.wikihow.com/Change-the-Scroll-Direction-on-a-Mac#:~:text=To%20change%20the%20scroll%20direction%20for%20your%20Mac's%20trackpad%2C%20click,scroll%20direction%20on%20or%20off.

**Comment by houndtt** [comment]
> **Describe the issue**
> Mouse scroll inverted in Windows 10 for ARM image. I've tried reversing the flip flop wheel entry in the registry but for some reason even that didn't work. Reproducible when using Logitech mouse connected via USB to MacBook Pro with M1.
> 
> **Configuration**
> 
> * UTM Version: 2.0.25
> * OS Version: Big Sur 11.2.3
> * Apple Silicon
> 
> **Upload VM**
> Attatched as txt since plist isn't allowed.
> [config.txt](https://github.com/utmapp/UTM/files/6380198/config.txt)

Hi, I was able to change the direction of scroll with my Magic Trackpad using the registry change (https://www.windowscentral.com/how-reverse-scrolling-direction-windows-10). I noted that there were multiple mouse objects in the device manager for me. I just tried the first one and it worked. Did you have multiple objects as well? May be worth a look... I don't have a Logitech mouse connected so I can't replicate the issue on my end.

**Comment by jonathanbell** [comment]
This does seem to be a bug in my opinion. I have "Scroll Direction: Natural" unchecked in Mac OS. This means that if I run two fingers down my trackpad a webpage will scroll down (not up, like the Mac OS default). Like other users, I tried editing the registry in Windows 11 in order to reverse the scrolling (to be the same behaviour as my Mac) but that didn't seem to do anything. 

I can actually open Trackpad: System Preferences in Mac OS, uncheck the Natural scroll direction and go back to Windows and the mouse scroll wheel and trackpad both behave as I'd like. Re-checking the box in the Mac OS makes the direction in the reversed way for me on the Mac OS side of things, but then reverses the direction in Windows.

**Comment by jonathanbell** [comment]
Well gosh... Look what I just found in the setting of my virtual Windows machine... 😃 

![image](https://user-images.githubusercontent.com/1707639/152429587-254696e7-5283-477b-a37c-74983acb8a57.png)

**Comment by choiwilson** [comment]
It works ... thanks

**Comment by kimjansheden** [comment]
> Well gosh... Look what I just found in the settings of my virtual Windows machine... 😃
> 
> ![image](https://user-images.githubusercontent.com/1707639/152429587-254696e7-5283-477b-a37c-74983acb8a57.png)

Hero!

**Comment by rejetto** [comment]
Same problem with UTM 4.0.3 on mac with m1, virtualizing Win11,
but missing the "invert mouse scroll" option. I'm using the trackpad, actually, but even tried to attach a mouse to make the option show up but didn't work.
<img width="630" alt="image" src="https://user-images.githubusercontent.com/1367199/189352897-f2888d62-d184-4a6c-963c-0ab665b8610e.png">

Also tried to change the "flip" entry in the regedit, restarted, and nothing changed.

**Comment by mochaslave** [comment]
> Same problem with UTM 4.0.3 on mac with m1, virtualizing Win11, but missing the "invert mouse scroll" option. I'm using the trackpad, actually, but even tried to attach a mouse to make the option show up but didn't work. <img alt="image" width="630" src="https://user-images.githubusercontent.com/1367199/189352897-f2888d62-d184-4a6c-963c-0ab665b8610e.png">
> 
> Also tried to change the "flip" entry in the regedit, restarted, and nothing changed.

I have the same problem, but after I read the source found out they move this setting to a global config.

![CleanShot 2022-09-29 at 16 49 14](https://user-images.githubusercontent.com/924994/192986371-26ed27e2-95a5-4a1c-9630-4bc5b9f0805c.png)

**Comment by ZaphodBeeblebroxSr** [comment]
> Well gosh... Look what I just found in the settings of my virtual Windows machine... 😃
> 
> ![image](https://user-images.githubusercontent.com/1707639/152429587-254696e7-5283-477b-a37c-74983acb8a57.png)

This is great!  BUT it isn't obvious if you're not familiar with UTM.  Is UTM not able to read my macos settings?  If so, then this is understandable.  If it can see my macos trackpad is set to "normal" or as Apple calls it "uncheck Natural", it should default to what it's been since forever, Down being Down, and Up being Up, or at the very least ASK which I want if my setting is changed.

**Comment by mochaslave** [comment]
> > Well gosh... Look what I just found in the settings of my virtual Windows machine... 😃
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/1707639/152429587-254696e7-5283-477b-a37c-74983acb8a57.png)
> 
> 
> 
> This is great!  BUT it isn't obvious if you're not familiar with UTM.  Is UTM not able to read my macos settings?  If so, then this is understandable.  If it can see my macos trackpad is set to "normal" or as Apple calls it "uncheck Natural", it should default to what it's been since forever, Down being Down, and Up being Up, or at the very least ASK which I want if my setting is changed.

Mate, I'm not in the development cycle as you seem. It's an obviously less documented problem for users. But considering its beta version, you only can find the clue yourself in the source code. ;)

**Comment by ZaphodBeeblebroxSr** [comment]
> > > Well gosh... Look what I just found in the settings of my virtual Windows machine... 😃
> > 
> > 
> > > 
> > 
> > 
> > > ![image](https://user-images.githubusercontent.com/1707639/152429587-254696e7-5283-477b-a37c-74983acb8a57.png)
> > 
> > 
> > This is great!  BUT it isn't obvious if you're not familiar with UTM.  Is UTM not able to read my macos settings?  If so, then this is understandable.  If it can see my macos trackpad is set to "normal" or as Apple calls it "uncheck Natural", it should default to what it's been since forever, Down being Down, and Up being Up, or at the very least ASK which I want if my setting is changed.
> 
> Mate, I'm not in the development cycle as you seem. It's an obviously less documented problem for users. But considering its beta version, you only can find the clue yourself in the source code. ;)

Didn't see anywhere else to mention this to them so I figured I'd add that here.  Apologies if it pinged you unnecessarily, I just didn't want to create a whole new thread for it either.

**Comment by jk779** [comment]
i've almost thrown my mac out of the window after 2 hours of debugging this and manipulating the registry over and over in windows 11. this setting is so un-intuitive, i wonder why it's (all of a sudden) hidden in the global settings?!

**Comment by hao-lee** [comment]
@mochaslave Thanks! Save my life!!!

**Comment by vandrieu** [comment]
- My macOS VM scrolls the normal way
- My Windows VM scrolls the opposite way

As a user switching VMs regularly, I see this global parameter as a regression compared to the old vm-wise parameter.

**Comment by Worko98** [comment]
> > Same problem with UTM 4.0.3 on mac with m1, virtualizing Win11, but missing the "invert mouse scroll" option. I'm using the trackpad, actually, but even tried to attach a mouse to make the option show up but didn't work. <img alt="image" width="630" src="https://user-images.githubusercontent.com/1367199/189352897-f2888d62-d184-4a6c-963c-0ab665b8610e.png">
> > Also tried to change the "flip" entry in the regedit, restarted, and nothing changed.
> 
> I have the same problem, but after I read the source found out they move this setting to a global config.
> 
> ![CleanShot 2022-09-29 at 16 49 14](https://user-images.githubusercontent.com/924994/192986371-26ed27e2-95a5-4a1c-9630-4bc5b9f0805c.png)

After almost 2 years, I should thank you for this. Save my days.

**Comment by tkreindler** [comment]
I haven't personally verified since I don't use a Mac anymore but it sounds like this is fixed, closing it out

**Comment by ZaphodBeeblebroxSr** [comment]
> I haven't personally verified since I don't use a Mac anymore but it sounds like this is fixed, closing it out

I'm not sure if it's "FIXED", more like there's a workaround. It feels like Apple flipped the scroll direction, then a UTM dev added a setting to invert it again by default. It should either be a more obvious button, or just copy the OS' setting IMHO. But you guys do you.

**Comment by DrewMerkle** [comment]
Thank you to the people commenting here for solving a very annoying headache for me. I'll add my voice as just one more person agreeing that it would be better if UTM set scrolling direction to default to whatever the Mac user prefers, with the option to change that both globally and per VM. Respectfully submitted.
