### ISSUE TITLE
Can't exit fullscreen of any VM

### ISSUE THREAD

**Issue by tkreind** [utmapp/UTM#2469]
**Describe the issue**
If I accidentally resize a VM to full screen using the green button on mac there is no way that I can determine other than Command W to close the window. This issue persists on all VMs I've tried and even the blank screen remaining after a VM is shutdown. On most full-screen applications hovering the mouse to the top of the screen exposes the MacOS menu bar allowing you to leave full screen and perform other functions. This bar never comes up for me, fixing that functionality would be ideal but at the very least there needs to be some sort of escape full screen hotkey.

**Configuration**
* UTM Version: 2.0.25 
* OS Version: Big Sur 11.2.3
* Apple Silicon

**Upload VM**
Unnecessary since it's VM independent.

**Comment by conath** [comment]
This happens if you shut down a VM without un-capturing the cursor by pressing ctrl-alt/option. If you un-capture the mouse first and then let the guest shut down, you can move the macOS cursor to the top of the fullscreen window and the menu bar will appear.

**Comment by RubenVerster** [comment]
@conath 
Thank you my man! ^-^
The control+option+command shortcut unlocked my cursor!
But now I now I can toggle my Ubuntu being the main focus on my MacBook :D
