### ISSUE TITLE
Network issue

### ISSUE THREAD

**Issue by muratdk23** [utmapp/UTM#2472]
After installing spice drivers internet in browser works but system still can't see network connection and I can't login my Microsoft account. 

**Configuration**
* UTM Version: 2.0.27
* OS Version: big sur
* Intel or Apple Silicon? Apple Silicon

**Comment by tkreind** [comment]
As far as I can tell the system is able to access the Internet but can’t ping to verify that it can. It’s a somewhat minor issue but it is very annoying as it took me 2 or 3 times to log into my Microsoft account. A fix would be awesome.

**Comment by muratdk23** [comment]
One more thing, also because of this problem I can’t sign in windows insider program and install new insider builds.

**Comment by osy** [comment]
ping doesn't work due to a limitation of QEMU. Future builds will support bridged networking which should be better.
