### ISSUE TITLE
Utm crashes when I close vm ios

### ISSUE THREAD

**Issue by cell-design-4938764** [utmapp/UTM#2479]
When I start utm vm it runs perfect but when I shutdown vm, utm crashed, im in ios 14.3 non jailbroken.

**Comment by osy** [comment]
It doesn’t crash it closes because you closed the vm.

**Comment by cell-design-4938764** [comment]
@osy can you please edit the utm app so if the vm closes it redirects to the utm vm picker and not homescreen?

**Comment by osy** [comment]
#6
