### ISSUE TITLE
Can't reference file paths in custom QEMU arguments due to sandboxing

### ISSUE THREAD

**Issue by GavinPacini** [utmapp/UTM#2483]
**Describe the issue**
When trying to run a VM which has worked before, I see this error:
```
libqemu-aarch64-softmmu.utm.dylib: -drive if=none,media=disk,id=drive0,file=/Users/gavinpacini/Library/Containers/com.utmapp.UTM/Data/Documents/WhonixGateway.utm/Images/Whonix-Gateway-XFCE-15.0.1.7.3-14-g15587d75153fcf0860f1de8d9675cf4889568f00.raw,cache=writethrough: Could not open '/Users/gavinpacini/Library/Containers/com.utmapp.UTM/Data/Documents/WhonixGateway.utm/Images/Whonix-Gateway-XFCE-15.0.1.7.3-14-g15587d75153fcf0860f1de8d9675cf4889568f00.raw': Operation not permitted
```

I have a custom argument for the QEMU command:
```
-cpu cortex-a72 -smp cpus=4,sockets=1,cores=4,threads=1 -machine virt,highmem=off -accel hvf -accel tcg,tb-size=512 -bios /Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd -m 2048 -name "Whonix Gateway" -device qemu-xhci -device usb-tablet -device usb-kbd -device virtio-blk-pci,drive=drive0,bootindex=0 -drive "if=none,media=disk,id=drive0,file=/Users/gavinpacini/Library/Containers/com.utmapp.UTM/Data/Documents/WhonixGateway.utm/Images/Whonix-Gateway-XFCE-15.0.1.7.3-14-g15587d75153fcf0860f1de8d9675cf4889568f00.raw,cache=writethrough" -nic none -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid 1F51737F-55BE-40E7-A6F0-E5B2AD101018 -rtc base=localtime -device virtio-net-pci,netdev=external -device virtio-net-pci,netdev=internal -netdev user,id=external,ipv6=off,net=10.0.2.0/24 -netdev socket,id=internal,listen=:8010
```

<img width="912" alt="Screenshot 2021-05-03 at 13 29 29" src="https://user-images.githubusercontent.com/1523414/116870867-98a15c80-ac13-11eb-8aa4-7773f8c5f3c5.png">

What's very strange is that when I go into the VM settings and then the "QEMU" tab and untick the "Advanced: Bypass...", remove the extra custom command, I can then boot the VM. Then, if I go back into the "QEMU" tab and re-tick the "Advanced: Bypass...", re-add the extra custom command, the VM will boot correctly with my custom command. This VM then works until I quit UTM. 

Once I re-open UTM the VM will fail again with the same "Operation not permitted" error.

I've tried a few things already:

- Checked the permissions on the .utm folder and files inside. All look fine and don't change.
- I've looked at the config.plist file when it's failing and then again when it's working and there is no diff.

Would really appreciate any help on this!

**Configuration**
* UTM Version: 2.0.27
* OS Version: 11.2.3
* Apple Silicon

**Upload VM**
https://drive.google.com/file/d/1aN763gxSqlPP2KN9bOOnyYKZkZJsoJSI/view?usp=sharing

**Comment by cuj** [comment]
type `sudo` and then put space then type in the qemu command you wish to run and press enter

**Comment by osy** [comment]
FYI if you don’t know the answer please refrain from commenting.

**Comment by GavinPacini** [comment]
Thanks @conath!

Okay, is there some work-around which you have found? I see you have posted a diff in #1216 but I'd prefer not to have to fork UTM. 

I commented on #2375 that allowing CocoaSpice to connect to an already running QEMU VM would work for my needs. @osy is this something you'd be open to a PR for (as per my comment on #2375)?

**Comment by austinben** [comment]
On M1, MacOS 11.2.3 as well, I am experiencing a similar issue regarding permission errors when specifying a path to a local -hda, -machine, and -initrd, but I can not even bypass it temporarily as when I attempt to go back to the QEMU tab and uncheck the "Advanced: Bypass..." box, the VM fails to start due to:

 `libqemu-arm-softmmu.utm.dylib: Invalid CPU topology: sockets (1) * cores (8) * threads (1) != maxcpus (1)`
 
 Is there another work-around or fix for this?

**Comment by conath** [comment]
> On M1, MacOS 11.2.3 as well, I am experiencing a similar issue regarding permission errors when specifying a path to a local -hda, -machine, and -initrd, but I can not even bypass it temporarily as when I attempt to go back to the QEMU tab and uncheck the "Advanced: Bypass..." box, the VM fails to start due to:
> 
> `libqemu-arm-softmmu.utm.dylib: Invalid CPU topology: sockets (1) * cores (8) * threads (1) != maxcpus (1)`
> 

This error means you need to supply the `-smp` argument yourself:

`-smp cpus=8,sockets=1,cores=8,threads=8`

Confusingly, the `maxcpus` value is the `cpus=` part of that line.

**Comment by austinben** [comment]
Right, Thank you.

Unfortunately, regardless if I have the "Advanced: Bypass.." enabled or disabled, it refuses to start due to the permissions error. I will keep an eye on this issue for any updates.

**Comment by conath** [comment]
One way to fix this would be to, while parsing the added QEMU arguments, check if there is a path included in the parameter. We could then check if that file exists at the path and, if it does, ask the system to access it through the sandbox.

In pseudocode:

```python
newQemuLine = "-bios /path/to/my/custom/bios.fd"
# Check if the QEMU argument contains a file path, typically begins with "=/" or " /"
if (newQemuLine.contains("=/") || newQemuLine.contains(" /")) {
    string = tryToGetPathFromLine(newQemuLine)
    url = maybeURL(string)
    if (url) {
        system.beginAccessingFile(url)
    }
}
```

What do you think about this @osy?

**Comment by GavinPacini** [comment]
I've for now forked the codebase and added the suggestion you made on #1216 @conath. This works well for my needs, but I'd really like to have a future proof solution which is in the main UTM codebase.

@osy the main reason I am using the custom QEMU arguments is to build a more complex network. Would your preferred way of doing this then be a PR which allows for more complex network settings in the network configuration view?

**Comment by conath** [comment]
@GavinPacini You could disable the UTM networking and add your networking arguments via the QEMU tab of the configuration. Does that work?

**Comment by GavinPacini** [comment]
@conath, wow that actually works quite nicely! I didn't realise I could rely on everything else and just do the networking in the extra config. Thank you!

From my side this can closed now, not sure if you want to tackle the larger issue?

**Comment by conath** [comment]
I'm going to close it for the same reason that #1216 was closed: the advanced config should not be needed, ideally. For specific use cases like yours it is always best to find another solution – be that a new configuration feature or a workaround.

If you need an improved network configuration @GavinPacini, then please open a separate issue (or even better, a PR).
