### ISSUE TITLE
Cannot run with an ia64 CPU

### ISSUE THREAD

**Issue by cheny0y0** [utmapp/UTM#2485]
I try to run an OS with an ia64 dual-core CPU, but UTM crashed.
When I start the VM, UTM quits and back to Home Page of iPadOS.
But it's normal when I use an x86_64 dual_core CPU.
**Configuration (required)**
* UTM Version: UTM-TCI
* OS Version: iPadOS 14.5
* Device Model: iPad mini 5 white with WLAN, 256GB
* no any jailbrokens
* How did you install UTM? 
AltStore on iPad

**Comment by osy** [comment]
IA64 is not a supported architecture. You can try x86 or x86_64 (amd64)

**Comment by cheny0y0** [comment]
> IA64 is not a supported architecture. You can try x86 or x86_64 (amd64)

So how about making ia64 CPU supported?
