### ISSUE TITLE
Feature: disable HVF per VM in macOS VM Config

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2493]
Not sure if this is feasible to implement, as the emulator used is platform and target architecture dependent. Use case is a user with multiple different virtual machines of which some run fine with HVF and some don't. For example, I have a Windows 7 VM that works fine with HVF but a Mac OS X Lion one that doesn't. This means that I need to return to UTM preferences often to check and uncheck "Force slower emulation".

**Comment by osy** [comment]
Added in https://github.com/utmapp/UTM/commit/72bf274a6e711bfe708c67fec6a6f7af3d78bca8#diff-bc255c7c28d4fefbfade29423c6e3d82a824f8a6b6569d24b0e32d2d3bf6a309
