### ISSUE TITLE
VM deletion under Big Sur 11.3

### ISSUE THREAD

**Issue by rimvydukas** [utmapp/UTM#2494]
**Describe the issue**
Hi,
Noticed one strange thing when I tried to delete VM. When I'm trying to delete VM, when I predd on delete button, I get confirmation window if I'm completely sure if I want to delete machine. But I'm clearly seeing that VM gets deleted and without my confirmation. And when I press on confirmation button - app complains that it is not able to delete VM. Is it a gug or am I doing something wrong?

**Configuration**
* UTM Version: 2.0.27
* OS Version: Big Sur 11.3
* Intel or Apple Silicon? Apple Silicon

**Comment by muratdk23** [comment]
It’s a bug. I have the same.

**Comment by conath** [comment]
There is a known issue that means the Delete confirmation shows up twice. There is not supposed to be a second confirmation dialog. #2337
