### ISSUE TITLE
Working with Vagrant

### ISSUE THREAD

**Issue by ajmas** [utmapp/UTM#2496]
I have been using VirtualBox by means of Vagrant to quickly spin up VMs for test scenarios. Mine are generally Linux based. 

It would be useful be able to use UTM in the same way. It is not clear what needs to be done on the UTM side or the Vagrant side to make this work. Maybe it can be done already, but we are just needing a written recipe?

I did look around, but couldn’t find any reference to UTM and Vagrant together.

**Comment by osy** [comment]
Not yet but planned on #2280
