### ISSUE TITLE
Attempting to install UTM via AltStore Repository or IPA fails.

### ISSUE THREAD

**Issue by TyTytheFurKit** [utmapp/UTM#2509]
Each time I attempt to install UTM may it be via the AltStore Repository or the IPA, it crashes the AltStore after it begins trying to install.

I'm using an iPad Mini 2 on iOS 12.5.1

**Comment by TyTytheFurKit** [comment]
I've also reported this to the AltStore developer.

**Comment by SugarRayLua** [comment]
TyTytheFurKit, you may also want to try using Signulous to install UTM. My MAC is too old to use AltStore, so I tried out Signulous, and it worked well for my iPad. (New iPad Pro). Fyi :-)

**Comment by TyTytheFurKit** [comment]
I don't think it's a signing or an AltStore issue, after doing some more trying to install. I think it may be because of the iPad itself. Thanks though. I've checked out Signulous and I don't have the money for it unfortunately.
