### ISSUE TITLE
Provide choice of BIOS to use (EFI/Legacy)

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2510]
As a UTM user I would like to be able to configure a q35 VM that uses EFI BIOS instead of legacy BIOS.

AFAIK UTM already ships with more BIOS files than are available through the system configuration. So this would only require a configuration option.

**Comment by osy** [comment]
What is the use case for EFI vs BIOS in x86_64 VM?

**Comment by conath** [comment]
Use case is to boot modern OS like Windows 10 and Ubuntu in EFI mode instead of relying on a legacy mode. Some OS will not support non-EFI at all.

**Comment by conath** [comment]
I would go as far as suggesting to default to EFI BIOS with the q35 machine but that would deviate from QEMU default behavior and also I don't think the EDK2 has legacy emulation to it would break backwards compatibility. So setting EFI as default might not be a good idea.

**Comment by albertofustinoni** [comment]
I'd like to add another vote for this feature: UEFI is already the standard by which modern operating systems boot, and Windows 10 in particular depends on it for some pretty important functionality (secure boot first and foremost, as well as several features in Windows Defender).

Please add this: it may even help with the blue screen issue plaguing recent Windows 10 versions on q35).

**Comment by conath** [comment]
> I'd like to add another vote for this feature: UEFI is already the standard by which modern operating systems boot, and Windows 10 in particular depends on it for some pretty important functionality (secure boot first and foremost, as well as several features in Windows Defender).
> 
> Please add this: it may even help with the blue screen issue plaguing recent Windows 10 versions on q35).

As a workaround until this is implemented, you can make UTM use an UEFI for your VM manually:

1. [Download the EFI BIOS](https://github.com/utmapp/edk2/files/6523369/edk2-utmlogo-release.zip) (archive includes both x86_64 and ARM 64 / AARCH64 versions however the latter is already included with UTM)
2. Open the Drives Configuration for the VM that should use EFI BIOS.
3. Import the EFI BIOS file into the Drives list (file `OVMF_CODE-utmlogo-RELEASE.fd` is for x86_64 system and file `QEMU-AARCH64_EFI-utmlogo-RELEASE.fd` is for AARCH64 system; Note that UTM includes this EFI BIOS for AARCH64 already).
4. Set drive properties:
    4a. For x86_64 system, change the Interface to PC System Flash (pflash), and leave Type as Disk Image.
    4b. For AARCH64 system, change the Type to BIOS.

UTM will recognize that a BIOS / PFLASH drive has been added and use it instead of the default BIOS.

**Comment by gaurav21r** [comment]
Also, according to #2628 I think an EFI BIOS may be able to provide the default resolutions of the Host MAC on the target OS?
