### ISSUE TITLE
Changing VMs directory

### ISSUE THREAD

**Issue by mrmac189** [utmapp/UTM#2515]
I'd like to install VMs on my external hard drive but I can't find any solution. In Parallels it's very easy to choose directory or change it.

**Comment by conath** [comment]
This is currently not supported. However, on macOS, you can move the virtual hard drive image to your external hard drive and then attach it to the VM as a removable drive.

**Comment by mrmac189** [comment]
it does not work. booting from external disk ends with error.

**Comment by conath** [comment]
> it does not work. booting from external disk ends with error.

Please create a new issue with the VM configuration and Debug log included. Instructions are in the New Issue template. Thank you.

**Comment by mrmac189** [comment]
Sorry, could you please describe steps to make this? As far as I understand, I need to move disk image to desirable folder and then create removable VirtIO drive. After, I need to mount my image, right? Error appears when I try to boot after this.

**Comment by conath** [comment]
> As far as I understand, I need to move disk image to desirable folder and then create removable VirtIO drive. After, I need to mount my image, right? Error appears when I try to boot after this.

You're correct except I would recommend you use USB as the drive interface. Please post the Debug Log from when the error happens.

**Comment by ahvlima** [comment]
This may be an old thread, but it can be done using a symbolic link from ~/Library/Containers/com.utmapp.UTM/Data/Documents to any directory on an external or even a network drive. If not VMs are present, it can start empty. Otherwise copy the contents to the link target. 

I have no problem running on a thunderbolt 3 attached NVMe drive (@40Gbps) or on a network drive (over 10G Ethernet). Both run perfectly (they are both fast). But it can run fine on a 5Gbps USB 3.2 or 1G Ethernet too.

**Comment by Photon9** [comment]
> This may be an old thread, but it can be done using a symbolic link from ~/Library/Containers/com.utmapp.UTM/Data/Documents to any directory on an external or even a network drive. If no VMs are present, it can start empty. Otherwise copy the contents to the link target.
> 
> I have no problem running on a thunderbolt 3 attached NVMe drive (@40Gbps) or on a network drive (over 10G Ethernet). Both run perfectly (they are both fast). But it can run fine on a 5Gbps USB 3.2 or 1G Ethernet too.

I can report similar though... Thank you for the advice. Word to the unwise reading this thread later though:

Do not move the whole containers folder thinking it will save you space. This borked my macOS and I had to move it back which wasn't quite as simple as moving it there.

**Comment by fzanart** [comment]
Any suggestions on how to restore a VM from an external drive? I moved it to free up space on my computer, but now I need to bring it back to run it as smoothly as possible.

**Comment by ktprograms** [comment]
@fzanart

**Comment by ktprograms** [comment]
@fzanart did you move it to an external drive using the Move menu option from within UTM?
If so, right click the shortcut VM and click Clone, this will move it back into the internal sandbox. You can then Remove the external VM and delete it from within Finder.

**Comment by MDanihy** [comment]
I do not have a Move option when right-clicking the VM.

**Comment by garfnodie** [comment]
Here we are in 2026.  Is there still no option to run a VM from a USB drive?

**Comment by conath** [comment]
@garfnodie Please try the following: Open UTM, ctrl-click (right click) a VM in the list, select Move.

**Comment by garfnodie** [comment]
Why can't I create it on the external drive at the beginning?  What if I needed to create a VM larger than the free space on my internal drive?  You've been able to create VM's right on external hdd's since the USB 1.0 days, so there's no reason I shouldn't be able to do that now.

**Comment by conath** [comment]
@garfnodie The space concern shouldn't get in your way here, as VMs are created "sparse" by default. This means they only take up as much space as the VM *actually* writes to disk later, not as much as the hard disk size you specify. 

If you really only want to create new VMs on an external drive, this isn't currently a feature of UTM. Please create a new Issue and describe your preferred User Experience, including where in the app you would like to be asked for the path for new VMs.

**Comment by garfnodie** [comment]
> including where in the app you would like to be asked for the path for new VMs.

This kind of d*ck head response tells me there is no point in submitting a request because it's obvious you don't care.

**Comment by conath** [comment]
@garfnodie Please use a respectful tone. I am simply asking for your opinion on the UX design. I'm not arguing with you.

Let me ask differently: If you had the ability to choose where to create a new VM, at which step in the UTM app would you like to be asked for this location? For example, a setting could be added to UTM settings, or to the New VM wizard.

**Comment by garfnodie** [comment]
I'm not a coder or UI/UX designer, so I'm not the person to decide that.  I just simply wanted VM software that wasn't Oracle or Broadcom, I heard about UTM and got excited, but was surprised it didn't have an ability that other VM software has had for decades at this point.
