### ISSUE TITLE
[Request] Legacy mouse sensitivity

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2522]
The captured mouse speed (mainly when using legacy input) is quite fast. Could there be a way to slow it down, maybe with a speed slider in the Input config?

**Comment by osy** [comment]
Seems to be related to #2400

**Comment by conath** [comment]
FWIW I managed to tame the mouse by turning the guest OS's mouse speed all the way down. However this is still an issue whenever the guest mouse settings are not available (e. g. graphical installers).
