### ISSUE TITLE
VHDX -> QCOW2 Autoconversion

### ISSUE THREAD

**Issue by DumbGameMaker** [utmapp/UTM#2526]
My feature request for UTM is simple:

So for a little background, because of the way QEMU handles VHDX files, it has a tendency to corrupt them, causing errors. For me the two that I have experienced (on Windows 10) is a process initialization BSOD and an error with the sign-in service, but the corruption can cause many others. This is an issue because Windows 10 for ARM gets distributed in the form of a pre-made VHDX disk, and manually converting is a pain.

My request is, if you try to launch a virtual machine with a VHDX file loaded as a boot drive, UTM will display a pop-up asking if you would like to convert the VHDX to QCOW2 automatically.

**Comment by osy** [comment]
This has been implemented for a while now.
