### ISSUE TITLE
PLEASE READ THIS ABOUT UTM CRASH.

### ISSUE THREAD

**Issue by Matoo69** [utmapp/UTM#253]
So first off all i have 11 pro max on 13.4.5b1 and from 13.3.1 to now (today) i cannot get to work utm no matter what i do and which verson i download ( download utm,create vm win xp/7 and press start automatic crash) BUT TODAY I INSTALL ALTSTORE V1.3 AND SIDELOAD UTM AND WORK WITHOUT PROBLEM SO EVERYONE WHO HAVE THE SAME PROBLEM JUSR DOWNLOAD AND INSTALL ALTSTORE (new version) SIDELOAD UTM AND THATS IT! Btw for altstore you dont need to be patriot... for sideload (free account as i have every 7days resign and thats it (or developer every 1 year) new version of altstore v1.3)

**Comment by osy86** [comment]
Thanks for the confirmation but this has been the recommended instruction for weeks.

**Comment by Matoo69** [comment]
Oh sorry than,but myb somone still have the problem like on #95,just try to help :)

**Comment by hmsjy2017** [comment]
Can I use Altstore to sign UTM with an enterprise certificate (.p12)?

**Comment by osy86** [comment]
No. https://getutm.app/install/
