### ISSUE TITLE
Win64 Arm on Mac M1 Mini

### ISSUE THREAD

**Issue by eotfox** [utmapp/UTM#2530]
I'm not finding any info on the network adapter.  Not detected and unsure how to fix this.

Thanks,
Ed

**Comment by conath** [comment]
Hi, this is not an issue related to the functioning of UTM so I'm moving it to Discussions. We also have a [Discord server](https://discord.gg/UV2RUgD) where you can ask support questions, by the way. I will try to answer your question in the next message.
