### ISSUE TITLE
Screamer audio device for PPC mac99 machines not working

### ISSUE THREAD

**Issue by brunocastello** [utmapp/UTM#2548]
**Describe the issue**
The Screamer audio device is not working. I am using both iOS and macOS versions of UTM 2.1.0 Beta, and there is no sound at all coming out in both builds.

Normally, MacOS 9.2 with QEMU Screamer fork produces a sound for any menu click (even in Sound control panel you can test sounds too). But this build is not producing any sound at all for MacOS 9.2. When I use a QEMU Screamer fork from e-maculation forms, there is sound.

Another unrelated issue is that on previous UTM builds, I was able to use 1280x960x32 resolution on MacOS 9.2. Now I cannot use it anymore, the resolution is not listed anymore, thus forcing me to run 1024x768x32, because other resolutions are either too big or too small for me.

**Configuration**
* UTM Version: 2.1.0 Beta
* OS Version: Both (iOS 14.4.2 and macOS Big Sur 11.3
* Intel or Apple Silicon? Intel mac and iPad Pro 12.9" 2nd generation

**Comment by brunocastello** [comment]
@conath - I can test for you if there is another build. Just let me know - I have an OS 9.2.2 VM for this.

**Comment by conath** [comment]
> @conath - I can test for you if there is another build. Just let me know - I have an OS 9.2.2 VM for this.

Can you please share your QEMU arguments? You can get it by opening the UTM VM configuration, click on QEMU tab and then Export QEMU arguments. Can click e.g. on Notes and then copy the text and paste it here. Thanks

**Comment by brunocastello** [comment]
Sure! @conath there you go:

qemu-system-ppc -L /private/var/containers/Bundle/Application/825DB694-F3C5-49DF-B888-C838DE405E35/UTM.app/qemu -S -qmp tcp:127.0.0.1:4444,server,nowait -vga none -spice port=5930,addr=127.0.0.1,disable-ticketing,image-compression=off,playback-compression=off,streaming-video=off -device VGA -cpu g4 -smp cpus=1,sockets=1,cores=1,threads=1 -machine mac99,via=pmu -accel tcg,tb-size=128,split-wx=on -boot menu=on -m 512 -name "MacOS 9.2" -device ich9-usb-ehci1,id=usb-controller-0 -device ich9-usb-uhci1,masterbus=usb-controller-0.0,firstport=0,multifunction=on -device ich9-usb-uhci2,masterbus=usb-controller-0.0,firstport=2,multifunction=on -device ich9-usb-uhci3,masterbus=usb-controller-0.0,firstport=4,multifunction=on -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 -device ide-hd,bus=ide.0,drive=drive0,bootindex=0 -drive "if=none,media=disk,id=drive0,file=/var/mobile/Containers/Data/Application/6CC128D1-352F-4987-AC75-88E6C4B97618/Documents/MacOS 9.2.utm/Images/macOS9.img,cache=writethrough" -device ide-cd,bus=ide.1,drive=drive1,bootindex=1 -drive if=none,media=cdrom,id=drive1 -device sungem,mac=66:C2:26:89:5A:A9,netdev=net0 -netdev user,id=net0,hostfwd=tcp::80-:80,hostfwd=tcp::22-:22 -uuid 1AFED0DA-6802-43D7-A81E-4659EC2FED6B -rtc base=localtime -rtc base=localtime,clock=host -g 1280x960x32 -device usb-tablet

**Comment by conath** [comment]
Seems fine, not seeing an audio device in there but according to release notes that is not required. @osy did you test PPC audio works with https://github.com/utmapp/UTM/commit/17bc4ecaca322ec78e6f8fee4aadf83c44d47914 ?

**Comment by osy** [comment]
I actually don’t have anything to test with. Would be great if someone can send me a img.

**Comment by brunocastello** [comment]
Its actually pretty easy. I think you can use an ISO image from macos9lives.com to make an install.

**Comment by brunocastello** [comment]
> Seems fine, not seeing an audio device in there but according to release notes that is not required. @osy did you test PPC audio works with [17bc4ec](https://github.com/utmapp/UTM/commit/17bc4ecaca322ec78e6f8fee4aadf83c44d47914) ?

Yup its not required. The Screamer fork has no need to declare an audio device

**Comment by osy** [comment]
> Its actually pretty easy. I think you can use an ISO image from macos9lives.com to make an install.
> 
> But, I can test too. I have QEMU Screamer fork running on my mac to compare with UTM.

I can't find it on that site. To make things easy, can you send me a working .utm? That way we can have it fixed quickly.

**Comment by brunocastello** [comment]
I'll try to create a smaller image with an out of the box install

**Comment by conath** [comment]
@brunocastello No need, I've sent one.

**Comment by brunocastello** [comment]
Thanks, @conath !

**Comment by osy** [comment]
So the problem is that screamer supports 44100 Hz while OPUS only supports 48000 Hz. This means the SPICE audio backend is incompatible and probably the reason why audio doesn't work in other configurations. I will add an option to force CoreAudio instead of SPICE.

**Comment by brunocastello** [comment]
Hi, thanks @osy! Errr.... I do not want to look like I'm picky, but I'm curious and while you're at it dealing with the patch, have you also found the reason why the extra video resolutions are no longer available for that VM?

**Comment by osy** [comment]
You should file a new ticket. You can leave out the details since it’s the same. This one will probably get closed soon.

**Comment by brunocastello** [comment]
> You should file a new ticket. You can leave out the details since it’s the same. This one will probably get closed soon.

Sure, no problem. I thought I had done it, but I will do.

**Comment by brunocastello** [comment]
Fixed for macOS, but not for iOS

**Comment by ThomasDBosboom** [comment]
[brunocastello](https://github.com/brunocastello) - your hint about RAM limit fixed it for me!

**Comment by itpick** [comment]
Mine is working on macOS but not on iPhone with the sound:

`qemu-system-ppc -L /var/mobile/Containers/Data/Application/6D22C77A-7490-4BB1-97B3-A611FE97FE80/Library/Caches/qemu -S -spice unix=on,addr=5D9B10A5-16E5-4FE1-9177-0CC0C9426DB8.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off -chardev spiceport,name=org.qemu.monitor.qmp.0,id=org.qemu.monitor.qmp -mon chardev=org.qemu.monitor.qmp,mode=control -nodefaults -vga none -device sungem,mac=0A:9A:C7:79:92:FD,netdev=net0 -netdev user,id=net0 -device VGA,edid=on -smp cpus=1,sockets=1,cores=1,threads=1 -machine mac99,via=pmu -accel tcg,tb-size=64 -device loader,addr=0x4000000,file=/var/mobile/Containers/Data/Application/6D22C77A-7490-4BB1-97B3-A611FE97FE80/Library/Caches/qemu/ppc-ndrvloader -prom-env "boot-command=init-program go" -m 256 -audio none -audiodev spice,id=audio0 -usb -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device virtio-tablet-pci -device ide-hd,bus=ide.0,unit=0,drive=drive245ED61C-4233-4AC8-AC22-E00F87447EC5,bootindex=0 -drive "if=none,media=disk,id=drive245ED61C-4233-4AC8-AC22-E00F87447EC5,file.filename=/private/var/mobile/Containers/Shared/AppGroup/B0BCC7C8-52DC-42C3-998B-0C94CCBD0DB2/File Provider Storage/Downloads/Mac OS.utm/Data/245ED61C-4233-4AC8-AC22-E00F87447EC5.qcow2,discard=unmap,detect-zeroes=unmap" -device ide-cd,bus=ide.0,unit=1,drive=drive858624D8-2192-44D4-BEC3-0CBE3A8A724E,bootindex=1 -drive if=none,media=cdrom,id=drive858624D8-2192-44D4-BEC3-0CBE3A8A724E,readonly=on -name "Mac OS" -uuid 5D9B10A5-16E5-4FE1-9177-0CC0C9426DB8’
