### ISSUE TITLE
USB devices attachment

### ISSUE THREAD

**Issue by rimvydukas** [utmapp/UTM#2549]
Please browse the existing issues and filter by 'enhancement' to make sure this has not already been suggested!
Hi,

Are there any plans to introduce USB devices attachment ability in UTM? Such a feature is a must for virtualisation.

**Comment by osy** [comment]
Duplicate of #46 

check out 2.1.0 beta.

**Comment by rimvydukas** [comment]
You duplicate issue talks about iOS version of UTM and I'm talking about Mac version of UTM.

**Comment by osy** [comment]
Did you open 2.1.0 beta?

**Comment by rimvydukas** [comment]
I'm considering it. Is it possible to install beta over normal version and then normal version over beta?
