### ISSUE TITLE
macOS application

### ISSUE THREAD

**Issue by osy86** [utmapp/UTM#255]
This, along with #132 would allow the user to run the same VM across all their Apple devices. We will likely use Catalyst and Swift UI to make development easier.
- [x] Implement VMs from any storage source (#132)
- [x] Refactor Storyboard to reuse common UI elements (#213)
- [x] Create UI for configuration on macOS
- [x] Create UI for listing VM and running VM on macOS
- [x] Enable KVM for x86_64 for near native speeds

**Comment by conath** [comment]
Another step to add before Mac catalyst app can be made: build the sysroot artefacts for macOS in addition to iOS Simulator.

**Comment by js-john** [comment]
I think KVM is a linux thing. On macOS, the accelerate args should be "-accel hvf".
