### ISSUE TITLE
9pfs directory sharing

### ISSUE THREAD

**Issue by osy** [utmapp/UTM#2551]
https://gist.github.com/woachk/3a7c88d8b04acea8633a6297600f2a21

Apply this to our QEMU fork and implement a way to interface with it.

**Comment by r2r-dev** [comment]
There's some work going on in this regard in other projects as well. This patch-set is not fully functional as for now.

See:
https://github.com/AkihiroSuda/lima/issues/20
https://github.com/NixOS/nixpkgs/pull/122420
https://github.com/Tarik02/qemu/commit/d0bcdb03394579d87e94bef154b8012fc8448903
https://github.com/NixOS/nixpkgs/issues/108984#issuecomment-842192023
https://github.com/r2r-dev/nixpkgs/commit/58142a0fa46a3e920cb4e92fcd0420eeec62ae27

**Comment by jseppanen** [comment]
Looks like virfs/9pfs support on Mac was just merged to QEMU: https://github.com/NixOS/nixpkgs/pull/122420#issuecomment-1061760608

> https://github.com/qemu/qemu/tree/f45cc81911adc7726e8a2801986b6998b91b816e
> https://lists.gnu.org/archive/html/qemu-devel/2022-03/msg02594.html

**Comment by osy** [comment]
Duplicate of #2184
