### ISSUE TITLE
USB passthrough uses ICH9 and USB 3 controller even for pc system

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2554]
Just set up a `pc` system VM in UTM v2.1.0 (Beta) and it puts in a USB-EHCI controller, which is incompatible.

**Comment by tex83br** [comment]
in macos 11 big sur silicon m1, with guest win 7, every time i atach an external storage i got "not recognized"

**Comment by conath** [comment]
[Apparently](https://bugzilla.redhat.com/show_bug.cgi?id=877330) for USB redirect we need either the ICH9 usb "companion" controller or `usb-host`. So I'll close this as "won't fix".
