### ISSUE TITLE
UTM virtual machine console unbearably slow with VoiceOver cursor

### ISSUE THREAD

**Issue by stas-prze** [utmapp/UTM#2555]
**Describe the issue**
When launching a virtual machine in UTM and trying to navigate the interface, for example the tool bar, with the VoiceOver screen reader cursor on Mac it gets very slow.
Voiceover reports that the app is busy all most all the time and getting to different buttons takes around 8 seconds, from the press of the cursor key to the actual cursor getting to the button.
Please fix this if you can.

**Configuration**
* UTM Version: 2.1.0 beta
* OS Version: 11.3.1
* Intel or Apple Silicon? Intel

**Comment by osy** [comment]
This seems like an issue with SwiftUI.

**Comment by osy** [comment]
I’m having trouble reproducing this on 2.2.2 beta running on 11.5 and 12.0 beta. @stas-prze is this still an issue on latest beta for you? If so can you give more details on how to reproduce? Thanks.
