### ISSUE TITLE
Option to only use performance cores when automatically determining core count

### ISSUE THREAD

**Issue by iRonJ** [utmapp/UTM#2557]
**Describe the issue**
I tried out the latest UTM version using an existing qcow and vhdx windows 10 ARM image, and Windows 10 runs qualitatively much slower (less responsive, more GUI tearing), than another compiled version of QEMU.
UTM running Windows 10 arm:
<img width="1288" alt="Screen Shot 2021-05-23 at 2 17 39 AM" src="https://user-images.githubusercontent.com/6108031/119250570-efdd8180-bb6e-11eb-8902-1c19779a5ae4.png">

Standalone Qemu running exact same image:
<img width="1320" alt="Screen Shot 2021-05-23 at 2 21 51 AM" src="https://user-images.githubusercontent.com/6108031/119250572-fb30ad00-bb6e-11eb-9bb1-e912fff6a0d2.png">

My goal is for UTM to be just as fast or faster than standalone Qemu. The launch options when I run qemu by itself are:
[launchwin.sh.txt](https://github.com/utmapp/UTM/files/6527640/launchwin.sh.txt)

**Configuration**
Version 2.0.28 (28)
*MacOS 11.3.1 (20E241)
* Apple Silicon

Comparing to QEMU compiled using these directions:
https://forums.macrumors.com/threads/success-virtualize-windows-10-for-arm-on-m1-with-alexander-grafs-qemu-hypervisor-patch.2272354/

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/6527637/debug.log)

**Upload VM**
[config.plist.txt](https://github.com/utmapp/UTM/files/6527631/config.plist.txt)

**Comment by iRonJ** [comment]
I did a quick test of setting UTM to max cores of 4, and this seems to bring it to parity with my other qemu version. So perhaps there's some issue with using all cores and hypervisor framework?

**Comment by osy** [comment]
@iRonJ I think the issue is that Windows doesn’t understand the difference between the performance cores and the efficiency cores and may have scheduled tasks non-optimally. So forcing it to a lower core count solved it. I’ll consider adding an option to use only the performance core count instead of the total core count.

**Comment by osy** [comment]
Here's the plan: a new global setting "Ignore efficiency cores when determining core count". Manually setting a core count for a VM will still override the automatic count.

**Comment by iRonJ** [comment]
Just a follow up to do this, but i noticed also that playing a youtube video works perfectly fine in my standalone qemu, but there's horrible video artifacts when running through UTM. Any thoughts on what could cause this?

**Comment by osy** [comment]
It may be related to #2569
