### ISSUE TITLE
UTM App for Mac throws an error when opening 'The application requires macOS 11.0 or later."

### ISSUE THREAD

**Issue by iTechOS** [utmapp/UTM#2572]
**Describe the issue**
When i download and open the UTM.dmg file from mac.getutm.app, i get the error :  
"You have macOS 10.15.7. The application requires macOS 11.0 or later."

<img width="424" alt="Screenshot 2021-05-26 at 2 10 04 PM" src="https://user-images.githubusercontent.com/81900008/119610604-13812000-be2c-11eb-992d-0ad9eb25649a.png">

UTM Version 2.0.28

* OS Version: 
10.15.7 Catalina
* Intel or Apple Silicon? 
Intel

**Debug log**
No debug log since UTM app will not open.

**Comment by osy** [comment]
Did you read the error message?

**Comment by iTechOS** [comment]
Oh yeah, sorry. I mis-read the error, thought it was for macOS 10.11.

**Comment by zizlog** [comment]
> Is there no compiled version still working on Catalina. I don't really want to change to Big Sur.
I would like to use the App in Catalina.

I was on Big Sur, then briefly on Monterey until last week and now back on Catalina, which works more smoothly on a mid-2014 MBP Retina. No wonder we need more powerful hardware all the time when application become more inefficient running their code.

Also Monterey didn't like the replacement battery.

I would like to understand, why UTM cant't run in OSX 10.15.x. 

Maybe there is a way to run Qemu without the help of UTM.

**Comment by tifasoftware** [comment]
> > Is there no compiled version still working on Catalina. I don't really want to change to Big Sur.
> > I would like to use the App in Catalina.
> 
> I was on Big Sur, then briefly on Monterey until last week and now back on Catalina, which works more smoothly on a mid-2014 MBP Retina. No wonder we need more powerful hardware all the time when application become more inefficient running their code.
> 
> Also Monterey didn't like the replacement battery.
> 
> I would like to understand, why UTM cant't run in OSX 10.15.x.
> 
> Maybe there is a way to run Qemu without the help of UTM.

Unfortunately, UTM is primarily intended for the newer Macs with Apple Silicon. Intel support is essentially an afterthought, as they're approaching the fringe of losing support.

What system are you trying to emulate?

**Comment by zizlog** [comment]
> What system are you trying to emulate?

Haiku OS x86_64 and eventually some RISC based systems (mainly Linux) down the road including Haiku OS. I looked into the Qemu CLI but don't quite get the performance compared to running it in Virtual Box, which limits guest display resolution to 1600 x 1200 for some reason. With Qemu it easily gets up 2560 x 1600

> Intel support is essentially an afterthought, as they're approaching the fringe of losing support.
That afterthought works on Intel based machines. Might be different in 10 years time, when Apple drops support for the last Intel based Mac. I hat UTM briefly working on Big Sur but I  didn't stay on Big Sur for long.

What do you mean by loosing support?

How much of a difference is it between UTM for Big Sur and UTM for Catalina?
