### ISSUE TITLE
Imported Disk image is not removed from temp dir if cancel creation of VM

### ISSUE THREAD

**Issue by Morac2** [utmapp/UTM#2576]
**Describe the issue**
I ran into an issue where I click cancel when creating a new VM after having imported a disk.   When I tried to create a new VM and import the same disk again I got a "... couldn’t be copied to “Images” because an item with the same name already exists." error.  This persisted after quitting and re-running UTM.

I knew that the disk image must have been copied somewhere so I used fs_usage to determine it had been copied to $TMPDIR/com.utmapp.UTM/Images.   Once I found that I could manually delete the image file.

The bug is that the image is not removed if the VM creation is canceled after the drive is imported (and not deleted prior to canceling.

**Configuration**
* UTM Version: 2.0.28
* OS Version: MacOS 11.4
* Intel or Apple Silicon? : Apple Silicon

**Comment by NosillaCast** [comment]
Thanks for creating this issue @Morac2 - I ran into this on my very first run of UTM on an M1 Mac mini. It crashed when I tried to add the Spice Tools, and I couldn't get going again without finding this image. Having zero experience with UTM, I wasn't sure where to look for it.
