### ISSUE TITLE
Can't install and run Ubuntu

### ISSUE THREAD

**Issue by TruthfulEdict1** [utmapp/UTM#2584]
I can't install Ubuntu. It doesn't work as the guide describes, so I went through the troubleshooting at the bottom of the page here:

https://mac.getutm.app/gallery/ubuntu-20-04

When I type the suggested command fs0:\efi\boot\bootaa44.efi into the shell, all I get is the following error message:

"is not recognized as an internal or external command, operable program, or script file"

I'm not sure what to search for to find existing threads about this, and I'm new to Github so not sure how to browse through the pinned posts either, sorry. 

**Configuration**
* UTM Version: Not sure how to find this, but I just downloaded it today, so the latest version off of the UTM site. 
* OS Version: Big Sur 11.4
* Apple Silicon 

[debug.log](https://github.com/utmapp/UTM/files/6572891/debug.log)

**Comment by winexe0** [comment]
The command is fs0:\efi\boot\bootaa64.efi

**Comment by TruthfulEdict1** [comment]
> The command is fs0:\efi\boot\bootaa64.efi

Thank you, yes I see I typed "bootaa44" instead of "bootaa64" in my post, but I tried again with the correct command and still get the same message.
