### ISSUE TITLE
Windows Keeps Looking for a Network Connection - Opens New Browser or Tab

### ISSUE THREAD

**Issue by themak1985** [utmapp/UTM#2585]
**Describe the issue**
So Windows 10 ARM Edition	Windows 10 Pro (21354.1) on UTM is super buggy - see #2569 - but I am encountering a weird issue. Windows is opening msftconnecttest.com/redirect via edge (or any browser) which is redirecting to https://www.msn.com/?ocid=wispr&pc=u477 every minute or so. Not sure how to stop it.

**Configuration**
* UTM Version: 2.1.1
* OS Version:  Big Sur
* Intel or Apple Silicon? Silicon

**Comment by PDVJAM** [comment]
Exactly the same issue.

**Comment by conath** [comment]
I believe I have the solution for you. There is a registry key you can change to disable this connect test:

Go to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet` and set `EnableActiveProbing` to `0`.

This worked in my Windows 10 VM in UTM. Source: https://networkproguide.com/fix-connect-attempts-to-www-msftconnecttest-com-windows-server-2016/

.reg file if you need it: 
[disable-ms-connect-test-popup.reg.zip](https://github.com/utmapp/UTM/files/6598432/disable-ms-connect-test-popup.reg.zip)
