### ISSUE TITLE
Issue installing UTM through AppStore source

### ISSUE THREAD

**Issue by geekalert** [utmapp/UTM#2586]
Today, when trying to update UTM or install it anew through the AppStore (paid) UTM source repo, I receive the following error:

```
"UTM SE" could not be installed. 
The bundle ID "com.utmapp.UTM-SE" does not match the one specified by the source ("com.utmapp.UTM").
```

System info: iPad Pro 2018 12.9” running iPadOS v14.3 in AltStore Beta v1.4.5b.

**Comment by osy** [comment]
I assume this is the mac app? Where do you see this message?

**Comment by geekalert** [comment]
My apologies; I didn’t realize that UTM was available on other platforms. Main issue has been updated to include this information.

**Comment by jankais3r** [comment]
I guess this is about AltStore, not App Store?

**Comment by osy** [comment]
I updated the repo generator, it should be fixed now.

**Comment by geekalert** [comment]
Yes, again, I apologize. “AppStore” was a typo. I have corrected the original.

Thank you @osy.
