### ISSUE TITLE
The Virtual Machine doesn't use the entire screen when in fullscreen

### ISSUE THREAD

**Issue by simonerancati** [utmapp/UTM#2587]
**Describe the issue**
When I start a VM and put it in fullscreen Windows doesn't actually use the entire screen until I go to the other desktop and come back.

**Configuration**
* UTM Version: 2.1.1
* OS Version: 11.4
* Intel or Apple Silicon? Apple Silicon

[video](https://drive.google.com/file/d/161y7_D0bpnmXZAxSc_IcnBS8MpMejRBy/view?usp=sharing)
[debug.log](https://github.com/utmapp/UTM/files/6594283/debug.log)

**Comment by volisoft** [comment]
This was likely introduced in the recent release. Previous version didn't have this issue. Tested on a machine with the same parameters as the original reporter.

**Comment by simonerancati** [comment]
No, I've had this problem since I started using UTM (I started with version 2.0.23 or 2.0.24).

**Comment by sandeepwadhwa-ai** [comment]
I have the same problem on my MacBook Air M1.

**Comment by i-lina** [comment]
I am trying this with UTM macOS app on my M2 MacBook Air running windows11 vm. I cannot full screen the VM. What am I missing?

**Comment by davidjeddy** [comment]
Would like to add my recent experience as well.

Host:
  Model Name:       MacBook Pro (M3)
  Model Identifier: Mac15,6
UTM:
  Version: Unable, see below


UTM does not full screen, nor include the little active dot under in the taskbar like other running applications, nor does the titlebar change to UTM when the application is selected. Dunno if this helps narrow down what might have broken but it is what I have observed.

Functionally the application works as intended. Seems like an host OS integration issue.

![Uploading Screenshot 2024-05-16 at 09.41.00.png…]()
