### ISSUE TITLE
Hid top bar in console mode, hard to make it show up again

### ISSUE THREAD

**Issue by zwerdna** [utmapp/UTM#259]
I’ve found that if you make top bar hide in console mode, then three-finger swipe down doesn’t make it to show up again. Maybe there is a way to make it shown again, but I haven’t yet discovered it. 

There is some workaround though: you can disable console mode, make top bar appear in graphical one, and then re-enable it again. Top bar will appear.

Is this the only way to make top bar re-appear?

**Comment by osy86** [comment]
What about double tapping the screen to show/hide the top bar?
