### ISSUE TITLE
Crash when launched with Jitterbug

### ISSUE THREAD

**Issue by jankais3r** [utmapp/UTM#2592]
**Describe the issue**
I just installed the latest version of UTM on my non-jailbroken iPad. When I launch the UTM manually, I get the warning about remote debugging requirement. So I launch it via Jitterbug on my iPhone - UTM launches with no pop-up this time. But the second I try to run any VM, it crashes.

**Configuration (required)**
* UTM Version: 2.1.1
* OS Version: 14.6
* Device Model: M1 iPad
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? Same as always - signed with my dev provisioning profile with iOS App Signer, then installed on the device with Apple Configurator.

**Crash log**
[UTM-2021-06-04-222545.zip](https://github.com/utmapp/UTM/files/6601113/UTM-2021-06-04-222545.zip)

**Debug log**
```
-[CSConnection initWithHost:port:]:269
-[CSInput initWithSession:]:293
```
That’s it, that’s the whole log.

**Upload VM**
Happens with all VMs (old and new).

**Comment by mrford12** [comment]
The same issue for iPad Pro 2020 iOS 14.5. UTM has been installed through AltServer and launched from the second device via Jitterbug without no pop-up warning. Trying to open settings like System, QEMU or starting virtual machine lead to crash. For the instance - DolphiniOS is working fine through Jitterbug on the same device.

**Comment by osy** [comment]
I believe it’s fixed in https://github.com/utmapp/UTM/commit/77d6ca13b42b768b7fc3c30a00ef0a6cc49971ed but that hasn’t been released yet.
