### ISSUE TITLE
Issue installing UTM through AltStore #2586

### ISSUE THREAD

**Issue by geekalert** [utmapp/UTM#2593]
**Describe the issue**
This issue was closed, but it persists. The new errors are:

When AltStore opens:

```
Could not refresh source “UTM repository”.
The data couldn’t be read because it isn’t in the right format.
```

When opening the “Browse” page where the sources are:

```
The data couldn’t be read because it isn’t in the right format.
The given data was not valid JSON.
```

**Configuration (required)**
* UTM Version: N/A (cannot install)
* OS Version: iPadOS v14.3
* Device Model: iPad Pro 2018 12.9”
* Is it jailbroken (name jailbreak used)? Not jailbroken
* How did you install UTM? AltStore Beta v1.4.5b

**Crash log**
No crash. The repo just isn’t being recognized properly.

**Debug log**
Cannot access a lot because the app is not installed. When I couldn’t update it, I uninstalled UTM thinking that might fix the problem. So, no UTM = no logs. 

**Upload VM**
N/A, for the same reasons.

**Comment by osy** [comment]
Sorry should ACTUALLY be fixed now. May be a while for all the caches to be updated.
