### ISSUE TITLE
Windows 98SE 

### ISSUE THREAD

**Issue by tolikes** [utmapp/UTM#2602]
**Describe the issue**

When I start the installation, the keyboard and the mouse do not work

**Configuration (required)**
* UTM Version: 2.11
* OS Version: 14.2
* Device Model: iPhone 11
* Is it jailbroken (name jailbreak used)? Unc0ver
* How did you install UTM? 
Altstore
**Crash log**
N/A
**Upload VM**
N/A

**Comment by tolikes** [comment]
Fixed already

**Comment by criyology** [comment]
Can you please tell what was the fix?
