### ISSUE TITLE
The source "UTM Repository" is not supported by this version of AltStore.

### ISSUE THREAD

**Issue by zuorong-zhang-contributer** [utmapp/UTM#2603]
**Describe the issue**
The source "UTM Repository" is not supported by this version of AltStore.
![image](https://github.com/zuorong-zhang-contributer/images/raw/main/1619fe5c0d18a6659b22d272a1420c3.jpg)

**Configuration (required)**
* UTM Version: 
* OS Version: 13.5.1
* Device Model: IPhone 6s
* Is it jailbroken (name jailbreak used)? no
* How did you install UTM? with UTM repo

**Crash log**
none

**Debug log**
none

**Upload VM**
none

**Comment by osy** [comment]
This is an AltStore issue.
