### ISSUE TITLE
Crash when trying to run Arch or any Arch based distro.

### ISSUE THREAD

**Issue by KZacharski** [utmapp/UTM#2609]
**Describe the issue**
App crashes when I try to run a VM with installation ISO of any Arch Linux based distro (in that case manjaro, but I have tested it on Garuda and few other too) or Arch itself.

**Configuration**
* UTM Version: 2.0.27
* OS Version: Big Sur 11.4
* Intel or Apple Silicon? Intel

**Crash log**
https://mega.nz/file/m15WxYxA#VgSzr-2kiR-Vn4J2q1i1YGAm7LZVOMIUM4BEoyyUV18

**Debug log**
https://mega.nz/file/O55kzKja#msWGQcev-3Uk_GoQ9twmvPHDpEvgD_Eo8maJ_XT-k5E

**Upload VM**
https://mega.nz/file/mlxEwKJI#opO9qw8x2vVLvkcqsOe7pdAo6Uh63m6JOQz6zFk2Ous

**Comment by conath** [comment]
I can't reproduce the crash. I have tried to replicate your VM config and tested the same ISO that you have in your config.

<img width="1136" alt="Bildschirmfoto 2021-06-24 um 12 28 26" src="https://user-images.githubusercontent.com/12073163/123247970-ae325480-d4e7-11eb-896b-3ebee808c091.png">

Was there a specific task you were doing in the guest when it crashed?

**Comment by KZacharski** [comment]
No. I have just run the vm and it crashed.

**Comment by KZacharski** [comment]
I have updated the app to the newest version and everything is fixed. Sorry for wasting your time.
