### ISSUE TITLE
UTM Crashes with newly created drives ("Parameter 'id' expects an identifier Identifiers consist of letters, digits, '-', '.', '_', starting with a letter")

### ISSUE THREAD

**Issue by swittk** [utmapp/UTM#2614]
(OS : iOS 13.1.3, iPad 2018)

Debug logs show something like this

````
qemu-system: -drive if=none,media=disk,id=2468FB06-440A-4E46-9EC1-4EDB37E415BA,file=/private/var/mobile/Containers/Data/Application/B391C024-1F8F-4E10-9CA4-90C4559EB283/Documents/Fedora.utm/Images/archlinux.img,cache=writethrough: Parameter 'id' expects an identifier
Identifiers consist of letters, digits, '-', '.', '_', starting with a letter.
QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
````

Opinion (not sure, just suggesting) :
Creating new drive images seems to use NSUUID (like [here](https://github.com/utmapp/UTM/blob/c312af03311801b90b8c4c3ca67da62c3fc24376/Configuration/UTMConfiguration%2BDrives.m#L107)), which calls [newDrive:path:type:interface:](https://github.com/utmapp/UTM/blob/c312af03311801b90b8c4c3ca67da62c3fc24376/Configuration/UTMConfiguration%2BDrives.m#L118)

NSUUID can start with either letters or numbers so maybe using NSUUID for drive name generation is the cause of this bug?

**Comment by conath** [comment]
Indeed, a recent change to drive identifiers causes this issue. It seems to only occur on iOS 13, which is why this wasn't caught in testing.
