### ISSUE TITLE
Cursor sometimes disappears or shows a stale state when SPICE is installed

### ISSUE THREAD

**Issue by Terabyte1385** [utmapp/UTM#2628]
**Describe the issue**
My Windows pointer is somewhere, but the pointer is actually somewhere else. Screenshot attached.

**Configuration**
* UTM Version: Version 2.1.1 (30)
* OS Version: macOS 12.0 Dev Beta 1
* Intel or Apple Silicon? Apple Silicon

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open Console.app, go to `Crash Reports`, and find the latest entry for either QEMU, QEMUHelper, or qemu-\*. Right click and choose `Reveal in Finder`. Attach the report here.

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the top of the `QEMU` page is `Debug Log`. Turn it on and save the VM. After you experience the issue, open the VM settings again and select `Export Log...` and attach it here.

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by TudorOnMac** [comment]
Update: Cursor sometimes even goes invisible.

**Comment by TudorOnMac** [comment]
<img width="1440" alt="Screenshot 2021-06-20 at 11 47 26" src="https://user-images.githubusercontent.com/78782971/122667827-84aebb80-d1bd-11eb-97f4-4085d0fbbc6a.png">
<img width="1440" alt="Screenshot 2021-06-20 at 11 48 50" src="https://user-images.githubusercontent.com/78782971/122667829-89736f80-d1bd-11eb-8eea-4c73ee22e84b.png">

**Comment by TudorOnMac** [comment]
First image: Cursor does not work properly, pointing towards the close button actually points somewhere else.
Second image: Cursor goes invisible.

**Comment by conath** [comment]
I have this issues sometimes as well. Clicking the Capture Cursor button in the Toolbar and then pressing ctrl-option/alt to unlock it again seems to fix it every time.

**Comment by TudorOnMac** [comment]
Doesn't work for me unfortunately. :(

**Comment by osy** [comment]
Related to #2569

And I also run into this issue a lot. Just haven't had the time to figure it out.

**Comment by osy** [comment]
I think the cursor disappearing issue is a Windows driver issue. Without installing the SPICE tools, it doesn't happen.

**Comment by TudorOnMac** [comment]
So should I uninstall SPICE tools?

**Comment by osy** [comment]
Try it and report back.

**Comment by TudorOnMac** [comment]
Now it seems to work fine, even though I still have SPICE tools installed. It seems like this issue happens if I move my cursor during startup. I'll play with it in the following days and I will let you know how's going.

**Comment by TudorOnMac** [comment]
> Does changing to display 2 instead of display 1 help?

I did change to display 2 now so that I can get a higher resolution but the cursor disappears or clicks somewhere else instead of clicking where it is pointing. Display 1 has a terrible resolution but cursor works perfectly.

**Comment by dmuratov-als** [comment]
I have a mouse pointer constantly disappearing on display 1 with SPICE installed. MacBook Air with M1.

**Comment by TudorOnMac** [comment]
> I have a mouse pointer constantly disappearing on display 1 with SPICE installed. MacBook Air with M1.

Same here but on display 2. Also 8GB MacBook Air with M1.

**Comment by Vishram1123** [comment]
To mitigate this, I used a different cursor that will be rendered by Windows instead of QEMU. By using the Inverted cursor, Windows will have to render it, preventing the cursor from disappearing. One caveat of this is that there are sometimes two cursors on the screen.

**Comment by meshonline** [comment]
I may figure it out:)

The Windows 10 VM generated by v2.1.1 may not compatible with v2.1.2, the document says that after installation, you need to setup display to “Show only on 1”, **this will cause lots of mouse issues**, **you should not modify the display settings, always leave it as default**, please always setup resolution in BIOS when starting by press 'ESC'.

I have re-installed Windows 10 VM from scratch, the issue disappeared.

**Comment by TudorOnMac** [comment]
Okay, will try that out!

**Comment by TudorOnMac** [comment]
<img width="663" alt="Screenshot 2021-07-14 at 09 59 32" src="https://user-images.githubusercontent.com/78782971/125577694-bdcf735a-012f-4918-8c71-6eed356b25eb.png">
Where can I change the resolution here in the BIOS?

**Comment by TudorOnMac** [comment]
<img width="677" alt="Screenshot 2021-07-14 at 10 02 02" src="https://user-images.githubusercontent.com/78782971/125577909-fe716508-f3b0-4da4-b787-7514866dd7c0.png">
Actually, I got there. What resolution do I put?

**Comment by yoedy108** [comment]
@meshonline Thanks for the tip! I re-installed Win10, kept the default display settings, installed SPICE Tools (need network access), changed the resolution thru BIOS and indeed the mouse cursor stays put.

Only thing, this is a workaround and shouldn't be treated as a fix for this issue, as resolution cannot be changed in the OS settings (disabled when changing thru BIOS), and the resolution is limited to a max of 1024x768, when using virtio-ramfb.
As per suggestions from #2569 , using ramfb shows a black screen, and virtio-gpu-pci crashes Windows Settings when trying to open it.

So I guess until this issue is fixed, this is a good enough workaround to be able to work.
Thank you!

**Comment by meshonline** [comment]
I built a custom bios from source code, it supports almost all popular resolutions, vary from standard VGA display to 5K retina display.

[http://www.mesh-online.net/edk2-aarch64-code.fd.zip](http://www.mesh-online.net/edk2-aarch64-code.fd.zip)

Download and unzip the package, replace '/Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd' with the custom 'edk2-aarch64-code.fd'.

When starting, press 'ESC' key to enter BIOS interface, from 'Device Manager->OVMF Platform Configuration->Change Preferred', setup a high resolution, select 'Commit Changes and Exit' and press enter, press 'ESC' key, select 'Reset' and press enter, the VM will re-start with high resolution.

The window may be larger than the screen, please enter full screen mode, the window will fit the screen automatically, if the fonts look too small, you can setup the scale to 200% in Windows 10, retina fonts look more comfortable than small fonts.

Enjoy the high resolution now.

**Comment by TudorOnMac** [comment]
Thanks! It works perfectly! Just a little question; what is the best resolution for a MacBook Air?

**Comment by meshonline** [comment]
I guess that 2880 x 1800 is suitable for MacBook Air, set scale to 200% in Windows.

**Comment by TudorOnMac** [comment]
It is too big. I cannot even see the Windows logo in the wallpaper or even the taskbar.

It seems like the resolution is changing back to default after every reboot.

**Comment by meshonline** [comment]
> It is too big. I cannot even see the Windows logo in the wallpaper or even the taskbar.
> 
> It seems like the resolution is changing back to default after every reboot.

Yes, the window is too big, but if you switch to full screen mode and wait for a few seconds, the window will fit to the screen automatically.

**Comment by TudorOnMac** [comment]
I have been waiting for minutes and nothing happens. The window still remains too big even in fullscreen.

**Comment by TudorOnMac** [comment]
UPDATE: It worked after moving to the desktop and leaving the window with the VM "alone" for a few minutes.

**Comment by TudorOnMac** [comment]
Is there a way to set this resolution to apply at all times, without having to boot into BIOS every time and set it manually?

**Comment by meshonline** [comment]
> UPDATE: It worked after moving to the desktop and leaving the window with the VM "alone" for a few minutes.

Yes, you must switch from standalone windows to full screen after the VM is ready.

> Is there a way to set this resolution to apply at all times, without having to boot into BIOS every time and set it manually?

No, though UTM supports custom BIOS, but the interface is hidden when starting, we can't configure parameters. I can configure parameters in another version of qemu and save them, then use them in UTM, but the workflow is too complicated, I'd rather set resolution every time.

**Comment by meshonline** [comment]
Figure out!
[http://www.mesh-online.net/custom-bios-utm.zip](http://www.mesh-online.net/custom-bios-utm.zip)
Unzip the package, there is a 'Readme.txt', follow the instructions to use the custom BIOS, the resolution can be saved automatically.

**Comment by FezVrasta** [comment]
@meshonline thanks, the last link you sent seems to work. The only problem is that after a restart some text doesn't render anymore (like, folder names, the date and time, etc). Has anyone experienced something like this?

**Comment by TudorOnMac** [comment]
Thank you very much @meshonline for helping me out! Thanks to your hard work, I can now keep a high resolution while still being able to use the cursor, my first issue. Thank you again!

**Comment by osy** [comment]
Please don’t close the issue as it’s not solved yet even if there’s a workaround.

**Comment by TudorOnMac** [comment]
> Please don’t close the issue as it’s not solved yet even if there’s a workaround.

Didn’t know that, thanks for letting me know!

**Comment by henriquec4rv** [comment]
> Thank you very much @meshonline for helping me out! Thanks to your work, I can now keep a high resolution while still being able to use the cursor, the reason I created issue. Thank you again!

Hey man, can u help me out? I've been handling with these same problems you did. And the link @meshonline posted it's not working anymore. Appreciate it.

**Comment by TudorOnMac** [comment]
> And the link @meshonline posted it's not working anymore. Appreciate it.

It is not working anymore, but I merged the archives I downloaded from those and put them in this zip. You have everything you need in there.

[CustomBIOS.zip](https://github.com/utmapp/UTM/files/6872457/CustomBIOS.zip)

**Comment by henriquec4rv** [comment]
> > And the link @meshonline posted it's not working anymore. Appreciate it.
> 
> It is not working anymore, but I merged the archives I downloaded from those and put them in this zip. You have everything you need in there.
> 
> [CustomBIOS.zip](https://github.com/utmapp/UTM/files/6872457/CustomBIOS.zip)
> 
> Make sure to check the Readme.txt file. The instructions are there.

Thank you a lot man. It should fix the cursor problem?

**Comment by TudorOnMac** [comment]
> It should fix the cursor problem?

It is a workaround for now. It does indeed fix the cursor issue while giving you resolution options.

**Comment by henriquec4rv** [comment]
> > It should fix the cursor problem?
> 
> It is a workaround for now. It does indeed fix the cursor issue while giving you resolution options.

Yeah, do u think it could work for me? I can use higher resolution, the only problem is the cursor. =/

**Comment by TudorOnMac** [comment]
> Yeah, do u think it could work for me?

You can definitely try! If it doesn't work let me know.

**Comment by henriquec4rv** [comment]
> > Yeah, do u think it could work for me?
> 
> You can definitely try! If it doesn't work let me know.
> 
> > I can use higher resolution, the only problem is the cursor. =/
> 
> If you already the resolution you want, don't enter the BIOS to change it. Just boot normally.

Already changed before read your post. But, seems the cursor goes invisible as before. I think it's only when I'm using some app.

**Comment by meshonline** [comment]
The custom bios can only solve the resolution issue, it can't solve the cursor issue, if your cursor has already disappeared, you need to re-install Windows, **do not change any display settings, leave it as default**, then use the custom bios to setup high resolution.

**Comment by TudorOnMac** [comment]
> The custom bios can only solve the resolution issue, it can't solve the cursor issue, if your cursor has already disappeared, you need to re-install Windows, do not change any display settings, leave it as default, then use the custom bios to setup high resolution.

He is right. Reinstall Windows, enable the custom BIOS and then you can change display scale (I use 225%). @meshonline Please let me know if that’s not right. That’s what I did.

**Comment by gaurav21r** [comment]
@meshonline @TudorOnMac Thanks a ton for all your help! You just saved me a ton of $$$ from switiching over to Parallels.
Would just like mention a few duplicates so we can all converge here on fixing the problem in the main branch.

Possible duplicates: #2684 #2471
Possible Regressions of: #576

**Comment by TudorOnMac** [comment]
> @meshonline @TudorOnMac Thanks a ton for all your help! You just saved me a ton of $$$ from switiching over to Parallels.
You're welcome!
> Would just like mention a few duplicates so we can all converge here on fixing the problem in the main branch.
> 
> Possible duplicates: #2684 #2471
> Possible Regressions of: #576

Thanks for letting me know! I mentioned this issue as you can see above.

**Comment by wickens** [comment]
Also had this issue, I started again from scratch (following this [tutorial](https://mac.getutm.app/gallery/windows-10-arm)), but this time changed the "System" to be "QEMU 5.2 ARM.." instead of "QEMU 6 ARM.." which was the default I had selected last time. It might well be a coincidence, but seeing as this is still open, I thought I'd mention it.

![Screenshot from tutorial](https://mac.getutm.app/images/guides/windows_screen_3.png)

**Comment by AnonymJ86** [comment]
Hello @Terabyte1385 @meshonline i just installed the custom Bios and follow your tutorial, after I replaced the original edk2 file in the /Applications/UTM.app/Contents/Resources/qemu and followed the steps to finish the process, see photos. After I put in the pflash0 and pflash1 files and try to start it I get stuck in the screen like the last photo or sometimes i get a message saying Windows detected a failure "something with the boot option" does someone know how to help me? Pls reply :) thank you

<img width="800" alt="Bildschirmfoto 2021-09-22 um 13 22 11" src="https://user-images.githubusercontent.com/91194269/134335531-d2147b9c-e675-4138-81fe-1e4bd001e345.png">
<img width="800" alt="Bildschirmfoto 2021-09-22 um 13 22 35" src="https://user-images.githubusercontent.com/91194269/134335539-91dbdf98-de45-4ce6-a738-0b4086743567.png">
<img width="1437" alt="Bildschirmfoto 2021-09-22 um 13 25 11" src="https://user-images.githubusercontent.com/91194269/134335542-d964f2ed-87eb-4de5-b9ed-236cdf8d9913.png">

**Comment by osy** [comment]
Please check the latest release (v2.3.0) and see if the issue persists.

**Comment by osy** [comment]
@AnonymJ86 is this the same issue that's being reported here? It seems like you're minimizing UTM and seeing it not resize properly.

**Comment by AnonymJ86** [comment]
Yes it is i did it like this comment did but as i mentioned sometimes i doesnt work. So its stuck in the big screen (without reszing properly)

https://github.com/utmapp/UTM/issues/2628#issuecomment-881897886

**Comment by osy** [comment]
Does the issue happen if you didn’t minimize the VM?

**Comment by AwlsomeAlex** [comment]
@osy I'm still seeing it with 2.3.0

**Comment by AwlsomeAlex** [comment]
@osy My issue is the cursor will randomly disappear if you use Screen 2 instead of Screen 1. Even with the BIOS workaround this still occurs. However the BIOS workaround will let me use Screen 1 with no issues (at the cost of degraded graphical performance).

**Comment by osy** [comment]
So this is an issue with the Windows DOD driver for Virtio. I will have to dig more into that.

**Comment by osy** [comment]
This was quite a tricky bug but it turned out to be a race condition in the virtio-gpu driver: https://gitlab.freedesktop.org/osy86/virtio-gpu-wddm-dod/-/commit/8f14154a6cb608bfe713d52c6908d997bcbc20bf

I will released an update SPICE tools ISO as soon as I get the driver signed, but people can build it and test sign it themselves if they have an urgent need to get this fix.

**Comment by AwlsomeAlex** [comment]
@osy Could you point to documentation that explains how to build this ourselves?

**Comment by osy** [comment]
I would advise waiting for the signed version. It's really complicated and a pain to run unsigned drivers on Windows 10 and 11. It took me like half a day to figure it out.

**Comment by AwlsomeAlex** [comment]
Gotcha, okay.

**Comment by tiberiogf** [comment]
> To use high resolution on Apple Silicon/M1 machine, I built a custom bios from the source code of the 'edk2' project, it supports almost all popular resolutions, vary from standard VGA display to 5K retina display.
> 
> http://www.mesh-online.net/edk2-aarch64-code.fd.zip
> 
> Download and unzip the package, replace '/Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd' with the custom 'edk2-aarch64-code.fd'.
> 
> When starting, press 'ESC' key to enter BIOS interface, from 'Device Manager->OVMF Platform Configuration->Change Preferred', setup a preferred high resolution, select 'Commit Changes and Exit' and press enter, press 'ESC' key, select 'Reset' and press enter, the VM will re-start with the preferred high resolution.
> 
> The window may be larger than the screen, enter full screen mode, the window will fit the screen automatically, if the fonts look too small, you can setup the scale to 200% for the 2nd display from 'Display Settings' in Windows 10, the retina fonts always look comfortable than small fonts.
> 
> Enjoy it!

![image](https://user-images.githubusercontent.com/7258566/139929473-5ac1953f-12bd-4458-9232-03e1f4e0cc8b.png)

Can you upload this file again on Google Drive?

**Comment by meshonline** [comment]
Sorry, I had wrongly deleted 'eedk2-aarch64-code.fd.zip' before, and I can find a copy on my machine:(

**Comment by meshonline** [comment]
I found the improved version: [https://www.mesh-online.net/custom-bios-utm.zip](https://www.mesh-online.net/custom-bios-utm.zip)
Unzip the file, there is a 'Readme.txt', read it carefully to setup custom BIOS in UTM.

**Comment by ozbrk** [comment]
When will we get the signed driver :D @osy

**Comment by gonewithharshwinds** [comment]
I randomly tried to hit esc button when it was invisible... it came back! XD

**Comment by osy** [comment]
> When will we get the signed driver :D @osy
Here's the ARM64 version [Signed_1152921505694127345.zip](https://github.com/utmapp/UTM/files/7471527/Signed_1152921505694127345.zip)

**Comment by AwlsomeAlex** [comment]
@osy Just installed it, works well.
Only problem is if you try to drag a window, it'll create a second cursor, where one will stay in place and the other will follow you. Once you release it becomes one again. Video below is a demonstration of it. 

https://user-images.githubusercontent.com/11639639/140247529-67d024a7-08d7-4659-a470-782d090e8783.mov

**Comment by Terabyte1385** [comment]
> @osy Just installed it, works well. Only problem is if you try to drag a window, it'll create a second cursor, where one will stay in place and the other will follow you. Once you release it becomes one again.

Same here. Is doesn’t really annoy me but I find it frustrating in some situations.

**Comment by ozbrk** [comment]
ummmmm how can I install the signed version?

**Comment by ozbrk** [comment]
Same here and cursor without the capturing more is simply useless

**Comment by AnonymJ86** [comment]
Hello 

I tried installing the new Windows 11 arm preview 22483.qcow2 and installed the custom bios like here: 
> I found the improved version and uploaded to the website: https://www.mesh-online.net/custom-bios-utm.zip
> Unzip the file, there is a 'Readme.txt', read it carefully to setup custom BIOS in UTM.

Replaced the edk2 file with the original:
> http://www.mesh-online.net/edk2-aarch64-code.fd.zip

And in UTM i used these settings:
<img width="796" alt="Bildschirmfoto 2021-11-04 um 14 47 56" src="https://user-images.githubusercontent.com/91194269/140325112-6b759bbe-ec34-4949-ba12-97ed96575bde.png">

And this problem is happening and also the UTM gets stuck in "Getting ready":
<img width="798" alt="Bildschirmfoto 2021-11-04 um 14 25 36" src="https://user-images.githubusercontent.com/91194269/140325301-c930cf38-c832-4480-8088-c3df1845d5f4.png">
<img width="803" alt="Bildschirmfoto 2021-11-04 um 14 23 30" src="https://user-images.githubusercontent.com/91194269/140325330-3d762292-9aa6-4c6c-a2aa-7bf578ab5c22.png">

Does someone know what i did wrong?

**Comment by sidjainn** [comment]
> @osy Just installed it, works well. Only problem is if you try to drag a window, it'll create a second cursor, where one will stay in place and the other will follow you. Once you release it becomes one again. Video below is a demonstration of it.
> 
>  Cursor.Anomaly.mov 
> ~**EDIT**: Oops, found something. SPICE will crash if you try to reboot. Attached is crash log and QEMU export.~
> 
> ~qemu-aarch64-softmmu: Spice: red-qxl.c:807:spice_qxl_gl_scanout: condition `qxl_state->gl_draw_cookie == GL_DRAW_COOKIE_INVALID' failed~
> 
> ~[crash.log](https://github.com/utmapp/UTM/files/7471893/crash.log)~ ~[debug.log](https://github.com/utmapp/UTM/files/7471901/debug.log)~
> 
> ~Not sure if this existed before. Need to spin up a new VM and reinstall the current SPICE drivers....~
> 
> **EDIT 2:** Crash above is not specific to this new driver. Opened a new issue. #3250

@AwlsomeAlex can you please guide me how to install the driver? I'm a bit clueless here, thanks!

**Comment by AwlsomeAlex** [comment]
@sidjainn They've updated the installer from their website. Please refer to that [here](https://mac.getutm.app/support/).

**Comment by billziss-gh** [comment]
I am still experiencing this problem with `spice-guest-tools-0.164.2.iso` which appears to be the latest available from the [Support](https://mac.getutm.app/support/) page.

Has the fix mentioned in https://github.com/utmapp/UTM/issues/2628#issuecomment-960346616 become publicly available as part of the SPICE guest tools ISO?

**Comment by osy** [comment]
`spice-guest-tools-0.164.3.iso` was released on https://mac.getutm.app/support/ and it should fix the cursor issues on Windows ARM64.

**Comment by ssbarnea** [comment]
Sadly it seems impossible to even install the tools with mouse absence inside the vm.
