### ISSUE TITLE
Specify minimum macOS version

### ISSUE THREAD

**Issue by cyounkins** [utmapp/UTM#2635]
It'd be great if you added a minor note to the website about the minimum macOS version. It might be Big Sur because of the note "... for the new style introduced in Big Sur".

Trying to run UTM on Mojave and it just crashes. Invoking from terminal yields:
```
craig@Craigs-MacBook-Pro /A/U/C/MacOS> ./UTM
dyld: Library not loaded: /System/Library/Frameworks/Combine.framework/Versions/A/Combine
  Referenced from: /Applications/UTM.app/Contents/MacOS/./UTM
  Reason: image not found
```

Apple documentation for Combine.framework says macOS 10.15+.

A tiny note near the download button with the minimum version would be great, a pop-up when starting the program on older  (but not EOL'd) versions of macOS would be even better!

**Comment by osy** [comment]
When you try to open it, it tells you that your version of macos is not supported.

**Comment by cyounkins** [comment]
Ah, I have figured it out. Apparently the "macOS version not supported" message does not appear with Path Finder. It correctly appears when using normal Finder.

I'll close, but would still appreciate a tiny message on the webpage indicating the minimum version when it is higher than the oldest Apple-supported version. "macOS 11+"

**Comment by osy** [comment]
I’ll see if there’s a good way to add it without messing up the layout.

**Comment by osy** [comment]
I’ll see if there’s a good way to add it without messing up the layout.
