### ISSUE TITLE
does it have any sense to install iOS 15 beta for JIT?

### ISSUE THREAD

**Issue by mrmac189** [utmapp/UTM#2639]
Does JIT work on iOS 15 beta? I haven't seen any intel about it.

**Comment by conath** [comment]
There has been discussion about it on the [UTM Discord](https://discord.gg/UV2RUgD) server. TLDR; iOS 15 makes the situation worse because it seems that you need to keep the debugger connected or the UTM JIT crashes. So no, JIT is not available on iOS 15 without tethering.
