### ISSUE TITLE
Crash on suspend

### ISSUE THREAD

**Issue by jankais3r** [utmapp/UTM#264]
I accidentally tapped the Pause button. I got a spinner for about 2 minutes, then iOS reboot.

VM info: x64, 1GB RAM
UTM: 0.9
iPadOS 13.4.1

No UTM crash log, just ResetCounter:
```
{"bug_type":"115","timestamp":"2020-04-13 10:35:00.00 +0200","name":"Reset count","os_version":"iPhone OS 13.4.1 (17E262)","incident_id":"D3D50283-15E1-4E9C-8AB8-FA0FE7D53104"}
Incident Identifier: D3D50283-15E1-4E9C-8AB8-FA0FE7D53104
CrashReporter Key:   5e92eda5dfc2d8043b850c1ad6d9592c8324671d
Date: 2020-04-13 10:35:00.06 +0200
Reset count: 0
Boot failure count: 1
Boot faults: wdog
Boot stage: 255
Boot app: 3495027688
```

**Comment by osy86** [comment]
How often is this reproducible?

**Comment by jankais3r** [comment]
I am unable to reproduce now. Will post debug if I get it ti crash again.

**Comment by osy86** [comment]
I will close for now. Please make a new ticket if you get a crash log or a consistent way of reproducing the issue. I can't do much without it.
