### ISSUE TITLE
VM configuration sheet controls are clipped on macOS 12

### ISSUE THREAD

**Issue by wjk** [utmapp/UTM#2644]
**Describe the issue**

When I open the VM configuration sheet and check the “Show Advanced Settings” box on the System tab, the controls grow horizontally and extend past the edges of the sheet window. See screenshot below. (This also affects the memory size slider, which is clipped on both the right and left sides of the sheet; it is not visible in the screenshot because the sheet is not resizable.)

**Configuration**

* UTM Version: 2.1.1 (30)
* OS Version: 12.0, Beta 2 (21A5268h)
* Intel or Apple Silicon? Intel

**Screenshot**

<img width="1680" alt="Screenshot" src="https://user-images.githubusercontent.com/1915951/123992878-fba43b00-d999-11eb-8dbc-b4fe0c4cd962.png">

**Comment by osy** [comment]
Oh yay apple changed how SwiftUI renders again

**Comment by osy** [comment]
Closed by https://github.com/utmapp/UTM/commit/61603293c8856e8d6d83eb4a7d9e0c45378eda23
