### ISSUE TITLE
VM freezes when trying to open webdav URL

### ISSUE THREAD

**Issue by jankais3r** [utmapp/UTM#265]
As discussed, Windows XP (both x86 and x64) fail to map the webdav network disk. When the url (http://localhost:9843) is typed into IE, the whole VM freezes.

Doesn’t matter if the webdav tool is running as a service or not.

**Comment by fomalsd** [comment]
[debugrepro.log](https://github.com/utmapp/UTM/files/4470480/debugrepro.log)

**Comment by osy86** [comment]
Can you get a screenshot of the console app when running it not as a service and trying to access the port from the web browser?

**Comment by fomalsd** [comment]
![image](https://user-images.githubusercontent.com/10403536/79143683-56b63600-7dc6-11ea-9eeb-bc99e2ffd9f6.png)

**Comment by osy86** [comment]
```
qemu: info: GSpice: spice-session.c:2790 No shared dir set, not creating webdav server
qemu: phodav: phodav_server_get_soup_server: assertion 'PHODAV_IS_SERVER (self)' failed
```

What did you set as your shared directory?

**Comment by fomalsd** [comment]
a new empty folder inside Downloads folder on the device

**Comment by osy86** [comment]
Device's Downloads or iCloud's Downloads?

**Comment by fomalsd** [comment]
device's Downloads

**Comment by osy86** [comment]
What version of iOS?

**Comment by fomalsd** [comment]
iPadOS 13.4 (17E255)
here's a fresher log after ensuring that path is right:
[debugrepro2.log](https://github.com/utmapp/UTM/files/4471016/debugrepro2.log)

**Comment by fomalsd** [comment]
I'd upload a repro VM but not sure how to shrink an .img (it's 12 gigs, but only ~2-4 are used)

**Comment by micodeyt** [comment]
Same here on a Linux guest !

**Comment by osy86** [comment]
So the issue is that file reading outside the sandbox is more complicated than I originally thought. I missed it because I only tested on the simulator which didn't have the filesystem sandbox. So for v1.0 we'll only have sandboxed shared directory and for post-1.0 we'll work on access to shared directory outside the sandbox.

**Comment by jankais3r** [comment]
![A9112F17-DA3D-4F7F-BCFB-7D5922D4B876](https://user-images.githubusercontent.com/2159464/79633126-cf6d1780-8163-11ea-890a-00fcc3bd7d79.png)

Still can’t map the drive on RC1. VM no longer freezes when I access the address in a browser, but mapping fails both in UNC and http formats.

**Comment by osy86** [comment]
What directory did you choose and are there any files in that directory?

**Comment by jankais3r** [comment]
I created a directory called "Shared", and put 1 picture into it. The folder was created from UTM's UI, but I can see it in the Files app.

**Comment by osy86** [comment]
Can you try repicking the directory and saving?

**Comment by jankais3r** [comment]
Ok I did that and now I can see the image, but I still cannot mount it.
![83F5AB21-6FED-4A1A-886C-52F0231072C2](https://user-images.githubusercontent.com/2159464/79643810-0a436f80-81a5-11ea-834f-67084d8556cf.png)

**Comment by osy86** [comment]
That’s strange but it’s a windows problem. I’ve had It hit or miss on XP. Windows 7 is more stable. Maybe try some app that interfaces with WebDAV?

**Comment by jankais3r** [comment]
Ok, I got it to work.

Root causes:
1. XP only supports webdav on port 80. Running the service manually on that port fixed the issue
2. XP does not allow mapping "root" of the webdav share. So to make it work, there has to be a sub-folder inside the folder that is selected in VM's settings, and then the mapping address is http://localhost:80/subfolder.

Might be worth mentioning this somewhere visible as more people will run into this.

**Comment by osy86** [comment]
Can you edit the Github wiki?
