### ISSUE TITLE
Not able to reach network in Kali Linux VM

### ISSUE THREAD

**Issue by markripoll** [utmapp/UTM#2658]
Describe the issue:
While trying to ping google.com, browsing or updating packages I'm not able to reach the network. I've tried to choose every virtio network card, but so far can't get it to work. I've tried also to set manual DNS addresses within Kali, but no luck either.

Configuration:
UTM Version: 2.1.1 (30)
OS Version: 11.4
Apple Silicon

**Comment by markripoll** [comment]
Reinstalling UTM did it for me.

**Comment by conath** [comment]
Your network issue seems to be resolved, and the boot issue is duplicate of #2503 so I'll close this. There is a [workaround available for the disappearing boot entry issue](https://github.com/utmapp/UTM/issues/2607#issuecomment-863023800).

**Comment by LordZexa** [comment]
I am facing the same network issue. Any suggestion ??
<img width="1552" alt="Screen Shot 2022-01-31 at 12 29 31 PM" src="https://user-images.githubusercontent.com/68213789/151751492-d6489189-5198-4204-9863-24a286f7af3a.png">

**Comment by conath** [comment]
@LordZexa Please don’t rely on ping for checking internet connectivity: https://github.com/utmapp/UTM/issues/3238#issuecomment-1026665392

**Comment by macknight** [comment]
> I am facing the same network issue. Any suggestion ?? <img alt="Screen Shot 2022-01-31 at 12 29 31 PM" width="1552" src="https://user-images.githubusercontent.com/68213789/151751492-d6489189-5198-4204-9863-24a286f7af3a.png">

Hi, have you resolved this problem of no network inside UTM VM?

BR

**Comment by beaglemarauder** [comment]
Update the network settings from shared to use bridged, that should solve it.
