### ISSUE TITLE
Mouse Issue in v2.1.2

### ISSUE THREAD

**Issue by meshonline** [utmapp/UTM#2663]
**Describe the issue**
Mouse disappears when I open existed guest VM of 'Windows 10 InsiderPreview Arm64' , when switched back to v2.1.1, the mouse disappears too.

The only way to recover from the issue is to recover the original status from a snapshot of the disk image, and open the VM with v2.1.1.

**Configuration**
* UTM Version:  2.1.2
* OS Version: macOS 11.4
* Intel or Apple Silicon? Apple Silicon
* Machine: Mac Mini Apple Silicon, 16G RAM, 512G SSD.
* Display: Dell U2720QM, 4K.

**Crash log**

**Debug log**

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by meshonline** [comment]
[config.plist.zip](https://github.com/utmapp/UTM/files/6800138/config.plist.zip)

**Comment by osy** [comment]
Being tracked in #2628
