### ISSUE TITLE
v2.1.2 is not notarized on MacOS

### ISSUE THREAD

**Issue by onedrawingperday** [utmapp/UTM#2664]
**Describe the issue**
The previous release v2.1.1 was notarized.  I do not plan on disabling system integrity. 
It would be useful if you notarized the next release of the app.

**Configuration**
* UTM Version: v2.1.1
* OS Version: Big Sur v11.4
* Intel or Apple Silicon?  M1

P.S. I tried installing from the .dmg: https://github.com/utmapp/UTM/releases/download/v2.1.2/UTM.dmg

**Comment by osy** [comment]
Updated the release DMG to be notarized
