### ISSUE TITLE
Windows VHDX failed to boot (error Invalid argument)

### ISSUE THREAD

**Issue by pleerock** [utmapp/UTM#2668]
**Describe the issue**

I've followed instructions, but have a following error: 

![image](https://user-images.githubusercontent.com/1753397/125981349-e483a61b-6279-4571-a60f-72efe53c0b1e.png)

Can you please help to figure it out? This is first time I'm using UTM. Thank you!

**Configuration**
* UTM Version:  2.1.2 (31)
* OS Version: 11.4
* Apple Silicon

**Debug log**

[debug.log](https://github.com/utmapp/UTM/files/6832203/debug.log)

**Comment by conath** [comment]
From your debug.log file I can see the actual error is:
> VHDX BAT entry 1 start offset 8924430336 points after end of file (4236197888). Image has probably been truncated.

Please re-download the VHDX from Microsoft and, without adding it to UTM, convert it to QCOW2 format. Here are detailed [instructions](https://thatsniceguy.gitbook.io/utmfaq/software-and-vms/misc-tips#vhdx-to-qcow2-conversion) for the conversion. Then add the QCOW2 file to UTM like you did with the VMDX file and it will work.

**Comment by pleerock** [comment]
It worked, thank you!
