### ISSUE TITLE
Cursor is stuck

### ISSUE THREAD

**Issue by Majhool** [utmapp/UTM#267]
Windows XP
The cursor is stuck in the top left 

Additional qemu argument 
-vga qxl

![image](https://user-images.githubusercontent.com/44234479/79242593-3301f700-7e7d-11ea-9445-9522cd84961e.jpeg)

![image](https://user-images.githubusercontent.com/44234479/79242647-401ee600-7e7d-11ea-9312-2d487409fdd3.jpeg)

![image](https://user-images.githubusercontent.com/44234479/79242684-4b721180-7e7d-11ea-8636-b70f02bead9b.jpeg)

![image](https://user-images.githubusercontent.com/44234479/79242707-50cf5c00-7e7d-11ea-88d0-f2595d61aab4.png)

**Comment by osy86** [comment]
Can you upload the .utm file to a cloud service so I can debug?

**Comment by Majhool** [comment]
I’m trying
