### ISSUE TITLE
Apple Silicon Mac, cannot emulate x64 Windows 10

### ISSUE THREAD

**Issue by Jimmy2004** [utmapp/UTM#2674]
I downloaded a windows 10 iso(64bit), and managed to load it and install it. However, it cannot boot after the required reboot.

**Comment by TudorOnMac** [comment]
Are you using VHDX drives in your virtual machine? I would recommend you use the ARM version of Windows for an Apple Silicon Mac. You **need** to convert the VHDX drive to QCOW2 so that you won't corrupt the image at the first reboot.

**Comment by Jimmy2004** [comment]
That works. Appreciate that.
