### ISSUE TITLE
Global Shortcuts are not intercepted by client, even when in fullscreen with capture pointer enabled

### ISSUE THREAD

**Issue by mdillavou** [utmapp/UTM#2677]
**Describe the issue**
On a macOS host, if a vm client is run as fullscreen, even with "Capture Pointer" enabled, certain keyboard and mouse short-cuts go to the host instead of the client. For example, pressing `Cmd-Tab` will change between host windows, instead of windows inside the VM. `Cmd-w` will attempt to close the UTM window, instead of just sending an Alt-w to the window in the client. Also, any touchpad gestures (three-finger swipe) go to the host, instead of allowing the client vm to handle it.

**Expected Behavior**
When Capture Pointer is enabled, then all key and mouse input should go to the VM and not the host. It appears that VMware Fusion has an option to handle this:

https://docs.vmware.com/en/VMware-Fusion/12/com.vmware.fusion.using.doc/GUID-A50D0E3C-9549-43B5-AB57-070F805780A3.html

**Configuration**
* UTM Version: 2.1.2 (31)
* OS Version: 11.4 (Big Sur)
* Intel or Apple Silicon?  Apple Silicon M1

**Comment by mdillavou** [comment]
I would jut like to update that Cmd-w suddenly stopped being processed by the host, and now works correctly inside the VM. I am not sure what changed (I didn't update UTM, just restarted the VM at some point).

That said, Cmd-Tab being sent directly to the host is still a big issue for me.

**Comment by kantum** [comment]
I'm experiencing this cmd-tab problem on version 4.3.5 (87)

**Comment by fwcd** [comment]
Same for me, <kbd>⌘</kbd> + <kbd>Tab</kbd> goes to both host and the VM on UTM 4.4.4 running under macOS 14.1.1 arm64.

**Comment by gsustek** [comment]
me also on Sonoma - latest utm, guest Sonoma. cmd TAB ghoes to host os...

**Comment by zugdev** [comment]
m4 pro: cmd+w closes utm, cmd+alt processed by host, same for touchpad movement
