### ISSUE TITLE
Install of Ubuntu 18.04 hangs

### ISSUE THREAD

**Issue by drchriscole** [utmapp/UTM#2685]
**Describe the issue**
When trying to launch the Ubuntu 18.04 server install, the process seemly hangs after selecting the 'Install Ubuntu Server' option in the Grub menu. Only left with a blank screen and a blinking cursor, but no errors or warnings. I have left it in this state for over an hour - in case it was just being slow - with no progress.

I used the "ubuntu-18.04.5-server-arm64.iso" (SHA256 checks out) and the same settings used with a 20.04 install as specified here: https://mac.getutm.app/gallery/ubuntu-20-04

The 20.04 install worked fine.

My suspicion is that it is due to a difference in how the ubuntu images were created as the 20.04 one is a 'live' ISO whereas the 18.04 is not. I'm trying to get to the bottom of what the difference between the two is.

**Configuration**
* UTM Version: 2.1.2
* OS Version: macOS 11.4
* Intel or Apple Silicon? Apple Silicon

**Debug log**

Running:  -L /Applications/UTM.app/Contents/Resources/qemu -S -qmp tcp:127.0.0.1:4004,server,nowait -nodefaults -vga none -spice port=4005,addr=127.0.0.1,disable-ticketing,image-compression=off,playback-compression=off,streaming-video=off -device virtio-ramfb -cpu cortex-a72 -smp cpus=8,sockets=1,cores=8,threads=1 -machine virt,highmem=off -accel hvf -accel tcg,tb-size=1536 -bios /Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd -boot menu=on -m 6144 -device intel-hda -device hda-duplex -name "Ubuntu 18.04" -device qemu-xhci,id=usb-bus -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device ich9-usb-ehci1,id=usb-controller-0 -device ich9-usb-uhci1,masterbus=usb-controller-0.0,firstport=0,multifunction=on -device ich9-usb-uhci2,masterbus=usb-controller-0.0,firstport=2,multifunction=on -device ich9-usb-uhci3,masterbus=usb-controller-0.0,firstport=4,multifunction=on -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 -device virtio-blk-pci,drive=drive0,bootindex=0 -drive "if=none,media=disk,id=drive0,file=/Users/CCole/Library/Containers/com.utmapp.UTM/Data/Documents/Ubuntu 18.04.utm/Images/disk-0.qcow2,cache=writethrough" -device usb-storage,drive=drive1,removable=true,bootindex=1 -drive if=none,media=cdrom,id=drive1 -device virtio-net-pci,mac=4A:CA:8F:3B:90:9B,netdev=net0 -netdev user,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid EE7A369E-A690-4FDF-94B5-598C32A316C7 -rtc base=localtime
qemu-aarch64-softmmu: -spice port=4005,addr=127.0.0.1,disable-ticketing,image-compression=off,playback-compression=off,streaming-video=off: warning: short-form boolean option 'disable-ticketing' deprecated
Please use disable-ticketing=on instead

**Upload VM**
[config.plist.zip](https://github.com/utmapp/UTM/files/6884520/config.plist.zip)

**Comment by drchriscole** [comment]
Turns out this is a display issue.

The non-live 18.04 of arm64 ubuntu server installation doesn't work when the 'Display' setting is 'Full Graphics'. It needs to be 'Console only'. Then, once the server is installed the setting can be reverted back to 'Full Graphics'.

Could be worth mentioning in the docs.

**Comment by conath** [comment]
Added this to the Wiki, thanks.
