### ISSUE TITLE
App wouldn't open in an ARM64 Win 10 VM

### ISSUE THREAD

**Issue by belaldata** [utmapp/UTM#2686]
I followed the guide and the windows VM is working except that downloaded apps wouldn't open along with some of the pre-installed apps like calender.

**Comment by conath** [comment]
Thanks for your message. While UTM GitHub Issues is reserved for technical discussion of UTM features and bugs, you are invited to [join the UTM Discord server](https://discord.gg/48BtjV9n) to discuss other issues such as your Windows VM.
