### ISSUE TITLE
[Build] Distribute as .ipa

### ISSUE THREAD

**Issue by TwoTenPvP** [utmapp/UTM#27]
It would be very nice to build the app as a pre-packaged, unsigned .ipa as part of the building. This makes it much easier to sideload for non macOS users, and to download and install the .ipa straight on device without the use of a computer for jailbroken devices.

**Comment by osy86** [comment]
So an IPA is just an ZIP archive of `UTM.xcarchive/Products/Applications/UTM.app`. What tools are you looking at? It may be better for those tools to be updated to support xcarchive as it is the preferred format for non-signed distribution.

**Comment by TwoTenPvP** [comment]
> So an (unsigned) IPA is just an ZIP archive of `UTM.xcarchive/Products/Applications/UTM.app`. What tools are you looking at? It may be better for those tools to be updated to support xcarchive as it is the preferred format for non-signed distribution.

Hmm. The primary ones I can think of are:
* Cydia Impactor (Linux, macOS and Windows installing of .ipa for non jailbroken devices)
* AltStore (Windows and macOS installing of .ipa for non jailbroken devices. Automatic signature refresh. Also allows signing of .ipas on device)
* Reprovision (Sign local .ipas for jailbroken device)

I think it's hard to argue against .ipa's.

**Comment by osy86** [comment]
Okay, how about this. We build IPAs on release: https://github.com/utmapp/UTM/commit/ac89c106ecf9c765ea47bfe0428f504fce9cd9a6

**Comment by TwoTenPvP** [comment]
> Okay, how about this. We build IPAs on release: [ac89c10](https://github.com/utmapp/UTM/commit/ac89c106ecf9c765ea47bfe0428f504fce9cd9a6)

Looks good and makes sense. I’m all for it.

**Comment by TwoTenPvP** [comment]
Thank you, this makes it super easy to install. Quick installation video on jailbroken iOS 13.3 iPhone 11 Pro Max ![here](https://youtu.be/mto0JIsJBYA). Same could be done for non jailbroken by opening in AltStore instead of Reprovision.
