### ISSUE TITLE
Improved Mouse Support

### ISSUE THREAD

**Issue by rreinhardt** [utmapp/UTM#270]
It would be a great improvement to the usability of the Guest OSs if the mouse support available on iOS was extended universally.

Example: Windows 95.

Right now, you have to click and drag the mouse to move the guest os pointer. Ideally, the guest os pointer would follow the iOS mouse location.

**Comment by osy86** [comment]
That’s purely dependent on drivers you have on Windows. If no such drivers exist someone has to make it.

**Comment by rreinhardt** [comment]
@osy86 

Interesting, I feel like it is something the iOS app could manage. Isn’t the codebase that manages that a layer above the Guest OS?

For the “Drag” version, the iOS code is taking drag-start coordinates, and measuring x/y translation to new coordinates and pushing that to the Guest OS to move the mouse that same amount. Wouldn’t it be possible to take the same logic and use the bounds of the view port to push the cursor to the absolute position of the iOS mouse.

**Comment by osy86** [comment]
The problem is without the guest communicating it could easily go out of sync with rounding errors and such. Then it’ll be impossible to know where the cursor “should” be.

**Comment by rreinhardt** [comment]
That makes sense. Thanks for the consideration and replies. Really great to have this project in development. Great work!
