### ISSUE TITLE
iPad M1 iOS15 support.

### ISSUE THREAD

**Issue by AnatolyPristensky** [utmapp/UTM#2707]
Hello guys!
First of all I want to say THANK YOU for your great work and UTM project. It's really can be a future of iOS mobile devices.
I understand that all this work is really hard - but I want to ask you - do you have a plans to make UTM support for iPads with M1 chip on new iOS15?

**Comment by conath** [comment]
Hi @AnatolyPristensky and thanks for your kind message. You will be glad to know UTM works on M1 iPad and iOS 15 will be officially supported in the fall, though UTM already has been reported to work on the more recent betas.

If you get a popup saying "This version of iOS does not support running VMs _while unmodified_. …" this does not mean that UTM doesn't work with this version of iOS. As the message suggests, it's the other way around: Apple's iPadOS doesn't provide the necessary API to run UTM like, e. g. on M1 Mac. So we need workarounds like [debugger connection ("tethering")](https://thatsniceguy.gitbook.io/utmfaq/installing-utm/installing-on-nonjailbroken-ios#utm-tether) to get acceptable performance, or [slow emulation](https://thatsniceguy.gitbook.io/utmfaq/installing-utm/installing-on-nonjailbroken-ios#utm-slow-edition-no-tether) as a fallback which will likely keep working regardless of iOS updates.

In some previous versions of iOS it was possible to run UTM without the above workarounds. TLDR; Apple decided to remove this capability in iOS 14.4 #2271
