### ISSUE TITLE
iOS11 cannot launch VMs (UTM 2.0+)

### ISSUE THREAD

**Issue by ty-yqs** [utmapp/UTM#2711]
**Describe the issue**
iOS11 cannot launch VMs by using UTM 2.0+. It works by using earlier versions.

**Configuration**
* UTM Version: UTM2.0+
* OS Version: iOS11.1.1
* Device Model: iPad2017 (A9)
* Is it jailbroken (name jailbreak used)?  unc0ver
* How did you install UTM?  Developer ID

**Comment by ty-yqs** [comment]
https://user-images.githubusercontent.com/61855011/128636933-3c4df1e5-db23-4fa2-92fd-c423daa6c43a.mov

**Comment by osy** [comment]
@ty-yqs is this v2.0 or v2.2.0? Also please attach a crash log.

**Comment by ty-yqs** [comment]
My bad. It is working now (I restarted my device)
