### ISSUE TITLE
Handling of right click using Bluetooth mouse

### ISSUE THREAD

**Issue by TyroneSlothrop** [utmapp/UTM#272]
Setup:
- UTM ipa version 0.9
- Host = iPad Pro
- Guest = Windows XP

Issue in guest:
- I have a Bluetooth mouse and although left click works fine, right click just works as left click (single tap)
- Two-handed tap works as right click fine per UTM options so it’s not a guest/HID driver issue

Potential fix:
- It seems like there is the concept of ‘adaptive input’ in iPad OS’s accessibility options
- Within these I seem to be able to bind the right click ok to various actions like double tap (NOT the same as two-handed tap), pinch etc
- However I cannot bind in iPad OS to the two-handed tap, nor can I bind right click to other gestures in UTM options
- The one crossover seems to be ‘long tap’ and although using this almost works, the fact that single tap and long tap are very close to each other means that I don’t end up with a right click solution (this behaves more like left click/drag etc)

- Therefore: is it possible to try and expose more gestures in UTM options to bind to right-click? Notably, iPad OS does seem to have the concept of a ‘secondary click’ in the accessibility options.

![E83C3890-F270-4897-A3B7-59CFFF30A045](https://user-images.githubusercontent.com/1816777/79339509-ebcd4200-7f20-11ea-977e-6992c77a5ed7.png)
![95D6ED85-44A8-489E-AC07-FC5AB7C51202](https://user-images.githubusercontent.com/1816777/79339525-f091f600-7f20-11ea-966f-63457b6f4832.png)

**Comment by fomalsd** [comment]
it's the same for wired USB mouse by the way

**Comment by ThatsNiceGuy** [comment]
same for Magic Trackpad 2
