### ISSUE TITLE
Windows won’t boot or install on 2.2.0

### ISSUE THREAD

**Issue by osy** [utmapp/UTM#2721]
My existing Windows 10 x86_64 VM doesn't work anymore with this version, even though I have not changed anything and had already set the system to remain the 6.0 one in the last version. The problem is as follows:
the first boot worked fine, then it crashed after started up completely and restarted. Then it failed to get past Windows boot so went into `Preparing Automatic Repair`. That also fails because the hard drive is `viostor`, the driver for which is missing in repair mode.

Maybe, did something with the hard disks change?

When trying to reinstall from ISO it keeps crashing before the Windows loading spinner appears. 
[debug.log](https://github.com/utmapp/UTM/files/6956652/debug.log)

Update: when I change back to 2.1.2 it boots fine again. Log from 2.1.2: 
[debug-2.1.2.log](https://github.com/utmapp/UTM/files/6956687/debug-2.1.2.log)

_Originally posted by @conath in https://github.com/utmapp/UTM/discussions/2716#discussioncomment-1150851_

**Comment by osy** [comment]
@conath does the problem occur without using shared networking?

**Comment by conath** [comment]
Yes, it does. I turned that on afterwards when trying to boot the install ISO.

**Comment by osy** [comment]
I wonder if it’s an issue with qemu 6.1.0

**Comment by conath** [comment]
Could be. Note that I specify to use the system from 6.0 in the config - does that not make a difference?

**Comment by ktprograms** [comment]
Just for extra info, I created new VM using the `QEMU 6.0 ARM Virtual Machine (virt-6.0)` and Ubuntu 20.04 Server ISO, and it installs just fine.

**Comment by coreycusick** [comment]
I have a similar issue. My already made VMs will say automatic repair. All my Windows VMs will crash with a blue screen saying page fault in non paged area when installing. Happens with XP, 7, and 10. And trying to boot from the hdd installer, it will sometimes work but usually crashes with that blue screen.

**Comment by ds8k** [comment]
> I have a similar issue. My already made VMs will say automatic repair. All my Windows VMs will crash with a blue screen saying *page fault in non paged area* when installing. Happens with XP, 7, and 10. And trying to boot from the hdd installer, it will sometimes work but usually crashes with that blue screen.

I've got the same problem running 2.2.0 on iOS. Windows 7 blue screens during install. I was able to get XP installed but trying to install spice guest tools would crash the app.

Reverting to 2.1.2 fixes all of this.

**Comment by conath** [comment]
I've tried booting Windows 10 21H1 x86_64 today and it shows BSOD [`PAGE_FAULT_IN_NONPAGED_AREA`](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x50--page-fault-in-nonpaged-area) when booting from the ISO.

**Comment by conath** [comment]
Same behavior in 2.2.2 beta!

**Comment by osy** [comment]
@conath Is this only an issue with `virtio-blk` or does `ide` not work as well? Any reason to go with `virtio-blk` over the other devices?

**Comment by osy** [comment]
Two other things to try:
1. Build latest EDK2 (with the patches) and see if that changes anything.
2. Try it with vanilla QEMU (`brew install qemu`) and see if the same issue occurs. If so, then it's definitely a QEMU bug and should be reported to them.

**Comment by conath** [comment]
> @conath Is this only an issue with `virtio-blk` or does `ide` not work as well? Any reason to go with `virtio-blk` over the other devices?

Same with `ide`. I was under the impression that `virtio` is faster than `ide`.

**Comment by osy** [comment]
So I tested on vanilla QEMU 6.1.0 and experience the same issue.

**Comment by osy** [comment]
@conath Testing with QEMU it seems like `q35` is broken on 6.1.0.

**Comment by conath** [comment]
That matches up with my testing of UTM 2.2.X where the only ones that worked were non-q35 systems.

**Comment by osy** [comment]
https://gitlab.com/qemu-project/qemu/-/issues/599

**Comment by osy** [comment]
@conath Please test the latest commit.

**Comment by conath** [comment]
Working fine as of https://github.com/utmapp/UTM/commit/634ddaaf6308994fed71b7a4a7fd15840961fbd2.

**Comment by mcayland** [comment]
The upstream fix for QEMU 6.1.0 has been merged and is available here: https://gitlab.com/qemu-project/qemu/-/commit/b04dc92e013d55c9ac8082caefff45dcfb1310e7. Please try this instead of reverting the affected patches as per https://gitlab.com/qemu-project/qemu/-/issues/599.

**Comment by osy** [comment]
QEMU 6.1.0 has been integrated with UTM 3.0.0
