### ISSUE TITLE
Add option for unique MAC addresses

### ISSUE THREAD

**Issue by ktprograms** [utmapp/UTM#2724]
With bridged networking, you should be able to have multiple VMs running each with a different IP address and being able to `ping`/`ssh` each other. But since there is no option to set the MAC address, only 1 VM can be running at any time. If I try to boot the second one it doesn't work.

I copied the network configuration lines from the QEMU arguments, then disabled the network in the options and pasted in the network configuration lines (but changed the MAC address). Then both VMs can boot and access each other.

I suppose when creating a new VM, the app can look in the `config.plist` of existing VMs and choose a MAC address that isn't already used. I see in the `config.plist` there is a key `NetworkCardMAC` which can (probably) be easily read/modified.

Just a note, changing the MAC address of an already installed (and setup) VM messes with it's network, but [this](https://askubuntu.com/questions/908614/ethernet-network-not-showing-or-connecting-in-ubuntu-17-04/909442#909442) solution works for Ubuntu (I'm not sure about Windows).

**Comment by conath** [comment]
Note about MAC Address changes on Windows: it will reset the network settings and show as a new Ethernet Connection.

**Comment by ktprograms** [comment]
I'm going to try implementing it. I think it's best to change the `generateMacAddress` method to check previously allocated MAC addresses and avoid using them. The `generateMacAddress` method is only called when creating a new VM or when a migration from an old VM is done.
https://github.com/utmapp/UTM/blob/13664282a2a9fb239f62c5777cb45cabcce29fae/Configuration/UTMConfiguration%2BNetworking.m#L75-L85
The simplest place to put the list of allocated MAC addresses would be the UserDefaults's `VMList` (truncated output from `defaults read com.utmapp.UTM`):
```
    ...
    VMList =     (
        "Ubuntu 20.04 arm.utm",
        "Ubuntu 20.04 x86_64.utm",
        "Nextcloud.utm",
        "Nextcloud 2.utm",
        "Ubuntu 20.04 arm 2.utm"
    );
}
```
Could be converted to:
```
    ...
    VMList =     (
                (
            "Ubuntu 20.04 arm.utm",
            "aa:aa:aa:aa:aa:aa"
        ),
                (
            "Ubuntu 20.04 x86_64.utm",
            "bb:bb:bb:bb:bb:bb"
        ),
                (
            "Nextcloud.utm",
            "cc:cc:cc:cc:cc:cc"
        ),
                (
            "Nextcloud 2.utm",
            "dd:dd:dd:dd:dd:dd"
        ),
                (
            "Ubuntu 20.04 arm 2.utm",
            "ee:ee:ee:ee:ee:ee"
        )
    );
}
```

**Comment by ktprograms** [comment]
@conath @osy any opinions on the above suggestion?

**Comment by osy** [comment]
The settings should be in the config file as the VMList isn't permanent. I already have some code for the Virtualization.framework backend so I can just backport some of that over.

**Comment by xvolks** [comment]
FYI: I've just bumped into this issue after cloning a VM. So when one selects the Clone... option it should change the MAC addresses of the NICs on the clone VM.

**Comment by osy** [comment]
Fixed in https://github.com/utmapp/UTM/commit/bb3044d6b16725f111c0661f3af15952e0254897
