### ISSUE TITLE
Compiling error: ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by stephensworld** [utmapp/UTM#273]
Maybe someone could help me.

Thanks

Stephan

MacBook-Pro:UTM stephan$ ./scripts/build_dependencies.sh
....

`      _qcrypto_hash_alg_map in hash-nettle.o
  "_nettle_sha256_init", referenced from:
      _qcrypto_hash_alg_map in hash-nettle.o
  "_nettle_sha256_update", referenced from:
      _qcrypto_hash_alg_map in hash-nettle.o
  "_nettle_sha384_digest", referenced from:
      _qcrypto_hash_alg_map in hash-nettle.o
  "_nettle_sha384_init", referenced from:
      _qcrypto_hash_alg_map in hash-nettle.o
  "_nettle_sha512_digest", referenced from:
      _qcrypto_hash_alg_map in hash-nettle.o
  "_nettle_sha512_init", referenced from:
      _qcrypto_hash_alg_map in hash-nettle.o
  "_nettle_sha512_update", referenced from:
      _qcrypto_hash_alg_map in hash-nettle.o
  "_nettle_twofish_decrypt", referenced from:
      _twofish_decrypt_native in cipher.o
      _twofish_decrypt_wrapper in cipher.o
  "_nettle_twofish_encrypt", referenced from:
      _twofish_encrypt_native in cipher.o
      _twofish_encrypt_wrapper in cipher.o
  "_nettle_twofish_set_key", referenced from:
      _qcrypto_cipher_new in cipher.o
  "_uncompress", referenced from:
      _vmdk_co_preadv in vmdk.o
     (maybe you meant: _dmg_uncompress_bz2, _dmg_uncompress_lzfse )
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libqemu-system-aarch64.dylib] Error 1
make: *** [aarch64-softmmu/all] Error 2
MacBook-Pro:UTM stephan$ `

**Comment by osy86** [comment]
Please read the readme. It mentions specifically about a vm and how existing packages can taint a build.

**Comment by saagarjha** [comment]
If you’re careful, you can do it on your own machine too. It’s a bit complicated, though.

**Comment by osy86** [comment]
The underlying issue is that `pkg-config` will always use the system default path in addition to the specified pkg config path. For aarch64 it might be easy to fix but for x86_64 simulator builds it could be more work. That's why I suggest using a fresh VM/container. Just so it's easier.

**Comment by saagarjha** [comment]
```diff
diff --git a/scripts/build_dependencies.sh b/scripts/build_dependencies.sh
index c99c175..c4bce60 100755
--- a/scripts/build_dependencies.sh
+++ b/scripts/build_dependencies.sh
@@ -177,17 +177,30 @@ build () {
 build_qemu_dependencies () {
     build $FFI_SRC
     build $ICONV_SRC
-    build $GETTEXT_SRC --disable-java
+    port -f deactivate libiconv
+    build $GETTEXT_SRC --disable-java gl_cv_libcroco=no
+    port activate libiconv
+    port -f deactivate zlib
     build $PNG_SRC
+    port activate zlib
     build $JPEG_TURBO_SRC
+    port -f deactivate libiconv
+    port -f deactivate zlib
     build $GLIB_SRC glib_cv_stack_grows=no glib_cv_uscore=no --with-pcre=internal
+    port activate libiconv
+    build $GLIB_SRC glib_cv_stack_grows=no glib_cv_uscore=no --with-pcre=internal
+    port activate zlib
+    port -f deactivate gawk
     build $GPG_ERROR_SRC
+    port activate gawk
     build $GCRYPT_SRC
     build $PIXMAN_SRC
     build_openssl $OPENSSL_SRC
     build $OPUS_SRC
     build $SPICE_PROTOCOL_SRC
+    port -f deactivate zlib
     build $SPICE_SERVER_SRC
+    port activate zlib
     build $NCURSES_SRC --without-debug --enable-overwrite --enable-widec --with-ospeed=int16_t --without-progs --without-tack --without-tests
 }
 
@@ -197,6 +210,12 @@ build_qemu () {
     #    echo "${GREEN}Cloning qemu...${NC}"
     #    git clone --depth 1 --recursive --shallow-submodules "$QEMU_GIT" "$QEMU_DIR"
     #fi
+    port -f deactivate bzip2
+    port -f deactivate zlib
+    port -f deactivate nettle
+    port -f deactivate libusb
+    port -f deactivate libxml2
+    port -f deactivate gnutls
     QEMU_CFLAGS="$CFLAGS"
     QEMU_CXXFLAGS="$CXXFLAGS"
     QEMU_LDFLAGS="$LDFLAGS"
@@ -210,6 +229,12 @@ build_qemu () {
     CFLAGS="$QEMU_CFLAGS"
     CXXFLAGS="$QEMU_CXXFLAGS"
     LDFLAGS="$QEMU_LDFLAGS"
+    port activate bzip2
+    port activate zlib
+    port activate nettle
+    port activate libusb
+    port activate libxml2
+    port activate gnutls
 }
 
 steal_libucontext () {
@@ -221,11 +246,23 @@ steal_libucontext () {
 }
 
 build_spice_client () {
+    port -f deactivate zlib
     build $JSON_GLIB_SRC
+    port activate zlib
     build $GST_SRC --enable-static --enable-static-plugins --disable-registry
+    port -f deactivate gcc9
+    port -f deactivate zlib
     build $GST_BASE_SRC --enable-static --disable-fatal-warnings
+    port activate zlib
+    port activate gcc9
+    port -f deactivate zlib
+    port -f deactivate bzip2
     build $GST_GOOD_SRC --enable-static
+    port activate zlib
+    port activate bzip2
+    port -f deactivate zlib
     build $SPICE_CLIENT_SRC --with-gtk=no
+    port activate zlib
 }
 
 fixup () {
@@ -376,7 +413,7 @@ CPPFLAGS="$CPPFLAGS -arch $ARCH -isysroot $SDKROOT -I$PREFIX/include -miphoneos-
 CXXFLAGS="$CXXFLAGS -arch $ARCH -isysroot $SDKROOT -I$PREFIX/include"
 LDFLAGS="$LDFLAGS -arch $ARCH -isysroot $SDKROOT -L$PREFIX/lib"
 MAKEFLAGS="-j$NCPU"
-PKG_CONFIG_PATH="$PKG_CONFIG_PATH":"$SDKROOT/usr/lib/pkgconfig":"$PREFIX/lib/pkgconfig":"$PREFIX/share/pkgconfig"
+PKG_CONFIG_PATH="$PKG_CONFIG_PATH":"$SDKROOT/opt/local/lib/pkgconfig":"$PREFIX/lib/pkgconfig":"$PREFIX/share/pkgconfig"
 PKG_CONFIG_LIBDIR=""
 export CFLAGS
 export CPPFLAGS
```

Like I said, it's a bit complicated ;)

**Comment by cgxxv** [comment]
> The underlying issue is that `pkg-config` will always use the system default path in addition to the specified pkg config path. For aarch64 it might be easy to fix but for x86_64 simulator builds it could be more work. That's why I suggest using a fresh VM/container. Just so it's easier.

If I want to fix it on macos aarch64 (sdk15.0), how to do it, can you give a guideline? And thanks very much! @osy
