### ISSUE TITLE
GL_OES_draw_elements_base_vertex error when launching KDE on a Linux ARM64 guest with virtio-gpu-gl-pci

### ISSUE THREAD

**Issue by neobrain** [utmapp/UTM#2735]
**Describe the issue**

When launching KDE on a Ubuntu AArch64 guest with GPU acceleration enabled on the latest UTM beta, an error message saying only `GL_OES_draw_elements_base_vertex` will pop up, terminating the VM.

*Notably, this does not happen with a qemu build from https://github.com/knazarov/homebrew-qemu-virgl.*

To reproduce:
* Setup a new Linux AArch64 VM with QEMU 6.1 and virtio-gpu-gl-pci
* Download and install a VM from https://cdimage.ubuntu.com/releases/21.04/release/ubuntu-21.04-live-server-arm64.iso
* Reboot and `sudo apt install kde-standard`
* Reboot and login (make sure KDE/Plasma is selected in the login manager)
* The error message should show up before

**Configuration**
* UTM Version: 2.2.0 (Beta)
* OS Version: 11.5.1
* Intel or Apple Silicon? Apple Silicon

**Crash log**
[Crash log here](https://github.com/utmapp/UTM/files/6968178/QEMULauncher_2021-08-11-125849_Tonys-MacBook-Air.crash.zip)

**Debug log**
```
gl_version 30 - es profile enabled
WARNING: running without ARB/KHR robustness in place may crash
vrend_renderer_fill_caps: Entering with stale GL error: 1280
GLSL feature level 130
No provider of glDrawElementsBaseVertex found.  Requires one of:
    Desktop OpenGL 3.2
    GL_ARB_draw_elements_base_vertex
    OpenGL ES 3.2
    GL_EXT_draw_elements_base_vertex
    GL_OES_draw_elements_base_vertex
```

**Comment by neobrain** [comment]
> This looks similar to #2729

Not sure if it's related. GNOME launches fine with `virtio-gpu-gl-pci` and is working fine (I've been able launch games using virgl), but it's something about KDE (presumably KWin) that's triggering an error here. 2729 sounds like nothing is not working at all, and triggers a different error message.

It's curious that the same setup (I'm on Ubuntu 21.04 rather than 20.04) would yield different results like that, though.

**Comment by osy** [comment]
@neobrain The homebrew version lets you choose between desktop GL profile and GLES profile. UTM does not support desktop GL profile (as it does not exist on iOS). Can you check if you are using GLES there and if not see if the same error happens with GLES?

**Comment by osy** [comment]
The GRUB rendering issue seems to be a QEMU bug. Closing this since the original issue seems to be resolved.
