### ISSUE TITLE
White Screen on app launch

### ISSUE THREAD

**Issue by Macmee** [utmapp/UTM#274]
**Describe the bug**
I'm on a 12 inch iPad Pro running 13.4 and installed UTM through AltStore. Not jailbroken. When I launch UTM a white screen happens. Basically just looks like the app is an empty uiviewcontroller and that's all I get.

**To Reproduce**
1. install UTM via altstore
2. launch UTM
3. blank/white screen

**Comment by osy86** [comment]
Restart the device.
