### ISSUE TITLE
“Retina mode” in settings doesn’t work with landscape mode 

### ISSUE THREAD

**Issue by ThatsNiceGuy** [utmapp/UTM#275]
Guest: Windows XP SP3 32bit
Host: iPad Pro 11” 2020 256GB/6GB RAM
Notes: Guest is running with 200% scaling to account for Retina display
Notes 2: SPICE guest driver **is** installed
**Describe the bug**
What i mean with the title is that the guest will adjust to the iPad’s screen resolution but in portrait mode, and will not readjust when in landscape mode. See images.

![F957F679-9854-413B-928E-891438B07774](https://user-images.githubusercontent.com/10524728/79377496-056a8b80-7f19-11ea-9b41-918c78c9f7cb.png)
In above image, all is well.

Now for the next image:
![ADAAD069-2F44-4786-B3A6-6032D742FAF3](https://user-images.githubusercontent.com/10524728/79378006-cf79d700-7f19-11ea-98cd-e93250a2e3d8.png)
In above image, the guest’s resolution isn’t changed to account for the iPad being in landscape mode.

**To Reproduce**
1. Go to 'Settings', enable Retina mode
2. Boot your XP VM and log in
3. Resolution will change but for portrait, even when iPad is rotation locked to landsacape

**Attempted fixes**
- Suspend VM, toggle Retina mode off and back on, then go back into VM
- Rotate device several times
- Suspend VM, toggle Retina mode off, go back to VM, shut down VM, toggle retina mode back on, then start VM again

**Comment by osy86** [comment]
Both resize and retina boxes are enabled?

**Comment by ThatsNiceGuy** [comment]
Yes

**Comment by osy86** [comment]
How long did you wait after rotating? Anyways please attach the debug log as requested from the bug report template.

**Comment by ThatsNiceGuy** [comment]
Will do. Sorry for not replying earlier, for some reason I didn’t get the github email

**Comment by itselijahciali** [comment]
Can confirm, also exists on iPhone XS on iOS 13.4 (non-jailbroken, AltStore Repo)

**Comment by ThatsNiceGuy** [comment]
Got the log.
[xp-retina.log](https://github.com/utmapp/UTM/files/4494766/xp-retina.log)
