### ISSUE TITLE
Can’t start a Raspbian VM 

### ISSUE THREAD

**Issue by LiuliLiuqi** [utmapp/UTM#279]
**Describe the bug**
Every time when starting a vm with an official Raspbian lite img, UTM will show an error banner: 

    `qemu: property '.vmport' not found`

and  then crash. 

Appears on UTM v0.8 on my iPad  Pro 3 (iPad8,1) | iPadOS 13.3 (iPhone OS 13.3 (17C54)) | jailbroken by unc0ver 4.3.1

**To Reproduce**
1. Create a new VM, while choosing ARM (aarch32) as the architecture, 1000 MB as the RAM size, 4 as the amount of CPU cores, the official lite disk image from Raspbian’s official site. 
2. Start the VM by tap the start button. 
3. See the error banner. 
4. Press “OK”, then crash. 

**Crash log**
I’m sorry, but there isn’t any crash log about UTM on my iPad, as this snapshot below. 
![IMG_2613](https://user-images.githubusercontent.com/47787400/79485885-7fe5f900-8048-11ea-9f84-7fc91ea7d743.jpeg)

**Debug log**
2020-04-17 00:59:12.397 UTM[1595:32500] -[CSConnection init]:245
2020-04-17 00:59:12.398 UTM[1595:32500] Loading libqemu-system-arm.dylib

**Upload VM**
Too big (1.83 MB) and failed to upload to Onedrive. So Sorry! :cry:

**Comment by osy86** [comment]
It was fixed in v0.9
