### ISSUE TITLE
UTM always makes an error when reopening the automatically saved virtual machine

### ISSUE THREAD

**Issue by none-null-blank** [utmapp/UTM#280]
Error log:QEMU encountered an error exit: qemu: Device 'drive0' does not have the requested snapshot 'suspend
UTM version:0.9

**Comment by osy86** [comment]
Please upload the .utm file and directions to reproduce.

**Comment by none-null-blank** [comment]
[MacOSX.utm.zip](https://github.com/utmapp/UTM/files/4491120/MacOSX.utm.zip)
