### ISSUE TITLE
UTM folder disappeared from Files app

### ISSUE THREAD

**Issue by jankais3r** [utmapp/UTM#289]
RC1, can no longer browse UTM’s storage from Files app. Makes the shared folder thing a bit useless.

**Comment by osy86** [comment]
I think it’s an iOS bug. I’ve experienced it as well you have to restart the device.

**Comment by jankais3r** [comment]
Can confirm that reboot worked. But shared folders still don’t. Will update corresponding issue.

**Comment by ThatsNiceGuy** [comment]
Rebooted twice now and I can’t see the UTM folder in Files. 
Sideloaded the IPA file using AltStore

UTM RC1 - 2020 iPad Pro 11” 256 GB / 6 GB RAM

**Comment by osy86** [comment]
It’s an iOS bug, not really sure what to do.

**Comment by ThatsNiceGuy** [comment]
Found out what’s causing it.
To make the folder appear in the files app I had to go into UTM and make a VM (empty is fine) and save it then exit. Then force close the files app if already open and then open it again and the UTM app will be there. Weird iOS bug but meh it works

**Comment by Stooovie** [comment]
Did that, UTM  still not in Files. Unc0ver jailbreak, 13.5.
