### ISSUE TITLE
[qemu] Port android emulator changes for qemu

### ISSUE THREAD

**Issue by konstantintuev** [utmapp/UTM#29]
I don't get how to run Android arm64. All the resources I find online are from 2014 with lots of dead links and my only clue is that the standard AVD by google runs on qemu but I have no idea how to run it.
Any help would be greatly appreciated!

Also is arm64 performance better on a arm64/e device than x86_64 performance or is it the same because it's emulated anyway?

**Comment by osy86** [comment]
Yeah, this is a known issue. I also read online that Android requires some google specific patches to qemu but I haven't dug more into it. Right now, most people running android are using kvm which is not available. OSX does not have kvm and I wasn't able to get qemu working on OSX either. If someone enlightens me on how android emulator works on OSX, the same thing can be done on iOS.

**Comment by Umiiii** [comment]
If I remember correctly, the official Android emulator on macOS is also based on qemu.
`~/Library/Android/sdk/emulator/emulator`
Have you ever tried it?

**Comment by Watking01** [comment]
Actually I researched into this a bit, it turns out the latest version of android x86 that doesn’t require kvm is android 4.3 
Link: https://archive.org/details/android-x86-4.3-20130725_201512

**Comment by Watking01** [comment]
> If I remember correctly, the official Android emulator on macOS is also based on qemu.
> `~/Library/Android/sdk/emulator/emulator`
> Have you ever tried it?

Wouldn’t that be a bit difficult to port onto iPhone

**Comment by osy86** [comment]
I mean obviously you would have to look at the source code, diff it with qemu 4.2.0 and then take the changes and so on.

**Comment by Watking01** [comment]
> I mean obviously you would have to look at the source code, diff it with qemu 4.2.0 and then take the changes and so on.

I mean if you are prepared to sure, but you probably have better stuff to do, like updating utm itself. Also what about the google patches that let you run android without the need for kvm, they could be helpful

**Comment by osy86** [comment]
Yeah that’s why I said “you” and not “me”. I have no plans to work on this issue. It’s a suggestion for anyone who wants to take a look.

**Comment by SarKaa** [comment]
love to see that your still working on this,

**Comment by vishy-dev** [comment]
Doesn't the android emulator on Mac use HAXM for acceleration?

**Comment by osy86** [comment]
Two things:

1) After spending a good chunk of my morning trying to find the Android Emulator changes. I don't think Google has posted their source code [since 2015](https://android.googlesource.com/platform/external/qemu/+/master). I don't think picking 5 year old changes that may or may not already be merged upstream would be useful.
2) But it doesn't matter because turns out Android x86 pretty much works without needing Google's fork after adding some args. They're still too slow to be usable because of the lack of hardware accelerated graphics. See https://getutm.app/vms/

**Comment by SarKaa** [comment]
Thanks man, you’re amazing
