### ISSUE TITLE
How to enter the F8 while making windows xp virtual machine on Iphone.??

### ISSUE THREAD

**Issue by raikikon** [utmapp/UTM#293]
**Describe the bug**
A clear and concise description of what the bug is. **BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**To Reproduce**

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here.

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the bottom of the configuration options is `Debug Log`. Turn it on and save the VM. After you experience the issue, quit the VM and re-launch UTM. Open the VM settings again and select `Export Log...` and attach it here.

**Upload VM**
If possible, upload the `.utm` you are experiencing an issue with. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by osy86** [comment]
Press F8 on the software keyboard.
