### ISSUE TITLE
[Release Candidate] Issue with the keyboard on legacy systems

### ISSUE THREAD

**Issue by brunocastello** [utmapp/UTM#294]
**Describe the bug**
After installing the Release Candidate version, I started my VM. I have a MSDOS 6.22 + Windows 3.11 VM, and after the boot when I get to the command prompt, the keyboard no longer works. It's the apple smart cover keyboard, and I'm using the iPad Pro 12'9 inch, Gen 2 (2017).

I rolled back to previous version and keyboard started working again (the "preview" version). So there is something on RC version preventing me from using the smart keyboard. Since the keyboard wasn't working on RC version, I could not see if it is also a show stopper when using Windows 3.11.

**To Reproduce**
Use a previously created UTM machine with MSDOS-622 Installed. Try to boot. After the boot phase, you are on command prompt. Try to type, and nothing you type will come out on screen, so keyboard is not doing any input.

** Upload **
I know that you asked me to upload the VM, but it has some sensitive & personal data inside, hence why I did not upload. I can clone it and delete all my data, leaving only MSDOS for you if that's all you need, but it's pretty easy to create one with the MSDOS disk images available at winworldpc.com. However, I'm uploading a stripped down version of my VM for you to debug.

EDIT: File available here on WeTransfer:
https://wetransfer.com/downloads/eca8c59338fa9742901e3cd36a155dbe20200418235143/7c290fd2d81a538fdd816abc6fca34e420200418235203/fdac61

**Comment by brunocastello** [comment]
Also, worth nothing, I tried to install Windows NT 4.0. While the installer program started as expected, I was presented the License Agreement page, I was asked to press PAGE DOWN  to go to the next page before accepting the license. Guess what, there is no PG DOWN, PG UP keys. I laughed at myself for a minute before I realised this while I was hitting ENTER...


![](https://www.wikihow.com/images/thumb/a/a7/Install-Windows-NT-4.0-Workstation-Step-3.jpg/aid7789805-v4-728px-Install-Windows-NT-4.0-Workstation-Step-3.jpg)

**Comment by conath** [comment]
I second this, there should be more buttons e. g. page up and down on the on-screen keyboard accessory view.

**Comment by ecstaticax** [comment]
Today I tried to install Windows 2000 and touch keyboard didn’t work, I could not go on after the first blue screen.

**Comment by osy86** [comment]
@brunocastello In the configuration -> Input you need to use Legacy Input.

**Comment by osy86** [comment]
I think #329 fixes this.
