### ISSUE TITLE
Cursor input settings have no effect

### ISSUE THREAD

**Issue by greybaron** [utmapp/UTM#298]
The Touch Input/Apple Pencil Input setting that is exposed in the iOS Settings app has no effect.
No matter which option is selected, Touch Input always functions as „Drag Cursor“ and Apple Pencil Input as „Touch Mode (try hiding cursor)“.

Note: a single time, while Touch Input was set to „Touch Mode (try hiding cursor)“ the cursor actually appeared where the screen was touched, but neither did the input actually work, nor was the cursor hidden. I couldn‘t reproduce this.

**Comment by rreinhardt** [comment]
It would be beneficial for all if you include additional information about your Guest OS. It is likely that your Guest OS does not have USB drivers for the mode required to drive it in alternative ways.

I believe ... if you are running an old OS that does not support USB mouses ... the UTM system will only work by dragging the cursor for inputs. If you select the other inputs, they will just not work.

**Comment by osy86** [comment]
Please provide more information. What os? What device? Are you using legacy input mode?

**Comment by rreinhardt** [comment]
And actually, if you have Legacy PS/2 toggled to ON for your guest OS — this will override whatever you’ve put in the Settings.app

**Comment by greybaron** [comment]
Sorry about not providing more info.
I don‘t have Legacy PS/2 enabled.
I was testing Windows XP/7/8/10 and other OS‘es that DO support the USB-Tablet input mode, and I also know that it works, because the Apple Pencil already works as such.

**Comment by osy86** [comment]
If the device doesn’t support usb tablet it won’t support absolute input.

**Comment by greybaron** [comment]
I don‘t seem to understand - if absolute input already DOES work using the Pencil, what is stopping UTM from interpreting finger touch input in the same way?
I don‘t see why absolute input wouldn‘t work using finger touch input, that‘s what that setting seems to imply

**Comment by osy86** [comment]
Sorry maybe I misunderstood. If Apple Pencil works since touch screen mode should work as well. If it isn’t then I need your .utm to check.

**Comment by greybaron** [comment]
yeah, Apple Pencil always works as direct input, touch always as indirect, the settings don‘t have any effect.
This .utm was created/used with these settings in reverse, so Pencil as indirect and touch as direct.
The Android x86 4.0 iso is included because its the smallest OS I had where direct input DOES indeed work. (Using Pencil of course)

https://drive.google.com/file/d/1ZydIWsSDsVRQA2bP5f7q0-hXZFCL08p-/view?usp=drivesdk

**Comment by greybaron** [comment]
also, this happens on my iPhone X on 13.3 as well, so I‘d suppose it happens on every device or on every 13.3 device.

**Comment by newperson1746** [comment]
same on iPad11,3 13.1.3

**Comment by greybaron** [comment]
IMO, it would also be far better to have this as a toggle in the top bar. You could leave the „cursor hidden/shown in direct touch mode“ option in the Settings, and make the toggle apply to the last used input method, so that you could also toggle the Apple Pencil mode.  
I feel like this is kind of necessary for at least finger touch direct input, because it isn’t very precise and frequently zooming in to tap stuff would be cumbersome

**Comment by osy86** [comment]
@greybaron can you post a screen of your settings page? I was not able to reproduce the issue.

Using your image from google drive, I have my settings set to "Touch input: touch mode (always show cursor)". I am able to directly tap buttons in the android setup screen. Then I go back to settings and set "Touch input: Drag cursor" and back at android setup screen, I see a cursor show up and I can move it with my finger.

I am using an 2018 iPad Pro.

**Comment by greybaron** [comment]
@osy86 these are my settings, on both devices: 
![D9F77A0C-2686-4E46-846A-7613B344041C](https://user-images.githubusercontent.com/20914657/82447751-0444f500-9aa9-11ea-954a-96583b4b0a15.jpeg)

I‘m using 13.4.1 on an iPhone X and 13.3 on an iPad Pro 2018, and in both cases regular touch always stays indirect (drag cursor).

**Comment by greybaron** [comment]
I have completely wiped and reinstalled UTM, and the issue persists on my end; and I have tried changing this setting while the VM ran and it made no difference

**Comment by osy86** [comment]
I added better debug logging in RC3. You can either pick up and resign a nightly build or if you don't know how to do that wait for RC3 release. If it still happens in RC3, get a debug.log and post it here which should have more information.

**Comment by osy86** [comment]
I think I figured it out. This appears to be another iOS issue. In the [APIs](https://developer.apple.com/documentation/foundation/nsstreamstatus/nsstreamstatuswriting?language=objc)

> Data is being written to the stream. This status would be returned if code on another thread were to call streamStatus on the stream while a write:maxLength: call (NSOutputStream) was in progress.

However, I'm seeing that `NSStreamStatusWriting` is returned in some cases even when no other thread is writing. When this happens, the code to switch cursor type fails silently. I have modified the code to ignore `NSStreamStatusWriting` and it seems to work in the times I hit this issue.

**Comment by greybaron** [comment]
@osy86 Unfortunately, RC3 made no difference on both of my devices. Tries changing the setting while UTM is running, and while it isn‘t.
I will attach my debug.log shortly

**Comment by greybaron** [comment]
I was using the Android VM. Before starting touch input was set to „ touch mode - always show cursor“, while the VM ran I changed it to „try hiding cursor“.

https://pastebin.com/HCrS9b1v

**Comment by osy86** [comment]
Hiding cursor doesn’t work without SPICE tools. Does it work going from “drag cursor” to “touch mode”?

**Comment by greybaron** [comment]
No, it always stays a drag cursor.

**Comment by greybaron** [comment]
@osy86 I have found the cause of the issue. This always happens when UTM is fakesigned. I have reinstalled UTM using a signing service, and now (without or while jailbroken) it always works as intended.

**Comment by greybaron** [comment]
but can this still get fixed in the future, because many people don’t have a signing store subscription or dev account. I for example have to fake sign on my second device. I even believe there could be more people fake signing than sideloading.

**Comment by ThatsNiceGuy** [comment]
If you’re jailbroken, why not use ReProvision? It signs things using your Apple ID similar to AltStore but doesn’t need the PC/Mac running on the same wifi.

**Comment by osy86** [comment]
I think what happened was you were on the wrong version. There’s no way signing makes a difference to how the app runs.

**Comment by newperson1746** [comment]
Wouldn’t perhaps entitlements be a difference?

**Comment by osy86** [comment]
No and also there is no difference in entitlements. The only entitlement we use is for running code so if you don’t have it you can’t launch any VM.

**Comment by greybaron** [comment]
Believe me, I didn‘t choose the wrong IPA. On none of my 3 devices it worked, but once I use a signing service (and the exact same IPA) on the only device where I can test it, it immediately works. The signing method really is the only difference here, I see no way around that honestly

**Comment by osy86** [comment]
True, but I wonder why then. Is it possible you somehow changed the bundle identifier such that the Settings changes wrote to the wrong settings file?

**Comment by greybaron** [comment]
I won’t be able to check against the working sideloaded install for a few days, but I noticed the following things:
- I have two UTM data containers
- the plist where the MouseTouchType is defined is in one container, the VMs in the other container
- No UTM data is exposed in the native files, which I assume should be possible

**Comment by osy86** [comment]
Yeah that probs explains it. Not sure why since I don’t have a jailbreak.
