### ISSUE TITLE
[UTM] Auto-pausing on task switch

### ISSUE THREAD

**Issue by utmapp** [utmapp/UTM#3]
Implement hooks to pause VM on task switch and low-memory conditions.

**Comment by ConfolidelBiins** [comment]
first issue!!!1!11!!!1!1!!1!11111!

**Comment by ConfolidelBiins** [comment]
UTM: adds this to v1.0
ghost: assigns utm for adding to v1.0
UTM: ewww I am not your gf I am removing this from the v1.0
ghost: you remove it, I unassign you :)

**Comment by HahaMeGoesBeLikeBRRRRRRRR** [comment]
FIRST!!!!

**Comment by 0h-no-oo-oo-her-0b-r11-ne-is-behind-you** [comment]
UTM: adds this to v1.0 milestone
ghostL o0h i wAñńâ hāvë śēx with u i assigned u!!!!!!!

**Comment by 0h-no-oo-oo-her-0b-r11-ne-is-behind-you** [comment]
UTM: ew, just fc_u!k off, bt_ich!
ghost: u ärė só śtūpíd >:(
