### ISSUE TITLE
'StaticDataTableViewController.h' file not found

### ISSUE THREAD

**Issue by rhld16** [utmapp/UTM#30]
happens mid-way building.
it's used by VMConfigViewController.h

**Comment by rhld16** [comment]
nvm i didn'y download sub modules

**Comment by haveamission** [comment]
@rhld16 What sub modules did you download and to where?

**Comment by jkcoxson** [comment]
> @rhld16 What sub modules did you download and to where?

```git submodule init```
```git submodule update```
