### ISSUE TITLE
Cursor out of alignment after startup

### ISSUE THREAD

**Issue by osy86** [utmapp/UTM#300]
Sometimes, the cursor can be out of alignment for a few pixels. It's resolved when switching apps and back again.

**Comment by bearzyj** [comment]
Hit the same issue in win7(virtual machine), my workaround is adjust resolution(then you can adjust back).

**Comment by vwxyzjn** [comment]
Hey, I seem to encounter this issue again, I can't resize the window until moving the cursor a few pixels lower than the window's boundary.

<img width="1136" alt="Screen Shot 2021-11-28 at 6 13 15 PM" src="https://user-images.githubusercontent.com/5555347/143790182-c1dbc2a0-26d5-4822-b697-a769d3af7d04.png">

**Comment by vwxyzjn** [comment]
So apparently the VM is using the host’s cursor which is slightly misaligned.

A kind of workaround is to do a screenshot (cmd shift 5), then the host os's mouse overlays with the correct location, as shown below.

![image](https://user-images.githubusercontent.com/5555347/143904742-6534ab88-7ef2-403b-863d-3dcc0724c6da.png)
