### ISSUE TITLE
Error resetting device: LIBUSB_ERROR_NOT_FOUND

### ISSUE THREAD

**Issue by kusti8** [utmapp/UTM#3010]
I’m currently on UTM 2.1.2 iOS with iPadOS 14.1 jailbroken with unc0ver.

I’ve been trying to share USB devices from my iPad to both Ubuntu 21.04 x86_64 and Debian 10.4 arm64, but each time I try and connect it, I get the error pop up Error resetting device: LIBUSB_ERROR_NOT_FOUND. I’ve tried this with an Arduino through 2 different USBC to USBA, my Pixel 3, and a smart card reader. The only thing that has successfully connected and appeared in Linux is the SD card reader on one of the USBC to USBA hubs.

Any help is appreciated, thanks!

**Comment by Krish-sysadmin** [comment]
@osy From what I understand the comparison of device descriptors has a mismatch and thus LIBUSB_ERROR_NOT_FOUND is outputted. Am I correct in this line of thought?

**Comment by Krish-sysadmin** [comment]
Did you manage to fix this? @kusti8

**Comment by kusti8** [comment]
No I haven't. I haven't played with it too much since though.

**Comment by Krish-sysadmin** [comment]
Hmm, I think I know why you get this error and could fix it, but just need confirmation from @osy that my line of thought is correct

**Comment by SmartBoy84** [comment]
> Hmm, I think I know why you get this error and could fix it, but just need confirmation from @osy that my line of thought is correct

If you think that's the problem and have a potential solution, why not fix it and see if it works?

**Comment by osy** [comment]
iOS and macos provide a device capture API that is lacking. Specifically it doesn’t prevent a race where the OS sees the device as soon as it’s reset and tries to configure it. Then the capture API is called and the application (QEMU) tries to configure it (again). Some devices don’t like this and you’ll see an error. Unfortunately there’s no way around this except to either 1) force unload and block the KEXT drivers from attaching or 2) doing some kernel patches.

**Comment by SmartBoy84** [comment]
> Unfortunately there’s no way around this except to either 1) force unload and block the KEXT drivers from attaching or 2) doing some kernel patches.

That's unfortunate since I've found that most USB peripherals fail with this error. Is a solution being worked on?

**Comment by SmartBoy84** [comment]
I hate to do this on issues but I hope waiting a couple of months warrants this - @osy  any update?

**Comment by osy** [comment]
libusb was updated in 3.2.0 beta. Are you still experiencing the issue?

**Comment by kusti8** [comment]
3.2.0 beta works for me, thanks!

**Comment by SmartBoy84** [comment]
Exciting stuff, thanks for this osy!

**Comment by heavyboots** [comment]
I'm running Version 3.2.4 (58) and seem to be unable to attach an iPhone 12PM at this point. Any suggestions for workarounds?

macOS 12.5 (21G72) / iOS 15.6 on an MBP 16" M1 Max

And, brew info libusb shows…

libusb: stable 1.0.26 (bottled), HEAD
Library for USB device access
https://libusb.info/
/opt/homebrew/Cellar/libusb/1.0.26 (22 files, 595KB) *
  Poured from bottle on 2022-08-03 at 10:24:53
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libusb.rb

**Comment by Dogo69Dog** [comment]
> iOS and macos provide a device capture API that is lacking. Specifically it doesn’t prevent a race where the OS sees the device as soon as it’s reset and tries to configure it. Then the capture API is called and the application (QEMU) tries to configure it (again). Some devices don’t like this and you’ll see an error. Unfortunately there’s no way around this except to either 1) force unload and block the KEXT drivers from attaching or 2) doing some kernel patches.

im still getting this issue today, is there antything i can try

**Comment by ivicak99** [comment]
im experiencing the issue too. im trying to connect my iPhone to windows x86 running trough emulation on macbook m1
