### ISSUE TITLE
Error starting VM in console mode

### ISSUE THREAD

**Issue by laedsonzz** [utmapp/UTM#3011]
I have a problem starting a VM in console mode, I have tested all versions of UTM, versions prior to 2.2.0 simply close the application when starting in console mode, in version 2.2.0 an error message appears, allowing a log of the problem.
![D4564B39-BA3E-490C-96E1-5293B2223C08](https://user-images.githubusercontent.com/78885446/129430979-332db1ee-05d1-4181-83c9-98217d64bb89.png)

* UTM Version: 2.2.0 and previous
* OS Version: iOS 14.3
* Device Model: iPhone SE 2020
* Is it jailbroken (name jailbreak used)? Yes, Taurine
* How did you install UTM? Sileo and Beta IPA

**Crash log**
Although the application closes in versions lower than 2.2.0, it doesn't show log in settings

**Debug log**
[Debug version 2.2.0](https://drive.google.com/file/d/1yuovU8ViVzz9A2i-6aYrz6I15TbnNtLV) 
[Debug version 2.1.2 (via Sileo)](https://drive.google.com/file/d/1QmRbRKyYeZQjImfDjVxX5G0aFuzWiXSe/view?usp=drivesdk) 

**Upload VM**
system pattern Debian 10.4 (Minimal)

**Comment by conath** [comment]
Hi @laedsonzz please kindly double check the [install instructions](https://getutm.app/install/). You can also try installing the .deb manually (not the IPA). If you've followed them then please also try to use AltStore method as a workaround if the .deb isn't working. 

The error you reported has been mentioned before in connection with improperly installed UTM. This is why I recommend you try the above. Please let us know if it works.
