### ISSUE TITLE
UTM cannot adjust graphics and cursor settings.

### ISSUE THREAD

**Issue by MTS-Rabbit** [utmapp/UTM#3013]
UTM can't adjust graphics and cursor settings, and can't left click. The mouse is stuck in the upper left corner and shakes. My mouse is OK, but UTM can't, and the touch screen can't.

* UTM Version: v2.1.2
* OS Version: iOS 15.0 (19A5318f)
* Device Model: iPad Pro 11
* Is no jailbroken.
* UTM installed with developer signature.

In PS / 2 mode, there is no problem with the mouse, and the touch screen can also be dragged normally. Press the left and right buttons. As long as PS / 2 is turned off, it cannot be used normally. The mouse is stuck in the upper left corner and shakes. When you click the screen, the mouse will follow your finger, but you can't click the left button.

**Comment by HubertZhang** [comment]
It seems that notification `GCMouseDidBecomeCurrentNotification` is triggered before `UTMQemuManager` is initialized. Thus mouse mode is not changed to proper value.
