### ISSUE TITLE
VMs in the VM list appear chopped off.

### ISSUE THREAD

**Issue by Pingvin0** [utmapp/UTM#3016]
VMs in the VM list appear chopped off. Just testing out the app for the first time.

**Configuration**
* UTM Version: 2.1.2 (31)
* OS Version: Big Sur ( 11.3.1 )
* Intel or Apple Silicon?  Apple Silicon

![image](https://user-images.githubusercontent.com/58985574/129461639-825541cc-9bd2-4da3-be51-374f3c243212.png)

**Comment by ktprograms** [comment]
Did you see https://github.com/utmapp/UTM/issues/2335#issuecomment-826385748?

**Comment by ty-yqs** [comment]
Update your macOS

**Comment by Pingvin0** [comment]
> Did you see [#2335 (comment)](https://github.com/utmapp/UTM/issues/2335#issuecomment-826385748)?

Ah. My bad.
