### ISSUE TITLE
Windows 10 VM + UTM crashes at VM login process

### ISSUE THREAD

**Issue by Terabyte1385** [utmapp/UTM#3019]
**Describe the issue**
When booting Windows 10, at the login process where it says Welcome, UTM crashes.

**Configuration**
* UTM Version: v2.1.2
* OS Version: macOS 12 Beta 5
* Intel or Apple Silicon? Apple Silicon

**Crash log**
[UTM-2021-08-15-150220.ips.zip](https://github.com/utmapp/UTM/files/6988069/UTM-2021-08-15-150220.ips.zip)

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/6988087/debug.log)

**Upload VM**
[config.plist.zip](https://github.com/utmapp/UTM/files/6988085/config.plist.zip)

**Comment by Terabyte1385** [comment]
It seems to happen **only sometimes**, and happens if I put the VM in full screen and then I switch focus to another window in my main desktop.

**Comment by MTS-Rabbit** [comment]
I don't know how to export crash log, debug log, and VM. Can you tell me how to export it?

**Comment by Terabyte1385** [comment]
> I don't know how to export crash log, debug log, and VM. Can you tell me how to export it?

Crash Log:

1. Open Console (/System/Applications/Utilities/Console.app)
2. Look for UTM, QEMU, qemu-_something_ or something similar
3. Right-Click and press Reveal in Finder
4. **OPTIONAL.** Copy the selected file somewhere else.
5. **OPTIONAL, but necessary if you upload directly to GitHub.** Right Click on the file in its new location and press "Compress _UTM-whatever_.ips"


Debug Log

1. Open UTM
2. Right Click on the VM you want to collect the log and press Edit.
3. Press QEMU
4. **If not turned on / checked already, **check Debug Logging.
5. **If you just turned on Debug Logging, **power on the VM and re-create the crash / error.
6. Press on Export Debug Log
7. **I didn't know what to do, so this is a workaround.** Press on Messages / Notes and save the debug.log file in a message to yourself / note, then right click on it and press "Save to Downloads"

VM

Uploading the entire VM is tough. It will upload **all data on it, including personal data in the guest OS**, **it is usually large, depending on the guest OS size** and because of that, **you will have to use a cloud storage sharing service, such as a Google Drive link.** Optionally, to reduce the size, you can compress it. To export the configuration, you don't need to export the entire VM.

1. Open UTM
2. Right Click on the VM you want to export and press Show in Finder.
3. **If you want to export the entire VM**, upload the selected file to a cloud service. **If you want to compress it before uploading it,** right-click on the selected file and click Compress _VMname_.utm.
4. **If you want to export just the configuration, **right-click the selected file and click Show Package Contents, then upload, or copy if needed, the _config.plist_ file.

**Comment by conath** [comment]
The crash reason is `NSWindow drag regions should only be invalidated on the Main Thread`, this is the relevant part of the crash log:

```log
Thread 5 Crashed:
0   libsystem_kernel.dylib        	       0x186258a58 0x18624f000 + 39512
1   libsystem_pthread.dylib       	       0x18628c228 0x186285000 + 29224
2   libsystem_c.dylib             	       0x1861c9314 0x186150000 + 496404
3   libc++abi.dylib               	       0x186248b50 0x186235000 + 80720
4   libc++abi.dylib               	       0x186239f64 0x186235000 + 20324
5   libobjc.A.dylib               	       0x1861311c0 0x186111000 + 131520
6   libc++abi.dylib               	       0x186247ee4 0x186235000 + 77540
7   libc++abi.dylib               	       0x186247e80 0x186235000 + 77440
8   libdispatch.dylib             	       0x1860cde90 0x1860ca000 + 16016
9   libdispatch.dylib             	       0x1860dc25c 0x1860ca000 + 74332
10  CoreFoundation                	       0x18639a6cc 0x1862d4000 + 812748
11  CoreFoundation                	       0x186358098 0x1862d4000 + 540824
12  CoreFoundation                	       0x186356f0c 0x1862d4000 + 536332
13  HIToolbox                     	       0x18ef2a19c 0x18eef6000 + 213404
14  HIToolbox                     	       0x18ef29f10 0x18eef6000 + 212752
15  HIToolbox                     	       0x18ef29cd0 0x18eef6000 + 212176
16  AppKit                        	       0x188e9086c 0x188e4f000 + 268396
17  AppKit                        	       0x188e8f110 0x188e4f000 + 262416
18  AppKit                        	       0x188e80cfc 0x188e4f000 + 204028
19  AppKit                        	       0x188e524f4 0x188e4f000 + 13556
20  SwiftUI                       	       0x1ab0b6154 0x1ab028000 + 581972
21  SwiftUI                       	       0x1abba41e4 0x1ab028000 + 12042724
22  SwiftUI                       	       0x1ab652330 0x1ab028000 + 6464304
23  UTM                           	       0x105024d30 0x104f8c000 + 625968
24  UTM                           	       0x10502224c 0x104f8c000 + 614988
25  dyld                          	       0x10563d0f4 0x105638000 + 20724
```

As this crash is happening on macOS 12 beta, it is unknown if this is a UTM or macOS issue. Since this kind of problem hasn't been reported frequently I am leaning towards macOS beta issue with SwiftUI (see also the call stack) and therefore will close this. 

Feel free to reopen if this persists with macOS 12 GM/Release. Thanks!

**Comment by atyshka** [comment]
I'm experiencing this issue on MacOS 12.1
