### ISSUE TITLE
Pre-installed windows 10/11 apps doesn't work

### ISSUE THREAD

**Issue by muratdk23** [utmapp/UTM#3023]
**Describe the issue**
When I trying to launch windows app like store, mail or calendar window shows for a second and shut down. 

**Configuration**
* UTM Version: 2.2.0
* OS Version: 12.0 monterey beta 5
* Intel or Apple Silicon? Apple Silicon

**Comment by Vishram1123** [comment]
Confirmed this happens on my end too. When launching a stock W11 app, it attempts to launch multiple times, then eventually fails.

**Comment by conath** [comment]
You reporting a Windows problem as a UTM issue. Do you know that this works without issue in other VM apps? 

It might be due to emulated network. @muratdk23 please send all information requested in the issue template (debug log!). Otherwise we can only guess what the problem may be. 

Anyway I recommend you switch to bridged network mode in the network configuration, that would rule out any network problems.

**Comment by muratdk23** [comment]
I think it’s utm problem because in parallels it woks fine.

**Comment by conath** [comment]
**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the top of the `QEMU` page is `Debug Log`. Turn it on and save the VM. After you reproduce / experience the issue, open the VM settings again and select `Export Log...` => Mail, drag the debug.log file to Desktop. Then attach it here.

Thanks!

**Comment by muratdk23** [comment]
[debug.log](https://github.com/utmapp/UTM/files/7017377/debug.log)

**Comment by conath** [comment]
I'm trying to reproduce this with the ARM version of Windows 11 Insider Preview, however it doesn't want to install in UTM using the default EFI BIOS. How did you install it?
![Screen Shot 2021-08-20 at 00 50 13](https://user-images.githubusercontent.com/12073163/130154181-ff95f31e-7126-4cb5-b32b-3974aa36d1a8.jpg)

**Comment by Vishram1123** [comment]
@conath,
1: I downloaded both an x86 Windows 10 ISO (From MSFT website) and an ARM64 Windows 11 ISO (from UUPDump)
2: I created an x86 VM and attached both drives, plus a 20gb qcow2 drive
3: I used the Windows 10 interface to partition the drive, then I used [DISM](https://www.tenforums.com/tutorials/84331-apply-windows-image-using-dism-instead-clean-install.html) to apply the Windows 11 image (using dism /Get-WimInfo to make sure it was Windows 11 - the WIM will show up as Windows 10 professional, with the description as Windows 11 Pro) and bcdboot to create the boot files. 
4: I shut down the VM and then I changed the machine type from x86_64 to ARM64, and I removed all the drives except for the 20gb qcow2 drive.
5: I booted up the VM, and after a few seconds of it showing up, the Windows 11 OOBE showed up.
6: After I finished setup, I updated the install (using Windows Update, requires Microsoft account as insider builds didn't show up until I enabled them, which required the account), and I was left with a functioning Windows 11 build, with the exception of those UUP applications.

**Comment by Vishram1123** [comment]
Another option is to take a windows 10 arm image from MSFT's website and using a tpm registry bypass to upgrade

**Comment by Vishram1123** [comment]
[Here is proof of what is happening](https://drive.google.com/file/d/1Aq2IMQczK2ZCzCznM62PV9FkEsPAY_jU/view?usp=sharing)

**Comment by Vishram1123** [comment]
> I think it’s utm problem because in parallels it works fine. Where can I get debug.log?

I have tried this in Parallels, it doesn't work there either. However, in Parallels, the app requests an update (which fails), but in UTM the update is never requested.

**Comment by conath** [comment]
@Vishram1123 Just saw you're on UTM 2.1.2 not 2.2.0. If you want to try with the beta, you could get Windows properly online and then maybe the apps can update/download properly and work.

**Comment by Vishram1123** [comment]
Well, when I try to boot an ARM vm on UTM 2.2.0, there is an everlasting spinner. It never boots (just upgraded, also tried creating a new vm and copying the old qcow2)

**Comment by Vishram1123** [comment]
It only allows me to boot in console graphics, and I cannot see Windows

**Comment by Vishram1123** [comment]
Actually nvm, I was able to boot when running UTM directly off of the DMG

**Comment by conath** [comment]
Oh interesting... this might mean that it is using the older QEMU 6.0 that is in your UTM in /Applications when running from the .dmg … @osy potentially useful for debugging/troubleshooting, if this is how it works.

**Comment by Vishram1123** [comment]
Same result with 6.0

**Comment by Vishram1123** [comment]
Ok, I figured out I didn't actually delete the old version of UTM, it was still there. So I deleted both versions and recopied the UTM from the dmg. Now it boots, but the same issue occurs with uup applications

**Comment by conath** [comment]
Just to make sure, were you able to boot your Windows 11 VM in UTM 2.2.0 beta?

**Comment by Vishram1123** [comment]
> ~Just to make sure, were you able to boot your Windows 11 VM in UTM 2.2.0 beta?~
> 
> I have successfully set up a Windows 11 ARM VM and it boots fine in UTM 2.2.0 on M1 Mac. Using shared network, the DNS problem is not present. 😃
> 
> I can now reproduce the issue. I will try to run Windows update in the VM and see if that resolves it.

Yes, I am able to boot windows 11. I made the mistake of choosing the virtio-gpu-gl-pci device, which now crashes the Display settings and causes (even more) horrible screen tearing.

**Comment by conath** [comment]
Same here, the apps don't open even after Windows Updates.

**Comment by osy** [comment]
Has anyone tested with QEMU (for example https://gist.github.com/akihikodaki/87df4149e7ca87f18dc56807ec5a1bc5 )? If it's a QEMU issue, then it should be reported to them.

**Comment by Jaiganeshkumaran** [comment]
You could try updating the individual apps through the Microsoft Store.

**Comment by muratdk23** [comment]
Microsoft store doesn’t work too.

**Comment by conath** [comment]
TIL

**Comment by brunocastello** [comment]
I have this issue too with an ARM64 Win 11 Pro install. Any news on it?

**Comment by osy** [comment]
https://github.com/utmapp/UTM/issues/3023#issuecomment-914786903

**Comment by Jaiganeshkumaran** [comment]
I found a workaround to run these apps. While M1 can't run ARM32 apps, it can emulate x86 apps. Most of the Store apps also have an x86 version however Windows will not install them since it thinks the ARM32 package is a better match. Instead, you could download the package bundle from Microsoft Store server through a tool like https://store.rg-adguard.net/, rename the extension of downloded package bundle to .zip, copy the x86 package inside the zip and install that. (Don't directly install the package bundle without extracting the x86 one inside since it will install the ARM one).

**Comment by brunocastello** [comment]
Argh, at this point I think that it would be better to run the emulated x86 Windows 11 version. Too much work reinstalling the apps.

**Comment by Marcinoo97** [comment]
I though emulating x86 would be slow

**Comment by brunocastello** [comment]
@conath this appears to have been patched by Microsoft?
https://www.windowscentral.com/microsoft-fixes-problem-preventing-built-apps-opening-windows-11

**Comment by Jaiganeshkumaran** [comment]
> @conath this appears to have been patched by Microsoft? https://www.windowscentral.com/microsoft-fixes-problem-preventing-built-apps-opening-windows-11

No that's a different issue.

**Comment by brunocastello** [comment]
> I found a workaround to run these apps. While M1 can't run ARM32 apps, it can emulate x86 apps. Most of the Store apps also have an x86 version however Windows will not install them since it thinks the ARM32 package is a better match. Instead, you could download the package bundle from Microsoft Store server through a tool like https://store.rg-adguard.net/, rename the extension of downloded package bundle to .zip, copy the x86 package inside the zip and install that. (Don't directly install the package bundle without extracting the x86 one inside since it will install the ARM one).

I can't, because the App Installer refuses to start when I double click the x86 after extracting it.

**Comment by brunocastello** [comment]
> I found a workaround to run these apps. While M1 can't run ARM32 apps, it can emulate x86 apps. Most of the Store apps also have an x86 version however Windows will not install them since it thinks the ARM32 package is a better match. Instead, you could download the package bundle from Microsoft Store server through a tool like https://store.rg-adguard.net/, rename the extension of downloded package bundle to .zip, copy the x86 package inside the zip and install that. (Don't directly install the package bundle without extracting the x86 one inside since it will install the ARM one).

That workaround doesn't work anymore. Microsoft Store x86 installs successfully, but on first run, it automatically goes after an update for itself, which will install an arm32 version over it. Back to square one - which means that we will have to start to wait for Microsoft to update all apps to arm64 for their final version.

**Comment by Jaiganeshkumaran** [comment]
> That workaround doesn't work anymore. Microsoft Store x86 installs successfully, but on first run, it automatically goes after an update for itself, which will install an arm32 version over it. Back to square one - which means that we will have to start to wait for Microsoft to update all apps to arm64 for their final version.

Did I download the latest version? Also after installing the x86 version, disable auto-update for Store apps under Settings.

**Comment by brunocastello** [comment]
Does it also stop the Store from updating itself? Because this is the main problem before I could even see any app to download from it. The way it is now, after installing the x86 Microsoft Store, and any attempt to run it will just auto-update the Store itself, bringing back the ARM32 version over it. No matter how many times I reinstall the x86 Store, it always updates itself back to ARM32 version when I attempt to open the Store.

**Comment by Jaiganeshkumaran** [comment]
@brunocastello It should because the Store also updated that way.

**Comment by brunocastello** [comment]
OK, I'm gonna try again later.

**Comment by brunocastello** [comment]
@Jaiganeshkumaran Here's what I did to be finally able to load Microsoft Store
1) Regedit
2) Find HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsStore
3) Add a 32bit DWORD named AutoDownload and give it a value of 2
4) Profit

I'm currently testing if I can download and run certain apps. Probably some won't and will have to be reinstalled and updated the same way I did for Microsoft Store x86. Damnit. But it's better than nothing.

**Comment by brunocastello** [comment]
For the names of other Windows preinstalled apps, you can find a decent list here:
https://www.howtogeek.com/224798/how-to-uninstall-windows-10s-built-in-apps-and-how-to-reinstall-them/
And then use the same method described by Jaiganeshkumaran for Microsoft Store above. I have just tested it with Mail, Calendar and Photos.

**Comment by brunocastello** [comment]
The Microsoft Store app is still ARM32 apparently, as of February 15, 2022.

**Comment by LPFchan** [comment]
I think this should be explicitly mentioned in installation guide both [here](https://mac.getutm.app/gallery/windows-10) and [here](https://mac.getutm.app/gallery/windows-11-arm). I've wasted so many hours and energy trying to troubleshoot this problem and finding the culprit in a **closed** issue is beyond me.

**Comment by osy** [comment]
Honestly most people including me don't use the apps so it never crossed my mind. I'll add it next time I edit the guide.

**Comment by LPFchan** [comment]
> Honestly most people including me don't use the apps so it never crossed my mind. I'll add it next time I edit the guide.

Thanks for the update. In my use case I rely on [winget](https://www.microsoft.com/en-us/p/app-installer/9nblggh4nns1?SilentAuth=1&wa=wsignin1.0#activetab=pivot:overviewtab) and [winstall](https://winstall.app/) to quickly setup any new Windows installation.

**Comment by osy** [comment]
Updated guide at https://mac.getutm.app/gallery/windows-11-arm
