### ISSUE TITLE
Windows 11 Install-No network connection stalls install

### ISSUE THREAD

**Issue by sdgros01** [utmapp/UTM#3024]
**Describe the issue**
When installing Windows 11 I can not get past the initial boot as it stalls on network connection- ask to connect to next work to update and continue. I have tried multiple different network adapter settings without luck. Any suggestions on the proper adapter to use for connection in the VM with W11?

**Configuration (required)**
* UTM Version: 2.2
* OS Version: 14.7.1
* Device Model: iPad Pro M1
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? AltStore / TF Jitterbug

**Comment by conath** [comment]
This is due to emulated networking. #2353

To work around it you need to [skip the OOBE](https://m.youtube.com/watch?v=KsNoGPczavw&t=516).
