### ISSUE TITLE
Left navigation items (VMs) are squished

### ISSUE THREAD

**Issue by neilabdev** [utmapp/UTM#3026]
**Describe the issue**

The left navigation items are squished.

![Screen Shot 2021-08-17 at 8 21 48 AM](https://user-images.githubusercontent.com/2140679/129725712-6a59faa5-db1c-4f7a-9753-ab7a452acfd3.png)

**Configuration**
* UTM Version: 2.1.2 (31)  [ and 2.2.0 beta ]
* OS Version:  Mac OS 11.3.1
* Intel or Apple Silicon?  M1

**Crash log**

No crash

**Comment by ktprograms** [comment]
See #2335, tldr upgrade to at least Mac OS 11.4

**Comment by neilabdev** [comment]
@ktprograms  Many Thanks, 11.5 work just fine :)
