### ISSUE TITLE
Add keyboard shortcut to fullscreen window

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [utmapp/UTM#3035]
Add a keyboard shortcut - preferably Command+Control+F, to full screen the window or exit out of full screen if it's already in full screen without clicking on the green button.

**Comment by RobMaskell** [comment]
Also VMs that were fullscreen when shutdown and closed do not return as fullscreen when restarted, the lack of the standard keyboard shortcut just makes it harder to get back to where you were. This is a good enhancement for me
