### ISSUE TITLE
Command+Tab should be ignored by VM

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [utmapp/UTM#3036]
Today in a Windows VM if you press Command+Tab, it opens the Start screen or menu as the Command key is mapped to the Windows key. Although Windows+Tab opens task view on a regular computer, it doesn't open task view inside VM because Windows only receives the Command key due to the fact that when you press tab, macOS switches to another app, stopping input for the previous window.  This can be annoying because you might use Command+Tab to switch between the VM and other macOS applications and it does do that however when you switch back into the VM, you'll see the Start screen/menu appear.

**Comment by Jaiganeshkumaran** [comment]
If you have the VM full screen, you may use Ctrl+Left/Right arrow to switch to another space without opening the Start screen/menu.

**Comment by conath** [comment]
FYI There is [another QEMU fork](https://github.com/akihikodaki/qemu/tree/macos) available from @akihikodaki that has implemented full key and mouse "grabbing" (aka locking, capturing) on macOS. [Commits to macos branch](https://github.com/akihikodaki/qemu/commit/) (macOS branch is outdated, macos is the current one)

Maybe we can make use of their [macOS specific code](https://github.com/akihikodaki/qemu/blob/macos/ui/cocoa/app_controller.m#L372).

**Comment by conath** [comment]
Related to https://github.com/utmapp/UTM/issues/2677

**Comment by lolxdtyuir69** [comment]
# **just like yo mom should be fat LMAO HAHAHAA 🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣NOW TELL ME HOW 2 PIRAT MINECRAFT!!!!!🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕**

**Comment by lolsideed3i228392** [comment]
# @LUPHORIA GET RID OF THE FOKIN MUTE FEATURE
# @SM64JS GET RID OF THE FOCKIN MUTE FEATURE!!!
# [GET. RID. OF. THE. F&CKN. MUTE. FEATURE. YOU. lDl0TS!!! 😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺GET. RID. OF. THE. F&CKN. MUTE. FEATURE. YOU. lDl0TS!!! 😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺GET. RID. OF. THE. F&CKN. MUTE. FEATURE. YOU. lDl0TS!!! 😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺😈😈🤢🤢😾😾😾😾😾😾😾😾🖕👎🖕👺👺👺👺🖕🖕🖕🖕👎👎👎👹👹👹😈🖕🖕🖕👺👺🤬🤬🤬🤬🤬🤬🤬👹👹👹👹👺👺👺👺👺👺](https://www.youtube.com/watch?v=iA8iaum8HOg)

**Comment by GETRIDOFTHEFOKINMUTFETUR** [comment]
# @luphoria @sm64js @everyone yuo suKC ANN ANMAL P$%$Y!!!! F^%KCING N#^SGGERS!!  [I SAYD TO GET RD OF THE FOKCIN MUTT FETAURE!!!!!!!! IDTIOS!!! NT$GGERS!!!!!!!!! B!THC CU-_SMLUt!!!!!!👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠v👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠](https://www.youtube.com/watch?v=iA8iaum8HOg)

**Comment by osy** [comment]
Duplicate of #2677

**Comment by simonmichael** [comment]
This issue was closed in favour of #2677, but I'd like to highlight this UX glitch on mac, since it's disruptive and isn't mentioned there at all: 

Every time you switch away from a UTM windows vm with Command-Tab, when you switch back, the Start menu popup will be in your way, so you have to also hit Escape every time.

Thank you very much for the awesome UTM (and CrystalFetch)!

**Comment by claudeviool** [comment]
Still facing this issue. Sequoia 15.5, UTM 4.6.5.

Whenever capture is enabled or not, I am not able to control the guest via e.g. cmd+tab.
