### ISSUE TITLE
Fail to Install UTM on iPadOS 13 or iOS 12.4

### ISSUE THREAD

**Issue by wangyiwei2015** [utmapp/UTM#304]
- AltServer:
    Could not save \*\*\*.dylib in Framework folder.

- Xcode with re-signed ipa:
    Unable to install.

- Xcode compiling source code:
    Build failed: Could not find UTM/sysroot\*/\*\*\*.cpp.

I've tried with a free developer account and a paid account.
I'd appreciate any clues or tips on installing.

**Comment by jankais3r** [comment]
If you have a paid account, then generate a provisioning profile, use iOS App Signer to sign the app with that profile, and install the profile and the app with Apple Configurator. This process works 100%.

**Comment by wangyiwei2015** [comment]
> If you have a paid account, then generate a provisioning profile, use iOS App Signer to sign the app with that profile, and install the profile and the app with Apple Configurator. This process works 100%.

Thanks a lot! It finally worked, with the profile, App Signer, and Apple Configurator.
