### ISSUE TITLE
Root Permission for Jailbroken iOS Devices

### ISSUE THREAD

**Issue by 1640675651** [utmapp/UTM#3049]
For jailbroken devices, why not install UTM to the system app folder and give it root permission? In this way we can store the VM in an external storage, make a symlink in the /var/mobile/Documents folder, and run the virtual machine directly from the external storage. Common third-party apps can't access external storage due to apple's sandbox mechanism.

**Comment by Vishram1123** [comment]
This was how it was before AppSync was created. It worked well, but some features (like documents folder integration and settings integration) were unavailable, so the app was migrated to sandboxed (app sync).

**Comment by conath** [comment]
I suppose we can close it as "won't fix" then? @osy what do you think?

I believe we can implement external storage without changing where the app is installed. see #2451
