### ISSUE TITLE
Hide multicore config UI for unsupported architectures

### ISSUE THREAD

**Issue by jankais3r** [utmapp/UTM#306]

**Comment by zaptrem** [comment]
This isn't a bug. The warning is very clear that enabling is at one's own risk, so this just takes away choice from those who know what they're doing. If you're worried about uninformed people enabling it then complaining, maybe the option would have to be enabled from an app-wide settings page or something?

**Comment by osy86** [comment]
I made the warning message more explicit and right under the CPU cores option in RC3. The core option is also removed for the "simplified" setup (the screen you see when you first create a VM).
