### ISSUE TITLE
network connections to gearssdk.opswat.com

### ISSUE THREAD

**Issue by minusf** [utmapp/UTM#3070]
**Describe the issue**
I use little snitch.  When UTM starts up a VM it is trying to connect to `gearssdk.opswat.com`. As this domain resolves to `127.0.0.1`, i cannot disallow it. Any reason why UTM is trying to connect there?  I have seen other software, mostly anti virus and VPN doing the same.

**Configuration**
* UTM Version: 2.2.1
* OS Version: 11.5.2
* Intel or Apple Silicon? M1
VM: `debian-10.4-arm64-utm.zip` from gallery

**Comment by conath** [comment]
Puzzling indeed. I ran `grep -l gearssdk.opswat.com . -r` in the UTM source code folder and got no results. Web search returned [nothing specific](https://www.reddit.com/r/sysadmin/comments/fsm9ce/odd_site_pings_as_local_host/). More generally, Gears SDK is/used to be a Windows security thing [apparently](https://www.opswat.com/blog/opswat-releases-gears-sdk-endpoint-manageability-and-security).

**Comment by osy** [comment]
This must be something running from your VM (maybe Debian uses it for something?) UTM does not make any requests to that domain. Also make sure the version of UTM you are running either comes from the app store or the .dmg downloaded from Github and make sure that you have Gatekeeper turned on so macOS can notify you if the application has been modified by any third party.

**Comment by minusf** [comment]
thank you for looking into this.  i managed to reproduce it and i have little snitch, so here's the screenshot:
<img width="288" alt="Screenshot 2021-09-06 at 15 41 01" src="https://user-images.githubusercontent.com/3632883/132226194-9a1ac3a2-c3b3-4aac-8d9e-e8051563f3c2.png">

**Comment by osy** [comment]
What if you block it? Does it prevent anything from functioning? Does it only happen with Debian vm or does it happen with Windows vm as well?

**Comment by minusf** [comment]
it's not possible to block it because it resolves to `127.0.0.1`...  i think one candidate might be the terraform aws provider intalled on the VM, not sure.  i think this ticket can be closed.  not an UTM issue per se.
