### ISSUE TITLE
mac m1: apple store & appleTV empty after installing ubuntu OS on UTM

### ISSUE THREAD

**Issue by dhafer83** [utmapp/UTM#3075]
problem with applestore & apple TV : it seems like no internet connection after using UTM by installing ubuntu server ARM64 .
when i click on applestore or app TV  icons , the app window is empty without any pics or text. nothing is displayed in the window of both applications.

**Configuration**
* UTM Version: Last
* OS Version: Big Sur
* Intel or Apple Silicon? :M1

**Comment by conath** [comment]
Have you experienced this issue more than once? Did it persist when you restarted your Mac?

**Comment by dhafer83** [comment]
Hey,

I confirm that it was persistant and had to fix it by formatting my drive.

Regards,
