### ISSUE TITLE
Failing to install Windows 10

### ISSUE THREAD

**Issue by Steve-0628** [utmapp/UTM#3078]
**Describe the issue**
When trying to install Windows 10 (21H1, x64), randomly the VM crashes, and reboots.
Sometimes it gives me a BSOD and it says: IRQL NOT LESS OR EQUAL
It never occurred before selecting the disk drive. After that, it seems to be random. 

**Configuration**
* UTM Version: 2.1.2 (31)
* OS Version: macOS 11.4（20F71）
* Intel or Apple Silicon? Intel

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/7097946/debug.log)

**Upload VM**
(The extension is changed but it's the same)
[config.plist.txt](https://github.com/utmapp/UTM/files/7097951/config.plist.txt)

**Comment by Jaiganeshkumaran** [comment]
Did you set the disk type as NVME?

**Comment by Steve-0628** [comment]
So I tried these additional things: 
Change the disk type to NVMe and create a new drive; which failed
Start a new VM with only disk drives and memory modified; which also failed sometimes even before the disk selecting menu. 

Also, the NVMe drive requires me to get some kind of drivers, which I don't know which one to, to install Windows on it.

**Comment by Steve-0628** [comment]
I'm sorry but I found this issue on the Known-issues page. I'll close it for now.
