### ISSUE TITLE
Android 9 Stuck On Loading

### ISSUE THREAD

**Issue by thecomputermaster** [utmapp/UTM#308]
**Describe the bug**

When trying to load Android 9 on the app, it gets stuck on the Android lading screen and never moves any further. This happens with both 32-bit and 64-bit iso.

**To Reproduce**
Download Android 9 iso image from 
https://www.android-x86.org/releases/releasenote-9-0-rc1.html

Start a new virtual machine and select this as the iso to boot from. It will only get stuck on the Android loading screen, and after over half an hour won't move any further.

The settings tried are 
System Architecture x86_64
System pc
Memory 800mb
CPU Count 1
Try booting first from cd

JIT Cache Default MB
Force Multicore tried both on and off.

Thanks very much.

**Comment by lunjielee** [comment]
you need at least 2048mb ram to be able to boot android 9 which I think is impossible now except project sandcastle

**Comment by thecomputermaster** [comment]
Is it in the works to run Android 9 via UTM? Thanks. --Keifer From: lunjieleeSent: Sunday, April 26, 2020 6:05 PMTo: utmapp/UTMCc: thecomputermaster; AuthorSubject: Re: [utmapp/UTM] Android 9 Stuck On Loading (#308) you need at least 2048mb ram to be able to boot android 9 which I think is impossible now except project sandcastle—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by aakashverma12** [comment]
Android x86 4.3+ images requires kvm to boot and work. That’s why android 9 doesn’t work. 
Neither ios nor osx supports kvm yet, so no hopes currently.
It can only be done if the developer have android specific patches inside qemu which the developer has put on los priority and will be available in v2.
This issue has already been opened and is already answered before.
Please search for it in issues,

**Comment by upintheairsheep** [comment]
> you need at least 2048mb ram to be able to boot android 9 which I think is impossible now except project sandcastle

so use the Go version of android. Go requires just 512 MB ram.

**Comment by dauphintje** [comment]
> > you need at least 2048mb ram to be able to boot android 9 which I think is impossible now except project sandcastle
> 
> so use the Go version of android. Go requires just 512 MB ram.

Where do i find the iso?
