### ISSUE TITLE
headless + autostart VM

### ISSUE THREAD

**Issue by UrielCh** [utmapp/UTM#3081]
Hi,

I want to host some services in Linux VM into a Mac mini M1 for power efficiency reasons.
For that, the VM must restart after a power loss. 

I tried to copy and past the Qemu command exported by the QEMU menu, but it did not works. (I used brew QEMU version).

Another request, it would be nice if we could start a VM in headless mode.

**Comment by conath** [comment]
The URL scheme #2670 which will come in a future update will allow you to auto-start a VM on login. (A headless mode is not included with that PR.)

**Comment by UrielCh** [comment]
nice, & thx for this great piece of software.
