### ISSUE TITLE
TPM module emulation

### ISSUE THREAD

**Issue by muratdk23** [utmapp/UTM#3082]
Will be nice to have this feature to use windows 11 without limitations.

**Comment by apfimagination** [comment]
Perhaps this swtpm can be incorporated
https://github.com/stefanberger/swtpm

**Comment by apfimagination** [comment]
TPM seems to be already in QEMU:

In case an Arm virt machine is emulated, use the following command line:

qemu-system-aarch64 -machine virt,gic-version=3,accel=kvm \
  -cpu host -m 4G \
  -nographic -no-acpi \
  -chardev socket,id=chrtpm,path=/tmp/mytpm1/swtpm-sock \
  -tpmdev emulator,id=tpm0,chardev=chrtpm \
  -device tpm-tis-device,tpmdev=tpm0 \
  -device virtio-blk-pci,drive=drv0 \
  -drive format=qcow2,file=hda.qcow2,if=none,id=drv0 \
  -drive if=pflash,format=raw,file=flash0.img,readonly=on \
  -drive if=pflash,format=raw,file=flash1.img

**Comment by muratdk23** [comment]
How apply this to utm vm machine?

**Comment by apfimagination** [comment]
This is the latest as far as I can tell
https://github.com/stefanberger/swtpm/issues/493

**Comment by spikespaz** [comment]
Anybody know what I'm supposed to do about this?
```
qemu-aarch64-softmmu: -chardev socket,id=chrtpm,path=/tmp/win11tpm/swtpm-sock: Failed to connect to '/tmp/win11tpm/swtpm-sock': Operation not permitted
```

FYI, this may be useful to you.
```
brew tap spikespaz/jacob
brew install swtpm
```

**Comment by mjonsson1986** [comment]
how to use this?

**Comment by dxlr8r** [comment]
I have the same issue (`Failed to connect to`). Got swtpm running, and socket present. Since UTM runs in a sandbox, I even tried to create the socket inside the sandbox (`~/Library/Containers/com.utmapp.UTM/Data/Documents/...`), with same result.

I can initiate connection to the socket from my terminal though, and `swtpm` replies.

**Comment by michelealbrigo** [comment]
I can add some more details. I've started swtpm with:

`/opt/homebrew/bin/swtpm socket --tpmstate dir=/Users/myuser/Documents/UTM-VMs/Windows11.utm/Images --ctrl type=unixio,path=/Users/myuser/Documents/UTM-VMs/Windows11.utm/Images/swtpm-sock --log file=/Users/myuser/swtpm.log,level=20 --tpm2`

(I moved the Windows 11 VM to the Documents folder, and I am using a space-free name)

When starting QEMU with the switches:

`-chardev socket,id=chrtpm,path=/Users/myuser/Documents/UTM-VMs/Windows11.utm/Images/swtpm-sock`
`-tpmdev emulator,id=tpm0,chardev=chrtpm`
`-device tpm-tis,tpmdev=tpm0`

...I get the same error as @dxlr8r (I suppose):

![Schermata 2022-04-15 alle 13 36 10](https://user-images.githubusercontent.com/25572118/163566287-1c038a8c-8b6d-4ef4-abc0-c516d33357f0.png)

Neither logging on the swtpm nor on the qemu side yields any result, so I investigated a bit more in the system logs (Console.app with admin privileges), and I found out that...

`Sandbox: QEMULauncher(58414) deny(1) network-outbound /Users/myuser/Documents/UTM-VMs/Windows11.utm/Images/swtpm-sock`

...and this probably causes...

QEMUHelper: `Could not open() the item: [102: Operation not supported on socket]`
UTM: `nw_socket_handle_socket_event <private> Socket SO_ERROR [61: Connection refused]`

I hope this can be of use to solve the issue, let me know if you want me to attempt something else.

**Comment by idarek** [comment]
Hi All,
I have followed TPM 2.0 module installation and configuration with QEmu according to this site
[Software TPM Emulator For QEMU](https://en.opensuse.org/Software_TPM_Emulator_For_QEMU).

I setup `swtpm` startup procedure in terminal 

Createf folder inside my UTM image
```
mkdir /Users/dariusz/Library/Containers/com.utmapp.UTM/Data/Documents/Windows_11_ARM.utm/mytpm0 
```

Create TPM start file (with content below) and started
```
touch tpm
nano tpm
chmod +x tpm
./tpm
```

Content of tpm file:
```
swtpm socket --tpm2 --tpmstate dir=/Users/dariusz/Library/Containers/com.utmapp.UTM/Data/Documents/Windows_11_ARM.utm/mytpm0 --ctrl type=unixio,path=/Users/dariusz/Library/Containers/com.utmapp.UTM/Data/Documents/Windows_11_ARM.utm/mytpm0/swtpm-sock --log file=/Users/dariusz/tpm.log,level=20
```
then added the following in UTM/QEmu:
```
-chardev
socket,id=chrtpm,path=/Users/dariusz/Library/Containers/com.utmapp.UTM/Data/Documents/Windows_11_ARM.utm/mytpm0/swtpm-sock
-tpmdev
emulator,id=tpm0,chardev=chrtpm
-device
tpm-tis,tpmdev=tpm0
```

> I need to rename my system in UTM to be without spaces, as in another case I got information about operations not permitted as posted above.

When running Windows in UTM it starts spinning on the Gray screen. This is expected and as advised that will take a minute to generate keys and load Windows further. However in my instance after a short while, I received `An error has occurred` instead.

There is some progress but not sure where to go from there. The terminal did not show any logs and the specified log file do not show anything.

**Comment by gvaldezd** [comment]
Change the path for swtpm-sock to "com.utmapp.QEMUHelper" instead and create the mytpm0 folder and the tpm file(with the new path) there:

/Users/<your user>/Library/Containers/com.utmapp.QEMUHelper/Data/Documents/mytpm0 

the QEMULauncher executes the socket-sock file inside its own container and no more sandbox network-outbound error; now the VM boots OK and Windows11 recognizes the TPM 2.0 (you can verify it under the device manager)

![MacM1UTM_Windows11ARM64](https://user-images.githubusercontent.com/13753776/178400760-e78ce77b-8afd-4e6a-889d-cd4c135a18f3.jpg)

However,  the Windows driver or some missing config could not start the device...yet

**Comment by idarek** [comment]
Whats your setting in QEMU?
as mine
```
-chardev
socket,id=chrtpm,path=/Users/dariusz/Library/Containers/com.utmapp.UTM/Data/Documents/Windows_11_ARM.utm/mytpm0/swtpm-sock
-tpmdev
emulator,id=tpm0,chardev=chrtpm
-device
tpm-tis,tpmdev=tpm0
```

with
```
swtpm socket --tpm2 --tpmstate dir=/Users/dariusz/Library/Containers/com.utmapp.QEMUHelper/Data/Documents/mytpm0 --ctrl type=unixio,path=/Users/dariusz/Library/Containers/com.utmapp.QEMUHelper/Data/Documents/mytpm0/swtpm-sock --log file=/Users/dariusz/tpm.log,level=5
```

resulting an Error message when starting UTM machine
> qemu-aarch64-softmmu: -device tpm-tis,tpmdev=tpm0: 'tpm-tis' is not a valid device model name

**Comment by michelealbrigo** [comment]
I can confirm that @idarek and @gvaldezd parameters are working on my setup, too. I'm now stuck at the same point you are (TPM detected by Win11, but not started).

**Comment by gvaldezd** [comment]
Ok, doing some more tests:

If the `--tpm2` option is removed (TPM 1.2 by default is used) from the swtpm setup, the tpm.log files shows a lot of activity (like everything is running fine before Windows boots), then under Device manager, listed under Memory Connections the TPM platform is OK but is not shown under Security Devices, then if you run CMD tmp.msc shows not valid TPM platform.

![TPM_1_2_Device-Manager](https://user-images.githubusercontent.com/13753776/179040600-230f6a0b-639f-489a-bd48-abccff9b1686.jpg)
[tpm_1_2.log](https://github.com/utmapp/UTM/files/9113813/tpm_1_2.log)

If we add the option `--tpm2`, the TPM2.0 device is not working (previous error) and the log shows less activity.

![TPM_2_0_Device_Manager](https://user-images.githubusercontent.com/13753776/179041907-a1941528-e289-4da9-99c8-d3c2ea8686c5.jpg)
[tpm_2_0.log](https://github.com/utmapp/UTM/files/9113833/tpm_2_0.log)

It seems there's something wrong in how Windows11Arm64 is identifying the TPM2.0 platform and the driver identified.

**Comment by benjamindahl** [comment]
Would be great if there where an "out of the box" solution integrated into UTM or  or a summarized "step by step" solution for Mac users. At the moment I don't really know how to realize what has been written, because it's quite messy.

**Comment by gvaldezd** [comment]
Hi, just to let you know, here's the TPM emulation using VW Fusion Tech Preview for OS (with M1), is working correctly under device manager, using the same MS 2006 Driver (default) with Windows11 ARM64, don't know what the differences are with swtpm.

<img width="587" alt="TPM_VWFusion" src="https://user-images.githubusercontent.com/13753776/196303336-c7fc814d-78bb-4a57-a60c-e4743dcda975.png">

**Comment by idarek** [comment]
Because they developed and provided their driver solution for it. Behind VM Fusion is a big company with larger funds. Behind UTM there is no so much. Unless we all work together to get this working, there is no golden solution for that.

**Comment by ehntoo** [comment]
Looks like the issue with TPM2.0 might be a UEFI firmware issue, and the OVMF image `edk2-aarch64-code.fd` from upstream QEMU might need to be rebuilt with `TPM2_ENABLE`. https://groups.google.com/g/linux.debian.bugs.dist/c/KIARY7bL5RI

It seems the upstream EDK2 defaults for the `ArmVirtQemu.dsc` that AFAICT is the basis for the firmware in upstream QEMU does not include TPM2.0 support: https://github.com/tianocore/edk2/blob/b92298a/ArmVirtPkg/ArmVirtQemu.dsc#L32

It looks somewhat straightforward to build a custom UEFI image following Gerd Hoffman's instructions here: https://www.kraxel.org/blog/2022/05/edk2-virt-quickstart/

**Comment by wzrzt** [comment]
Are there any limitations in Windows11 without TPM2.0?  I'm using windows11 2021H2 and wanna to upgrade to 2022H2 but failed because of missing TPM2.0 and SecureBoot. I don't want a clean setup, so  I tried Rufus(https://rufus.ie/en/) and it has to create bootable u-disk from iso, and it has option to remove TPM2.0 and secure boot limitation of windows setup program. And then I used setup.exe in u-disk to upgrade windows. It works.

**Comment by subesokun** [comment]
@ehntoo Thanks for your research! Just wondered if you've been able to get it work after all?

**Comment by phirestalker** [comment]
Since we can't update Windows 11 Arm automatically without TMP 2.0, does anyone know of another method that does not require wiping and reinstalling?
The funny thing is I JUST downloaded the damn thing today FROM Microsoft, yet when I boot it up it tells me it is expired. WTF?

**Comment by phirestalker** [comment]
OK all. I found an article that explains how to force windows 11 arm into the dev channel. Tested and it is updating as I type.

[https://winaero.com/how-to-enable-windows-11-dev-channel-on-unsupported-device/](https://winaero.com/how-to-enable-windows-11-dev-channel-on-unsupported-device/)

**Comment by xilopaint** [comment]
> does anyone know of another method that does not require wiping and reinstalling

@phirestalker Have you come up with an answer?

**Comment by phirestalker** [comment]
> @phirestalker Have you come up with an answer?

I gave up and think I will wait for a real release of Windows 11 arm. I am just using my windows box with RDP for now.

**Comment by MasterDriverRex** [comment]
> Testing with the following:
> 
> ```
> -chardev
> socket,id=chrtpm,path=/Users/dariusz/Library/Containers/com.utmapp.QEMUHelper/Data/Documents/mytpm0/swtpm-sock
> -tpmdev
> emulator,id=tpm0,chardev=chrtpm
> -device
> tpm-tis-device,tpmdev=tpm0
> ```
> 
> Starting TPM prior to UTM with
> 
> ```
> swtpm socket --tpm2 --tpmstate dir=/Users/dariusz/Library/Containers/com.utmapp.QEMUHelper/Data/Documents/mytpm0 --ctrl type=unixio,path=/Users/dariusz/Library/Containers/com.utmapp.QEMUHelper/Data/Documents/mytpm0/swtpm-sock --log file=/Users/dariusz/tpm.log,level=5
> ```
> 
> Can confirm that is working. Great! Now the matter of drivers to sort out :)
> 
> > Relace `/dariusz/` with your username

Where do I put this?
