### ISSUE TITLE
2.2.2/2.2.3 DMG build broken on Monterey beta

### ISSUE THREAD

**Issue by greybaron** [utmapp/UTM#3083]
previous builds (including beta 2.2.1) worked fine.

2.2.2 displays "啟動 QEMU 時發生錯誤" ("Error starting QEMU").
This happens on new VM's as well, on any arch

the debug log only contains the QEMU launch command.

macOS 12 beta 6 (21A5506j)
Intel MBP 2015 13"
[debug.log](https://github.com/utmapp/UTM/files/7111326/debug.log)

**Comment by osy** [comment]
Is this from the DMG or TestFlight?

**Comment by greybaron** [comment]
DMG.

**Comment by osy** [comment]
Can you try the new beta v2.2.3?

**Comment by greybaron** [comment]
same error unfortunately

**Comment by osy** [comment]
Can you open Console.app and filter by "QEMU". When it fails, you should see an error message "Error starting QEMU:" followed by the description.

**Comment by greybaron** [comment]
`error	11:31:42.796610+0200	kernel	exec of /Applications/UTM.app/Contents/XPCServices/QEMUHelper.xpc/Contents/MacOS/QEMULauncher.app/Contents/MacOS/QEMULauncher denied since it was quarantined by Safari;B885D5F6-0887-4C22-B7A4-E820F7BD13E and not approved by Gatekeeper, qtn-flags was 0x00000183


standard	11:31:42.796804+0200	QEMUHelper	Error starting QEMU: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"`

**Comment by osy** [comment]
How did you install it? Typically it's:

1. Download the DMG from Safari
2. Open the DMG wit Finder
3. Drag UTM.app from the DMG to /Applications
4. Double click UTM.app in /Applications to open it
5. macOS will prompt you once: `You are opening the application “UTM” for the first time. Are you sure you want to open this application?` and press `Open`
6. You will see "Verifying UTM" and macOS does the signature check.
7. macOS will prompt you a second time: `“UTM” is an app downloaded from the Internet. Are you sure you want to open it?` and press `Open` again
8. UTM will open

If you follow all that, at step 4, qtn-flags should be 0x183 and at step 8 qtn-flags should be 0x1c3. Once it's 0x1c3, you should not get the error. For some reason you aren't getting 0x1c3, so I'm wondering if you've installed it in some other way?

**Comment by greybaron** [comment]
Very interesting. This is how I always did it, however now I remember an important detail: my Monterey install always tells me I‘m opening UTM for the first time. I think it does this for other apps as well. I will try a clean install of Monterey now

**Comment by greybaron** [comment]
I have discovered the root cause: with SIP disabled, macOS apparently never ran stage 5 and later (thus telling me every time that I‘m opening for the first time). I‘m pretty sure this is a Monterey bug so I‘m closing this issue

**Comment by GregOriol** [comment]
I just had this problem after downloading UTM on macOS Monterey 12.0.1.

A solution is to remove the quarantine attributes manually:
```
xattr -r -d com.apple.quarantine /Applications/UTM.app/
```
