### ISSUE TITLE
Virtual Keyboard Exchanged letters and symbols

### ISSUE THREAD

**Issue by gilcruz007** [utmapp/UTM#309]
On the virtual machines that I installed: Windows 10 and Kali linux some virtual keyboard characters are exchanged, the symbol / inserts the letter Ç, this happens with other letters and symbols too, maybe the ios entry is not compatible because I did  test with other keyboards like Google's and the problem persists forcing the use of the VM's system keyboard, I changed other entries in the installed system to try a better recognition but without success.

**Comment by greybaron** [comment]
It is not ideal, but you need to always set the keyboard layout inside your VM to english QWERTY keyboard, it doesn‘t matter which keyboard you use on the iOS side

**Comment by gilcruz007** [comment]
thanks ✌🏽
