### ISSUE TITLE
Mac99: Mouse permanently detaches if moved outside of window

### ISSUE THREAD

**Issue by kode54** [utmapp/UTM#3095]
**Describe the issue**
When starting a MacOS 9 image, the mouse must be attached to the window before macOS boots, and must never leave the window. The moment it is detached using control+option, or moved outside of the window, it becomes permanently detached until the machine is rebooted.

**Configuration**
* UTM Version: 2.2.3
* OS Version: macOS Big Sur 11.5.2
* Intel or Apple Silicon? Apple Silicon

**Crash log**
No crash.

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/7132320/debug.log)

**Upload VM**
[config.plist.zip](https://github.com/utmapp/UTM/files/7132321/config.plist.zip)

**Comment by osy** [comment]
@kode54 Is this an issue introduced in 2.2.x or does it also persist in older versions? I have a macOS 9 image and don't observe this.

**Comment by kode54** [comment]
Does it matter that I have two mice attached to the machine? I'll investigate with the current stable release as well.

**Comment by osy** [comment]
Oh I've never tested with two mice, but I can see how that may cause issues...

**Comment by kode54** [comment]
First I'll try powering off the Magic Mouse and see how it reacts to just the corded mouse I usually use just for gaming.

**Comment by kode54** [comment]
Nope, it refuses to capture the mouse at all. It just passes right over the window, only hiding it as it passes over, but never captures it.

**Comment by conath** [comment]
I'm not sure I understand the issue description, but I will add my own observation of MacOS 9 in UTM: it only works with the pointer captured. Otherwise the mouse jumps to the bottom right of the window and stays there.
<img width="340" alt="utm-capture-pointer" src="https://user-images.githubusercontent.com/12073163/132919084-61627a8c-2c23-4df1-b53e-1d417e77dee6.png">

**Comment by kode54** [comment]
Okay, my toolbar isn't exactly laid out like that, but yeah, I see that mouse capture by clicking that button does work. Oops. It wasn't working before, maybe I did something wrong.
