### ISSUE TITLE
Differentiate the main UTM window title from VM windows

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#3099]
After clicking Play to run a VM on macOS, the main UTM window and the VM's window have the same title:

![Screen Shot 2021-09-10 at 12 50 12](https://user-images.githubusercontent.com/12073163/132842682-e17db0c0-e86f-4e35-ac1d-3fe4b90549d4.jpg)

This is confusing when trying to switch between them using the menu bar item "Window".
The VM and main windows should each gain additional text to indicate which one is which. For example, the VM window could indicate the state of the VM ("Windows 10 installed – running").

**Comment by Jaiganeshkumaran** [comment]
I think it's better to keep the title of the main window as UTM instead of the selected VM's name.

**Comment by ktprograms** [comment]
Here's my quick research into trying to fix this: UTM uses the `.navigationTitle` modifier to set the title in the main window UI. However, the title set there is also used in the dock context menu. As far as I can tell, there isn't any way to have a different navigation title and dock title.

**Comment by conath** [comment]
I've gotten this to work by removing the `navigationTitle` from the `VMDetailsView`. However this creates a UX problem: now the title of the toolbar doesn't show the name of the selected VM anymore.
<img width="968" alt="utmtitle" src="https://user-images.githubusercontent.com/12073163/134077915-c98d62fe-d2af-4865-8498-48de69617476.png">

There needs to be a way to keep the window title from changing while still showing the name of the selected VM. Alternatively, the details screen could be redesigned to show the name on macOS. @osy what to you think?

**Comment by conath** [comment]
Or maybe UTM could be changed to have a Window menu similar to messages, where the main window is always listed separately from any conversation windows. 
<img width="587" alt="Messages app on macOS. Two windows are open, one with all conversations and one with just one conversation. The Window menu is selected and shows the main Messages window separated from the conversation window by a separator line." src="https://user-images.githubusercontent.com/12073163/134078727-91da54c8-15b5-4274-bade-a4b03e7e82ca.png">

**Comment by osy** [comment]
Fixed with #3125
