### ISSUE TITLE
[qemu] Implement bulletproof JIT

### ISSUE THREAD

**Issue by osy86** [utmapp/UTM#31]
Have a mirror mapping of RW and RX pages so we don’t have to unlock/lock memory.

**Comment by nullpixel** [comment]
question: is there any point in this?

**Comment by osy86** [comment]
Much fastee

**Comment by nullpixel** [comment]
interesting - guess that it is really expensive to keep changing page permissions

**Comment by saagarjha** [comment]
Maybe not with APRR
