### ISSUE TITLE
Disable suspend/resume when no compatible disk image is loaded

### ISSUE THREAD

**Issue by BenjyWiener** [utmapp/UTM#310]
If UTM is exited while a VM is suspended, attempting to resume the VM after restarting UTM results in the following message:

> QEMU exited from an error: qemu: info: Spice:
> reds.c:3334:spice_server_remove_interface: remove
> SPICE_INTERFACE_RECORD

After pressing "OK" UTM exits, and then the VM can be restarted normally.

**To Reproduce**
1. Start a VM (this has happened for every VM I've tried, including TinyCore)
2. Suspend the VM
3. Exit UTM using the 'X' (alternatively, leave UTM in the background until iOS kills it)
4. Relaunch UTM and attempt to resume the VM

**Xcode debug output (from second run, trying to resume VM)**
[Xcode debug.log](https://github.com/utmapp/UTM/files/4536711/Xcode.debug.log)

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/4536700/debug.log)

**Upload VM**
[TinyCore.utm.zip](https://github.com/utmapp/UTM/files/4536704/TinyCore.utm.zip)

**Comment by osy86** [comment]
Did you change any settings?

**Comment by BenjyWiener** [comment]
No, these results are all from a fresh installation in the Simulator (but I get the same results on my device).

**Comment by osy86** [comment]
> qemu: No block device supports snapshots

So the issue is that you don't have a HDD image. That's needed for suspend/resume. I will make this more clear in a future release.

**Comment by BenjyWiener** [comment]
What are the HDD requirements? On my VMs that do have an HDD image, I get the following line in the debug output:

> qemu: Device ‘drive0’ is writable but does not support snapshots

The image is a raw disk image (created with UTM) mounted as a disk image on ide.

**Comment by osy86** [comment]
It needs to be qcow2

**Comment by BenjyWiener** [comment]
Does UTM only create raw images, or does it go based on the provided file extension?

**Comment by osy86** [comment]
The creation supports two types. If you check the box it’s qcow2 otherwise it’s raw.

**Comment by BenjyWiener** [comment]
Got it. This should probably be made more clear in the app. Especially since the placeholder text is “hda.img” (and raw images can be sparse). Should I open a new issue?

**Comment by osy86** [comment]
No need, I’ll use this issue to improve it.
