### ISSUE TITLE
Unable to release keyboard while USB popup is shown; system unresponsive

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#3101]
When UTM has captured the keyboard and mouse to the guest, all inputs are redirected to it. This means, if a popup is shown like the USB passthrough one, it is impossible to interact with the popup. (other than Touch Bar)
This means the system becomes unusable, since keyboard input is locked to the VM and at the same time, the "release input" shortcut stops working (ctrl-opt/alt).

I suggest the inputs should be released automatically if an alert/popup appears.

**Configuration**
* UTM Version: 2.2.4
* OS Version: 11.5.2
* Intel or Apple Silicon? Apple Silicon

**Comment by jppmac** [comment]
Goes to the UTM preferences.
Check the USB box.

![UTM](https://user-images.githubusercontent.com/91919142/135929515-d3461d0c-91a8-4f85-bfb8-fd4b1ce4bf2d.png)

You can connect a mouse and no confirmation will be requested. The mouse works.
