### ISSUE TITLE
UI for customizing QEMU -rtc option.

### ISSUE THREAD

**Issue by trustin** [utmapp/UTM#3104]
UTM currently adds `-rtc base=localtime` option automatically. It'd be nice if there's a configuration UI that allows a user specify other RTC options. More specifically, when running Linux guests, it makes sense to specify `-rtc base=utc` by default.

**Comment by brunocastello** [comment]
I also generally use `-rtc base=localtime,clock=host` when using vanilla QEMU. Being able to customize it would be good. Sometimes the clock is behind the host clock by a few minutes...

**Comment by wolfo** [comment]
It also would be handy for running Beta versions of OS's that expired on a certain date. I have added `-rtc base=2000-05-05` in the extra QEMU arguments which, oddly enough, worked yesterday, but is now again superceded by the earlier automatic `rtc base=localtime`.

It would also be helpful if you could import a qemu string just like you can currently export it.

**Comment by adespoton** [comment]
Related to #3124
