### ISSUE TITLE
Transfer files 

### ISSUE THREAD

**Issue by shalom500** [utmapp/UTM#311]
Hello, I have XP
Please someone can help me understand how to transfer files from iphone to the umt win XP

**Comment by jankais3r** [comment]
You can read about shared folders in the [wiki](https://github.com/utmapp/UTM/wiki/Useful-tips), otherwise go to Discord to ask more questions. Issues are for reporting bugs.

**Comment by shalom500** [comment]
But I don’t have a network on the win Xp, 
How should I make a internet on the win xp

**Comment by osy86** [comment]
Answered in wiki.

**Comment by fastfading** [comment]
this wiki https://github.com/utmapp/UTM/wiki/Useful-tips
is out of date  

Open Services (run services.msc) and Stop & Disable the "Spice webdav proxy" service
Create a file called service.bat containing the following line and copy it to C:\Program Files\SPICE webdavd\ folder:
"C:\Program Files\SPICE webdavd\bin\spice-webdavd.exe" -p 80 --no-service
there is no "Spice webdav proxy" service
and there  is  no "C:\Program Files\SPICE webdavd\bin\spice-webdavd.exe"

**Comment by jankais3r** [comment]
Unless you are suggesting that spice went back and secretly changed contents of a package from 2017, it cannot be out of date. What is the name of the package you installed?

**Comment by fastfading** [comment]
mac m1 12.3.1
I get the utm file from here   https://mac.getutm.app/gallery/windows-xp
install https://archive.org/details/en_windows_xp_professional_with_service_pack_3_x86_cd_vl_x14-73974_202010  this winxp iso 
then install spice-guest-tools-0.164.3.iso  

<img width="687" alt="image" src="https://user-images.githubusercontent.com/8351732/167364728-39cb3ba5-8d42-4700-b657-53f12622998a.png">

**Comment by fastfading** [comment]
<img width="784" alt="image" src="https://user-images.githubusercontent.com/8351732/167365067-c6ec18df-ccf8-4ce6-84d2-3e1a3b7be91f.png">
install  fail

**Comment by fastfading** [comment]
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/8351732/167365387-ec52d8e0-b7d4-4d67-869a-1f0c986388b3.png">

**Comment by jankais3r** [comment]
Have you read the first step of the guide?
> 1. Download SPICE webdav daemon v2.2 (newer versions don't work on XP)

You installed SPICE 2.4

**Comment by ranmocy** [comment]
I've tried to follow the guide with SPICE 2.2 and the service keeps failing upon startup. When I tried to launch it manually from cmd it says "System can not find the file":

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/601767/172881683-f0e049ce-98bf-45cf-b1fe-0852189c6905.png">

I'm using UTM 3.2.4 on Macbook Pro M1, the guest OS is Windows XP SP3 + spice-webdavd-x86-2.2.msi.

**Comment by tmbRandy** [comment]
> Have you read the first step of the guide?
> 
> > 1. Download SPICE webdav daemon v2.2 (newer versions don't work on XP)
> 
> You installed SPICE 2.4

A download link would be helpful

**Comment by gingerbeardman** [comment]
@tmbRandy quick google gives me https://www.spice-space.org/download/windows/spice-webdavd/
