### ISSUE TITLE
Unable to start a VM from Gallery

### ISSUE THREAD

**Issue by svet007** [utmapp/UTM#3111]
**Describe the issue**
While starting a Debian 10.4/minimal from UTM Gallery, UTM crashes.

<img width="1824" alt="Screen Shot 2021-09-13 at 5 35 48 PM" src="https://user-images.githubusercontent.com/5215578/133160344-92035eeb-9b3f-4c35-b660-98b921460229.png">

**Configuration**
* UTM Version: 2.2.4
* OS Version: MacOS 11.5.2
* Apple Silicon

**Crash log**
[QEMULauncher_2021-09-13-173539_Svitlanas-Mac-mini-M1.crash.zip](https://github.com/utmapp/UTM/files/7157491/QEMULauncher_2021-09-13-173539_Svitlanas-Mac-mini-M1.crash.zip)

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/7157497/debug.log)

**Upload VM**
[config.plist.zip](https://github.com/utmapp/UTM/files/7157499/config.plist.zip)

**Comment by ktprograms** [comment]
Does the crash stop if you edit the VM and disable audio? I noticed in the debug log there were coreaudio errors.

**Comment by svet007** [comment]
Turning audio off helped, thanks!
