### ISSUE TITLE
Add additional soundcards for PPC

### ISSUE THREAD

**Issue by snslpa** [utmapp/UTM#312]
The available ISA soundcards are not compatible with macOS, can you add screamer or burgundy? Thanks

**Comment by snslpa** [comment]
Thanks osy86

**Comment by osy86** [comment]
After researching I see that this requires using a different QEMU fork. I'm not changing QEMU backend for 1.0 release so this will have to target post-1.0. Probably will also be merged with the Android fork (#29)

**Comment by IIWare** [comment]
would be great if it wasn't removed from the v2.0 milestone

**Comment by osy86** [comment]
We are already using a fork of qemu and merging with another fork complicates the build process. Ideally the PPC stuff gets merged into qemu proper. Otherwise, this won’t be considered until the iOS patches make it into qemu.
