### ISSUE TITLE
mac99: additional configuration for macOS

### ISSUE THREAD

**Issue by snslpa** [utmapp/UTM#313]
I have tried macOS 9.1, 9.2.2, 10.0, 10.1, and 10.3 All works great but in 10.0 and 10.1 doesn't work the mouse and keyboard.

The reason is that we need an option for: (In the processor selection).

-M mac99,via=pmu | pmu power management, providing USB mouse and keyboard
-M mac99,via=pmu-adb | pmu power management with adb bus for older OSs not supporting USB
-M mac99,via=cuda | cuda power management with adb bus (this is the default)

Please, also add in the mac99 processor this description: Mac G4 Processor

Thanks

**Comment by rreinhardt** [comment]
Not to hijack, but wasn’t sure how else to follow up on this... what config did you use to get mouse and keyboard working on MacOS 9.1 and 9.2.2? @snslpa 

Thanks!

**Comment by snslpa** [comment]
Hello, only mouse sorry, not the keyboard. I used this ISO https://winworldpc.com/product/mac-os-9/91

**Comment by snslpa** [comment]
Thanks osy86

**Comment by jankais3r** [comment]
I have an OS X 10.5 VM in UTM v1.0 RC2. Machine set to mac99. With default config, mouse works, but software keyboard does not. External keyboard works fine. When I manually set additional QEMU argument to `via=pmu` or `-via=pmu` (not sure if the dash is required, so I've tried both), the VM does not even start and whole UTM freezes and reboot is required. I assume that's because `via=pmu` is already applied automatically when mac99 is selected? Anyway, yeah, the soft keyboard doesn't work.

**Comment by osy86** [comment]
@snslpa I don't want to modify the config GUI for 1.0. This could be an option post 1.0, but I'm wondering if there's any downside of setting `via=pmu-adb` as the default. You say 10.0 and 10.1 doesn't work with `via=pmu` but does `via=pmu-adb` work for all versions?

**Comment by osy86** [comment]
Okay, I see that `via=pmu-adb` does not work for all versions. In v1.0, I'll give the ability to specify custom machine properties. In v2.0, we should have an ability to create VM templates to make it easier to config (that way we don't need complicated GUI options for rarely used things) #336

**Comment by osy86** [comment]
Also regarding this comment
> Please, also add in the mac99 processor this description: Mac G4 Processor

I am sticking with the QEMU descriptions for now because eventually I want a script to pull strings directly from QEMU (whenever there's an update).

**Comment by Joe-Moussally** [comment]
Anyone resolved this issue? I'm dealing with the same problem here, stuck at setting up MacOS X. Mouse/Trackpad not working.
