### ISSUE TITLE
Drivers

### ISSUE THREAD

**Issue by snslpa** [utmapp/UTM#314]
You should add drivers.iso for the most common OS inside the App Folder such a toolbox in other emulation apps. 

It can help a lot. 

temporary the SPICE driver that in Windows 9x worked for me.

Thanks.

**Comment by itselijahciali** [comment]
SPICE drivers seem to be a little too big to include every OS, what if it downloaded your respective OS's SPICE drivers on a per-VM basis?

**Comment by osy86** [comment]
Agreed, it's too big to distribute for all different OS. Once I get to writing a user guide, I will include the links.
