### ISSUE TITLE
Windows 11 ARM64 Build 22454 BSOD

### ISSUE THREAD

**Issue by lilvadim** [utmapp/UTM#3141]
The new Windows 11 for ARM64 Build 22454 (available [here](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewARM64) won't boot. I converted the file to `qcow2` and then run but there is BSOD "INACCESSIBLE BOOT DEVICE". Previous available build 22000.132 run correctly.

**Configuration**
* UTM Version: 2.2.4
* OS Version: 11.6
* Intel or Apple Silicon? Silicon

**Comment by conath** [comment]
Which UTM version did you use to boot the previous build?

Please add the basic troubleshooting info as requested in the issue template. Otherwise we can't pinpoint the cause of this issue. Thanks.

**Comment by lilvadim** [comment]
I used 2.2.4 version to run previous build, I guess. I'll send debug log later.

**Comment by lilvadim** [comment]
I have just noticed that previous build that I used to run successfully also falls into this BSOD (INNACCESSIBLE BOOT DEVICE). I will try to reinstall UTM app.

**Comment by muratdk23** [comment]
Build 22468 works fine.

**Comment by muratdk23** [comment]
Build 22468 works fine.

**Comment by Francesco146** [comment]
> Build 22468 works fine.

Well, I still get the BSOD and can't install it so... how did you install this build of Windows 11 in details?

**Comment by muratdk23** [comment]
> > Build 22468 works fine.
> 
> Well, I still get the BSOD and can't install it so... how did you install this build of Windows 11 in details?

I installed through windows update.

**Comment by Francesco146** [comment]
> > > Build 22468 works fine.
> > 
> > 
> > Well, I still get the BSOD and can't install it so... how did you install this build of Windows 11 in details?
> 
> I installed through windows update.

Ok, so the installer of the build is broken, no the actual build. It's a start

**Comment by conath** [comment]
Did anyone take note of the hard disk interface that is set in their VMs when this BSOD appears? My theory is that it's set to VirtIO and Windows doesn't like that. NVMe or USB should work, though.

**Comment by Francesco146** [comment]
> Did anyone take note of the hard disk interface that is set in their VMs when this BSOD appears? My theory is that it's set to VirtIO and Windows doesn't like that. NVMe or USB should work, though.

mine was set on NVMe

**Comment by dude19me** [comment]
mine windows 11 so slow cant install

**Comment by lilvadim** [comment]
> > > Build 22468 works fine.
> > 
> > 
> > Well, I still get the BSOD and can't install it so... how did you install this build of Windows 11 in details?
> 
> I installed through windows update.

But Windows Update does not work on Insider builds, does it?

**Comment by muratdk23** [comment]
> > > > Build 22468 works fine.
> > > 
> > > 
> > > Well, I still get the BSOD and can't install it so... how did you install this build of Windows 11 in details?
> > 
> > 
> > I installed through windows update.
> 
> But Windows Update does not work on Insider builds, does it?

Find offlineinsiderenroll program and you can turn on receiving dev builds.

**Comment by lilvadim** [comment]
> Did anyone take note of the hard disk interface that is set in their VMs when this BSOD appears? My theory is that it's set to VirtIO and Windows doesn't like that. NVMe or USB should work, though.

Oh, I am sorry, totally forgot to set it so. Now latest Windows Build runs as it was. Using latest UTM release. 

Off topic: where or when I can get information about graphics acceleration for Windows 11 ARM VM on Apple Silicon?

**Comment by Francesco146** [comment]
> > Did anyone take note of the hard disk interface that is set in their VMs when this BSOD appears? My theory is that it's set to VirtIO and Windows doesn't like that. NVMe or USB should work, though.
> 
> Oh, I am sorry, totally forgot to set it so. Now latest Windows Build runs as it was. Using latest UTM release.

oh really? works converting the disk in cow2 or keeping it in vhdx?

> Off topic: where or when I can get information about graphics acceleration for Windows 11 ARM VM on Apple Silicon?

idk man, sry

**Comment by lilvadim** [comment]
> > > Did anyone take note of the hard disk interface that is set in their VMs when this BSOD appears? My theory is that it's set to VirtIO and Windows doesn't like that. NVMe or USB should work, though.
> > 
> > 
> > Oh, I am sorry, totally forgot to set it so. Now latest Windows Build runs as it was. Using latest UTM release.
> 
> oh really? works converting the disk in cow2 or keeping it in vhdx?
> 
> > Off topic: where or when I can get information about graphics acceleration for Windows 11 ARM VM on Apple Silicon?
> 
> idk man, sry

I have not tried with VDHX, I converted then run.
