### ISSUE TITLE
MacOS could't connect with ssh to VM ubuntu

### ISSUE THREAD

**Issue by Lisstrange** [utmapp/UTM#3143]
**Describe the issue**
I have tryed to setup linux VM on Mac M1 (https://medium.com/@lizrice/linux-vms-on-an-m1-based-mac-with-vscode-and-utm-d73e7cb06133)

I installed ubuntu VM, selected newtwork mode *emulated VLAN* . Setup port like there
https://miro.medium.com/max/4800/1*yABPQBtxXg8_5l8MlYOLqA.png

Ubuntu server can see your adress (ssh -p 22 127.0.0.1)
But Macbook can't find it. 
- ssh -p 2200 127.0.0.1
return: Connection reset by peer

**Configuration**
* UTM Version : 2.2.4 
* OS Version:  12.0
* Intel or Apple Silicon?  Apple Silicon

what should I do?

**Comment by conath** [comment]
Duplicate of #2534 

You need to switch to another mode other than emulated network to use SSH. https://github.com/utmapp/UTM/discussions/2535#discussioncomment-1398958

@osy This issue has been around for some time and I can reproduce. Is this something that can be fixed here or is it QEMU/SPICE territory?

**Comment by ml2s** [comment]
Is sshd active on Ubuntu? Inside VM, try:

> ssh localhost
or
> sudo systemctl status sshd

if it's not even installed:
> sudo apt install openssh-server

**Comment by Lisstrange** [comment]
@conath  I selected Network mode  - shared network initially.

**Comment by Lisstrange** [comment]
@ml2s ssh is active
<img width="585" alt="Снимок экрана 2021-09-29 в 23 19 33" src="https://user-images.githubusercontent.com/47192124/135342554-e82c946e-12c5-4949-a32c-9dddab2c0ddc.png">

**Comment by Lisstrange** [comment]
I decide the problem:
 1) select  Network mode - shared network
 2) get guide to connect ssh
 
<img width="567" alt="Снимок экрана 2021-09-29 в 23 01 08" src="https://user-images.githubusercontent.com/47192124/135353130-d668edd3-9d93-4b69-a0b4-0e26410c74bc.png">

3) connect to ubuntu server with ssh <YOUR_USERNAME>@guide host
<img width="556" alt="Снимок экрана 2021-09-30 в 00 49 55" src="https://user-images.githubusercontent.com/47192124/135353539-1d151b49-1241-48e9-b780-13cbd95fe976.png">

**Comment by conath** [comment]
@Lisstrange Thanks for sharing your fix. Does this also work in Emulated Network mode?

**Comment by anzbert** [comment]
hey @Lisstrange what does step two mean in your fix?

```2) get guide to connect ssh```

Thx :)
