### ISSUE TITLE
Error: Device 'vmnet-macos' could not be initialized

### ISSUE THREAD

**Issue by zigang93** [utmapp/UTM#3145]
**Describe the issue**
I follow the instruction to install arm based ubuntu..
it show this error after I select the iso to run ..
`qemu-aarch64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: Device 'vmnet-macos' could not be initialized`

**Configuration**
* UTM Version:  2.2.4
* OS Version: 11.6
* Intel or Apple Silicon?  Apple Silicon M1

**Comment by sunhao1256** [comment]
same problem

**Comment by conath** [comment]
How did you install UTM?

**Comment by osy** [comment]
Please answer conath and also if possible attach debug.log as instructed in the issue template.

**Comment by jplee-metaframe** [comment]
Same problem.  Debug log attached.
[debug.log](https://github.com/utmapp/UTM/files/7306720/debug.log)

**Comment by conath** [comment]
Was it working across VM restarts before updating macOS to 11.6?

**Comment by zigang93** [comment]
yeah, fixed on my side too. close this issue

**Comment by monozoro19** [comment]
> Change the network mode to Emulated VLAN

thanks appreciated

**Comment by deepesh616** [comment]
> **Describe the issue** I follow the instruction to install arm based ubuntu.. it show this error after I select the iso to run .. `qemu-aarch64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: Device 'vmnet-macos' could not be initialized`
> 
> **Configuration**
> 
> * UTM Version:  2.2.4
> * OS Version: 11.6
> * Intel or Apple Silicon?  Apple Silicon M1

same problem in kali aslo 
![Screenshot 2022-04-27 at 4 10 10 PM](https://user-images.githubusercontent.com/77091048/165500745-b9810670-5024-425d-98a8-bd17572a4484.png)

**Comment by deepesh616** [comment]
kidly check the issue

**Comment by osy** [comment]
@deepesh616 can you provide your UTM version and macOS version?
