### ISSUE TITLE
No input should go to the VM when not captured

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [utmapp/UTM#3149]
Today some input goes to the VM even if input isn't captured while other input doesn't. This causes an inconsistency behaviour. I would expect no input to go to the VM when not captured.

**Comment by osy** [comment]
That isn’t the intended behaviour because you are able to interact with the VM just by making it the key window. Capture allows you to use system keys and mouse when an absolute input device isn’t supported.

**Comment by Jaiganeshkumaran** [comment]
@osy I understand however currently it seems the behavior is inconsistent. For example, Ctrl+Tab isn't working when mouse isn't captured even though it's not a system/app shortcut.
