### ISSUE TITLE
It’s question more than an issue

### ISSUE THREAD

**Issue by diabycool** [utmapp/UTM#316]
I have installed UTM ..after alot of memory crashing issues i have managed to install windows xp sp 2 x64 pro on my ipad air
Now i am asking about the possibility of using a gaming wireless mouse on the windows system itself directly ..or i can pair it with the ios system and use it through the app ? Because i dont have wirless mouse so i buy a one soonif that was possible
Sorry for inconvenience because iam a new member here

**Comment by itselijahciali** [comment]
The Discord server is the place to ask questions, not GitHub issues. Here's a link to join: https://discord.gg/tRzKfXC

**Comment by jankais3r** [comment]
Yes, you can use a wireless mouse within UTM VM.
