### ISSUE TITLE
Access physical USB disk ?

### ISSUE THREAD

**Issue by hannesa2** [utmapp/UTM#3169]
I want t use a external USB hard drive in Ubuntu guest and I found no option in `Settings->Drives`

How to access physical USB hard disk in Ubuntu guest ?

**Comment by BluDood** [comment]
You can't do this at the moment, but external drive support is in development

**Comment by hannesa2** [comment]
> You can't do this at the moment, but external drive support is in development

@BluDood any news here ?

**Comment by hannesa2** [comment]
I found it, but now it hangs on start (again) 🥲
<img width="855" alt="image" src="https://user-images.githubusercontent.com/3314607/206168371-47ded2e9-e565-46e7-bce1-704fcf15ad5b.png">

**Comment by ktprograms** [comment]
Is there anything installed on the VM's main (internal) drive?

**Comment by anijatsu** [comment]
@hannesa2 If you have found a resource or a guide that you have tried to follow there, then could you link it as well?
