### ISSUE TITLE
Kernel panic - not syncing: No working init found

### ISSUE THREAD

**Issue by obbcth** [utmapp/UTM#317]
**Describe the bug**
![1E3D6C6F-BAAD-4793-B5E1-3D39D7986B00](https://user-images.githubusercontent.com/12216587/81101843-a9a88680-8f49-11ea-8dbb-9acef9a87d1c.jpeg)

**To Reproduce**
1. Download ubuntu server 20.04 LTS
2. Create VM
3. Run

**Comment by osy86** [comment]
Not enough host memory.

**Comment by nnuk** [comment]
I have the same issue and increasing memory or cores is not solving it.
