### ISSUE TITLE
would it be faster to run an ARM image instead of an x86 image?

### ISSUE THREAD

**Issue by icanotc** [utmapp/UTM#318]
so currently qemu is "emulating" the system for x86, which is normal since ios devices are ARM-based, but it will need software to emulate the hardware, which makes it run much slower. but would it be "virtualized" when I use an ARM image? on Linux, you can use KVM to virtualize the system, how about on ios?

**Comment by osy86** [comment]
There’s no KVM or virtualization hardware on iOS.

**Comment by icanotc** [comment]
but still, would it be faster to emulate ARM on ARM?

**Comment by osy86** [comment]
No
