### ISSUE TITLE
Ubuntu install doesn't continue after installer reboots

### ISSUE THREAD

**Issue by btosello** [utmapp/UTM#3182]
After finishing the intalation of the ubuntu image I restart the Machine and now it get stuck (see image)

![image](https://user-images.githubusercontent.com/31852874/137530380-cd44808c-50e2-4113-b796-5687c0cced2a.png)

**Configuration**
* UTM Version: Version 2.1.2 (31)
* OS Version:  M1 Big sur
* Intel or Apple Silicon? Apple

**Comment by conath** [comment]
This is how it looks on my Mac when Ubuntu starts up normally. Doesn't look like a UTM issue.

Which version fo Ubuntu are you trying to use?
