### ISSUE TITLE
macOS Intel

### ISSUE THREAD

**Issue by snslpa** [utmapp/UTM#319]
More options to intall modern macOS 

Like VMware.

Maybe this project can be integrated:

https://github.com/kholia/OSX-KVM

**Comment by jankais3r** [comment]
Can't use KVM on current Apple hardware.

**Comment by vishy-dev** [comment]
This could be part of the MacOS version, but not the mobile one. Or am I wrong?

**Comment by osy86** [comment]
That could be possible but macOS version is very low priority right now
