### ISSUE TITLE
Memory allocation

### ISSUE THREAD

**Issue by RawTechnique** [utmapp/UTM#320]
Is it possible to assign the full or close to the full 6GB of ram the iPad Pro has (2018 1TB model and all 2020 models)?

**Comment by ThatsNiceGuy** [comment]
No, thanks to Jetsam. Also, due to the way JIT is implemented iirc, ios will think UTM is using double the RAM it is actually using

**Comment by RawTechnique** [comment]
Dang just found that, should have done a more in-depth look at the prior issues posted (I only searched for the term RAM, and not memory). Even still with that double memory amount taken into account, and the 80% limit, for some reason I am still capped to a a max of ~512MB of ram on my iPad Pro 2020 which is weird af.

**Comment by jankais3r** [comment]
I regularly use 1GB on my VMs without an issue, same iPad as you.

**Comment by RawTechnique** [comment]
Weird, if you don't mind me asking what's the max you can go up to (for some reason I'm capped at under 512MB)?

I'm going to try clearing cache and rebuilding, and if that doesn't work ill debug some stuff and post logs.
