### ISSUE TITLE
Ubuntu 20.04 Server for Arm64 stuck on boot

### ISSUE THREAD

**Issue by DragonDev07** [utmapp/UTM#3203]
**Describe the issue**
I am just booting Ubutnu 20.04 Server(ARM64) from ISO so that I can install it. It goes to Grub, and I am able to select "Install Ubuntu Server", but then it just goes to a black screen with the UTM logo on it, and nothing happens. I am not sure what the issue is whatsoever, and have even tried booting through the boot options.
<img width="901" alt="Screen Shot 2021-10-24 at 7 21 24 PM" src="https://user-images.githubusercontent.com/76081718/138622783-aadacb04-aed0-4711-b6fb-1c8f41c7ca10.png">

**Configuration**
* UTM Version: 2.3.1(Latest)
* OS Version: macOS Big Sur
* Intel or Apple Silicon? m1 MacBook Air

**Crash log**
None

**Debug log**
`Running:  -L /Applications/UTM.app/Contents/Resources/qemu -S -qmp tcp:127.0.0.1:4002,server,nowait -nodefaults -vga none -spice "unix=on,addr=/Users/andrewwelton/Library/Group Containers/WDNLXAD4W8.com.utmapp.UTM/C73AAB34-AFB5-46BC-8026-5F4837B08DBB.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=on" -device virtio-ramfb-gl -cpu cortex-a72 -smp cpus=8,sockets=1,cores=8,threads=1 -machine virt,highmem=off -accel hvf -accel tcg,tb-size=128 -drive if=pflash,format=raw,unit=0,file=/Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd,readonly=on -drive "if=pflash,format=raw,unit=1,file=/Users/andrewwelton/Library/Containers/com.utmapp.UTM/Data/Documents/Ubutnu Arm64.utm/Images/efi_vars.fd" -boot menu=on -m 512 -device intel-hda -device hda-duplex -name "Ubutnu Arm64" -device qemu-xhci,id=usb-bus -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device ich9-usb-ehci1,id=usb-controller-0 -device ich9-usb-uhci1,masterbus=usb-controller-0.0,firstport=0,multifunction=on -device ich9-usb-uhci2,masterbus=usb-controller-0.0,firstport=2,multifunction=on -device ich9-usb-uhci3,masterbus=usb-controller-0.0,firstport=4,multifunction=on -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 -device nvme,drive=drive0,serial=drive0,bootindex=0 -drive "if=none,media=disk,id=drive0,file=/Users/andrewwelton/Library/Containers/com.utmapp.UTM/Data/Documents/Ubutnu Arm64.utm/Images/disk-0.qcow2,cache=writethrough" -device usb-storage,drive=drive1,removable=true,bootindex=1 -drive if=none,media=cdrom,id=drive1 -device virtio-net-pci,mac=36:34:D2:8F:1A:7B,netdev=net0 -netdev vmnet-macos,mode=shared,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid C73AAB34-AFB5-46BC-8026-5F4837B08DBB -rtc base=localtime
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: Started vmnet interface with configuration:
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: MTU:              1500
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: Max packet size:  1514
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: MAC:              a2:97:c3:86:06:fe
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: DHCP IPv4 start:  192.168.64.1
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: DHCP IPv4 end:    192.168.64.254
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: IPv4 subnet mask: 255.255.255.0
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: UUID:             C9F15A10-0CCE-445D-9B0E-BB8C29EEAC19
qemu-aarch64-softmmu: warning: Spice: playback:0 (0x13c0d4920): setsockopt failed, Operation not supported on socket
qemu-aarch64-softmmu: warning: Spice: record:0 (0x13c0d49d0): setsockopt failed, Operation not supported on socket`

**Upload VM**
[https://drive.google.com/file/d/1eaYeVqIGb87KppiGMh5hIdjrjyeonylj/view?usp=sharing](url)

**Comment by SebDanielsson** [comment]
Same error on M1 MacBook Air on UTM 3.1 and macOS Monterey.

**Comment by boywijnmaalen** [comment]
I have the same issue, however in my case there are 3 differences;

- running UTM 3.0.4
- the startup prntscrn shown above in my case shows valid start-up text (so no errors)
- the issue really only starts once I install docker inside the Ubuntu VM

Ubuntu install script: 

(which basically is a copy of what is shown in the docker docs)

```
sudo apt-get update
sudo apt-get install -y ca-certificates curl gnupg lsb-release
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose
```

**Comment by boywijnmaalen** [comment]
@DragonDev07 why did you close this issue? did managed to find a solution?

**Comment by jyssy** [comment]
I am getting stuck on the reboot screen, after loading NEW ubuntu ARM server on MAC M1 - just sits there with blinking cursor

**Comment by tegola** [comment]
Getting the same issue on reboot, after installing Ubuntu Server ARM 22.04 on a MacBook Pro with M1 Pro. It only shows the blinking cursor.

**Comment by mwcoleman** [comment]
Was this resolved? I am having the same issue as @tegola. Default options using the Ubuntu Server ARM 22.04 image on a MacBook Pro M1.

debug.log shows the following (last entry was before the install completed, no further update since the install triggered the soft reboot):

```
Running:  -L /Applications/UTM.app/Contents/Resources/qemu -S -qmp tcp:127.0.0.1:4000,server,nowait -nodefaults -vga none -spice "unix=on,addr=/Users/mattc/Library/Group Containers/WDNLXAD4W8.com.utmapp.UTM/3A684989-0675-40F1-8A93-37F39BE4A009.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off" -device virtio-ramfb -cpu host -smp cpus=4,sockets=1,cores=4,threads=1 -machine virt, -accel hvf -accel tcg,tb-size=1024 -drive if=pflash,format=raw,unit=0,file=/Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd,readonly=on -drive if=pflash,unit=1,file=/Users/mattc/Library/Containers/com.utmapp.UTM/Data/Documents/Linux.utm/Images/efi_vars.fd -boot menu=on -m 4096 -device intel-hda -device hda-duplex -name Linux -device nec-usb-xhci,id=usb-bus -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device qemu-xhci,id=usb-controller-0 -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 -device usb-storage,drive=cdrom0,removable=true,bootindex=0,bus=usb-bus.0 -drive if=none,media=cdrom,id=cdrom0 -device virtio-blk-pci,drive=drive0,bootindex=1 -drive if=none,media=disk,id=drive0,file=/Users/mattc/Library/Containers/com.utmapp.UTM/Data/Documents/Linux.utm/Images/data.qcow2,discard=unmap,detect-zeroes=unmap -device virtio-net-pci,mac=FA:F9:7F:93:7C:7F,netdev=net0 -netdev vmnet-shared,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -device virtserialport,chardev=charchannel1,id=channel1,name=org.spice-space.webdav.0 -chardev spiceport,name=org.spice-space.webdav.0,id=charchannel1 -uuid 3A684989-0675-40F1-8A93-37F39BE4A009 -device virtio-rng-pci
qemu-aarch64-softmmu: warning: Spice: playback:0 (0x11f063140): setsockopt failed, Operation not supported on socket
qemu-aarch64-softmmu: warning: Spice: record:0 (0x11f0631e0): setsockopt failed, Operation not supported on socket

```

**Comment by jpearl-003** [comment]
Having a similar issue to the original posting. Already have Ubuntu installed, however my recent attempts to boot the VM have be failing. I am able to GRUB screen where I can start Ubuntu, but I get stuck with a screen telling me "exiting boot services".

![Screen Shot 2023-02-08 at 8 36 33 PM](https://user-images.githubusercontent.com/110782491/217693838-5de80c56-ba50-4c36-b5a4-9506fb59928e.png)


UTM Version: 3.2.4
macOS Version: Monterey 12.5.1
M1 chip

Debug Log:
[debug.log.zip](https://github.com/utmapp/UTM/files/10691724/debug.log.zip)

Config:
[config.plist.zip](https://github.com/utmapp/UTM/files/10691732/config.plist.zip)
