### ISSUE TITLE
How to keep the app up to date, and what is the newest version of Android supported?

### ISSUE THREAD

**Issue by thecomputermaster** [utmapp/UTM#321]
Hi, so I am wondering, is there a way to be notified when the app is updated? What is the newest version of Android currently supported? Thanks very much.

**Comment by jankais3r** [comment]
Please don't use GitHub Issues to ask questions, Issues are for tracking bugs and feature requests.

You can Watch this repo and you will receive an email every time there is a new release. I haven't seen working any android above 4.3.

**Comment by thecomputermaster** [comment]
Ok, thx.

**Comment by osy86** [comment]
Or become Riley’s Patreon and use altstore beta which supports updates. https://getutm.app/install/
