### ISSUE TITLE
UTM VM freezes randomly

### ISSUE THREAD

**Issue by jSxgit** [utmapp/UTM#3222]
the VM freezes randomly, and I have to close UTM & open it again. if I try to restart the VM, UTM terminates. 

Configuration (required)
UTM Version: 2.3.1
OS Version: 14.7.1
Device Model: iPhone 11
Is it jailbroken: No
How did you install UTM?: Sideloadly

[debug.log](https://github.com/utmapp/UTM/files/7444799/debug.log)

[config.zip](https://github.com/utmapp/UTM/files/7444828/config.zip)
(config.plist)

[freeze.zip](https://github.com/utmapp/UTM/files/7444840/freeze.zip)
(video showing it freezing)

**Comment by osy** [comment]
Duplicate of #301
