### ISSUE TITLE
Add more keyboard buttons to accessory view

### ISSUE THREAD

**Issue by osy86** [utmapp/UTM#323]
From #294 it seems like a Page Down button would be good. There should be other buttons as well.

**Comment by siuying** [comment]
Esc key would be a great help, since there is no Esc key on iPad keyboard

**Comment by osy86** [comment]
There is already the esc key in the key strip. It uses the Mac’s symbol for esc

**Comment by saagarjha** [comment]
(⎋)

**Comment by obbcth** [comment]
How about add option change symbols to texts? (like ⌘ to command)
