### ISSUE TITLE
Cannot change VM icon anymore

### ISSUE THREAD

**Issue by SDolha** [utmapp/UTM#3231]
I don't know if this is macOS Monterey related, or a regression in the newer versions of UTM, but when I click on Operating System or Custom in Icon/Style section under Edit for a VM, it won't open the icon selection/image file selection dialog (anymore).

Same behavior when creating a new VM.

Configuration:
UTM Version: 2.4.0 (39)
OS Version: macOS Monterey 12.0.1
Intel or Apple Silicon? Apple Silicon - M1 MacBook Air

**Comment by osy** [comment]
Does it work for a new vm?

**Comment by SDolha** [comment]
Unfortunately not, same behavior (I also updated the issue text).

**Comment by osy** [comment]
Any idea when the last version when it worked for you? I just re-tested on Intel macOS 12.0.1 and it does work fine here.

**Comment by SDolha** [comment]
Hmm. Two updates ago (Mac App Store) it did work well. Since then I updated macOS then also UTM. Not a big issue, all my VMs are already "iconed" but wondered if it's a general/known issue.

I will poat a video tomorrow when I have time/test by uninstalling-reinstalling the app (with all VMs backed up) and report findings.

**Comment by SDolha** [comment]
This is what (doesn't) happens:
https://1drv.ms/v/s!Ak6rxQgjgCFBhI9d08MiP3TMfpnjTg

Note: selecting the file for a drive's image, for example, does work from the Browse buttons...

**Comment by SDolha** [comment]
Ah, never mind. I see just now that the window has probably became smaller for some reason and is scrollable, so the icon is actually down there, and I can click it to change it. (Oh my, so ashamed.)
