### ISSUE TITLE
Windows 7 Does Not Boot

### ISSUE THREAD

**Issue by DJZSwag** [utmapp/UTM#3233]
**Describe the issue**
I was going to use parallels for win7 until I found out that it only does ARM64 emulation. So then I used UTM, hoping it would work, but once I pressed start, this came up: qemu-x86_64-softmmu: -netdev vmnet-macos, mode=shared, id=net0: Device 'vmnet-macos' could not be initialized. 

**Configuration**
* UTM Version: 2.4.0 (39)
* OS Version: macOS Monterey 12.1 Beta (21C5021h)
* Intel or Apple Silicon? Apple Silicon with 16 GB

**Crash log**
No App Crashes.

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/7451126/debug.log)

**Upload VM**
I forgot my Google password :(

Edit: Got an image of the error window, thanks Parelells Toolbox
![Screen Shot 2021-11-01 at 1 23 02 PM](https://user-images.githubusercontent.com/87071118/139657756-33c725bc-ad6d-44b4-8713-1cc29433a6f3.png)

**Comment by conath** [comment]
How did you install UTM on your Mac? I got this error recently when I had my code signing settings wrong in Xcode.

**Comment by DJZSwag** [comment]
Through the website,

**Comment by conath** [comment]
As an immediate workaround you can click the options button for the VM, then click Network tab and change the mode to emulated VLAN.

**Comment by DJZSwag** [comment]
It worked! Thanks!

**Comment by yll373-4-real-true** [comment]
I have a similar problem but know it is not the architecture 

![Image](https://github.com/user-attachments/assets/763b12d2-b26d-49d1-b864-39011c206cb9)
