### ISSUE TITLE
SPICE Not Working

### ISSUE THREAD

**Issue by DJZSwag** [utmapp/UTM#3237]
**Describe the issue**
SPICE is not working in Windows 7. I restarted the vm, went to control panel, and it didn't give me any option to change the  resolution. Please help, so I can achieve the perfect Windows 7 vm.

**Configuration**
* UTM Version: 2.4.0 (39)
* OS Version: macOS Monterey 12.1 Beta (21C5021h)
* Intel or Apple Silicon? Apple Silicon with 16 GB

**Crash log**
No App crashes.
**Debug log**
Nothing wrong with emulation or qemu.

**Upload VM**
Just like last time, I forgot my Google password.

**Comment by conath** [comment]
The VM resolution should change as you resize the UTM VM window. Changing the resolution from within the guest works without SPICe tools installed, as long as you installed the proper guest drivers. For Windows 7 I recommend you choose the `qxl-vga` card in the Display configuration and then install the QXL driver in the VM, it is contained in the [virtio ISO](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.208-1/virtio-win-0.1.208.iso).
