### ISSUE TITLE
Host VPN Connection doesn't reach the Guest

### ISSUE THREAD

**Issue by goncalolalmeida** [utmapp/UTM#3238]
**Configuration**
* UTM Version: 2.3.1 (38)
* OS Version: macOS Big Sur 11.6.1
* Intel or Apple Silicon? Apple Silicon

[config.plist.zip](https://github.com/utmapp/UTM/files/7456018/config.plist.zip)

I'm using Kali Linux arm version on UTM (kali 5.14 arm64, installed Kali's 2021.3 version) and I have no internet connection when using a VPN on the host.
My Network configuration on UTM is `Shared` (I doubt Bridged would solve it) and Emulated Network Card is `virtio-net-pci`, I'm not sure if it's a a misconfiguration, a bug or something else... but since I can't install Mobile Access Portal natively on Kali (no arm64 version) I really need my host's VPN connection to get to the guest inside UTM.

Looking for some help here, since I didn't find a related issue.
Many thanks in advance!

**Comment by conath** [comment]
Have you tried the emulated VLAN network mode? If any, that one would definitely go through the VPN since it's emulated in userspace. The other modes use macOS Virtualization features that might not respect the host's VPN settings.

**Comment by goncalolalmeida** [comment]
It works @conath ! Thank you so much!!

**Comment by voa257** [comment]
Hi!

Facing a similar issue, but with the following configuration:
   
    - UTM Version: 3.0.4
    - OS Version: macOS Monterey 12.1 (on Apple Silicon)

I'm emulating a Windows 11 Insider Preview Client (ARM64) (build 22523) with SPICE Guest Tools (0.164.3) correctly installed. When the Network configuration on UTM is Shared (Emulated Network Card: virtio-net-pci), the internet connection works fine on the emulated Windows.

However, I would like the host's VPN connection to get the guest. I tried to get it working both with Shared and Emulated VLAN network modes of UTM, but I didn't make it... Moreover, if I switch to the VLAN option, I have no internet connection on the guest.

Is there any specific network configuration that I should try given the Windows version?

Any help would be appreciated.
Thanks!

**Comment by conath** [comment]
@voa257 You should use emulated VLAN mode as suggested above. You might need to set manual DNS server in the VM to make it work.

**Comment by spyrospapp** [comment]
> Have you tried the emulated VLAN network mode? If any, that one would definitely go through the VPN since it's emulated in userspace. The other modes use macOS Virtualization features that might not respect the host's VPN settings.

I spent a whole day because of this I finally found the solution you are the best

**Comment by vimlohulmu** [comment]
I'm having the same issue with a MacOS guest. How do I enable VLAN mode?

**Comment by conath** [comment]
@vimlohulmu It‘s in the VM configuration, Network tab.

**Comment by vimlohulmu** [comment]
@conath It's only showing None, Shared and Bridged there
![Screen Shot 2022-01-26 at 7 27 28 PM](https://user-images.githubusercontent.com/98487242/151269357-356c6e5d-4582-47c4-a4e2-6e563f36b711.png)
.

**Comment by conath** [comment]
@vimlohulmu My bad, the emulated VLAN mode is only available for QEMU backend, not for Apple VMs.

**Comment by vimlohulmu** [comment]
@conath So is there a solution for me?

**Comment by conath** [comment]
@vimlohulmu I believe no. You could instead try to connect to the VPN from within the VM if that is possible for your use case.

**Comment by vimlohulmu** [comment]
@conath Unfortunately I'm out of connections. So I guess there's no workaround and I'll have to wait for a future update which may or may not include a possible solution?

**Comment by spyrospapp** [comment]
Hi there! I have set my hard drive in UTM to have around 60 GB available of Mac's storage can I give more GB to it?
![Screenshot 2022-01-27 at 21 33 26 Small](https://user-images.githubusercontent.com/98436516/151431438-76dfdf8d-9955-4b5f-be39-774671fc280e.jpeg)

**Comment by conath** [comment]
@spyrospapp See this other discussion: https://github.com/utmapp/UTM/issues/2636#issuecomment-1013598127

**Comment by bradyap** [comment]
I'm having a similar issue. I'm on macOS (apple silicon) running a debian vm in UTM. I am connected to a socks5 proxy on my host machine, however vm traffic doesn't seem to be going through it even while using emulated VLAN mode.

**Comment by dylan-gluck** [comment]
Running into a similar issue Mac (Intel) host & Debian guest. 
- Working network connection on guest with `Shared` interface & no vpn running on host
- No ping on guest with `Shared` interface and vpn connected
- No ping on guest with `emulated VLAN` and vpn connected

Also, I noticed that none of the other network interfaces are working even without the vpn running on host
- No ping on guest with `emulate VLAN` and no vpn connection on host
- No ping on guest with `Bridged` and no vpn connection on host

**Comment by conath** [comment]
@dylan-gluck Don‘t use `ping` to check internet connectivity in UTM VMs, it‘s not supported (at least in emulated VLAN mode, see #530) 

Instead perform a DNS lookup like `dig @1.1.1.1 DuckDuckGo.com`. If it times out, no connection. Otherwise you’re connected.

**Comment by Moulick** [comment]
@bradyap did you ever find a solution?

**Comment by Flood1993** [comment]
I switched to VLAN network mode and now the VPN from the host seems to be used in the guest machine. However, I'm facing a weird issue: `ping google.com` is not working, even though I can access the site on a browser and also my behind-VPN settings services (ping also broken for them). 🤔

**Comment by patryk4815** [comment]
@ghost @conath 
Here workaround for apple.virtualization: 

1. dump current rules using:
```console
sudo pfctl -a com.apple.internet-sharing/shared_v4 -s nat 2>/dev/null > newrules.conf
```
(it should look like this:)
```console
$ cat newrules.conf
nat on en0 inet from 192.168.64.0/24 to any -> (en0:0) extfilter ei
no nat on bridge100 inet from 192.168.64.1 to 192.168.64.0/24
```

2.  Add your vpn interface (for me it is utun5, check in `ifconfig`) and vpn CIDR
```console
echo "nat on utun5 inet from 192.168.64.0/24 to 10.0.0.0/8 -> (utun5) extfilter ei" >> newrules.conf
```

3. Reload pfctl rules
```console
sudo pfctl -a com.apple.internet-sharing/shared_v4 -N -f newrules.conf 2>/dev/null
```

ref: https://communities.vmware.com/t5/VMware-Fusion-Discussions/Share-host-VPN-with-guest/m-p/2810095/highlight/true#M170151

**Comment by trenshaw** [comment]
Could support for a new 'NAT' option vs. 'Emulated VLAN' be added? This would function similar to how the 'NAT' option in VMware and VirtualBox work i.e. provide NAT between any of the networks visible to the host e.g. WiFi, LAN, VPN etc.

I need both my guest and local apps on my macOS host to be able to connect to hosts over the same Pritunl VPN connection. This would significantly simplify networking for those wishing to be able to route between all available networks on the host.

**Comment by MeiAnd** [comment]
I solved this issue like this: 

Network: Bridge 

nano /etc/resolv.conf
nameserver 8.8.8.8

**Comment by Tropical-Smootie** [comment]
should i set up port fowarding?

**Comment by 0xElmalky** [comment]
I changed it to bridged with en0 and it works now !

**Comment by zdeneksvarc** [comment]
> @dylan-gluck Don‘t use `ping` to check internet connectivity in UTM VMs, it‘s not supported (at least in emulated VLAN mode, see #530)
> 
> Instead perform a DNS lookup like `dig @1.1.1.1 DuckDuckGo.com`. If it times out, no connection. Otherwise you’re connected.

Using `fping` is always better. And of course works in this case.

**Comment by HarishChalki** [comment]
1. Change it to bridged
2. In services.msc check for the following services, they should be enabled and running 
   i) DNS Client
  ii) Function Discovery Resource Publication
  iii) SSDP Discovery
  iv) UPnP Device Host
3. Then in some cases you may have to disable/Off the windows firewall also

**Comment by aleksis-lv** [comment]
> @ghost @conath Here workaround for apple.virtualization:
> 
> 1. dump current rules using:
> 
> ```
> sudo pfctl -a com.apple.internet-sharing/shared_v4 -s nat 2>/dev/null > newrules.conf
> ```
> 
> (it should look like this:)
> 
> ```
> $ cat newrules.conf
> nat on en0 inet from 192.168.64.0/24 to any -> (en0:0) extfilter ei
> no nat on bridge100 inet from 192.168.64.1 to 192.168.64.0/24
> ```
> 
>  2. Add your vpn interface (for me it is utun5, check in `ifconfig`) and vpn CIDR
> 
> ```
> echo "nat on utun5 inet from 192.168.64.0/24 to 10.0.0.0/8 -> (utun5) extfilter ei" >> newrules.conf
> ```
> 
>  3. Reload pfctl rules
> 
> ```
> sudo pfctl -a com.apple.internet-sharing/shared_v4 -N -f newrules.conf 2>/dev/null
> ```
> 
> ref: https://communities.vmware.com/t5/VMware-Fusion-Discussions/Share-host-VPN-with-guest/m-p/2810095/highlight/true#M170151

Do you happen to know if there is an updated set of instructions for Mac OS Sonoma onwards? It seems that they changed something to do with pfctl and dumping it no longer works, neither does applying the new file.

Thanks :-)

**Comment by aleksis-lv** [comment]
hey, unsure if anyone is still having this issue, the solution by @patryk4815 didn't end up working for me, but the following did after a few minutes with ai:

```
nat on en0 inet from 192.168.64.0/24 to any -> (en0) extfilter ei
no nat on bridge100 inet from 192.168.64.1 to 192.168.64.0/24
nat on utun6 inet from 192.168.64.0/24 to any -> (utun6) round-robin extfilter ei
# i think these aren't necessary, but were recommended to avoid local requests going through the vpn
no nat on utun6 inet from 192.168.64.0/24 to 192.168.0.0/16
no nat on utun6 inet from 192.168.64.0/24 to 10.0.0.0/8
no nat on utun6 inet from 192.168.64.0/24 to 172.16.0.0/12
```

utun6 being the vpn tunnel, and i'm using a script to run on startup to persist these settings :-)
hope this helps!

**Comment by jgfoster** [comment]
@patryk4815, your solution worked for me. Thanks so much!

**Comment by ersinakinci** [comment]
@patryk4815's solution got me part of the way there.

I have "shared" networking selected for my VM with macOS as host. Here's what I added to `/etc/pf.conf`:

```
nat on utun6 from 192.168.65.0/24 to any -> (utun6)
pass in on bridge100 inet from 192.168.65.0/24 to any keep state
pass out on utun6 inet from 192.168.65.0/24 to any keep state
```

Then I run `sudo pfctl -F all -f /etc/pf.conf` on the host to flush the packet filter and load the rules.

Every explanation on the internet that I found failed to state that there are three essential pieces of information:

- Which interface your VPN is using
- Which interface your VM is using
- The CIDR for your VM's network

In my case, the VPN's interface is `utun6`, the VM's interface is `bridge100`, and the VM's IP block/CIDR is `192.168.65.0/24`--that is, `192.168.65.0` through `192.168.65.255`.

I figured all of these out by using `netstat -rn -f inet` on my host before and after turning on the VPN, as well as before and after booting my VM. Observe the differences in the list, especially the `Destination` and `Netif` columns, and you'll see which interfaces and IP addresses are associated with the VPN and the VM.

You can derive the CIDR with a little bit of pattern matching from the IP addresses associated with your VM--`/24` means "all possible 256 addresses in the last octet." I recommend looking up CIDR rules and using a CIDR calculator.

Contrary to many explanations out there, I didn't find that UTM assigned a default block of addresses that started with `10...` I also didn't find any way to determine which addresses would be assigned by UTM. The only way that I could figure out is to just observe which IP addresses are connected to your machine before and after starting your VM.

One last bit. If you're using TLS/HTTPS in your guest VM, you'll need to set the MTU to be somewhat smaller than the MTU of your VPN's interface. Otherwise, you'll get random dropped packets in the guest.

My VPN's interface is `utun6`, so I ran `ifconfig utun6 | grep mtu` on my host, which listed my MTU as 1320. So I set my MTU in my guest (Debian Linux) to 1200 by running `sudo ip link set dev enp0s1 mtu 1200`.

When my VPN reconnects, I have to do a little dance where I re-flush the packet filter on the host (`sudo pfctl -F all -f /etc/pf.conf`) and sometimes I need to disconnect/reconnect on the guest. Other than that, everything works great.

**Comment by aleksis-lv** [comment]
@ersinakinci god bless 😭 i think that a solution should be standardised for this because it’s very common for people to use a vpn, perhaps added to the wiki or built in? :)

**Comment by lucaslpsan** [comment]
@ersinakinci Thanks so much for your time!

**Comment by s4t0shi-n4k4m0t0** [comment]
@ersinakinci 's solution really should be put in the FAQ – I strongly gues it is a very commonly encountered issue.
