### ISSUE TITLE
win 11 and settings app

### ISSUE THREAD

**Issue by mjonsson1986** [utmapp/UTM#3243]
looks like  utm have same issue with win 11 as parallels have. after a while you cant open settings app..
**Describe the issue**
easy. use win 11 in utm for some days. after a while try to open settings app
you cant!

**Comment by conath** [comment]
Hi, this Issues section is for UTM technical problems. This seems like a Windows problem to me. 

As you write "use win 11 in utm for some days", has something changed in those days (e. g. different WiFi network)?

**Comment by mjonsson1986** [comment]
no Skickades från E-post för Windows Från: CONATHSkickat: den 3 november 2021 20:55Till: utmapp/UTMKopia: mjonsson1986; AuthorÄmne: Re: [utmapp/UTM] win 11 and settings app (Issue #3243) Hi, this Issues section is for UTM technical problems. This seems like a Windows problem to me.As you write "use win 11 in utm for some days", has something changed in those days (e. g. different WiFi network)?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by conath** [comment]
Alright, please let us know if you discover any additional information that might point to a solution. For the meantime I will close this issue since we don't have enough information to start troubleshooting or debugging this.
