### ISSUE TITLE
Ability to add more than one network card

### ISSUE THREAD

**Issue by JuniorJPDJ** [utmapp/UTM#3248]
Hello!
I just tried to migrate from VirtualBox and I spotted a problem.
My usecase needs more than one network card attached to VM, but I found no way of doing it.
It's probably possible using qemu arguments, but it's a workaround.

**Comment by conath** [comment]
Duplicate of #2722 

As you pointed out correctly, it is already possible to add multiple NICs via the "QEMU" tab - but not in the Network tab UI.
