### ISSUE TITLE
Don't default to Skylake-Client CPU on PC VMs

### ISSUE THREAD

**Issue by wdormann** [utmapp/UTM#3249]
**Describe the issue**
If a PC / Q35 VM is created with UTM, the default QEMU selected is Skylake-Client.  The issue with this is:

1. QEMU's default CPU will run just fine on these architectures, without needing to specify a particular CPU such as Skylake-Client.
2. In my brief testing, specifying Skylake-Client as a QEMU CPU on an x86_64 OS will result in a VM that runs up to 50% slower.  I've tested both Linux and Windows VMs.

For these two reasons combined, I have to wonder what the reason is for defaulting to Skylake-Client CPUs is.

**Configuration**
* UTM Version: 2.4.0 (39)
* OS Version: macOS Monterey 12.0.1
* Intel or Apple Silicon?   Apple Silicon M1

[patch.diff.txt](https://github.com/utmapp/UTM/files/7474812/patch.diff.txt)

**Comment by ktprograms** [comment]
Well it was meant to fix [this](https://github.com/utmapp/UTM/issues/2368) issue apparently, but it's interesting that it runs so much slower. I wonder if it's because it's is running using TCG?

**Comment by conath** [comment]
Interesting. I tested that fix on a 2-core Intel MacBook Air, so I may have missed a performance impact - the Air is just slow generally. It'd like to believe it is still faster than TCG, but I will have to test that with a stopwatch to make sure.

**Comment by wdormann** [comment]
I'm not so sure about the underlying reason, but I had poked around with a naive benchmark of "how long does it take to power on a VM until it completes an acid3 test in Chrome", with some notes around this thread:
https://twitter.com/wdormann/status/1456023659655667715
With further confirmation here:
https://twitter.com/astr0baby/status/1456045796550402057

**Comment by ktprograms** [comment]
@conath I have no doubt it's faster than TCG on an Intel Mac. I just think it might be some special features in the `Skylake-Client` CPU that slows it down with M1 Macs (and TCG) compared to the QEMU default CPU.

**Comment by osy** [comment]
That’s interesting, and I too would be curious to know why.

**Comment by hawwky** [comment]
> I'm not so sure about the underlying reason, but I had poked around with a naive benchmark of "how long does it take to power on a VM until it completes an acid3 test in Chrome", with some notes around this thread:
> https://twitter.com/wdormann/status/1456023659655667715
> With further confirmation here:
> https://twitter.com/astr0baby/status/1456045796550402057



> That’s interesting, and I too would be curious to know why.

maybe because running with skylake-client on intel mac is easier since the physical arch is the same. just like the software x86 emulation is horrible when you don't have an physical translation chip (like the new macs have)
