### ISSUE TITLE
Rebooting Windows 11 Guest during Windows Update crashes QEMULauncher

### ISSUE THREAD

**Issue by AwlsomeAlex** [utmapp/UTM#3250]
**Describe the issue**
Rebooting Windows 11 by a Windows Update causes QEMULauncher to crash. VM will not reboot.
Setting it to reboot into Safe Mode also made it crash... seems to be sporadic.
(qemu-aarch64-softmmu: Spice: red-qxl.c:807:spice_qxl_gl_scanout: condition `qxl_state->gl_draw_cookie == GL_DRAW_COOKIE_INVALID' failed)

**Configuration**
* UTM Version: 2.4.0
* OS Version: macOS Monterey 12.0.1
* Intel or Apple Silicon? Apple Silicon

**Crash log**
[crash.log](https://github.com/utmapp/UTM/files/7477152/crash.log)

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/7477158/debug.log)

**Upload VM**
[config.plist.zip](https://github.com/utmapp/UTM/files/7477177/config.plist.zip)

**Comment by conath** [comment]
Please change the Emulated Display Card to `virtio-ramfb`, this will get rid of the crash. The `-gl` cards are not supported for Windows guest OS (yet)
![Open the VM config, Display tab, change Emulated Display Card to virtio-ramfb.](https://user-images.githubusercontent.com/12073163/140544393-d00f0bfa-9144-4272-be59-9b012b969756.jpg)
.

**Comment by dylanmc** [comment]
I think this should be in the UTM Troubleshooting section for Windows 11.
