### ISSUE TITLE
Would be great if we can run utm bundle from anywhere.

### ISSUE THREAD

**Issue by hawwky** [utmapp/UTM#3253]
Hello today I was testing bare qemu and utm. Suprisingly qemu was able to boot some machines off external drives. I wonder why UTM wasn't able to. if import my 16gb vm into utm. i think it copies it to my internal mac ssd. tho running qemu from cli is a pain in ass

Running/ emulating virtual machines on internal ssd (which is un-repairable) would make anyone anxious. is there any workaround for this, meanwhile?

**Comment by conath** [comment]
Hello and thanks for your suggestion. Work is ongoing to add this feature. 

This issue is a duplicate of #132
