### ISSUE TITLE
Add more URL Scheme actions

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#3255]
The following UTM features could reasonably be exposed via the URL scheme:

- [ ] Delete a VM
- [ ] Rename a VM
- [ ] Clone a VM
- [ ] Import a VM from file URL (as opposed to the `downloadVM` action which only works with Web URLs)
- [ ] Quit (possibly with a parameter whether to force quit any running VMs)

**Comment by ktprograms** [comment]
If a URL scheme can return data, an `export QEMU command` url might be helpful.

**Comment by conath** [comment]
To allow bidirectional communication, we would need to implement the [X-Callback-URL](http://x-callback-url.com) specification. I'm not sure if this would be helpful for scripting from the command line. It would definitely work [with Shortcuts](https://support.apple.com/guide/shortcuts-mac/use-x-callback-url-apdcd7f20a6f/mac).

**Comment by conath** [comment]
I've opened #3256 about the X-Callback-URL implementation.

**Comment by adespoton** [comment]
Another feature that could be reasonably exposed is Pause|Snapshot/Resume VM.  You could also expose ejecting/loading removable media from a VM.

**Comment by conath** [comment]
Pause & resume is already implemented, [see the Wiki](https://github.com/utmapp/UTM/wiki/URL-Scheme-%E2%80%93-Automation-for-UTM-app-&-VMs) for the full list.

**Comment by honzajerabek** [comment]
I'm using Monterey m1 virtualization, is there a way (or a workaround) how to clone a VM, or at least import/download from local file system? I understand the QEMU export is off limits

**Comment by conath** [comment]
Closing because we have two scripting options for macOS now: AppleScript and `utmctl`. https://docs.getutm.app/scripting/scripting/
