### ISSUE TITLE
Keyboard not working

### ISSUE THREAD

**Issue by billywws** [utmapp/UTM#329]
I created a standard PC VM on my stock iPhone SE running 13.4.1, but the virtual keyboard does not work no matter what I do. However, the function keys at the top do work. None of the alphanumerical keys work at all.

**Comment by ThatsNiceGuy** [comment]
iPhone SE first gen (A9/2GB RAM) or iPhone SE second gen (A13/3GB RAM)

**Comment by billywws** [comment]
> iPhone SE first gen (A9/2GB RAM) or iPhone SE second gen (A13/3GB RAM)?
> I ask because both can run 13.4.1 and my own iPhone SE first gen has had occasional issues in UTM too.
> Also, what OS, and do you have legacy input mode enabled for the VM?

It's a first gen iPhone SE, and I'm attempting to run MS-DOS to install a Windows 9x OS. I've tried both with and without legacy inputs, too.

**Comment by ThatsNiceGuy** [comment]
Let me try to reproduce on my own SE because its been only sometimes for me that the keyboard doesn't work in MS-DOS 5 to play Planet X3

**Comment by billywws** [comment]
> Let me try to reproduce on my own SE because its been only sometimes for me that the keyboard doesn't work in MS-DOS 5 to play Planet X3

I also tried Windows XP's installer and the same thing occurred. Keyboard just doesn't work at all.

**Comment by Carter1190** [comment]
same here on ios 13.4.1 iphone xr non jailbroken with legacy on and off even tried different english ios keyboards (english canada,english us,english uk and gboard (google keyboard)

**Comment by amir1kkh** [comment]
Same problem here 
Jailbroken iOS 13.4.1 iPhone 7 on the latest release candidate 
Tried on windows xp installer and Slitaz(linux distro) and also windows 95 
Both on legacy on and off

**Comment by ThatsNiceGuy** [comment]
Try [the first release candidate](https://github.com/utmapp/UTM/releases/tag/v1.0-rc1), ive had better luck with it.

**Comment by SinaGamer55** [comment]
> Try [the first release candidate](https://github.com/utmapp/UTM/releases/tag/v1.0-rc1), ive had better luck with it.

I installed v1.0-rc1 version.
Can confirm it works ok and the keyboard is fully functional. rc2 has this bug.
iPad Air - iOS 12.4 - Jailbroken

**Comment by billywws** [comment]
> > Try [the first release candidate](https://github.com/utmapp/UTM/releases/tag/v1.0-rc1), ive had better luck with it.
> 
> I installed v1.0-rc1 version.
> Can confirm it works ok and the keyboard is fully functional. rc2 has this bug.
> iPad Air - iOS 12.4 - Jailbroken

I can confirm that it does indeed work. Not sure what's wrong with the new release, but thanks for the suggestion!

**Comment by ThatsNiceGuy** [comment]
Yep, I just tried RC2 on my iPad Pro 11” 2020 and it broke software keyboard. I don’t know about hardware keyboard since i misplaced my Smart Keyboard

**Comment by ewkoob** [comment]
I am trying to install Ubuntu 20.04 server with this.

I can boot with the Ubuntu install ISO, hit F2 to start install.

First step is to select a language.  I can use arrow keys to navigate, and there is a button to cancel on the keyboard that works.  I cannot use return, or any other keys to select the language and proceed with the install.

**Comment by lexieye** [comment]
> I created a standard PC VM on my stock iPhone SE running 13.4.1, but the virtual keyboard does not work no matter what I do. However, the function keys at the top do work. None of the alphanumerical keys work at all.

Try and add memory?
I had standard 500mg memory and it was unresponsive. I bumped it up to 1000 and it works, 2000 crashes the system (try it around?)

**Comment by Therealsidthecat** [comment]
I have had the same problem, stock iOS, iPhone 11. I added more memory and it didn’t work. Updated to latest version of UTM.
