### ISSUE TITLE
UTM github page "about" should indicate that it's for more than just IOS

### ISSUE THREAD

**Issue by wdormann** [utmapp/UTM#3298]
If you don't dig deeper, you might think that UTM is only for IOS.  The first time I saw it, I moved on looking for the repo for what I was running on the Mac.  The github page for UTM should probably be updated to reflect this
![Screen Shot 2021-11-08 at 1 20 04 PM](https://user-images.githubusercontent.com/14325582/140802647-22ed1687-9826-414c-9e20-d47ea5037526.png)
![Screen Shot 2021-11-08 at 1 22 05 PM](https://user-images.githubusercontent.com/14325582/140802687-ec7bab40-8d47-405b-9499-889b755b3974.png)

.

**Comment by osy** [comment]
Done
