### ISSUE TITLE
build_dependencies error

### ISSUE THREAD

**Issue by applejian** [utmapp/UTM#330]
**Describe the bug**
A clear and concise description of what the bug is. **BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**To Reproduce**
1. clone the project
2. brew install bison pkg-config gettext glib libgpg-error nasm
3. git submodule update --init --recursive
4. run./scripts/build_dependencies.sh
5. build long time
6. at last error

**Debug log**

clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libqemu-system-arm.dylib] Error 1
make: *** [arm-softmmu/all] Error 2
  LINK    aarch64-softmmu/libqemu-system-aarch64.dylib
ld: warning: ignoring file /usr/local/Cellar/libusb/1.0.23/lib/libusb-1.0.dylib, building for iOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/Cellar/nettle/3.4.1/lib/libnettle.dylib, building for iOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/Cellar/gnutls/3.6.11.1/lib/libgnutls.dylib, building for iOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_gnutls_anon_allocate_client_credentials", referenced from:
      _qcrypto_tls_creds_anon_prop_set_loaded in tlscredsanon.o
  "_gnutls_anon_allocate_server_credentials", referenced from:
      _qcrypto_tls_creds_anon_prop_set_loaded in tlscredsanon.o
  "_gnutls_anon_free_client_credentials", referenced from:
      _qcrypto_tls_creds_anon_finalize in tlscredsanon.o

**Comment by osy86** [comment]
Read the note in the readme.

**Comment by obbcth** [comment]
In case of “Easy” method in readme, you should manually add libapps and StaticDataTableViewController in each folder (ConfigurationViews and Views)
https://github.com/libapps/libapps-mirror
https://github.com/peterpaulis/StaticDataTableViewController
