### ISSUE TITLE
Unable to share WIFI dongle via USB

### ISSUE THREAD

**Issue by josephillips85** [utmapp/UTM#3300]
**Describe the issue**
when im trying to share USB WIfi Dongle the guest see the dongle but is unable to initialize it
On logs i got the error `(<unknown>:16457): GSpice-CRITICAL **: 23:25:59.786: usbredirhost: error received interrupt out packet is larger than wMaxPacketSize`

**Configuration**
* UTM Version: 2.3.1
* OS Version: Monterrey 12.0.1
* Intel or Apple Silicon? Intel

Using Kali Linux as Guest .Works well on Virtualbox with the same image.

**Comment by conath** [comment]
Please provide debug log. See the [troubleshooting page](https://github.com/utmapp/UTM/wiki/Troubleshooting-a-VM) for details.

Have you tried enabling "USB 3.0 (XHCI) Support" in the VM Configuration → Sharing?

**Comment by stefgina** [comment]
Hello, I have also tried to use a wifi dongle inside the Kali Linux VM (Kali Linux 2022.1 for ARM). Even though it gets recognized by Kali, it seems like the communication of the USB device (Alfa AWUS036NHA usb wifi adapter) - with the virtual machine gets really really slow. I can turn it into monitor mode too with airmon-ng, but all the commands are getting executed really slow.

I have checked the USB 3.0 tickbox in UTM's sharing. The WiFi adapter is a USB 2.0. The macbook M1 pro (14 inch, 2021) port is a thunderbolt 4 and I am passing it into a USB hub and then into the macbook. In the networking section of UTM, the network mode is "Shared Network", and the emulated network card is "virtio-net-pci".

Is there a faster way I can get the WiFi adapter to communicate with the system (a setting or something) ? Has anyone achieved to make a WiFi dongle work properly with the Kali Linux VM, or with any Linux distro in general? If yes have you manage to make it work properly under monitor mode? 

**Configuration**
* UTM Version: 3.0.4 (46)
* OS Version: macOS Monterey 12.3
* Apple Silicon
* VM is the Kali Linux 2022.1 for ARM
* Apple MacBook Pro 14" (2021) (M1-Pro 10-core/16GB/1TB SSD/Retina Display)

**Comment by Baga81** [comment]
> Hello, I have also tried to use a wifi dongle inside the Kali Linux VM (Kali Linux 2022.1 for ARM). Even though it gets recognized by Kali, it seems like the communication of the USB device (Alfa AWUS036NHA usb wifi adapter) - with the virtual machine gets really really slow. I can turn it into monitor mode too with airmon-ng, but all the commands are getting executed really slow.
> 
> I have checked the USB 3.0 tickbox in UTM's sharing. The WiFi adapter is a USB 2.0. The macbook M1 pro (14 inch, 2021) port is a thunderbolt 4 and I am passing it into a USB hub and then into the macbook. In the networking section of UTM, the network mode is "Shared Network", and the emulated network card is "virtio-net-pci".
> 
> Is there a faster way I can get the WiFi adapter to communicate with the system (a setting or something) ? Has anyone achieved to make a WiFi dongle work properly with the Kali Linux VM, or with any Linux distro in general? If yes have you manage to make it work properly under monitor mode?
> 
> **Configuration**
> 
> * UTM Version: 3.0.4 (46)
> * OS Version: macOS Monterey 12.3
> * Apple Silicon
> * VM is the Kali Linux 2022.1 for ARM
> * Apple MacBook Pro 14" (2021) (M1-Pro 10-core/16GB/1TB SSD/Retina Display)

Hello, I have same issue with macbook pro 14 2021 and tl-wn722n usb dongle, did you find any solution?
Tested on Parallels Desktop 17.1 and it works fine, but I dont want to buy PD only to fix this one :(

**Comment by stefgina** [comment]
Yes I did make it work, with the same network adapter as you. Use this repo to install the drivers https://github.com/stefgina/rtl8188eus  inside the VM ,and then it should work. Follow the steps of the procedure, and you should be fine.

**Comment by josephillips85** [comment]
well the problem still persist with atheros 9k firmware 
i get the error on "unable to reset hardware; reset status -5"
on M2 and UTM 4.1.6

**Comment by josephillips85** [comment]
looks like is a issue with ARM based kernel and atheros 9k solved using a rtl firmware device
