### ISSUE TITLE
Crashes when using VM

### ISSUE THREAD

**Issue by Arya118251** [utmapp/UTM#3302]
**Describe the issue**
It just crashes sometimes while using the VM. Very Annoying!

**Configuration**

Mid 2014 MacBook Pro 13 inch

* UTM Version: latest 
* OS Version: 11.6.0
* Intel or Apple Silicon? Intel

**Comment by phirestalker** [comment]
I also have VMs crash on me, but I only notice this when using the GPU accelerated display drivers. Can you tell me what option you have chosen under display settings for the VM?

Also, macOS always gives me a crash report for these crashes. Can you open the Console app and look in the Crash Reports section for UTM. If you find one or more pick the latest one and paste the whole thing inside of a code or preformatted block, please. I want to see if it is the same error that I am seeing.

Thanks.

**Comment by conath** [comment]
Indeed @Arya118251 we'll need crash log and debug log to investigate this, otherwise we can't find out what is going wrong. Please see the new [troubleshooting page](https://github.com/utmapp/UTM/wiki/Troubleshooting-a-VM) for details.

**Comment by Arya118251** [comment]
@phirestalker @conath  Alright, I will send it if crash happens one more time...

**Comment by conath** [comment]
@Arya118251 the crash log will appear in a new Windows a few seconds after the crash. Just copy the entire test and paste here.

There is a number of known issues & crashes related to the -gl cards, unfortunately.  See #2729, #3060 and #3084

**Comment by Arya118251** [comment]
now its not crashing after updating to the latest version.... thx....
