### ISSUE TITLE
ERROR: could not get https://ftp.pcre.org/pub/pcre/pcre-8.37.tar.bz2

### ISSUE THREAD

**Issue by Alex-Braine** [utmapp/UTM#3308]
Hello,
https://ftp.pcre.org is down, so "./scripts/build_dependencies.sh -p macos -a arm64" breaks off...

**Comment by conath** [comment]
In the mean time, if you are okay with using pre-built dependencies, you can use the `sysroot-macos-arm64` generated by GitHub Actions. https://github.com/utmapp/UTM/actions/runs/1430056582

**Comment by kkk669** [comment]
According to https://pcre.org/:

> Note that the former ftp.pcre.org FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on GitHub instead.

**Comment by kkk669** [comment]
Maybe we need to wait for the next release of glib.

https://github.com/GNOME/glib/commit/e5dc299701df7189685d322cb709649ce3c9c81d#diff-bcf487a428afba1739e08e831ec3906c27fc16a195459d76bccd2083ce0c72f3

**Comment by Alex-Braine** [comment]
https://github.com/GNOME/glib/releases/tag/2.70.2

**Comment by conath** [comment]
I've spent some time yesterday trying to fix the CI by upgrading some or all of the source dependencies. I learned quickly I am in way over my head and it didn't end up working. Maybe the patches need to be updated. See #3380 (update all) and #3381 (update glib)

**Comment by Alex-Braine** [comment]
https://github.com/Alex-Braine/qemu/tree/48310571a6ca7e1a50a3c0ca71923d35f1d8e560/scripts -> https://github.com/Alex-Braine/qemu/actions/runs/1603384020
Changes only in scripts/build_dependencies.sh and patches/sources.
I'll try to solve the python's "six" problem in order to update spice-gtk.
