### ISSUE TITLE
Change VM Icon button is hard to discover and use

### ISSUE THREAD

**Issue by SpeedStepper** [utmapp/UTM#3310]
**The Option to Edit the Icon for a VM Seems to have Disappeared.**
Under 'Information' below the the 'Style' drop down menu, when selecting 'Operating System' there used to be an option to change the icon for the selected VM, that option seems to have disappeared from the UI.**

**Configuration**
* UTM Version: Version 2.4.1 (40)
* OS Version: Monterrey 12.0.1
* Apple Silicon, M1 Mac mini (Also Observed on M1 MacBook Pro with similar config.) 

**Screen Shot**

![Screen Shot 2021-11-06 at 12 58 15 PM](https://user-images.githubusercontent.com/56007286/141502766-4f12ad59-4c58-4cdc-84f2-8534a3dd85b6.png)

**Comment by conath** [comment]
Right now you'll need to scroll down and then click on the computer button to select the OS icon. Here's a screenshot of what it looks like when scrolled down on the info tab, and with an icon selected: 
<img width="791" alt="Screen Shot 2021-11-12 at 20 40 54" src="https://user-images.githubusercontent.com/12073163/141525377-c6e5d4cf-ec2d-4d0b-a0c3-07f4b5614b4e.png">

This UI needs to be improved in my opinion. @osy has this UI been updated in the Monterey branch?

**Comment by SpeedStepper** [comment]
Thank you for the quick & informative response!

 I will close this issue since it's mostly cosmetic and a UI update on Monterey is a larger separate topic.

Thanks for all the great work UTM Team 😃.

**Comment by rcatyvr** [comment]
The problem still exist in Monterey. Guarantied solution:

1. open the .utm container
2. paste in your preferred icon: yourOS.png in the same folder as the .plist files are found
3. open config.plist inside the .utm container in your favourite text editor (it is plain text)
4. find the line: 		<key>Input</key>                     (note the indent is 2 tabs)
5. paste the following 7 lines directly above that line   (note the indent is 2 tabs): 
		**<key>Info</key>
		<dict>
			<key>Icon</key>
			<string>yourOS.png</string>
			<key>IconCustom</key>
			<true/>
		</dict>**
