### ISSUE TITLE
Cannot install Ubuntu Server 20

### ISSUE THREAD

**Issue by saberioon** [utmapp/UTM#3311]
When I tried to install ubuntu on my MacBook pro M1, UTM closed with this error. 

`drive0, #block587: Preventing invalid write on metadata (overlaps with active L1 table)`

and after opening UTM again and run the ubuntu installer I am getting this error: 

`qemu-aarch64-softmmu: -drive if=none,media=disk,id=drive0,file=/Users/mms/Library/Containers/com.utmapp.UTM/Data/Documents/ubuntu.utm/Images/disk-0.qcow2,cache=writethrough: qcow2: Image is corrupt; cannot be opened read/write`

Any advice

**Comment by conath** [comment]
It seems like the VM's drive file was damaged somehow. Please try the following:

1. open UTM and select the VM
2. click Options/configuration button (the right-most one)
3. click Drives tab
4. Delete the drive with the disk-0.qcow2 name
5. click Save
6. click Options again
7. click Drives tab again
8. create a new drive (capacity at least 20GB)
9. click Save
10. re-try installing Ubuntu Server

**Comment by conath** [comment]
If after following all steps an error occurs, please re-try with Debug Log enabled and post the Debug Log below (see the [troubleshooting page](https://github.com/utmapp/UTM/wiki/Troubleshooting-a-VM) for details)
