### ISSUE TITLE
Ubuntu-desktop installation failing

### ISSUE THREAD

**Issue by Daniyal-Warraich** [utmapp/UTM#3315]
I installed Ubuntu Server successfully, however I am facing issues trying to `sudo tasksel install ubuntu-desktop`.
It always gives me this error: `tasksel: apt-get failed (100)`
<img width="799" alt="Screen Shot 2021-11-15 at 11 02 38 PM" src="https://user-images.githubusercontent.com/84168421/141924086-7e5db802-0e72-4b3d-9e86-dcfa0795610a.png">

**Configuration**
* UTM Version: 2.4.1
* OS Version: 12.0.1
* Apple Silicon

[ubuntu-debug.log](https://github.com/utmapp/UTM/files/7543532/ubuntu-debug.log)

I use the same configuration as suggested in the installation guide.

**Comment by Daniyal-Warraich** [comment]
I have tried doing `sudo tasksel install ubuntu-desktop` multiple times.

**Comment by conath** [comment]
Can you please try `dig duckduckgo.com` and `dig @1.1.1.1 duckduckgo.com` from the VM? If the first one results in a timeout, you'll need to set manual DNS or switch the VM Network to Bridged Mode networking.

**Comment by Daniyal-Warraich** [comment]
It doesn't return timeout or any error; it seems it returned ok.
<img width="601" alt="Screen Shot 2021-11-16 at 5 42 09 PM" src="https://user-images.githubusercontent.com/84168421/142083766-39a49751-7dfe-4ca4-a38f-cd088d83277c.png">

The second one, however, timed out.

**Comment by conath** [comment]
Ok this was to confirm that auto-DNS works. There is no error in your Debug Log and I can see the network mode is "Shared", which works with Linux from my experience.

It seems like your VM got most of the packages installed before the process failed. It might be worthwhile to get a log from the `tasksel` action you are attempting and see which package might be failing to install and how it fails.

**Comment by Daniyal-Warraich** [comment]
I didn't do anything apart from what you suggested to the system: and now it works. I don't know why. Maybe doing what you suggested made it work?
<img width="1440" alt="Screen Shot 2021-11-16 at 6 02 48 PM" src="https://user-images.githubusercontent.com/84168421/142085353-20178de4-de33-4608-a42b-7f7d4f67f7cd.png">

Thanks for all your help.

**Comment by conath** [comment]
The command I posted is a DNS lookup; all it does is determine an IP or a domain. So no, that wasn't it. But apparently enough of your packages installed :)

**Comment by Daniyal-Warraich** [comment]
Oh, @conath I found another way to do it: `sudo apt install ubuntu-desktop`
