### ISSUE TITLE
Which cpu set the vm is using

### ISSUE THREAD

**Issue by amir1kkh** [utmapp/UTM#332]
As you know apple uses two sets of cpu for their iphone and ipads first set is normal set and second one is high performance set for example iphone 7 has 2 cpu cores for casual usage and 2 high performance cores for gaming which by the way these 2 sets can’t be in use at the same time
I wanted to ask if it’s possible UTM app sometime use the low speed cpu and sometimes the high speed ones cause for example sometimes the boot time for windows xp ,on an iphone 7 with system configuration of 2 cpu cores, is about 2 minutes but sometimes it takes up to 10minutes to boot

**Comment by osy86** [comment]
You can’t control it. Apple’s hardware automatically chooses based on how much resources the app is using.
