### ISSUE TITLE
M1 iPad not loading vm

### ISSUE THREAD

**Issue by GamerHut96** [utmapp/UTM#3321]
M1 iPad not loading any vm, I tried making one from scratch and did not work so I downloaded a prebuilt one and nothing happens too, please fix, M1 iPad has a lot of issues with modding and jail breaking right now but I need Utm to work

**Comment by conath** [comment]
Do you mean it UTM shows a black screen when you tap Play? UTM doesn't work on iOS without enabling JIT; either AltJIT or [Jitterbug](https://github.com/osy/Jitterbug) or Xcode or some other method. (Jailbreak would be an option but there isn't one for M1 iPad.)

You can use UTM SE on your iPad without any JIT workarounds. It runs slower than regular UTM, though, so it's not recommended to run modern guest OS in it.
