### ISSUE TITLE
Possibility of booting Android on UTM?

### ISSUE THREAD

**Issue by firefinchdev** [utmapp/UTM#3325]
Hi
Google has confirmed that the official emulator would not make older versions of Android available via the official Android emulator on the M1 macs.
It would be really useful if UTM is able to boot Android images.
If we can boot ARM64 based images, then performance would be good enough.

Edit: typo

**Comment by conath** [comment]
This is off topic for the UTM issues section, this is for technical problems and suggestions. I will move this topic to Discussions.

I would recommend you research if it is possible to run Android in QEMU, which is the emulator used in UTM. Please let us know if you find out that it is or isn't possible.
