### ISSUE TITLE
R statistical package: key chisq.test() function not working

### ISSUE THREAD

**Issue by SugarRayLua** [utmapp/UTM#3326]
**Describe the issue**
A clear and concise description of what the issue is:

Wanting to rely on UTM to do more R statically package work. Almost all R functions and packages seem to work except for the important chi squared R base function (chisq.test()). Consistently gives an "illegal operation" error and crashes the R program but not UTM. Confirmed not working with multiple different small datasets as examples with either R version 3.5.2 or 3.6.3 despite multiple attempted re-installs of each. Function works fine with same data set in R in Mac Terminal. 

Interestingly, function fails in R 3.6.3 in iSH emulator app also with an illegal operation--perhaps a problem with emulators on iPad and R program? Also interesting is that the function does work when used in the App Store R app "R Analyst" (although that R version is much older and not running through an additional host iOS emulator). 

Has anyone else tried to use the chisq.test() function in R on UTM on their iPAD and gotten it to work? If so, would you please let me know what setup you got the chisq.test() function to work in? Tt is a very key function for my use. 

Thanks!

**Configuration (required)**
* UTM Version: 2.24
* OS Version: iPAD OS 15.1 
* Device Model: iPad Pro M1 8GB
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? Signulous 

Debian 10 x86_64 XFCE

(No crash logs included as did not crash UTM-- just crashed R).

**Comment by ktprograms** [comment]
I don't know much about R, you could try following [these](https://stackoverflow.com/a/40223712/15603854) instructions and paste the output.

Also please paste the exit code when R crashes (do it by running `echo $?` as the immediate next bash command after the crash).

**Comment by SugarRayLua** [comment]
Thanks, @ktprograms, for such prompt a reply!

I followed all of your suggestions and got the following output (although unfortunately did not give me actual assembly output):

Test case in R:
------------------------------

> x = c("Mike", "Mark", "Jeff")
> y = c("Blue", "Red", "Red")
> chisq.test(x,y)

 *** caught illegal operation ***
address 0x7f1fe77db820, cause 'illegal operand'

Traceback:
 1: tcrossprod(as.vector(X), as.vector(Y))
 2: outer(sr, sc, "*")
 3: chisq.test(x, y)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 1
R is aborting now ...
Illegal instruction

------------------------
#Entered echo $? right after this crash and got this:

xxx@debian:~$ echo $?
132

-------------------------
#Enabled core dumps and after R crashed followed instructions
# and a core dump folder named core.1001 was generated 
# and as instructed entered "gdb R core.1001" from Bash 
# and got the following reply:

[New LWP 1001]
Core was generated by `/usr/lib/R/bin/exec/R'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00007f7a162cd820 in ?? ()

---------------------------
#Typed in gdb layout asm and go the following response:

[No Assembly Available]

core LWP 1001 In:
Cannot access memory at address 0x7f7a162cd820
(gdb)

**Comment by ktprograms** [comment]
With that core dump, type `bt` when at the `(gdb)` prompt.

Also could you try running `gdb R`, then at the `(gdb)` prompt type `r`, and reproduce the issue? When it crashes, the type `layout asm`.

**Comment by SugarRayLua** [comment]
@ktprograms, thank you very much for your continued suggestions. I did what you said and got a little more information:
X
=
c( "Mike"
y
= c("red"
chisq.test(x,y)
"Sue"
Program received signal SIGILL,
Illegal instruction.
0x00007ffff5320820 in dgemm otcopy OPTERON SSE3 ()
from /usr/lib/x8664-linux-gnu/libopenblas.so.0
(adb) bt
#0
0x00007ffff5320820 in dgemm_otcopy_OPTERONSSE3()
from /us/lib/x86 64-linux-gnu/libopenblas.so.0
＃1
0x00005555576def08 in ?? ()
#2
0x0000000000000004 in ?? ()
#3
0x0000000000000001 in ?? ()
#4
0x00007ffff6a37530 in
?? () from /us/lib/x86 64-Linux-gnu/libopenblas.so.0
#5
0x00000000000000in?? (

Layout asm did work but then showed me what I believe was at least 100 lines of assembly code and didn’t seem to flag any specific part as abnormal. Unfortunately, such code is above my head in understanding to be able to debug. Is there something specific I should look for in that asm code as a clue?

Since I saw the mention about OpenBlas in the stack traceback section pasted above, I thought there might be something wrong with my Blas/OpenBlas code (since the chisq.test function does use matrix math that would depend on Blas/OpenBlas), and I downloaded an R package to link the latest OpenBlas to my R code. Unfortunately that ended up breaking something so that now the sub-package that contains the chisq.test function won’t load in R at all. I’ll probably end up re-installing R again to get back to a starting point to troubleshoot this.

Please let me know if you have further ideas. 

Have good upcoming week.

**Comment by ktprograms** [comment]
Could you please paste the `layout asm` output in a code block?

It looks like sse3 isn't emulated by qemu

**Comment by SugarRayLua** [comment]
Thanks, @ktprograms, I think you figured out the problem and read that R requires SSE3 for many of its calculations and because of that is not yet supported for ARM (although there is an ARM R build in development given the support of the M1 Mac). That might also be why R causes the same error in iSH since although the iSH emulates an x86, the developer might not have built in SSE3 support. The following article from the RStudio R IDE developers discusses this:

https://developer.r-project.org/Blog/public/2020/11/02/will-r-work-on-apple-silicon/

However, the article goes on to mention that with Rosetta, R does run okay on the M1 MAC without SSE3, and I found some further info that seemed to indicate QEMU can emulate the SSE3 instruction set with perhaps some settings turned on:

https://www.linux-kvm.org/page/Tuning_KVM

It may take me a day to reinstall R in UTM (after I broke it from my experiment in trying to bind a new OpenBlas library to it), but after that I can paste the asm code. However, I don,t know how to do that in this forum (straight cut and paste would seem overwhelming with number of lines). Is there a special way to upload the asm code to this message on the forum?

I think this will be helpful to other potential UTM users that are thinking about using it for R since I believe the UTM wiki last had R as working, but not being able to run a basic chi-square test in R being built for statistics is a big deficit in wanting to use it in UTM.

Thanks again for your help.

**Comment by ktprograms** [comment]
You can upload the output of `layout asm` to a [GitHub Gist](https://gist.github.com).

**Comment by SugarRayLua** [comment]
Hi, @ktprograms, guess what!

I got my reinstalled and got my broken R working again by removing the new OpenBlas libraries that I had linked to my R using:

update-alternatives --config libblas.so.3-x86_64-linux-gnu and update-alternatives --config liblapack.so.3-x86_64-linux-gnu

I thought that would just get my R working back to their baseline state by linking back the blas libraries that were previously linked to R. I then started gdb aiming to reproduce the error and sent you the asm code via Gist, but then instead, it just worked!

x = c("Jon", "Larry", "Sue")
> y = c("red", "blue", "red")
> chisq.test(x,y)

	Pearson's Chi-squared test

data:  x and y
X-squared = 3, df = 2, p-value = 0.2231

Warning message:
In chisq.test(x, y) : Chi-squared approximation may be incorrect

(That warning message is an appropriate warning message in R).

So, it seems that the amazing UTM app may be able to run full R! I'm not sure though how if its not able to emulate ssse3 instruction set, but it seems to work. It may be though that actually the chisq.test function doesn't need to use the ssse3 instruction set-- I'll watch for any other errors that might pop up because of it but so far, this was the only one I found. I not sure why it now works and hasn't in the past--the only thing differently I did was to update the Blas and Lapack libraries bound to R with standardly installed Blas and Lapack libraries-- perhaps they are not standardly attached to R in a standard R installation? This has all gotten above my head as a novice Linux user, but I'm very happy that it works and very thankful that you introduced me to gdb and helped me troubleshoot the problem. 

I'll let others in the R community know--based on the previous R/Mac article I previously linked to, the M1 Mac community has been worried about not having an official R or RStudio ARM distribution and UTM Mac program might fit their needs. 

Unless you have other questions or things you would like me to test on this matter, please feel free to close this issues. :-)

**Comment by conath** [comment]
You could try adding the SSE3 CPU flag in the VM config => Advanced => CPU to ask QEMU to emulate it. I'm not sure if it is supported in the QEMU that is included with UTM.

**Comment by SugarRayLua** [comment]
Hi, @conath. 
I tried on my iPad going to VM config => Qemu => Advanced => Bypass configuration and manually set arguments and added
-cpu +ssse3

However, that didn’t seem to work as VM gave me a “could not open ‘ssse3’ no file or directory” error.

On the positive side I think this is now a non-issue in that I got the function to work I think by linking the OpenBLAS and Lapack packages in the Debian 10 repository with R via the “update-alternatives’ command over R’s preconfigured BLAS package. I think that might mean that UTM’s Qemu does have ssse3 emulation (since everything seems to work now with R statistics). 

If I find any other instances where R doesn’t work in UTM, I’ll troubleshoot it and start a new issues; otherwise, I’ll keep my fingers crossed, enjoy using full R, and close this issue. 

Have a good night.

**Comment by conath** [comment]
Sorry, made a typo. The CPU flags option is in VM Config => System => Advanced.

![cpu-flags](https://user-images.githubusercontent.com/12073163/143407435-86fd3b7a-25ea-4d19-81a4-0379960f2643.jpeg)

**Comment by SugarRayLua** [comment]
That’s, interesting, @conath — I see that now. I’ve been using the “default” CPU which doesn’t give me the option to set those ssse3 flags like I can if I choose the Penryn CPU. Perhaps if R is now working the default CPU has the ssse3 flag set? Do you know what CPU settings are actually used if one chooses the “default” CPU? Is there any advantage to choosing the Penryn CPU for regular UTM x86_64 work? Non-urgent, but I’m curious and suspect other UTM users might be interested (perhaps for another forum or the UTM wiki). Thanks!

**Comment by conath** [comment]
Default CPU will select based on the system. I believe it will be `qemu64` for `x86_64` which has the following flags as standard:

`fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx lm up pni hypervisor` 

Note to take this list with some skepticism because it is from [Tuning KVM](https://www.linux-kvm.org/page/Tuning_KVM). UTM doesn't use KVM so not sure it all of these flags apply. (on iOS, UTM uses the TCG emulator)

After doing some more digging online, I found this semi-recent change to QEMU which indicates `qemu64` roughly has the capabilities of an "AMD AthlonTM 64 X2" processor, [which did not (originally) support SSE3](https://www.amd.com/system/files/TechDocs/33425.pdf). (side note: the CPU speed is not controlled by the model chosen - UTM will always run at maximum possible emulation speed)

The conclusion, then, is to change your VM's CPU to `qemu64` and add all of the flags you would like/need and see if it works. If you enable [Debug Log](https://github.com/utmapp/UTM/wiki/Troubleshooting-a-VM#how-to-get-debug-log) you will see in the log if the emulator doesn't support one or more of the flags you requested.

**Comment by SugarRayLua** [comment]
Thank you very much for that additional information and explanation.
