### ISSUE TITLE
New GUI Concept

### ISSUE THREAD

**Issue by vishy-dev** [utmapp/UTM#334]
(Edited) I have made a new GUI for UTM: iPhone, iPad and MacOS (In Progress)

Instead of scrolling, I update the latest GUI at https://vishy-dev.github.io/utmGUI/

If you want to suggest something, add a comment. If you want to see the new GUI, just use the link

**Comment by ThatsNiceGuy** [comment]
The iPhone UI concept looks good, but would this translate over to iPads?

**Comment by osy86** [comment]
Yeah that looks nice. I'm not sure what the other tabs would be though. It doesn't make sense to make settings its own tab because it's per-VM. Debug Log isn't really useful for 99% of people, so it doesn't make sense to give real estate to it.

I think the tiles are nice but there's a bit too much shadow imo, it doesn't look "modern iOS". According to [Apple](https://developer.apple.com/design/human-interface-guidelines/ios/overview/themes/):

> Minimal use of bezels, gradients, and drop shadows keep the interface light and airy, while ensuring that content is paramount.

**Comment by snslpa** [comment]
What do you think about this but with a modern design? Wizard machine creator based on your Apple hardware and the guest OS would be great.

It is Qemu manager 7 for windows.

<img width="924" alt="1" src="https://user-images.githubusercontent.com/64661812/82265224-634a2300-995e-11ea-9197-837e6488ae26.png">
<img width="928" alt="2" src="https://user-images.githubusercontent.com/64661812/82265335-a4423780-995e-11ea-9eb6-b51d305edbca.png"><img width="924" alt="3" src="https://user-images.githubusercontent.com/64661812/82265345-a906eb80-995e-11ea-8ad4-f43398f384c1.png"><img width="862" alt="4" src="https://user-images.githubusercontent.com/64661812/82265646-67c30b80-995f-11ea-9b58-845e88c3ef59.png">
<img width="860" alt="5" src="https://user-images.githubusercontent.com/64661812/82265648-68f43880-995f-11ea-80d5-0e8168335742.png">
<img width="935" alt="6" src="https://user-images.githubusercontent.com/64661812/82265649-698ccf00-995f-11ea-8966-62500070b38c.png">

Also
PDF MANUAL:
[qemumanager.pdf](https://github.com/utmapp/UTM/files/4647196/qemumanager.pdf)

**Comment by osy86** [comment]
I very specifically wanted to AVOID something like that. It feels antiquated to me and doesn't fit iOS.

**Comment by vishy-dev** [comment]
> Yeah that looks nice. I'm not sure what the other tabs would be though. It doesn't make sense to make settings its own tab because it's per-VM. Debug Log isn't really useful for 99% of people, so it doesn't make sense to give real estate to it.
> 
> I think the tiles are nice but there's a bit too much shadow imo, it doesn't look "modern iOS". According to [Apple](https://developer.apple.com/design/human-interface-guidelines/ios/overview/themes/):
> 
> > Minimal use of bezels, gradients, and drop shadows keep the interface light and airy, while ensuring that content is paramount.

True, I did kinda neglect using a list view. I will update that.

**Comment by vishy-dev** [comment]
> The iPhone UI concept looks good, but would this translate over to iPads?
On iPads we could have a form of split screen, the selection for vm on the side, vm details on the rest of the screen (settings etc)

**Comment by vishy-dev** [comment]
I’ll try make a better one with a bit more context and also a iPad version

**Comment by snslpa** [comment]
It was only an idea to have more options but it's better to follow Apple guidelines, simplicity its much better.

Thanks, Osy86 and vishy.

**Comment by vishy-dev** [comment]
I would try to make storyboards but sadly I'm not that experienced in iOS. I code in flutter, not native. I'll stick to sketch, I'm almost done with the home design, I'll also try design VM settings and maybe more menus. From reading latest issues, I'll make a MacOS version too

**Comment by vishy-dev** [comment]
How does this look? I kind of based it on the current GUI, and Apple's Guidelines. ![image](https://user-images.githubusercontent.com/56125930/82430593-71469380-9a85-11ea-8700-f9e4294201ed.png) 
![image](https://user-images.githubusercontent.com/56125930/82430642-86232700-9a85-11ea-90ad-381fde9b8a89.png)

**Comment by snslpa** [comment]
It looks very nice, I add in red my suggestion.

Mosaic/List view icon for more options
Different (Play) location
RAM in the general specs

![82430593-71469380-9a85-11ea-8700-f9e4294201ed](https://user-images.githubusercontent.com/64661812/82440981-1cab1480-9a95-11ea-9b62-5581cabc1c2c.png)

**Comment by vishy-dev** [comment]
I'll update that when I get time.

**Comment by snslpa** [comment]
Thanks Vishy-dev

**Comment by vishy-dev** [comment]
no problem, I just saw this project, had some free time, found it interestiny. I wanted to contribute.

**Comment by vishy-dev** [comment]
I didn't add the second button you suggested parallel to the **Windows 7** text, as that would be too many in my opinion. ![image](https://user-images.githubusercontent.com/56125930/82560021-847e5f80-9b68-11ea-8b93-90ccd6c5f090.png)

**Comment by snslpa** [comment]
Very nice but what about this? like in the Files app.
<img width="836" alt="Captura de pantalla 2020-05-21 a las 15 17 01" src="https://user-images.githubusercontent.com/64661812/82568104-3c663980-9b76-11ea-85a7-2504d29f8ef9.png">

**Comment by snslpa** [comment]
Also RAM first, SPICE Tool last. ;-)

**Comment by snslpa** [comment]
Also there is a line for that. Boot sequence.
<img width="839" alt="Captura de pantalla 2020-05-21 a las 18 37 34" src="https://user-images.githubusercontent.com/64661812/82588483-c6240000-9b92-11ea-85fc-07da5b920f77.png">

**Comment by vishy-dev** [comment]
> Very nice but what about this? like in the Files app.
> <img alt="Captura de pantalla 2020-05-21 a las 15 17 01" width="836" src="https://user-images.githubusercontent.com/64661812/82568104-3c663980-9b76-11ea-85a7-2504d29f8ef9.png">

tried that but couldn't find the icon in apples library so I went with that

**Comment by vishy-dev** [comment]
> Also there is a line for that. Boot sequence.
> <img alt="Captura de pantalla 2020-05-21 a las 18 37 34" width="839" src="https://user-images.githubusercontent.com/64661812/82588483-c6240000-9b92-11ea-85fc-07da5b920f77.png">

I'll update it in a bit

**Comment by vishy-dev** [comment]
Also what should the Mac OS version look like hmm

**Comment by vishy-dev** [comment]
Maybe I'll use a virtual box like design but then with new things. So like play controls and edit etc could be in a top bar like this 
![100971FB-F8FF-4992-BEFF-F6FFB508853F](https://user-images.githubusercontent.com/56125930/82589870-b3122f80-9b94-11ea-94c7-093187371f0f.jpeg)

**Comment by snslpa** [comment]
if we want more refinement, the icons with the OS logo can be even better. The exact OS Logo, Windows 10 logo is different to XP for example, and same in macOS, Tiger, Leopard, Catalina ... Linux Arch Debian, Suse, Ubuntu ... The ideal thing is to put the OS logo in the bottom left of the snapshot:
<img width="1260" alt="Captura de pantalla 2020-05-21 a las 19 55 57" src="https://user-images.githubusercontent.com/64661812/82595456-7f87d300-9b9d-11ea-83a3-04dad4a77b70.png">

**Comment by vishy-dev** [comment]
hmmmm i dont know if this is good so far ![image](https://user-images.githubusercontent.com/56125930/82596252-e8bc1600-9b9e-11ea-8349-f02974d47a20.png)

**Comment by vishy-dev** [comment]
> if we want more refinement, the icons with the OS logo can be even better. The exact OS Logo, Windows 10 logo is different to XP for example, and same in macOS, Tiger, Leopard, Catalina ... Linux Arch Debian, Suse, Ubuntu ... The ideal thing is to put the OS logo in the bottom left of the snapshot:
> <img alt="Captura de pantalla 2020-05-21 a las 19 55 57" width="1260" src="https://user-images.githubusercontent.com/64661812/82595456-7f87d300-9b9d-11ea-83a3-04dad4a77b70.png">

hmm, like how virtual box has some generic icons, we could get something like that
![image](https://user-images.githubusercontent.com/56125930/82596512-510af780-9b9f-11ea-8404-dad0d4536eb1.png)

**Comment by ThatsNiceGuy** [comment]
I’m by no means an expert on this but I strongly suggest that UTM uses generic icons because the project probably doesn’t have rights to use those icons

**Comment by vishy-dev** [comment]
yes thats true for what snspla said. thats probably why vbox has their own icons

**Comment by snslpa** [comment]
Probably, some Parallels and VMWare uses genuine logos, not generic but are paid apps, maybe with rights. But elegant generic is OK.

**Comment by vishy-dev** [comment]
how it look? ![image](https://user-images.githubusercontent.com/56125930/82607385-9552c380-9bb0-11ea-8f8a-dbca74fc8f69.png)

**Comment by vishy-dev** [comment]
vmware uses their own icons 
![image](https://user-images.githubusercontent.com/56125930/82607521-dc40b900-9bb0-11ea-9242-006cfa17a212.png)

**Comment by vishy-dev** [comment]
looks custom too, but this could be a old version, its just from a google. ![image](https://user-images.githubusercontent.com/56125930/82607677-232eae80-9bb1-11ea-8e1f-9cb445166efa.png)

**Comment by snslpa** [comment]
> how it look? ![image](https://user-images.githubusercontent.com/56125930/82607385-9552c380-9bb0-11ea-8f8a-dbca74fc8f69.png)

Not so clean as previously. It needs more refinement, more Apple Style.

**Comment by vishy-dev** [comment]
Which parts? I didn't know what to do for the like bottom info section. If you could guide me a bit as I'm not sure apple doesn't have much on listviews/ info views for macOS.

**Comment by snslpa** [comment]
What do you think about this, without squares
<img width="883" alt="Captura de pantalla 2020-05-22 a las 10 50 58" src="https://user-images.githubusercontent.com/64661812/82656190-4130f900-9c1b-11ea-9e78-10e859d1431b.png">

**Comment by snslpa** [comment]
Even, it can be simplified with small and elegant icons
<img width="298" alt="Captura de pantalla 2020-05-22 a las 11 02 08" src="https://user-images.githubusercontent.com/64661812/82656461-b8668d00-9c1b-11ea-9f6f-d3a1d634def0.png">

**Comment by vishy-dev** [comment]
I was also thinking about a fusion like design, with just a big picture and basic info on the VM view and the more detailed stuff in settings

**Comment by vishy-dev** [comment]
like this?
![Desktop HD](https://user-images.githubusercontent.com/56125930/82658337-b9e58480-9c1e-11ea-93d6-2caf544d2d76.jpg)

**Comment by snslpa** [comment]
Look at my Parallels and my VirtualBox: Complete different. I think UTM is a Qemu machine and should be more like what you are doing, similar to Virtual Box but with more macOS style and elegant. 
<img width="507" alt="Captura de pantalla 2020-05-22 a las 11 23 08" src="https://user-images.githubusercontent.com/64661812/82658299-a9350e80-9c1e-11ea-8849-cd15e467080e.png">
<img width="905" alt="Captura de pantalla 2020-05-22 a las 11 25 53" src="https://user-images.githubusercontent.com/64661812/82658631-3c6e4400-9c1f-11ea-8b0f-78449089eb81.png">

**Comment by vishy-dev** [comment]
hows my new design

**Comment by vishy-dev** [comment]
also heres a pic of fusion for reference
![image](https://user-images.githubusercontent.com/56125930/82658767-87885700-9c1f-11ea-914b-21a834a23cdf.png)

yea what you are saying. It needs to be like vbox, but more fitting with macOS

**Comment by snslpa** [comment]
> like this?
> ![Desktop HD](https://user-images.githubusercontent.com/56125930/82658337-b9e58480-9c1e-11ea-93d6-2caf544d2d76.jpg)

This one looks very nice the only thing is the icons in the corner, not sure about the style. Also the trash is close to the settings so it can be accidentally touch

**Comment by vishy-dev** [comment]
there would be some sort of verification before deleting?

**Comment by vishy-dev** [comment]
1 min let me change the button style

**Comment by vishy-dev** [comment]
or do we put the buttons in the toolbar ?

**Comment by vishy-dev** [comment]
i like this one ![Desktop HD](https://user-images.githubusercontent.com/56125930/82659463-a9360e00-9c20-11ea-8050-0c23fdfb9f84.jpg)

**Comment by snslpa** [comment]
Good point and the trash down in the corner, also a play button un the center of the os that when is paused can be converted into sleep button such as a moon or zzz
<img width="504" alt="Captura de pantalla 2020-05-22 a las 11 37 43" src="https://user-images.githubusercontent.com/64661812/82659475-afc48580-9c20-11ea-806c-61f68a7c1c14.png">

**Comment by vishy-dev** [comment]
ok 2 mins

**Comment by vishy-dev** [comment]
wait if we put a play button do we move the vm text down to below the image or put the play button below the Windows 10

**Comment by snslpa** [comment]
I think that trash should be separated, in the corner or inside the setting.

**Comment by vishy-dev** [comment]
hmm, i guess its in settings now
![Desktop HD](https://user-images.githubusercontent.com/56125930/82659863-43965180-9c21-11ea-9f85-610df12acdaf.jpg)

**Comment by vishy-dev** [comment]
> wait if we put a play button do we move the vm text down to below the image or put the play button below the Windows 10

where we put it

**Comment by snslpa** [comment]
> hmm, i guess its in settings now
> ![Desktop HD](https://user-images.githubusercontent.com/56125930/82659863-43965180-9c21-11ea-9f85-610df12acdaf.jpg)

I love this one

**Comment by vishy-dev** [comment]
looks perfect now ![image](https://user-images.githubusercontent.com/56125930/82660136-b7385e80-9c21-11ea-998f-6305bc9a8462.png)

**Comment by vishy-dev** [comment]
or do we not like the play button

**Comment by snslpa** [comment]
I love it, even with 2 play buttons but it's ok.

**Comment by snslpa** [comment]
You are a genius Vishy

**Comment by snslpa** [comment]
Maybe the notes in the OS corner should appear if in the settings, someone fills this field.

**Comment by vishy-dev** [comment]
hmm
but i kinda like it there. for example if i stored credientals there if it was like a premade vm from a future importable like .utmVM or something. if so i would have to open settings every time to get the creds

**Comment by snslpa** [comment]
I like it there too, but I mean that if we add a field in the settings to add notes, it automatically is on the main screen, but if it is empty, nothing there. What do you think?

**Comment by vishy-dev** [comment]
yea could be. i kinda liked the area where it says click to add text as like a text box, but that could be too

**Comment by snslpa** [comment]
The next step is the VM toolbar
In parallels is in the top, in Virtualbox is in the bottom
<img width="368" alt="Captura de pantalla 2020-05-22 a las 11 58 06" src="https://user-images.githubusercontent.com/64661812/82661326-b6083100-9c23-11ea-981f-b6695636d4b2.png">
<img width="647" alt="Captura de pantalla 2020-05-22 a las 12 01 16" src="https://user-images.githubusercontent.com/64661812/82661472-fcf62680-9c23-11ea-9258-f3135a2326e4.png">

**Comment by vishy-dev** [comment]
hmm

**Comment by snslpa** [comment]
And the settings view also

**Comment by snslpa** [comment]
Settings in VB and P
<img width="693" alt="Captura de pantalla 2020-05-22 a las 12 19 02" src="https://user-images.githubusercontent.com/64661812/82662867-87d82080-9c26-11ea-85be-96c9733bfd78.png">
<img width="703" alt="Captura de pantalla 2020-05-22 a las 12 17 45" src="https://user-images.githubusercontent.com/64661812/82662875-8ad31100-9c26-11ea-86be-249a9da8549f.png">
<img width="704" alt="Captura de pantalla 2020-05-22 a las 12 16 51" src="https://user-images.githubusercontent.com/64661812/82662877-8c043e00-9c26-11ea-9aa8-98ebc00e3ad3.png">

**Comment by vishy-dev** [comment]
im a bit busy right now, ill be back in 15-20 mins

**Comment by snslpa** [comment]
Take your time, you have done a big step. Thanks for your contribution

**Comment by vishy-dev** [comment]
backkk. just attended a birthday party

**Comment by vishy-dev** [comment]
ok ive put the latest version on https://vishy-dev.github.io/utmGUI so when we are done people wont have to scroll

**Comment by vishy-dev** [comment]
do we use a side bar like par or topbar like vbox?

**Comment by snslpa** [comment]
Good question, the idea is to do something original, clean and fresh design

**Comment by vishy-dev** [comment]
im thinking a finder like sidebar with all the things ![image](https://user-images.githubusercontent.com/56125930/82665549-efdd3580-9c2b-11ea-83b1-cf5817bee56d.png)

**Comment by vishy-dev** [comment]
we can also make some minimal icons

**Comment by vishy-dev** [comment]
what other settings would there be hmm

**Comment by vishy-dev** [comment]
looks good ![image](https://user-images.githubusercontent.com/56125930/82665816-798d0300-9c2c-11ea-9af3-940de33c74be.png)

**Comment by snslpa** [comment]
I like it and it is a good idea to have small icons, we have to think also in the dark mode, so the change doesn't affect to the final design.

**Comment by vishy-dev** [comment]
don't think theres more stuff that utm does right now? can i get a like list of any settings im missing. if none ill start designing the icons and then the menus themselves

**Comment by snslpa** [comment]
Storage maybe separate?

**Comment by snslpa** [comment]
Sorry, Drives is there

**Comment by vishy-dev** [comment]
yes

**Comment by vishy-dev** [comment]
adding icons from apple's icons

**Comment by vishy-dev** [comment]
usb icon is hard to find

**Comment by vishy-dev** [comment]
maybe cause there isnt one...

**Comment by vishy-dev** [comment]
got a usb icon but now need a disk icon

**Comment by vishy-dev** [comment]
got it
(totally not stolen from finder but)

**Comment by snslpa** [comment]
I don't know the icon style you are using to help you

**Comment by vishy-dev** [comment]
almost done anyway 
![image](https://user-images.githubusercontent.com/56125930/82666924-c96cc980-9c2e-11ea-9710-aa7932c92971.png)

**Comment by vishy-dev** [comment]
im just using apple's sf icons

**Comment by vishy-dev** [comment]
looks good to me ![image](https://user-images.githubusercontent.com/56125930/82667021-f3be8700-9c2e-11ea-8622-75681742be08.png)

**Comment by snslpa** [comment]
very cool

**Comment by vishy-dev** [comment]
thx, now im gonna do the pages itself

**Comment by snslpa** [comment]
in the System tab: 
Name, Description / Notes
Processor
RAM
JIT
...

**Comment by vishy-dev** [comment]
should we make a general tab for Name, Description / Notes

then in system

Boot Sequence
OS
Architecture 
Processor & Processor Aceleration
RAM

**Comment by snslpa** [comment]
Better

**Comment by snslpa** [comment]
In the General tab, an OS presets settings would be good (main OS configuration profiles for non-experts ), also a "restore defaults" button in all settings could be nice.

**Comment by vishy-dev** [comment]
hows this? 
![image](https://user-images.githubusercontent.com/56125930/82668629-ddfe9100-9c31-11ea-96c3-a9ab1bce4e4e.png)

**Comment by snslpa** [comment]
Elegant but can we add color to the RAM bar? just to indicate the recommended for your computer based on your specs.
<img width="579" alt="Captura de pantalla 2020-05-22 a las 13 44 07" src="https://user-images.githubusercontent.com/64661812/82668924-62e9aa80-9c32-11ea-9c95-7e1f069c2019.png">
<img width="436" alt="Captura de pantalla 2020-05-22 a las 13 44 25" src="https://user-images.githubusercontent.com/64661812/82668928-641ad780-9c32-11ea-8602-67774e75e2e3.png">

**Comment by snslpa** [comment]
Boot Sequence for the General Tab

**Comment by vishy-dev** [comment]
I’m gonna be busy for a bit, color may be harder to add as I’m using apples predefined ui  kit but ok

**Comment by snslpa** [comment]
not necessary but maybe as it is in the iOS app, a numerical indicative in a note under the slider.

**Comment by vishy-dev** [comment]
hows this
![image](https://user-images.githubusercontent.com/56125930/82672701-9a5b5580-9c38-11ea-8ae8-e493bd6a3b47.png)

**Comment by vishy-dev** [comment]
boot sequence can be a part of drives

**Comment by vishy-dev** [comment]
> In the General tab, an OS presets settings would be good (main OS configuration profiles for non-experts ), also a "restore defaults" button in all settings could be nice.

ill add the restore button, but i guess the config would be preset based on the os you select and your host's power

**Comment by vishy-dev** [comment]
![image](https://user-images.githubusercontent.com/56125930/82674691-9bda4d00-9c3b-11ea-8d84-39848b808ada.png)
![image](https://user-images.githubusercontent.com/56125930/82674744-adbbf000-9c3b-11ea-8ec6-f0fc73168609.png)

**Comment by saagarjha** [comment]
Was wondering why I had a hundred new emails this morning…

**Comment by vishy-dev** [comment]
lollll, sorry

**Comment by IIWare** [comment]
> (Edited) I have made a new GUI for UTM: iPhone, iPad and MacOS (In Progress)
> 
> Instead of scrolling, I update the latest GUI at https://vishy-dev.github.io/utmGUI/
> 
> If you want to suggest something, add a comment. If you want to see the new GUI, just use the link

lol It will look like Virtual Box

**Comment by IIWare** [comment]
> (Edited) I have made a new GUI for UTM: iPhone, iPad and MacOS (In Progress)
> 
> Instead of scrolling, I update the latest GUI at https://vishy-dev.github.io/utmGUI/
> 
> If you want to suggest something, add a comment. If you want to see the new GUI, just use the link

if the ios device has dark mode enabled, will dark mode support the new GUI?

**Comment by osy86** [comment]
Closing this since the new UI will be tracked in #408
