### ISSUE TITLE
Asks me to enable JIT or it isnt enabled on the alt server

### ISSUE THREAD

**Issue by BallerDope06** [utmapp/UTM#3348]
When i open the app, a text screen pops up saying "Cannot find AltServer for JIT enable. You cannot run VMs until JIT is enabled"

I don't have to make a configuration for this to pop up but a vm i am trying to make is a 64 bit windows xp computer with 512 mb of ram and 1 core
I am using v2.4.1 
The version of ios my phone is running is 14.7.1
I have an iphone 10
And no, it isnt jail broken i use alt store
I downloaded it from safari on my phone through the github page

I could not find a crash log and or how to even get it on here (im on my pc running windows 10)

I cant upload the vm because i mean. i cant even get it running. i can try other os like windows 7 or windows 98 but still dosent work.
![image](https://user-images.githubusercontent.com/95145451/143719453-8cc67858-2071-4b93-be51-8e913b3acef2.png)
I dont know if the picture will work but it is the pop-up of what happens everytime i try to open the app. i also have a screen recording of it happening.

**Comment by conath** [comment]
This message tells you that you didn't launch UTM with AltStore JIT enabled or according to the [instructions](https://getutm.app/install/). Please read about [how UTM works](https://getutm.app/faq/#how-does-utm-work) and note that Apple places many unfortunate restrictions on what we can do on iOS. If you want a simpler option without needing to launch with a Computer, install UTM SE instead.
<img width="330" alt="Screen Shot 2021-11-28 at 17 06 57" src="https://user-images.githubusercontent.com/12073163/143776186-f4bd267e-f729-4e4e-80a7-0208765e2b4a.png">

You can find the latest UTM IPA files on the [Releases](https://github.com/utmapp/UTM/releases) page.

**Comment by Eric-1987** [comment]
>If you want a simpler option without needing to launch with a Computer, install UTM SE instead. <img alt="Screen Shot 2021-11-28 at 17 06 57" width="330" src="https://user-images.githubusercontent.com/12073163/143776186-f4bd267e-f729-4e4e-80a7-0208765e2b4a.png">

@conath could you please clarify does UTM(with tether) always require to run Jitterbug on secondary device on the network?
So in case iPAD use UTM with tether, it(iPAD) can't autonomically run VM without running Jitterbug on the windows PC at the same time?

**Comment by conath** [comment]
That is correct @Eric-1987. Check out the new user guide for more information: [UTM User Guide: Installation on iOS](https://docs.getutm.app/installation/ios/)

**Comment by Eric-1987** [comment]
@conath could suggest me what would be faster run linux arm emulation or linux x64 emulation on iPAD(Air 4, CPU A14) ?

**Comment by conath** [comment]
@Eric-1987 It's going to be roughly the same speed. So it depends on availability of the applications you want to run, I would suggest the x64 version.

**Comment by Eric-1987** [comment]
@conath Thank very much for your help! WBR Danylo.

**Comment by Drobeled** [comment]
i use stikjit, and when i launch the utm through stikjit no message pops up, i cant use the virtualization option 

![Image](https://github.com/user-attachments/assets/5afefda5-ea6b-4915-bf5f-a5064738b944)
