### ISSUE TITLE
how to fix resolution on Windows 11 mac utm, spice was installed

### ISSUE THREAD

**Issue by Mikasxp** [utmapp/UTM#3358]
**Describe the issue**
A clear and concise description of what the issue is. **BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Configuration**
* UTM Version: 
* OS Version: 
* Intel or Apple Silicon? 

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open Console.app, go to `Crash Reports`, and find the latest entry for either QEMU, QEMUHelper, or qemu-\*. Right click and choose `Reveal in Finder`. Attach the report here.

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the top of the `QEMU` page is `Debug Log`. Turn it on and save the VM. After you experience the issue, open the VM settings again and select `Export Log...` and attach it here.

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by conath** [comment]
Please provide the info as requested in the issue template.

**Comment by Mikasxp** [comment]
hello,

the main problem is that I can't change the resolulion on windows 11 (ARM) on VM, I'm using UTM (Version 2.4.1 (40)) on mac M1 Monterey OS.
everything runs well, the "spice" is installed (0.164.2). after all I wanted to use it on Microsoft remote desktop. Without changing resolution - "it runs!", but in the VM on windows advanced display cannot be detected.... Maybe "in windows" video driver is missing?
