### ISSUE TITLE
UTM getting stuck while using in full screen

### ISSUE THREAD

**Issue by karanamrahul** [utmapp/UTM#3367]
**Configuration**
* UTM Version:  2.12
* OS Version:  MacOS Monterey 12.0.1
* Apple M-1

**Crash log**
qemu-aarch64-softmmu: -qmp tcp:127.0.0.1:4000,server,nowait: Failed to find an available port: Address already in use

I am using ubuntu 20.04 and the issue has been happening since two months.

Screen will get stuck and I need to manually close it down.

**Comment by conath** [comment]
Please update UTM. There have been many bug fixes and improvements. If you downloaded UTM from the website, simply download the latest version and replace the UTM.app in your Applications folder with the new one. This way your VMs are not removed.

If the problem does not go away with a UTM update, please re-open this issue.

<details>
  <summary>More info in case this error persists after you update UTM</summary>

It sounds to me like UTM is attempting to start a VM, but times out while waiting for the backend. A macOS restart could help, too.

When does this error occur? Please provide a list of exact steps to take to reproduce this error. (alternatively, you could make a screen recording that begins with you launching UTM.)

</details>
