### ISSUE TITLE
When open app, it’s white screen

### ISSUE THREAD

**Issue by Softdrink87** [utmapp/UTM#337]
**Describe the bug**
A clear and concise description of what the bug is. **BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**To Reproduce**

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here.

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the bottom of the configuration options is `Debug Log`. Turn it on and save the VM. After you experience the issue, quit the VM and re-launch UTM. Open the VM settings again and select `Export Log...` and attach it here.

**Upload VM**
If possible, upload the `.utm` you are experiencing an issue with. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

Hi,there. I’m loved user of this UTM. However,when I install resigned ipa through filza and open app,that’s white screen. Somebody know this situation?? Sorry for my English.

**Comment by professorIsaac** [comment]
You force quit didn’t you

**Comment by DJtijn1** [comment]
My UTM is inf crashing when I trying to open a virtual maschine so dit u know what it was and here is my debug screen: {"crashreporter_key":"deb0c33d7447f5a7d1c3da6861b394aa0b436aca","bug_type":"211","timestamp":"2021-07-27 02:01:46.00 +0200","os_version":"iPhone OS 14.7 (18G69)","incident_id":"C5445DA3-A77D-4CF4-A5DA-D1C483AF56F9"}
{"_marker":"<metadata>","_preferredUserInterfaceLanguage":"nl-NL","_userInterfaceLanguage":"nl","_userSetRegionFormat":"NL","configUuid":"7b23a67e-1f3e-464e-a7ce-dcf29138f2be","deviceCapacity":128,"startTimestamp":"2021-07-26T00:02:02Z","version":"2.1"}
{"message":{"BogusFieldNotActuallyEverUsed":null,"Count":6,"daily_total_BogusMeasureNotActuallyEverUsed":null},"name":"StabilityHeartBeatCount5","sampling":100,"uuid":"3c8f638f-d492-465e-9e27-546a163beac9_2"}
{"_marker":"<end-of-file>"}
