### ISSUE TITLE
Change default display upscaling mode to nearest neighbor

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#3371]
It was suggested [on Twitter](https://twitter.com/rsms/status/1467604395302866948?s=20) to change the default upscaling mode to integer/nearest neighbor. This results in sharp (but blocky) graphics for low-res guests when the window resolution is greater than the host screen resolution.

I am in favor of this idea as the now-default linear upscale doesn't look pretty in my opinion. Here is the same VM in two screenshots. 

This screenshot taken with linear scaling mode:
![utm-linear-scaling](https://user-images.githubusercontent.com/12073163/144768159-e0abd919-f0d0-4971-b78f-ca6c94363c7f.jpg)

This screenshot taken with nearest neighbor scaling mode:
![utm-nearest-neighbor-scaling](https://user-images.githubusercontent.com/12073163/144768163-20447c1b-e6f8-4c8a-8fa5-bdf279e379c3.jpg)

Note the noticeable lower contrast in the menu bar text in the linear mode, as well as the general fuzziness.

**Comment by livid** [comment]
It would be awesome if we could have integer scaling for full screen.

For instance, the M1 MacBook Air screen has a resolution of 2560x1600. When emulating OS 9.2.2 at a resolution of 640x480, the area required on the screen for integer scaling could be calculated as follows:

```python
device_width = 2560
device_height = 1600

vm_width = 640
vm_height = 480

for n in range(1, 6):
    width = vm_width * n
    height = vm_height * n
    if width <= device_width and height <= device_height:
        last_good_n = n

print("Last good n: " + str(last_good_n))
print("Last good width: " + str(vm_width * last_good_n))
print("Last good height: " + str(vm_height * last_good_n))
```

This would eliminate the fuzziness that occurs when using nearest neighbor scaling, especially when the device's width and height are not integer multiples of the VM's dimensions.
