### ISSUE TITLE
Integrity could not be verified

### ISSUE THREAD

**Issue by Mar10Josh** [utmapp/UTM#3382]
**Describe the issue**
This is what happened when I installed it using Apple Configurator 2.
This won't work, I don't think this will work with other installers, Well I don't know others.

**Configuration (required)**
* UTM Version: 2.4.1
* OS Version: iPadOS 15.0
* Device Model: iPad Pro 11-Inch
* Is it jailbroken (name jailbreak used)? Non-Jailbroken
* How did you install UTM? Apple Configurator 2

**Pictures**
![A screenshot from the iPad Pro 11-inch](https://user-images.githubusercontent.com/65928867/145695323-feb36aee-087d-472d-9ca9-eb51c83e7a37.png)

**Comment by conath** [comment]
It is recommended to [install UTM using AltStore](https://getutm.app/install/), as almost all other ways are known to be problematic.
