### ISSUE TITLE
No network in shared mode in Windows 11 ARM

### ISSUE THREAD

**Issue by hrleinonen** [utmapp/UTM#3385]
Hi,

I got no network in my Windows 11 ARM installation. Bridged network works fine, but in shared mode Windows won't get IP-address.

* UTM Version: 2.4.1 (40)
* OS Version: 12.0.1
* Intel or Apple Silicon: Apple M1 (2020)
* Guest OS: Windows 11 build 22499.1000
* Emulated network interface: virtio-net-pci
* SPICE tools: 0.164.2

Also shutting down Windows gives error:

"qemu-aarch64-softmmu: Spice: red-qxl.c:807:spice_qxl_gl_scanout: condition `qxl_state->gl_draw_cookie == GL_DRAW_COOKIE_INVALID' failed"

<img width="269" alt="Screenshot 2021-12-12 at 16 28 56" src="https://user-images.githubusercontent.com/37574297/145716466-3bf4ab4c-141f-463d-b06a-aedb6f83f1cc.png">

Regards,

Ville

**Comment by hrleinonen** [comment]
Reinstall and couple of reboots resolved this issue.

**Comment by saldana83** [comment]
Same problem here, i can't finish the installation because of the network
