### ISSUE TITLE
utm crash

### ISSUE THREAD

**Issue by liangyaobin** [utmapp/UTM#3390]
**Describe the issue**
UTM crash when running 3 centos vm on mac pro

**Configuration**
* UTM Version: 2.4.1(40)
* OS Version: macOS Monterey 12.0.1
* Apple M1 Pro 

**Crash log**
Thread 4 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x000000010302c000   x2: 0x000000011c700000   x3: 0x000000011c77f230
    x4: 0x0000000000000040   x5: 0x000000011c77f230   x6: 0x0000000000000004   x7: 0x0000000000000001
    x8: 0x000000011e058038   x9: 0x0000000000000000  x10: 0x000000011e058038  x11: 0x0000000000003fff
   x12: 0x000000000000eb9f  x13: 0x00000000ee123c20  x14: 0x000000010302c038  x15: 0x00000000ee123c2d
   x16: 0x00000000ee123b42  x17: 0x000000000000eb9f  x18: 0x0000000000000000  x19: 0x000000011c81a000
   x20: 0x000000011c81a7b0  x21: 0x000000011c77f230  x22: 0x00000000a1a1a1a1  x23: 0x000000016de870e0
   x24: 0xa3a3a3a3a3a3a3a3  x25: 0x0000000000000000  x26: 0x000000012a453f20  x27: 0x000000011c81a7a8
   x28: 0x00000001e46e4000   fp: 0x000000016dab5000   lr: 0x260180018b89747c
    sp: 0x000000016dab4fc0   pc: 0x000000018b897444 cpsr: 0x60001000
   far: 0x0000000000000010  esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
       0x18b9c8000 -        0x18b9fdfff libsystem_kernel.dylib (*) <c8524c02-b14f-30bd-a228-c44b4a448e68> /usr/lib/system/libsystem_kernel.dylib
       0x18b9fe000 -        0x18ba0afff libsystem_pthread.dylib (*) <4786e19a-9312-38e6-80ef-9c1394548118> /usr/lib/system/libsystem_pthread.dylib
       0x10460c000 -        0x10477ffff com.utmapp.glib-2.0.0 (1.0) <ee55ae15-bb01-3107-97ae-66b3fe44ba9d> /Applications/UTM.app/Contents/Frameworks/glib-2.0.0.framework/Versions/A/glib-2.0.0
       0x102348000 -        0x102673fff com.utmapp.UTM (2.4.1) <fc72dc0e-88df-332a-bb5e-15354d110883> /Applications/UTM.app/Contents/MacOS/UTM
       0x18ba4c000 -        0x18bf8ffff com.apple.CoreFoundation (6.9) <b2ff96d0-ae99-31ef-9014-fc9964b4f3e0> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x18e5e2000 -        0x18f493fff com.apple.AppKit (6.9) <518f4e68-c324-320f-9d7f-85c224eae972> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x193024000 -        0x19307ffff com.apple.CoreVideo (1.8) <0a5486b6-072c-36ad-bf48-7248e5039ecb> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
       0x18b88a000 -        0x18b8c5fff libobjc.A.dylib (*) <2eabed7f-1e81-3a1b-bb4b-985b8dd3b77f> /usr/lib/libobjc.A.dylib
       0x194614000 -        0x194943fff com.apple.HIToolbox (2.1.1) <98ea191e-b6f8-3036-b267-eeadb5f03c7d> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x1b032e000 -        0x1b1309fff com.apple.SwiftUI (3.1.9) <7075cb0c-797c-3cb0-b2f0-df2929140591> /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI
       0x102934000 -        0x102993fff dyld (*) <86a8ba48-8bb4-3b30-9cda-051f73c74f44> /usr/lib/dyld
       0x102828000 -        0x10283ffff com.utmapp.usb-1.0.0 (1.0) <f15a9ad5-5b69-36e0-9bbc-c24fa052a5eb> /Applications/UTM.app/Contents/Frameworks/usb-1.0.0.framework/Versions/A/usb-1.0.0
       0x103c90000 -        0x103db7fff com.utmapp.spice-client-glib-2.0.8 (1.0) <1a66af74-e7ee-3c7a-848d-8bced3b0bb33> /Applications/UTM.app/Contents/Frameworks/spice-client-glib-2.0.8.framework/Versions/A/spice-client-glib-2.0.8
       0x190666000 -        0x190b1dfff com.apple.CFNetwork (1325.0.1) <a9068037-0e3b-3486-88cb-5098d0c827e3> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
       0x18c943000 -        0x18cd30fff com.apple.Foundation (6.9) <de039f1b-ffe5-3644-a8cf-7ba52c32cd73> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x19439a000 -        0x1943c1fff com.apple.audio.caulk (1.0) <c8b77e54-af14-37e1-8a72-6437f54c6fd1> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

[utm-crash.txt](https://github.com/utmapp/UTM/files/7725706/utm-crash.txt)

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/7725710/debug.log)

**Comment by conath** [comment]
This looks like a SwiftUI or other system-related bug/crash. We've had a number of similar reports from users on macOS 12.0.1. Could you please update to macOS 12.1 or later and see if that resolves the issue? Thanks.
