### ISSUE TITLE
PowerPC Mac OS X Guests refuse to connect with Software Update server.

### ISSUE THREAD

**Issue by mavethee** [utmapp/UTM#3399]
**Describe the issue**
PowerPC Mac OS X Guests being connected to the network and loading webpages as old web browser can, they refuse to connect with Software Update server, tested every Mac OS X except Tiger (since my instal discs don't really contain "latest the greatest"), I'm kinda stuck to looking around for Combo update files. I've included Panther debug.log but each VM is just copy-paste of settings and issue with Software Updates.

**Configuration**
* UTM Version: 2.4.1
* OS Version: macOS 12.1 Monterey
* Intel or Apple Silicon? Apple Silicon M1 MacBook Air

**Debug log**
[Panther_Debug.log](https://github.com/utmapp/UTM/files/7748022/Panther_Debug.log)

**Upload VM**
[config.plist.zip](https://github.com/utmapp/UTM/files/7748026/config.plist.zip)

**Comment by conath** [comment]
Your configuration looks good, bridged mode network is the best for avoiding network problems with some guests. That said this does not sound like a UTM-related problem. Are you sure this Software Update still works on real PPC Macs? Servers or SSL certificates might have changed. 

Which Mac OS X specifically have you tested and which of them had this problem?

Do you have a way to test with a real USB network card passed to the VM via USB Sharing?

**Comment by mavethee** [comment]
> Your configuration looks good, bridged mode network is the best for avoiding network problems with some guests. That said this does not sound like a UTM-related problem. Are you sure this Software Update still works on real PPC Macs? Servers or SSL certificates might have changed.

On real PPC Macs I have no idea if it still works because I don't have one (I'm planning to get iMac G4 but its kinda pricey, I guess the design is a thing) but so far I found official combo updates hosted by Apple so I assume it still should work but in 10.5 for example I ended up boot looping after installing Combo (tried a few times on VM copies, same thing).
Out of like 7 cloned VMs with different Mac OS 9 (but since MacOS9Lives ISO exists I won't bother bringing its topic) and X - Software Update works perfectly on Tiger only which is a bit of funny since all my VMs are cloned from each other and upgraded. I checked, all of them have different IPs assigned by DHCP so they don't fight with each other on the network.
![image](https://user-images.githubusercontent.com/47083527/147095694-188d734b-c7e5-40d0-b7ad-74fe9085a788.png)

> Which Mac OS X specifically have you tested and which of them had this problem?
10.0 - Immediately kicks me out with message I'm up to date or gets stuck on findings without any errors (I'm on 4K78 as the CD was shipped with it, it's not latest).
10.1 - Internet connection works as its expected on 20 yo OS but yeah, Software Update just ignores me.
<img width="1680" alt="Zrzut ekranu 2021-12-22 o 14 04 40" src="https://user-images.githubusercontent.com/47083527/147097237-4666a73b-6fd7-49a3-bbd2-8b7caa4b77a6.png">
10.2 - Failed. Error occurred while checking. {Shows my correct timezone}
10.3 - Update server could not be found. Make sure you're network is configured properly, then try again.
<img width="1680" alt="Zrzut ekranu 2021-12-22 o 14 26 05" src="https://user-images.githubusercontent.com/47083527/147099719-8d1f5edb-4a8e-49aa-b364-b28f15c0cd8c.png">
10.4 - No issues.
10.5 - Error -1001 connection with server gets timed out, sometimes after deleting two plists it finds the updates but fails to install them because connection issues even tho network diagnostics is all green. Sometimes it's able to find updates after deleting com.apple.SoftwareUpdate.plist from /Library/Preferences/ (https://discussions.apple.com/thread/4752087) but fails to install them because of the same error with connection timed out.

> Do you have a way to test with a real USB network card passed to the VM via USB Sharing?

Unfortunately, no.

**Comment by conath** [comment]
In #3404 you wrote something to the effect of, you were able to get online in the VM by switching to emulated VLAN mode. Please close this issue if that is the case.

**Comment by mavethee** [comment]
> In #3404 you wrote something to the effect of, you were able to get online in the VM by switching to emulated VLAN mode. Please close this issue if that is the case.

Yeah, will do that, forgot, it's weird because QEMU used from command line applies that by default, UTM even if replicated in GUI setting doesn't work, needs to be added as QEMU argument.
