### ISSUE TITLE
[bug] [qemu] arm64/aarch64 missing .dylib

### ISSUE THREAD

**Issue by Marcinoo97** [utmapp/UTM#34]
UTM claims to support 30 processor architectures but arm64/aarch64 refused to start when I tried. 

![IMG_20200220_1837382](https://user-images.githubusercontent.com/2014596/74967511-08616800-5411-11ea-8162-0eb4d29c9893.jpg)

**Comment by iosdec** [comment]
@Marcinoo97 have you got os's working so far? if so could you provide a link to a working one and the setup you're using? not having any luck so far with anything

**Comment by ledwardchow** [comment]
It's loading the dylib filename from systemArchitecturesPretty instead of systemArchitectures.

x86 works because it's the same name by coincidence.

Replace line 158 of VMConfigSystemViewController.m:
        self.configuration.systemArchitecture = self.architectureLabel.text;
with:
        self.configuration.systemArchitecture = [UTMConfiguration supportedArchitectures][row];

**Comment by osy86** [comment]
Merged #37
