### ISSUE TITLE
Spinning Wheel Upon Adding Removable Drive

### ISSUE THREAD

**Issue by Tylast** [utmapp/UTM#3406]
I've searched all the open & closed issues.  Not seeing anything close.  When creating a W10 VM, I've narrowed the problem down to when I add the removable USB drive.  As soon as I do, I get the spinning wheel & I have to force quit UTM...everytime.  I've removed & reinstalled UTM...no effect.  No other configurations seem to matter...the result is the same every time.

**Configuration**
* UTM Version: 2.4.1 (40)
* OS Version: MacOS 12.1
* Apple Silicon

**Crash log** / No crash but I get a never-ending spinning wheel.  I recorded the error from the console....attached.  The error appears at line 94.     
[UTM Removable Drive error.txt](https://github.com/utmapp/UTM/files/7774953/UTM.Removable.Drive.error.txt)

**Debug log** / Enabled, but doesn't produce anything....grayed out.

**Upload VM** / plist file attached.     
[config.plist.zip](https://github.com/utmapp/UTM/files/7774958/config.plist.zip)

**Comment by conath** [comment]
Thank you for the logs, however there is no relevant error in there. The lines about bookmark data occur during normal operation of the app.

I can't reproduce the issue from the description you gave. Please either make a screen recording or write down a list of steps (step meaning mouse click, text typed, etc. in *detail*) so I can find the problem.

Here are the steps I took to attempt to reproduce the issue. I have attached the UTM file that is produced after taking the below steps.
[Windows 10.utm.zip](https://github.com/utmapp/UTM/files/7776239/Windows.10.utm.zip)


1. Open UTM
2. Click + to create new VM
3. Click "Start from scratch"
4. Type Windows 10
5. Click System tab
6. Change Architecture to aarch64
7. Click Drives tab
8. Click New Drive
9. Click Create
10. Click New Drive
11. Check Removable
12. Click Create
→ No infinite spinner

Other set of steps where I save before I create the drives:

1. Open UTM
2. Click + to create new VM
3. Click "Start from scratch"
4. Type Windows 10
5. Click System tab
6. Change Architecture to aarch64
7. Click Save
8. Select the VM in the list
9. Click Edit button
10. Click Drives tab
11. Click New Drive
12. Click Create
13. Click New Drive
14. Check Removable
15. Click Create
→ No infinite spinner

**Comment by Tylast** [comment]
Thanks conath.  I've downloaded the UTM you created & I get the spinning wheel as soon as I click on the VM.  Something must be wrong on my end.

**Comment by conath** [comment]
Oh I see, you mean the macOS cursor shows the  spinning animation. That might be a UTM bug or a system problem on your end.

**Comment by Tylast** [comment]
OK, I think I've gotten past the issue.  I followed a bit of guidance about adding drives [from this site](https://jensd.be/1533/windows/windows-11-arm-on-m1-based-macs-with-utm).  I wound up removing the special QEMU arguments & I finally got it to boot!!!  Installing now!  Thx.
