### ISSUE TITLE
Windows 10 (x64) always boots to troubleshooting screen on M1 Mac after install

### ISSUE THREAD

**Issue by kickblade** [utmapp/UTM#3411]
**Describe the issue**
I'm trying to emulate Windows 10 (x64) on my M1 Mac but it fails to start after install, and always displays the "Why did my PC restart?" troubleshooting screen. The OS says there is a problem that could be fixed by downloading an update but I never get the opportunity to install the spice tools, so it can't download any updates as I don't have any network access (it's the latest iso anyway AFAIK).

If I continue with the process anyway, it tries to get the OS ready to use but then always ends up restarting to the same screen:

<img width="1352" alt="Fail Screen" src="https://user-images.githubusercontent.com/39281961/147396625-3d74457c-5da3-4c8c-8e8a-a9ca297689e4.png">

I am wondering if there is some combination of cpu flags or QUME machine properties I need to enable for it to work? There are a lot of options and I am not sure if there are some minimum capabilities that I have missed. I have just enabled the features I want to test.

Any help or guidance would be amazing, thanks heaps :-)

NOTE: I have the Windows 11 (ARM) running and working as expected but I am wanting to emulate Windows 10 on intel 64-bit.

**Configuration**
* UTM Version: 2.4.1 (see attached pic of settings)
* OS Version: Win10_21H2_English_x64.iso
* Intel or Apple Silicon? Apple Silicon

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/7776440/debug.log)

**Upload VM**
[config.plist.txt](https://github.com/utmapp/UTM/files/7776439/config.plist.txt)

**Comment by conath** [comment]
You are using "Shared" network mode, which has previously been reported to cause problems with Windows x64 guests. Please change to "Bridged" mode and re-install. For recommended Windows 10 x64 on M1 install steps, please see my [video tutorial](https://www.youtube.com/watch?v=KsNoGPczavw).

**Comment by kickblade** [comment]
Thanks heaps for the info @conath, had a feeling it would have already been covered but couldn't find anything on it when I looked. Have a happy new year!

**Comment by daladim** [comment]
Thanks, this is working for me as well.
Could you add this [troubleshooting info](https://docs.getutm.app/guides/windows/#troubleshooting) in the "official directions"?

**Comment by crimist** [comment]
I encountered this as well and fixed it by using bridged network mode. Though I didn't have to reinstall Windows 11.

I opened a PR to add this to the troubleshooting docs: https://github.com/utmapp/docs.getutm.app/pull/54

**Comment by cellodude05** [comment]
This worked for me!! Thank you!!!!
