### ISSUE TITLE
UTM Freezes when VMs are Imported (also has a blank VM list)

### ISSUE THREAD

**Issue by reaowe** [utmapp/UTM#342]
![image](https://user-images.githubusercontent.com/11878353/82715665-32ba0000-9c62-11ea-922b-e750f1c9bd87.png)

Here are the VMs I had trouble showing up:

[](https://github.com/utmapp/vm-downloads/releases/download/ubuntu-14.04/Ubuntu-14.04.utm.zip)

[](https://github.com/utmapp/vm-downloads/releases/download/ubuntu-18.04/Ubuntu-18.04.utm.7z)

To reproduce the issue; tap on any of the VMs listed above in the Files app.

By the way I extracted the zip file of the first VM with the files app; I extracted the second VM which was a 7z file with iZip.

**Comment by ThatsNiceGuy** [comment]
Occurs on iPadOS 13.5 jailbroken with unc0ver 5.00, I installed the app using appinst with appsync unified.

**Comment by reaowe** [comment]
Hmm... happened to me with iPadOS 13.4.1 non jb with UTM. Installed with Altstore.

**Comment by osy86** [comment]
I’m not sure why this happens but it may be the same reason you can’t force kill UTM. For now, you shouldn’t open to import but just copy to UTM’s Document folder using Files app.

**Comment by ThatsNiceGuy** [comment]
I can’t add to UTM’s document folder in the Files app. It’s not there, even after making a blank VM. I’ll try to find it through Filza

**Comment by ThatsNiceGuy** [comment]
Even after adding directly to the documents folder Filza, the new VMs don’t appear in UTM, only the empty one I made previously . And the folder now appears in Files now appears but has the same contents what I put in Filza

**Comment by devsifi** [comment]
I had this issue, when I searched UTM in the Files app, there were two UTM folders, one empty, and the one UTM folder I made with the VM.
So I uninstalled it, deleted both folders and reinstalled UTM.
I created a blank/placeholder VM so that the UTM folder is visible in files, then copying my VMs over worked again.
