### ISSUE TITLE
'Invalid virtual machine configuration. “auxiliaryStorage” is nil.' for macOS Monterey Guest

### ISSUE THREAD

**Issue by AwlsomeAlex** [utmapp/UTM#3429]
**Describe the issue**
Attempted to create a macOS 12.1 Monterey VM. Downloaded latest IPSW restore image from [Mr. Macintosh's website](https://mrmacintosh.com/apple-silicon-m1-full-macos-restore-ipsw-firmware-files-database/), completed setup wizard, and was presented with "Invalid virtual machine configuration. “auxiliaryStorage” is nil."

**Configuration**
* UTM Version: 3.0.0 (Beta)
* OS Version: macOS 12.1 Monterey
* Intel or Apple Silicon? Apple Silicon (M1 Pro)

**Crash log**
Nothing crashed

**Debug log**
VM wasn't created.

**Upload VM**
VM wasn't created.

**Comment by AwlsomeAlex** [comment]
Looks like it was fixed with 8536251c. Closing.

**Comment by driedener** [comment]
It seems the issue is also in the newest version: Version 3.0.0 (41)

**Comment by Darkomen78** [comment]
I got the exact same error with Beta 3.0.0 (41) version, the lastest one on the release page.

I'm on MBP M1 Pro, macOS 12.1

**Comment by emersonian** [comment]
Same here. Up for a new release with the fix?

**Comment by osy** [comment]
You can get a dev build from https://github.com/utmapp/UTM/actions/runs/1644813856

**Comment by Darkomen78** [comment]
Thanks @osy it's good with this build !
