### ISSUE TITLE
Show placeholder VM details view when a pending VM is selected

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#3432]
This view could contain additional information about the VM download progress and another option to cancel the download.
<img width="912" alt="What happens when you click a pending VM? Currently nothing." src="https://user-images.githubusercontent.com/12073163/147861154-4034c456-e4be-484a-897a-502e4e3cbef2.png">

**Comment by conath** [comment]
I came up with this little popover view that shows you some stats about the download process, and includes a cancel button.

![UTM-pending-vm-details](https://user-images.githubusercontent.com/12073163/148664500-efb78a7b-8347-4458-8a6b-884ced219561.jpg)

**Comment by brunocastello** [comment]
> I came up with this little popover view that shows you some stats about the download process, and includes a cancel button.
> 
> ![UTM-pending-vm-details](https://user-images.githubusercontent.com/12073163/148664500-efb78a7b-8347-4458-8a6b-884ced219561.jpg)

For a standard UI, you might want to copy the design used by Safari when downloading. The popup has a bit different design.

<img width="538" alt="iu" src="https://user-images.githubusercontent.com/23453202/149062494-d273d243-9ef1-475b-9e85-547408f26170.png">

**Comment by osy** [comment]
I think the problem is that it won’t fit because the sidebar is pretty narrow.

**Comment by conath** [comment]
My design is different from Safari because we have a list of downloads in the sidebar. Clicking on on a Download (pending VM) simply reveals more details about this specific download instead of a list like in Safari. The popover could technically be wider than the sidebar but I find that looks very odd and there’s no use in making it wider right now.

Above screenshots are outdated. The as of now final design is closer to Safari and shown here: https://github.com/utmapp/UTM/issues/3437#issuecomment-1008311039
