### ISSUE TITLE
Windows 3.1 mouse

### ISSUE THREAD

**Issue by ecstaticax** [utmapp/UTM#3436]
**Configuration**
* UTM Version: latest not-beta
* OS Version: latest mac
* Intel or Apple Silicon? Silicon

I installed dos 6.2.2 + windows 3.1. It runs, there’s mouse arrow, but I cannot move. What may be?
Thanks and regards

**Comment by UrkiMimi** [comment]
Click on the capture mouse button.
<img width="58" alt="Screen Shot 2022-01-03 at 9 49 59 AM" src="https://user-images.githubusercontent.com/74517821/147951057-68b572ce-d819-44e9-8d75-c7594d1e7d5d.png">

**Comment by ecstaticax** [comment]
Thanks!
