### ISSUE TITLE
Not seeing a way to move the UTM toolbar in VM on iPad OS

### ISSUE THREAD

**Issue by SugarRayLua** [utmapp/UTM#3438]
Recent UTM release highlights the ability to use a new UTM toolbar while in a VM that can be pinned to any side of the display. In the release link demonstrating this feature there is a small arrow icon that one is supposed to drag to the side of the display that one wishes to pin the toolbar to. However, I do not see that new arrow on my toolbar on the new UTM release; instead my toolbar appears the same as previous releases and does not seem movable. 

Thanks!

**Configuration**
* UTM Version: 3.0.0 beta
* OS Version: 15.2
* Device Model: iPAD M1
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? Signulous

**Comment by osy** [comment]
Can you clarify what you're seeing with a screenshot?

**Comment by SugarRayLua** [comment]
Sure, @osy:  attached. 
![IMG_0802](https://user-images.githubusercontent.com/76857619/148633013-f5da2bfe-4b30-4820-aa38-275aa5c58dec.jpeg)

**Comment by osy** [comment]
Are you certain you're running 3.0 on iOS 15? Unless you're spoofing your OS version, that old toolbar shouldn't even be loaded.

**Comment by SugarRayLua** [comment]
Yes, understood. I thought it looked the same and wondered the same thing—is there a way to check inside of the VM or from the UTM settings on the iPAD? I double checked that I downloaded the correct UTM.ipa from the UTM releases site and it matches the app size for 3.0 (198.1 MB).

**Comment by osy** [comment]
Not sure but one thing you can check is to see if creating a new ARM64 virt machine shows up as virt-6.2 or 6.1

**Comment by SugarRayLua** [comment]
6.1
May not be 3.0 then. I wonder if something if it is not retrieving the correct .ipa for download? Strange though that ipa size is different than my prior downloads and matches what it says is 3.0 on releases site on Github. Any other links you could send me to download in case something not working wright on Github releases for the iOS version? Could also see if anyone else on iOS has got the right .ipa downloaded. Thanks.

**Comment by SugarRayLua** [comment]
I’ll try downloading and installing again also just to me sure.

**Comment by SugarRayLua** [comment]
Sorry, @osy— it may be my mistake. I think I was downloading the V3.0 pre-release. I’ll retry agin now.

**Comment by SugarRayLua** [comment]
Unfortunately, @osy that didn’t work— I just confused myself. The “release” I just tried to download was actually the older stable UTM 2.4 release. It looks like the UTM 3.0.ipa pre-release is the most current release which is what I previously downloaded and now re-downloaded again and still new ARM64 VM only shows up to QEMU 6.1. Perhaps incorrect iOS UTM version on the website link for download? Happy to keep troubleshooting at your convenience. Have a good night.

**Comment by osy** [comment]
Did you try deleting the app and installing fresh?

**Comment by conath** [comment]
For reference, here is how to move the UTM 3.0 toolbar on iPadOS 14+. You tap and hold on the arrow that shows and hides the bar, then while it is enlarged swipe to move it to another corner. 

https://user-images.githubusercontent.com/12073163/148661764-6304d204-9cc4-4475-994e-8533cf2649d1.mov

**Comment by osy** [comment]
Also FYI I added a version info display to system settings page for UTM iOS on v3.0.1.

**Comment by SugarRayLua** [comment]
Thanks, @osy and @conath.

Thank you also for adding a version number to the system settings on UTM iOS— that will help future troubleshooting. 

You were correct: I was able to install V 3.0 properly after I first deleted my previous installed UTM on my iPad. Strange in that I never had to delete UTM on my iPad before to install a new version— all the previous versions just installed over the previous versions. The nice thing about that was that it would keep my VM intact while updating versions. Since I had to delete UTM to install V 3.0, I first needed to save my VM to the cloud which took a little while (already a 30GB VM) and then open it up after installing the new V 3.0 UTM.

https://user-images.githubusercontent.com/76857619/148666033-2f140789-572a-44bd-8a09-c55d0ae0aab1.mp4


Unfortunately, the UTM toolbar doesn’t seem to be working as smoothly with iOS 15 and Debian Linux; I see the arrow of the movable toolbar briefly but then it goes away, and I can’t get it back. At times, I am able to move it but not consistently and when I do, it often vanishes soon after I move it. I then need to enlarge the display manually with finger zooming the screen. Not sure if has anything to do with fact that I’m using a VM created with prior UTM version? I’ve attached a video showing what happens.



PS,
On a side note, I also really do like the new VM wizard set up— very helpful and intuitive.

Unfortunately, unlike, Conath on his Mac, I seem to have lost a little OpenGL ability despite the Virgl and Angle upgrade (e.g. old graphics apps [OpenGL 1.0?] no longer work: rgl app in R no longer displays anything in OpenGL window, and I just get a purple flash when trying to open old glhack game). Other and newer OpenGL apps work about the same. Will stay on V 3.0 for now to help troubleshoot any iOS 15 iPad issues but then may go back to prior release on iPad until further update.

**Comment by conath** [comment]
@SugarRayLua You can prevent VMs from getting deleted by moving them to an “On My iPad” folder in Files. No need to upload to iCloud.

**Comment by SugarRayLua** [comment]
@conath - thanks for letting me know!

**Comment by osy** [comment]
> Thanks, @osy and @conath.
> 
> Thank you also for adding a version number to the system settings on UTM iOS— that will help future troubleshooting.
> 
> You were correct: I was able to install V 3.0 properly after I first deleted my previous installed UTM on my iPad. Strange in that I never had to delete UTM on my iPad before to install a new version— all the previous versions just installed over the previous versions. The nice thing about that was that it would keep my VM intact while updating versions. Since I had to delete UTM to install V 3.0, I first needed to save my VM to the cloud which took a little while (already a 30GB VM) and then open it up after installing the new V 3.0 UTM.
> 
>  RPReplay_Final1641691836.mp4 
> 
> Unfortunately, the UTM toolbar doesn’t seem to be working as smoothly with iOS 15 and Debian Linux; I see the arrow of the movable toolbar briefly but then it goes away, and I can’t get it back. At times, I am able to move it but not consistently and when I do, it often vanishes soon after I move it. I then need to enlarge the display manually with finger zooming the screen. Not sure if has anything to do with fact that I’m using a VM created with prior UTM version? I’ve attached a video showing what happens.
> 
> PS, On a side note, I also really do like the new VM wizard set up— very helpful and intuitive.
> 
> Unfortunately, unlike, Conath on his Mac, I seem to have lost a little OpenGL ability despite the Virgl and Angle upgrade (e.g. old graphics apps [OpenGL 1.0?] no longer work: rgl app in R no longer displays anything in OpenGL window, and I just get a purple flash when trying to open old glhack game). Other and newer OpenGL apps work about the same. Will stay on V 3.0 for now to help troubleshoot any iOS 15 iPad issues but then may go back to prior release on iPad until further update.

It's expected that the button disappears if the screen hasn't been touched in 30 seconds. Are you not able to get it back by touching the screen?

**Comment by conath** [comment]
> It's expected that the button disappears if the screen hasn't been touched in 30 seconds. Are you not able to get it back by touching the screen?

It seems to only come back when I tap the location where the button was before it disappeared.

**Comment by osy** [comment]
Oh that’s a bug then. I’ll fix it.

**Comment by SugarRayLua** [comment]
Thank you.

**Comment by osy** [comment]
@conath @SugarRayLua To be clear, when you two say tap you mean with your finger on the screen? The interaction assertion is only triggered for screen touches, not pencil or touchpad.

Also I noticed that the dim view over a black background is too dim so I've changed the opacity from 0.2 to 0.4. Hopefully that will make the button more obvious.

**Comment by conath** [comment]
@osy Yes tapping with my finger, not pencil or cursor.

**Comment by osy** [comment]
Can you test with 3.0.2? I think maybe the issue was the button was too dim.

**Comment by SugarRayLua** [comment]
Hi, @osy. Sorry, I should have written you back— I did test it this week with 3.0.2 and it works fine, and yes, it might have been too dim before. Now the bottom gradually fades when not in use, but I can still see it to tap on it.

**Comment by conath** [comment]
Just tried 3.0.2 as well. The toolbar button is now visible while in the first fade out stage and it appears reliably when I tap the screen. 

It is noteworthy that the button does not respond to taps when faded away completely. I assume this is how it is supposed to work.

**Comment by osy** [comment]
Yes, and it's supposed to ignore touchpad and pencil inputs.
