### ISSUE TITLE
Input problem on Windows XP

### ISSUE THREAD

**Issue by ToaruTaikun** [utmapp/UTM#344]
When I'm using legacy mode under XP , I can have full access to the keyboard but unable to use mouse normally. But when I disabled legacy mode, both keyboard and mouse became unable to use.

**Comment by ToaruTaikun** [comment]
Both software and external keyboard have that problem.

**Comment by osy86** [comment]
Can you post a screenshot of your UTM cursor settings?

**Comment by osy86** [comment]
@ToaruTaikun post your `.utm` or `config.plist` and screenshots of your UTM settings otherwise I will close this for not enough information.
