### ISSUE TITLE
Virtualization is not supported on your system.

### ISSUE THREAD

**Issue by tolikes** [utmapp/UTM#3442]
![AB66F7EA-6AF1-443A-8302-DE569CD7704A](https://user-images.githubusercontent.com/6198417/148023243-ee0fee11-1ab0-4cca-a432-d495275b39e5.png)

iPhone 11 iOS 14.6

UTM 3.0.0 beta

**Comment by osy** [comment]
Not a bug.

**Comment by sergeycherepanov** [comment]
@osy could you please tell, which devices supports virtualization? I can't find this on the site. 

Does any ios/ipad supports it? Or it's only m1 based feature.

**Comment by osy** [comment]
Macs only

**Comment by m-a-v** [comment]
But technically, would it be possible to use virtualization on iOS? I think this could be quite interesting with the iPad Pro which has the M1 chipset.

**Comment by lifesnotfair0** [comment]
You see the problem is the people that created utm have no heart. Thats why noone can virtualize with utm. I suspect one has to pay money to efficiently use utm but their site is unc,lear on how one would purchase it. They also say its open source software but whos it available to, martians? it didnt work for me.

**Comment by rullinoiz** [comment]
> But technically, would it be possible to use virtualization on iOS? I think this could be quite interesting with the iPad Pro which has the M1 chipset.

virtualization.framework is only available on mac AFAIK, it's most likely impossible to port to ios

**Comment by osy** [comment]
Apple can always introduce it at WWDC 🤞

**Comment by DumbGameMaker** [comment]
unlikely, this is apple. releasing that for iOS (or more likely iPadOS) would probably be accompanied by some slideshow of new virtualization apps
