### ISSUE TITLE
Please update ubuntu installation guide.

### ISSUE THREAD

**Issue by paulpaul1076** [utmapp/UTM#3454]
**Describe the issue**
I followed an installation guide from here https://mac.getutm.app/gallery/ubuntu-20-04 and network wasn't working, I resolved it as described here https://apple.stackexchange.com/questions/434799/utm-ubuntu-linux-installation-says-network-is-unreachable I think you need to specify this in the guide.

**Configuration**
* UTM Version: Version 2.4.1 (40)
* OS Version: host OS - macOS Monterey 12.1, guest OS - ubuntu 20.04.
* Apple Silicon

Also this step didn't work (I would get "tasksel apt-get failed (100)"):

$ sudo tasksel install ubuntu-desktop

Until I did "sudo apt-get update".

Thanks.

**Comment by conath** [comment]
The guide should also be updated with a section about the process in UTM 3.0.0.

**Comment by Daniyal-Warraich** [comment]
Also, you could do `sudo apt install ubuntu-desktop`, which worked better in my opinion.

**Comment by astroboylrx** [comment]
> The guide should also be updated with a section about the process in UTM 3.0.0.

Yes, please do so. The new interface may make sense to people who is familiar with using qemu directly, but not for others.

**Comment by osy** [comment]
https://mac.getutm.app has been updated along with the guide.

**Comment by astroboylrx** [comment]
If I check "Use Apple Virtualization", then the interface to choose "Boot ISO Image" disappears. Instead I need to choose Linux Kernel and a few other things. Are there documentations for using Apple Virtualization?
(Sorry if I misunderstand something) If I choose an ISO image and do not use "Apple Virtualization", does that mean the virtualized Linux will not use the Hypervisor.Framework? If so, what kind of virtualization is being used?
Thanks in advance.

**Comment by osy** [comment]
Yes, Apple Virtualization does not support booting from ISOs. TBH, I wouldn't use Apple Virtualization for Linux (it's provided as an option for developers and power users).

**Comment by ktprograms** [comment]
@astroboylrx 

>does that mean the virtualized Linux will not use the Hypervisor.Framework?

No, it means that it will use QEMU with Hypervisor.framework.

Using Apple Virtualization means using [Virtualization.framework](https://developer.apple.com/documentation/virtualization/)

**Comment by astroboylrx** [comment]
I see. Thank you both very much for the replies and explanations!
