### ISSUE TITLE
3d acceleration on windows

### ISSUE THREAD

**Issue by muratdk23** [utmapp/UTM#3459]
Any plans to add 3d acceleration on windows guest?

**Comment by conath** [comment]
UTM provides 3D graphics support via the [virgl3d](https://virgil3d.github.io) graphics card. (#161) 

The missing piece to make 3D acceleration work in Windows is a suitable Windows driver  for this graphics card that supports modern 3D features like DirectX and Vulcan. This work is beyond the scope of the UTM project.

**Comment by aisobe** [comment]
Then how did Parallels do it?

**Comment by conath** [comment]
@aisobe By investing lots of money into creating their own proprietary graphics layer (OpenGl3 & DirectX11 to Metal).

I decided to look for the open source software Parallels use and found [this list](https://www.parallels.com/about/legal/licensing/). It doesn’t mention any DirectX related OSS so I assume it’s proprietary.

**Comment by mgrossu** [comment]
https://github.com/virtio-win/kvm-guest-drivers-windows/pull/943

**Comment by PerplexedTheta** [comment]
Exciting stuff -- looks like we might not be so far away from this goal!
