### ISSUE TITLE
arm64 ‘guest disabled display’

### ISSUE THREAD

**Issue by hjh70526** [utmapp/UTM#346]
I find this problem when booting armbian.
It seems this problem did not appear in 刘’s arm vison.

**Comment by osy86** [comment]
Can you upload the .utm? Also link to “ 刘’s arm version”?

**Comment by hjh70526** [comment]
Thanks for your help，here is the qcow2 image and 刘’s arm vison and compare video
kali arm64 image: https://hjh666.xyz/software/system/kali%20arm.qcow2.gz

刘’s arm vison: https://hjh666.xyz/for-osy86/UTM-ARM-resigned.ipa

This video shows thebug‘guest disabled display’: https://hjh666.xyz/for-osy86/kali%20arm64%20on%20latest%20vison%20of%20UTM%20with%20%E2%80%98QEMU-EFI%E2%80%99%20BIOS.mp4

This video shows kali correctly boot on 刘‘s vison: https://hjh666.xyz/for-osy86/kali%20arm64%20on%20%E5%88%98%E2%80%99s%20arm%20vison.mp4

I made this image by myself,maybe my image‘s bad(⌒▽⌒)

**Comment by osy86** [comment]
Please provide the source code for 刘’s arm version. That’s the only way I can fix this. If you don’t have it contact them for it.

**Comment by hjh70526** [comment]
Thank you again
Here is the code: https://hjh666.xyz/for-osy86/code.zip

**Comment by osy86** [comment]
Can you add `-device virtio-gpu` as an Additional Argument in System settings?

**Comment by hjh70526** [comment]
I tried to add ‘-device virtio-gpu’ when I realize this problem,but it did not work,still showing ‘Guest disabled display’.

**Comment by osy86** [comment]
@hjh70526 I can't get your VM to boot. Can you post your settings or config.plist?

**Comment by hjh70526** [comment]
Of course
Latest UTM config: https://hjh666.xyz/for-osy86/config-utm.zip
I use ‘QEMU_EFI.fd’  in package as BIOS

刘’s arm vison config: https://hjh666.xyz/for-osy86/config-arm.zip
It do not need to set BIOS manual

**Comment by hjh70526** [comment]
It was my first time to use uefi on arm64,so it need ‘fs0:\efi\debian\grubaa64.efi’ to open grub

**Comment by osy86** [comment]
I am able to boot with your config and disk images. Are you on 1.0-rc3?

**Comment by osy86** [comment]
@hjh70526 Please confirm that you are on 1.0-rc3

**Comment by hjh70526** [comment]
I am sure I am on 1.0-rc3 (build 58),but using Js-john’s Chinese transltion
And I foget to tell you that VM can correctly boot in Console Mode,but showing ‘guest disabled display’ when using Full Graphics
I asked Js-john for help yesterday,but Js said he can not boot in Full Graphics either
Sorry that I send config without problem to you
But ‘guest disabled display’ problem is truly appear in Full Graphics

**Comment by osy86** [comment]
I changed to full graphics and I see the UEFI boot logo.

**Comment by osy86** [comment]
Are you sure there's no other code changes? I replaced `argsFromConfiguration` with your code and changed a few lines to get it to work with the latest UTM changes (you can check the code in the attachment). I see the same issue.
[UTMQemuSystem.m.txt](https://github.com/utmapp/UTM/files/4703499/UTMQemuSystem.m.txt)

**Comment by osy86** [comment]
Oh! Lol, if you just wait on that message for a while, it disappears and boots up.

**Comment by hjh70526** [comment]
That is the lastest full code before 刘 close up arm-vison
I waited about half an hour,still stuck on that massage
My device is iPad2017,maybe it is too old to run UTM XD

**Comment by zwerdna** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1661288#c22

**Comment by osy86** [comment]
@hjh70526 Can you try one of the Debian premades in https://getutm.app/vms/ these all show "Guest Disabled Display" for me but after a few minutes it boots up.

**Comment by osy86** [comment]
Closing due to lack of response. Seems issue is fixed.
