### ISSUE TITLE
UTM 3.0.1 (Beta) has no option to delete a disk

### ISSUE THREAD

**Issue by ktprograms** [utmapp/UTM#3461]
**Describe the issue**
Prior to UTM 3.0.0, there was a delete button in the drives tab. This has been removed in UTM 3.0.0.

Also there should be an option to not create a disk in the wizard (for example when using Apple Virtualization, if you already have a rootfs disk, you don't need another disk)

**Configuration**
* UTM Version: 3.0.1 (Beta)
* OS Version: macOS 11.6
* Intel or Apple Silicon? M1 Air

**Comment by osy** [comment]
Does the delete button not appear if you click on the disk?

**Comment by ktprograms** [comment]
No
<img width="1012" alt="Screenshot 2022-01-10 at 10 44 24 AM" src="https://user-images.githubusercontent.com/71804605/148712766-4e3e5f6b-f68b-4b6a-90fd-b0eb7e1da5bb.png">

**Comment by osy** [comment]
Seems like a SwiftUI issue on macOS 11

**Comment by ktprograms** [comment]
I'll take a look at it.

BTW where in the code are VM drives actually created when using virtualization.framework for linux? (Meaning the part that actually makes the file on disk)

**Comment by osy** [comment]
Also https://github.com/utmapp/UTM/commit/60ac313d3e28854e83531f2c7ecf511f7e4284e6

**Comment by ktprograms** [comment]
@osy Could skipping the disk creation step be done even if a rootfs isn't selected? It's possible to have an entire Linux system running in the initramfs with no disk.

Either with a checkbox on the vmlinuz selection page, or change the code in the disk creation step that if `0` is entered, skip the creation?

**Comment by ktprograms** [comment]
Should the drive modification buttons be completely hidden if a drive isn't selected?
<img width="1012" alt="Screenshot 2022-01-10 at 11 13 47 AM" src="https://user-images.githubusercontent.com/71804605/148714385-1003e45c-ba25-40b2-98a5-48d81da26d3b.png">

**Comment by osy** [comment]
> Should the drive modification buttons be completely hidden if a drive isn't selected?
> 
> <img width="1012" alt="Screenshot 2022-01-10 at 11 13 47 AM" src="https://user-images.githubusercontent.com/71804605/148714385-1003e45c-ba25-40b2-98a5-48d81da26d3b.png">

No since how else will you create a drive if there's no drives.

**Comment by ktprograms** [comment]
> No since how else will you create a drive if there's no drives.

I meant the Delete and Move buttons, sorry

**Comment by osy** [comment]
> It's possible to have an entire Linux system running in the initramfs with no disk.

It's possible but is that a real use case?

**Comment by osy** [comment]
> > No since how else will you create a drive if there's no drives.
> 
> 
> 
> I meant the Delete and Move buttons, sorry

That's how it is on macOS 12. SwiftUI bug prevents us from conditionally showing the buttons.

**Comment by ktprograms** [comment]
> That's how it is on macOS 12. SwiftUI bug prevents us from conditionally showing the buttons.

Oh, I see. Thanks

**Comment by ktprograms** [comment]
> It's possible but is that a real use case?

Not really, I guess. Nevermind then.

**Comment by ktprograms** [comment]
@osy https://github.com/utmapp/UTM/commit/60ac313d3e28854e83531f2c7ecf511f7e4284e6 wouldn't be a good idea because there currently isn't anywhere to specify a ISO image, so the ISO would need to be in the rootfs field, which would cause drive creation to be skipped, even though it would be needed in that case.

I think the best solution would be to have a field for a ISO image, which would additionally be marked as read only in the VM config (the `readOnly` property in `VZDiskImageStorageDeviceAttachment`)

**Comment by osy** [comment]
I don't think Apple virtualization supports emulating a CD/DVD drive and it only works on distributions that happen to have hybrid ISOs. It's expected that you pass in a pre made rootfs image.

FWIW I haven't been able to get Ubuntu installer to work because it fails at the kernel install because it doesn't recognize the machine type.

**Comment by ktprograms** [comment]
@osy If I download the [Alpine Linux 3.15 virt aarch64 ISO](https://dl-cdn.alpinelinux.org/alpine/v3.15/releases/aarch64/alpine-virt-3.15.0-aarch64.iso) and extract the `vmlinuz` and `initramfs` from it, I can then use the whole ISO as the rootfs.

I agree that Apple virtualization doesn't emulate a CD/DVD drive, but I think making the drive read only would be good.

**Comment by osy** [comment]
Maybe open a new ticket with this information and I'll come back to it. Thanks.
