### ISSUE TITLE
Can't create Mac vm on TestFlight

### ISSUE THREAD

**Issue by jawshoeadan** [utmapp/UTM#3462]
**Describe the issue**
When I try creating a macOS VM using the TestFlight, I get this error: "Internal Virtualization error. Installation service returned an unexpected error."

**Configuration**
* UTM Version: 3.0.1 Testflight
* OS Version: 12.1
* Intel or Apple Silicon? Apple Silicon

**Comment by osy** [comment]
Does the DMG version work fine?

**Comment by jawshoeadan** [comment]
Yes, just the TestFlight version doesn’t work. But I assume that would be the same situation on the App Store so just wanted to let you know

**Comment by osy** [comment]
I found the issue, I accidentally signed the app store version with the wrong entitlements.

**Comment by osy** [comment]
@jawshoeadan please check that it’s fixed in TestFlight 3.0.2

**Comment by jawshoeadan** [comment]
Yes it is fixed
