### ISSUE TITLE
Cannot run UTM in iOS 15.2 Simulator from Xcode 13.2.1

### ISSUE THREAD

**Issue by ktprograms** [utmapp/UTM#3463]
**Describe the issue**
When I run UTM from Xcode, it has a `SIGABRT` with the error:
```
dyld[37724]: symbol not found in flat namespace '_strcmp'
symbol not found in flat namespace '_strcmp'
```
This only happens when using iOS 15 simulators (happened since the first release of the iOS 15 sims, still happening with iOS 15.2). UTM launches and runs perfectly fine on the iOS 14.5 simulators.

**Configuration (required)**
* UTM Version: 3.0.1 (Beta), from Git commit https://github.com/utmapp/UTM/commit/60ac313d3e28854e83531f2c7ecf511f7e4284e6
* OS Version: iOS 15.2 Simulator, macOS 11.6 for development
* Device Model: iPhone 13 mini Simulator
* Xcode Version: 13.2.1 (Build number 13C100)

**Comment by osy** [comment]
Yeah, I've noticed this too. Haven't been able to figure out why... It only happens in iOS 15 simulator.

**Comment by ktprograms** [comment]
Also it happens before any UTM code.
<img width="1387" alt="Screenshot 2022-01-11 at 9 34 18 AM" src="https://user-images.githubusercontent.com/71804605/148865836-2ed43a3f-4c0e-4423-9b6f-3cfaff2ca7be.png">
Maybe could you please help to file an issue with Apple?

**Comment by osy** [comment]
I have not gotten time to file an issue yet because I haven't found a way to reproduce it minimally. If you can help with that, it would be appreciated.

**Comment by ktprograms** [comment]
I'm thinking of trying to compile a simple C program that makes use of `strcmp` as a shared library and link it in an iOS project, but I'm not sure how to compile the library as shared **and** make it into a Framework.

**Comment by osy** [comment]
I think if you make framework project it's the same as a shared library.

**Comment by ktprograms** [comment]
I tried making a simple framework that uses `strcmp`, but that runs fine when embedded into an iOS app.

I even tried just copying some of the frameworks from the `sysroot-ios_simulator-arm64` (without calling any functions from them), but it still runs fine.

**Comment by osy** [comment]
I narrowed down the problematic library to `libjson-glib-1.0.0`. If you add all the dependencies except for that in a brand new project it works. But adding `libjson-glib-1.0.0.dylib` or `json-glib-1.0.0.framework` causes the simulator to crash with the `_strcmp` error.

**Comment by osy** [comment]
Submitted a bug report with the following example project

[test_project.zip](https://github.com/utmapp/UTM/files/7849444/test_project.zip)
