### ISSUE TITLE
wizard(apple): proper support for ISO disk drives

### ISSUE THREAD

**Issue by ktprograms** [utmapp/UTM#3472]
If I download the [Alpine Linux 3.15 virt aarch64 ISO](https://dl-cdn.alpinelinux.org/alpine/v3.15/releases/aarch64/alpine-virt-3.15.0-aarch64.iso) and extract the vmlinuz and initramfs from it, I can then use the whole ISO as the rootfs.

This causes a problem because https://github.com/utmapp/UTM/commit/60ac313d3e28854e83531f2c7ecf511f7e4284e6 makes it that putting a ISO in the rootfs field will cause a disk image to not be created, which is wrong.

I propose adding a ISO field that will also be marked as read only, since you can't write to an ISO.

(followup to https://github.com/utmapp/UTM/issues/3461#issuecomment-1008593307)

**Comment by osy** [comment]
The one thing I don't like about this is that it makes the wizard flow more complicated for Linux now. Please test and try to see if any edge cases break the wizard. Thanks.

**Comment by ktprograms** [comment]
@osy since the current code isn't making it read only anyway, I think the simplest thing to do is to revert this commit and just add a checkbox for `Skip creation of disk`.

FYI If you do `git rebase -i HEAD~2` and in the editor change the word `pick` to `drop` on line with `007f9d4`, that will remove the commit without creating another revert commit. (you will have to force push after that)

**Comment by osy** [comment]
8eacd8f now makes it read-only. Is that all?

**Comment by ktprograms** [comment]
Also a `HStack` around the `Browse` and `Clear` buttons for the `Boot ISO Image` is needed, thanks

I'll do some proper testing and let you know

**Comment by ktprograms** [comment]
@osy It's working fine so far, but it seems that https://github.com/utmapp/UTM/commit/60ac313d3e28854e83531f2c7ecf511f7e4284e6 doesn't work properly. It skips the disk creation wizard step, but a 64 GB disk is still created.

**Comment by osy** [comment]
Fixed in ceb6f91
