### ISSUE TITLE
Use SwiftTerm for QEMU backend

### ISSUE THREAD

**Issue by osy** [utmapp/UTM#3473]
Currently we use hterm.js for QEMU backend and SwiftTerm for Apple backend. We should switch to SwiftTerm across both backends for both macOS and iOS. The only complication is that SwiftTerm requires iOS 13 and we support down to iOS 11. So there's two possibilities:

1. We drop support for iOS 11 and iOS 12, which will free up the codebase as well. However, there still seems to be some people who are on an older jailbreak or a device that doesn't support iOS 13.
2. We drop console mode from < iOS 13, which depends on how many people on < iOS 13 actually use console mode.
3. We keep both hterm.js for < iOS 13 and use SwiftTerm for iOS 13+. This is the most user friendly but will add even more complexity to the codebase (which is already swelling with conditional code for different platforms and configurations).

Calling for comments on the options above.

**Comment by conath** [comment]
I say 1. - we should drop iOS 11/12 in 3.0 in favor of easier maintainability. 

The last compatible version should be made available where possible and maybe a final bugfix update could be released for version 2 before 3 lands. (not sure if needed)

One interesting thought I had just now: maybe we should add some anonymous telemetry to the app so we can make more informed decisions about these kinds of issues. I would suggest [TelemetryDeck](https://github.com/TelemetryDeck/SwiftClient) since you have full control over the data it sends.

**Comment by adespoton** [comment]
I was going to say 2, until I read through the outstanding issues, and realized that there are other issues and feature requests that are also incompatible with 13 and below.  

And the reality is, devices that are limited to iOS 11/12 are also RAM and CPU-limited.  I've tried UTM on both and it's "usable" for running a lightweight BSD or Linux without X (so, console mode only), and possibly Windows XP, but it's not really usable for anything more recent, and even struggles to run Mac OS 9.  The additions in 3.x and later are going to make this situation worse, not better, for iOS 11/12 users, so it would make more sense in my opinion to limit support to version 2 with bugfixes.

Having said that, probably worth gathering some degree of telemetry from active users to see how many people are actively using UTM on iOS 11/12.  If not via TelemetryDeck, then by a feedback form in a new release of 2.x.  Anyone not willing to upgrade to the new release and fill out the feedback form is unlikely going to complain about 3.x dropping support.

**Comment by osy** [comment]
Also it’s not like we’ll pull the downloads for older versions. It’s just that it won’t get any new updates which is relevant only to the QEMU backend.
