### ISSUE TITLE
macOS: Allow using UTM bundles from anywhere on the filesystem (i.e. don't move it inside the container)

### ISSUE THREAD

**Issue by diamondsw** [utmapp/UTM#3479]
When opening a UTM bundle that is outside the container (~/Library/Containers/UTM/Data/Documents), UTM automatically copies it there before running it. I'd prefer to keep them elsewhere (for instance, a single folder with UTM, Parallels, and other VM files so I can exclude from Time Machine). Is this possible within the sandboxing requirements on macOS?

**Comment by osy** [comment]
Duplicate of #1205
