### ISSUE TITLE
macOS: Better handling of "main" window when a VM isn't running

### ISSUE THREAD

**Issue by diamondsw** [utmapp/UTM#3480]
After opening a VM, I typically close the "main" UTM window that lists VMs. However, this means when I close a VM it automatically quits UTM, and it means there's no longer any way to adjust the settings of any VM. Frequently I'd like to change settings for the VM, open a different one, etc, which then means I have to quit and relaunch the app.

Two things may be useful to address this:
1. Add a menu item to open the "main" window again if it's closed (for instance File > Virtual Machines). This would be useful in any event if the user closed the window to tidy up the screen, but later needs to create/adjust a virtual machine.
2. When the last VM closes, don't quit the app, allowing for opening the main window and continuing on in another machine (or adjusting the settings of a machine). Alternatively, perhaps open the window automatically when the last VM exits so it's clear what actions are available.

**Comment by osy** [comment]
My understanding was that this was added in 6437ad7a74346bcee6c6715e7fef348000daab20 due to some SwiftUI bug where it wasn't possible to open the main window after it was closed. However, that seems to be fixed in macOS 12.

**Comment by ktprograms** [comment]
@osy Would you be okay with making it a Preference option whether to quit after the last window is closed? I find it quite convenient that UTM automatically quits after I shut down and close my VM.

**Comment by osy** [comment]
Sure can you open a new ticket.
