### ISSUE TITLE
Adjust memory allocation on sample Windows XP VM

### ISSUE THREAD

**Issue by diamondsw** [utmapp/UTM#3482]
The sample Windows XP VM is pre-configured with 512MB memory. After applying all updates to current, this is no longer sufficient to boot, and it will crash very shortly into the boot process. I'd recommend updating this to 1GB as a modern minimum.

**Comment by conath** [comment]
I believe the template is intended to work on iOS, where memory available to UTM is very limited. You are always invited to adjust the settings yourself after using the template as a starting point.

Which updates are you referring to, by the way?

**Comment by diamondsw** [comment]
Ah, that makes sense. The final batch of .Net updates tripped it. To get up-to-date there were over 200 updates post-SP3.

**Comment by conath** [comment]
Thanks for the information. I will close this for now and if others run into this frequently we can re-open later.
