### ISSUE TITLE
ui: add preference for `applicationShouldTerminateAfterLastWindowClosed`

### ISSUE THREAD

**Issue by ktprograms** [utmapp/UTM#3483]
I find it quite convenient that UTM automatically quits after I shut down and close my VM.

**Comment by conath** [comment]
I wonder why this is not the default setting right now. It makes sense to me that if you closed the UTM main window and then close the last VM, UTM would quit.

**Comment by osy** [comment]
> I wonder why this is not the default setting right now. It makes sense to me that if you closed the UTM main window and then close the last VM, UTM would quit.

Just can't satisfy everyone smh
