### ISSUE TITLE
Follow changes in sound output device

### ISSUE THREAD

**Issue by phirestalker** [utmapp/UTM#3488]
When I connect my Bluetooth headset, most Mac apps will be able to output sound to it even if they are already running. The same applies when they are disconnected. Those apps will switch back to the original output with the OS.

UTM cannot do this. Similar apps (VirtualBox) also seem unable to handle changes in sound output device. Is this something that can be added? If this is something handled by the QEMU backend, let me know and I will take it up with them.

**Comment by osy** [comment]
Can you test with QEMU (`brew install qemu`) and see?

**Comment by phirestalker** [comment]
I have never been able to get anything but a black screen. Is there somewhere I can find base settings for say a Debian Live CD to boot into with QEMU?

**Comment by osy** [comment]
You’ll want to go into VM settings and export the QEMU command from the QEMU page. Then you run with those parameters but remove the -S and anything related to SPICE.

**Comment by phirestalker** [comment]
Ya, I tried that first. I will try and determine what is happening with my QEMU.

**Comment by phirestalker** [comment]
QEMU seems able to do it. One odd thing is that QEMU seems to ignore my audio chooser app called Soundsource. I set the sound device per-app, but QEMU ignores this setting and I have to change the system audio device.

I changed the audio device to bluetooth and QEMU played it through bluetooth. I changed it back to speakers, and it played on the speakers. For some reason UTM seems to ignore the audio changes. I will run one more deliberate test with UTM to be sure, but I believe I tried changing the system audio device too.

**Comment by osy** [comment]
In that case I suspect the issue is with SPICE.

**Comment by phirestalker** [comment]
Stupid question, but is there a way to use spice for video, but not for the audio? Are there some settings I can change, or would this require code changes?

If there are code changes required, could they be a band-aid solution for the short-term? I imagine spice folks to be slow in fixing "minor" issues.

**Comment by osy** [comment]
It can be possible but I’m not sure since we run QEMU in a separate process.

**Comment by wingcomm** [comment]
Would love to see this as well! I need to be able to have the host audio output followed as well when I need to switch to bluetooth headphones.

**Comment by fiore42** [comment]
> In that case I suspect the issue is with SPICE.

apologies if this is a silly question, but I can't find this issue on the [SPICE page](https://gitlab.freedesktop.org/groups/spice/-/issues).

Are they aware of this issue? Which bug shall we track and petition on the SPICE board to solve this bug?

Thanks and Happy New Year!
