### ISSUE TITLE
Windows XP internet explorer connects to google.com and searching but other websties come up as "page cannot be displayed"

### ISSUE THREAD

**Issue by itsyecoder** [utmapp/UTM#349]
Installed Windows XP ISO and when I go totype in a url into internet explorer, it gives me the error, "the page cannot be displayed"

**Comment by fomalsd** [comment]
it's not an UTM issue. install firefox to be able to browse modern sites

**Comment by itsyecoder** [comment]
> it's not an UTM issue. install firefox to be able to browse modern sites

How would i be able to do this without the use of a working browser?

**Comment by osy86** [comment]
Yes this is a Windows XP issue. You'll have the exact same problem installing Windows XP on a real computer in 2020. You can make an ISO of Firefox and attach it as a disk drive.
