### ISSUE TITLE
virtio-rng-pci blocks OpenBSD 7.0 from booting

### ISSUE THREAD

**Issue by AwlsomeAlex** [utmapp/UTM#3493]
**Describe the issue**
Tried booting OpenBSD 7.0 (install.img) with boot-flags `set tty fb0` in order to get graphics. Console spams `"LNRO0005" at acpi0 not configured"` then stops at `virtio1: couldn't map interrupt`. virtio1 is supposedly the RNG device, as seen in the following screenshot.

<img width="912" alt="Screen Shot 2022-01-16 at 3 25 24 PM" src="https://user-images.githubusercontent.com/11639639/149677137-61d6a6bd-99f5-420a-a03f-38884b1e9a8a.png">

Was able to run this fine with qemu
`qemu-system-aarch64 -M virt,highmem=off -accel hvf -cpu host -smp 4 -m 4096 -drive file=pflash0.img,format=raw,if=pflash,readonly=on -drive file=pflash1.img,format=raw,if=pflash -device ramfb -display default,show-cursor=on -device qemu-xhci -device usb-kbd -device usb-tablet -device intel-hda -device hda-duplex -drive file=install70.img -drive file=fbsd.img,if=virtio,cache=writethrough`

But when I add `-device virtio-rng-pci` the error occurs. I've booted OpenBSD 7.0 before, could this possibly be #3121 

**Configuration**
* UTM Version: 3.0.3 (beta)
* OS Version: macOS Monterey 12.1
* Intel or Apple Silicon? Apple Silicon

**Crash log**
UTM did not crash

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/7877893/debug.log)

**Upload VM**
[config.txt](https://github.com/utmapp/UTM/files/7877894/config.txt)

**Comment by osy** [comment]
Maybe we make that device an option.
