### ISSUE TITLE
Stuck in VM Edit screen after exporting QEMU debug file

### ISSUE THREAD

**Issue by AwlsomeAlex** [utmapp/UTM#3494]
**Describe the issue**
Not able to exit out of settings after you export a QEMU "debug" file.

**Recreate**
1) Press "Edit" on VM
2) Go to QEMU and press "Export Debug Log"
3) Save file anywhere (in my case, default was Download)
4) Press "Cancel" to leave "Edit" screen
5) Save prompt reappears, resaving or cancelling action does nothing, pressing "Cancel" makes save prompt reappear. Need to COMMAND+Q UTM.

Can not recreate when I try this with "Export QEMU Command".

**Configuration**
* UTM Version: 3.0.3 (beta)
* OS Version: macOS 12.1 Monterey
* Intel or Apple Silicon? Apple Silicon

**Crash log**
UTM does not crash

**Debug log**
VM is not ran

**Upload VM**
VM does not matter

**Comment by osy** [comment]
@ktprograms can you debug this one?

**Comment by osy** [comment]
I see `SwiftUI: Modifying state during view update, this will cause undefined behavior.`
