### ISSUE TITLE
Invert Mouse Scroll option does not change scrolling on macOS

### ISSUE THREAD

**Issue by tiiiecherle** [utmapp/UTM#3497]
**Describe the issue**
Enabling/Disabling the "Invert Mouse Scroll" option per vm does not change the scrolling direction neither in a Windows 10 vm nor in a Linux vm on a Macbook Pro when using Trackpad.

**Configuration**
* UTM Version: 3.0.3 beta
* OS Version: 12.1
* Intel

**Comment by tiiiecherle** [comment]
I don't know how this is supposed to work but additionally as a default for this option it does not use the value specified in the macOS system preferences. I would expect that to be the default even in the vm.

**Comment by tiiiecherle** [comment]
Thanks for looking into it.

**Comment by ktprograms** [comment]
@osy #3498 should fix this

**Comment by dnyrivera** [comment]
You can use the Terminal to disable natural scrolling (also known as reverse scrolling) on macOS by changing the relevant system preference using the `defaults write` command. Here's how to do it:

1. Open the Terminal application. You can find it in the Utilities folder within the Applications folder, or you can use Spotlight Search to find and open it.

2. To disable natural scrolling, use the following command:
   
   ```bash
   defaults write -g com.apple.swipescrolldirection -bool false
   ```

   This command sets the "com.apple.swipescrolldirection" preference to "false," which turns off natural scrolling.

3. After running the command, you may need to log out and log back in, or restart your Mac for the changes to take effect.

If you ever want to enable natural scrolling again, you can use the following command:

```bash
defaults write -g com.apple.swipescrolldirection -bool true
```

Again, you may need to log out or restart for the changes to be applied.
