### ISSUE TITLE
Deleted VMs still take up storage?

### ISSUE THREAD

**Issue by Jakubikk** [utmapp/UTM#3505]
Hello,
I created a virtual machine, and after I deleted it, the disk space hasn't been freed up. Here's what I did:

1. I created a new VM,
2. Added 1 virtIO drive and 1 USB drive,
3. Booted the VM,
4. Shut it down after a couple seconds,
5. Removed everything in order: USB, VirtIO, the VM   **FROM THE UTM APP**,
6. Closed UTM and checked the disk space.

I'd be very thankful for help.

**Comment by conath** [comment]
How much disk usage are you talking about? UTM itself uses much more space than a new “blank” VM you create. 

On my Mac the UTM app uses 1.12 GB. A new VM that has never been started uses 200KB, and it increases to around 750KB after it is started once. The only other size increase should be if you import a drive or install an operating system.

**Comment by Jakubikk** [comment]
> How much disk usage are you talking about? UTM itself uses much more space than a new “blank” VM you create.
> 
> On my Mac the UTM app uses 1.12 GB. A new VM that has never been started uses 200KB, and it increases to around 750KB after it is started once. The only other size increase should be if you import a drive or install an operating system.

It's 45GBs, the same size as the VirtIO

**Comment by conath** [comment]
Did you click “Save” in UTM after you deleted the drive and before you closed the app?

**Comment by Jakubikk** [comment]
Yes, I think so.

**Comment by Jakubikk** [comment]
> Did you click “Save” in UTM after you deleted the drive and before you closed the app?

Yes, I did.

**Comment by Jakubikk** [comment]
Why u deleting my comments UTM?

**Comment by conath** [comment]
Ok. I just tested this on my Mac and it deletes the files as expected. Please add the information about your system configuration like below:

- UTM Version: 3.0.3 (44) from GitHub releases page
- macOS Version: 12.1
- Intel or Apple Silicon? Apple Silicon

**Comment by Jakubikk** [comment]
<img width="396" alt="Screen Shot 2022-01-20 at 09 50 08" src="https://user-images.githubusercontent.com/83714079/150304772-7dce6007-df9c-4ca3-8a01-8ccc7028dd2c.png">
<img width="257" alt="Screen Shot 2022-01-20 at 09 50 31" src="https://user-images.githubusercontent.com/83714079/150304849-274436b0-4595-412a-91b8-d0e2ca70eb64.png">

**Comment by Jakubikk** [comment]
Please stop deleting, I'm just trying to get help.

**Comment by conath** [comment]
I am not sure what is happening with your comments, it seems like you are hitting some kind of spam filter. 

Thanks for the info, you are using the latest non-beta UTM. So let's try to get your storage space back. Open Finder and click Go => Go to Folder… menu. Then paste this path: `~/Library/Containers/com.utmapp.UTM/Data/Documents/` and press return. Now you see a list of all VMs that are still in the UTM folder and not deleted. You can delete any of them by selecting the UTM file, then press ⌥ ⌘ -delete . If there are no files there, the storage use is from something else.

**Comment by Jakubikk** [comment]
No, there's only a folder named Public, but thanks for the help.

**Comment by conath** [comment]
> No, there's only a folder named Public, but thanks for the help.

Alright then you will need to look for the large file elsewhere.

**Comment by neosh11** [comment]
Same issue, 30gb just disappeared from my computer. MacOS
