### ISSUE TITLE
Can not pass ping in cmd of vms downloaded from official website

### ISSUE THREAD

**Issue by svjack** [utmapp/UTM#351]
Run the reactos download from vms in the website 

Can not have network in my iPad Pro.
But archlinux seemed works.

ping www.baidu.com
Not passed.

**Comment by svjack** [comment]
or what i should change in vm configuration?

**Comment by osy86** [comment]
This is expected as ping doesn't work with SLIRP: https://wiki.qemu.org/Documentation/Networking#User_Networking_.28SLIRP.29

**Comment by svjack** [comment]
> This is expected as ping doesn't work with SLIRP: https://wiki.qemu.org/Documentation/Networking#User_Networking_.28SLIRP.29

you said ping not works with reactos?
it is based on win system, and similar as. win nt and 2000 ui .
and the application manager can not download from web for no network.

**Comment by osy86** [comment]
Application manager works fine for me. I was able to install Firefox from it.

**Comment by svjack** [comment]
> Application manager works fine for me. I was able to install Firefox from it. 
can you share your network configuration of vm to me ?

**Comment by svjack** [comment]
or if not bother you, can you share your utm file installed with firefox to me ?
dropbox or google drive are appreciated.

**Comment by svjack** [comment]
I know the problem is my device link to a vpn app.
So now the problem is how can i use network in vm with link to vpn ?

**Comment by osy86** [comment]
So UTM networking does not work over VPN?

**Comment by svjack** [comment]
It seemed works with archlinux and win xp vms but not works with reactos

**Comment by osy86** [comment]
I suspect that this is an issue with reactos + QEMU.

**Comment by svjack** [comment]
> I suspect that this is an issue with reactos + QEMU.
It seems some problems occur that I can use reactos to install old version of anaconda (which is a interpreter of python) and can use “conda” command to perform some pkgs mangerment and update with network but “pip” command with network resources seems not work.
I think the reactos is the only win like lightly system to perform. And if the problem can be overcome than use reactos to programming can be fun, do you have some suggestions ?

**Comment by osy86** [comment]
In some regions you have to allow network access for the app (there should have been a popup on first launch). Double check to make sure you allowed network access.
