### ISSUE TITLE
Cannot modify settings from context menu

### ISSUE THREAD

**Issue by hzieechen** [utmapp/UTM#3513]
**Describe the issue**
A clear and concise description of what the issue is. **BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Configuration (required)**
* UTM Version: 
* OS Version: 
* Device Model: 
* Is it jailbroken (name jailbreak used)? 
* How did you install UTM? 

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here.

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the bottom of the configuration options (or at the top of the `QEMU` page) is `Debug Log`. Turn it on and save the VM. After you experience the issue, quit the VM and re-launch UTM. Open the VM settings again and select `Export Log...` and attach it here.

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since GitHub has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by osy** [comment]
I'm not sure what the issue is and you did not provide any of the information in the template. If you can attach a video or something showing the problem and provide information on reproducing the issue, feel free to re-open the issue.

**Comment by hzieechen** [comment]
**Describe the issue**
Can't edit Existing VM Settings
**Configuration (required)**
* UTM Version:2.4.1 
* OS Version: 15.0
* Device Model: ipad pro 12.9-inch , 5th generation , m1 chip
* Is it jailbroken (name jailbreak used)? no
* How did you install UTM? altstore sideload

发自我的iPhone

**Comment by osy** [comment]
You still haven't explained what happens. Please attach a video if possible.

**Comment by hzieechen** [comment]
https://user-images.githubusercontent.com/95420677/150634510-b785acd0-83b6-4889-a1b8-28e41ade9b97.mp4
Can't edit Existing VM Settings

**Comment by hzieechen** [comment]
[202201221636.mp4.zip](https://github.com/utmapp/UTM/files/7918113/202201221636.mp4.zip)
