### ISSUE TITLE
Add a "QEMU Console" button in the toolbar for QEMU VMs, link to monitor.

### ISSUE THREAD

**Issue by adespoton** [utmapp/UTM#3522]
It would be great to expose the QEMU monitor for more advanced users.  

Since this provides direct access to the existing QEMU interface for disk management, debugging, VM snapshots, etc. it would enable UTM users to use advanced features even if they're not being presented as options in the default UTM UI.  It would also mean the QEMU monitor documentation would be directly applicable, so UTM wouldn't have to maintain its own documentation for the feature.  

There's currently over a dozen feature requests in the Issue tracker that would instantly be resolved with this feature (direct people to use existing commands in monitor), plus others that could be properly debugged with the monitor easily available.  Following implementation, feature requests could switch to exposing specific monitor features in the UI, rather than people making requests for features similar to what's already available in QEMU but hidden from the UI.

**Comment by adespoton** [comment]
To avoid confusion for regular users, it could be hidden by default, but an optional button to add to the toolbar in prefs.

**Comment by osy** [comment]
> There's currently over a dozen feature requests in the Issue tracker that would instantly be resolved with this feature (direct people to use existing commands in monitor)

I disagree with this philosophy. It's one of the most frustrating things dealing with the Linux community is that because more advanced options exist, people will just dismiss UX issues since "you can just do this in the terminal".

> It would be great to expose the QEMU monitor for more advanced users.

There's plans to support PTY interface for serial forwarding. I can make QEMU monitor as an option for the serial port.

**Comment by adespoton** [comment]
Your plans sound like a great option for macOS; how would that work for i*OS users?

I'm thinking that linking it in to your debug log would also be useful (and doable by just sending monitor commands in the background and emitting the results to STDOUT, such as the QEMU hardware configuration)

**Comment by osy** [comment]
You can open a TCP port on iOS and use a telnet client.

**Comment by adespoton** [comment]
I guess we can close this one as "won't fix" unless you want to change the title to "add QEMU monitor as an option for the serial port."

**Comment by conath** [comment]
@osy is there an open issue about the PTY interface?

**Comment by conath** [comment]
Superseded by #3546
