### ISSUE TITLE
Support booting into recovery mode / 1TR?

### ISSUE THREAD

**Issue by Naville** [utmapp/UTM#3526]
Hi:

Is it possible for me to boot into recovery mode when running macOS using Virtualization.framework on Apple Silicon Mac?
Otherwise SIP can't be disabled?

EDIT:
To be clear, we are talking about [1TR](https://support.apple.com/guide/security/contents-a-localpolicy-file-mac-apple-silicon-secc745a0845/web) which is possible only with a physical press on the TouchID sensor for a physical AppleSilicon Mac

**Configuration**
* UTM Version: v3.0.4
* OS Version: macOS 12.1
* Apple Silicon

**Comment by osy** [comment]
Currently this isn’t possible without private framework calls. See https://github.com/saagarjha/VirtualApple for an example of how if can be implemented.

**Comment by osy** [comment]
I would be curious if you can take VirtualApple’s aux files and copy it to the .utm and if that would work.

**Comment by Naville** [comment]
@osy I saw that yesterday and implemented my little tool based off UTM.
I wonder if that should be added to UTM upstream though🤔

**Comment by anoane** [comment]
> Currently this isn’t possible without private framework calls. See https://github.com/saagarjha/VirtualApple for an example of how if can be implemented.

Using virt framework recovery works fine, csrutil/bputil work fine, nvram can be set, but I still have some extra issues with spctl (some settings are not sticky)
https://github.com/saagarjha/VirtualApple/issues/2
Any idea? @osy @Naville

**Comment by Naville** [comment]
@anoane From what I heard, they are just not supported in current version of the VM Kernel.  I mean you **can** set them but

**Comment by Naville** [comment]
@anoane To be clear, vmapple uses a much stripped down version of the macOS kernel and lacks a bunch of critical features, I ended up just dual-booting another macOS install

**Comment by steven-michaud** [comment]
I've found [a workaround for this bug](https://github.com/utmapp/UTM/issues/3904#issuecomment-1100924393).

**Comment by kFYatek** [comment]
I also just found out that there is a public API for booting into recovery in macOS Ventura beta, see https://developer.apple.com/documentation/virtualization/vzmacosvirtualmachinestartoptions/4013558-startupfrommacosrecovery

**Comment by pistachiomatt** [comment]
@osy It looks like this was fixed but it's not in the docs. How to boot into recovery mode?

**Comment by osy** [comment]
You should be able to right click on the VM and choose boot into recovery mode. I will make sure to update the docs.

**Comment by mig8447** [comment]
I do not get the "Boot into recovery mode button" on the latest UTM

**Comment by kFYatek** [comment]
> I do not get the "Boot into recovery mode button" on the latest UTM

Which version of macOS are you running? I'm pretty sure this is only available in Ventura.

**Comment by mig8447** [comment]
I was trying on macOS Sierra, then upgraded to Ventura and the button still didn't show, I ended up following this workaround https://github.com/utmapp/UTM/issues/3904#issuecomment-1100924393 and left a 128MB disk in my vm so I can access this again.

**Comment by kFYatek** [comment]
Sierra? So you're probably running on an Intel Mac? I'm pretty sure that this functionality only applies to Apple Silicon.

**Comment by mig8447** [comment]
Not Sierra, sorry, Monterey
