### ISSUE TITLE
Black screen when start VR in 1.0rc3

### ISSUE THREAD

**Issue by shaughanlavine** [utmapp/UTM#353]
**Describe the bug**
UTM opens normally, but when a VM is opened, there is a black screen with the bar on top and nothing happens. The bar seems to function normally: keyboard opens and closes UTM quits. 
Everything works as expected using 1.0rc1 or 1.0rc2.

**To Reproduce**
Attempt to open any VM using 1.0rc3.

**Debug log**

UTMTerminalIO does not support debug mode.
Loading libqemu-system-aarch64.dylib
Running:  qemu -L /private/var/containers/Bundle/Application/64F3C059-0D12-4254-9ABA-A55070CD03F6/UTM.app/qemu -qmp tcp:localhost:4444,server,nowait -smp cpus=2,sockets=1 -machine virt, -accel tcg,thread=multi -cpu cortex-a72 -device virtio-gpu-pci -boot order=d -m 768 -soundhw ac97 -name "ArchLinux ARM mine" -drive "file=/private/var/mobile/Containers/Data/Application/71A2CB27-BB60-49E0-8625-E3C5FAFB0148/Documents/ArchLinux ARM mine.utm/Images/disk.qcow2,if=sd,media=disk,id=drive0" -initrd "/private/var/mobile/Containers/Data/Application/71A2CB27-BB60-49E0-8625-E3C5FAFB0148/Documents/ArchLinux ARM mine.utm/Images/initramfs-linux.img" -kernel "/private/var/mobile/Containers/Data/Application/71A2CB27-BB60-49E0-8625-E3C5FAFB0148/Documents/ArchLinux ARM mine.utm/Images/Image.gz" -nographic -chardev "pipe,id=term0,path=/private/var/mobile/Containers/Data/Application/71A2CB27-BB60-49E0-8625-E3C5FAFB0148/tmp/ArchLinux ARM mine.terminal" -serial chardev:term0 -device rtl8139,netdev=net0 -netdev user,id=net0,hostfwd=tcp::5555-:22 -device usb-ehci -device usb-tablet -device usb-mouse -device usb-kbd -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid E3459327-D6AC-409C-ABCA-08EAAC345F57 -rtc base=localtime -append "root=/dev/vda rw"
Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
QMP connection failed, retries left: 9
changeFont error: (null)
setCursorBlink error: (null)
qemu: -drive file=/private/var/mobile/Containers/Data/Application/71A2CB27-BB60-49E0-8625-E3C5FAFB0148/Documents/ArchLinux ARM mine.utm/Images/disk.qcow2,if=sd,media=disk,id=drive0: machine type does not support if=sd,bus=0,unit=0
RPC: Error Domain=com.osy86.utm Code=-1 "No connection for RPC." UserInfo={NSLocalizedDescription=No connection for RPC.}
Connected to stream
QMP connection successful! (readStream:1)
Connected to stream
QMP connection successful! (readStream:0)
Debug JSON recieved <- {
    QMP =     {
        capabilities =         (
            oob
        );
        version =         {
            package = "";
            qemu =             {
                major = 4;
                micro = 0;
                minor = 2;
            };
        };
    };
}
Got QMP handshake: {
    QMP =     {
        capabilities =         (
            oob
        );
        version =         {
            package = "";
            qemu =             {
                major = 4;
                micro = 0;
                minor = 2;
            };
        };
    };
}
Debug JSON send -> {
    arguments =     {
    };
    execute = "qmp_capabilities";
}
Terminal resize: (
    141,
    91
)
RPC: Error Domain=com.osy86.utm Code=-1 "Timed out waiting for RPC." UserInfo={NSLocalizedDescription=Timed out waiting for RPC.}

**Upload VM**
This doesn't appear to be necessary since the error occurs with multiple VMs. All are based on your ArchLinux VM.

**Comment by osy86** [comment]
What device? What iOS?

**Comment by osy86** [comment]
Oh I see you didn't read the notes.
<img width="807" alt="image" src="https://user-images.githubusercontent.com/50960678/83434339-29adf900-a3ef-11ea-9b4e-74cc8c08c1b3.png">

**Comment by shaughanlavine** [comment]
Yeah, that was it. 'Sorry. Next time I won't head straight for Releases.
