### ISSUE TITLE
Cursor got stuck during MacOS Lion/Mavericks Recovery

### ISSUE THREAD

**Issue by Anappledevlovperlover** [utmapp/UTM#3531]
![IMG_0167](https://user-images.githubusercontent.com/93073424/150785238-33279ffa-92e1-4319-8824-0e1e82b659ce.png)

I followed https://khronokernel.github.io/apple/silicon/2021/01/17/QEMU-AS.html This tutorial, only changed its setting from Catalina to Mavericks (or Lion, same error). 
However, whenever I start recovering MacOS (Extracted the DMG from MACRECOVERY), and reach Language selecting screen, the cursor gets stuck on the left-top corner as it’s showed on the picture I provided.
Is there some setting that I should adjust more, or it is just problem with just MacOS?
Please feel free to comment :) 👍

**Comment by adespoton** [comment]
Have you tried pressing control-option a few times to toggle mouse capture?

I've got functional configs for Lion through Catalina over at github.com/adespoton/utmconfigs -- all verified working without mouse issues.

**Comment by Anappledevlovperlover** [comment]
What the- You’re so kind!! Thx alot! I already got the recoeryimages. Thank you for your reply! 
If it doesn’t work, I will contact again. Thank you again!

**Comment by Anappledevlovperlover** [comment]
Hi, sorry for recontacting in the closed issue:
I found that there is an instruction on the prebuilt vm (configuration I mean), and I can’t quite understand

[Save the following as InstallElCapitan.command and run "InstallElCapitan.command /Applications/Install OS X El Capitan.app" from Terminal.app:

#!/bin/sh

echo "Create ISO image from OS X install app"

echo "Usage: <script> <path to installer.app>"

# Method for El Capitan.  Some older installers require mounting 

echo "create a blank disk image:"
hdiutil create -o /tmp/installer.cdr -size 7316m -layout SPUD -fs HFS+J

echo "mount your blank image:"
DEVNUM=`hdiutil attach /tmp/installer.cdr.dmg -noverify -nobrowse -mountpoint /Volumes/install_build | perl -ne'if ($_ =~ /^\/dev\/disk([0-9]+)\s+Apple_partition_scheme/) { print($1); exit(0) }'`
echo "DEVNUM: $DEVNUM"
# restore BaseSystem.dmg from the installer over to the newly mounted image:
# asr restore -source $1/Contents/SharedSupport/BaseSystem.dmg -target /Volumes/install_build -noprompt -noverify -erase
# hdiutil detach /Volumes/OS\ X\ Base\ System

echo "use the built-in installer to set up the newly mounted image:"
echo "sudo $1/Contents/Resources/createinstallmedia --volume /Volumes/install_build --applicationpath $1"
sudo "$1/Contents/Resources/createinstallmedia" --volume /Volumes/install_build --applicationpath "$1"

echo "unmount installed image:"
hdiutil unmount /Volumes/Install\ * -whole -force
hdiutil detach /dev/disk$DEVNUM

echo "convert built image to ISO file:"
hdiutil convert /tmp/installer.cdr.dmg -format UDZO -o /tmp/installer.dmg
rm /tmp/installer.cdr.dmg

echo "and move to the Downloads folder:"
mv /tmp/installer.dmg ~/Downloads/osxinstall.dmg

echo "$1 converted to ~/Downloads/osxinstall.dmg!"]

So, I just ignored that and placed the RecoveryImage.dmg in to the Removable Disk, and first, It booted
fine, but when It came to OS selection, I can’t find MacOS. I thought I did something wrong, to I changed the Removable Drive’s configuration (CD to USB.). However, that has the same problem-again with no MacOS selection. Did I do something wrong? Please heeeelp
