### ISSUE TITLE
Cannot connect to wifi in arch-linux (from gallery)

### ISSUE THREAD

**Issue by Leovaldez42** [utmapp/UTM#3535]
Cannot connect to wifi in arch linux

* UTM Version: 2.4.1
* OS Version: 12.1
* Intel or Apple Silicon: Apple Silicon

If we download Arch Linux from the gallery, the packages which need to be install "dialog" is not preinstalled, due to which we cannot connect to wifi networks. wifi-menu does not work

**Comment by AwlsomeAlex** [comment]
This image should be using your Mac's network connection. Perhaps somethings blocking you from communicating with Arch's servers?

**Comment by Leovaldez42** [comment]
I am not able to ping or download any packages, although the internet is working perfectly fine. Maybe someone else may have faced the same issue?

**Comment by Leovaldez42** [comment]
> I am not able to ping or download any packages, although the internet is working perfectly fine. Maybe someone else may have faced the same issue?

I meant the internet outside the vm, not the arch linux running inside the vm

**Comment by ktprograms** [comment]
@Leovaldez42 Qemu presents a virtual wired network to the VM, even if your Mac is running on wifi.

What do you get when you run `ip a` (or `ifconfig` if `ip` isn't installed)?

**Comment by Leovaldez42** [comment]
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 16:47:59:53:6d:7c brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic enp0s5
       valid_lft 86376sec preferred_lft 86376sec
    inet6 fec0::1447:59ff:fe53:6d7c/64 scope site dynamic mngtmpaddr noprefixroute 
       valid_lft 86379sec preferred_lft 14379sec
    inet6 fe80::1447:59ff:fe53:6d7c/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by Leovaldez42** [comment]
<img width="749" alt="Screenshot 2022-01-26 at 11 05 52 AM" src="https://user-images.githubusercontent.com/48851300/151109391-9aaa1a04-a2fb-4b64-81b0-dab7cf8edb8f.png">

**Comment by ktprograms** [comment]
Can you try doing a `curl duckduckgo.com` or `wget -O - duckduckgo.com`?

**Comment by Leovaldez42** [comment]
<img width="369" alt="Screenshot 2022-01-26 at 11 08 00 AM" src="https://user-images.githubusercontent.com/48851300/151109552-cd1fd840-514b-4e9e-aa3c-a154761afdbb.png">

**Comment by ktprograms** [comment]
Ok, the curl is successfully fetching duckduckgo.com, so network is working.

I suspect it's either a misconfiguration with pacman repos, or it just hasn't synced. Try running `pacman -Sy`

**Comment by Leovaldez42** [comment]
It Synchronised, but I am still not able to ping google.com

**Comment by ktprograms** [comment]
ping is not expected to work, because of the Emulated VLAN networking used in Qemu. But web browsing is doable.

Have you tried installing packages?

**Comment by Leovaldez42** [comment]
Yes package installation is working. Thanks a lot!! This was my first time using arch linux so did not really know.
