### ISSUE TITLE
UTM can't launch any VMs on iOS 14.8

### ISSUE THREAD

**Issue by Userna34** [utmapp/UTM#3542]
I am always getting the error "QEMU exited from an error: gemu- system: -accel tcg,tb-size=128: allocate 134217728 bytes for jit buffer: Invalid argument" when launching the VM.
The message always popup and I am unable to access the VM.

* UTM Version: 3.0.4
* OS Version: iOS 14.8
* Device Model: iPhone XS
* Is it jailbroken (name jailbreak used)? unc0ver
* How did you install UTM? I used the ipa from github to create a deb with Filza to give UTM root access.

![E33DC6F6-EF60-4EE8-BBC9-90747020DAB8](https://user-images.githubusercontent.com/98495496/151258406-d71d9464-d8f6-40c8-ac02-220bb75e6d9a.png)

**Comment by conath** [comment]
I'm not sure it UTM works when installed this way, as it needs to be signed with a development certificate AFAIK. I would recommend you install via the DEB provided in the GitHub Releases page, following the [UTM install instructions](https://getutm.app/install/). If this does not make it work either, please re-open this issue.
