### ISSUE TITLE
Can't install UTM properly (jailbreak version)

### ISSUE THREAD

**Issue by bogotesr** [utmapp/UTM#3543]
**Describe the issue**
UTM will not install through cydia, sileo or, zebra. I can install through ipa but not VMs will launch, when i tap on the vm the app crashes. If I open cydia after installing it says that UTM is a half installed package (even with ipa)

**Configuration (required)**
* UTM Version: 3.0.4
* OS Version: 12.5.5
* Device Model: ipad4,4 (iPad mini 2 wifi) (15gb of free storage)
* Is it jailbroken (name jailbreak used)? yes (checkra1n)
* How did you install UTM? ipa 

**Crash log**
from installing with sileo:

> {"app_name":"com.utmapp.utm.postinst","app_version":"","bug_type":"109","timestamp":"2022-01-25 20:30:26.09 -0700","os_version":"iPhone OS 12.5.5 (16H62)","incident_id":"0A5B29FB-135A-4A89-B19D-A0F023724144","slice_uuid":"17609c69-dc50-3de0-ad5c-a5b3d5ed8898","build_version":"","is_first_party":true,"share_with_app_devs":false,"name":"com.utmapp.utm.postinst"}
Incident Identifier: 0A5B29FB-135A-4A89-B19D-A0F023724144
CrashReporter Key:   39d99efdd6cca930562debd8b1b528738c2a65d7
Hardware Model:      iPad4,4
Process:             com.utmapp.utm.postinst [1648]
Path:                /Library/dpkg/info/com.utmapp.utm.postinst
Identifier:          com.utmapp.utm.postinst
Version:             ???
Code Type:           ARM-64 (Native)
Role:                Unspecified
Parent Process:      Exited process [1635]
Coalition:           org.coolstar.SileoStore [470]

>Date/Time:           2022-01-25 20:30:25.8563 -0700
Launch Time:         2022-01-25 20:30:25.7250 -0700
OS Version:          iPhone OS 12.5.5 (16H62)
Baseband Version:    n/a
Report Version:      104

>Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, missing LC_DYLD_INFO load command
Highlighted by Thread:  0

>Backtrace not available

>Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000009   x2: 0x000000016ee2aa60   x3: 0x0000000000000014
    x4: 0x000000016ee2a660   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000d60
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x0000000000000009
   x12: 0x0000000000010220  x13: 0x0000000000000006  x14: 0x0000000100fd44e0  x15: 0x0000000100fd44c8
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016ee2a660  x21: 0x0000000000000014  x22: 0x000000016ee2aa60  x23: 0x0000000000000009
   x24: 0x0000000000000006  x25: 0x000000000000002f  x26: 0x000000010131f5e0  x27: 0x000000010131f000
   x28: 0x000000010131fa00   fp: 0x000000016ee2a630   lr: 0x0000000101305a58
    sp: 0x000000016ee2a5f0   pc: 0x0000000101306418 cpsr: 0x40000000

>Binary images description not available

>Error Formulating Crash Report:
Failed to create CSSymbolicatorRef

>EOF

from installing .deb from filza:

>{"app_name":"com.utmapp.utm.postinst","app_version":"","bug_type":"109","timestamp":"2022-01-26 10:22:53.90 -0700","os_version":"iPhone OS 12.5.5 (16H62)","incident_id":"E60BB515-9502-43B3-A770-8A5869BD098A","slice_uuid":"17609c69-dc50-3de0-ad5c-a5b3d5ed8898","build_version":"","is_first_party":true,"share_with_app_devs":false,"name":"com.utmapp.utm.postinst"}
Incident Identifier: E60BB515-9502-43B3-A770-8A5869BD098A
CrashReporter Key:   39d99efdd6cca930562debd8b1b528738c2a65d7
Hardware Model:      iPad4,4
Process:             com.utmapp.utm.postinst [5073]
Path:                /Library/dpkg/info/com.utmapp.utm.postinst
Identifier:          com.utmapp.utm.postinst
Version:             ???
Code Type:           ARM-64 (Native)
Role:                Unspecified
Parent Process:      Exited process [5065]
Coalition:           com.tigisoftware.filza.helper [432]

>Date/Time:           2022-01-26 10:22:53.6597 -0700
Launch Time:         2022-01-26 10:22:53.5274 -0700
OS Version:          iPhone OS 12.5.5 (16H62)
Baseband Version:    n/a
Report Version:      104

>Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, missing LC_DYLD_INFO load command
Highlighted by Thread:  0

>Backtrace not available

>Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000009   x2: 0x000000016f046850   x3: 0x0000000000000014
    x4: 0x000000016f046450   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000d60
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x0000000000000009
   x12: 0x0000000000010220  x13: 0x0000000000000006  x14: 0x0000000100db84e0  x15: 0x0000000100db84c8
   x16: 0x0000000000000209  x17: 0x0000000000000044  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016f046450  x21: 0x0000000000000014  x22: 0x000000016f046850  x23: 0x0000000000000009
   x24: 0x0000000000000006  x25: 0x000000000000002f  x26: 0x00000001011675e0  x27: 0x0000000101167000
   x28: 0x0000000101167a00   fp: 0x000000016f046420   lr: 0x000000010114da58
    sp: 0x000000016f0463e0   pc: 0x000000010114e418 cpsr: 0x40000000

>Binary images description not available

>Error Formulating Crash Report:
Failed to create CSSymbolicatorRef

>EOF

**Debug log**
App says that no debug log is found.

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since GitHub has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by bogotesr** [comment]
Realized I should probably include this, error when installing .deb from filza:

![IMG_0E6BEC4C26B5-1](https://user-images.githubusercontent.com/71040782/151409714-174a712b-cf95-4870-bf2d-14007b164f49.jpeg)

**Comment by We1eVen** [comment]
same problem on iOS 12.4
