### ISSUE TITLE
Ubuntu VM not saving files from previous session

### ISSUE THREAD

**Issue by zbeucler2018** [utmapp/UTM#3548]
**Describe the issue**
Hi Everybody. I am using UTM on my 2020 m1 Macbook air to virtualize Ubuntu Desktop (v20.04.3 amd64). Every time I start the ubuntu VM, I need to go through the entire installation process and all my files from the previous session are lost. After the boot process, I am met with the install GUI. When I leave the VM, I shutdown from Ubuntu (as recommended by pop-up when pressing the on/off button in UTM's GUI). What is the procedure to safely terminate the VM such that all files from that session are saved? Please let me know if I am unclear or if I can give any additional info. Thank you!

** VM Config **
* Architecture: x86_64
* Machine: Standard PC (Q35 + ICH9, 2009) (alias of pc-q35-6.2) (q35)
* Memory: 4.0 GB
* Size: 744 KB
* CD/DVD: ubuntu-20.04.3-desktop-amd64.iso

**Configuration**
* UTM Version: 3.0.4 (46)
* OS Version: Big Sur 11.5.2
* Apple Silicon

**Comment by zbeucler2018** [comment]
Hi @adespoton ! I believe that I am booting from the install image everytime but I am not sure (I am very new to VMs). When I start up the VM, I am greeted with this screen
<img width="789" alt="Screen Shot 2022-01-27 at 3 05 06 PM" src="https://user-images.githubusercontent.com/49871927/151435700-711004f8-2c1f-4797-982a-c37b8bc464de.png">
Everytime I get this screen, I choose the first option.

**Comment by adespoton** [comment]
After you've installed onto a blank disk image, you need to eject the DVD image so you don't boot into the installer anymore.  At that point, the VM will boot up from the "internal" disk instead.

Just like with a real computer; if the DVD is still in the drive, that's what you're booting from.  Its only purpose is to install the OS onto your main drive image.

**Comment by zbeucler2018** [comment]
Okay I think I understand.

So from UTM, I boot the VM with the `ubuntu-20.04.3-desktop-amd64.iso` as the DVD/CD image. Then, after ubuntu has completely installed onto the VM, I shutdown and exit the VM. Then, I will use UTM to clear the DVD/CD slot of the image and then start the VM again. 

Is that correct?

**Comment by adespoton** [comment]
Correct.

**Comment by adespoton** [comment]
I think this issue can be closed now.

**Comment by Garenbbbbb** [comment]
HOW to eject the DVD image
