### ISSUE TITLE
Program/App shortcuts like Parallels desktop

### ISSUE THREAD

**Issue by upintheairsheep** [utmapp/UTM#3552]
Please browse the existing issues and filter by 'enhancement' to make sure this has not already been suggested!

Add optional folders per VM when you use UTM virtual machines that has the shortcuts to all windows (win32 and UWP/Metro/Store/Modern and Windows Subsystem for Android apps), Linux, macOS, and android applications you have installed. For windows Classic, macOS before Big Sur, and Linux and legacy android apps, it creates a frame with either a color or the OS wallpaper. There should be no ugly icon on the side and no tinted name to keep it seem less. When you launch it, it opens the app in the VM. This may only be possible with a driver however, or command prompt.

**Comment by upintheairsheep** [comment]
Also add shortcuts to the virtual machines themselves in a folder.

**Comment by osy** [comment]
This is not possible currently in an App Sandbox app. Note that Parallels’ App Store version doesn’t support this either.

**Comment by adespoton** [comment]
FYI, I've made apps that use the utm:// uris to launch the various VMs.  I could probably make a generic app that you could use to walk through UTM VMs and create .webloc shortcuts for each one.

If there's enough interest, I'll set some of this up publicly as helper software for UTM.  So far, I'm just generating pre-configured .utm files with custom icons and screenshots for various OS versions (bring your own install iso).

**Comment by conath** [comment]
@adespoton I believe the OP is asking for an alias to apps installed within the guest OS, not to launch the VM itself (which [can be achieved with Apple Shortcuts](https://github.com/utmapp/UTM/wiki/URL-Scheme-–-Automation-for-UTM-app-&-VMs#start-a-vm-automatically-when-you-log-in-macos-12-monterey)).

**Comment by upintheairsheep** [comment]
> This is not possible currently in an App Sandbox app. Note that Parallels’ App Store version doesn’t support this either.

Exclusively for the macOS version

**Comment by upintheairsheep** [comment]
Closing for future issue to bundle winapps
