### ISSUE TITLE
Coherence/Seamless Mode like VirtualBox and Parallels

### ISSUE THREAD

**Issue by upintheairsheep** [utmapp/UTM#3554]
Add coherence/seamless mode to UTM so you can use each window like a normal program and that will mean better productivity and add drag and drop support.

https://kb.parallels.com/4670

**Comment by osy** [comment]
This is not possible currently in an App Sandbox app. Note that Parallels’ App Store version doesn’t support this either.

**Comment by dinosauria123** [comment]
How about Application window through RDP server like WinApps ?

https://github.com/Fmstrat/winapps

**Comment by upintheairsheep** [comment]
> This is not possible currently in an App Sandbox app. Note that Parallels’ App Store version doesn’t support this either.

It doesn’t have to be sandboxed. The vast majority of installs are via DMG files.

**Comment by upintheairsheep** [comment]
> 

This is a very wanted feature, due to the insane price of Parallels desktop, and the removal of Boot Camp

**Comment by upintheairsheep** [comment]
WSL uses a locally compiled Wayland for convergence.

**Comment by upintheairsheep** [comment]
Steps to add:

> Add app shortcuts to Launcher on Windows/Linux first after installing a program for the host to get control over it
> Cross compile some sort of window management tool for Windows and Linux
> Get the convergence running
> Add taskbar notification/tray icons for Windows and Linux to the macOS tray

**Comment by upintheairsheep** [comment]
https://www.parallels.com/blogs/how-to-use-coherence-mode-in-parallels-desktop/
The majority of Parallels users use Coherence mode. This issue should definitely be pinned.

**Comment by upintheairsheep** [comment]
https://kb.parallels.com/en/116675 - options panel

**Comment by upintheairsheep** [comment]
> How about Application window through RDP server like WinApps ?
> 
> https://github.com/Fmstrat/winapps
> 
> https://apple.stackexchange.com/questions/430432/coherence-mode-in-a-remote-desktop-app

Related issue: https://github.com/Fmstrat/winapps/issues/136

**Comment by upintheairsheep** [comment]
Superseding with issue asking for bundling winapps
