### ISSUE TITLE
macOS Big Sur guest mouse and keyboard are broken by SPICE devices

### ISSUE THREAD

**Issue by adespoton** [utmapp/UTM#3561]
**Describe the issue**
When booting the linked UTM image with a Big Sur install iso, the image boots perfectly to the "select language" screen and then can go no further, because the mouse and keyboard can't be found (the SPICE defaults appear to do something that causes the USB controler to panic and shut down).  I believe the details are in the debug log; if there isn't enough there, I can run from terminal and capture the SPICE log as well (similar to what I did for the qemu-system-powerpc I/O disconnect issue).

**Configuration**
* UTM Version: 2.x through 3.0.4
* OS Version: macOS 12.x
* Intel or Apple Silicon? Apple Silicon

**Debug log**
contained inside macOS.11.utm.zip

**Upload VM**
[macOS 11.utm.zip](https://github.com/utmapp/UTM/files/7975222/macOS.11.utm.zip)

**Comment by adespoton** [comment]
Since I can't redirect stdout AND use VGA, here's a screenshot.  Note the bit about the USB:
<img width="1280" alt="UTM-macOS11-USB-fail" src="https://user-images.githubusercontent.com/4846661/152243790-6acd67fd-6aac-4706-a1ae-412e533803d3.png">

**Comment by adespoton** [comment]
Issue appears to be fixed with 3.1.0; mouse pointer and keyboard are eventually auto-detected.  This issue can be closed.

**Comment by osy** [comment]
I’m curious what fixed it as there hasn’t been any change to QEMU…
