### ISSUE TITLE
macOS - mouse pointer gets uncalibrated when changing the scale rate of the guest OS UI

### ISSUE THREAD

**Issue by filip-malinowski-rhebo** [utmapp/UTM#3562]
**Describe the issue**
When I change the scale rate from 100% to any other like 150% or 200%, right after the change is being applied and the system UI rescales then the pointer becomes uncalibrated. When I move it over the screen the hover/focus is on completely different parts of the UI, not under the pointer itself.

**Configuration**
* UTM Version: 3.0.4
* OS Version: Ubuntu 21.10 - Linux 5.16.2-051602-generic aarch64
* Apple Silicon - MacBook Air M1

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/7979159/debug.log)

**Upload VM**
Packed with zip because GitHub doesn't allow uploading `.plist`
[config.plist.zip](https://github.com/utmapp/UTM/files/7979174/config.plist.zip)

**Comment by yougotwill** [comment]
This happens to me when the screen is automatically resized using spice-guest tools. I hope this issue can be fixed please 🙏

**Comment by osy** [comment]
On v4.6.1 running on macOS 15.1.1, I no longer get this issue. Feel free to re-open if anyone experiences this still on the latest version (and provide a screen capture if possible).
