### ISSUE TITLE
Copy/Paste Not working macOS Host to Guest Monterey VM from Apple Silicon Laptop

### ISSUE THREAD

**Issue by pauljrob** [utmapp/UTM#3567]
**Describe the issue**
Copy and paste is not working between the host and the guest. Is this expected behavior or is there something additional that needs to be enabled?

**Configuration**
* UTM Version: 3.0.4
* OS Version: Monterey 
* Intel or Apple Silicon? Apple Silicon

**Comment by adespoton** [comment]
From Parallels Desktop notes:
> Productivity and integration features are not available to this VM yet. It is not possible to suspend and resume the VM, [shared folders](https://kb.parallels.com/122567#:~:text=virtual%20machine%20configuration.-,Shared%20Folders%20Tool,-Shared%20Folders%20Tool) and [snapshots](https://kb.parallels.com/en/5691) are not supported for now. Apart from that it is currently not possible to adjust guest macOS screen resolution in real-time mode when resizing ratio; to change virtual machine amount of CPU and RAM or its hardware parameters (Device UUID and Serial number) and to register with Apple ID. USB and camera sharing are also missing in macOS Monterey VM running on a Mac with Apple M1 chips so far.

> Parallels Engineering Team is researching ways to expand the list of supported features in future product updates. Shared Clipboard has already been added. To enable this feature make sure Parallels Tools are installed and up-to-date.

So, it looks to me like shared clipboard is possible, but requires adding something inside the guest VM and supporting it through the VM framework.

Anyone not connected with UTM development want to have a look at what Parallels is doing and describe it in broad terms?  Might be usable inside x86_64 macOS VMs too.  Or someone figuring out SPICE integration for macOS.

**Comment by niklr** [comment]
That's the only thing preventing me from using a Monterey VM right now.

**Comment by protectmango** [comment]
Hello : 
Giving you a short help 
use command + c to copy thing from mac os also for M1 mac also .
and then use control(^) + shift + V to copy it in UTM

**Comment by protectmango** [comment]
> That's the only thing preventing me from using a Monterey VM on Apple Silicon right now.


Hello :
Giving you a short help
use command + c to copy thing from mac os also for M1 mac also .
and then use control(^) + shift + V to copy it in UTM

**Comment by flotpg** [comment]
@protectmango 
hi, this doesn't work for me on macOS M1 Max with 3.1.5 and macOS Monterey guest VM

**Comment by adespoton** [comment]
> @protectmango 
> 
> hi, this doesn't work for me on macOS M1 Max with 3.1.5 and macOS Monterey guest VM

You may want to update to 3.2.1?

**Comment by flotpg** [comment]
@adespoton: i already looked for it, but I can't find the download links on the releases page...

**Comment by adespoton** [comment]
https://github.com/utmapp/UTM/releases

-Em

**Comment by flotpg** [comment]
None of the beta releases have assets attached (no links to dmg, etc).

**Comment by osy** [comment]
Uhhh have you tried clicking on the word “Assets”

**Comment by neilgoldman** [comment]
> > That's the only thing preventing me from using a Monterey VM on Apple Silicon right now.
> 
> Hello : Giving you a short help use command + c to copy thing from mac os also for M1 mac also . and then use control(^) + shift + V to copy it in UTM

Not working for me in 3.2.2

**Comment by flotpg** [comment]
Ahh, too blind. For stable releases the assets are expanded. Betas are collapsed.
Found it and will try, many thanks.

**Comment by flotpg** [comment]
control(^) + shift + V not working for me with Monterey guest on apple silicon host running UTM 3.2.2

**Comment by mikiquantum** [comment]
Same here, on version 3.2.4.

**Comment by protectmango** [comment]
https://www.youtube.com/watch?v=A2fEUnk5io0&t=231s
Bro Watch this dude video it will definitely solve all your problems

**Comment by m4rc0g** [comment]
For me worked install on Kali Virtual `sudo apt install spice-vdagent spice-webdavd` and enable clipboard sharing from settings. Restart UTM and Kali to make changes work.

**Comment by jjcfrank** [comment]
It does not seem to work if only terminal i.e. Ubuntu Server.

**Comment by Sherry112** [comment]
Not working for me as well.

**Comment by ahrenstein** [comment]
For Monterey hosts and Monterey guests you can use a bit of hacky workaround: Apple Remote Desktop. It allows you to copy the clipboard to to/from the guest and you can also drag and drop files to the remote window to transfer files to the VM.

**Comment by jonathanlaniado** [comment]
@ahrenstein, interesting, can you expand on that further? How do you set this up?

**Comment by j26w** [comment]
> For Monterey hosts and Monterey guests you can use a bit of hacky workaround: Apple Remote Desktop. It allows you to copy the clipboard to to/from the guest and you can also drag and drop files to the remote window to transfer files to the VM.

Wow. You, sir, are a genius. Seriously, thank you. What a brilliantly simple solution to use the Screen Sharing app. It even enabled the touchpad pinch-to-zoom functionality in Photoshop, which I was sorely missing. Thank you!

**Comment by jonathanlaniado** [comment]
Oh man now I really feel left out. Anybody care to be kind enough to explain how to set that up?

**Comment by j26w** [comment]
> Oh man now I really feel left out. Anybody care to be kind enough to explain how to set that up?
> 
> Edit: I guess I'm curious if you're able to connect to the VM via ARD (Apple Remote Desktop) offline or if you need to have UTM and ARD running side-by-side with an Internet connection.

Start the VM (yes it needs to be running side-by-side). In the VM, enable Screen Sharing in Preferences-->Screen Sharing. Then on your host mac, open the default Screen Sharing app, and connect to the VM's IP address.

I also have File Sharing in the VM enabled so I can mount it as a remote drive in my host, but you can drag and drop from host to guest (and vice versa) with the Screen Sharing app.

**Comment by ahrenstein** [comment]
@jonathanlaniado In the guest macOS under System Preferences > Sharing enable either "Remote Management" or "Screen Sharing" I use the former since I own a copy of [ARD](https://apps.apple.com/us/app/apple-remote-desktop/id409907375?mt=12)
Then you can just use ARD or Screen Sharing to access the IP address of the VM from your host. In my case last night it was `192.168.64.2` although you can find your IP in the Network settings.

@j26w I'm glad I could help!

**Comment by adespoton** [comment]
No need to even find the IP address.  With Remote Access enabled on the guest, the guest should show up in the Locations list on the host’s Finder sidebar.  Select it and click Share Screen… and you’re connected.

Do we have a way to run VMs headless by default in UTM now? Because UTM itself could be used to use the share screen feature for screen display if the option is enabled on the guest and the feature was added to UTM.

-Em

**Comment by patniemeyer** [comment]
I agree that on Mac screen sharing is a much smoother and better experience than the native display.  I also wish there were an option to just start UTM headless and launch screen sharing for the UI.

**Comment by nklsw** [comment]
Are there other workarounds for a shared clipboard? It's working with remote access, but I'm not happy with graphic performance.

**Comment by BenJackGill** [comment]
Incase you have trouble doing the screen share trick, follow these steps:

**On the Guest machine:**
1. Open System Sharing > General > Sharing
2. Turn on Screen Sharing
3. Click the "i" symbol next to Screen Sharing and change "Allow Access" to "All Users"

Now go back to the Host machine...

**On the Host Machine:**
1. Open Finder
2. In the left sidebar under "Locations" click the "Network" tab
3. You will see your virtual machine in there. Right click on it and select "Screen Share"
4. The input the Username and Password for the Guest machine

Now you can use the Screen Share window to move files and copy/paste between the host and guest machines easily.

The UTM window of the Guest needs to remain open because it will shut down the guest machine it you close it. But to avoid confusion with the Screen Share window, you can minimize the UTM guest window down and out of sight.

**Comment by RedNo7** [comment]
> On the Guest machine:
> Open System Sharing > General > Sharing

Where on earth do you find this setting?  ...very new to UTM, but I have looked in every menu and right-clicked on everything right-clickable.

Thanks.

**Comment by guycalledseven** [comment]
Running UTM Version 4.2.5 (81), on macOS Ventura 13.4.1 (22F82), VM is Linux 6.1.0-kali9-arm64 #1 SMP Debian 6.1.27-1kali1 (2023-05-12) aarch64 GNU/Linux.

I have configured folder/clipboard sharing in UTM and have spice-vdagent spice-webdavd installed.

In UTM in VM settings if under Display I select `virtio-ramfb` - copy paste works.

If I select `virtio-ramfb-gl (GPU Supported)` - copy paste does not work.

**Comment by hairer** [comment]
> Anyone not connected with UTM development want to have a look at what Parallels is doing and describe it in broad terms? Might be usable inside x86_64 macOS VMs too. Or someone figuring out SPICE integration for macOS.

I am not very familiar with VM development, but isn't [this](https://developer.apple.com/documentation/virtualization/clipboard_sharing) precisely what's needed, at least on Ventura?

**Comment by jzmail** [comment]
For text, you can take a screenshot of what you want to copy (Shift, Command, and 4 to capture a portion of the screen) in the VM. Then right click on the thumbnail in the corner of your screen and choose Markup, and copy the text. It's now in your Clipboard to paste wherever you want.

**Comment by Alkenso** [comment]
As solution, I've found very convenient to use ScreenSharing builtin tool.
Just run the VM, enable Screen Sharing in preferences, hide the window. 
On Host, go to Network, select your VM and press "Share Screen..."

That's all! With screen sharing you can use clipboard, drag-n-drop files in and out of VM

**Comment by zakkg3** [comment]
if you installed the spice agent, as mentioned in documentation https://docs.getutm.app/guest-support/linux/#spice-agent
and it does not work. Close at all UTM and reopen. That worked for me.

**Comment by ramj9** [comment]
Documentation says it only works on Linux guests : https://github.com/utmapp/UTM/issues/5409

I wonder if anybody tried compiling `spice-vdagent` on mac with any success?

**Comment by godblesslancek** [comment]
Thanks to [this issue](https://github.com/utmapp/UTM/issues/1204) , I was able to find a solution, for guest Vanilla Ubuntu 22 ARM64 guest, Host Macbook Pro M1 2021

The trick was to install ubuntu-gnome-desktop over a vanilla Ubuntu ARM64 VM the clipboard now works when doing `Ctrl^+Maj+V` .

What worked for me 
 Enable "Clipboard sharing"
`sudo apt install ubuntu-gnome-desktop`
`reboot`

What didn't work for me
 Enable "Clipboard sharing"
`sudo apt install spice-vdagent`
`reboot`

Not sure why installing gnome desktop environment did the trick, though.

**Comment by mig8447** [comment]
@godblesslancek This issue in particular has nothing to do with Ubuntu

**Comment by azeer-esmail** [comment]
installing SPICE Agent, QEMU Agent and SPICE WebDAV on the guest worked for me:
[linux](https://docs.getutm.app/guest-support/linux/)
[windows](https://docs.getutm.app/guest-support/windows/)

**Comment by adespoton** [comment]
How does that work?  Guest is macOS 12.  SPICE is still just for Linux and Windows isn’t it?  Or did someone succeed in compiling a version that works with macOS?My solution is currently to use screen sharing between the host and guest and run the guest headless; screen sharing includes a shared clipboard and file transfer.On Dec 21, 2023, at 5:17 AM, azeer-esmail ***@***.***> wrote:﻿
installing SPICE Agent, QEMU Agent and SPICE WebDAV on the guest worked for me:
linux
windows

**Comment by azeer-esmail** [comment]
> How does that work?  Guest is macOS 12.  SPICE is still just for Linux and Windows isn’t it?  Or did someone succeed in compiling a version that works with macOS?My solution is currently to use screen sharing between the host and guest and run the guest headless; screen sharing includes a shared clipboard and file transfer.On Dec 21, 2023, at 5:17 AM, azeer-esmail ***@***.***> wrote:﻿ installing SPICE Agent, QEMU Agent and SPICE WebDAV on the guest worked for me: linux windows —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

my bad didn't see that guest is macOS as well.

**Comment by mbwmbw1337** [comment]
> Incase you have trouble doing the screen share trick, follow these steps:
> 
> **On the Guest machine (the UTM virtual machine):**
> 
> 1. Open System Settings > General > Sharing
> 2. Turn on Screen Sharing
> 3. Click the "i" symbol next to Screen Sharing and change "Allow Access" to "All Users"
> 
> **On the Host Machine (your real computer):**
> 
> 1. Open Finder
> 2. In the left sidebar under "Locations" click the "Network" tab
> 3. You will see your virtual machine in there. It will be named something like "[NAME]'s Virtual Machine". Right click on it and select "Screen Share"
> 4. Input the Username and Password for your Guest machine
> 
> At this point will have two windows open for interacting with the Guest machine:
> 
> * The UTM window - it will be named whatever you called the UTM machine when you created it
> * The Screen Share window - it will be named "[NAME]'s Virtual Machine"
> 
> Use the Screen Share window as your main window for interacting with the Guest desktop. You'll be able to move files and copy/paste between the host and guest machines easily.
> 
> The other UTM window needs to remain open because closing it will shut down the guest machine. I just minimize it to avoid confusion.

Thank you for this!

**Comment by josfaber** [comment]
Seeing all sorts of answers for users on desktop environments. I'm having a clean ubuntu server installed via netinstaller, not ready for ssh or remote yet. I just like to copy/paste between my mac and ubuntu terminal running in utm. Is that even possible?

**Comment by Crown0815** [comment]
> Seeing all sorts of answers for users with desktop environments in their vm's. I'm having a clean Debian server installed via netinstaller, not ready for ssh or remote yet. I just like to copy/paste simple commands or urls between my mac and Debian terminal running in utm. Is that even possible? I installed `spice-vdagent` and `spice-webdavd`

Same issue here (Ubuntu Server). I just want to paste commands into the terminal, but nothing seems to work.

**Comment by kmatheussen** [comment]
> > Seeing all sorts of answers for users with desktop environments in their vm's. I'm having a clean Debian server installed via netinstaller, not ready for ssh or remote yet. I just like to copy/paste simple commands or urls between my mac and Debian terminal running in utm. Is that even possible? I installed `spice-vdagent` and `spice-webdavd`
> 
> Same issue here (Ubuntu Server). I just want to paste commands into the terminal, but nothing seems to work.

Not related to the ticket, but I'll answer anyway (it's been answered many times in other threads already). Trick is, at least for me and a few others, is to run the spice-vdagent command as your own user (not as root).

**Comment by Crown0815** [comment]
@kmatheussen, thank you for the tip. Unfortunately, running the `spice-vdagent` command did not change anything.
Neither `[CMD] + [V]`, nor `[CTRL] + [V]`, nor `[CTRL] + [SHIFT] + [V]` paste previously copied text into the terminal.

**Comment by Crown0815** [comment]
@kmatheussen That maybe. I am not familiar with it though. What is `X` and how would I check if I am running it?

**Comment by kmatheussen** [comment]
Sorry for hijacking your thread. The "X" comment was about making
copy-paste working when running a debian client, so it's not relevant for
running a mac client.
X is the most common GUI system on Linux.

**Comment by nashyvan** [comment]
> Seeing all sorts of answers for users with desktop environments in their vm's. I'm having a clean Debian server installed via netinstaller, not ready for ssh or remote yet. I just like to copy/paste simple commands or urls between my mac and Debian terminal running in utm. Is that even possible? I installed `spice-vdagent` and `spice-webdavd`

I also installed Debian without DE (Desktop Environment) and WM (Window Manager). You need to install Xorg with Window Manager (I use i3).
```apt install xorg i3 alacrity```

Copy/Paste doesn't work for me in

**Comment by mykolenkomitya** [comment]
> > Seeing all sorts of answers for users with desktop environments in their vm's. I'm having a clean Debian server installed via netinstaller, not ready for ssh or remote yet. I just like to copy/paste simple commands or urls between my mac and Debian terminal running in utm. Is that even possible? I installed `spice-vdagent` and `spice-webdavd`
> 
> Same issue here (Ubuntu Server). I just want to paste commands into the terminal, but nothing seems to work.

If you use Ubuntu Server as Guest machine, just open Terminal on your Host machine and connect to Ubuntu Server via SSH `ssh <user>@<ip>`

**Comment by briskerkazoos** [comment]
I purchased UTM from the App Store because I really enjoy the app and want to support its development. However, I'm forced to rely on VirtualBuddy for macOS virtualization due to this ongoing clipboard sharing issue that has been open for over two years. It's a bit frustrating to see this feature missing when nearly every other macOS virtualization solutions support clipboard sharing with macOS guests.

I understand that implementing new features can be complex, but I believe this issue is making macOS virtualization a hassle to use if not entirely unusable. I would appreciate it if this issue could be prioritized, as it has a significant impact on my daily workflow.

**Comment by singularity-s0** [comment]
I wonder if we can somehow make the VirtualBuddy Guest app work in UTM too?

**Comment by mmto-io** [comment]
> I purchased UTM from the App Store because I really enjoy the app and want to support its development. However, I'm forced to rely on VirtualBuddy for macOS virtualization due to this ongoing clipboard sharing issue that has been open for over two years. It's a bit frustrating to see this feature missing when nearly every other macOS virtualization solutions support clipboard sharing with macOS guests.
> 
> I understand that implementing new features can be complex, but I believe this issue is making macOS virtualization a hassle to use if not entirely unusable. I would appreciate it if this issue could be prioritized, as it has a significant impact on my daily workflow.

for what it's worth i am using the screen sharing method mentioned by other users in the chain and while it's not ideal, does work quite well for my daily tasks of needing to copy and paste between the VMs. have you gave that a try?

**Comment by singularity-s0** [comment]
> for what it's worth i am using the screen sharing method mentioned by other users in the chain and while it's not ideal, does work quite well for my daily tasks of needing to copy and paste between the VMs. have you gave that a try?

Screen sharing does work, but the quality isn’t ideal. If I have to rely on these workarounds, I might as well just use VirtualBuddy or another virtualization software that already supports native clipboard sharing. After all, they all use the same Apple Virtualization framework on macOS, so there's not much difference. The main reason I prefer UTM for macOS virtualization is that I don’t want to clutter my Mac with multiple virtualization apps.

**Comment by briskerkazoos** [comment]
Wow that was quick. Thank you @osy

**Comment by osy** [comment]
v4.6.2 added clipboard sharing between macOS 15 guest and macOS 15 host. Earlier guests are not supported due to a bug in Apple's VirtIO drivers.

**Comment by smayer97** [comment]
There is a workaround for any macOS older than 15... using Screen Sharing. "To have copy-paste enabled in UTM for macOS with ARM64 M1 or M2, you can connect to your guest OS via "Screen Sharing"". See [simple instructions](https://stackoverflow.com/a/73948781/8884051)

**Comment by sky96111** [comment]
> v4.6.2 added clipboard sharing between macOS 15 guest and macOS 15 host. Earlier guests are not supported due to a bug in Apple's VirtIO drivers.

I tested it on host macOS Sequoia 15.6 (24G84), VM macOS Sequoia 15.6 (24G84), UTM 4.6.5 (108). But both copy text in VM and paste it to host, and copy text in host and paste it into VM not work. Am I missing something? Clipboard shearing in UTM setting is enabled.

**Comment by lam1011** [comment]
> > v4.6.2 added clipboard sharing between macOS 15 guest and macOS 15 host. Earlier guests are not supported due to a bug in Apple's VirtIO drivers.
> 
> I tested it on host macOS Sequoia 15.6 (24G84), VM macOS Sequoia 15.6 (24G84), UTM 4.6.5 (108). But both copy text in VM and paste it to host, and copy text in host and paste it into VM not work. Am I missing something? Clipboard shearing in UTM setting is enabled.

also having trouble, just had UTM installed not long ago

**Comment by NorthernMan54** [comment]
To set this up you need to install the guest tools

<img width="900" height="524" alt="Image" src="https://github.com/user-attachments/assets/87b4d2ac-67e7-4038-aed9-c8036c9ffa59" />

**Comment by sky96111** [comment]
> To set this up you need to install the guest tools
> 
> <img alt="Image" width="900" height="524" src="https://private-user-images.githubusercontent.com/19808920/528130826-87b4d2ac-67e7-4038-aed9-c8036c9ffa59.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjYyMDIzNzgsIm5iZiI6MTc2NjIwMjA3OCwicGF0aCI6Ii8xOTgwODkyMC81MjgxMzA4MjYtODdiNGQyYWMtNjdlNy00MDM4LWFlZDktYzgwMzZjOWZmYTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjIwVDAzNDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2YjNlMTY5YmU3YTMzOGEzYjA5YzIxZWE0ZWIyMmMyODY1ZWExNjAyYzY4NmZlM2JlYTJiYzRiMzU0NGI5NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Xd2WSHnPBV9ZOgh3ECPBnyy9S4gIeUP_SH0Io2ypjCE">

Thanks! It works for me

**Comment by xepozz** [comment]
Still have problems, UTM 4.7.5, Macos Tahoe 26.5 on both sides.

It worked when I setup everything, but a day after stopped working, as well as input capturing: cmd+tab, cmd+shift+4 dont work, but control+tab and others do.
cmd+tab was working well
