### ISSUE TITLE
Auto-eject removable drives on VM start if the linked file was (re)moved

### ISSUE THREAD

**Issue by berkaey** [utmapp/UTM#3575]
Hi,

I'm got the this thin morning  "error trying to restore removable drives failed create bookmark", and find out if you won't eject disk before disk path is changed or removed. VM just won't run and gives above error. I think, It just should run and eject automatically if there is no file on that path.

**Configuration**
* UTM Version: 3.0.4
* OS Version: 12.2
* Apple Silicon

**Comment by ktprograms** [comment]
@osy Would this be similar to how shortcut VMs are automatically deleted if the source `.utm` doesn't exist?

**Comment by osy** [comment]
I think we still show that error but eject the drive so when you start it again it works. That way it doesn't hide the error and you don't know why your install iso isn't mounting.

**Comment by ktprograms** [comment]
On Mon Feb 14, 2022 at 11:13 AM +08, osy wrote:
> I think we still show that error but eject the drive so when you start it again it works. That way it doesn't hide the error and you don't know why your install iso isn't mounting.

Ok, makes sense. Should I implement it or are you going to?

**Comment by osy** [comment]
I probably will, it’s pretty simple. Can you make the changes to the console colour PR so I can merge it for the next release?

**Comment by ktprograms** [comment]
On Mon Feb 14, 2022 at 11:18 AM +08, osy wrote:
> I probably will, it’s pretty simple.

Great, thanks!

> Can you make the changes to the console colour PR so I can merge it for the next release?

Still waiting for an answer on my SO question about the drift.

Refresh my memory, was there anything else that needs changing?
