### ISSUE TITLE
Multiple network interfaces

### ISSUE THREAD

**Issue by ptiyoda** [utmapp/UTM#3585]
Hi guys,

Is a way to have a multiple network interfaces on a single VM?
I tryed to modify the config.plist file and add array after <key>Networking</key> but it's not working.

Do you think is possible?

Thanks a lot

**Comment by adespoton** [comment]
Just my opinion, but it should be possible using an extra set of flags in the QEMU section, with a different label for the new network interface.  Worth trying, anyway.  Don't make the second one Shared Networking; that probably won't work.

**Comment by osy** [comment]
The feature has been added in v4.0.
