### ISSUE TITLE
IOS More Ram allocation for iOS 15 

### ISSUE THREAD

**Issue by stossy11** [utmapp/UTM#3591]
**com.apple.developer.kernel.increased-memory-limit**

A Boolean value that indicates whether core features of your app may perform better with a higher memory limit on supported devices.

https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_kernel_increased-memory-limit?changes=latest_beta

**Comment by adespoton** [comment]
Well that's definitely useful!  Thanks for bubbling that up!

**Comment by ktprograms** [comment]
@stossy11 It's already implemented: https://github.com/utmapp/UTM/blob/master/Platform/iOS/iOS.entitlements#L5-L6

See also https://github.com/utmapp/UTM/pull/3318
