### ISSUE TITLE
Import files by dragging into the VM directly.

### ISSUE THREAD

**Issue by ty-yqs** [utmapp/UTM#3599]

**Comment by adespoton** [comment]
To expand on this, you'd like to see the ability to do file transfer by dragging a file from the host file manager into the guest window to copy the file to the guest filesystem?
I presume you'd also like to see the inverse (drag a file from the guest system to the host file manager to copy it out)?

I don't believe SPICE supports this, nor QEMU, so it'd be a major development for UTM to implement it.  Seems like it should be possible, but it would need custom drivers or client software written for the guest system, and some sort of special handler written in for the UTM interface.  Not sure this is at all possible in a sandboxed environment.

**Comment by PsychoH13** [comment]
I would love to see that feature too, this is something that other softwares like Parallels and VMWare support, sadly they are only virtualization softwares and not emulators.
