### ISSUE TITLE
Request: Fakesign all the binaries in the .ipa for jailbroken users to use with AppSync

### ISSUE THREAD

**Issue by jakeajames** [utmapp/UTM#36]
This way jailbroken users don't have to sign the app (won't cause any trouble for non-jailbroken ones). For every macho just do: ldid -S /path/to

**Comment by osy86** [comment]
1. Does this work with the required entitlements? I.e. has this been tested? I don’t have a jailbroken device.
2. Is the preferred format IPA or DEB?

**Comment by basti564** [comment]
1. Yes, this should work. (I don't know if anyone has tested it with UTM specifically)
2. IPA, because most app sideloaders(iFunbox, impactor and co.) only accept IPA files.

**Comment by osy86** [comment]
I'm asking 1 specifically for someone to test it because UTM requires `get-task-allow` entitlement. I'm not sure if ldid will give it. My hunch is no.

**Comment by basti564** [comment]
Do you have a fakesigned IPA? I could try to install it and test if it works

**Comment by osy86** [comment]
No, I don't.

**Comment by basti564** [comment]
Sorry, but initially answered because I knew the answer for your question 2. about the preferred format of apps is.

**Comment by basti564** [comment]
I made a [script](https://github.com/utmapp/UTM/files/4238640/fakesigner.sh.zip) that automatically fakesigns an .ipa file using ldid from Homebrew.
Just type "path/to/fakesigner.sh path/to/UTM.ipa" and it will produce a file called [UTM.ipa-fakesigned.ipa](https://drive.google.com/file/d/11fh_igHhkAVYUA0KMYQ-NVr2EFcAU2mV/view?usp=sharing)
This build has been tested by installing it on a jailbroken iPhone 7 with AppSync Unified via iFunBox and booting a VM

**Comment by zxq2233** [comment]
#43 please help me!

**Comment by baconglucose** [comment]
> I made a [script](https://github.com/utmapp/UTM/files/4238640/fakesigner.sh.zip) that automatically fakesigns an .ipa file using ldid from Homebrew.
> Just type "path/to/fakesigner.sh path/to/UTM.ipa" and it will produce a file called [UTM.ipa-fakesigned.ipa](https://drive.google.com/file/d/11fh_igHhkAVYUA0KMYQ-NVr2EFcAU2mV/view?usp=sharing)
> This build has been tested by installing it on a jailbroken iPhone 7 with AppSync Unified via iFunBox and booting a VM

Your script didn't work for me. It repackaged the `ipa` but I still couldn't install it. However, I was able to install the binary you provided.

For anyone coming across this with a jailbroken device and `appsync`. You don't need tools like iFunBox because the command line tool `appinst` should have been installed with `appsync` (It's from the same creator and can be found on her repository).
Use it like this (with a mobile terminal or ssh):
```bash
appinst <path to ipa file>
```

**Comment by jakeajames** [comment]
There are no limitations when fakesigning, you can have any kind of entitlement (you can even disable sandbox etc) with it. The preferred format is .ipa, debs are used if distributed with Cydia.

**Comment by osy86** [comment]
Please check https://github.com/utmapp/UTM/releases/download/v0.2-fakesign/UTM.ipa to see that the fake sign has worked.

**Comment by basti564** [comment]
It works 👌

**Comment by osy86** [comment]
We also need someone to test #67 basically compare v0.2 and v0.2 fakesign and see if the fakesign version supports larger memory sizes.

In my personal experience, I have Windows 7 on iPad 2018 with 2GB of RAM. On v0.1 this is fine but on v0.2 it crashes on boot. I don't have a JB device to test, so I don't know if the fakesign version can bypass the iOS memory limits.

**Comment by The-SamminAter** [comment]
I’ll test in similar conditions using the fakesigned on my jailbroken phone @osy86

**Comment by The-SamminAter** [comment]
@osy86 I’m having problems: https://github.com/utmapp/UTM/issues/32#issuecomment-590649167
