### ISSUE TITLE
Nothing to boot: No such file or directory (http://ipxe.org/2d03e13b)

### ISSUE THREAD

**Issue by TheoSanto** [utmapp/UTM#360]

**Comment by TheoSanto** [comment]
Once set drivers, Virtual machine doesn't start. I tried with different ISO but i have the same errors.
i have IOS 13.3.1
My output:





Boot failed: could not read the boot disk

Booting from Floppy. . . 
Boot failed: could not read the boot disk

Booting from DVD/CD. . .
Boot failed: Could not read from CDROM (code 0003)

Booting from ROM. . .

iPXE (PCI 00:04.0) starting execution. . .ok
iPXE initialising devices. . . ok



iPXE 1.0.0+ (de45) -- Open Source Network Boot Firmware -- http://ipxe.org

Features: DSN HTTP iSCSI TFTP AoE ELF MBOOT PXE bzImage Menu PXEXT


net0: 52:54:00:12:34:56 using rt18139 on 0000:00:04.0 (open)
     [Link:up, TX:0  TXE:0  RX:0  RXE:0]
Configuring (net0 52:54:00:12:34:56)=. . . . . . ok
net0: 10.0.2.15/255.255.255.0 gw 10.0.2.2
Nothing to boot: No such file or directory (http://ipxe.org/2d03e13b)

No bootable device.

**Comment by osy86** [comment]
https://getutm.app/guide/#quick-start

**Comment by TheoSanto** [comment]
> https://getutm.app/guide/#quick-start
Thanks for replying,
I followed the procedure step by step but i still have the same problem.

**Comment by osy86** [comment]
You likely have an ISO that’s not bootable. You can confirm this by trying it with VMware or virtual box.

**Comment by TheoSanto** [comment]
> You likely have an ISO that’s not bootable. You can confirm this by trying it with VMware or virtual box.

Thanks a lot, i’ve found an error in ISO file (probably due to partial download). Now i’ve reinstalled ISO and it works!

**Comment by Rtoax** [comment]
Got the same problem

**Comment by WiiUOwnerWithBannedNNID** [comment]
> Once set drivers, Virtual machine doesn't start. I tried with different ISO but i have the same errors. i have IOS 13.3.1 My output:
> 
> Boot failed: could not read the boot disk
> 
> Booting from Floppy. . . Boot failed: could not read the boot disk
> 
> Booting from DVD/CD. . . Boot failed: Could not read from CDROM (code 0003)
> 
> Booting from ROM. . .
> 
> iPXE (PCI 00:04.0) starting execution. . .ok iPXE initialising devices. . . ok
> 
> iPXE 1.0.0+ (de45) -- Open Source Network Boot Firmware -- http://ipxe.org
> 
> Features: DSN HTTP iSCSI TFTP AoE ELF MBOOT PXE bzImage Menu PXEXT
> 
> net0: 52:54:00:12:34:56 using rt18139 on 0000:00:04.0 (open) [Link:up, TX:0 TXE:0 RX:0 RXE:0] Configuring (net0 52:54:00:12:34:56)=. . . . . . ok net0: 10.0.2.15/255.255.255.0 gw 10.0.2.2 Nothing to boot: No such file or directory (http://ipxe.org/2d03e13b)
> 
> No bootable device.

Try forcing PS/2 legacy. It worked for me in Windows 2000
