### ISSUE TITLE
Crash when selecting item in sidebar or resizing window

### ISSUE THREAD

**Issue by salvomic** [utmapp/UTM#3612]
**Describe the issue**
Opening an item window and expanding it to show all fields, the macOS spinning wheel appears and UTM hangs.

**Configuration**
* UTM Version: 3.0.4 (46)
* OS Version: Monterey 12.3 beta
* Intel or Apple Silicon? M1 pro ARM Silicon

**Crash log**
**Debug log**
No log possible.

**Comment by osy** [comment]
Can you explain what “an item window” is? Preferably attach a screenshot?

**Comment by salvomic** [comment]
yes,
sure. Thank you for your diligent reply.

Sorry, I’m not native English speaker.

I mean the windows of a virtual machine.
i.e. for now I’m trying to get a working Solaris 11 VM (please, help for this! Solaris starts book but then has no network so it doesn’t complete the installarion...) and OpenStep, but with every window, if I expand the right part, when the two dropdown field below are showed, the spinning wheel freezes the app.

Salvo



PS: It would be really nice to have VMs for Solaris 11.4, OpenStep and Haiku in the gallery :)

Thank you

**Comment by osy** [comment]
I’m still not clear what the “two drop down field” refers to. Can you please provide a screenshot?

**Comment by salvomic** [comment]
Normally these two fields (dropdown) remain half-hidden unless the scroll bar slides.

If you expand the entire window to make them appear completely (with mouse in one of the side of the window), to avoid the scroll bar use, the spinning wheel appears and the app remains waiting, in fact then it must be closed because you no longer have control of it.

Salvo

**Comment by osy** [comment]
Now I am more confused, you mentioned this is in the virtual machine window but there isn’t a scroll bar in that window. Are you referring to something that happens int the guest?

Any chance you can attach a screenshot? That would clear things up really quickly.

**Comment by salvomic** [comment]
Sorry again,
I wrote very badly.

So, four simple steps:

1. I open the main UTM window

2. I select an item on the left

3. I extend the window to see all the information on the right without having to use the scroll bar, until the last two fields at the bottom are visible.

4. the blockage happens.

Even simpler.

The screenshots of before could be enough, I can't do better, sorry :)

Salvo

**Comment by osy** [comment]
Oh if you made an attachment, I don’t think it made it to GitHub. Otherwise please follow https://support.apple.com/en-us/HT201361

**Comment by salvomic** [comment]
I found that this behaviour is related to scrollbar settings in macOS:

If is set “Automatically based on the mouse or trackpad” (the one I always use) or “Always” the lock happens, if “While scrolling” option is set it does not happen.

I tested it various times here now.

I hope this can help.

Thank you for your attention

**Comment by salvomic** [comment]
I mean: in System Preference -> General


::::
I found that this behaviour is related to scrollbar settings in macOS:

If is set “Automatically based on the mouse or trackpad” (the one I always use) or “Always” the lock happens, if “While scrolling” option is set it does not happen.

I tested it various times here now.

I hope this can help.

Thank you for your attention

**Comment by conath** [comment]
@salvomic Please open [the issue website](https://github.com/utmapp/UTM/issues/3612#issuecomment-1034027176) to upload your screenshots, at the bottom of the page there is a comment field where you can drop the files. It will not work if you reply via email with an attachment. Thank you.

**Comment by jkleckner** [comment]
I was able to use the above workaround of changing the scroll bar behavior to "when scrolling" to get out of a state of the main UTM application persistently hanging whenever I selected a virtual machine.

It first started happening when I stretched the main window displaying the virtual machines to be bigger.

If I returned the scroll bar behavior preference to "always" and I was able to get the spinning beach ball hang by dragging a corner of that window around to make it small then large and eventually it would start to hang after some resize.

Again returning the preference to "when scrolling" eliminated the hang.

**Comment by osy** [comment]
@jkleckner is this on UTM 3.1.x beta?

**Comment by jkleckner** [comment]
Yes, version 3.1.1 (48) also was able to reproduce the problem when the preference for scroll bar behavior is "always".

**Comment by jkleckner** [comment]
They way to make it more reproducible is to select one VM before dragging the bottom right corner around to make it minimum then as large as possible then move your mouse into the area of the scroll bar.  I can get it pretty fast that way.  No need to start any virtual machines (which you don't want to do since a force quit will kill them).
It does seem to need the selection of a VM to stimulate the problem.

I did a "sample" of the process while hung and am attaching it in case it is useful.
Also the problem report of the Force Quit as sent via the reporter with a link to this issue.

[Sample of UTM.txt](https://github.com/utmapp/UTM/files/8162632/Sample.of.UTM.txt)

[ForceQuitReport.txt](https://github.com/utmapp/UTM/files/8162699/ForceQuitReport.txt)

**Comment by jkleckner** [comment]
And here is the Force Quit report for the beta version:
[ForceQuitReport-Beta.txt](https://github.com/utmapp/UTM/files/8162756/ForceQuitReport-Beta.txt)

**Comment by osy** [comment]
This is a SwiftUI but. The following code can reproduce it:

```swift
struct ContentView: View {
    var body: some View {
        ScrollView {
            Rectangle().aspectRatio(CGSize(width: 16, height: 9), contentMode: .fill)
            Rectangle().frame(height: 400)
        }
    }
}
```
