### ISSUE TITLE
-vnc command crashes UTM

### ISSUE THREAD

**Issue by Anappledevlovperlover** [utmapp/UTM#3620]
I am using UTM on iOS 15, tethered with Jitterbug.
I attempted to try -vnc 127.0.0.1:2 to use it as a VNC server.
However, everytime I connect to VNC server, server UTM VM crashes.
Any solutions?

**Comment by conath** [comment]
Unfortunately, the QEMU VNC is not supported in UTM. Instead, you could install a VNC server in your VM and use port forwarding to access it from your host or another device.

@osy do we have plans to fix QEMU VNC?

**Comment by Anappledevlovperlover** [comment]
@conath 
I heard there is a way to imstall Native QEMU on Jailborken iOS devoce terminal.
Do you know how..? I tried with NewTerm2 but I can’t figure out the commands….

**Comment by conath** [comment]
Sorry, I don't know.

**Comment by osy** [comment]
Duplicate of #3528
