### ISSUE TITLE
Network configuration when host machine uses VPN

### ISSUE THREAD

**Issue by iSamBa** [utmapp/UTM#3634]
My host machine uses VPN to connect to the company network. I am willing to access a repository in that server from the VM, and I keep getting a time out failure.
I am using a Shared Network configuration, and tested also with the bridged one with no success

**Configuration**
* UTM Version: 3.0.4 (46)
* OS Version: 12.2.1
* Intel or Apple Silicon? Apple Silicon

**Comment by iSamBa** [comment]
The solution is to use Emulated VLAN, that will use port forwarding from the host machine.
Found the solution here : https://github.com/utmapp/UTM/issues/3238#issuecomment-959911107

**Comment by osy** [comment]
https://github.com/machyve/xhyve/issues/84

Seems to be an issue with vmnet. Reopening for a proper fix.

**Comment by stefan1983** [comment]
Any update here?

**Comment by rzzldzzl** [comment]
Your VPN might disable IP Forwarding.  That is the case with the AWS Client VPN.

My experience is -
Guest can access networks as expected (IP Forwarding is enabled)
After the hosts connects to the AWS Client VPN, the guest looses access to anything but the host.  (IP Forwarding is disabled)
Manually enabling IP Forwarding restores connectivity from the guest.

After connecting your VPN (on the host), try enabling IP Forwarding on the host:
`% sudo sysctl -w net.inet.ip.forwarding=1
net.inet.ip.forwarding: 0 -> 1`
