### ISSUE TITLE
Specify serial number for macOS guests using Apple Virtualization

### ISSUE THREAD

**Issue by sclsj** [utmapp/UTM#3639]
I want to specify a serial number for macOS 12 virtual machine. I remembered reading somewhere that this seems to be supported by Apple Virtualization framework but can't find any documentation about it. 

Note: In Parallels Desktop (Intel only), you set the boot flag "devices.smbios.serial=<serial here> to specify a serial number. There is no such option for the ARM version of Parallels Desktop, which is what I've tried.

Is this possible to implement in UTM?

**Comment by osy** [comment]
Unfortunately, as you may have suspected, this isn't permitted by Apple APIs. You may check out https://github.com/saagarjha/VirtualApple for an implementation that uses private Apple APIs.

**Comment by sclsj** [comment]
https://github.com/saagarjha/VirtualApple do not provide any documentations. Do you have any more information to share as to how I can specify a serial number?

**Comment by osy** [comment]
I have no idea. I’m saying that’s the project you should reach out to if you want to do things outside of what apple has allowed. I don’t know if it’s actually possible to do at all (even outside of public apis). But this isn’t the right project to ask.

**Comment by sclsj** [comment]
OK. Thank you for your help and clarifications!
