### ISSUE TITLE
Can’t seem to run VMs from the vm-downloads 

### ISSUE THREAD

**Issue by Vweston** [utmapp/UTM#364]
Help needed. I cannot get downloaded VMs to work. But I did create a dos VM that does work.
I am on UTM 1.0-rc4 On 10.5” iPad Pro running iPadOS 13.5 (latest public beta)
I also can’t get the reactOS vom to run either. Am I missing something??
 

**To Reproduce**

I downloaded the Debian 10.4 (osy’s Developer Edition) ARM VM. 
Used The Unarchiver app on Mac to uncompress. 
air dropped the .UTM to my files app. 
created a new VM in UTM. System aarch64 with virt 
added the Drive Path Debian Arm.UTM, Image Type: disk location: virtio (I also tried ide)

Saved & then try to run newly created VM.

I get QEMU exited with an error....
Debian Arm.utm,if=vitro,media=disk,id=drive0: A regular file was expected by the ‘file’driver, but something else was given.

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here.

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/4712743/debug.log)
![IMG_5545](https://user-images.githubusercontent.com/17938259/83438736-2cb0e580-a3ff-11ea-8e99-e8421f9a3c9c.jpeg)

**Upload VM**
If possible, upload the `.utm` you are experiencing an issue with. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by osy86** [comment]
Not sure I understand what you did there. You should be able to open the .utm directly with UTM (airdrop asks you what app you want to open with). Then you just press the play button. You shouldn’t need to touch any settings.

**Comment by Vweston** [comment]
Thank you for the fast response. Just as I thought, I was over thinking this. I got at least to the Debian login & actually running the reactOS. Now for some fun testing.

Thx again..

-- VW
