### ISSUE TITLE
Warn before copying UTM file

### ISSUE THREAD

**Issue by fulldecent** [utmapp/UTM#3640]
**Describe the issue**

**Test case:**

1. Put a UTM file on your desktop or external drive
2. Double click the file

**Expected outcome:**

A warning pops up telling you:

> The file `FILENAME` (`XXX GB`) will be copied to `PATH`. After that, UTM will load the copy. This is a necessary part of how UTM works.
>
> OK / Cancel

**Actual outcome**

UTM silently copies this huge file to an invisible location you probably will never know about. And the file that is opened is not the file you double clicked on. Years later when your hard drive is full you will have no idea why.

## Configuration
* UTM Version: Version 3.0.4 (46) // paid App Store version
* OS Version: 12.0.1 (21A559)
* Intel or Apple Silicon? Apple Silicon

**Comment by ktprograms** [comment]
Note that in 3.1.0 (Beta), support has been implemented for `.utm` bundles being stored outside the app container (this so-called invisible location), so when a `.utm` bundle is double clicked, it will no longer be copied, instead a reference (bookmark) to it will be stored.

**Comment by osy** [comment]
Right closing since the behavior has already been implemented in 3.1.x.
