### ISSUE TITLE
com.Metal.CompletionQueueDispatch SIGSEGV Occurred when using virtio-ramfb-gl

### ISSUE THREAD

**Issue by sokurenko** [utmapp/UTM#3660]
It looks like virtio-ramfb-gl is not stable and sometimes might crash or freeze UI, while ssh would continue working.
[utm_crash.txt](https://github.com/utmapp/UTM/files/8111776/utm_crash.txt)
[command.txt](https://github.com/utmapp/UTM/files/8111785/command.txt)

Running ubuntu 20.04 arm with Wayland.

**Comment by osy** [comment]
Duplicate of #3519
