### ISSUE TITLE
enabling full graphics on the arch linux vm results in a black screen

### ISSUE THREAD

**Issue by moham96** [utmapp/UTM#3661]
**Describe the issue**
enabling full graphics on the archlinux vm imported from the gallery result in a blank black screen

**Configuration**
* UTM Version: 3.0.4 (46)
* OS Version: 12.2.1
* Intel or Apple Silicon? apple silicon

**Crash log**
no crash

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/8113245/debug.log)

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by osy** [comment]
There is no graphics support for that vm. It says so on the website. Try one of the other ones.

**Comment by moham96** [comment]
> There is no graphics support for that vm. It says so on the website. Try one of the other ones.

Ok but why? Debian runs fine with graphics what prevent graphics on archlinux can we get a technical explanation?
Thanks

**Comment by osy** [comment]
ArchLinux was installed with a minimal set of packages. No GUI supporting packages (such as X11) are installed. If you know how to use Linux you can do it yourself but that is beyond the scope of what we're willing to provide support for.

**Comment by moham96** [comment]
I do know how to configure archlinux for graphical interface but i was baffled because after i installed the required packages and rebooted to enable the full graphical interface from the settings the vm booted to a black screen.

So for anyone finding this issue this is what happened: because archlinux is a rolling release, you can't just install packages without updating the entire system so after updating the archlinux system (`pacman -Syu`) and rebooted with gui enabled the problem was that the `linux-aarch64` package was updated (which updated the kernel image along with the kernel modules) so after rebooting and enabling the gui option the system tries to load the virtio-gpu module for the old kernel but it failes because the kernel lives outside the `.qcow2` drive so the real kernel that gets booted is not updated but the kernel modules does get updated.
