### ISSUE TITLE
UTM debug logs expose your real location if you enabled VMs running in the background

### ISSUE THREAD

**Issue by BluDood** [utmapp/UTM#3667]
**Describe the issue**
Enabling "Continue running VM in the background" and allowing location access, will output your current location into the debug log. If you did not allow precise location, it will still show a location near you. This is a serious privacy issue, and we should look into the issues here and the Discord chats to see if other people got it leaked.

**Configuration (required)**
* UTM Version: 3.1.0
* OS Version: 15.1
* Device Model: iPad Pro M1
* Is it jailbroken (name jailbreak used)? no
* How did you install UTM? SignTools

**Crash log**
Not relevant

**Debug log**
2022-02-22 21:39:57:165 UTM[xxx:xxxxx] **Current location: xx.xxxxxxxxxxxx xx.xxxxxxxxxxxx**

**Upload VM**
Any VM that has debug logging enabled

**Comment by DownGnu** [comment]
Also, it crashes UTM and takes me to the home screen

Configuration 
UTM/UTM SE Version: 3.1.0
iPados: 15.3.1
Device Model: iPad Pro M1
Is it jailbroken (name jailbreak used)? no
How did you install UTM? Altstore
