### ISSUE TITLE
Feature request: Save last screen resolution of VM

### ISSUE THREAD

**Issue by BluDood** [utmapp/UTM#3669]
Every time I start a VM i have to press the icon to resize the screen. While this is obviously not a huge problem, it would still be a cool feature to have. Either it saves the screen resolution from last time, or you can set it in the VMs config.

**Comment by osy** [comment]
Are you talking about macos or iOS? iOS should have this already…

**Comment by BluDood** [comment]
Sorry for not specifying that, it's iOS. It doesn't work for me, is that a feature?

**Comment by osy** [comment]
Yeah but the refactor might have broken it. Does it work in 2.x/3.0?

**Comment by BluDood** [comment]
I'll download some older versions and see
