### ISSUE TITLE
Add USB options to Input configuration

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#3674]
I would like to be able to switch USB input device emulation on and off via the Input tab. Maybe a segmented control with the options "PS/2 keyboard", "PS/2 keyboard and mouse" and "USB Keyboard and Mouse" could be added to replace the "Legacy PS/2 Mode" toggle.

On that note, it would make sense to move the "USB 3 XHCI support" toggle to the Input tab as well and have all of the devices connect to this USB bus. Even better, maybe we could allow choosing UHCI, ECHI and XHCI via segmented control? (if one chooses UHCI, that might mean we have to disable the USB Sharing feature - IIRC that can only use EHCI or XHCI)

## Back story (as mentioned in #3031)

UTM used to add a `-device usb-kbd` to the QEMU parameters unless "Legacy PS/2" was enabled in the Input tab. In an update, this was removed because UTM will always add a PS/2 keyboard for compatible guests, regardless of the USB keyboard parameter.

However this change means that guest OSs that don't support PS/2 (namely Mac OS X / macOS) now don't receive keyboard input anymore. A workaround is to add the line `-device usb-kbd,bus=usb-bus.0` to the QEMU arguments tab, which restores the USB keyboard input.

**Comment by adespoton** [comment]
As an addition to this, Mac OSes (9.0.4, 10.0, 10.1) that use CUDA instead of PMU use "legacy" to enable ADB mouse and keyboard, not PS/2.  And CUDA doesn't support a USB bus, so providing a workaround via USB will only make things worse.

My current solution is to grab the mouse and keyboard while OpenBIOS is still loading; this forces UTM to use the ADB mouse and keyboard, so when the SPICE devices kick in, they don't affect the already-established mouse and keyboard connections.  Releasing the mouse and keyboard permanently loses them, however.  Once released, you can't get them back.

**Comment by osy** [comment]
> Even better, maybe we could allow choosing UHCI, ECHI and XHCI via segmented control? 

What is the use case for this? I always want to make sure that any additional UI will serve 90% of the users so we don't end up with hundreds of knobs for every little thing five years down the line.

**Comment by conath** [comment]
I’m happy with the changes here, would still prefer if the USB3/2 toggle was in the Input tab or maybe Drives tab. The issue is that the USB bus affects emulated USB disk transfer speeds, and it’s not intuitive to go to the Sharing tab to change the USB bus to 3.0. (Keeping the input device on USB 2 is fine with me)

**Comment by startergo** [comment]
> A workaround is to add the line `-device usb-kbd,bus=usb-bus.0` to the QEMU arguments tab, which restores the USB keyboard input.

I wish it restored it. I can use the keyboard without an issue in Snow Leopard, but not in Mavericks. And if I don't force the PS/2 controller even the mouse stops working. Both of them are not attached to a USB BUS in the ioregistry. If I can get Apple Remote Desktop connected this is my only option

**Comment by startergo** [comment]
I got it working:
<img width="1630" alt="image" src="https://github.com/utmapp/UTM/assets/7897244/1f99db7f-ed2c-4fe0-8b5c-36c3b34d821c">
Added OHCI (USB1.1) controller:
```
-device pci-ohci -device usb-kbd -device usb-tablet
```
https://en.wikibooks.org/wiki/QEMU/Devices/USB/Root#EHCI

**Comment by startergo** [comment]
After more testing here is what I found:
Mavercs as a guest OS:
A combination of `Use Hypervisor`, `force PS2 controller` and `-device pci-ohci -device usb-kbd -device usb-tablet` works fine. Anything else with `Use Hypervisor` leaves the keyboard and the mouse undetected.
`Use Hypervisor` turned off and `-device pci-ohci -device usb-kbd -device usb-tablet` or `-device keyboard` works fine for keyboard and mouse detection.
For 10.8.6 `-device pci-ohci -device usb-kbd -device usb-tablet` or `-device keyboard` or `force PS2 controller` are not required for proper detection of the keyboard and the mouse even with `Use Hyervisor` enabled
