### ISSUE TITLE
iOS Sensor support

### ISSUE THREAD

**Issue by upintheairsheep** [utmapp/UTM#3675]
Please browse the existing issues and filter by 'enhancement' to make sure this has not already been suggested!

1. Add Support for all the sensors on iOS devices for making the operating system and the hardware more together and for some research programs for feeding data. Optional for privacy reasons and to prevent crashes on unsupported Operating Systems. List of sensors to support:
- Gyroscope
- Accelerometer
- Barometer
- Proximity
- Ambient Light
- iBeacon
These are not sensors but they should be added
-NFC
- LiDAR (this is the most innovative feature of iPhone so far)
- Flashlight (if possible)
2. Additional camera & microphone related info
Make sure to include a few modes to the support. 1 mode is only 1 webcam which is the front or back camera, 2 mode is both the back and front camera is detected as separate cameras. 3 is all 4 cameras are detected as a single camera. Microphone has 2 modes, 1 is the regular microphone as only 1, pro mode has all 3 microphones as separate devices.

**Comment by osy** [comment]
I'll leave this open but to be honest, it's unlikely any of these would be done. It's a lot of work to 1) implement the QEMU device, 2) implement the bridge from iOS and QEMU, and 3) implement drivers on Linux/Windows for those device.

**Comment by upintheairsheep** [comment]
Closing: superseded by later issues, did not know that UTM was a GUI for QEMU at the time
