### ISSUE TITLE
Does nothing when I click on the settings button while running a vm

### ISSUE THREAD

**Issue by IIWare** [utmapp/UTM#368]
When I press the settings button, it doesn't do anything, was that meant to even be a button, or not functionable button?

https://user-images.githubusercontent.com/66434686/83788209-846c7c80-a69d-11ea-9794-2016476106c4.PNG

**Comment by osy86** [comment]
It’s not implemented in v1.0

**Comment by IIWare** [comment]
will it be functionable in the future versions?

**Comment by IIWare** [comment]
> It’s not implemented in v1.0

Ok, but will the settings button be clickable in the future releases/versions?

**Comment by osy86** [comment]
No idea, it may be removed. It’s only there because I needed an extra icon in the layout.

**Comment by IIWare** [comment]
Implemented in v2.0, the settings icon changed to a cd icon. thanks for implementing.

**Comment by cuj** [comment]
@osy Unrelated - Can you please delete all of my issues under this utmapp/UTM repository including this one? closing them is not enough. I am the author of these issues, but for some reason GitHub does not allow the author of an issue to delete their own, so I am requesting you to delete all of my issues including this one under utmapp/UTM. Thanks.

**Comment by osy** [comment]
Can you explain what your reason is? Usually public posts stay public because they involve other people who might have contributed to the thread. So if you delete it all it impacts them too.

**Comment by cuj** [comment]
I personally wasn't happy with the issues I created before, and I would like them to be deleted.

**Comment by osy** [comment]
Please reach out to GitHub support and see if they can remove your posts under GDPR rules. I cannot delete your posts without deleting the entire issue including contributions by other members.

**Comment by cuj** [comment]
You could not delete each of my issues 1 by 1 manually?
You can filter using search results to show only my issues:
https://github.com/utmapp/UTM/issues?q=is:issue+author:cuj

**Comment by cuj** [comment]
Hi @osy 
I need a response now - could you look at all of my issues in this repository (https://github.com/utmapp/UTM/issues?q=is:issue+author:cuj) and manually delete them one by one? If not, should I contact GitHub support to remove my issues like you said?
