### ISSUE TITLE
UTM Crashes when making Virtualised Windows 11 Operating System

### ISSUE THREAD

**Issue by mastergentar** [utmapp/UTM#3683]
When making a new VM, it crashes as soon as the VHDX is assigned, and outputs a crash log immediately.

**Configuration**
* UTM Version: 3.0.4
* OS Version: 12.0
* Intel or Apple Silicon? Apple Silicon

[log.txt](https://github.com/utmapp/UTM/files/8139438/log.txt)

**Comment by osy** [comment]
Bug is in `NumberTextFieldNew.body.getter (in UTM) (NumberTextField.swift:75)`. I think it may be a SwiftUI bug. Can you try updating to latest macOS Monterey and see if it still persists?

**Comment by conath** [comment]
@mastergentar Please consider upgrading your Mac to the latest version of macOS. There have been many system level bug fixes that improve the stability of UTM.
