### ISSUE TITLE
Saving snapshots fails when EFI is enabled

### ISSUE THREAD

**Issue by osy** [utmapp/UTM#3698]
This is due to pflash1: `Device 'pflash1' is writable but does not support snapshots`

See https://bugzilla.redhat.com/show_bug.cgi?id=1180955

**Comment by Sigma711** [comment]
How to solve it?

**Comment by svenstaro** [comment]
> How to solve it?

Stumbling upon this, I had an [XKCD 979](https://xkcd.com/979) moment so I'm returning to share the knowledge;

`qemu-img convert -O qcow2 OVMF_VARS.4m.fd OVMF_VARS.4m.fd.qcow2`

and then

`-drive if=pflash,format=qcow2,file=/tmp/OVMF_VARS.4m.fd.qcow2`
