### ISSUE TITLE
Enhancement for v2.0 regarding virtualisation 

### ISSUE THREAD

**Issue by skulldealer** [utmapp/UTM#371]
Hello,
I would request you to check out the the discord support channel 1 where adding gpu n hardware virtualisation support (kvm) was discussed as an outcome it was found that it was a very tedious process to program it. Would like to point out never the less it was possible to do the job.

iPad Pro even after having the hardware resources equal to intel i7 is outstanding but as per the utm limitation of virtualisation specified in your faq link- https://getutm.app/faq/ , just holds utm back from becoming at par with other PC vms. I know it is hard to program it but never the less it is a suggested feature for most awaited V-2.0 of utm from the community. After squashing the minor bugs in the current state of the app , I would recommend you to work out this as we have figured out that this feature is possible.After having support for hardware and gpu virtualisation we hands down would agree the app you have made is not less than a miracle for the emulator community. I too wish the implementation and execution of the suggestion. Seeing the complexity of the program this feature is must have but still as a low priority and would definitely take time.
Thank You.
A UTM APP LOVER😍🤩

**Comment by osy86** [comment]
Pretty sure this has been said many times before but KVM is impossible as apple chips don’t have hardware virtualization features.

**Comment by skulldealer** [comment]
At least try adding to v2.0 milestone

**Comment by skulldealer** [comment]
It is possible

**Comment by skulldealer** [comment]
Need to know complexities of gpu virtualisation tech

**Comment by skulldealer** [comment]
By programming it?
