### ISSUE TITLE
Cannot update UTM through AltStore

### ISSUE THREAD

**Issue by 8thHalfHour** [utmapp/UTM#3710]
**Describe the issue**
I have two issues to report:

1. After installing UTM SE, an update shows up in AltStore immediately. When I try to update, the update finishes (no error is displayed), but the app update stays on the screen. I have tried deactivating and re-installing everything, including AltStore itself — more than once — and this issue does not resolve. The updates remain and a badge remains on the AltStore app telling me that there are updates. (FYI: I did try installing with UTM, even though I cannot use it because not JIT support, just to see if that app did update as expected. It did not.)
2. Additionally, I am unable to access UTM beta updates through AltStore (i.e., currently, a 3.1.2 beta version is available in GitHub releases for UTM).

BOTTOM LINE: I am unsure if the issues above are related to UTM or to how AltStore is processing the installations, etc. I am hoping to get your help determining this. If it’s an AltStore issue, then I will contact him. If it’s an issue here, though, then I’d like to see how we can fix it. (I have been experiencing these issues since last Fall and have been trying to resolve them on my own this whole time, to no avail. I have some here for assistance figuring it out.) I appreciate any help/guidance you can offer. Thank you.

**Configuration (required)**
* UTM Version: UTM SE v3.0.4 bld 46
* OS Version: iPadOS v15.3.1
* Device Model: iPad Pro 2018 12.9”
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? AltStore v1.5b3

**Crash log**
No crash detected. No VMs installed currently. App opens and closes correctly. No app malfunctions detected; app installation and updates are the problem.

**Debug log**
No debug log. (See above.)

**Upload VM**
No VMs installed; VMs not affected.

**Screenshots**

*The App page with the update listed:*
![IMG_0014](https://user-images.githubusercontent.com/44852729/156261025-e71905e2-9b74-47a9-9d55-c388eb418f10.jpg)

*The UTM update details page, showing 3.0.4-2 is the update:*
![IMG_0015](https://user-images.githubusercontent.com/44852729/156261289-32ae8157-7a19-473c-9615-bf532eef7864.jpg)

**Comment by osy** [comment]
I think the problem is that we re-released 3.0.4 as 3.0.4-2 to address a build issue. This version number format is non-standard and probably failed to parse by AltStore. It’ll be “fixed” in the next release but it could also be fixed by AltStore parsing.

**Comment by 8thHalfHour** [comment]
Understood; thank for looking into it. Is there a way to get AltStore to just always link an “update” to the latest available version available rather than any incremental updates in between? For example, in this situation, the update button would appear, but it would lead to the latest beta, not 3.0.4-2. Is this what would typically happen? Or do we typically need to update to each individual version? 

FYI, I have updated the issue with screenshots reflecting what I see. AltStore clearly “sees” 3.0.4-2 and goes through the motions of trying to update, but there is no error.

I think the biggest confusion for me was that even reinstalling did not give me the latest versions. I would have expected today that 3.1.2 beta would have been installed. Maybe this is not the expectation I should have?

**Comment by osy** [comment]
None of the betas will be on AltStore or (Mac) App Store.

**Comment by 8thHalfHour** [comment]
Good to know. Thanks.
