### ISSUE TITLE
Solaris 8 and 10 (x86) doesn't recognize the keyboard  

### ISSUE THREAD

**Issue by DJZSwag** [utmapp/UTM#3720]
**Describe the issue**
So I was bored, and I decided to install Solaris 10 Intel on UTM. At first, everything seemed fine, until I got to the section where you choose if you wanted to boot into a shell, a desktop environment, and other stuff. I pressed all the numbers on my keyboard, nothing. So I let it continue on its own, then it got to the section where it asked me what keyboard layout I use. F2 and all the other Function keys weren't working. 

P.S: When Solaris got to configuring devices, it took a while, like 1 or 2 minutes. And when it boots, it says: `WARNING: Device /pci@0,0/pci1af4,1100@1f ,2/disk1,0 failed to power up.`

**Configuration**
* UTM Version: 3.1.3 (51), but it also didn't work in 3.1.2.
* OS Version: 12.3 Beta (21E5227a)
* Intel or Apple Silicon? Apple Silicon

**Crash log**
No crashes.

**Debug log**
[solaris.log](https://github.com/utmapp/UTM/files/8185145/solaris.log)

**Comment by DJZSwag** [comment]
Here is the config.plist: (couldn't upload the .plist)

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ConfigurationVersion</key>
	<integer>2</integer>
	<key>Debug</key>
	<dict>
		<key>DebugLog</key>
		<true/>
	</dict>
	<key>Display</key>
	<dict>
		<key>ConsoleBackgroundColor</key>
		<string>#000000</string>
		<key>ConsoleFont</key>
		<string>Menlo-Regular</string>
		<key>ConsoleFontSize</key>
		<integer>12</integer>
		<key>ConsoleOnly</key>
		<false/>
		<key>ConsoleTextColor</key>
		<string>#ffffff</string>
		<key>ConsoleTheme</key>
		<string>Default</string>
		<key>DisplayCard</key>
		<string>virtio-vga</string>
		<key>DisplayDownscaler</key>
		<string>linear</string>
		<key>DisplayUpscaler</key>
		<string>nearest</string>
	</dict>
	<key>Drives</key>
	<array>
		<dict>
			<key>DriveName</key>
			<string>cdrom0</string>
			<key>ImageType</key>
			<string>cd</string>
			<key>InterfaceType</key>
			<string>ide</string>
			<key>Removable</key>
			<true/>
		</dict>
		<dict>
			<key>DriveName</key>
			<string>drive0</string>
			<key>ImagePath</key>
			<string>data.qcow2</string>
			<key>ImageType</key>
			<string>disk</string>
			<key>InterfaceType</key>
			<string>ide</string>
		</dict>
	</array>
	<key>Info</key>
	<dict>
		<key>Icon</key>
		<string>HP-Greets-IBM-2.png</string>
		<key>IconCustom</key>
		<true/>
	</dict>
	<key>Input</key>
	<dict>
		<key>InputLegacy</key>
		<false/>
	</dict>
	<key>Networking</key>
	<dict>
		<key>NetworkCard</key>
		<string>e1000</string>
		<key>NetworkCardMAC</key>
		<string>76:54:F0:91:69:30</string>
		<key>NetworkMode</key>
		<string>emulated</string>
	</dict>
	<key>Printing</key>
	<dict/>
	<key>Sharing</key>
	<dict>
		<key>ClipboardSharing</key>
		<true/>
		<key>DirectoryReadOnly</key>
		<false/>
		<key>DirectorySharing</key>
		<true/>
		<key>UsbRedirectMax</key>
		<integer>3</integer>
	</dict>
	<key>Sound</key>
	<dict>
		<key>SoundCard</key>
		<string>AC97</string>
		<key>SoundEnabled</key>
		<true/>
	</dict>
	<key>System</key>
	<dict>
		<key>Architecture</key>
		<string>i386</string>
		<key>BootDevice</key>
		<string></string>
		<key>BootUefi</key>
		<false/>
		<key>CPU</key>
		<string>default</string>
		<key>CPUCount</key>
		<integer>1</integer>
		<key>Memory</key>
		<integer>1024</integer>
		<key>RTCUseLocalTime</key>
		<true/>
		<key>RngEnabled</key>
		<true/>
		<key>SystemUUID</key>
		<string>7A22F8C3-807E-42EF-BEA6-B3B784B8A63E</string>
		<key>Target</key>
		<string>q35</string>
		<key>UseHypervisor</key>
		<false/>
	</dict>
</dict>
</plist>
`

**Comment by DJZSwag** [comment]
PS2: Turned off USB, nothing. Put it to 3.0, nothing.

**Comment by DJZSwag** [comment]
PS3: Here is my config: https://drive.google.com/file/d/1HwxnmxIxqPXa31pyi1TMjrWbF_kx5_1C/view?usp=sharing

**Comment by DJZSwag** [comment]
Still doesn't work in 3.1.4

**Comment by conath** [comment]
Have you tried using the `pc` system instead of `q35`?

**Comment by DJZSwag** [comment]
Solaris 10 now works! But 8 shows a whole new error. Should be its own issue. But thanks!
