### ISSUE TITLE
Windows XP guest with pc machine type stops booting if PS/2 bus is disabled

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#3723]
Since a recent [change](https://github.com/utmapp/UTM/commit/657a1ba968d4ac4db5bebd5c17b516f48053d868) UTM now disables the PS/2 controller in the VM if USB is enabled. This breaks Windows XP VMs in `pc` machines, both existing and new installs will fail to boot. For existing VMs there is a black screen after the BIOS boots the hard drive, for new installs it hangs at "Analyzing your hardware configuration".

My other VMs installed on `pc` like ReactOS and Windows 8.1 are unaffected, and my Windows XP on `q35` machine also still works despite the USB 2.0-only option selected.

**Suggested fix**
Instead of defaulting to "USB 2.0" only when `pc` VMs are "upgraded" or created in UTM 3.1, default to a new "PS/2 input and USB 2.0 bus" option that mirrors the behavior from previous versions of UTM. This way we have working XP and can use USB sharing.

**Configuration**
* UTM Version: 3.1.3
* OS Version: macOS 12.1
* Apple Silicon

**Debug log**
[debug-xpflp.log](https://github.com/utmapp/UTM/files/8190519/debug-xpflp.log)

The debug log contains the parameter `-machine pc,vmport=off,i8042=off` which causes the problem. If I turn off USB in the Input settings, the log changes to `-machine pc,vmport=off` and the machine boots again. However, this means I can't use USB sharing.

**Upload VM**
[config.plist.zip](https://github.com/utmapp/UTM/files/8190522/config.plist.zip)

**Comment by osy** [comment]
I've decided to make "ForcePS2Controller" a new tweak because

1. This issue is isolated to only pc+XP and other "specific configuration issues" are left to toggle-able tweaks
2. Adding something like "PS/2 input and USB 2.0 bus" will confuse a lot of people who may not understand what "PS/2" is and also does not apply for targets that do not have PS/2
3. Exposing most people who are not using Windows XP to the internal details of PS/2 vs USB input emulation goes against the idea of "easy for 99% of people to do 99% of things"

**Comment by carlo-righini** [comment]
Hi @osy @conath , Enabling USB via the Input settings, still causes XP to not boot. If I disable USB then XP will boot but I cannot access USB devices - I'm just trying to install a program in XP but I cannot find a way to access the installer (USB CD drive and USB stick containing the installer files obviously do not work). Is there any workaround for this? Thanks. 
UTM version: 4.2.5 (81)
Mac M1, MacOS Ventura 13.4

**Comment by conath** [comment]
@carlo-righini A workaround would be to create an ISO image of the CD/DVD you're trying to load into Windows. You can do this [using Disk Utility](https://support.apple.com/guide/disk-utility/create-a-disk-image-dskutl11888/mac) on your Mac. Make sure to choose the option "DVD/CD master" when creating the image file. If needed, rename the resulting file to .iso and then insert the image into the VM's CD drive.

**Comment by eyaeya** [comment]
> Hi, enabling USB through the settings still causes XP to not boot. If I disable USB, then XP will boot but I can't access USB devices - I just want to install a program in XP but I can't find a way to access the installer (apparently, neither the USB optical drive nor the USB flash drive containing the installer files are working). Is there a solution to this problem? Thank you. UTM version: 4.2.5 (81) Mac M1, MacOS Ventura 13.4.

@osy I have the same problem, I don't know how to use the USB interface

**Comment by tsboom** [comment]
Hello, I cannot get Windows XP with USB 2.0 or USB 3.0 sharing enabled either. I'm trying to use a USB device that's not a usb flash drive.

**Comment by Coloured568** [comment]
i still cant either
