### ISSUE TITLE
Virtualisation.Framework seems broken on 12.2.1 (arm64)

### ISSUE THREAD

**Issue by dmarkey** [utmapp/UTM#3749]
Hey,

While trying to boot a linux VM using Virtualisation.Framework, it seems broken(see error attached). I have also tried vmcli to start a VM and getting a similar error.

So not a bug against UTM, but a PSA, and perhaps a call for workarounds?

This is a MBA, freshly formatted, so kinda stumped!

<img width="645" alt="image" src="https://user-images.githubusercontent.com/1159924/157881859-dde038a6-2d81-4ac7-aaae-26253d145505.png">

**Comment by dmarkey** [comment]
Sorry, seems I had a busted kernel image!

**Comment by shenghan97** [comment]
> Sorry, seems I had a busted kernel image!

Hey! Can you tell me which kernel image did you use eventually? I used the [fedora](https://mirrors.ocf.berkeley.edu/fedora/fedora/linux/releases/35/Everything/aarch64/os/images/pxeboot/) one here but I saw the same error as you did. Thanks!

**Comment by dmarkey** [comment]
Were you able to get a serial console with that kernel image?

**Comment by shenghan97** [comment]
> Were you able to get a serial console with that kernel image?

Yes I was! But it was very buggy - there were lots of kernel errors when I do updates.
