### ISSUE TITLE
EFI option for UTM

### ISSUE THREAD

**Issue by IIWare** [utmapp/UTM#375]
Can you add the UEFI option in UTM app?
The UEFI for windows 10 for example might be something like this:
![Image of UTM EFI](https://i.ibb.co/x6fLsck/utmefi.png)
btw this image was just photo edited, and I didn't edit the source code of UTM
It would be so good if UTM had EFI option!

**Comment by osy86** [comment]
I'm not sure QEMU supports that. If you can boot into a custom EFI then you can do something like that. If QEMU provides an options, we can probably expose it. Otherwise it will be far too much trouble to implement.

**Comment by IIWare** [comment]
> I'm not sure QEMU supports that. If you can boot into a custom EFI then you can do something like that. If QEMU provides an options, we can probably expose it. Otherwise it will be far too much trouble to implement.

actually QEMU supports UEFI, I searched in google and QEMU supports EFI
I am not meant to be too lazy to make EFI in QEMU, I am just asking you that can you
add EFI in QEUM.

**Comment by osy86** [comment]
Of course QEMU supports UEFI, that's how we boot ARM stuff. I'm saying I don't know if it supports custom UEFI logos. I.e. is there an option to load the logo into UEFI flash memory.

**Comment by IIWare** [comment]
> Of course QEMU supports UEFI, that's how we boot ARM stuff. I'm saying I don't know if it supports custom UEFI logos. I.e. is there an option to load the logo into UEFI flash memory.

ok but you don't have to add the custom UEFI logos, only EFI, but once windows 10 is installed I will use a Program called HackBGRT to change UEFI logo. so you don't have to worry about adding UEFI custom logos, so can you alteast add EFI in UTM?

**Comment by osy86** [comment]
Can you tell me the QEMU command you used on Linux to get it working? I tried https://gist.github.com/voltagex/7af5955c029539ae904f851ac434b00c and that doesn't let you change the logo (unless you manually patch the BIOS image).

**Comment by IIWare** [comment]
> Can you tell me the QEMU command you used on Linux to get it working? I tried https://gist.github.com/voltagex/7af5955c029539ae904f851ac434b00c and that doesn't let you change the logo (unless you manually patch the BIOS image).

Tell you the command I used on Linux to get what working?

**Comment by osy86** [comment]
> Basically, if you can show me how to do this on QEMU on linux, I can probably get it working on UTM.

**Comment by IIWare** [comment]
> > Basically, if you can show me how to do this on QEMU on linux, I can probably get it working on UTM.

I think this might help: https://fedoraproject.org/wiki/Using_UEFI_with_QEMU#:~:text=On%20the%20%27Overview%27%20screen%2C,re%20running%20an%20UEFI%20OS.

**Comment by osy86** [comment]
Are you reading my replies at all?

> I tried https://gist.github.com/voltagex/7af5955c029539ae904f851ac434b00c and that doesn't let you change the logo (unless you manually patch the BIOS image).

It's the same instructions as there. The UEFI partition is read-only and you can't change the boot logo or anything. Try it yourself and once it works, tell me exactly what you did.

**Comment by IIWare** [comment]
> Are you reading my replies at all?
> 
> > I tried https://gist.github.com/voltagex/7af5955c029539ae904f851ac434b00c and that doesn't let you change the logo (unless you manually patch the BIOS image).
> 
> It's the same instructions as there. The UEFI partition is read-only and you can't change the boot logo or anything. Try it yourself and once it works, tell me exactly what you did.

Ok I will, so please wait and I will tell you what I excatly did.

**Comment by IIWare** [comment]
> Are you reading my replies at all?
> 
> > I tried https://gist.github.com/voltagex/7af5955c029539ae904f851ac434b00c and that doesn't let you change the logo (unless you manually patch the BIOS image).
> 
> It's the same instructions as there. The UEFI partition is read-only and you can't change the boot logo or anything. Try it yourself and once it works, tell me exactly what you did.

ok so i install QEMU software in linux or I install linux Operating system in QEUM?

**Comment by IIWare** [comment]
> Are you reading my replies at all?
> 
> > I tried https://gist.github.com/voltagex/7af5955c029539ae904f851ac434b00c and that doesn't let you change the logo (unless you manually patch the BIOS image).
> 
> It's the same instructions as there. The UEFI partition is read-only and you can't change the boot logo or anything. Try it yourself and once it works, tell me exactly what you did.

i've searched in the internet for like a week and since it is too complex for me, I've found 2 things, 1 is HackBGRT, it is a Windows executable program that you use to change EFI logo to any logo, and 2nd, using OVMF, you can change the boot logo of QEMU: https://www.garyhawkins.me.uk/custom-logo-on-uefi-boot-screen/
I hope this helps, Thanks!

**Comment by jankais3r** [comment]
What you linked confirms what osy was saying - you have to recompile or patch the UEFI image in order to change the logo. Way beyond the scope of this project.

**Comment by conath** [comment]
I have succeeded in building the OVMF EFI images *from within a UTM virtual machine*. 😃 I followed [these instructions](https://gist.github.com/niw/e4313b9c14e968764a52375da41b4278#build-edk-ii-ovmf-efi-image-from-the-source-code) in a Ubuntu Server 20.04 VM.

**Comment by Vishram1123** [comment]
You can build the EFI from within MacOS itself; just clone edk2, then follow [these](https://github.com/BlankOn/ovmf-blobs) instructions.
