### ISSUE TITLE
NSIS Error : Installer integrity check has failed.

### ISSUE THREAD

**Issue by obbcth** [utmapp/UTM#376]
While trying to install programs such as Spice guest tools, Firefox 52.9, NSIS Error occurs everytime.
Tested on Windows 2000, XP, and 7.
iPad Air 3 13.4.1 , with 768MB memory allocated.
Tried with -NCRC option, but nothing changed.

**Comment by osy86** [comment]
Can you post your device information and the config.plist for the vm?

**Comment by obbcth** [comment]
[config.zip](https://github.com/utmapp/UTM/files/4774151/config.zip)
On iPad Air 3 (A12 chip and 3GB memory) 13.4.1 Jailbroken, UTM installed with Filza.

**Comment by osy86** [comment]
Can you try with less memory allocated?

**Comment by obbcth** [comment]
![A12B3F47-D7BE-4698-BC26-CB065CE2E4EB](https://user-images.githubusercontent.com/12216587/84745603-c972a600-afef-11ea-9abc-6839fa911bd4.jpeg)
![1D589793-A273-4F8D-92E6-FC8E9DAC9CDE](https://user-images.githubusercontent.com/12216587/84745616-cc6d9680-afef-11ea-9fde-1b9cc17dca4d.jpeg)
Tried with 256MB (JIT is default), result is same.
Plus, this issue occurs in every installer in my case. (regardless of nullsoft)

**Comment by osy86** [comment]
I was not able to reproduce the issue.

I created a new VM and used your config.plist and c.img. I also added a CD containing spice tools (attached). I was able to run the installer both on iOS simulator and iPad 2018 without issue.

However, I noticed your disk image is not QCOW2 format. There's been many issues with drives that aren't QCOW2 which is why I removed the option to create a RAW formatted disk a while ago. Try converting your RAW disk to QCOW2 using `qemu-img convert` and see if that helps.

[spice.iso.zip](https://github.com/utmapp/UTM/files/4802276/spice.iso.zip)

**Comment by obbcth** [comment]
Okay, I tried with your iso and working.
I downloaded programs on the internet using IE6, so there will be a problem on IE6 (and somewhat server problems) or RAW Image format.
So, I will convert it (RAW to qcow2) and try again with downloaded programs.

**Comment by obbcth** [comment]
I converted and tried again, and the same error occurs.

So, It was the problem with IE6 and server (somewhat corrupted).

**Comment by osy86** [comment]
Hmm I wonder if it's a problem with UTM's QEMU slirp networking library that's causing the corruption. I've definitely experienced this once in a while but not often. Open another ticket if you continue to see the issue in firefox.

**Comment by obbcth** [comment]
![CF309579-24C3-49FD-B4AF-4E4007D7E8F0](https://user-images.githubusercontent.com/12216587/85187117-3a5bdb80-b2d8-11ea-9608-4d3bc77c36a9.jpeg)

Firefox 52.9 ESR shows this error.

**Comment by osy86** [comment]
Can you collect a debug log?

**Comment by obbcth** [comment]
I’m on 14 now, so I could do that if several bugs are fixed.
#397 and rileytestut/AltStore#272

**Comment by osy86** [comment]
Unfortunately #397 is unlikely to ever be fixed. You will probably have to jailbreak iOS 14 and run a future version.

**Comment by obbcth** [comment]
> Unfortunately #397 is unlikely to ever be fixed. You will probably have to jailbreak iOS 14 and run a future version.

Sorry to hear that :(

**Comment by UInt2048** [comment]
@obbcth With the current state of the issues, you might be able to now?

**Comment by obbcth** [comment]
> @obbcth With the current state of the issues, you might be able to now?

Yes, I'll test it again when I have enough time

**Comment by osy** [comment]
This is actually an issue with disk cache corruption. Latest builds fix this by disabling QEMU’s write cache.
