### ISSUE TITLE
Can’t launch UTM on jailbroken IPad Pro running IOS 12.3.1 on unc0ver jailbreak (QEMU)

### ISSUE THREAD

**Issue by accdtc** [utmapp/UTM#3765]
Everything was working perfectly during the setup process for running Android until, seemingly randomly, it didn’t. I hadn’t finished the setup process for partitioning the Android OS when it no longer launched the VM and gave me this error: “QEMU exited from an error: Identifiers consist of letters, digits, ‘-’,’.’,’_’, starting with a letter.”

I’ve tried looking it up but I couldn’t find anything. I’ve restored RootFS and Re-Jailbroken. Restarted the process multiple times and tried re-installing UTM multiple times as well. I’m at a complete loss on what to do and would really appreciate some help.

This was the debug.txt 
[debug.log](https://github.com/utmapp/UTM/files/8240203/debug.log)

**Comment by accdtc** [comment]
Also, I got UTM from Cydia and am running version 2.1.1.

**Comment by osy** [comment]
Use 3.1.5 from the official repo.
