### ISSUE TITLE
Virtualize grayed out

### ISSUE THREAD

**Issue by JohnB17** [utmapp/UTM#3769]
**Describe the issue**
Virtualize option is grayed out

**Configuration (required)**
* UTM Version: 3.1.5
* OS Version: 14.8
* Device Model: iPhone SE (2nd Generation)
* Is it jailbroken (name jailbreak used)? Unc0ver
* How did you install UTM? Sideloadly

**Crash log**
None

**Debug log**
I was trying to create the vm, so there is no debug log.

**Upload VM**
I was trying to create the vm, so there is no vm yet.

**Comment by osy** [comment]
This is not a bug.

**Comment by JohnB17** [comment]
How can I fix it though?

**Comment by JohnB17** [comment]
Oh maybe I should read that it isn't support. Nevermind.
