### ISSUE TITLE
create an cydia/sileo repo

### ISSUE THREAD

**Issue by boy13epic** [utmapp/UTM#377]

**Comment by ThatsNiceGuy** [comment]
cant you just download the IPA, unzip it and stick the `.app` into `/Applications` and then do a `uicache`?

**Comment by jankais3r** [comment]
I think they want the benefit of automatic updates, but that can be achieved by already existing AltStore source with AltDaemon.

**Comment by osy86** [comment]
I think there's a Cydia mirror of the altstore repo. I can't recall it right now but some googling might help.
