### ISSUE TITLE
UTM Crashes When I Try To Edit Virtual Machine Configuration

### ISSUE THREAD

**Issue by PabloElOtaku333** [utmapp/UTM#3785]
I have a problem, When I try to edit a virtual machine configuration utm closes and says: "UTM Has Closed Unexpectedly"

I am on M1 Mac
Mac OS Monterey 12.0 Beta 1
(shoot I didn't know that there were more versions of Monterey)
UTM Version: 3.1.5

https://user-images.githubusercontent.com/101748664/158678428-88d320a1-fe4a-4c56-adf6-910fbb04967e.mov

(Sorry For The video being in Spanish its because I live in Spain)

Edit:The virtual machines that you can see were made before this started to happen

**Comment by PabloElOtaku333** [comment]
also happens when I am creating a vm


https://user-images.githubusercontent.com/101748664/158679532-46672da6-1f0a-4acd-b92f-a9f132809153.mov

**Comment by osy** [comment]
You left out the most important information:

1. What is the exact version of macOS? You say "Beta 1" But is it 12.0 beta 1? 12.1 beta 1? 12.3 beta 1? etc
2. What is the exact version of UTM? 3.1.?? 3.1.5 is the latest one.

If possible, can you copy the crash log? Click the "more details" button and copy paste the data here.

**Comment by PabloElOtaku333** [comment]
1.I am In Mac OS Monterey Beta 1
<img width="698" alt="Captura de pantalla 2022-03-17 a las 8 53 56 a  m" src="https://user-images.githubusercontent.com/101748664/158762377-e974805d-dca3-49e8-8ac3-522c524417a4.png">

2.I am with the latest version of UTM

Here are  the logs:
[Crash Log When Edit Virtual Machine.txt](https://github.com/utmapp/UTM/files/8282499/Crash.Log.When.Edit.Virtual.Machine.txt)

[Crash Log When Creating a VM.txt](https://github.com/utmapp/UTM/files/8282519/Crash.Log.When.Creating.a.VM.txt)

**Comment by PabloElOtaku333** [comment]
Im Gonna Update And See If That Fixes it

**Comment by PabloElOtaku333** [comment]
I updated to Monterey 12.3 and it fixed
