### ISSUE TITLE
Ubuntu 21 on Mac M1 goes back to installation screen after restart

### ISSUE THREAD

**Issue by CameronHamidi** [utmapp/UTM#3787]
I'm trying to create a Ubuntu 21.10 vm on my Mac (m1 chip). I followed the guide [here](https://mac.getutm.app/gallery/ubuntu-20-04) and went through the installation screen, but after the vm reboots, it just goes back to the start of the installation flow.

I tried quitting the vm and unmounting the iso under the vm settings, but after restarting it just got stuck on a `failed to load` error page.

**Configuration**
* UTM Version: 3.0.4
* OS Version: macOS Monterrey 12.1
* Intel or Apple Silicon? Apple Silicon

**Comment by CameronHamidi** [comment]
Doing either of those gives me a `EFI STUB: ERROR: FIRMWARE BUG: kernel image not aligned on 64k boundary` error

**Comment by osy** [comment]
This is fixed I. 3.1.5

**Comment by josalvatorre** [comment]
This happened to me today in version `4.5.3`. Moving the usb down like [boywijnmaalen suggested][1] worked. What an annoying problem 😅

[1]: https://github.com/utmapp/UTM/issues/3787#issuecomment-1071235969
