### ISSUE TITLE
Kali Linux and Ubuntu not booting !

### ISSUE THREAD

**Issue by RwdBass** [utmapp/UTM#3789]
I have been using both OSes on UTM and they were working perfectly fine.
Last week Ubuntu stopped booting and today Kali also freezes on booting.

UTM Version: Version 3.0.4 (46)

Hardware: MacBook Air M1 2020
Software: macOS Monterey - Version 12.3

Kali Linux Version: 2022.1
Ubuntu Version: 20.04.3 LTS
(both for ARM 64 obviously)

The Following screenshots are the pages I get:

Ubuntu:
<img width="1440" alt="Screen Shot 2022-03-18 at 3 18 28 PM" src="https://user-images.githubusercontent.com/72977353/159020998-7275d072-f1b2-4780-b432-6cd09a3453e0.png">

Kali Linux:
<img width="1440" alt="Screen Shot 2022-03-18 at 3 19 09 PM" src="https://user-images.githubusercontent.com/72977353/159021005-41dbf467-2c99-4135-8ea4-81112646bbb9.png">

**Comment by freebrowser1** [comment]
Try again on UTM 3.1.5 I have experienced. But it still takes long time to boot Ubuntu and shared folder is not mounted.

**Comment by gradygambrell** [comment]
i also had this issue. plus when i redownload it, it will be stuck on the updating part unless i force restart
