### ISSUE TITLE
No Network Connection in VM on M1 mac

### ISSUE THREAD

**Issue by epiplun** [utmapp/UTM#3802]
I had installed UTM and installed Kali Linux successfully on the vm. For a week the network and vm worked well with no issues, then one day I restarted my mac and now I can't get a network connection on any vms. I know network issues have been posted about already, but I believe the circumstance is different from all the other cases.

**Configuration**
* UTM Version: 3.1.5
* OS Version: Macos 12.2.1
* M1 Max

Any suggestions would be greatly appreciated, thanks!

**Comment by epiplun** [comment]
Sorry about that, I have attached the debug log below. Also, I have not tried the Bridged mode as I do not know what configuration details I should use for it, but I have change the network device with no change on the outcome in the VM. What should I put for the Bridged interface in order to try out that mode?

[debug.log](https://github.com/utmapp/UTM/files/8337171/debug.log)

Thanks

**Comment by conath** [comment]
@epiplun Thank you, the configuration looks good, and the shared network mode is what I would suggest for Linux guest. If you want to try Bridged Mode, just choose it and Save (leave the defaults) unless you have multiple network devices on your Mac.

Do you use any network related macOS features like Internet Sharing or VPN?

**Comment by epiplun** [comment]
Great news, the bridged mode worked! Just out of curiosity, do you know why the Shared stopped working?
Thanks for your help @conath

**Comment by alshdavid** [comment]
I am having this issue with MacOS 13.0.1

Internet on my guests worked for weeks then suddenly today shared connections are no longer working. I do have a corporate VPN but it wasn't an issue previously, not sure why it became one suddenly

**Comment by DarksideVT** [comment]
@alshdavid did you ever get this to work with shared network? I have to connect my VM to my VPN on the host.

**Comment by xXxSpicyBoiiixXx** [comment]
I had this issue but it was resolved when I changed the settings from "shared network" to "emulated VLAN"

**Comment by dwoller-uptycs** [comment]
Maybe the default setting should be temporarily/indefinitely changed to emulated VLAN? I got stuck here for a bit, but switching to emulated VLAN fixed my problems.

**Comment by yllekz** [comment]
Hey folks, this is still a critical issue. Every UTM VM I make is unable to connect to the network properly. I would recommend reopening and prioritizing this bug.

**Comment by KhaledHormos** [comment]
I was able to solve the network issue.
however, the clipboad is not working.

**Comment by MichaelVoelkel** [comment]
Hm, nothing works for me either. Also being on M1 2019. I tried bridged, shared, VN, ... nope

**Comment by KhaledHormos** [comment]
Ok 
I installed Kali,  on macbook pro m1 using UTM


the issue started when i was not able to get an ip address 

first I edited the vm to change the network to bridged mode 

<img width="610" alt="Screenshot 2023-07-18 at 6 46 14 PM" src="https://github.com/utmapp/UTM/assets/101827274/d10a3c3e-1767-4d49-95fd-fadd2798b5f9">

then added

auto etho
iface eth0 inet dep

at the end 


<img width="630" alt="Screenshot 2023-07-18 at 6 51 20 PM" src="https://github.com/utmapp/UTM/assets/101827274/43aff926-7ee6-4ff7-af5d-23767861f9bd">


restart the OS

**Comment by MichaelVoelkel** [comment]
Ok, I had a centos minimal and network interface not enabled... your post gave me the right hint, thank you for that!

**Comment by KhaledHormos** [comment]
@MichaelVoelkel 
I hope that would help.



I tried ubuntu, it works just fine and I think the clipboard too, but Kali is another story.

I did not change the interface on ubuntu 
But I changed the VM network to bridged mode tho

**Comment by MichaelVoelkel** [comment]
Well now it does NOT work anymore, no clue why... it cannot retrieve IPv4 address

**Comment by KhaledHormos** [comment]
but how did you edit it the first time ?

**Comment by MichaelVoelkel** [comment]
I followed this guide: https://lintut.com/how-to-setup-network-after-rhelcentos-7-minimal-installation/

**Comment by KhaledHormos** [comment]
could you send me the link to apple silicone  version of  rhelcentos-7-minimal  I will try to install it on my device and let you know if i managed to run the network

**Comment by MichaelVoelkel** [comment]
I used this one: https://ftp.plusline.net/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-Minimal-2009.iso

**Comment by MichaelVoelkel** [comment]
By the way, I get an IPv6 address but this is useless with my network (my ISP does not support IPv6), so I need IPv4 which usually works but... not now

**Comment by ukyoi** [comment]
Hey guys, if you still can't connect to Internet, try to change a network card. I upgraded to Fedora 28 (aarch64 version) and lost my network connection. I tried different settings but all failed until I changed the device to Intel Gigabyte Ethernet (e1000). Now everything works fine.

**Comment by johncronan** [comment]
> it cannot retrieve IPv4 address

I had the same experience as others here - it started working after I messed with the network settings. And I'm back on the defaults.

The wifi that I'm connecting to is a mixed IPv4/IPv6 network. I suspect these remaining issues noted here may have to do with IPv6.

**Comment by silbo** [comment]
This helped me https://www.youtube.com/watch?v=KGZMV8IuUtA

**Comment by andrewc513** [comment]
Found this thread after starting to use UTM on my new M2 MacBook Air. Same as others, shared networking and its defaults everywhere resulted in no network connectivity in the VM.

This appears to be an issue with DNS between the guest and host.  Once I manually set the guest's DNS settings to Quad 9 (9.9.9.9), networking functioned as expected.

DNS passing through the shared network with out of box defaults did not function correctly on both my own home network (which pushes 8.8.8.8 and 9.9.9.9 for DNS via DHCP) and my work network (which pushes our own Cisco Umbrella VAs for DNS via DHCP).

So my advice to others before chasing this too far... Just see if manually specifying your DNS server(s) in the guest OS settings resolves problems.

**Comment by outermosthouse** [comment]
Got it to work after I changed `Interface` in bridged mode from `Automatic` to `en0`. No other config changes were needed. Hope this helps someone.

**Comment by 1R053** [comment]
> Got it to work after I changed `Interface` in bridged mode from `Automatic` to `en0`. No other config changes were needed. Hope this helps someone.

this also fixed the issue for me on Ubuntu

**Comment by rzzldzzl** [comment]
> I am having this issue with MacOS 13.0.1
> 
> Internet on my guests worked for weeks then suddenly today shared connections are no longer working.
> 
> I do have a corporate VPN but it wasn't an issue previously, not sure why it would became one suddenly

Your VPN might disable IP Forwarding. That is the case with the AWS Client VPN.

My experience is -
Guest can access networks as expected (IP Forwarding is enabled)
After the hosts connects to the AWS Client VPN, the guest looses access to anything but the host. (IP Forwarding is disabled)
Manually enabling IP Forwarding restores connectivity from the guest.

After connecting your VPN (on the host), try enabling IP Forwarding on the host:
% sudo sysctl -w net.inet.ip.forwarding=1 net.inet.ip.forwarding: 0 -> 1

**Comment by va2bdc** [comment]
I’ve installed Ubuntu 23.04 with UTM on a MacBook Pro m1. I’ve set to bridged and en0 and virtio-net-pci the network interface in UTM. I have access to the internet only for gmone online accounts and sharing, and probably other things. I can’t figure out the problem. That’s why I’m posting this issue. i've look around, I can't seem to figure out what is wrong.
![Capture d’écran du 2023-09-29 18-15-09](https://github.com/utmapp/UTM/assets/146648813/05e6639b-12cf-4d97-9835-24ad78912dae)
![Capture d’écran du 2023-10-01 16-34-36](https://github.com/utmapp/UTM/assets/146648813/9bcc1e99-835e-47be-adca-f5031706b2bb)

**Comment by WyattLiu** [comment]
likely a DNS issue, try ping 1.1.1.1, should be able to ping it.

**Comment by va2bdc** [comment]
yes, ping 1.1.1.1 works, but online accounts still doesn't work.
he's my netplan configuration:

/etc/netplan/01-netcfg.yaml

network:
  version: 2
  renderer: networkd
  ethernets:
#    enp0s1: # Le nom de votre interface peut varier, assurez-vous d'utiliser le bon nom
     en0: 
      dhcp4: yes
      dhcp6: no
      addresses: [192.168.1.70/24] # Remplacez par l'adresse IP souhaitée
      gateway4: 192.168.1.1
      nameservers:
        addresses: [212.27.40.240,212.27.40.241] # Serveurs DNS Google, remplacez si nécessaire


/etc/netplan/00-installer-config.yaml

# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s1:
      dhcp4: true
  version: 2

the issue is probably within these two files. But can't figure out.

**Comment by farazmsiddiqi** [comment]
> Got it to work after I changed `Interface` in bridged mode from `Automatic` to `en0`. No other config changes were needed. Hope this helps someone.

This fixed it for me as well -- The network had mysteriously populated an `en9` setting, and I am assuming that the `Automatic` setting on bridged mode was defaulting to en9.

**Comment by va2bdc** [comment]
The problem with online account is an issue with Ubuntu 23.04 arm. It has been correct with 23.10.

**Comment by mohgopathi** [comment]
> Got it to work after I changed `Interface` in bridged mode from `Automatic` to `en0`. No other config changes were needed. Hope this helps someone.

this worked for me,thanks !

**Comment by kaungmyathan22** [comment]
Internet access inside window is still not working. I'm running this on macos m3.
<img width="860" alt="Screenshot 2024-04-06 at 11 26 46 AM" src="https://github.com/utmapp/UTM/assets/45494917/77ac7bab-9c09-4fcf-a033-7d12fb00639c">
 
<img width="654" alt="image" src="https://github.com/utmapp/UTM/assets/45494917/82ab6149-dc85-463d-bd63-bc646284cce7">
pls help me. how can i fix this?

**Comment by SB-Dex** [comment]
I need the "shared" network on guest VM Win 11 but it doesn't have an internet connection. Please help!!!

@kaungmyathan22 Update the `Bridged Interface` to en0 may help you. It works on my m3 laptop.

**Comment by agungjk** [comment]
> Internet access inside window is still not working. I'm running this on macos m3. <img alt="Screenshot 2024-04-06 at 11 26 46 AM" width="860" src="https://private-user-images.githubusercontent.com/45494917/320178274-77ac7bab-9c09-4fcf-a033-7d12fb00639c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNTYyODIsIm5iZiI6MTcxNjI1NTk4MiwicGF0aCI6Ii80NTQ5NDkxNy8zMjAxNzgyNzQtNzdhYzdiYWItOWMwOS00ZmNmLWEwMzMtN2QxMmZiMDA2MzljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDAxNDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZjM0M2E3MTNlMWY1MDQwYmQ0MDRiNDFjMzA4YjU2YTRiNjZmZDI4NTUyNmJmNGIzZjRmMDY4MmU4Y2U2YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zHnElhoscYHLxMojdDV2c4-CQCj0tfm4JZAFiqkRJoI">
> 
> <img alt="image" width="654" src="https://private-user-images.githubusercontent.com/45494917/320178672-82ab6149-dc85-463d-bd63-bc646284cce7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNTYyODIsIm5iZiI6MTcxNjI1NTk4MiwicGF0aCI6Ii80NTQ5NDkxNy8zMjAxNzg2NzItODJhYjYxNDktZGM4NS00NjNkLWJkNjMtYmM2NDYyODRjY2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDAxNDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMTMyYWYyMDk3YmViMjdmMDRkMmY3YTdhM2YyYzg1N2ZlOTJlNDlkYjgwZmQ4ZjczNDdmMDA1OGQ1YTVmOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.awO43BS89SXMqdSh4HmwJ08fTln5-DgdHySPywwJLMo"> pls help me. how can i fix this?

you can use "emulated VLAN" on network mode

**Comment by arycloud** [comment]
Here's how i resolved it, may be helpful for someone:

1. Change to bride
2. In terminal, run `nmcli` to grab the name of NW: ( `enp0s1` in m,y case)
3. Then update the `enp0s1's ifcfg` as below:
```
[root@localhost ~]# vi /etc/sysconfig/network-scripts/ifcfg-enp0s1
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=dhcp
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME=enp0s1
UUID=<UUID>
DEVICE=enp0s1
ONBOOT=yes
```

4. Restart the network service as: `sudo systemctl restart network.service `
5.  Finally check back `nmcli` it shows the connected status for `enp0s1` and it works

**Comment by shub-0101** [comment]
Hello Folks,

Well, I have installed Kali and Metasploitable on UTM and when I started the machine, they did not have the IPv4 address, checked with Bridge, Emulated VLAN, and Shared options nothing worked. 

Eventually, I tried with the host option and post doing so,  I did get the IPv4 address and was now able to ping the machines from each other 

Kali to Metasploitable===== Success

UTM- 4.5.4
MacOS 15.0
M3 Pro

**Comment by mercy-holdiness** [comment]
I've had the UTM running well since May, now all of a sudden the network issue is coming up. I've tried different suggestions Emulated VLAN, Shared Network, Host only, Bridge Advanced. I tested with different configurations as suggested, but most just prevented the machine from even booting. What else can be done? Seem such a shame that we cannot have a stable connection, when the machine works otherwise splendidly. I have an M3.

**Comment by dwxw** [comment]
> Got it to work after I changed Interface in bridged mode from Automatic to en0. No other config changes were needed. Hope this helps someone.

I needed to do this to get internet working.  Thanks.

**Comment by albe-jj** [comment]
Emulated VLAN worked for me. I had this issue after a while i was using utm. switching to Emulated VLAN fixed network issue.

**Comment by louij2** [comment]
I had this issue on and off twice now and switching to Emulated VLAN fixed it too.

**Comment by sarezas** [comment]
I have MacOS Sequoia 15.1, installed Metasploitable 2, Host-only network setup. For one day it worked perfectly, just the way as expected. But the next day host machine can't reach guest machine and vice versa. Pinging guest from host gives "request timeout" error, and pinging host from guest gives "unreachable network" error. The annoying thing is that I did not change any network settings.

Does anyone have any idea as to what might have happened?

**Comment by liaohaiyang1534** [comment]
"Bridged" works for me. I use macbook air m3, Sequoia 15.1.1, UTM, Arch64. And I am using VPN to get to goole.com, not only using domestic internet.

**Comment by Drjacky** [comment]
> I had this issue but it was resolved when I changed the settings from "shared network" to "emulated VLAN"

Bridged, emulated VLAN, shared network, with/without VPN didn't help on M2!

**Comment by bcorcoran** [comment]
> Found this thread after starting to use UTM on my new M2 MacBook Air. Same as others, shared networking and its defaults resulted in no network connectivity in guest VMs.
> 
> This appears to be an issue with DNS between the guest and host. Once I manually set the guest's DNS settings to Quad 9 (9.9.9.9), networking functioned as expected. The previous non-working default was the same IP as the default gateway of the shared network. (192.168.64.1)
> 
> DNS not passing through the shared network with out of box defaults was the same when the host machine was on either my own home network (which pushes 8.8.8.8 and 9.9.9.9 for DNS via DHCP) and my work network (which pushes our own Cisco Umbrella VAs for DNS via DHCP).
> 
> So my advice to others before chasing this too far... Just see if manually specifying your DNS server(s) in the guest OS settings resolves problems.

This is the correct answer! All I had to do was manually specify any DNS server.

**Comment by song6174** [comment]
End up using 'virtio-net-pci-non-transitional' for Emulated Network Card. That solves the problem for me. 

See this post for more details
https://www.reddit.com/r/UTMapp/comments/1flphnr/quick_overview_of_every_network_adapter_in/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by amadeuspzs** [comment]
> End up using 'virtio-net-pci-non-transitional' for Emulated Network Card. That solves the problem for me.

Ditto - I had networking working then suddenly stopped. Switching to `virtio-net-pci-non-transitional` appears to have fixed this (with a Shared network).

**Comment by LavajavaLux** [comment]
Why is this closed. Host only network does still not work with a custom host network. The VMs are not able to connect

**Comment by sivadevwiz** [comment]
After a day of struggle to get it worked in the "Shared network" setting the below Bridge network setting made it work on my Macbook for ubuntu.

@LavajavaLux this works

<img width="897" height="663" alt="Image" src="https://github.com/user-attachments/assets/fe9f63c7-5c0e-4725-a4ca-bc4608b3fc6d" />

**Comment by gabirosca** [comment]
Turn off "Display Power Management." in Kali. It did the trick for me on Mac M1.
I also put ServerAliveInterval 60 and ServerAliveCountMax 3 in my sshconfig

**Comment by Snowfighter** [comment]
System parameters: 
- M1 Pro
- macOS Tahoe
- UTM v4.3.5

I experienced the same issues with Ubuntu 24.04 and had to install it with "Emulated VLAN" and after installation I switched to "Bridged" with "virtio-net-pci-non-transitional"

**Comment by kwazieharry** [comment]
I think setting the specific interface to use fixes the issue, i noticed i had this issue once I got  a USB hub. 
So it didn't know which interface to use so network connections stopped until i selected the one to use.

**Comment by codethief** [comment]
@kwazieharry 

> I think setting the specific interface to use fixes the issue, i noticed i had this issue once I got a USB hub.

Man, you just saved me! I had already been debugging this issue for hours! As soon as I disconnect my USB hub, everything works again.

> So it didn't know which interface to use so network connections stopped until i selected the one to use.

By "it" you mean UTM or macOS? Where do you select the interface to be used?

EDIT: I figured out the answer to my questions: In the VM settings in UTM under "Network" one can pick an interface to bridge to. "Automatic" means it will use whatever interface macOS prioritizes. The assigned priorities can be changed through macOS settings -> Network -> "…" (the button with the three dots) -> Set service order. Otherwise one can also pick a specific interface in UTM. (However, if one frequently switches between different network setups (wifi vs. cable-bound), updating the UTM settings gets annoying, so it's probably best to adjust the service order.)
