### ISSUE TITLE
Download speed ok, upload speed near 0 or 0

### ISSUE THREAD

**Issue by gerbot4000** [utmapp/UTM#3805]
**Describe the issue**
I created 2 or 3 windows 7 VM and a XP. I use speedtest.net, download speed is ok, but every time I get a "upload test error". I tried the preconfigured VMs on the gallery, changed the network adapters and I always get the same problem.

**Configuration**
* UTM Version: Version 3.1.5 (53)
* OS Version: macOS Monterey 12.3
* Intel or Apple Silicon? Apple Silicon

**Comment by conath** [comment]
I just did a speed test in my XP VM using [SpeedOf.Me](https://speedof.me/) and I saw acceptable download and upload speeds. Guest is Windows XP SP3 with K-Meleon Goanna browser. Network set to "Shared Network" mode and "rtl8139" card. (Manual DNS set in the guest to get working web browsing)

My host is a MacBook Pro M1 on 12.2.1, UTM 3.1.5.
