### ISSUE TITLE
can not boot windows11

### ISSUE THREAD

**Issue by bukaixyz** [utmapp/UTM#3810]
**Describe the issue**
can not boot windows11,but boot into UEFI

**Configuration**
* UTM Version: 3.1.5
* OS Version: macOS 12.3
* Intel or Apple Silicon? Intel

**Crash log**
No

**Debug log**
Running:  -L /Applications/UTM.app/Contents/Resources/qemu -S -qmp tcp:127.0.0.1:4001,server,nowait -nodefaults -vga none -spice "unix=on,addr=/Users/wangruoming/Library/Group Containers/WDNLXAD4W8.com.utmapp.UTM/C811E05C-2E63-4EA1-8114-309D531EFE12.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off" -device virtio-vga -device virtio-rng-pci -smp cpus=8,sockets=1,cores=4,threads=2 -machine q35,vmport=off,i8042=off -accel hvf -accel tcg,tb-size=1024 -global PIIX4_PM.disable_s3=1 -global ICH9-LPC.disable_s3=1 -drive if=pflash,format=raw,unit=0,file=/Applications/UTM.app/Contents/Resources/qemu/edk2-x86_64-code.fd,readonly=on -drive "if=pflash,unit=1,file=/Users/wangruoming/Library/Containers/com.utmapp.UTM/Data/Documents/Windows 11.utm/Images/efi_vars.fd" -boot menu=on -m 4096 -device intel-hda -device hda-duplex -name "Windows 11" -usb -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device ich9-usb-ehci1,id=usb-controller-0 -device ich9-usb-uhci1,masterbus=usb-controller-0.0,firstport=0,multifunction=on -device ich9-usb-uhci2,masterbus=usb-controller-0.0,firstport=2,multifunction=on -device ich9-usb-uhci3,masterbus=usb-controller-0.0,firstport=4,multifunction=on -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 -device ide-cd,bus=ide.0,drive=cdrom0,bootindex=0 -drive if=none,media=cdrom,id=cdrom0 -device ide-hd,bus=ide.1,drive=drive0,bootindex=1 -drive "if=none,media=disk,id=drive0,file=/Users/wangruoming/Library/Containers/com.utmapp.UTM/Data/Documents/Windows 11.utm/Images/data.qcow2,cache=writethrough" -device e1000,mac=E6:8F:5B:7A:09:B8,netdev=net0 -netdev vmnet-macos,mode=shared,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -device virtserialport,chardev=charchannel1,id=channel1,name=org.spice-space.webdav.0 -chardev spiceport,name=org.spice-space.webdav.0,id=charchannel1 -uuid C811E05C-2E63-4EA1-8114-309D531EFE12 -rtc base=localtime
qemu-x86_64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: Started vmnet interface with configuration:
qemu-x86_64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: MTU:              1500
qemu-x86_64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: Max packet size:  1514
qemu-x86_64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: MAC:              ee:ca:92:30:31:cc
qemu-x86_64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: DHCP IPv4 start:  192.168.64.1
qemu-x86_64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: DHCP IPv4 end:    192.168.64.254
qemu-x86_64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: IPv4 subnet mask: 255.255.255.0
qemu-x86_64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: UUID:             66D98CA6-DC92-4B32-A35B-5F218E1E67C0
qemu-x86_64-softmmu: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
qemu-x86_64-softmmu: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
qemu-x86_64-softmmu: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
qemu-x86_64-softmmu: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
qemu-x86_64-softmmu: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
qemu-x86_64-softmmu: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
qemu-x86_64-softmmu: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
qemu-x86_64-softmmu: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
qemu-x86_64-softmmu: warning: global PIIX4_PM.disable_s3=1 not used
qemu-x86_64-softmmu: warning: Spice: record:0 (0x7f7a09840a00): setsockopt failed, Operation not supported on socket
qemu-x86_64-softmmu: warning: Spice: playback:0 (0x7f7a09840950): setsockopt failed, Operation not supported on socket
**Upload VM**
No

**Comment by bukaixyz** [comment]
I have solved it by myself.

**Comment by bwillemo** [comment]
What have you done to resolve it?
