### ISSUE TITLE
No password interaction when using full disk encryption in Full Grafics mode

### ISSUE THREAD

**Issue by ty-clapp** [utmapp/UTM#3813]
I've try to use full disk encryption but can't get password interaction in Full Grafics mode. Only clear screen with blinking cursor after loading initial ramdisk. In console mode is fine. I've try to use nomodeset in grub but with no success.

**Configuration**
* UTM Version: 3.1.5 (53)
* OS Version: 12.3
* Apple Silicon

**Comment by conath** [comment]
Your issue doesn’t mention the guest OS but it sounds like #3555. Is that what you’re trying to do?
