### ISSUE TITLE
Redesigned Preferences

### ISSUE THREAD

**Issue by swaggio7** [utmapp/UTM#3814]
I feel like the preferences panel should be redesigned, as there aren't that many things and settings to do in it. Not only that, there are 2 deprecated options which are unnecessary for future use.
![preferences_2x](https://user-images.githubusercontent.com/87071118/159996179-b57ed8e2-ceec-487e-90bb-ab224adb44f9.png)

**Comment by DJZSwag** [comment]
#3812

**Comment by osy** [comment]
Are you talking about the Cmd+, options? Those deprecated settings will be removed in the future. Otherwise I don’t see a need to “redesign” it as it’s just a bunch of check boxes…
