### ISSUE TITLE
iPad Magic Keyboard and Extended Keys

### ISSUE THREAD

**Issue by adityanz** [utmapp/UTM#3816]
It's not the VM, it's very simple. With the magic keyboard, the bottom keyboard keys bar does not disappear and comes back with the keyboard interaction and it overlays on top of the VM. 

![IMG_5205789757D3-1](https://user-images.githubusercontent.com/24827643/160084386-e8f81a08-78d7-4aa4-850b-9037e3e91bfe.jpeg)

**Configuration (required)**
* UTM Version:  v3.1.5
* OS Version: 15.5 (19E241)
* Device Model: iPad Pro 11 inch 2nd generation my232vc/a
* Is it jailbroken (name jailbreak used)?  No 
* How did you install UTM? iPA file then Altserver and altstore.

**Comment by conath** [comment]
Does the bar go away when you tap the downwards arrow on the right? (bottom right corner in your screenshot)

**Comment by conath** [comment]
I tested this myself (with a bluetooth keyboard), the bar does go away when I tap the downwards arrow.
