### ISSUE TITLE
FreeBSD with Spice Tools

### ISSUE THREAD

**Issue by oransel** [utmapp/UTM#3850]
It was a piece of cake to run FreeBSD AARCH64 in UTM on M1. XFCE installed without issues and running very smoothly. I can’t seem to find the SPICE tools for FreeBSD though. With the extensions, WM should scale to the window, clipboard sharing between host and guest, and share mounting. It would be an amazing solution. Anybody have any clue how to have SPICE tools installed?

**Configuration**
* UTM Version: 3.0.4
* OS Version: 12.3
* Intel or Apple Silicon? M1 Max

**Comment by conath** [comment]
I couldn’t find any SPICE guest tools for FreeBSD online (only found others asking for the same), seems like it might simply not exist.

**Comment by osy** [comment]
Yup, those don’t exist currently.

**Comment by oransel** [comment]
Bummer

**Comment by oransel** [comment]
Not UTM related
