### ISSUE TITLE
How to increase Debian disk space.

### ISSUE THREAD

**Issue by Jas-Grace** [utmapp/UTM#3853]
Hello, I recently downloaded Debian(xfce) from the utm galley. After installing some programs, it says - 'The volume "Filesystem root" has only 324.1 MB disk space remaining.' Is there a way I can increase the disk space? Please note that I have tried resizing the qcow2 file using qemu-img, and resized the file by increasing 10GB space, but still it gives this error.
Please help, and thanks in advance!

**Comment by conath** [comment]
After resizing with qemu-img, you have effectively replaced the virtual hard drive with a larger one. The new larger drive has the identical contents as the previous drive, including the size of the disk partitions. 

You need to grow the size of the partition within the VM to resolve the error. How this can be done depends on the guest OS and many guides can be found elsewhere online.

**Comment by Jas-Grace** [comment]
'You need to grow the size of the partition within the VM to resolve the error. How this can be done depends on the guest OS and many guides can be found elsewhere online.' couldn't find any guides 😩

**Comment by Jas-Grace** [comment]
???

**Comment by Jas-Grace** [comment]
My os is macOS(m1). Any examples?

**Comment by Jas-Grace** [comment]
> After resizing with qemu-img, you have effectively replaced the virtual hard drive with a larger one. The new larger drive has the identical contents as the previous drive, including the size of the disk partitions.
> 
> You need to grow the size of the partition within the VM to resolve the error. How this can be done depends on the guest OS and many guides can be found elsewhere online.

My os is macOS(m1). Any examples?

**Comment by conath** [comment]
For example https://unix.stackexchange.com/questions/67095/how-to-expand-ext4-partition-size-using-command-line#67107

**Comment by joshmarinacci** [comment]
How does this work? There is nothing in the UI to resize an existing disk image. The disk size is a read only field.
