### ISSUE TITLE
Causes a respring loop on jailbroken device

### ISSUE THREAD

**Issue by SarKaa** [utmapp/UTM#386]
**Describe the bug**
So I gave up on trying to install windows on my iphone, due to storage limitations, but still reinstalled altstore after a while, just to check out the new features. I get respring loops all the time, and I thought it was a bad tweak
What was weird was that whenever I would install UTM, whether it was from altstore or filza, and then try respringing, it would enter a loop. I don't know for sure, but I am pretty sure that UTM is the cause of this

**To Reproduce**
1. Install UTM
3. Close UTM from app switcher (i.e. crash it)
2. Respring
3. It gets stuck in a loop

**Crash log**
There is no way of getting any logs, as it is in a state where springboard is broken

**Comment by obbcth** [comment]
Maybe you close UTM without clicking X button.
This will cause #32, and respring loop (in jailbroken state) so you should force restart it.
In this state iDevices cannot shutdown itself and will try to reset.

**Comment by osy86** [comment]
I've heard of this issue from a few people now but only people who are jailbroken. My suspicion is that something else is the issue here. UTM is a sandboxed app so if it's able to crash the OS, then we found a 0day sandbox escape.

**Comment by rullinoiz** [comment]
> I've heard of this issue from a few people now but only people who are jailbroken. My suspicion is that something else is the issue here. UTM is a sandboxed app so if it's able to crash the OS, then we found a 0day sandbox escape.

if thats the case then congrats on the accidental find

**Comment by SarKaa** [comment]
> Maybe you close UTM without clicking X button.
> This will cause #32, and respring loop (in jailbroken state) so you should force restart it.
> In this state iDevices cannot shutdown itself and will try to reset.

Yes that is what I was trying to do, I was seeing what happens if you respring after the crash, or ldrestart, but no you have to reboot completely to run utm, which is annoying on checkra1n

**Comment by professorUnknown** [comment]
Ios 14 sandbox escape will save the day.

**Comment by professorUnknown** [comment]
Can anybody post a crash log from iOS?

**Comment by SarKaa** [comment]
> Ios 14 sandbox escape will save the day.

I mean what for, theres already checkra1n

**Comment by professorUnknown** [comment]
A12 and A13

**Comment by SarKaa** [comment]
Yeah ok it may be useful for those

**Comment by professorUnknown** [comment]
@SarKaa I think if you have Mac you can use Apple configurator 2 to see the console and log it but you have to have password off.

**Comment by ThatsNiceGuy** [comment]
I have tried extensively to reproduce this on all my devices (iPad Pro 2020 11", XR, X, 6s+, 8, SE1, a borrowed 7 and 7+, and a borrowed 11 Pro). All running iOS 13.5 or lower, jailbroken with unc0ver and only the base tweaks installed. I haven't been able to reproduce this issue.

I would close this issue, if you do encounter this it's probably a conflicting tweak. Just reboot your device.

**Comment by osy86** [comment]
Right my guess is that if your VM gets too large and run out of space, some other badly coded tweak doesn’t like that and crashes the device.
