### ISSUE TITLE
No internet connection available after switching VM to console mode

### ISSUE THREAD

**Issue by battleunicorn** [utmapp/UTM#3860]
**Describe the issue**
Similar to #3372 . I'm running Ubuntu arm server 20.04 with default configurations. When in Console Only mode the VM has no access to internet. When switching back to Full Graphics Internet works again. I have no clue why it happens. Bug is easily reproducible.

I'm not your most advanced user but I am more then willing to provide any further informations or debug info.

**Configuration**
* UTM Version: 315 (53) installed with brew 
* OS Version: Monterey 12.3
* Intel or Apple Silicon? M1

**Debug log**
With console only mode (no internet):
[debug1.log](https://github.com/utmapp/UTM/files/8398811/debug1.log)

With Full graphics (internet works): 
[debug2.log](https://github.com/utmapp/UTM/files/8398951/debug2.log)

**Upload VM**
[configplist.txt](https://github.com/utmapp/UTM/files/8398958/configplist.txt)

**Comment by conath** [comment]
This sounds like #3094. The cause of the problem in that case was the network device got a new name in Ubuntu guest when it was switched to console mode. This caused missing network settings and effectively no internet. [Here is the solution](https://github.com/utmapp/UTM/issues/3094#issuecomment-951468790). Does this help?

**Comment by battleunicorn** [comment]
Yes the solution did help.
