### ISSUE TITLE
On iOS, what's the difference between Virtualize and Emulate, for running arm64 VMs? And why does it say "virtualization is not supported on your system" on my iPad? (it's not jailbroken btw)

### ISSUE THREAD

**Issue by Oneechan69** [utmapp/UTM#3862]
More specifically, what are differences in the ways VMs run between option?

**Comment by conath** [comment]
On iOS, Apple does not allow UTM to use virtualization. It is not known for sure whether iDevice CPUs (including iPad “M1”) have the necessary hardware to theoretically support it, either. So we need to use emulation instead, and you get the “not supported” message when attempting to use virtualization.

Check out this [technical overview of UTM software architecture](https://github.com/utmapp/UTM/blob/master/Documentation/Architecture.md) for related information.
