### ISSUE TITLE
Docker and Vagrant support

### ISSUE THREAD

**Issue by PhilAndrew** [utmapp/UTM#3863]
I want Docker and vagrant support
I can't run Vagrant on Mac M1 and its super important

**Comment by adespoton** [comment]
Here's a good description of what Docker and Vagrant are good for, direct from Vagrant: https://www.vagrantup.com/intro/vs/docker

UTM is a front end for QEMU and Apple VM -- its purpose is to emulate or provide virtualization for secondary OSes.

How exactly do you propose adding Docker and Vagrant support?  To what purpose?  What's your user story?

**Comment by jonwest** [comment]
✋ I have a use case!  We're using UTM to quickly create a macOS VM for testing system setup scripts on M1 macs.  Part of that setup includes installing and configuring Docker Desktop, but we're unable to complete that setup at the moment.

Presumably there are some hurdles to overcome with this, given that nested virtualization is... not great... I honestly don't care about the performance of it—I am well aware it'll run like molasses in comparison to natively, it's more for smoke test purposes.

Is nested virtualization possible on a Mac host?

**Comment by conath** [comment]
@jonwest Apple M1* SOCs don't have nested virtualization capability. I do not know if M2 has it.
