### ISSUE TITLE
UTM for Android devices

### ISSUE THREAD

**Issue by muhammadbahaa2001** [utmapp/UTM#3869]
Won't we ever have UTM for Android (apk)? And if so, why we won't have?

**Comment by conath** [comment]
Please use the search feature before creating a new issue.

UTM on Android has been requested many times, and the reason it will not happen is twofold

1. AFAIK the developers behind UTM are mostly iOS, not Android developers. That also means we can‘t just pick up the code here and run it on Android, it‘s very platform specific.
2. UTM (on iOS) is based on QEMU. There are several Android apps based on QEMU that allow you to run VMs on an Android device.

If you want to learn more, check out #434 and the linked earlier issues.

**Comment by lentas1** [comment]
apple suck, 
create  it for android

**Comment by lentas1** [comment]
create or u suck
