### ISSUE TITLE
New UTM logo

### ISSUE THREAD

**Issue by IIWare** [utmapp/UTM#387]
This isn't an issue, and I am sorry for submitting too many issues so here is
a new UTM logo I made and I hope you like it.
new UTM logo:
![New UTM Logo](https://i.imgur.com/WTfylux.png)
if you don't think you can change the UTM logo to new logo
please let me know.
this isn't a bug, I don't know how to remove the bug label, sorry
you can remove the bug label, and I am new to github.

**Comment by osy86** [comment]
It looks fine but I’m not sure what the issue with the old logo is?

**Comment by IIWare** [comment]
> It looks fine but I’m not sure what the issue with the old logo is?

Well i am not saying that the old logo looks bad, or something, but I am just asking if you could use that logo. so could you?

**Comment by osy86** [comment]
No because rebranding is a lot of work and creates confusion. It shouldn’t be done “just because”. There has to be a good reason like “oh our previous logo was racist” or something.

**Comment by IIWare** [comment]
> No because rebranding is a lot of work and creates confusion. It shouldn’t be done “just because”. There has to be a good reason like “oh our previous logo was racist” or something.

oh ok I thought you will be offended when I tell you the reason why the logo should be changed so I should tell you the real reason?

**Comment by IIWare** [comment]
> No because rebranding is a lot of work and creates confusion. It shouldn’t be done “just because”. There has to be a good reason like “oh our previous logo was racist” or something.

should I tell you the real reason?
