### ISSUE TITLE
Debian fails to boot, invalid identifiers

### ISSUE THREAD

**Issue by Sposito** [utmapp/UTM#3872]
**Describe the issue**
I installed UTM as described below. when trying to run either arm or amd64 Debian I get the error msg of the screenshot “QEMU exited from an error: identifiers consist of letters...” full msg on screenshot.

I saw some similar problems in old issues here, would be that a regression?
![8C4BC437-6C5F-4498-A852-BAA4610CEBD9](https://user-images.githubusercontent.com/4186852/162111090-ebc89571-0009-4c68-8f1b-3bf1fee67101.png)

**Configuration (required)**
* UTM Version: 3.15
* OS Version: 12.5.5
* Device Model: IPad Air 1 lte 
* Is it jailbroken (name jailbreak used)? Yes checkra1n
* How did you install UTM? Cydia as instructions for jail broken devices

**Crash log**
None

**Debug 
[debug.log](https://github.com/utmapp/UTM/files/8439228/debug.log)
log**
For all issues, _including_ crashes, you should attach a debug log.

**Comment by conath** [comment]
Did you create this VM with the current version of UTM or with a previous one?

**Comment by Sposito** [comment]
With the current one, but yes it's an old iPad so I am locked in iOS 12.5

**Comment by Sposito** [comment]
Can someone point me to the fix commit for the "non-legacy" mode?
