### ISSUE TITLE
Not possible to share folders with macOS guest

### ISSUE THREAD

**Issue by cperezabo** [utmapp/UTM#3874]
I have installed macOS using defaults settings in the UTM wizard, providing a IPSW. No clipboard nor folder sharing is available, not even the option is available in settings

Any workaround?

**Comment by conath** [comment]
Please use the macOS Sharing preference pane to enable File Sharing in the VM, then you can access it from the host. Or enable File Sharing on the host to access that from the VM. For reference, here is the [file sharing chapter of the macOS User Guide](https://support.apple.com/guide/mac-help/set-up-file-sharing-on-mac-mh17131/12.0/mac/12.0).

Not sure what you are referring to in regards to "the option is available in settings". I don't see any sharing options for my macOS VM.

<img width="842" alt="Screen Shot 2022-04-07 at 22 46 04" src="https://user-images.githubusercontent.com/12073163/162296739-74354047-3feb-4a7a-b595-15453e0fa5f2.png">

**Comment by cperezabo** [comment]
I tried to say I didn't have the sharing option in settings.

What about clipboard?

**Comment by conath** [comment]
I see, let me explain why this isn’t available: ARM macOS VMs in UTM are forced to use Apple’s proprietary backend so we are limited to their features – it’s not open source so we can’t improve on it.
Unfortunately clipboard sharing is one of the things that is not (yet) available, along with a “baked in” shared folder option like we have for emulated VMs.

**Comment by conath** [comment]
One way we can try to affect Apple’s VM features is by sending them [feedback reports](https://feedbackassistant.apple.com).

**Comment by cperezabo** [comment]
It makes sense, thanks for the kind answer! I'll send a feedback report too. In the meanwhile I'm using the macOS file sharing over network. 
Cheers!

**Comment by DaveFlashNL** [comment]
well even sharing the folders is laden with obstacles, I can see my host's users's folders, I can access some of them, but when I open either downloads or documents, i'm greeted with a blank folder in the guest os (which is monterey), my host is Ventura on M2 Pro Macmini.

**Comment by DaveFlashNL** [comment]
i've found the fix, turn off sharing in both guest and host reboot both, turn it back on again, that's how it started working again for me. my host os is Ventura on M2 Pro Mac Mini and guest OS in UTM is Monterey
