### ISSUE TITLE
AVX flags CPU not working Mac M1

### ISSUE THREAD

**Issue by Donato1992** [utmapp/UTM#3877]
I checked on the CPU options in the advanced settings and it doesn't enable AVX for me. It only enables SSE 4.1 and SSE4.2 but not AVX. How do I enable it?

**Comment by osy** [comment]
So those options doesn’t necessarily mean it’s implemented in QEMU. If checked, it still requires QEMU to support it.

**Comment by Donato1992** [comment]
ok. so i have to wait for the developers to support this feature in the next versions of UTM?

**Comment by osy** [comment]
QEMU must support it.

**Comment by Donato1992** [comment]
@osy Would you have any other information on this?

**Comment by agraf** [comment]
AVX emulation in TCG is part of QEMU 7.2, so an update should fix this issue.

**Comment by osy** [comment]
Closing since we have merged QEMU 7.2 changes.
