### ISSUE TITLE
Digital Keyboard with Function keys for VMs

### ISSUE THREAD

**Issue by Terabyte1385** [utmapp/UTM#3886]
Windows requires users to press Shift + F10 to open a Command Prompt window in PE. F10 is also the Function key associated with the Mute Volume action. Pressing Shift + F10 will just mute my volume on the host Mac and not open the Command Prompt. I know I can use the Fn key, but that is not reliable as it sometimes just shows the Emoji picker on the host Mac. This is just an example: Function keys don't work anywhere. If this cannot be fixed, please provide a digital keyboard in a separate window with the function keys.

**Comment by conath** [comment]
UTM already shows a dedicated function row next to the system keyboard in the iOS version. On macOS, pressing and holding the Globe/FN key will change Touch Bar and Multifunction Keys to the F-keys, and this is passed to the VM accordingly. 

I don't see why the app should diverge from the macOS system way of handling function keys. It's certainly less intuitive to use an on-screen keyboard on macOS, even less a partial one. ([macOS already comes with an on-screen keyboard available from the Input menu bar item or using Accessibility shortcuts](https://support.apple.com/guide/mac-help/use-the-accessibility-keyboard-mchlc74c1c9f/mac))
