### ISSUE TITLE
macOS sharing a folder with M1 VM

### ISSUE THREAD

**Issue by tosbaha** [utmapp/UTM#3892]
**Describe the issue**
I created M1 VM with `Virtualize`. Sharing a folder is not possible with this configuration. I checked the source code and saw `VZVirtioFileSystemDeviceConfiguration` but it seems it isn't enabled. How can I enable this option? Can it be enabled by overriding the `config.plist`?

**Configuration**
* UTM Version: 3.1.5
* OS Version:  Monterey
* Intel or Apple Silicon? Apple Silicon

**Comment by osy** [comment]
The framework doesn’t support shared folders for macos guests yet. That option is only supported on Linux currently. Once Apple supports it, we will update UTM.
