### ISSUE TITLE
Adding qemu arguments not working/broken

### ISSUE THREAD

**Issue by vordenken** [utmapp/UTM#3895]
**Describe the issue**
I'm trying to launch a microOS VM and in order to configure it I add a qemu argument: `-fw_cfg name=opt/org.opensuse.combustion/script,file=/var/combustion-script`. For some reason this feature is completely broken at least on my machine. If I save it and reenter the menu, the entry is gone. If I add the entry and scroll up, it seems to be "accepted" because there is a up-arrow right next to it. If I add multiple arguments and save it, they are also somehow invisible because starting the VM no longer works (errors about the arguments pop up) but because they are invisible in the menu I can't remove them.

To reproduce: 
Add new VM in UTM.
Go to the VM settings, choose "QEMU" and scroll to the bottom.
Add an argument 
Press save
Open settings/qemu again -> Added argument is gone.
Try to run the VM -> UTM gets error because there's a argument that doesn't make sense.

Here is a screenshot:
 The UTM menu doesn't show any entries but the VM fails because of them.

<img width="1269" alt="Bildschirmfoto 2022-04-12 um 16 50 27" src="https://user-images.githubusercontent.com/62395860/162990449-fb57428c-f8a6-438a-b7cd-80b4c278574d.png">

**Configuration**
* UTM Version: 3.1.5
* OS Version: 12.3.1
* Intel or Apple Silicon? Apple 

**Crash log**
Nothing is crashing.

**Debug log**
Also nothing interesting here, only that my arguments are not right. (Because they are there multiple times but invisible in the menu)

**Upload VM**
Its the basic microOS aarch64 raw image. I had this problem also with fedora coreOS. Don't think this has to do with the vm.

**Comment by adespoton** [comment]
My experience has been that the line gets saved, but you may not see it when you re-open the tab... scrolling down and up a few times causes it to show up.
