### ISSUE TITLE
[Configuration] Delete VMs from main screen

### ISSUE THREAD

**Issue by langkhach270389** [utmapp/UTM#39]
Please add features copy duplicate machine. And delete machine. Thanks

**Comment by js-john** [comment]
You can duplicate or delete machine in the "File" App.

**Comment by langkhach270389** [comment]
Thanks very much

**Comment by The-SamminAter** [comment]
@js-john how?

**Comment by js-john** [comment]
> @js-john how?
This App. Inside UTM folder you can clone or delete the *.utm file.

![IMG_7A2C7723DF0C-1](https://user-images.githubusercontent.com/9637998/75851274-2a50e680-5e24-11ea-8f75-d5bd709d0371.jpeg)

**Comment by osy86** [comment]
Tracking in #18
