### ISSUE TITLE
Instructions to add Windows 11 aarm64 one M1 are outdated and confusing

### ISSUE THREAD

**Issue by ssbarnea** [utmapp/UTM#3907]
There are multiple problems related to missing or outdated information which makes the experience of booting a Windows machine on an M1 mac less than ideal. I will try to mention them here, so we can hopefully address them gradually

* https://mac.getutm.app/gallery/ page contains two confusing entries for aarm64: Windows 10/11 and Windows 11. Anyone can see the overlap but hardly understand its purpose. The second entry is a subset of the first.
* Microsoft link to download windows preview image does not work on Chrome, giving a weird error. Still download is possible with Safari. I contacted Microsoft support and the first suggestion was to use Edge, which I politely denied. They got me into adblocking/extensions stuff, I doubt they will do anything about it, they were just happy to close another support case. It would worth mentioning this on the guide as I seen others reporting the same issue.
* Ideally UTM should register the VDHX extension, so when someone is double clicking the file it would prompt to import it. At this moment you need to even go the extra sped of using the advanced open dialog to open it
* Website and [wiki page](https://github.com/utmapp/UTM/wiki/Install%20Windows%20ARM64%20on%20Apple%20M1) documenting the same thing, both outdated: https://mac.getutm.app/gallery/windows-11-arm and https://github.com/utmapp/UTM/wiki/Install%20Windows%20ARM64%20on%20Apple%20M1 -- the screenshots are from an older version and many UI elements moved around considerably. The loss of import button being quite a major confusing loss.
* Bypass network connection section is bit confusing as I had to only do `Shift-F10`, `Fn` being needed only for those that do not have function keys enabled by default.
* There is a section there which is worring: "Note that due to libslirp limitations, ping will not work and so Windows may think that there is still no internet connection." - Does this mean that I cannot really make networking to work? That would render the VM almost useless for any practical purpose. Still, after installing SPICE tools, networking started to work and `ipconfig` returned an IP and **ping worked!!**. Even got the dual IPv4/IPv6 stack.

Maybe it would worth removing the steps from the website and replace them with a link to the wiki, which can be updated much faster. That should also reduce the maintenance.

**Comment by Terabyte1385** [comment]
You have a point. After installing Windows 10 and 11 many times on many different computers throughout the year, both physical and virtual, I can confirm some of the instructions are of no use. `libslirp` does not seem to affect network connectivity, all you need to do is to install SPICE Tools from the ISO provided on the website, and that will install the necessary network driver. You can customise network settings in the Settings panel provided in UTM. 

Some instructions on the website include converting the VHDX from Microsoft to QCOW2 via the Terminal, but this isn't necessary as of recent versions as UTM will do that automatically.

**Comment by osy** [comment]
> https://mac.getutm.app/gallery/ page contains two confusing entries for aarm64

History here is that Microsoft replaced the Windows 10 VHDX with Windows 11 and many people still want to install Windows 10 so we added the UUP method which can also be used for Windows 11. If you want Windows 11, either guide works.

> Ideally UTM should register the VDHX extension

I disagree here because technically UTM doesn't know how to read VHDX, it can only convert it to QCOW2. It would cause confusion if people think you can launch any VDHX VMs (including for example x86_64 on ARM64).

> Website and [wiki page](https://github.com/utmapp/UTM/wiki/Install%20Windows%20ARM64%20on%20Apple%20M1) documenting the same thing, both outdated

The wiki has been updated to point to the gallery.

> Bypass network connection section is bit confusing

This will be updated in the gallery guide.

> ping will not work and so Windows may think that there is still no internet connection

This is referring to sometimes seeing a yellow exclamation mark if you're using Emulated networking.
