### ISSUE TITLE
Is anyone willing to participate in running MacOS 10.16 Big Sur natively?

### ISSUE THREAD

**Issue by Fnckerpoi** [utmapp/UTM#391]
I think ipad Pro has a high probability of being realized in the past two years。
What do you think?

**Comment by reaowe** [comment]
I am on board with testing it out. 😉

**Comment by biggiecam** [comment]
ill test it out.  I got a back up device.  actually 2, but lets rock it

**Comment by osy86** [comment]
This is not a discussion forum.
