### ISSUE TITLE
 Install Ubuntu ARM64 on Apple M1 (link in wiki)

### ISSUE THREAD

**Issue by m-c-g** [utmapp/UTM#3910]
The instructions in this file don't correspond to the behavior of the current version.
After clicking either of the buttons in the first step you get the dialog in the attached screenshot, not the screen indicated in the second step of the instructions.

**Configuration**
* UTM Version: Version 3.1.5 (53)
* OS Version: macOS Monterey 12.3.1
* Intel or Apple Silicon? M1

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open Console.app, go to `Crash Reports`, and find the latest entry for either QEMU, QEMUHelper, or qemu-\*. Right click and choose `Reveal in Finder`. Attach the report here.

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the top of the `QEMU` page is `Debug Log`. Turn it on and save the VM. After you experience the issue, open the VM settings again and select `Export Log...` and attach it here.

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.
 
<img width="801" alt="Screen Shot 2022-04-17 at 11 49 50 AM" src="https://user-images.githubusercontent.com/23322930/163728347-36f52346-5842-4f79-8a33-bc84259e2b99.png">

**Comment by osy** [comment]
Sorry, the Wiki is outdated. I will change it to point to the up to date instructions.
