### ISSUE TITLE
Allow mac toolbar in VM fullscreen mode

### ISSUE THREAD

**Issue by TJTorola** [utmapp/UTM#3919]
I would love to be able to see my mac's toolbar when I fullscreen a VM. I have toggled the setting in my system preferences not to auto-hide the toolbar on fullscreen and if I fullscreen the VM selector screen the toolbar doesn't get hidden. But when I fullscreen a VM it is hidden. I assume this is some setting that UTM is using. This is also particularly nice with the new notched macbooks, that is all deadspace if the toolbar is hidden so showing the time / wifi / bluetooth etc is nice.

Thanks.

**Comment by conath** [comment]
I’m not sure I understand. Do you want to see your Mac’s [Menu Bar](https://support.apple.com/guide/mac-help/menu-bar-mchlp1446/mac) while the UTM VM is in full screen? Or do you want to see the toolbar of the UTM VM window? (that has reset, pause, USB, CD buttons…)

**Comment by TJTorola** [comment]
Sorry, I mean the Mac menu bar. I see there is a setting for showing the toolbar already.

**Comment by conath** [comment]
Just to be sure, you already did the following: System Preferences → Dock & Menu Bar → (at the bottom) uncheck “Automatically hide and show the menu bar in full screen”.

**Comment by TJTorola** [comment]
Yes I did, I can fullscreen any other app and the menu bar stays visible. Only the VM seems to hide it for some reason.

**Comment by TJTorola** [comment]
Not a mac developer so excuse me if this is off, but it may be related to this here https://github.com/utmapp/UTM/blob/f9c04224493cded64ba7e8845b44572600539271/Platform/macOS/Display/VMDisplayWindowController.swift#L197

**Comment by osy** [comment]
I tried to delete that line but it seems like it isn't working because we manually set the window size to the size of the screen. That way we're able to display content on the whole screen. I'm not sure if it's possible to have the menu overlay the top of the screen. If not, we would have to manually calculate the size of the menu bar and subtract that height. This is additionally complicated with the notch macbooks which have a taller menu bar.

**Comment by TJTorola** [comment]
Are you on a notched macbook? I wonder if the behavior is different between models as UTM already does not attempt to cover up the menu bar space on the newer macbooks. This may be related https://developer.apple.com/documentation/bundleresources/information_property_list/nsprefersdisplaysafeareacompatibilitymode

**Comment by TJTorola** [comment]
The latest fix works perfect! Thank you.
