### ISSUE TITLE
Crash during OSX install

### ISSUE THREAD

**Issue by PsuperPsyq0** [utmapp/UTM#392]
During installation of OS X Leopard A dark grey screen appeared within UTM with a respring-like loading icon  and the app crashed altogether. I’m currently still in a jb state and am worried to reboot my device again as it was a pain in the ass the past couple times I made attempts to install OS X.

Steps to reproduce the issue;
1. Install UTM
2. Followed [THIS](https://www.ipodhacks142.com/how-to-install-full-mac-os-x-on-the-iphone-or-ipad-using-utm-no-jailbreak/) tutorial 
3. I had to partition the disk I created once OS X installer booted
4. Was successfully installing (maybe 10%) and respring-like loading icon appeared
5. app crash - fear induced to reboot

What could I do to safely respring/reboot my device without getting a loop again?!

**Comment by reaowe** [comment]
You mean Leopard not Snow Leopard?

**Comment by PsuperPsyq0** [comment]
Yeah sorry I’m not entirely familiar with Mac OS versions

**Comment by osy86** [comment]
It may be due to lack of disk space.

Otherwise, because you're jailbroken, there could be some tweak (or the jailbreak itself) that caused the crash. UTM shouldn't be able to cause a respring because it's a standard sandboxed app.

**Comment by HexCodeFFF** [comment]
Install cr4shed, it might tell you what (if any) tweaks are crashing springboard

**Comment by osy86** [comment]
This is likely space issue or QEMU issue. Closing.
