### ISSUE TITLE
PC.RAM Error on iPad Air 2 with both Android 9.0 and Windows 10 VMs

### ISSUE THREAD

**Issue by evennotodd** [utmapp/UTM#393]
![CEC60EB9-5FAA-4125-B23E-BADDF9945F9F](https://user-images.githubusercontent.com/43918795/85474827-356e8480-b583-11ea-8ebc-4fc7bd786147.jpeg)
The error is seen above. Also attaching the debug logs for the VMs. I left the Android RAM default (downloaded the file from UTM site). Created Windows 10 VM manually and assigned it 1500mb RAM. 

Android VM Log:
-[CSConnection init]:250
Loading libqemu-system-x86_64.dylib
Running:  qemu -L /private/var/containers/Bundle/Application/6209DDEB-A46F-4C39-92B8-FD148F2A3FA7/App.app/qemu -qmp tcp:localhost:4444,server,nowait -smp cpus=1,sockets=1 -machine pc,vmport=off -vga qxl -global PIIX4_PM.disable_s3=1 -global ICH9-LPC.disable_s3=1 -boot order=d -m 1024 -soundhw ac97 -name "Android 9" -drive "file=/private/var/mobile/Containers/Data/Application/5347692E-F81C-4E16-B622-BE67B94F10E2/Documents/Android 9.utm/Images/android-9.0.qcow2,if=ide,media=disk,id=drive0" -spice port=5930,addr=127.0.0.1,disable-ticketing,image-compression=off,playback-compression=off,streaming-video=off -device rtl8139,netdev=net0 -netdev user,id=net0 -device usb-ehci -device usb-tablet -device usb-mouse -device usb-kbd -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid 00EB91C7-9DC0-4F0B-BAFB-ACCFEE75D5FF -rtc base=localtime -cpu max
qemu: info: Spice: reds.c:4214:spice_server_set_seamless_migration: seamless migration enabled=0
qemu: info: Spice: reds.c:3359:do_spice_init: starting 0.14.1
qemu: info: Spice: char-device.c:690:red_char_device_reset_dev_instance: sin 0x0, char device 0x10ff0c110
qemu: info: Spice: reds.c:2561:reds_init_socket: bound to 127.0.0.1:5930
qemu: info: Spice: main:0 (0x10ff180f0): thread_id 0x16f5ab000
qemu: info: Spice: inputs:0 (0x10ff141a0): thread_id 0x16f5ab000
qemu: info: Spice: reds.c:3297:spice_server_add_interface: SPICE_INTERFACE_MIGRATION
qemu: info: Spice: reds.c:3214:spice_server_add_interface: SPICE_INTERFACE_KEYBOARD
qemu: info: Spice: reds.c:3224:spice_server_add_interface: SPICE_INTERFACE_MOUSE
qemu: cannot set up guest memory 'pc.ram': Cannot allocate memory
-[CSSession initWithSession:]:309
qemu: info: GSpice: spice-session.c:1802 no migration in progress
qemu: info: GSpice: spice-channel.c:141 main-1:0: spice_channel_constructed
qemu: info: GSpice: spice-session.c:2282 main-1:0: new main channel, switching
cs_channel_new:139
2020-06-23 20:53:58,843 DEBUG (null)-/Users/runner/runners/2.263.0/work/UTM/UTM/CocoaSpice/CSConnection.m:133 new channel (#0)
2020-06-23 20:53:58,843 DEBUG (null)-/Users/runner/runners/2.263.0/work/UTM/UTM/CocoaSpice/CSConnection.m:136 new main channel
2020-06-23 20:53:58,844 DEBUG (null)-/Users/runner/runners/2.263.0/work/UTM/UTM/CocoaSpice/CSSession.m:249 Changing main channel from 0x0 to 0x10613bf00
qemu: info: GSpice: spice-channel.c:2707 main-1:0: Open coroutine starting 0x10613bf00
qemu: info: GSpice: spice-channel.c:2544 main-1:0: Started background coroutine 0x106139a30
qemu: info: GSpice: spice-session.c:2234 main-1:0: Using plain text, port 5930
qemu: info: GSpice: spice-session.c:2165 open host 127.0.0.1:5930
qemu: info: GSpice: spice-session.c:2087 main-1:0: connecting 0x1247a6c28...
qemu: info: GSpice: spice-session.c:2071 main-1:0: connect ready
Connected to stream
QMP connection successful! (readStream:1)
qemu: info: GSpice: spice-channel.c:1367 main-1:0: channel type 1 id 0 num common caps 1 num caps 1
Connected to stream
QMP connection successful! (readStream:0)
Debug JSON recieved <- {
    QMP =     {
        capabilities =         (
            oob
        );
        version =         {
            package = "";
            qemu =             {
                major = 4;
                micro = 0;
                minor = 2;
            };
        };
    };
}
Got QMP handshake: {
    QMP =     {
        capabilities =         (
            oob
        );
        version =         {
            package = "";
            qemu =             {
                major = 4;
                micro = 0;
                minor = 2;
            };
        };
    };
}
Debug JSON send -> {
    arguments =     {
    };
    execute = "qmp_capabilities";
}

Windows 10 VM Log:
-[CSConnection init]:250
Loading libqemu-system-x86_64.dylib
Running:  qemu -L /private/var/containers/Bundle/Application/6209DDEB-A46F-4C39-92B8-FD148F2A3FA7/App.app/qemu -qmp tcp:localhost:4444,server,nowait -smp cpus=1,sockets=1 -machine pc,vmport=off -vga qxl -global PIIX4_PM.disable_s3=1 -global ICH9-LPC.disable_s3=1 -boot order=d -m 1500 -soundhw ac97 -name "Windows 10" -drive "file=/private/var/mobile/Containers/Data/Application/5347692E-F81C-4E16-B622-BE67B94F10E2/Documents/Windows 10.utm/Images/Win10_2004_English_x64.iso,if=ide,media=cdrom,id=drive0" -drive "file=/private/var/mobile/Containers/Data/Application/5347692E-F81C-4E16-B622-BE67B94F10E2/Documents/Windows 10.utm/Images/HDD.img,if=ide,media=disk,id=drive1" -spice port=5930,addr=127.0.0.1,disable-ticketing,image-compression=off,playback-compression=off,streaming-video=off -device rtl8139,netdev=net0 -netdev user,id=net0 -device usb-ehci -device usb-tablet -device usb-mouse -device usb-kbd -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid 373635AA-7AAC-46DD-9C62-B4FFEF4C9F78 -rtc base=localtime
qemu: info: Spice: reds.c:4214:spice_server_set_seamless_migration: seamless migration enabled=0
qemu: info: Spice: reds.c:3359:do_spice_init: starting 0.14.1
qemu: info: Spice: char-device.c:690:red_char_device_reset_dev_instance: sin 0x0, char device 0x1107e8110
qemu: info: Spice: reds.c:2561:reds_init_socket: bound to 127.0.0.1:5930
qemu: info: Spice: main:0 (0x1107f00b0): thread_id 0x16f217000
qemu: info: Spice: inputs:0 (0x1107ec160): thread_id 0x16f217000
qemu: info: Spice: reds.c:3297:spice_server_add_interface: SPICE_INTERFACE_MIGRATION
qemu: info: Spice: reds.c:3214:spice_server_add_interface: SPICE_INTERFACE_KEYBOARD
qemu: info: Spice: reds.c:3224:spice_server_add_interface: SPICE_INTERFACE_MOUSE
qemu: cannot set up guest memory 'pc.ram': Cannot allocate memory
-[CSSession initWithSession:]:309
qemu: info: GSpice: spice-session.c:1802 no migration in progress
qemu: info: GSpice: spice-channel.c:141 main-1:0: spice_channel_constructed
qemu: info: GSpice: spice-session.c:2282 main-1:0: new main channel, switching
cs_channel_new:139
2020-06-23 22:36:57,736 DEBUG (null)-/Users/runner/runners/2.263.0/work/UTM/UTM/CocoaSpice/CSConnection.m:133 new channel (#0)
2020-06-23 22:36:57,737 DEBUG (null)-/Users/runner/runners/2.263.0/work/UTM/UTM/CocoaSpice/CSConnection.m:136 new main channel
2020-06-23 22:36:57,737 DEBUG (null)-/Users/runner/runners/2.263.0/work/UTM/UTM/CocoaSpice/CSSession.m:249 Changing main channel from 0x0 to 0x1058f2f00
qemu: info: GSpice: spice-channel.c:2707 main-1:0: Open coroutine starting 0x1058f2f00
qemu: info: GSpice: spice-channel.c:2544 main-1:0: Started background coroutine 0x1058f0a30
qemu: info: GSpice: spice-session.c:2234 main-1:0: Using plain text, port 5930
qemu: info: GSpice: spice-session.c:2165 open host 127.0.0.1:5930
qemu: info: GSpice: spice-session.c:2087 main-1:0: connecting 0x12a64ac28...
qemu: info: GSpice: spice-session.c:2071 main-1:0: connect ready
Connected to stream
QMP connection successful! (readStream:1)
Connected to stream
QMP connection successful! (readStream:0)
qemu: info: GSpice: spice-channel.c:1367 main-1:0: channel type 1 id 0 num common caps 1 num caps 1
Debug JSON recieved <- {
    QMP =     {
        capabilities =         (
            oob
        );
        version =         {
            package = "";
            qemu =             {
                major = 4;
                micro = 0;
                minor = 2;
            };
        };
    };
}
Got QMP handshake: {
    QMP =     {
        capabilities =         (
            oob
        );
        version =         {
            package = "";
            qemu =             {
                major = 4;
                micro = 0;
                minor = 2;
            };
        };
    };
}
Debug JSON send -> {
    arguments =     {
    };
    execute = "qmp_capabilities";
}

**Comment by evennotodd** [comment]
Just want to note that my Ubuntu 18.04 VM (also downloaded from UTM) doesn’t not have this issue.

**Comment by reaowe** [comment]
You will need to allocate less memory to the android vm. If it doesn’t boot. The vm may need more memory then your device can give.

**Comment by evennotodd** [comment]
> You will need to allocate less memory to the android vm. If it doesn’t boot. The vm may need more memory then your device can give.

I used the default. Any idea how much less I should allocate? I think I only have 1gb allocated and my iPad has 2. My Ubuntu VM works fine with the same amount allocated.

**Comment by evennotodd** [comment]
Got Android to start displaying boot progress. Will see what happens and if it works. Got Ubuntu to start to boot but it was slow in doing so I am waiting to work with that.

**Comment by osy86** [comment]
You probably don't have enough RAM to run Windows or Android. The iPad Pro 2020 is probably the only device that can run them and it runs it pretty slowly. You should probably try ReactOS or Debian or Arch.
