### ISSUE TITLE
Unable to login in apple account on macOS12 VM

### ISSUE THREAD

**Issue by invokermoon** [utmapp/UTM#3935]
I just used UTM to build a new macos12 on my M1max macbook14.
Everything seems to be okay, but i can't login my apple account in setting.
And i can login my apple id in the safari in the virtual macos12.
Does anyone have this problem？

**Comment by osy** [comment]
Duplicate of #3617

**Comment by invokermoon** [comment]
@osy 
I saw your Duplicate.
So there is no way to workaround this feature?

**Comment by invokermoon** [comment]
> Duplicate of #3617
Dear osy,
I saw your Duplicate.
So there is no way to workaround this feature?

**Comment by mattruzzi** [comment]
https://kb.parallels.com/128867
https://forum.parallels.com/threads/apple-id-login-in-macos-guest-os.355059/
https://developer.apple.com/forums/thread/707682
