### ISSUE TITLE
Delete existing screenshot when option is enabled

### ISSUE THREAD

**Issue by VariableDeclared** [utmapp/UTM#3936]
Hi,

I had a quick search of open issues and could not see one that matched up; so here's the feature request.

When using UTM; UTM is periodically taking screenshots of the VM display, and, if the VM is shut down, that preview will remain. This is a privacy concern for users of UTM if the VM manager is effectively displaying their last activity, including open browsers, names, etc clearly displayed.

This request is to add an option disabling VM preview in the VM manager screen.

Many thanks,
VD

**Comment by VariableDeclared** [comment]
Okay, so I did some digging, there's an option "Do not save VM screenshot to disk".

<img width="516" alt="Screenshot 2022-04-23 at 19 07 47" src="https://user-images.githubusercontent.com/7092570/164934358-10b507ad-eaa1-4add-9060-2c02dd77fe48.png">

Enabling this will achieve the desired result **but** it will not remove screenshots that already exist. So I found a workaround -:

1. Open your favourite terminal
2. `USER=$USER_MACOS_USERNAME`
3. `cd /Users/peterdesousa/Library/Containers/$USER/Data/Documents`
4. `ls` and note you should see your VMs in this folder. Ending `.utm`. These are folders, cd into your target VM
5. Once in the VM you can run `rm screenshot.png`
6. Exit UTM
7. Reopen - the screenshot was removed for me.

I think I can close this issue for now; given that I have provided a workaround for screenshot purging,

Cheers,
VB

**Comment by osy** [comment]
Would it be useful if we delete the last saved screenshot the next time a VM is launched after “do not save screenshots” is checked?

**Comment by VariableDeclared** [comment]
hey @osy yes, I think after enabling the feature purging should occur,

VD

**Comment by VariableDeclared** [comment]
hey @osy I created a draft which might be suitable for addressing this issue, let me know what you think,
