### ISSUE TITLE
Upgrade from 3.1.5 vm failed to start with error: 'ifname' is missing

### ISSUE THREAD

**Issue by RIKEIZEN** [utmapp/UTM#3945]
**Describe the issue**
I upgraded UTM from version 3.1.5 to 3.2.0 today. When I start any aarch64 vms exist in UTM now, vm can not be started and error message dialog said: "qemu-aarch64-softmmu: -netdev vmnet-bridged,id=net0: Parameter 'ifname' is missing". x86_64 vm said: "qemu-x86_64-softmmu: -netdev vmnet-bridged,id=net0: Parameter 'ifname' is missing". I tried edit the vm network configuration   then saved it, but no use.

**Configuration**
* UTM Version: 3.2.0(54)
* OS Version: macOS 12.3
* Intel or Apple Silicon? Apple Silicon.

**Crash log**
Doesn't crash.

**Debug log**
Running:  -L /Applications/UTM.app/Contents/Resources/qemu -S -qmp tcp:127.0.0.1:4000,server,nowait -nodefaults -vga none -spice "unix=on,addr=/Users/lichao/Library/Group Containers/WDNLXAD4W8.com.utmapp.UTM/74A06755-338D-4718-8EAE-D9B0A74011F5.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=on" -device virtio-ramfb-gl -cpu host -smp cpus=4,sockets=1,cores=4,threads=1 -machine virt,highmem=off -accel hvf -accel tcg,tb-size=1024 -drive if=pflash,format=raw,unit=0,file=/Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd,readonly=on -drive "if=pflash,unit=1,file=/Users/lichao/Library/Containers/com.utmapp.UTM/Data/Documents/Windows 11 ARM64.utm/Images/efi_vars.fd" -boot menu=on -m 4096 -device intel-hda -device hda-duplex -name "Windows 11 ARM64" -device nec-usb-xhci,id=usb-bus -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device ich9-usb-ehci1,id=usb-controller-0 -device ich9-usb-uhci1,masterbus=usb-controller-0.0,firstport=0,multifunction=on -device ich9-usb-uhci2,masterbus=usb-controller-0.0,firstport=2,multifunction=on -device ich9-usb-uhci3,masterbus=usb-controller-0.0,firstport=4,multifunction=on -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 -device nvme,drive=drive0,serial=drive0,bootindex=0 -drive "if=none,media=disk,id=drive0,file=/Users/lichao/Library/Containers/com.utmapp.UTM/Data/Documents/Windows 11 ARM64.utm/Images/Windows11_InsiderPreview_Client_ARM64_en-us_22483.qcow2,discard=unmap,detect-zeroes=unmap" -device usb-storage,drive=drive1,removable=true,bootindex=1,bus=usb-bus.0 -drive if=none,media=cdrom,id=drive1 -device virtio-net-pci,mac=66:2E:B6:AE:B1:56,netdev=net0 -netdev vmnet-bridged,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid 74A06755-338D-4718-8EAE-D9B0A74011F5 -rtc base=localtime -device virtio-rng-pci
WARNING: Image format was not specified for '/Users/lichao/Library/Containers/com.utmapp.UTM/Data/Documents/Windows 11 ARM64.utm/Images/efi_vars.fd' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
qemu-aarch64-softmmu: -netdev vmnet-bridged,id=net0: Parameter 'ifname' is missing

**Upload VM**

**Comment by osy** [comment]
Can you upload your config.plist inside the .utm package? I think you have it set to bridged without selecting a bridged adapter.

**Comment by RIKEIZEN** [comment]
Thank you. This is my config.plist. As you said I didn't select a bridged adapter. But after I selected a bridged adapter, VM even fail to startup. I have attached debug.log. 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>ConfigurationVersion</key>
        <integer>2</integer>
        <key>Debug</key>
        <dict>
                <key>DebugLog</key>
                <false/>
        </dict>
        <key>Display</key>
        <dict>
                <key>ConsoleBackgroundColor</key>
                <string>#000000</string>
                <key>ConsoleFont</key>
                <string>Menlo-Regular</string>
                <key>ConsoleFontSize</key>
                <integer>12</integer>
                <key>ConsoleOnly</key>
                <false/>
                <key>ConsoleTextColor</key>
                <string>#ffffff</string>
                <key>ConsoleTheme</key>
                <string>Default</string>
                <key>DisplayCard</key>
                <string>virtio-ramfb-gl</string>
                <key>DisplayDownscaler</key>
                <string>linear</string>
                <key>DisplayFitScreen</key>
                <false/>
                <key>DisplayRetina</key>
                <true/>
                <key>DisplayUpscaler</key>
                <string>linear</string>
        </dict>
        <key>Drives</key>
        <array>
                <dict>
                        <key>DriveName</key>
                        <string>drive0</string>
                        <key>ImagePath</key>
                        <string>Windows11_InsiderPreview_Client_ARM64_en-us_22483.qcow2</string>
                        <key>ImageType</key>
                        <string>disk</string>
                        <key>InterfaceType</key>
                        <string>nvme</string>
                </dict>
                <dict>
                        <key>DriveName</key>
                        <string>drive1</string>
                        <key>ImageType</key>
                        <string>cd</string>
                        <key>InterfaceType</key>
                        <string>usb</string>
                        <key>Removable</key>
                        <true/>
                </dict>
                <dict>
                        <key>DriveName</key>
                        <string>drive2</string>
                        <key>ImagePath</key>
                        <string>efi_vars.fd</string>
                        <key>ImageType</key>
                        <string>none</string>
                        <key>InterfaceType</key>
                        <string></string>
                </dict>
        </array>
        <key>Info</key>
        <dict>
                <key>Icon</key>
                <string>windows-11</string>
                <key>IconCustom</key>
                <false/>
        </dict>
        <key>Input</key>
        <dict>
                <key>InputLegacy</key>
                <false/>
        </dict>
        <key>Networking</key>
        <dict>
                <key>NetworkCard</key>
                <string>virtio-net-pci</string>
                <key>NetworkCardMAC</key>
                <string>66:2E:B6:AE:B1:56</string>
                <key>NetworkMode</key>
                <string>bridged</string>
                <key>PortForward</key>
                <array>
                        <dict>
                                <key>GuestAddress</key>
                                <string></string>
                                <key>GuestPort</key>
                                <integer>3389</integer>
                                <key>HostAddress</key>
                                <string></string>
                                <key>HostPort</key>
                                <integer>3389</integer>
                                <key>Protocol</key>
                                <string>tcp</string>
                        </dict>
                </array>
        </dict>
        <key>Printing</key>
        <dict/>
        <key>Sharing</key>
        <dict>
                <key>ClipboardSharing</key>
                <true/>
                <key>Usb3Support</key>
                <false/>
                <key>UsbRedirectMax</key>
                <integer>3</integer>
        </dict>
        <key>Sound</key>
        <dict>
                <key>SoundCard</key>
                <string>intel-hda</string>
                <key>SoundEnabled</key>
                <true/>
        </dict>
        <key>System</key>
        <dict>
                <key>Architecture</key>
                <string>aarch64</string>
                <key>BootDevice</key>
                <string></string>
                <key>BootUefi</key>
                <true/>
                <key>CPU</key>
                <string>default</string>
                <key>ForcePS2Controller</key>
                <false/>
                <key>JITCacheSize</key>
                <integer>0</integer>
                <key>MachineProperties</key>
                <string>highmem=off</string>
                <key>Memory</key>
                <integer>4096</integer>
                <key>RTCUseLocalTime</key>
                <true/>
                <key>RngEnabled</key>
                <true/>
                <key>SystemUUID</key>
                <string>74A06755-338D-4718-8EAE-D9B0A74011F5</string>
                <key>Target</key>
                <string>virt</string>
                <key>UseHypervisor</key>
                <true/>
        </dict>
</dict>
</plist>

debug.log
Running:  -L /Applications/UTM.app/Contents/Resources/qemu -S -qmp tcp:127.0.0.1:4000,server,nowait -nodefaults -vga none -spice "unix=on,addr=/Users/lichao/Library/Group Containers/WDNLXAD4W8.com.utmapp.UTM/74A06755-338D-4718-8EAE-D9B0A74011F5.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=on" -device virtio-ramfb-gl -cpu host -smp cpus=4,sockets=1,cores=4,threads=1 -machine virt,highmem=off -accel hvf -accel tcg,tb-size=1024 -drive if=pflash,format=raw,unit=0,file=/Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd,readonly=on -drive "if=pflash,unit=1,file=/Users/lichao/Library/Containers/com.utmapp.UTM/Data/Documents/Windows 11 ARM64.utm/Images/efi_vars.fd" -boot menu=on -m 4096 -device intel-hda -device hda-duplex -name "Windows 11 ARM64" -device nec-usb-xhci,id=usb-bus -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device ich9-usb-ehci1,id=usb-controller-0 -device ich9-usb-uhci1,masterbus=usb-controller-0.0,firstport=0,multifunction=on -device ich9-usb-uhci2,masterbus=usb-controller-0.0,firstport=2,multifunction=on -device ich9-usb-uhci3,masterbus=usb-controller-0.0,firstport=4,multifunction=on -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 -device nvme,drive=drive0,serial=drive0,bootindex=0 -drive "if=none,media=disk,id=drive0,file=/Users/lichao/Library/Containers/com.utmapp.UTM/Data/Documents/Windows 11 ARM64.utm/Images/Windows11_InsiderPreview_Client_ARM64_en-us_22483.qcow2,discard=unmap,detect-zeroes=unmap" -device usb-storage,drive=drive1,removable=true,bootindex=1,bus=usb-bus.0 -drive if=none,media=cdrom,id=drive1 -device virtio-net-pci,mac=66:2E:B6:AE:B1:56,netdev=net0 -netdev vmnet-bridged,id=net0,ifname=en0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid 74A06755-338D-4718-8EAE-D9B0A74011F5 -rtc base=localtime -device virtio-rng-pci
WARNING: Image format was not specified for '/Users/lichao/Library/Containers/com.utmapp.UTM/Data/Documents/Windows 11 ARM64.utm/Images/efi_vars.fd' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
qemu-aarch64-softmmu: Addressing limited to 32 bits, but memory exceeds it by 1073741824 bytes

**Comment by osy** [comment]
That’s a different issue and addressed in the release notes.

**Comment by RIKEIZEN** [comment]
Ah, Got it, thanks a lot for your help.

**Comment by mindesik** [comment]
Change network mode to "Shared network"
