### ISSUE TITLE
The tab of the VM is confusing

### ISSUE THREAD

**Issue by alan0890** [utmapp/UTM#395]
I pressed the arrow which is facing upwards on the tab while the vm was running. Now the tab is gone and I can’t access anything even I can’t access the keyboard pls help

**Comment by IIWare** [comment]
> I pressed the arrow which is facing upwards on the tab while the vm was running. Now the tab is gone and I can’t access anything even I can’t access the keyboard pls help

Use a three-finger swipe down gesture to get it to re-appear.

**Comment by alan0890** [comment]
Also how do I right click?

**Comment by IIWare** [comment]
> Also how do I right click?

tap with two fingers

**Comment by alan0890** [comment]
Thanks a lot

**Comment by IIWare** [comment]
> Thanks a lot

you're welcome, and if you need anymore help, just click [HERE](https://getutm.app/faq)
