### ISSUE TITLE
Allow import VMs from site other than github.com

### ISSUE THREAD

**Issue by smattar2020** [utmapp/UTM#3950]
I would like to import VMs from OneDrive via utm://downloadVM?url=<RAW ONEDRIVE LINK> When I do this, UTM says, failed to parse download URL

**Comment by osy** [comment]
That’s not an UTM issue. OneDrive probably doesn’t allow for direct downloading. You’re probably downloading a webpage preview.

**Comment by smattar2020** [comment]
It is a raw file. I have checked.

**Comment by osy** [comment]
Only .utm inside a zip is supported

**Comment by smattar2020** [comment]
It is inside a zip. The URL just doesn't show it.

**Comment by smattar2020** [comment]
> Only .utm inside a zip is supported

It is a .utm inside a .zip
