### ISSUE TITLE
Allow import VM from URL with redirects

### ISSUE THREAD

**Issue by smattar2020** [utmapp/UTM#3953]
I have a UTM file online that is a .utm.zip but the URL doesn't show it. How would I go to utm://downloadVM?url=<MYURL>. It says failed to parse download URL.

**Comment by osy** [comment]
Maybe provide the URL to @conath who can look into it.

**Comment by smattar2020** [comment]
The URL is https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBbzNpSVRXZV9FWmdwdEllVmM0NUFHSkdRdkZKTnc_ZT10cmZEOVk/root/content

**Comment by conath** [comment]
The link you shared redirects to a .utm.zip, but UTM doesn't recognize this. The download feature doesn't follow redirects currently.

**Comment by osy** [comment]
Shouldn’t be hard to implement right?

**Comment by conath** [comment]
According to [this](https://developer.apple.com/forums/thread/130623) it might already work if we just remove the .utm.zip check, don't have time to check right now.

**Comment by smattar2020** [comment]
I made a fork and fixed it in the fork. I will submit a pull request.
