### ISSUE TITLE
Combined size of system firmware exceeds ... bytes

### ISSUE THREAD

**Issue by PenguinMan1219** [utmapp/UTM#3958]
<img width="261" alt="Screen Shot 2022-04-30 at 3 58 05 PM" src="https://user-images.githubusercontent.com/82232790/166120814-5301e46f-9bf9-4b0a-ba3d-f614d1a169ef.png">
What's happening currently?

_Originally posted by @PenguinMan1219 in https://github.com/utmapp/UTM/discussions/3956#discussioncomment-2667228_

**Comment by osy** [comment]
Please post debug.log and config.plist

> For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the top of the `QEMU` page is `Debug Log`. Turn it on and save the VM. After you experience the issue, open the VM settings again and select `Export Log...` and attach it here.

> (Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by conath** [comment]
This happens when you use an uncompressed EFI BIOS image with a Q35 machine. You need to use compressed .fd file for the BIOS, and uncompressed file for the variables.
