### ISSUE TITLE
How do I transfer my files from iOS to windows on UTM??

### ISSUE THREAD

**Issue by alan0890** [utmapp/UTM#396]
How do I do it??

**Comment by jankais3r** [comment]
Via iTunes File Sharing

**Comment by alan0890** [comment]
No I meant the windows which is running on UTM. I want to transfer files from my iOS to it

**Comment by jankais3r** [comment]
https://github.com/utmapp/UTM/wiki/Useful-tips#webdav-shared-folders

**Comment by alan0890** [comment]
But I am using windows 98

**Comment by osy86** [comment]
You can build a custom iso but this is not a support forum. Please use discord or some other means.
