### ISSUE TITLE
Capslock issue with 3.2.1 update

### ISSUE THREAD

**Issue by upstroke-version** [utmapp/UTM#3974]
**Describe the issue**
  I've noticed that there was a change in the way UTM recognizes Caps lock with v3.2.1 patch which is "Caps lock state will now be synchronized when mouse is captured (note that if mouse is captured before the guest OS has booted up, the state will be out of sync) (https://github.com/utmapp/UTM/issues/3415)".

**But this change introduces new problem for none native english users.**
I don't really know about US keyboard layouts, but in other layouts which they have to input multiple languages(with different alphabets), Apple uses Caps lock key as input method switcher.
Short pressing Caps lock keys work as a input method switch, and long pressing Caps lock keys turns on and off normal Caps lock feature.
The problem with this patch is that lots of users edit registry on Windows or use third party programs on Windows to remap Caps lock key to work as a Windows's input method switching key, so they could have a consistent experience between Windows and macOS.
(FYI default input method switching key is in very different  location on each OS)
**After this update, this method really doesn’t work**. 
We really nead an option to use legacy way to use our capslock key

**Configuration**
* UTM Version: v3.2.1(beta)
* OS Version: macOS 12.4 Beta (21F5063e)
* Intel or Apple Silicon? Apple Silicon

**Comment by osy** [comment]
How about an option in preferences to treat Caps lock as a regular key (the old behaviour)?

**Comment by upstroke-version** [comment]
> How about an option in preferences to treat Caps lock as a regular key (the old behaviour)?

If you mean UTM's preferences, that would be awesome!
