### ISSUE TITLE
Can you give me the link for discord server of this Forum?

### ISSUE THREAD

**Issue by alan0890** [utmapp/UTM#398]
Actually I need live support that’s why I am asking discord server for UTM

**Comment by jankais3r** [comment]
https://discord.gg/CYjSWd

**Comment by lyons88** [comment]
Can I join the discord too?

**Comment by desrod** [comment]
The above Discord invite is invalid, and should be removed so it no longer appears in search results.

**Comment by osy** [comment]
Done
