### ISSUE TITLE
Cannot allocate more than 3500 MB RAM on 8GB iPad Pro

### ISSUE THREAD

**Issue by pranav-bhatt** [utmapp/UTM#3982]
Thank you for taking the time to read my issue.

**Describe the issue**
I'm using a 2021 iPad Pro 11" M1 (8GB) running iPadOS 15.1. When I try and allocate more than 3600 MB of memory, I get the following error:
```
QEMU exited from an error: qemu-system: cannot set up guest memory 'mach-virt.ram': Cannot allocate memory
```

I'm aware that earlier, apps couldn't request for more than 5 GB RAM. However with iPadOS 15, apparently apps can request up to 6 GB on my device [as stated in this article](https://www.macrumors.com/2021/09/17/ipados-15-up-to-12gb-ram-high-end-ipad-pro/): 
```
The new details were shared by the developers behind the graphic design app Artstudio Pro, and according to their findings
on the highest-end ‌M1‌ ‌iPad Pro‌, which features 16GB of RAM, apps can request through the entitlement
to use up to 12GB of that available memory. On the other ‌M1‌ ‌iPad Pro‌ models, which feature only 8GB of RAM,
apps can request up to 6GB.
```

The memory warning that is shown while trying to increase the allocated RAM is as follows:
```
Allocating too much memory will crash the VM. 
Your device has 5082 MB of memory and the estimated usage is 4736 MB.
```
I believe these details are shown incorrectly. Not sure if the `total memory` and `used memory` being reported is in fact what has been allocated to the app, or if there is some other issue. 

I would greatly appreciate if you could clarify if this is due to how iPadOS works or if this is a genuine issue. Thank you for your time!

**Configuration (required)**
* UTM Version: 3.1.5
* OS Version: iPadOS 15.1
* Device Model: iPad Pro 11-inch 3rd generation (8GB RAM)
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? AltServer+AltStore

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/8619985/debug.log)

**Comment by Halo-Michael** [comment]
You need sign entitlement com.apple.developer.kernel.increased-memory-limit for your UTM app.

**Comment by Halo-Michael** [comment]
CC: https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_kernel_increased-memory-limit?language=objc

**Comment by kkk669** [comment]
You need two entitlements, `com.apple.developer.kernel.increased-memory-limit` and `com.apple.developer.kernel.extended-virtual-addressing`. Please see #3318.

**Comment by Halo-Michael** [comment]
com.apple.developer.kernel.extended-virtual-addressing entitlement need a paid Apple developer account, so ¯\_(ツ)_/¯

**Comment by pranav-bhatt** [comment]
The frustration I'm feeling rn can't be expressed 😅.

Is this something that can be dealt with on a jailbroken device in the future?

**Comment by osy** [comment]
If you’re jailbroken you can use those entitlements without a developer account.

**Comment by pranav-bhatt** [comment]
That makes me hopeful xD. Unfortunately I don't have a mac to compile this project. Would it be possible to consider maintaining a version with the entitlements enabled, or would that add a ton of work/be unfeasible?

**Comment by osy** [comment]
Doesn't work that way. You need to sign it for your own iPad. Otherwise we wouldn't need this whole AltStore stuff...

**Comment by pranav-bhatt** [comment]
Damn, I might have to use OSX-KVM then. Thank you so much for your help!

With the AltJIT feature being released in the mainline, there will be more people with this query. Would this issue be a good candidate to be pinned?

**Comment by osy** [comment]
AltJIT has nothing to do with entitlements. As was pointed out before the only way is to have a paid Apple Developer account or to jailbreak. I promise you I'm not purposely leaving out information.

**Comment by pranav-bhatt** [comment]
No no, please don't get me wrong, I'm not questioning anything you said. I've edited my original comment to make it clearer. Sorry for any misunderstandings
