### ISSUE TITLE
Human User Interface Review

### ISSUE THREAD

**Issue by jsoref** [utmapp/UTM#3984]
**Describe the issue**

### Steps
1. Install UTM
2. Open UTM
    <img width="1012" alt="image" src="https://user-images.githubusercontent.com/2119212/166822393-b00564c6-ac18-4315-9641-c4b5d4113407.png">
3. Click `Create a New Virtual Machine`
   ![image](https://user-images.githubusercontent.com/2119212/166821856-244b0f68-0b4c-438e-8e97-6f6fd6976d92.png)
4. Click `Virtualize`
    <img width="1012" alt="image" src="https://user-images.githubusercontent.com/2119212/166822553-2f1a89c8-0d0b-4c7f-80d2-82bef22b7fa1.png">
5. Click Windows
6. Uncheck `Import VHDX Image` (the `I` in `Image` should probably be `i`) -- see [https://docs.microsoft.com › ... › Desktop manufacturing](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/deploy-windows-on-a-vhd--native-boot)
Oct 1, 2021 — Maintaining and deploying a common reference VHDX image to execute in either
7. Click `Browse`
    <img width="1012" alt="image" src="https://user-images.githubusercontent.com/2119212/166821948-610b19eb-fc3f-4bc3-85ca-3169daaa99f8.png">
8. Note that the button for closing the file picker is `Cancel` and not `Close`
9. Select an ISO and click `Open`
10. Click `Next` 
11. Click `Next` 
12. Click `Next`
     <img width="1012" alt="image" src="https://user-images.githubusercontent.com/2119212/166824074-fc0ede83-e065-4251-95c8-568831ebebba.png">
13. Offhand, the Browse/Clear things feel wrong, but I can't find a point of reference.
14. I'm fairly confident `Read only share?` shouldn't have a `?` -- Possibly `Share read only`
15. macOS doesn't tend to talk about `Directory`, it would generally use `Folder`
16. Click `Next`
    <img width="1012" alt="image" src="https://user-images.githubusercontent.com/2119212/166828283-42de3490-06d0-4f72-9f89-b4bb85a72c86.png">
17. Generally macOS doesn't show paths -- instead one can command click to see the path:
    <img width="144" alt="image" src="https://user-images.githubusercontent.com/2119212/166830570-28aac609-1e82-4ad5-ac78-2fec9190cc2f.png">

 
### References
1. Open `System Preferences.app`
2. Click `Keyboard`
3. Click `Set Up Bluetooth Keyboard`
    <img width="780" alt="image" src="https://user-images.githubusercontent.com/2119212/166823496-0a6a11c0-1a08-44aa-9199-6a5fdc6286f4.png">
4. Note that the _Back_ button is `Go Back`
    * Apple uses `Back` in the initial macOS install wizard. But most other wizards (including the installer wizard) seem to use `Go Back`. A sample installer app is [macfuse](https://github.com/osxfuse/osxfuse/releases/tag/macfuse-4.2.5) -- download the [dmg](https://github.com/osxfuse/osxfuse/releases/download/macfuse-4.2.5/macfuse-4.2.5.dmg) and open the .pkg -- no need to allow anything, you can see the `Go Back` button in the background:
    <img width="732" alt="image" src="https://user-images.githubusercontent.com/2119212/166827281-6cafcd74-7338-479a-82d4-a91b36a73543.png">
5. Note that the opposite of `Go Back` is `Continue`, not _Next_

### Expected results
* The buttons should be wider (see the file picker picture and others)
* `Close` is not a commonly used button on macOS. As the button here effectively Cancels the task, it should be labeled `Cancel`
* Pressing `<esc>` should trigger this Cancel button if there isn't a back button.
* It should probably be on the right side of the dialog
* `Next` should be `Continue`
* `Back` should be `Go Back`

**Configuration**
* UTM Version: 3.1.5 (53)
* OS Version: 12.3.1 (21E258)
* Intel or Apple Silicon? M1

**Crash log**

**Debug log**

**Upload VM**

**Comment by osy** [comment]
I've made most of the suggested changes with the following exception

> the I in Image should probably be i

The options here are titles and follow title casing ("Use Virtualization" as another example)

> macOS doesn't tend to talk about Directory, it would generally use Folder

"Directory sharing" is the name of the feature and is referred to as such in various places. I think changing it now may cause some confusion.
