### ISSUE TITLE
Kubuntu installation crashes after “A start job is running for Snap Daemon”

### ISSUE THREAD

**Issue by HexCodeFFF** [utmapp/UTM#399]
![image](https://user-images.githubusercontent.com/35177464/85666821-85804080-b682-11ea-9f33-8122eb858b39.png)
![image](https://user-images.githubusercontent.com/35177464/85666992-b9f3fc80-b682-11ea-9cb2-5614024978fd.png)
![image](https://user-images.githubusercontent.com/35177464/85667004-bceeed00-b682-11ea-963a-9f46bd0b4caa.png)

The kubuntu hash is correct and internal hash checks don’t fail so that’s not the problem
Trying to boot with an arm64 processor does nothing so that won’t fix it

Here’s debug.log: https://controlc.com/5b02a326

Just to clarify: kubuntu crashes, UTM _seems_ to keep working fine

**Comment by osy86** [comment]
Any chance you can try on QEMU? Could be a qemu issue.

**Comment by HexCodeFFF** [comment]
It appears to be a qemu issue. I'm trying different args to hopefully fix it and if I get it working i'll close the issue.

**Comment by HexCodeFFF** [comment]
I let it sit at the installations free for a _while_ and eventually it got to a GUI and said there was a fatal error

I forgot to take a screenshot

**Comment by osy86** [comment]
Closing since it’s a QEMU issue.
