### ISSUE TITLE
Adding "-netdev vmnet-macos,mode=bridged,id=net0" is not supported anymore

### ISSUE THREAD

**Issue by bartheerman** [utmapp/UTM#3999]
**Describe the issue**
I used additional qemu cli parameters to have multiple network interfaces. Since UTM 3.2.0 (and qemu 7), vmnet-macos is not supported anymore. What alternative could be used?

**Configuration**
* UTM Version: > 3.2.0 beta
* OS Version: 12.3.1
* Intel or Apple Silicon? Apple Silicon

**Crash log**
n/a

**Comment by bartheerman** [comment]
I found the new setup. It seemd to be `-netdev vmnet-bridged,id=net0,ifname=en0` and `-netdev user,id=net1`.

**Comment by osy** [comment]
Why not use the GUI?

**Comment by osy** [comment]
I see so a vote for #3585

**Comment by dmilith** [comment]
Well, if you want bridged networking in Qemu on modern macOS, there's only one solution that will work no matter which Qemu version you use (I use v6.1.0 with the HVF acceleration patch).

See stuff from https://github.com/lima-vm/socket_vmnet/tree/master#qemu

Checked on macOS 12.6.x arm64, bridged networking works like a charm!

**Comment by rebroad** [comment]
I get "Parameter 'type' does not accept value 'vmnet-bridged'" - does qemu need special command-line configure arguments to enable this, or particular packages installed first?

**Comment by osy** [comment]
1. This is a closed issue and is not relevant.
2. The contents of this issue has been outdated for a long time.
3. Custom arguments are unsupported and should only be used for debugging. There is no promise that they continue working.
