### ISSUE TITLE
Add button for ACPI shutdown

### ISSUE THREAD

**Issue by fulldecent** [utmapp/UTM#4001]
# Background 

There's three ways to turn off a physical computer:

1. Login, ask the operating system to shutdown (may require admin permission)
2. Yank the power cord.
3. Press a physical button on the computer to indicate you want to shutdown.

# Abstract

UTM supports the first two. I hope we can support 3., which is called ACPI shutdown.

# Proposal

In the GUI this can be done by changing what happens when you click the shut down button.

Currently it asks if you are sure you want to yank the power cord "CONFIRMATION: this may corrupt the VM and any unsaved changes will be lost. To quit safely, shut down from the guest."

But this could be changed instead to show a dialog box with options:

> 1. Soft shutdown (ACPI, requires OS support)
> 2. Hard shutdown (immediate stop, may corrupt VM)
> 3. Cancel
> 
> Note you may also be able to shut down inside the guest operating system.

**Comment by JacksonChen666** [comment]
alternative dialog:

```
ACPI shutdown
2.

**Comment by JacksonChen666** [comment]
alternative dialog:

How would you like to shutdown the VM?
- ACPI shutdown
- Hard shutdown
- Cancel

(hard shutdown button is red to indicate a *slightly* dangerous action, both shutdown action would prompt for confirmation and hard shutdown may include info that vm might corrupt, may also apply to restarts if that exists)

**Comment by osy** [comment]
It is my opinion that such a feature will lead to "complexity creep". Most (90%) of people won't know what "ACPI shutdown" means or how it's different from other kinds of shutdown. Most people also won't need such an option. Maximum flexibility will come at a cost of a more difficult to understand UX. In most cases, you can trigger an ACPI shutdown directly from the guest.

**Comment by fulldecent** [comment]
In order to shutdown from the guest you need to login. And then you need the root password.

It's a lot of steps. So maybe other people also like the ACPI option.

**Comment by conath** [comment]
Agree we need a “safe shutdown” button. See https://github.com/utmapp/UTM/issues/3859#issuecomment-1114787051, closes 3859

**Comment by introns-bungles** [comment]
> ...Most (90%) of people won't know what "ACPI shutdown" means or how it's different from other kinds of shutdown...

To be honest UTM is already pretty "complex" as such pieces of specialized software are. I tend to believe most users with the need to emulate/virtualize are more tech-savvy to begin with.

**Comment by alejandroacostaalamo** [comment]
> Agree we need a “safe shutdown” button. See [#3859 (comment)](https://github.com/utmapp/UTM/issues/3859#issuecomment-1114787051), closes 3859

+1

**Comment by mbbee** [comment]
> Agree we need a “safe shutdown” button. See [#3859 (comment)](https://github.com/utmapp/UTM/issues/3859#issuecomment-1114787051), closes 3859
+1

**Comment by anonymousaga** [comment]
+1

**Comment by anonymousaga** [comment]
Just curious:
1. Will this require spice guest tools or any acpi-compliant os?
2. When approximately will 4.1 be released with this feature (beta and stable)?

Thanks in advance for adding this feature!

**Comment by JacksonChen666** [comment]
this feature requires ACPI functioning systems because it uses ACPI stuff

**Comment by osy** [comment]
The way QEMU implemented it is more generic. Any hw can hook on to that call. In practice I think it’s probably most useful in ACPI systems.

**Comment by fgclue** [comment]
> +1

+1

**Comment by anonymousaga** [comment]
@osy sometimes I find myself clicking the power button accidentally instead of holding it down. I know this is petty and thank you for configuring the ACPI, but do you think it would be possible in settings to add a toggle to "show advanced shutdown options by default"? Many thanks in advance, and I love your software!

**Comment by stuaxo** [comment]
I had no idea that holding down the power button showed more options until reading this.

It would be nice if the defaults were the safest for the user:  closing the window could save a snapshot that is restored next time, and hitting the power button would attempt an ACPI shutdown, after some timeout a dialogue could ask if you want to force shutdown.

**Comment by mbk5631** [comment]
I didn't either, maybe either what anonymousaga suggests or let people set the default action.

**Comment by Mister-A** [comment]
For me setting default close action, as one can with VirtualBox, is the only way to gracefully handle host shutdowns and reboots.

A bare minimum is a pop up on any close request asking what type of shutdown is required, Request Shutdown, Force, or Cancel.

**Comment by wpiekutowski** [comment]
I'd love to have a setting that would either send ACPI shutdown for all running guests on host user log out or shutdown/reboot. The second option could be to save a snapshot. This would block UTM quitting until all guests gracefully exit.

**Comment by Mister-A** [comment]
I believe you'll find the newest build does now save state of guest VMs that are capable of being suspended when the host application is requested to quit.

> Automatically save state when you close a VM This will only work on VMs that support save states. If your VM does not support it, you will get an error message with an explanation.

https://docs.getutm.app/updates/v4.4/

**Comment by stuaxo** [comment]
Great stuff, I'll wait until the `GL_ARB_clear_texture` bug is resolved before trying this, but it looks good.
