### ISSUE TITLE
Auto-Update for UTM? (Ignore the bug label I don't know how to remove it)

### ISSUE THREAD

**Issue by IIWare** [utmapp/UTM#401]
can you add new feature called "auto update" for utm app?
or maybe add a check for updates button?

It will be much better than always checking on the new releases.
I don't know how to remove the bug label :(

**Comment by osy86** [comment]
If you are an altstore Patreon supporter you can use the altstore repo to get updates. iOS apps do not provide their own update system and UTM is a normal iOS app.

**Comment by IIWare** [comment]
> If you are an altstore Patreon supporter you can use the altstore repo to get updates. iOS apps do not provide their own update system and UTM is a normal iOS app.

oh ok, now I know, sorry for me misunderstanding.
