### ISSUE TITLE
secondary click not working

### ISSUE THREAD

**Issue by xpitt** [utmapp/UTM#4018]
**Describe the issue**
show the VM’s package location in Finder (as well as the other options) by secondary click does not work on utm 3.2.3 (all vms)
**Configuration**
* UTM Version: 3.2.3
* OS Version: macos 12.4 rc
* Intel or Apple Silicon? 
Apple Silicon
**Crash log**
If the app crashed, you need a crash log. To get your crash log, open Console.app, go to `Crash Reports`, and find the latest entry for either QEMU, QEMUHelper, or qemu-\*. Right click and choose `Reveal in Finder`. Attach the report here.

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the top of the `QEMU` page is `Debug Log`. Turn it on and save the VM. After you experience the issue, open the VM settings again and select `Export Log...` and attach it here.

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by xpitt** [comment]
same on intel macos 12.3.1, macbook pro 13" 2016

**Comment by osy** [comment]
I am unable to reproduce. You see the menu but clicking any of the options does nothing?

**Comment by xpitt** [comment]
Right-clicking any of the vm names nothing happens, no menu shos up, unlike it was with the previous version; then, I used it to open the vm location in finder.

**Comment by osy** [comment]
Right clicking on the trackpad? Or two finger clicking?

**Comment by tiiiecherle** [comment]
I have the same issue on an ARM MacBookPro.
If you open UTM and try to right click on any of the vm's two finger click on the trackpad works but right clicking by using control + on finger click does not work. The issue is present in all versions 3.2.x.
Thanks for fixing in advance.

**Comment by osy** [comment]
@xpitt I can reproduce with Control+Click but not with Two Finger or with "Right of trackpad" settings. Can you clarify how you are doing the secondary click? If it is just Control+Click, I can easily fix it.

**Comment by xpitt** [comment]
It is control +click
