### ISSUE TITLE
3D Graphics acceleration on Windows VM for Mac

### ISSUE THREAD

**Issue by akxks** [utmapp/UTM#4028]
3D Graphics acceleration on Windows VM for Mac
Could implement it by adding a translation layer that translates to the Metal API for Mac.

This way we will be able to play games on Mac.

**Comment by osy** [comment]
Windows 3D requires driver support for Windows. Currently there is nobody with the required expertise to work on such an immense project.

**Comment by Rastafabisch** [comment]
There is some very promising early work happening on that front now.
https://github.com/virtio-win/kvm-guest-drivers-windows/pull/943
