### ISSUE TITLE
Can't shutdown the device because of UTM

### ISSUE THREAD

**Issue by LorenzoAlb2003** [utmapp/UTM#403]
I have installed UTM on my Iphone 11 pro using Altstore (the device is updated to the last stable version which is iOS 13.5.1), and the app works perfectly. Sfortunately i think that UTM is at the moment too heavy for a non-jailbroken device because everytime i shutdown my iphone the screen is blank and no buttons work. After few seconds the device is starting. So i can't shutdown it, but only reboot. Is there a solution currently or this is an unresolved bug? Thanks in advance.

**Comment by osy86** [comment]
Did you make sure to use the X button (or power button in the VM) as it warns you on first boot?

**Comment by LorenzoAlb2003** [comment]
Yes, i have tried a few times. But now i'm reinstalling the app and all works fine. Probabily there was something that disturbed the OS. Sorry for the inconvenience. I realised that the app works much better on a jailbroken device.
