### ISSUE TITLE
.OVA file in UTM -- Urgent

### ISSUE THREAD

**Issue by RwdBass** [utmapp/UTM#4043]
**Describe the issue**
I need to run Vulnerable VMs on my UTM for a class. The VM is in .OVA and I have converted it into qcow2 using qemu-img.
I create a new UTM VM --> Emulate --> Skip ISO Boot --> Delete the existing drive and import the qcow2 drive --> unselect UEFI boot --> start the machine.
I have used these steps for Metasploitable and it work but for this image it is not working

**Configuration**
* UTM Version: 3.2.3
* OS Version: macOD Monterey Version 12.4
* Apple Silicon 

Here's a screenshot when booting:
<img width="1440" alt="Screen Shot 2022-05-20 at 10 20 46 AM" src="https://user-images.githubusercontent.com/72977353/169486917-d91ee07c-8f8b-47e2-be85-06a90f5e29c9.png">

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/8737752/debug.log)

The VM is found and downloaded from Vulnhub: https://www.vulnhub.com/entry/unknowndevice64-1,293/

**Comment by conath** [comment]
OVA import is not a supported use case in UTM, and Github issues is not where we provide support regarding third party software.

With every import from another VM backend there is lots that can go wrong, especially if you don't know the virtual hardware used when the VM was created. 

You can inspect the .OVA file in a text editor application to see the virtual hardware it is expecting. Then change your UTM VM settings to match as close as possible- I would also try both with and without UEFI boot enabled. Good luck!
