### ISSUE TITLE
Apple Virt macOS 11 -> 12 default values not saved

### ISSUE THREAD

**Issue by ktprograms** [utmapp/UTM#4048]
**Describe the issue**
https://github.com/utmapp/UTM/commit/5bcbb7af51b4420249b56401cf4ca53ea2ff395b allows importing and running an Apple Virt VM created on macOS 11, but the new config with default values isn't saved, so after closing and reopening UTM it shows as Unavailable.

**Configuration**
* UTM Version: 3.2.4
* OS Version: 12.3.1
* Intel or Apple Silicon? M1

**Comment by osy** [comment]
That’s weird that it would be unavailable. Wouldn’t the same code just run again?

**Comment by ktprograms** [comment]
Oh, sorry, I think this is being caused by the shortcut problem.

Is there a way to move the an Apple Virt VM into the sandbox?

**Comment by osy** [comment]
You should be able to with “clone” then delete the original.

**Comment by ktprograms** [comment]
Thanks, that worked!
