### ISSUE TITLE
ERROR install in older ios, is there anyway to compile it to ios 9?

### ISSUE THREAD

**Issue by rnadesignlab** [utmapp/UTM#405]
I have an ipad 3, ios 9.3.5
I tried to sideload UTM but always fail.
I read that it works for ios 11+
is there anyway to compile this to an older ios version like ios 9?
how to do it?
sorry I am new to this.
many thanks

**Comment by IIWare** [comment]
> I have an ipad 3, ios 9.3.5
> I tried to sideload UTM but always fail.
> I read that it works for ios 11+
> is there anyway to compile this to an older ios version like ios 9?
> how to do it?
> sorry I am new to this.
> many thanks

I am not entirely sure. but for now, you can either use BOCHS for iOS or iBox v2.6.8 or just upgrade to ios 11 or above.

**Comment by reaowe** [comment]
His iPad 3 doesn’t support iOS 11. Max iOS 9 which what it’s on.

**Comment by rnadesignlab** [comment]
> > I have an ipad 3, ios 9.3.5
> > I tried to sideload UTM but always fail.
> > I read that it works for ios 11+
> > is there anyway to compile this to an older ios version like ios 9?
> > how to do it?
> > sorry I am new to this.
> > many thanks
> 
> I am not entirely sure. but for now, you can either use BOCHS for iOS or iBox v2.6.8 or just upgrade to ios 11 or above.

I am only be able to install old version of bochs which have issue with the screen (only 1/4 of the screen) and only win3.11 and win95. Any bochs that is in the github is for newer ios version.

Meanwhile I am stuck with ios 9.

**Comment by osy86** [comment]
iOS 11 is the minimum supported version.

**Comment by IIWare** [comment]
> > > I have an ipad 3, ios 9.3.5
> > > I tried to sideload UTM but always fail.
> > > I read that it works for ios 11+
> > > is there anyway to compile this to an older ios version like ios 9?
> > > how to do it?
> > > sorry I am new to this.
> > > many thanks
> > 
> > 
> > I am not entirely sure. but for now, you can either use BOCHS for iOS or iBox v2.6.8 or just upgrade to ios 11 or above.
> 
> I am only be able to install old version of bochs which have issue with the screen (only 1/4 of the screen) and only win3.11 and win95. Any bochs that is in the github is for newer ios version. Meanwhile as @reaowe pointed out, I am stuck with ios 9.
> 
> As of iBox v2.6.8 I tried using the ipa from this link: https://www.ipodhacks142.com/download/ibox-v2-6-8-ipa/, but it doesn't work either. I read in the github that it has been upgraded to ios 10.
> 
> Many thanks

ok then if none of those work then, I forgot that there is 2 more options for you
try [PCjs](http://pcjs.org) or try [Virtual x86](http://copy.sh/v86). those websites
countless operating systems, known as "run operating systems in your browser"
hope this helps.
