### ISSUE TITLE
UTM not able to reboot Ubuntu 20.04 and 22.04

### ISSUE THREAD

**Issue by fede-di-guardo** [utmapp/UTM#4055]
Good afternoon, I'm a university student and I have to work with Ubuntu for an exam. I encountered a strange issue: I opened UTM and start Ubuntu and it didn't work (I don't remember the error). I thought that I did something wrong so I tried to reinstall Ubuntu Server to have Ubuntu Desktop with the commands `sudo apt install tasksel` and `sudo tasksel install ubuntu-desktop`   but I can't because of this error. Can someone helped me? I tried also to uninstall and reinstall UTM, but there is always the same problem.

![1](https://user-images.githubusercontent.com/81449398/169881598-6d35acb9-de08-4f95-b813-1d358239bfee.jpeg)

P.s. The error is also with command `sudo apt update`

![2](https://user-images.githubusercontent.com/81449398/169881678-2058cb60-405c-4f6f-b4e4-05c067c5b50a.jpeg)

**Configuration**
* UTM Version: 3.2.4
* OS Version: macOS Monterey 12.4
* Intel or Apple Silicon? Apple Silicon M1 Pro

**Comment by conath** [comment]
This means your VM is not connected to the internet, which can have any of a number of reasons. Please check out the [Ubuntu install guide](https://mac.getutm.app/gallery/ubuntu-20-04#networking-is-unavailable) which includes network troubleshooting steps.

**Comment by fede-di-guardo** [comment]
@conath I followed the guide to resolve network troubleshooting, but for me is all ok! Please look at this :(

<img width="1429" alt="3" src="https://user-images.githubusercontent.com/81449398/170221007-8090fe80-5386-4086-8a47-406372f4efe0.png">

<img width="1429" alt="4" src="https://user-images.githubusercontent.com/81449398/170221051-c66c4fa0-9df5-4c95-9597-71cca7df2057.png">

**Comment by buluma** [comment]
Been struggling with this as well till i came across a simple hack. Simply modify resolv.conf nameserver to a working one. 
Manually set the following name servers in the /etc/resolv.conf file, so that you access the FQDMs of Ubuntu repository servers on the internet.

Add to /etc/resolv.conf:
nameserver 8.8.4.4
nameserver 8.8.8.8

Also consider applying [permanent changes](https://www.tecmint.com/set-permanent-dns-nameservers-in-ubuntu-debian/)

**Comment by fede-di-guardo** [comment]
> Been struggling with this as well till i came across a simple hack. Simply modify resolv.conf nameserver to a working one. Manually set the following name servers in the /etc/resolv.conf file, so that you access the FQDMs of Ubuntu repository servers on the internet.
> 
> Add to /etc/resolv.conf: nameserver 8.8.4.4 nameserver 8.8.8.8
> 
> Also consider applying [permanent changes](https://www.tecmint.com/set-permanent-dns-nameservers-in-ubuntu-debian/)

It works now!!! Thank you so much!
