### ISSUE TITLE
Pink screen of death when starting ESXi via emulation

### ISSUE THREAD

**Issue by d3adwolf** [utmapp/UTM#4056]
I know exactly what can be raised on QEMU under Arm VMware ESXi through emulation of CPU Westmere based on Q35, but people write that it is necessary to disable the arguments `ignore_msrs` and `report_ignored_msrs,` but I do not know where to find them in UTM, because if you install separately QEMU, they will be located at: `/sys/module/kvm/parameters/` and `/etc/modprobe.d/kvm.conf`.

**Configuration**
* UTM Version: 3.2.4 (58)
* OS Version: 12.4 (21F79)
* Apple M1

So I want to know your experience with ESXi in QEMU/UTM, you can, of course, download Arm version of ESXi, but it is more for Rasberry Pi and other such things, I want to take the basic to be a home lab for virtualization.

Below I will also stick a screenshot of the pink screen in ESXi, maybe someone can figure it out, because I did not google it. :(
![alt text](https://i.imgur.com/CYs9I08.png)

**Comment by agraf** [comment]
You're trying to run ESXi for x86_64 on an M1. That means every instruction is going through (relatively slow) binary translation. Even if you manage to get that setup working, you won't get happy with it: It will be too slow to be usable.

The ARM port of ESXi also won't work because M1 does not support nested virtualization. Within a virtual machine on M1, you can not execute a hypervisor.

**Comment by osy** [comment]
Thanks for the explanation.

**Comment by d3adwolf** [comment]
Yes, thank you very much for the explanation.

About, ESXi for ARM - everything is clear, but about the architecture x86_64 managed to run the current version 6.5. There are not baked legacy drivers, which are available in QEMU, so it runs, the only thing I need to solve is the question with the storage, the installation does not see IDE and any other virtual disks, probably again not enough ESXi drivers, I think to try to raise some standalone server in a local area with NFS/iSCSI, as file storage and it already installed ESXi, as I will successfully do this - will report! :) Thanks again.

**Comment by hronro** [comment]
@agraf What if I'm using an Intel MacBook Pro? Seems those won't be an issue on Intel chips.

**Comment by erikmartinessanches** [comment]
I was hoping to run WSL2 (to Run Docker) in a Win 11 VM on Macbook Pro M1 (using UTM). Windows says "enable nested virtualization" but M1 doesn't seem to support this, judging from the responses here?  Tough luck?

**Comment by Allen050329** [comment]
> @agraf What if I'm using an Intel MacBook Pro? Seems those won't be an issue on Intel chips.

Yeah, same for AMD hacks, tbh

**Comment by willie** [comment]
> I was hoping to run WSL2 (to run Docker) inside a Win 11 arm VM on Macbook Pro M1 (using UTM). Windows says "enable nested virtualization" but M1 doesn't seem to support this, judging from the responses here? Tough luck?
> 
> Is it possible to enable virtualization inside Windows 11 arm guest?

I came here looking for this as well.

**Comment by AdityaKoranga** [comment]
Can some one give me one word conclusion for this- Can we run docker desktop on a win 11 VM created using UTM on top of mac m1?
Thanks

**Comment by agraf** [comment]
@AdityaKoranga 

> Can some one give me one word conclusion for this- Can we run docker desktop on a win 11 VM created using UTM on top of mac m1? Thanks

Not natively. You can use [Docker's remote feature](https://docs.docker.com/engine/daemon/remote-access/) to access a second Linux VM you create in parallel to your win11 VM in UTM.
