### ISSUE TITLE
feat: connect printer  

### ISSUE THREAD

**Issue by jjangga0214** [utmapp/UTM#4058]
Hi!
I run ARM Windows 11 on m1.

When I try to print some docs, a weird broken error occurs like the below screenshot. 
<img width="737" alt="스크린샷 2022-05-24 오후 3 55 55" src="https://user-images.githubusercontent.com/28584151/169967832-886179bb-2b33-4bbb-a3ad-19463532f94b.png">

Does utm not support connecting to a printer?

At least, an option like exporting as a pdf file to macOS would be plausible, IMHO.

Thanks.

**Comment by conath** [comment]
Would you like to use a printer that currently works with your Mac, or are you trying to connect a printer to the VM via the USB sharing feature?

**Comment by conath** [comment]
This would appear to be an issue with the specific program you installed, then.
