### ISSUE TITLE
resource fork, Finder information, or similar detritus not allowed

### ISSUE THREAD

**Issue by smattar2020** [utmapp/UTM#4059]
When I try to build UTM unsigned with 
`./scripts/package_mac.sh unsigned UTM.xcarchive utmoutput`
I get the error on several files: 

```
/tmp/UTM.xcarchive/Products/Applications/UTM.app/Contents/Frameworks/gstvideo-1.0.0.framework: replacing existing signature
/tmp/UTM.xcarchive/Products/Applications/UTM.app/Contents/Frameworks/gstvideo-1.0.0.framework: resource fork, Finder information, or similar detritus not allowed
```

How can I build UTM unsigned?

**Comment by osy** [comment]
No, you need to run it on the directory where you intend to output the package to.

**Comment by smattar2020** [comment]
I don't get any output for running it on the output directory.

**Comment by smattar2020** [comment]
Now it worked but I can't start a VM
