### ISSUE TITLE
UTM does not load

### ISSUE THREAD

**Issue by SemmieboyYT** [utmapp/UTM#406]
**Describe the bug**
UTM worked fine for me, until I opened the app again and it just gave me a white screen. I don't know how this could have happened, because I didn't mess with the app. I also could not find any crash reports. The best thing I have is this screenshot:
![IMG_3910 1](https://user-images.githubusercontent.com/58337334/86222457-8cc5b380-bb86-11ea-9c6f-ec411b41ea21.PNG)

You can always ask me for more information, and I know this would be really hard to fix because I can't find any information.
(That green part on the screenshot is my battery symbol)

**Comment by jankais3r** [comment]
This is what happens when you force-quit UTM from the app switcher. To exit the app properly you have to use the X button in the top left corner. To fix this, you have ti reboot your phone.

**Comment by SemmieboyYT** [comment]
Thanks its working now!
