### ISSUE TITLE
Cannot login to apple id from system preferences > apple id

### ISSUE THREAD

**Issue by bwspot** [utmapp/UTM#4065]
Cannot login to apple id .
i get an error:

"
Verification Failed
The action could not be completed.
"

* UTM Version: Version 3.2.3 (57)
* HOST OS Version: 12.4
* Guest os: 12.2.1 created using UniversalMac_12.2.1_21D62_Restore.ipsw
* Intel or Apple Silicon?  M1 Pro

**Comment by conath** [comment]
This is a limitation of the Apple-provided backend which we have to use to provide Apple Silicon VMs. You cannot sign into iCloud or App Store inside the Mac VM. (This may change with macOS updates)

**Comment by fharper** [comment]
It may have changed, as I have the "The action could not be completeted" when trying to sign in in the App Store on Ventura 13.3.1.
