### ISSUE TITLE
Cannot connect USB and Internet at the same time

### ISSUE THREAD

**Issue by polatztrk** [utmapp/UTM#4066]
I am trying to connect my ESP32 board to the my ubuntu virtual machine but when USB support is USB 2.0 i cannot see my device on ubuntu and when USB support is USB 3.0 then i can see my device but my internet connection lost.

* UTM Version: 3.1.5 (53)
* OS Version: 12.0.1
* Apple Silicon

**Comment by conath** [comment]
Which part loses Internet, your VM or the host? Please add the configuration of your VM (config.plist file).
