### ISSUE TITLE
Windows 10 stuck on "Just a moment..." loop.

### ISSUE THREAD

**Issue by xXBannedXx** [utmapp/UTM#407]
**Describe the bug**
A clear and concise description of what the bug is. **BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**To Reproduce**
1. Install on an iPhone XS with ios 13.5 fakesigned with unc0ver jb.
2. Create a new VM with 1024mb of ram, 2 cores, microsoft windows 10 iso, and a 50gb virtual harddisk.
3. Start the VM, and install windows.
4. At here you will be stuck on the "Just a moment..." screen, Until you get to a screen that says "Why did my PC restart? There's a problem that's keeping us from getting your PC ready to use, but we think an update will get things working again. Here's how to get the update, 1. Make sure your PC is plugged in. 2. If your PC uses wifi, select next and follow the instructions to connect it to a wifi network. 3. If this PC does not use wifi insert a network cable to connect to a wired network and select Next. 4. Once your connected, select Next, and the update will install."
5. Select next, and it will get stuck on "Just a moment..." again, and it will go back to the screen described in step 4. 

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here.

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the bottom of the configuration options is `Debug Log`. Turn it on and save the VM. After you experience the issue, quit the VM and re-launch UTM. Open the VM settings again and select `Export Log...` and attach it here.
[debug.log](https://github.com/utmapp/UTM/files/4858849/debug.log)

**Upload VM**
If possible, upload the `.utm` you are experiencing an issue with. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.
https://mega.nz/folder/hHwHUDbS#kBdzof5v_8ay1lXPYeuZHg

**Comment by IIWare** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is. **BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Install on an iPhone XS with ios 13.5 fakesigned with unc0ver jb.
> 2. Create a new VM with 1024mb of ram, 2 cores, microsoft windows 10 iso, and a 50gb virtual harddisk.
> 3. Start the VM, and install windows.
> 4. At here you will be stuck on the "Just a moment..." screen, Until you get to a screen that says "Why did my PC restart? There's a problem that's keeping us from getting your PC ready to use, but we think an update will get things working again. Here's how to get the update, 1. Make sure your PC is plugged in. 2. If your PC uses wifi, select next and follow the instructions to connect it to a wifi network. 3. If this PC does not use wifi insert a network cable to connect to a wired network and select Next. 4. Once your connected, select Next, and the update will install."
> 5. Select next, and it will get stuck on "Just a moment..." again, and it will go back to the screen described in step 4.
> 
> **Crash log**
> If the app crashed, you need a crash log. To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here.
> 
> **Debug log**
> For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the bottom of the configuration options is `Debug Log`. Turn it on and save the VM. After you experience the issue, quit the VM and re-launch UTM. Open the VM settings again and select `Export Log...` and attach it here.
> [debug.log](https://github.com/utmapp/UTM/files/4858849/debug.log)
> 
> **Upload VM**
> If possible, upload the `.utm` you are experiencing an issue with. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.
> https://mega.nz/folder/hHwHUDbS#kBdzof5v_8ay1lXPYeuZHg

try this:
Step 1. Create A windows 10 vm in virtualbox on PC or mac
step 1.1. Name the vm "windows 10"
step 1.2. if you are going to install windows 10 32-bit, use Atleast 1 GB of ram or the 64 bit use atleast 2 GB of ram.
step 1.3. select Create new Hard disk
step 1.4. Set the hd size to 32 gigs or if not, use 24 gigs.
step 1.5. select VDI option
step 1.6. click on Create
step 2. power on the VM
step 3. Install Windows 10 like you normally do and finish the entire setup till when it shows you the desktop
step 4. power off the VM
step 5. copy the hard disk file to your iPhone XS
step 6. go to UTM app and change the hard disk image to the hard disk file you've copied in the last step.
step 7. Boot up the VM in UTM app
I hope it helps!

**Comment by xXBannedXx** [comment]
I got the error "not a bootable disk".

**Comment by xXBannedXx** [comment]
Edited: Ignore what I said, it works fine, safari just tries to block the vdi download.

**Comment by xXBannedXx** [comment]
A small bug is that even if I create a new hda.img and attach it to the VM, it is unable to save snapshots to it.

**Comment by IIWare** [comment]
> Edited: Ignore what I said, it works fine, safari just tries to block the vdi download.

then use chrome, and if that browser doesn't work, use other iOS browsers in your iPhone XS Max

**Comment by xXBannedXx** [comment]
yea that's what I did, Also I tried converting the .vdi to the raw format(.img) using clone, but I still can't save snapshots.

**Comment by IIWare** [comment]
wait I think I will make a download link for Win10.utm file
Download Link: _testing the VM..._
