### ISSUE TITLE
Add support for raw image files

### ISSUE THREAD

**Issue by 33blocks** [utmapp/UTM#4075]
Add support for raw image files or .img  to be able to support more operating systems

**Comment by 33blocks** [comment]
is this a qemu issue in anyway?

**Comment by osy** [comment]
It is already supported. Just import the disk image and check raw image.

**Comment by 33blocks** [comment]
ok

**Comment by WilhelmFred** [comment]
Sorry, where is this "check raw image" ?
Not visible on my screen...
<img width="640" alt="Screenshot 2022-11-02 at 14 21 26" src="https://user-images.githubusercontent.com/103637618/199500457-80741186-785e-4903-8e4c-0e32771c3d7e.png">

**Comment by JHPG** [comment]
<img width="329" alt="image" src="https://github.com/user-attachments/assets/07aab951-849c-45e9-a981-7e2c04c5ec8c">

I took a while to find it too.
