### ISSUE TITLE
Win10 still have 1ghz cpu Power

### ISSUE THREAD

**Issue by Laserfreak1337** [utmapp/UTM#4080]
i succesfully installed a Windows Machine but the cup it hold at 1 ghz and 100% full of use. How can i upgrade to 2-3GHz

**Comment by conath** [comment]
The CPU speed shown is not really what the VM runs at. You’re looking at an emulated CPU that will always run as fast as the emulator (UTM/QEMU) and the host computer (iOS device or M1 Mac, I’m guessing) can handle. 

Therefore, there is no need to change the “1 GHz” shown in Task Manager. That is not the reason why it runs slow. The emulation is very CPU-intensive and is effectively limited by your host computer’s single-threaded performance.
