### ISSUE TITLE
Shared Directory Not working for Win 7 Environment

### ISSUE THREAD

**Issue by Aliq52** [utmapp/UTM#4084]
I have installed the latest UTM 3.2.4 and have created a VM from the Win 7 image provided in the gallery. After setting up everything and installing the tools i'm still unable to see the Shared Folder on the VM.

**Comment by dayue1984** [comment]
Check if the WebClient service is enabled, then reboot your VM.

**Comment by conath** [comment]
Shared Directory feature works with all guest OS where Spice WebDAV client exists, including Windows 7. Please look elsewhere online for instructions to configure the SPICE WebDAV client.

**Comment by RobotLimeLtd** [comment]
The online instructions say:

"If Shared Directory is enabled (in Sharing settings) and the [SPICE Guest Tools](https://mac.getutm.app/support/) are installed in the guest operating system, this allows you to change the shared directory to be accessed in the guest."

source: https://mac.getutm.app/guide/#shared-directory

The OP has followed these instructions (as have I) but nothing appears in Windows 7.
