### ISSUE TITLE
How to set up bridge mode

### ISSUE THREAD

**Issue by Patr-ick** [utmapp/UTM#4085]
Hey, how would I need to configure the bridge mode to connect to my vaccum cleaner/robot?
I've used Parallels Desktop before and it was just straigt-forward by selecting Wifi Adapter via "Bridged: Wifi".

Now with UTM Virtual Machine and Ubuntu 22.04, I can't get the bridge mode set up correctly to connect/ping my vacuum cleaner when I connect my Macbook with the robot's Wifi. Keeps receiving "Host unreachable".

What are the correct bridge settings here?
Bridge Interface, Emulated Network Card and MAC Adress?

* UTM Version: latest
* OS Version: Apple Silicon/M1

**Comment by freebrowser1** [comment]
Rather simple. Go to the UTM manager and select your VM and click on 'Settings'. Go to Network and select in modes 'Bridged', default it is set to 'Shared network' which cannot find other devices in your LAN.
When 'Bridged' it can connect to other devices.

<img width="1030" alt="Screenshot 2022-06-11 at 22 21 31" src="https://user-images.githubusercontent.com/26625141/173203759-77359cba-d5e1-4d00-8238-51bf7167e599.png">

**Comment by Patr-ick** [comment]
Jup, I am aware of that and that was not really the question, which is the correct network card to emulate for the Macbook's Wifi? Can't get it running.

This is what I receive directly from my Macbook when I do `ping 192.168.8.1`
```
patrick@MacBook-Pro ~ % ping 192.168.8.1
PING 192.168.8.1 (192.168.8.1): 56 data bytes
64 bytes from 192.168.8.1: icmp_seq=0 ttl=64 time=17.440 ms
```
this is out of the UTM VM:
```
patrick@ubuntu:~$ ping 192.168.8.1
PING 192.168.8.1 (192.168.8.1) 56(84) bytes of data.
From 192.168.10.40 icmp_seq=1 Destination Host Unreachable
```
So bridged seems not to work.

**Comment by freebrowser1** [comment]
What is the address of you Macbook ? It should be 192.168.8.XXX and the address of your device should also start with the same prefix: 192.168.8.YYY. 
And the router (which determines the IP addresses) should also have an address like 192.168.8.ZZZ.
And this cannot be reached from an address like 192.168.10.x as it is a different subnet. This has nothing to do with network virtualization.

**Comment by imclint21** [comment]
I would like to create a bridge and redirect all traffic of this bridge through Tor, and then use it in UTM, does seems possible to you?

**Comment by theMyth721** [comment]
There is no Manager on my app

**Comment by q316077570** [comment]
Is there no Android UTM?



---- Replied Message ----
| From | ***@***.***> |
| Date | 01/01/2024 02:56 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [utmapp/UTM] How to set up bridge mode (Issue #4085) |

There is no Manager on my app
