### ISSUE TITLE
How to solve this please

### ISSUE THREAD

**Issue by easonEH** [utmapp/UTM#4086]
![截圖 2022-06-02 上午10 57 05](https://user-images.githubusercontent.com/106719137/171543465-7d89ad5b-3a9d-46f4-b701-a0fddd03c11c.png)

**Comment by conath** [comment]
It looks like your VM does not recognize the contents of the hard drive as bootable EFI OS. Check out the links in [this discussion](https://github.com/utmapp/UTM/discussions/4122) for steps to install Windows in UTM.
