### ISSUE TITLE
Do you plan to add something like Coherence/Unity/Seamless mode?

### ISSUE THREAD

**Issue by vadimszzz** [utmapp/UTM#4095]
I'm looking for the solution to run linux GUI applications seamlessly but Parallels, VMWare and VB they are all removed the ability to do this and now they support only Windows.
It would be awesome if you do it, especially for linux guests, very great app! Thank you!

**Comment by vadimszzz** [comment]
Found this discussion https://discourse.ubuntu.com/t/seamless-linux-gui-app-support-on-macos-using-mir/22341

**Comment by osy** [comment]
I don’t think this is possible on a sandboxed app. Even if it is, the amount of work here (drivers, etc) is astronomical and is only possible if funded by a billion dollar company.

**Comment by upintheairsheep** [comment]
> I don’t think this is possible on a sandboxed app. Even if it is, the amount of work here (drivers, etc) is astronomical and is only possible if funded by a billion dollar company.

Reopen? This can be DMG exclusive.

**Comment by upintheairsheep** [comment]
> I don’t think this is possible on a sandboxed app. Even if it is, the amount of work here (drivers, etc) is astronomical and is only possible if funded by a billion dollar company.

It can be only without sandboxing.

**Comment by upintheairsheep** [comment]
> I'm looking for the solution to run linux GUI applications seamlessly but Parallels, VMWare and VB they are all removed the ability to do this and now they support only Windows.
> It would be awesome if you do it, especially for linux guests, very great app! Thank you!

For Windows, use Wine on macOS, then you get convergence but if it’s not supported on wine you can’t
