### ISSUE TITLE
No option for enabling nested virtualization (VT-x/AMD-v)

### ISSUE THREAD

**Issue by almeyras** [utmapp/UTM#4098]
**Describe the issue**
Hello, I can't find any option for enabling nested virtualization (VT-x/AMD-v). Does this feature exist in UTM? Or in bare QEMU? Thank you.

**Configuration**
* UTM Version: 3.2.4 (58)
* OS Version: 12.4
* Intel

**Comment by osy** [comment]
Duplicate of #4056

**Comment by ohioohio** [comment]
did you find the fix?
