### ISSUE TITLE
Internal Virtualization error when creating macOS 13 beta VM

### ISSUE THREAD

**Issue by kjy5** [utmapp/UTM#4099]
Failed to install macOS 13 beta using IPSW file.

Steps to reproduce:
1. Get IPSW file from [Apple Developer](https://developer.apple.com) website
2. Create new virtualization set to macOS 12+
3. Select IPSW file
4. Set RAM (I used 16 GB) and set CPU (I get the same error regardless if I leave this as "default" or I set it to a specific number)
5. Accept everything else and run
6. Click OK to erase the disk and install macOS
7. After some loading, UTM shows the error that an "Internal Virtualization error" has occurred and the "Installation failed"
8. Clicking OK exits the VM but the process wheel is still spinning, even if you try stopping it. Only stops after quitting UTM.
9. If you try rebooting into the VM, a black screen appears and it uses 100% of one core's utilization. But nothing happens after this for a while.

**Configuration**
* UTM Version: 3.2.4 (58)
* OS Version: macOS 12.4
* Apple Silicon (M1 Max)

**Comment by vitorgalvao** [comment]
I can reproduce. For reference, [it also fails in `tart`](https://github.com/cirruslabs/tart/issues/118).

**Comment by tngranados** [comment]
It worked for me, only difference in my settings is that I used 32GB of RAM. Also on a M1 Max (64GB).

**Comment by tngranados** [comment]
I'm not sure if that's the RAM is the problem, 16GB should be enough 🤔

**Comment by kjy5** [comment]
Did you do anything different in your setup?

**Comment by tngranados** [comment]
> I figured as much... Did you do anything different in your setup?

Everything is the same but the RAM. Same host, same UTM version, same steps. I just installed UTM for the first time so everything is in its default configuration, maybe it's related to that.

**Comment by kjy5** [comment]
Interesting, maybe I'll try doing a clean install of UTM

**Comment by fkorotkov** [comment]
@tngranados do you have Xcode 14 Beta installed by any chance?

**Comment by tngranados** [comment]
> @tngranados do you have Xcode 14 Beta installed by any chance? 

I do indeed, could it be related?

**Comment by fkorotkov** [comment]
This is my running theory that Xcode 14 Beta installs some stuff that affects `VZMacOSInstaller`. :shrug`

**Comment by kjy5** [comment]
That seems reasonable, I will try that out too

**Comment by pointum** [comment]
Looks like running Xcode 14 beta solved the issue for me. Thanks, @fkorotkov 

Here's some relevant diagnostic info from Virtualization log files (from when it did not work, before I launched Xcode 14):

> [18:52:05.9477] restore failed with CFError:
> [18:52:05.9477] 0: AMRestoreErrorDomain/a: **This host version is unsupported. You may need to update your host tools.**
> [18:52:05.9484] [01:52:05.0751-GMT]{4>7} CHECKPOINT END: RESTORED:[0x0648] cleanup_send_final_status
> [18:52:05.9485] restore-step-ids = {0x11030655:14}
> [18:52:05.9493] restore-step-names = {0x11030655:is_host_compatible}
> [18:52:05.9494] restore-step-uptime = 17
> [18:52:05.9500] restore-step-user-progress = 0

**Comment by kjy5** [comment]
That seems to be the problem, the Xcode tools just needed to be updated!

**Comment by osy** [comment]
Re-opening for visibility.

**Comment by kFYatek** [comment]
Just so everybody knows: there's also a simple workaround of installing Monterey and upgrading it to Ventura.

Apparently the VM's disk image needs to be at least 256 GB for this to work, though, otherwise the "Failed to personalize software update" error will occur during the upgrade.

**Comment by lukele** [comment]
@kFYatek if the disk size is a limiting factor that would be specific to UTM not Apple's Virtualization.framework, since I managed to upgrade from Monterey to Ventura just fine with a 60GB disk.

**Comment by steven-michaud** [comment]
> That seems to be the problem, the Xcode tools just needed to be updated!

Updating the XCode command line tools to version 14 beta isn't enough by itself. You also have to install the XCode 14 beta and run it once (to make it install additional things). I tested on macOS 12.4, using UTM 3.2.4.

I still also have XCode 13 installed, and still have `xcode-select -p` set to it.

**Comment by jteloh** [comment]
> I can reproduce. For reference, it also fails in tart <https://github.com/cirruslabs/tart/issues/118>.
> 
When I use 13.0 Beta (22A5266r), the install goes fine and it opens with the beta OS.
I think interfaces have changed in the library.

**Comment by Jakobovski** [comment]
I had this issue when i gave less than 32gb of disk
