### ISSUE TITLE
Support sandbox file access for QEMU

### ISSUE THREAD

**Issue by osy86** [utmapp/UTM#410]
In order to support mounting a drive/ISO from "anywhere" we need to implement a custom QEMU block file handler that can interface with sandbox file access.

**Comment by conath** [comment]
I have implemented mounting ISO and shared folder from any location (tested with Downloads folder). 

![UTM_outside_sandbox_share](https://user-images.githubusercontent.com/12073163/98978954-fc778200-251a-11eb-8b13-e43d507e8eb5.jpeg)

![UTM_outside_sandbox_share_read](https://user-images.githubusercontent.com/12073163/98978949-fa152800-251a-11eb-9e1f-e4d545ba2929.jpeg)

See #531
