### ISSUE TITLE
Running Intel Binaries in Linux VMs with Rosetta

### ISSUE THREAD

**Issue by misuzu** [utmapp/UTM#4100]
Is it possible to integrate this into UTM? https://developer.apple.com/documentation/virtualization/running_intel_binaries_in_linux_vms_with_rosetta

**Comment by osy** [comment]
Yes there will likely be a new option toggle.

**Comment by merchantzain** [comment]
Is there an estimate to when this feature will be integrated, or the priority it has?

**Comment by osy** [comment]
@merchantzain It isn't too difficult to implement as the work is already done by Apple. However, right now priority is given to v3.3 release (https://github.com/utmapp/UTM/milestone/26) which already has features planned out. macOS 13 is still in very early beta and 99% of people are not running it so I see no need to prioritize the feature at this point.

**Comment by bpg0x03** [comment]
I'm looking to have a crack at this. In newer macOS you don't need to provide the kernel/initrd either, works with just an ISO! Will submit a PR.

**Comment by paisuhas** [comment]
@bpg0x03 could you point out the documentation where it says you don't need kernel/initrd for newer macOS?

**Comment by 12101111** [comment]
> @bpg0x03 could you point out the documentation where it says you don't need kernel/initrd for newer macOS?

https://developer.apple.com/documentation/virtualization/running_gui_linux_in_a_virtual_machine_on_a_mac

**Comment by tdeverx** [comment]
This is an interesting idea if you bring in the possibility of installing SteamOS3..

**Comment by digaus** [comment]
Currently I am emulating x86_64 version of RaspberryMatic (from .ova import) on my M1 Mac Mini since RaspberryMatic aarch64 still requires 32bit binaries. So I can only emulate it currently.

Would this change allow me to run the x86_64 docker version of RaspberryMatic inside a an arm64 Linux VM with better performance because of Rosetta 2?
