### ISSUE TITLE
Support sandbox file access for SPICE

### ISSUE THREAD

**Issue by osy86** [utmapp/UTM#411]
To support shared directory "anywhere" we have to implement custom access handlers in SPICE.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
OK！The <img src="https://files.catbox.moe/52hlp6.jpeg"> icon is the icon of icloud and other spice storage device. And in the system identify as hot pluggable local storage device.

**Comment by cs-sugar** [comment]
If you can't see this icon, the address of the icon is: https://files.catbox.moe/52hlp6.jpeg

**Comment by cs-sugar** [comment]
If you can't see this icon, the address of the icon is: https://files.catbox.moe/52hlp6.jpeg

**Comment by cs-sugar** [comment]
If you can't see this icon, the address of the icon is: https://files.catbox.moe/52hlp6.jpeg

**Comment by cs-sugar** [comment]
If you can't see this icon, the address of the icon is: https://files.catbox.moe/52hlp6.jpeg

**Comment by cs-sugar** [comment]
If you can't see this icon, the address of the icon is: https://files.catbox.moe/52hlp6.jpeg

**Comment by cs-sugar** [comment]
If you can't see this icon, the address of the icon is: https://files.catbox.moe/52hlp6.jpeg

**Comment by cs-sugar** [comment]
If you can't see this icon, the address of the icon is: https://files.catbox.moe/52hlp6.jpeg

**Comment by cs-sugar** [comment]
If you can't see this icon, the address of the icon is: https://files.catbox.moe/52hlp6.jpeg

**Comment by saagarjha** [comment]
Is it just me or did anyone else get 28 emails from this

**Comment by osy86** [comment]
Yup. Poster above edited 28 times. Wish github had some way to filter that out.

**Comment by saagarjha** [comment]
Edits don't send emails I think, perhaps @cs-sugar commented and deleted it repeatedly? In any case, please just edit it if you need to change anything…

**Comment by cs-sugar** [comment]
> Yup. Poster above edited 28 times. Wish github had some way to filter that out.

I'm sorry, at that time, there were some problems with my network. I sent a message. I found 28 of them, and then deleted them, leaving only one. Please forgive me.

**Comment by osy86** [comment]
Implemented in 689c9e8f2b40a04269255657a37b43874b735638
