### ISSUE TITLE
mac os 13

### ISSUE THREAD

**Issue by Yash11097** [utmapp/UTM#4116]
im using a m1 mac and my vm wont open on mac os 13 beta
because of some network issue

**Comment by conath** [comment]
Please add the information requested in the New Issue template.

Especially, please provide the debug log and system log. See the [troubleshooting page](https://github.com/utmapp/UTM/wiki/Troubleshooting-a-VM) for details.

Note that if you’re trying to run UTM on a macOS beta version, it might not be possible for UTM to be updated to fix this until the macOS beta reaches GM status.
