### ISSUE TITLE
Suggestion: Use SDL for video output

### ISSUE THREAD

**Issue by brad-x** [utmapp/UTM#4132]
This is a tall order considering the rework implied, but:

I see that UTM uses SPICE to connect to the backend QEMU instance, performance is quite a bit lower than running QEMU by itself using the cocoa or SDL frontends and displaying the virtual machine's graphics through that - 2D performance is considerably higher using these.

It's likely the cocoa frontend for QEMU can't be consumed in its current form, but perhaps the SDL frontend could be?

**Comment by osy** [comment]
> performance is quite a bit lower than running QEMU by itself using the cocoa or SDL frontends and displaying the virtual machine's graphics through that - 2D performance is considerably higher using these.

do you have any empirical evidence for this?

**Comment by brad-x** [comment]
.
> 
> do you have any empirical evidence for this?

I believe that's able to be produced yes - I'll work on adding to this issue today. This has been the case with QEMU+SPICE generally (using virt-viewer etc against a QEMU instance can produce similar results) and is definitely not unique to UTM (which is amazing all things considered).

This may become moot as well once Ventura's virtualization.framework introduces a virtio console - this got a passing mention in a WWDC developer session.

**Comment by brad-x** [comment]
Actually there are a couple of reasons we should just close this: 

- I had been overprovisioning CPU in the VM(s) I've been testing and then testing graphics performance under load (super basic mistake here)
  - Not a fair test as guest/host socket communication and rendering were getting choked on a not-high-end MacBook Pro
- Enabling VirGL in a guest eliminates any notable lag, probably much more worthwhile to aim for that
- Ventura Virtualization.framework enabling virtio-gpu is also really interesting
- Wrapping the Cocoa or SDL QEMU frontend is only fruitful for macOS and doesn't do anything for iOS/iPadOS


Sorry for the noise, closing
