### ISSUE TITLE
Support virtio-balloon 

### ISSUE THREAD

**Issue by Pusnow** [utmapp/UTM#4136]
QEMU device `virtio-balloon` allows [memory ballooning](https://en.wikipedia.org/wiki/Memory_ballooning) which is useful for memory constrained environment.

I think it should be nice to add an option for memory ballooning. In QEMU, adding `-device virtio-balloon` enables memory ballooning.

**Comment by osy** [comment]
The feature has been added in v4.0.

**Comment by Atemu** [comment]
How does one use the balloon? I can enable it and the guest sees the PCI device but it doesn't seem to do anything?

I've tried adding `-m size=1G,maxmem=8G` but it doesn't grow past 1G.

**Comment by osy** [comment]
Please do not comment on closed issues as nobody will see it. Try posting a question in the Q&A section of the discussion tab.
