### ISSUE TITLE
Running VMs on unsigned UTM

### ISSUE THREAD

**Issue by 3DCoded** [utmapp/UTM#4139]
When I try to run UTM from Xcode, I cannot start a VM. When I use the instructions to build it unsigned, I still cannot start a VM. How can I start a VM while developing UTM?

**Comment by ktprograms** [comment]
Is there any error shown?

FYI only Emulated VLAN networking will work with an unsigned build.

**Comment by smattar2020** [comment]
Something about permissions error

**Comment by ktprograms** [comment]
Can you send a screenshot?

**Comment by smattar2020** [comment]
<img width="271" alt="Screen Shot 2022-06-17 at 9 33 08 AM" src="https://user-images.githubusercontent.com/69043333/174308602-ff4de476-6f41-4e1c-b7a1-e23ca0b9688b.png">

**Comment by ktprograms** [comment]
On Fri Jun 17, 2022 at 9:33 PM +08, Sandra Mattar wrote:
> <img width="271" alt="Screen Shot 2022-06-17 at 9 33 08 AM" src="https://user-images.githubusercontent.com/69043333/174308602-ff4de476-6f41-4e1c-b7a1-e23ca0b9688b.png">

Yes, that means the VM is using either Shared or Bridged networking.
Change it to Emulated VLAN in the VM settings.

**Comment by smattar2020** [comment]
OK. Now I get
<img width="271" alt="Screen Shot 2022-06-17 at 9 35 46 AM" src="https://user-images.githubusercontent.com/69043333/174309131-ea5aeaef-0302-4ed0-8bbf-ba712c7096e1.png">

**Comment by ktprograms** [comment]
Do you have a VM running with UTM already? If not, go to Activity
Monitor and kill all the "QEMU Helper" and "QEMU Launcher" processes.

**Comment by smattar2020** [comment]
No. It works fine in the versions of UTM I download from the Releases page, but not when I build it myself.

**Comment by smattar2020** [comment]
I am using Emulated VLAN now. It still doesn't work.

**Comment by ktprograms** [comment]
If you're still having the error in your second screenshot, then try
rebooting your Mac (so the QEMU processes using that port won't be
running)

**Comment by smattar2020** [comment]
I rebooted my Mac and now I ge
<img width="270" alt="Screen Shot 2022-06-17 at 10 16 56 AM" src="https://user-images.githubusercontent.com/69043333/174316374-b1184911-7b77-4abb-a913-f6266e54f349.png">
t

**Comment by smattar2020** [comment]
Is there a way to completely turn off SPICE?

**Comment by conath** [comment]
Worth noting that on maOS, UTM needs the hypervisor entitlement to run VMs in virtualization mode. See [development docs](https://github.com/utmapp/UTM/blob/master/Documentation/MacDevelopment.md).

**Comment by ktprograms** [comment]
Weird, not sure what would cause that error.
