### ISSUE TITLE
Seems to be missing functionality to use arrow keys on keyboard

### ISSUE THREAD

**Issue by florisdipt** [utmapp/UTM#414]
Hey all, great work you've all put in. The emulation is working great for me.
I have a Linux based guest OS that only has CLI and I'm running into a problem.
I'm thinking it could be a oversight on my part but I read the guide and tried different things.
I cannot seem to be able to move my (text) cursor in my CLI a char forwards, backwards or line up or down.
I tried enabling scrolling to no avail. 
Also I want to make sure to mention I'm using the (default)on screen keyboard not a external one.
I'm running Arch Linux Server LTS on a iPhone SE (2020) on iOS 13.5 
If you all could either point me in the right direction or acknowledge this is a issue that'd be great. 

Thanks!

**Comment by osy** [comment]
I believe this should be fixed but if it's still broken please open a new issue with the requested information in the template.
