### ISSUE TITLE
How to change language setting in UTM vertual machine?

### ISSUE THREAD

**Issue by jnymrks** [utmapp/UTM#4140]
I want to know how to change the language setting in UTM. 
After downloading the app, I opened it and what I saw was just some Chinese letters and some icons.
I do not know Chinese well so I need to change it to English version.

If anyone know how to change them or anyone has the same issue, please let me know.

* UTM Version: 3.2.4
* OS Version: macOS Monterey 12.3.1
* Intel or Apple Silicon? Apple Silicon
<img width="896" alt="スクリーンショット 2022-06-18 0 09 45" src="https://user-images.githubusercontent.com/103639022/174326153-1a538a28-d3c2-459f-ba4e-01547b1e7c21.png">

**Comment by conath** [comment]
Can you take a look at the fix suggested in #3740 please?

**Comment by jnymrks** [comment]
Issue solved!! 
Thank you so much.
