### ISSUE TITLE
Operation not permitted error when starting VM

### ISSUE THREAD

**Issue by astronaut125** [utmapp/UTM#4144]
**Describe the issue**
UTM does not let me buy the VM because I don't have permission to a folder but I'm the administrator of the Mac so I should have permission. Alert I'm getting: qemu-x86_64-softmmu: -drive if=pflash,unit=1,file=/Users/juancruz/Downloads/Windows 7.utm/Images/efi_vars.fd: Could not open '/Users/juancruz/Downloads/Windows 7.utm/Images/efi_vars.fd': Operation not permitted It says the same thing for Windows XP
**Configuration**
* UTM Version: Latest one 
* OS Version: Mac OS Ventura Beta 1
*  Apple Silicon

**Comment by conath** [comment]
How did you get the VM into the Downloads folder? Did you move it with the UTM Move feature or did you download it and open in UTM?

**Comment by astronaut125** [comment]
Downloaded it then opened it in UTM

**Comment by conath** [comment]
Please try this:

1. Open UTM and select the VM that has this issue
2. Right-click (two finger tap on trackpad) and choose Clone
3. Click Yes
4. Start the newly created, clone VM. Note it does not have the arrow on its icon:
<img width="130" alt="Screen Shot 2022-06-20 at 23 51 29" src="https://user-images.githubusercontent.com/12073163/174682024-17e9df57-4684-4bfc-b787-5ac647c2bf4f.png">

Does this work?

**Comment by lekosbelas** [comment]
> Please try this:
> 
> 1. Open UTM and select the VM that has this issue
> 2. Right-click (two finger tap on trackpad) and choose Clone
> 3. Click Yes
> 4. Start the newly created, clone VM. Note it does not have the arrow on its icon:
> 
> <img alt="Screen Shot 2022-06-20 at 23 51 29" width="130" src="https://user-images.githubusercontent.com/12073163/174682024-17e9df57-4684-4bfc-b787-5ac647c2bf4f.png">
> 
> Does this work?

Thanks dude! You fixed my problem as well.

**Comment by minseolee** [comment]
In my case, this solution did not resolve the problem.

Reselecting the location of the .iso file worked for me.

**Comment by karatekid430** [comment]
None of these things help and it is still very broken. I even granted full disk permission to the qemu process and it still refuses.

**Comment by minseolee** [comment]
> None of these things help and it is still very broken. I even granted full disk permission to the qemu process and it still refuses.
> 
> ```
> QEMU error: QEMU salió por un error: qemu-x86_64-softmmu: -drive if=none,media=cdrom,id=driveDF63E9FB-6DC0-49F6-B396-BFB71D268E21,file=/Users/user/win98.iso,readonly=on: Could not open '/Users/user/win98.iso': Permission denied
> ```


Try this:
1. Change your location of the .iso file such as mv
2. Apply chmod 777 to the file
3. Reselect the location of the file at which you've moved

**Comment by tbagshakur** [comment]
Where you have the Shared directory, select "clear" for the second CD/DVD option. i.e. the first option would be your windows iso and the second should be empty. 
At least that worked for me. Good luck!

**Comment by lmasagao** [comment]
> Where you have the Shared directory, select "clear" for the second CD/DVD option. i.e. the first option would be your windows iso and the second should be empty. At least that worked for me. Good luck!

did work perfectly for me..
Thank You

**Comment by Congee** [comment]
trying `chmod u+rw` on that file worked for me

**Comment by dangelion** [comment]
I got this issue after moving VM to an external drive. I re-selected the location of the ISO and it worked
