### ISSUE TITLE
Virtualization is not supported on your system 

### ISSUE THREAD

**Issue by Yasry** [utmapp/UTM#4148]
![48FE1F5F-B8A4-44E6-BDD8-C625103FABB4](https://user-images.githubusercontent.com/69744917/174675130-34c7e246-41a7-42d8-88a7-ebad4fbdcc07.png)
How i fix this issue 
Iphone 13 pro max
iOS 16 beta

**Comment by conath** [comment]
See https://getutm.app/install/

**Comment by Yasry** [comment]
> See https://getutm.app/install/

I can’t understand 
I use it to install UTM but problem still
