### ISSUE TITLE
Mac on mac file sharing

### ISSUE THREAD

**Issue by ckive** [utmapp/UTM#4149]
**Describe the issue**
Installed the preconfigured macOs 12+ on a host M1 macOS 12. There was no shared folder option available from the installation. I'd assumed usb/drive pass through would be on but it doesn't seem so. How can I get files from the guest OS back out?

**Configuration**
* UTM Version: 3.1.5
* OS Version: Mac OS 12.1
* Intel or Apple Silicon? Apple

**Comment by conath** [comment]
You may use any way you would usually share files between two Macs, including the [File Sharing feature in macOS](https://support.apple.com/guide/mac-help/set-up-file-sharing-on-mac-mh17131/mac). Enable it in either the host or the guest.
