### ISSUE TITLE
Add UTM version to menu in future UTM releases.

### ISSUE THREAD

**Issue by IIWare** [utmapp/UTM#415]
So can you please add UTM version in menu because people will know what version of UTM they are using. I have provided an image below of iPhone SE to make sure it will fit in ipads/bigger iphones:
![](https://i.imgur.com/rf3WbRw.png)
Notice How I changed it from **Virtual Machines** to **VMs** to fit the version of UTM in the menu.
or if you are gonna skip v1.1 and release v2.0 here is the provided image:
![](https://i.imgur.com/C0Z8Yhr.png)
_Note: please expect me not to respond for a few hours_

**Comment by osy86** [comment]
Going to pass on this one.

**Comment by IIWare** [comment]
@osy86 I know your misunderstanding, so you think that everytime a new version of UTM is released the version in the menu updates, but it isn't that, the version in the menu is like the info of the app, for example, if you go to winver in windows 7, the winver application will always show windows 7 and not windows 10, also if you go to system info in, lets say iOS 10, the info will show iOS 10 and not iOS 14, so it's the same with the UTM app, if you released UTM v2.1 and you are in v2.0, it will always show v2.0

**Comment by reaowe** [comment]
Why not have it inside of a info button (i)? It could show information about the app etc.

**Comment by jankais3r** [comment]
UTM version is already listed at the bottom of the VM config.

![9EF3DFFE-0735-4E7C-9D18-F51A8BC81A8D](https://user-images.githubusercontent.com/2159464/87441588-89eda880-c5f3-11ea-96e0-56942d7fb0ba.jpeg)

**Comment by osy86** [comment]
Sorry I’m not going to follow Microsoft Windows for design guidance.

**Comment by IIWare** [comment]
@jankais3r thanks for telling me, I didn't see that in the config, but it might be annoying just in order to find the version you need to create a VM, but before that, @reaowe gave out a better idea, and it is to put the (i) button so here it is with the (i) button for v1.1:
![](https://i.imgur.com/eUDTgCM.png)
or here it is in v2.0:
![](https://i.imgur.com/7c2EuxZ.png)
it will show the about page of UTM, so I will design the about page, this may take a while since I am not that good at editing.

**Comment by osy86** [comment]
There is no reason for the end user to care about the version number. What version of safari are you using? What version of of discord? Imo the only place you need to know the version is in debug and crash logs.

And yes, I think lowly of any app that prominently displays the version number.

**Comment by IIWare** [comment]
@osy86 you need version number (and not only version number, all UTM info) to make sure you are up to date, and plus I will show you the about page of UTM when the (i) button is clicked, this may take a while for me to edit.

**Comment by osy86** [comment]
Locking the thread because I don’t see anything productive will come out of it. It’s a matter of taste and I’m making the executive decision to not follow design techniques from Microsoft Windows.
