### ISSUE TITLE
utm://downloadVM does not work with space characters (%20)

### ISSUE THREAD

**Issue by BluDood** [utmapp/UTM#4155]
**Describe the issue**

If the `utm://downloadVM` URL scheme is supplied with a URL that has a space character (%20), UTM fails to download and gives an error saying "Failed to parse download URL". Using the same URL without a %20 character, UTM downloads the VM as expected. Is this intended behavior?

**Configuration**
* UTM Version: 3.2.4
* OS Version: Monterey 12.4
* Intel or Apple Silicon? Intel

**Comment by BluDood** [comment]
Happens on iOS too. IOS 16, UTM SE 3.2.4
![](https://i.imgur.com/7L237OZ.mp4) https://imgur.com/7L237O.mp4

**Comment by conath** [comment]
You didn't give the example that fails, and I can't open the imgur link, so I can only guess. It seems like you are not encoding the URL string like UTM expects. The download link should be encoded so a space becomes `%2520`. For example I can download a file from the URL `https://chrisp.cafe/UTM/Intel Big Sur.utm.zip` with this link: `utm://downloadVM?url=https%3A%2F%2Fchrisp.cafe%2FUTM%2FIntel%2520Big%2520Sur.utm.zip`

The error you are seeing is triggered in this line:

https://github.com/utmapp/UTM/blob/753564cd3abc9db25fd94266781010bab6d9b5ab/Platform/UTMData.swift#L665-L672

Maybe there is [one more URL decode](https://stackoverflow.com/a/16085190) going on in the code path than one would expect?

**Comment by BluDood** [comment]
That looks to have worked! One question though, why are spaces parsed as `%2520`? The correct code would be `%20`. I'm guessing it has to decode it twice, once for the shortcut to open UTM and another to send the request.
