### ISSUE TITLE
UTM can't access drive image file from custom QEMU arguments after restarted once

### ISSUE THREAD

**Issue by tomba4** [utmapp/UTM#4158]
**Describe the issue**
I create a VM using "Do not generate any arguments based on current configuration" (since the generated options are incorrect in my case), everything works fine, I can install the guest OS, start/restart the machine, etc. Everything works until I quit UTM and start it again. When I try to run the VM then, I see "Operation not permitted" error when trying to open the qcow2 image.

**Configuration**
* UTM Version: 3.2.4
* OS Version: 12.4
* Intel or Apple Silicon? Intel

**Crash log**
N/A

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/8969856/debug.log)

**Comment by conath** [comment]
Sounds like a security-scoped resource issue... @osy ?

**Comment by osy** [comment]
Yeah, once you use the “do not generate…” feature you’re on your own. It’s not possible to determine and save bookmarks outside of the sandbox.

**Comment by tomba4** [comment]
You mean it's not possible to use disk images when using "do not generate..."?  @osy in https://github.com/utmapp/UTM/issues/4102 you wrote that "do not generate..." is the option to use when the arguments generated by UTM are not suitable. But how can it be used without referencing disk images?
