### ISSUE TITLE
Networking doesn’t work regardless of adapter

### ISSUE THREAD

**Issue by jf352** [utmapp/UTM#416]
Any virtual machine created, with any OS, doesn’t seem to be able to connect to the internet with the latest release.

Perhaps I’m missing something, or there is something wrong with my device, but browsing the issues here hasn’t seemed to resolve anything. Can’t give logs as nothing is happening in the first place.

**Comment by reaowe** [comment]
Have you tried asking in the discord server?

**Comment by jf352** [comment]
> Are you in the China region? I’ve heard some places require per app permission for network access. If that’s the case make sure you enabled the access.

Unfortunately not. I’m in Germany and my device is a UK device. Don’t see any issues with network permissions. Even the pre-made VMs on the website aren’t connecting to the internet - it’s quite peculiar.

My device is a non-jailbroken iPad Pro 2020, on iPadOS 13.5.1

**Comment by demhademha** [comment]
Have you installed it with an enterprise certificate or a developer one?

**Comment by nimalouk** [comment]
Just type a free DNS Server, for example 1.1.1.1

**Comment by jf352** [comment]
Well, this is an interesting one. I had already had a DNS server set @nimalouk , which was 1.1.1.1 and was still getting the issue.

Funnily enough, after rebooting the iPad Pro, it started working again. I guess the old adage of "turn it off and on again" really does  apply. Just wish I could figure out what the original problem was though.
