### ISSUE TITLE
Add the ability to boot into macOS recovery mode.

### ISSUE THREAD

**Issue by jawshoeadan** [utmapp/UTM#4164]
As seen in [VirtualBuddy](https://github.com/insidegui/VirtualBuddy) it is possible to do this now with the private headers, so my proposal is to add this to UTM as well.

**Comment by ideologysec** [comment]
It's explicitly supported in macOS 13 as well.

https://developer.apple.com/documentation/virtualization/vzmacosvirtualmachinestartoptions

**Comment by conath** [comment]
Duplicate of #3526
