### ISSUE TITLE
Not getting the skip option in the network connecting setup!!-

### ISSUE THREAD

**Issue by ArhamBaluch** [utmapp/UTM#4165]
I cannot setup my windows!! pls help
![Uploading Screenshot 2022-06-26 at 11.35.17 PM.png…]()

**Comment by ThatsNiceGuy** [comment]
while this is not a UTM issue, this is easily fixed.

Press Shift+F10, type `oobe\bypassnro` and hit Enter. Windows will reboot, and then you can skip network setup.

for any further windows help, I suggest you join the UTM discord at https://discord.gg/UV2RUgD
