### ISSUE TITLE
Main window's stop button doesn't stop QEMULauncher, causing data corruption if the same VM is launched again

### ISSUE THREAD

**Issue by arroz** [utmapp/UTM#4166]
**Describe the issue**
1. Configure and run a VM. 
2. In the main UTM window (not the VM window), select the running VM and click the stop button on the toolbar. Confirm you want to turn off the VM.
3. Check in the terminal the QEMULauncher is still running (by running `ps xuawww | grep QEMULauncher` for example).
4. **Warning: this step will likely corrupt your vm!** Launch the VM again.

Now you should have two QEMULauncher processes running, using the same VM image. This will corrupt the image (I've seen an instance where QEMU doesn't launch saying the image is corrupted, and another where it does, but the guest OS wont boot because the image contents corrupted).

**Configuration**
* UTM Version: 3.2.4 (58)
* OS Version: macOS 12.4
* Apple Silicon (M1, Mac Mini)
* Guest OS: FreeBSD 13.1 aarch64

**Comment by tplueer** [comment]
I have the same problem, but it also occurs when I try to stop vm directly inside the vm window. For me, the problem occurs every 3-4th time.

OS Version macOS 12.4
Apple M1 Max
Guest OS: Ubuntu 20.04 ARM64

**Comment by osy** [comment]
When you do this, do you see the progress indicator show up or does it stop "immediately"?
