### ISSUE TITLE
build input file(s) cannot be found - compiled from source 

### ISSUE THREAD

**Issue by littlejob** [utmapp/UTM#417]
downloaded source - open project in Xcode - sign with dev cert - build to iPhone - errors out indicating there are several build input files that are not found in source directory. 

`error: Build input file cannot be found: '/Users/bgodbout/Downloads/UTM-1-2.0/sysroot-arm64/qapi/qapi-builtin-visit.c' (in target 'UTM' from project 'UTM')`

the below are also listed: 
quip-visit-audio.c
qapi-visit-transaction.c
qapi-visit.c

any ideas?

**Comment by osy86** [comment]
Read the readme.
