### ISSUE TITLE
Mouse cursor capture button grayed out on macOS Ventura VM

### ISSUE THREAD

**Issue by Alex-Simedrea** [utmapp/UTM#4171]
**Describe the issue**
The 'Capture mouse cursor' button is greyed out on macOS Ventura Beta 2 VM. 

**Configuration**
* UTM Version: 3.2.4
* OS Version: macOS 12.4
* Apple M1 chip

**Upload VM**
[config.plist](https://github.com/utmapp/UTM/files/9000720/config.txt)

**Comment by osy** [comment]
There is no mouse capture feature in macOS VMs.
