### ISSUE TITLE
Stuck on windows network step

### ISSUE THREAD

**Issue by lucaspukus** [utmapp/UTM#4177]
Hi all. Im trying to install Windows 11 (Windows11_InsiderPreview_Client_ARM64_en-us_25140.VHDX) on an M1 (pro) MBP & once I get to the network step, I dont get the "I do not have internet" option. I tried with both the available windows downloads.
Can anyone help? TIA
<img width="744" alt="Screen Shot 2022-06-29 at 21 28 03" src="https://user-images.githubusercontent.com/40289017/176432356-99c22755-9a1c-45bc-95d6-b13df46281de.png">
.

**Comment by lucaspukus** [comment]
> I had the exact same issue. i followed the instructions from this website: https://pureinfotech.com/bypass-internet-connection-install-windows-11/ if you dont want to read everything here is a quick rundown:
> 
> 1. if you are at the network step, press shift+f10 (+fn if you have the default behaviour for the function keys in macos) to open the command prompt
> 2. enter this command: OOBE\BYPASSNRO (if you use a keyboard where the backslash is under a alt button combination you can press ctrl+option)
> 
> thats it. it will reboot and you can proceed in the installation process. if you get to the network step you should get the network skip button.

Worked a treat! Thanks for that. Ill leave this up for anyone else who has the same issues. Cheers

**Comment by Zebede3** [comment]
Unfortunately, I think this is no longer working. I have tested my kb to ensure I am infact hitting SHIFT-F10, but no CMD. Not sure if it has been removed :(

**Comment by phuc0903** [comment]
Hi @Zebede3 
You need to press SHIFT-F10 before that screen
I pressed in 'Select key board layout screen' and it worked.

**Comment by apanzerj** [comment]
thank you. i was losing my mind. you can hit the key combo ANY TIME BEFORE the network screen. it might reboot a few times too. then hit the "i don't have a network connection" when you go through the setup a second time.

**Comment by Zebede3** [comment]
> Hi @Zebede3 You need to press SHIFT-F10 before that screen I pressed in 'Select key board layout screen' and it worked.

You legend, thanks!

**Comment by jonx** [comment]
Totally works. As stated in the documentation here: https://mac.getutm.app/gallery/windows-11-arm

Just one tip for those with a German keyboard, note that you type the backslash character "\" with "control + option + ß" in a Windows terminal.

**Comment by novissoeeeeeeeeeeee** [comment]
does any one know how backslash is on Switzerland keyboard terminal windows

**Comment by jowillll** [comment]
> Hi @Zebede3 You need to press SHIFT-F10 before that screen I pressed in 'Select key board layout screen' and it worked.

How do I go back to the previous screen?

**Comment by israkkayum** [comment]
Hold fn + shift keys and press f10 key
then press option + tab keys

**Comment by Golonchy** [comment]
this isnt working for me, i tried holding down fn+shift+f10 for mute.
any ideas?

**Comment by jaymecd** [comment]
Fn+Shift+F10 works, focus bust be inside VM window, otherwise it's processed by host (MacOS). 

Note: for me only right-shift has worked

**Comment by fireballpoint1** [comment]
After pressing Fn+Shift+f10 i pressed CMD+R, which opened the run menu. type cmd and press enter.
then cd ../../Windows/System32/oobe Press enter
bypassnro Press enter

However, this just shows access denied and after a restart comes back to the same screen again

**Comment by TimoKruth** [comment]
> For me, the Fun+Shift+F10 action isn't working... the only thing that happens is leaving the equipment muted... Does anyone know how I can use the F10 function?

@annax11b
If fn+Shift+F10 is actually muting your system then just press Shift+F10 since your system seems to be setup to default to Function keys instead of the Extra functionalities like muting.


> After pressing Fn+Shift+f10 i pressed CMD+R, which opened the run menu. type cmd and press enter. then cd ../../Windows/System32/oobe Press enter bypassnro Press enter
> 
> However, this just shows access denied and after a restart comes back to the same screen again

I think you overcomplicated it a litte. It should be enough to write oobe\BYPASSNRO after the cmd shell opened due to pressing fn+Shift+F10. 

@novissoeeeeeeeeeeee I think it is next to the left Shift key where the <> signs are. But might be wrong: https://kbdlayout.info/KBDSG/
