### ISSUE TITLE
autostart on boot

### ISSUE THREAD

**Issue by techpro2004** [utmapp/UTM#4179]
This is an enhancement.

It would be great if there was a way to have a vm auto start on boot. Thanks.

**Comment by conath** [comment]
Here you are: https://github.com/utmapp/UTM/wiki/URL-Scheme-%E2%80%93-Automation-for-UTM-app-&-VMs#start-a-vm-automatically-when-you-log-in-macos-12-monterey

**Comment by ylluminate** [comment]
Perhaps a followup to this @conath: is it possible to also have UTM shutdown a guest vm at restart/reboot? I have, for example, a macOS `virtualization.framework` guest that I need to be sure shuts down (better would be: suspends/saves state, but I don't think this works on Apple's framework yet) properly and then starts back up when the system boots and/or user logs in...

**Comment by conath** [comment]
@ylluminate No, this is not possible, as UTM does not currently contain a "safe shutdown" feature and adding it for macOS VMs is not possible – Apple would need to add such a feature first in their backend, just like the missing suspend-to-disk feature you mentioned. You would need to use a 3rd party automation tool to trigger the VM shutdown and then the host shutdown in sequence.

**Comment by maxpavlov** [comment]
@conath is there an updated link to that wiki? The above one no longer works as it seems. Thanks.

**Comment by conath** [comment]
@maxpavlov Indeed the Wiki was removed in favor of the new documentation website. Unfortunately this section about the URL scheme automation was not copied to the [relevant chapter](https://docs.getutm.app/advanced/remote-control/) yet.
Thankfully the [wiki page is archived](https://web.archive.org/web/20220309041214/https://github.com/utmapp/UTM/wiki/URL-Scheme-%E2%80%93-Automation-for-UTM-app-&-VMs) on the Internet Archive.

**Comment by grantwest** [comment]
@conath It might make sense to implement this just for QEMU based VMs for now. And then if/when Apple adds support it can be turned on for MacOS VMs. It seems like there might not be any wasted effort implementing this now vs when Apple adds support.

**Comment by tommytran732** [comment]
I noticed a strange behavior so I'd just note it here:

Adding the shortcut to "Login Items" alone is not enough - UTM will launch but it will not start the VM. UTM also needs to be added to the list of "Login Items" for this to work properly.

**Comment by diddeb** [comment]
**Because Google brings me here, so for posterity:** I find Apple Script to be the easier (cleaner) solution. The [docs](https://docs.getutm.app/scripting/cheat-sheet/) are accurate and using Script Editor.app to create a macOS binary is trivial. In my case wanting to boot a VM on login:

```applescript
tell application "UTM"
    set vm to virtual machine named "W11"
    start vm
end tell
```

**Comment by TodayNoLunch** [comment]
> **Because Google brings me here, so for posterity:** I find Apple Script to be the easier (cleaner) solution. The [docs](https://docs.getutm.app/scripting/cheat-sheet/) are accurate and using Script Editor.app to create a macOS binary is trivial. In my case wanting to boot a VM on login:
> 
> tell application "UTM"
>     set vm to virtual machine named "W11"
>     start vm
> end tell

Thanks! It works perfectly

**Comment by devantler** [comment]
> **Because Google brings me here, so for posterity:** I find Apple Script to be the easier (cleaner) solution. The [docs](https://docs.getutm.app/scripting/cheat-sheet/) are accurate and using Script Editor.app to create a macOS binary is trivial. In my case wanting to boot a VM on login:
> 
> tell application "UTM"
>     set vm to virtual machine named "W11"
>     start vm
> end tell

For those of you wishing to auto-start **all** UTM VMs, you can use [a loop](https://alvinalexander.com/apple/applescript-for-loop-while-loop-examples/) over the listed vms, to operate on them:

```AppleScript
tell application "UTM"
	set vms to virtual machines
	repeat with vm in vms
		if status of vm is not started then start vm
		repeat
			if status of vm is started then exit repeat
		end repeat
	end repeat
end tell


```
