### ISSUE TITLE
How to press F8 when installing win xp?

### ISSUE THREAD

**Issue by armqtt** [utmapp/UTM#418]
When I am installing windows XP, there are process to agree the policy by pressing F8.

I try many manner but in vain for example, Bluetooth keyboard fn F8.

How to achieve the pressing F8 effects?

**Comment by IIWare** [comment]
@armqtt o to press f8, go to the toolbar
![](https://i.imgur.com/oXpt7Km.png)
and then click the keyboard icon and then at the top right, swipe from right to left until you see F8.
if you still have issues, either tell me the issue or click [HERE](getutm.app/faq) to go to UTM FAQ (frequently asked questions).

**Comment by obbcth** [comment]
Try this : #294

**Comment by armqtt** [comment]
it's work. Thanks all of you.

**Comment by yayicanfart** [comment]
> Try this : #294

It didnt even help

**Comment by MolypolyGuy** [comment]
yeah
it diddent work

**Comment by Metaphorme** [comment]
Still can't work! When I press F8, just open the stupid music!

**Comment by Metaphorme** [comment]
It works when I press fn+F8
