### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by MikeyBeez** [utmapp/UTM#4197]
Are there uninstall instructions?  How does one uninstall this application?  Holding down the option key in the launcher doesn't work.

**Comment by conath** [comment]
If you installed UTM from the Mac App Store, [use Launchpad to uninstall it](https://support.apple.com/en-us/HT202235#launchpad).  
If you installed UTM from the website or GitHub page, you should [use Finder to uninstall it](https://support.apple.com/en-us/HT202235#finder).  

To remove the VM files from your Mac and free up disk space, open a Finder window and click the Go menu. Hold down the option/alt ⌥ key and choose *Library*. Double-click the Containers folder and select the UTM folder in it. (full path: `~/Library/Containers/com.utmapp.UTM`) Click the File menu. Hold down option/alt ⌥ key and choose *Delete Immediately…* to permanently remove all VMs and the files and applications contained within them.
