### ISSUE TITLE
Open a TestFlight beta ?

### ISSUE THREAD

**Issue by jcampbell05** [utmapp/UTM#42]
This is how iSH distributed this :)

**Comment by ThatsNiceGuy** [comment]
pretty sure TestFlight apps need to pass App Store checks and since JIT code is not allowed for App Store apps then it’s likely not gonna be able to be on testflight

**Comment by uhlhosting** [comment]
Did someone made a all in one script to deploy the building on osx? Why isnt there a ipa made to be resigned for all who have a dev account?

**Comment by osy86** [comment]
TestFlight only allows distribution certificates and not development certificates. Distribution certificates do not have `get-task-allow` entitlement.

**Comment by mattruzzi** [comment]
Somehow someone published UTM to the iOS App Store under a different name:
https://apps.apple.com/us/app/merge-vm-pro/id1598053029

I have no idea if it works at all or if it is a complete scam but I don't want to pay $99 to find out.
