### ISSUE TITLE
Debian 10.4 osy not started completely

### ISSUE THREAD

**Issue by pehAche** [utmapp/UTM#422]
Hi,

i can't start debian (osy) VM. After the login windows, the desktop Start but stay bloqued without anything other than the background et the botom « toolbar »

I’ve launched the .utm file directly 

Sorry for vas english

Thanks for help

**Comment by osy86** [comment]
https://i3wm.org/docs/refcard.html

**Comment by pehAche** [comment]
Thanks. But wich key on the iOS keyboard correspond to the key « alt » or « windows » 

Thanks

**Comment by ThatsNiceGuy** [comment]
Command corresponds to Windows and Option corresponds to Alt. Please take further inquiries elsewhere as these are not UTM issues.
