### ISSUE TITLE
macOS 10.5 stuck on OpenBIOS

### ISSUE THREAD

**Issue by fhildfshjkdsaiojsga** [utmapp/UTM#425]
Currently, macOS 10.5 after install (yes I did follow a tutorial), it’s now on OpenBIOS and I cannot get out of it. Can somebody help me?

**Comment by Fnckerpoi** [comment]
How to run Big Sur? Arm64 OR X86?

**Comment by itselijahciali** [comment]
> How to run Big Sur? Arm64 OR X86?

We don't have the ARM binaries yet, but I'm not sure that it can be run on x86 as of now either.
