### ISSUE TITLE
UTM crashes on launch

### ISSUE THREAD

**Issue by nuwandame** [utmapp/UTM#4258]
**Describe the issue**
UTM crashes immediately upon launching the app. I have uninstalled and reinstall UTM from App Store obtaining the same results. 

**Configuration**
* UTM Version: 3.2.4 
* OS Version: 12.5
* Intel or Apple Silicon? Apple M1 Max 

**Crash log**
[UTM-2022-08-05-083141.ips.zip](https://github.com/utmapp/UTM/files/9269335/UTM-2022-08-05-083141.ips.zip)

**Debug log**
None - cannot launch UTM.

**Upload VM**
None

**Comment by osy** [comment]
One of your .utm is crashing on `migrateNetworkConfigurationIfNecessary`. How many VMs do you have? Is it possible to dump config.plist from each one and attach it so I can find which config is causing the crash?

**Comment by nuwandame** [comment]
Hmm... that makes me wonder if there was a problem with the extra network that I was attempting to add to the OPNSense VM.

Wow, thank you for your assistance. I forgot I was trying to hack an extra network in that OPNSense VM a couple of months ago (my bad here). I tried making it an array and putting multiple network devices in there:
` <key>Networking</key>
        <array>
                <dict>
                        <key>NetworkCard</key>
                        <string>e1000</string>
                        <key>NetworkCardMAC</key>
                        <string>E6:4D:1A:EB:C7:5A</string>
                        <key>NetworkMode</key>
                        <string>shared</string>
                </dict>
        </array>`

I didn't clean the array tags out and forgot until you mentioned the problem with network configuration. 

How did you know that there was a problem with networking from crash file?

I owe you a coffee or something -- thanks so much!!!
