### ISSUE TITLE
USB devices not working

### ISSUE THREAD

**Issue by osy** [utmapp/UTM#4263]

**Comment by introns-bungles** [comment]
@osy You added the label `iOS` but does this issue also apply to `macOS`? Today I upgraded macOS to `Ventura 13.0 Beta (22A5321d)` and UTM to `4.0.0-Beta` and USB redirect of my USB Bluetooth Stick stopped working. I will provide a separate issue if this is not the case.

**Comment by ktprograms** [comment]
Looking at the code I think this also applies to macOS. The fix isn't in any beta version yet.

**Comment by introns-bungles** [comment]
> The fix isn't in any beta version yet.

Do you plan on releasing a hotfix for this or bundle this patch with the next regular beta release?

**Comment by ktprograms** [comment]
I'm not the dev, that'd be up to osy to decide.

**Comment by introns-bungles** [comment]
Sure thing I hope this didn't come across as rude. Will revert back to stable in the meantime.
