### ISSUE TITLE
iPad Pro 2017 (iOS 13.6)

### ISSUE THREAD

**Issue by despot84** [utmapp/UTM#427]
The application starts only once. Further, just a white screen.
After installation, I create a VM, try to pick up an ISO image, but nothing happens

**Comment by itselijahciali** [comment]
Are you Jailbroken? Try asking questions in the official Discord before creating an issue.

**Comment by brunocastello** [comment]
@itselijahciali where is the official discord?

**Comment by WeiChei7** [comment]
Please tell me how to stop getting notified on this thread

**Comment by ThatsNiceGuy** [comment]
https://discord.gg/jhmRCAS
