### ISSUE TITLE
French localization update for v4 Beta

### ISSUE THREAD

**Issue by FRtranslator** [utmapp/UTM#4273]
Hi,

I updated the French localization for v4 beta.
I'm still a newbie and can't build the project, so I'm note sure that it works, especially since the main localization file doubled in size (don't know why). @osy , can you test with the files attached and make a feedback?
All strings should be translated.

[French localization for v4 beta.zip](https://github.com/utmapp/UTM/files/9277522/French.localization.for.v4.beta.zip)

Thanks!
Regards.

**Comment by osy** [comment]
I'm not an expert on how localization works, so there's not much feedback I can give. However, I did notice that one of your files was saved in utf-16le which I converted to utf-8.
