### ISSUE TITLE
virtual machine not starting 

### ISSUE THREAD

**Issue by meghmodi** [utmapp/UTM#4290]
error
qemu-aarch64-softmmu: -netdev vmnet-shared,id=net0: cannot create vmnet interface: conflict, sharing service is in use
[debug.log](https://github.com/utmapp/UTM/files/9329825/debug.log)

**Comment by conath** [comment]
Please disable macOS internet sharing feature before you start the VM that has shared/bridge mode network.

Duplicate of #3636
