### ISSUE TITLE
[macOS guest] Cannot transfer files from/to the VM

### ISSUE THREAD

**Issue by albertosottile** [utmapp/UTM#4291]
**Describe the issue**  
Hello, first of all thank you for this great software.

Yesterday I set up a macOS guest VM (Monterey 12.5) but I could not find a way to transfer files from the VM or into it. Copy and paste does nothing, drag and drop does not work, the shared folders icon is grayed out, and there is no support for USB devices (#3778). How can I transfer files from a macOS guest VM?

**Configuration**  
* UTM Version: 3.2.4
* Host macOS Version: 12.5
* Mac Chip (Intel, M1, ...): M2 (MacBook Air 2022)
* Guest OS: macOS 12.5

**Comment by H-G-Hristov** [comment]
A few workarounds:
- scp - https://linux.die.net/man/1/scp
- Google drive & co.

**Comment by albertosottile** [comment]
I could think of internet-based workaround but, can you confirm there is no local way for doing so?

**Comment by conath** [comment]
There will be shared folders for Apple VMs starting with the next macOS release. The backend is controlled by Apple and they do not offer a shared folders feature for now, only in the next update.

You may use SMB shares if you are willing to allow the VM in your LAN.
