### ISSUE TITLE
Problem installing new VM with UTM

### ISSUE THREAD

**Issue by Treintillin** [utmapp/UTM#4295]
Hello, I'm trying to use a different operating system with UTM but once I start it after configuration and have chosen "Graphical Install" it goes black with an underscore titling. Just that.

Does someone know why this is? I would really appreciate some help,

**Comment by vickyhck** [comment]
try this method
https://github.com/utmapp/UTM/issues/4090#issuecomment-1213306172

**Comment by Treintillin** [comment]
This was it!! Thank you so much!! I was already giving up
