### ISSUE TITLE
Unable to install UTM on jailbroken device 

### ISSUE THREAD

**Issue by zxq2233** [utmapp/UTM#43]
IOS version: 13.3 (17C54) 

My ipad has successfully jailbroken and installed appsync,
I use fiiza file manager to install ipa files. Prompt installation failed!
Does UTM not support ios13.3?

**Comment by obbcth** [comment]
Install app via Reprovision if your device is jailbroken.

**Comment by Austin76016** [comment]
I just used AltStore since that’s what I installed unc0ver with. Just open the ipa in Files after download. Click share in the top right and Open in AltStore. I believe this is due to the lack of fake signing.

**Comment by The-SamminAter** [comment]
I personally installed it by unpacking the ipa and moving UTM.app to /Applications/. After respringing, it should show up on your home screen. If it doesn’t, try running uicache

**Comment by TangMonk** [comment]
> I personally installed it by unpacking the ipa and moving UTM.app to /Applications/. After respringing, it should show up on your home screen. If it doesn’t, try running uicache

I have tried your way, but not works

**Comment by osy86** [comment]
Only the method in the README and https://getutm.app/install using a paid developer certificate is supported. Any other install methods, please ask the community.
