### ISSUE TITLE
firefox crashes in Ubuntu 22.04 arm64 guest

### ISSUE THREAD

**Issue by mikeactual** [utmapp/UTM#4300]
Here is some system information and the command line results:

michael@jammy-desk-vm:~$ neofetch && firefox --safe-mode 

OS: Ubuntu 22.04.1 LTS aarch64 
Host: QEMU Virtual Machine virt-7.0 
Kernel: 5.15.0-46-generic 
Uptime: 47 secs 
Packages: 1698 (dpkg), 9 (snap) 
Shell: bash 5.1.16 
Resolution: 2940x1840 
GPU: 00:01.0 Red Hat, Inc. Virtio GPU 
Memory: 1004MiB / 3908MiB [---============] 
GPU Driver: virtio-pci 
Local IP: 192.168.1.206 

update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/usr/share/gtk-doc /usr/share/gtk-doc none bind,ro 0 0): cannot open directory "/var/lib": permission denied
update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/usr/share/libreoffice/help /usr/share/libreoffice/help none bind,ro 0 0): cannot create directory "/usr/share/libreoffice/help": permission denied
update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/usr/share/xubuntu-docs /usr/share/xubuntu-docs none bind,ro 0 0): cannot open directory "/var/lib": permission denied
Gtk-Message: 15:16:35.291: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:16:35.295: Failed to load module "canberra-gtk-module"
[GFX1-]: glxtest: VA-API test failed: failed to initialise VAAPI connection.
ATTENTION: default value of option mesa_glthread overridden by environment.
michael@jammy-desk-vm:~$ 

I'm running UTM Version 3.2.4 (58) under macOS version 12.5 (21G72) on an M2 macbook air.

Let me know if I can provide any more info. If this is a known issue or bug from somewhere else in the stack please point me to that and I'll go sniff around there.

Regards,
mike

**Comment by mikeactual** [comment]
It looks like UTM 4.0 changes could have some effect on this issue. I'll try firefox (and vs code which also doesn't work in the 3.2.4 vm) on the pre-release. If anything interesting happens I'll report back here.

Regards,
mike

**Comment by mikeactual** [comment]
I installed UTM Version 4.0.1 (60). The release notes state that Ubuntu Server will not install under this version of the beta. I let the pre-release rip on the existing ubuntu vm. There was no appreciable difference to my eye anyway. Firefox crashes (see below) and vs code opens a completely black window.

I'm happy to try or test anything else if it'll help.

michael@jammy-desk-vm:~$ neofetch && firefox --safe-mode
michael@jammy-desk-vm 

OS: Ubuntu 22.04.1 LTS aarch64 
Host: QEMU Virtual Machine virt-7.0 
Kernel: 5.15.0-46-generic 
Uptime: 2 mins 
Packages: 1698 (dpkg), 9 (snap) 
Shell: bash 5.1.16 
Resolution: 2940x1840 
GPU: 00:01.0 Red Hat, Inc. Virtio GPU 
Memory: 892MiB / 3908MiB [---============] 
GPU Driver: virtio-pci 
Local IP: 192.168.1.206 

update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/usr/share/gtk-doc /usr/share/gtk-doc none bind,ro 0 0): cannot open directory "/var/lib": permission denied
update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/usr/share/libreoffice/help /usr/share/libreoffice/help none bind,ro 0 0): cannot create directory "/usr/share/libreoffice/help": permission denied
update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/usr/share/xubuntu-docs /usr/share/xubuntu-docs none bind,ro 0 0): cannot open directory "/var/lib": permission denied
Gtk-Message: 13:58:04.316: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:58:04.320: Failed to load module "canberra-gtk-module"
[GFX1-]: glxtest: VA-API test failed: failed to initialise VAAPI connection.
ATTENTION: default value of option mesa_glthread overridden by environment.
michael@jammy-desk-vm:~$ code
michael@jammy-desk-vm:~$

**Comment by frol** [comment]
I experience the same issue with UTM 4.0.1 (60) running Ubuntu 22.04 Desktop.

**Comment by conath** [comment]
@mikeactual Please add your VM config, else I can't offer any suggestions. Thanks.

**Comment by mikeactual** [comment]
Here is the config from the vm that has been run under UTM 4.0.1. I still have a copy of the clean 3.2.4 vm. Let me know if it'll help to see that config.

Thank you for your attention. It's much appreciated.

Regards,
mike

[config.txt](https://github.com/utmapp/UTM/files/9387986/config.txt)

**Comment by conath** [comment]
@mikeactual Have you tried using a non-GL GPU? For example “virtio-ramfb”?

**Comment by mikeactual** [comment]
@conath That fixed me right up. Thank you for the pointer. Much appreciated.

**Comment by frol** [comment]
Well, non-GL GPU option allows Firefox (and Chromium) to start, but FPS is extremely low (2-5 FPS on https://webglsamples.org/aquarium/aquarium.html). Interestingly, Firefox in Ubuntu 22.04 LiveCD environment works just fine without residing to falling back to non-GL GPU

**Comment by mikeactual** [comment]
@frol Agreed, it's slow but it does work. It's ok for development. For performance I can flip out to the mac host or move over to Linux on a bare metal desktop. 

May I ask you where you found an Ubuntu 22.04 arm64 LiveCD with Ubuntu Desktop? I'd like to try that out.

Regards,
mike

**Comment by frol** [comment]
@mikeactual https://cdimage.ubuntu.com/jammy/daily-live/current/

**Comment by frol** [comment]
Oh, well, ubuntu LiveCD is running Xorg, and after installation it defaults to Wayland, but if you choose Xorg at the login (in the bottom right corner on the password screen), GL acceleration works perfectly fine, and Firefox runs at 23 FPS on that benchmark page (much more usable than 2 FPS as you may imagine)

**Comment by mikeactual** [comment]
@frol Thanks for the pointer. I could swear that the desktop edition wasn't there last time I looked. Well it is now. Cool. Also I can confirm that switching to Xorg enables GL acceleration on my rig as well. The graphics controller shows up as virgl (ANGLE (Apple, Apple M2, OpenGL 4.1 Metal - 76.3)). Nice catch. Thanks again. You are on a roll.

**Comment by TheFern2** [comment]
Just to add you can disable wayland on a config, to login automatically to xorg.

https://linuxconfig.org/how-to-disable-wayland-and-enable-xorg-display-server-on-ubuntu-18-04-bionic-beaver-linux

**Comment by mrinal975** [comment]
> Contributor

Thanks a lot, would you please explain matter.

**Comment by fabiensanglard** [comment]
I also encountered gfx glitches (infinity mirrro) when starting Firefox on Ubuntu ARM when I logged in with Wayland. No matter which display I selected for the VM.

If I logged in with XOrg, the glitches went away but Terminal and Files were full black.

I ended up fixing the issue by starting Firefox with `MOZ_ENABLE_WAYLAND=1` and logging in with Wayland. Everything works now.

**Comment by Yokubenimaru** [comment]
> @mikeactual Have you tried using a non-GL GPU? For example “virtio-ramfb”?

Thank you. This fixed for me

**Comment by retinfai** [comment]
> non-GL GPU

Can someone tell me how to do this please? Is it something I install?

**Comment by fabiensanglard** [comment]
You can select the GPU when you edit the VM configuration (right click on
it).

**Comment by retinfai** [comment]
Thanks! Worked straight away

**Comment by fabiensanglard** [comment]
Should we re-open this issue? There is a workaround but not having GPU acceleration is a problem.

**Comment by retinfai** [comment]
I agree. I don't know how, but the first ubuntu jammy VM I made with utm didn't have this error. Trying to recreate now

**Comment by vmachiel** [comment]
I know this is closed: has a new issue been opened yet?
