### ISSUE TITLE
3rd French localization update

### ISSUE THREAD

**Issue by FRtranslator** [utmapp/UTM#4311]
Hey,

I have attached a third update for the French localization of UTM.
There is a typo fix, a huge number of new translations (mainly tooltips, warnings and error messages), and a little update for Readme.md.

[UTM 4.0.1 beta french.zip](https://github.com/utmapp/UTM/files/9359000/UTM.4.0.1.beta.french.zip)

**Comment by osy** [comment]
I've merged the changes. I found a few files that were not UTF-8 and converted them to the right encoding. For the future, please consider making a pull request which will make things more streamlined. You can see other language translations as examples. Thanks!
