### ISSUE TITLE
mac OS 13 Beta 5 Installation Issue

### ISSUE THREAD

**Issue by rplankenhorn** [utmapp/UTM#4318]
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Describe the issue**  
Cannot install mac OS 13 Beta 5

**Configuration**  
* UTM Version: 3.2.4
* macOS Version: 12.5
* Mac Chip (Intel, M1, ...): M1

![Screen Shot 2022-08-18 at 9 59 29 AM](https://user-images.githubusercontent.com/228338/185414478-0af2563b-c926-4fcf-a47b-077e443d193c.png)

![Screen Shot 2022-08-18 at 10 00 11 AM](https://user-images.githubusercontent.com/228338/185414493-6b2e9105-3b05-4088-872e-858b32f77634.png)

**Comment by gustaf71** [comment]
I have not try, but it could be that you do not use the beta of Xcode... Apple also update Xcode when they have beta releases.

**Comment by conath** [comment]
I had a similar issue when I tried to restore an iPad to the latest beta. I had to install the latest Xcode beta first, including the additional software it installs on first run, and then it worked. So I suggest you install the latest Xcode beta and then try again.
