### ISSUE TITLE
Move deleted .utm into Trash

### ISSUE THREAD

**Issue by AwlsomeAlex** [utmapp/UTM#4332]
I know UTM will ask for confirmation if you want to delete a Virtual Machine, but another thing it could do is instead of completely erasing the .utm file containing the VM, it can move that file to the Trash bin where the user can then completely remove it itself. And maybe if the user doesn't want this to happen there could be a "Always erase" button in Preferences or a button to "Always erase" in the confirmation dialog.

**Comment by osy** [comment]
This isn't possible because the app is sandboxed and therefore cannot access the user's Trash.
