### ISSUE TITLE
Ubuntu Server Restarts Into Start of Install While Installing

### ISSUE THREAD

**Issue by stevekessler** [utmapp/UTM#4347]
When starting from a Ubuntu 22.0.41 server ISO (https://ubuntu.com/download/server/arm) for arm I am able to boot to the installer however the OS does not actually install.  Sometimes after the required install reboot after a significant amount of time it returns to the the screen to install the OS (Where I started before)  It has also completely crashed the UTM application (crash report included)

**Configuration**  
* UTM Version: Version 3.2.4 (58) - Downloaded from the App Store. 
* macOS Version:  12.5.1
* Mac Chip (Intel, M1, ...):  M1

**Crash log**  

I have added the crash log to a gist since it is over 600 lines.  https://gist.github.com/stevekessler/174a5ee4566fc8054db0b717e4e3da87

**Debug log**  
I have done the same with the Debug Log. https://gist.github.com/stevekessler/4ad720a62c7bed7ba344ef3618fb204c

**Upload VM**  
Here is a link for the UTM file https://ln5.sync.com/dl/562cb25a0/zu7ypc5x-vdn3m55y-z325k262-5np33crr . Sync.com is showing it as a folder.  I can upload it as a zip if this did not work.  

Thank you for any help getting this to work.  

Thanks,
Steve

**Comment by slhck** [comment]
Same here, after installing the OS and rebooting, it is just showing a blinking cursor indefinitely.

**Comment by sidouglas** [comment]
Same. I spent way too much time going around in circles. After running through the installation, it hangs. I reboot, and we start the process again.

https://youtu.be/Wr29ituooBI

**Comment by ak4zh** [comment]
Once installation is done cleared the mounted CD/DVD drive or choose boot from next volume.

**Comment by stevekessler** [comment]
I just got a message that a user named ak4zh suggested to remove the CD image after rebooting.  I do not know what happened to that message but it is 100% right. Thank you ak4zh. I appreciate you pointing this out and I am glad it was a simple solution. 

Thanks,
Steve
