### ISSUE TITLE
Misreporting RAM amounts in VM settings

### ISSUE THREAD

**Issue by ThatsNiceGuy** [utmapp/UTM#435]
**Describe the bug**
UTM will misreport RAM amounts in the System tab of VM settings.
This is with the release version of UTM 1.0 on iPad Pro 2020 11” with iOS 13.5.
Happens even if not jailbroken.

I have allocated 1024MB for RAM and JIT cache each and UTM reports only 128MB estimated RAM usage.
Also the device has 6.14GB of RAM, 5.56GB of which is usable by software after VRAM and other hardware needs but UTM reports that the host only has 1025MB of RAM.
![FAC91D64-F23D-4C60-9AC6-6464CC409905](https://user-images.githubusercontent.com/10524728/91682121-bf037b00-eb0d-11ea-902b-e1605f8a0d4a.png)

**To Reproduce**
N/A

**Crash log**
N/A

**Debug log**
N/A

**Upload VM**
N/A

**Comment by WeiChei7** [comment]
I am not subscribed to this thread yet I am still getting notifications

**Comment by ThatsNiceGuy** [comment]
Maybe you starred the repo. Idk

**Comment by saagarjha** [comment]
GitHub tells you why you are receiving notifications on the side of the issue:

<img width="292" alt="Screen Shot 2020-08-30 at 21 51 55" src="https://user-images.githubusercontent.com/13786931/91684018-063c3c80-eb0b-11ea-8a8e-8d76a4bd4bf8.png">

You're watching UTM, so you'll get a notification for all activity in the repository. Unwatch it to opt out.

**Comment by IIWare** [comment]
an r/softwaregore moment...

**Comment by joker3492** [comment]
I have a similar problem.
I installed android 9.utm but don’t run.
This is the error.
Can help me?
![Uploading AF511096-A751-42D8-8E28-A05885822115.png…]()

**Comment by osy** [comment]
Wondering if this is still an issue on latest. That code has gone though some changes.

**Comment by asesidaa** [comment]
I think there is still some issue. The estimated usage seems to be correct, but the total RAM value is still not correct. On my iPad Pro 2020 the total RAM is around 1300MB, which should be way more.

**Comment by osy** [comment]
Reworked memory limit detection in https://github.com/utmapp/UTM/commit/fc42aa9e5651d3d017bd7f17b82a9b075ab449c3
