### ISSUE TITLE
Config window text and control elements alignment issues [v4.0.3]

### ISSUE THREAD

**Issue by LostInCompilation** [utmapp/UTM#4374]
**Describe the issue**  
The config window of the VMs have alignment issues. The text and control elements are cut. This happens on most pages like "Input", "Sharing", "Display", ...

<img width="797" alt="Screenshot 2022-09-05 at 13 49 09" src="https://user-images.githubusercontent.com/12819635/188442515-787ee8c3-4a89-445f-9347-410a1a464d27.png">

**Configuration**  
* UTM Version: 4.0.3 (62)
* macOS Version: 12.5.1
* Mac Chip (Intel, M1, ...): M1 Pro

**Comment by brunocastello** [comment]
Same happens with the buttons for drive reclaim and compress space. I think the previous UI for that action is better, because semantically speaking, compressing the image is also a way to reclaim space (on host, it is).

**Comment by brunocastello** [comment]
> I disagree. The old UI is just an unnecessary extra click. It is far better like it is now. Those are also two completely different functions. Compressing is not reclaiming free space.
> 

As a professional UI/UX Designer, It's not an extra click when you want to do both reclaim and compress, which is what I have been doing on all vms prior to 4.0.2. Now I have to press one then wait till it reclaims to hit another to compress. Users will find its better to do it all in one go. 

Compressing is reclaiming free space, yes. Example: I have a 2GB DOS vm. It uses approx 1GB. After compression, it now uses 500mb of my host disk storage for that disk image. So I reclaimed 500GB back for my host machine. In a world where Apple machines are expensive and you have to save some bucks buying the entry level ones with less storage sizes, it's a must have to do it.

**Comment by osy** [comment]
But you don’t. If you click compress it literally says it will do both operations. This is also to make the UI consistent across multiple versions. On macOS 11 SwiftUI doesn’t support 3 button alerts so we just dropped the compress option.

**Comment by LostInCompilation** [comment]
Yeah I think you misunderstood something @brunocastello... It's literally the exact same thing, except those are now two separate buttons instead of a separate dialog which contains the same buttons previously. It is just one click less now, with the same functionality. Therefore much better UI design.

**Comment by brunocastello** [comment]
OK, I may have misunderstood it then. BTW, The current compression method on 4.0.3 is compressing much less than it did in 4.0.2. I noticed quite a bit of diffence between them when I compressed the exact same vm on both. I guess it has to go in another issue instead of here.

**Comment by osy** [comment]
By how much? We changed to zstd which should be ~5% worse in compression but should be much faster during reads.

**Comment by LostInCompilation** [comment]
Reclaiming space seems to be buggy too, see #4377. I could not test compression reliably, since reclaiming inflates the size by a great degree.
