### ISSUE TITLE
Emulation bugs on 4.0.3 but not on 4.0.2

### ISSUE THREAD

**Issue by Andrupka** [utmapp/UTM#4376]
**Describe the issue**
My Windows 7 VM crashes on 4.0.3 but works just fine on 4.0.2

**Configuration (required)**
* UTM Version: 4.0.3
* OS Version: 15.6.1
* Device Model: Xr
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? AltStore

[debug.log](https://github.com/utmapp/UTM/files/9491170/debug.log)

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the bottom of the configuration options (or at the top of the `QEMU` page) is `Debug Log`. Turn it on and save the VM. After you experience the issue, quit the VM and re-launch UTM. Open the VM settings again and select `Export Log...` and attach it here.

**Comment by osy** [comment]
Please also provide debug.log for 4.0.2
