### ISSUE TITLE
French localization update for 4.0.3 beta

### ISSUE THREAD

**Issue by FRtranslator** [utmapp/UTM#4383]
Hi,

Please find attached the update French localization for UTM 4.0.3 beta.
A few fixes, new strings, and trying to cleanup the file a bit.

Enjoy.

[UTM French localization update for4.0.3 beta.zip](https://github.com/utmapp/UTM/files/9507846/UTM.French.localization.update.for4.0.3.beta.zip)

**Comment by osy** [comment]
Hi, your files are still using the wrong encoding. I will convert them again but please make sure they are in UTF8 and please use the pull request feature in the future.
