### ISSUE TITLE
Issues with PowerPC VMs with virtual IDE drive interface

### ISSUE THREAD

**Issue by Denisxiang** [utmapp/UTM#4384]
<img width="912" alt="Screenshot_2022-09-07_at_10 49 41_pm" src="https://user-images.githubusercontent.com/94837981/189027784-f1a7ff69-5dba-4cde-9fe7-a929ed8ff331.png">
[debug.log](https://github.com/utmapp/UTM/files/9523373/debug.log)

**Comment by dannywmckee** [comment]
same issue with my attempt to set up power pc / mac os 9.2

**Comment by osy** [comment]
Same cause as #4372, will be fixed next beta.
