### ISSUE TITLE
Can not mount virtiofs under Ubuntu focal (20.04.5 LTS)

### ISSUE THREAD

**Issue by gkyildirim** [utmapp/UTM#4386]
Ubuntu kernel version:
 ``` Linux SPA 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Mon Aug 8 18:51:21 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux ```

I see qemu process is launched in macOS with the correct params as:
 ```
-fsdev local,id=virtfs0,path=/Users/userx/Public,security_model=mapped-xattr -device virtio-9p-pci,fsdev=virtfs0,mount_tag=share
```

When trying to mount  it gives the following error:
```
sudo mount -t virtiofs share /mnt
mount: /mnt: wrong fs type, bad option, bad superblock on share, missing codepage or helper program, or other error.
```

And kernel error is:
```
[Thu Sep  8 08:25:07 2022] virtio-fs: tag <share> not found
```

I read that virtiofs needs ```virtiofsd``` running in the hypervisor and I see no process running in my macOS (https://virtio-fs.gitlab.io/design.html).

Am I missing something? 

Thanks for the hard work.

* UTM Version: v.4.0.3
* macOS Version: 12.5.1
* Mac Chip (Intel, M1, ...):  M1

[config.plist.zip](https://github.com/utmapp/UTM/files/9523831/config.plist.zip)

**Comment by ehntoo** [comment]
The new shared folder implementation appears to be virtio-9p/"virtfs" rather than virtiofs. You may have better luck attempting a mount this way:

```
mount -t 9p -o trans=virtio share /mnt -oversion=9p2000.L
```

(from https://wiki.qemu.org/Documentation/9psetup#Mounting_the_shared_path)

**Comment by gkyildirim** [comment]
This is related to #4389. And I hope this feature lands in UTM.
