### ISSUE TITLE
“QEMU exited from an error: Could not remap code buffer mirror” please help

### ISSUE THREAD

**Issue by subzero75** [utmapp/UTM#439]
I got this “QEMU exited from an error: Could not remap code buffer mirror” when trying to start the android 9 that I downloaded from here: https://getutm.app/vms/
After that the app close automatically 
Ipad 9.7” 2016 , 32 gb , 4g ram , wifi only 

IOS: 14 beta 

Not jailbroken device

Please help and thanks

**Comment by ThatsNiceGuy** [comment]
UTM won’t work on iOS 14 unless you use a Mac with Xcode to attach a debugger.
Please downgrade to iOS 13.

**Comment by subzero75** [comment]
I downgraded to iOS 13.6.1 and then worked fine , thx

**Comment by osy86** [comment]
Duplicate of #397
