### ISSUE TITLE
UTM slows down only to accelerate when control/notification panel is switched on

### ISSUE THREAD

**Issue by olly138** [utmapp/UTM#440]
I am dealing with an issue on all x86 windows versions I have installed 98/XP on 7th gen iPad.
VM seems to be working fine, although it's being very laggy - both in terms of loading times as well as well as in how the cursor moves.
Solution to this is to launch any iOS interface module for a second - then the VM accelerates for about 5 seconds.
On occasions - whole setup tends to work fine and smoothly - I could easily make a use out of it on regular basis back in the days.

Launching XP takes around 30 seconds if you do this thingy with notification panel - without it - it easily takes 2 mins or even more.

Any ideas on how to deal with this kind of bug?
I am happy to provide a video of this behavior and/or any logs that you could find useful.

Thanks!

**Comment by osy86** [comment]
This is likely iOS's scheduling algorithm at work.

**Comment by olly138** [comment]
Well, one way to deal with that is to start screen recording. Probably eats some of device's power but it's still better than launching notifications pane every 5 secs.

**Comment by hdjdvd** [comment]
I'll give you a ban that you're distributor. You don't have any value.
You're a failed company. You don't send me.
