### ISSUE TITLE
Append QEMU arguments to the UTM GUI

### ISSUE THREAD

**Issue by sbates130272** [utmapp/UTM#4405]
Hi!

I would like the ability to add QEMU arguments to the QEMU call in UTM. It seems like we could do this via a field in the UTM GUI under the QEMU tab? I want to be able to add more emulated devices (right now CXL) and I cannot seem to do that via UTM.

Stephen

**Comment by osy** [comment]
Yes you can add arguments but not every QEMU argument is supported.

**Comment by sbates130272** [comment]
@osy can you point to the documentation that describes how to add QEMU argments to the UTM call into QEMU? I can not see how it is done.
