### ISSUE TITLE
Exporting VM includes view.plist, prevents importing on other machines

### ISSUE THREAD

**Issue by Aaron-Rumpler** [utmapp/UTM#4406]
**Configuration**  
* UTM Version: 3.2.4
* macOS Version: 12.4
* Mac Chip: Intel

When I export a VM from UTM, the exported VM includes the `view.plist` file, which prevents the VM from being imported on different machines (it complains that it can't follow the shortcut bookmark).

**Comment by osy** [comment]
This is one of the reasons why view.plist is gone on UTM v4
