### ISSUE TITLE
Unable to disable hypervisor option on different architecture

### ISSUE THREAD

**Issue by Aaron-Rumpler** [utmapp/UTM#4407]
**Configuration**  
* UTM Version: 3.2.4
* macOS Version: 12.4
* Mac Chip: M1

When importing an x86 VM that has the 'Use Hypervisor' option enabled on an Apple Silicon Mac, the VM refuses to start with the error "qemu-x86_64-softmmu: unable to find CPU model 'host'".

<img width="800" alt="QEMU Error" src="https://user-images.githubusercontent.com/80610725/189800280-51b954d3-ed5c-4571-94e8-80a844bd0188.png">

**Comment by osy** [comment]
That’s expected because obviously you can’t virtualized x86 on arm. Go into the vm settings and uncheck the option to use hypervisor under QEMU settings.

**Comment by Aaron-Rumpler** [comment]
1. The mouseover text for that option implies the option is ignored on Apple Silicon: 
<img width="828" alt="Screen Shot 2022-09-13 at 4 22 12 PM" src="https://user-images.githubusercontent.com/80610725/189808224-22314f2a-2c14-4bd4-bf85-60b943b513cc.png">
2. The option is grayed out on Apple Silicon, even if enabled.

**Comment by Aaron-Rumpler** [comment]
Thanks
