### ISSUE TITLE
Linux guest keyboard and mouse not working on Apple Virtualization (Intel)

### ISSUE THREAD

**Issue by fernandomacho** [utmapp/UTM#4409]
I try to install linux image over Apple virtualization, the installer bring up, but not work capture keyboard and mouse and unable continue with installation

**Configuration**  
* UTM Version: 4.0.3
* macOS Version: 16.0
* Mac Chip (Intel, M1, ...): Intel
[utm_log.txt](https://github.com/utmapp/UTM/files/9554831/utm_log.txt)

**Comment by conath** [comment]
Please double-check if this still occurs in UTM 4.0.6 RC: https://github.com/utmapp/UTM/releases/tag/v4.0.6

**Comment by fernandomacho** [comment]
Hi, I install version Version 4.0.6 (65) and I get same result, and keyboard not work

Thanks in advance

**Comment by ManuW** [comment]
I can confirm this. My keyboard is not working too if I try to install an image over Apple virtualization.

It make no difference if I use the integrated keyboard from my MacBook or use the  Magic Keyboard via Bluetooth or USB.

I have no issues if I try the Apple example _Running GUI Linux in a virtual machine on a Mac_.

**Comment by ManuW** [comment]
Okay, I found the bug. `keyboards` and [pointingDevices](url) are only available for arch `arch64` if I understand it correct. See [UTMAppleConfigurationVirtualization.swift](https://github.com/utmapp/UTM/blob/977c2cc9b59eedbf4d82df7bfd2ea6efc85cf369/Configuration/UTMAppleConfigurationVirtualization.swift#L137)

I checked the main branch and installed all dependencies. I run the project, bug can be reproduces on my machine.
Then, I simply searched for `keyboards =`. Moved booth lines, keyboards and pointingDevices and run the project again. Now I can use keyboard and my mouse as well.

**Comment by osy** [comment]
Okay that’s true but I didn’t know that GUI (EFI boot) works on Intel. I’ll add it if it’s supported.

**Comment by ManuW** [comment]
From the [GUI Linux example](https://developer.apple.com/documentation/virtualization/running_gui_linux_in_a_virtual_machine_on_a_mac):

> ...
> **Important**
> The Virtualization framework can run Linux VMs on a Mac with Apple silicon, and on an Intel-based Mac. The Linux ISO image you download must support the CPU architecture of your Mac.
> ...

Yes, booth CPU architectures are supported.

**Comment by ManuW** [comment]
Thanks @osy - I test this tomorrow. 

I have an audio issue too and I will write an issue report. Audio in-/output works when I create two sound devices. One for input and one for output. Like in the examples I have seen. But I found no information in the documentation, that the current code is not correct. Maybe an issue only on Intel, who knows? There is not much documentation to find...

My current patch https://github.com/utmapp/UTM/compare/main...ManuW:UTM:test-apple-virtualization

**Comment by osy** [comment]
I see, I will do that as well just to be safe.

**Comment by ManuW** [comment]
@osy Thanks! I tested it today and keyboard, mouse is working and sound in general too. If I record something, then I have glitches, but that issue is somewhere else...
