### ISSUE TITLE
Virtualized VM immediately crashing upon launch on M1 iPadOS 14.5, arm64 Windows 11

### ISSUE THREAD

**Issue by meerkatriptide** [utmapp/UTM#4416]
**Describe the issue**
Created VM using "Virtualize" option with Windows 11 (22000.918) arm64 ISO. 4GB RAM and 50GB storage.
Starting VM immediately crashes the app.
Disabling in Settings -> QEMU -> Use Hypervisor allowed the VM to launch.

**Configuration (required)**
* UTM Version: 4.0.4, UTM.HV.ipa used
* OS Version: iPadOS 14.5
* Device Model: 5th Gen M1 12.9 inch iPad, 16GB RAM
* Is it jailbroken (name jailbreak used)? Yes, unc0ver
* How did you install UTM? Tried both filza/appsync unified & trollstore

**Crash log**
[UTM-2022-09-11-170412.txt](https://github.com/utmapp/UTM/files/9570383/UTM-2022-09-11-170412.txt)

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/9570407/debug.log)

**Comment by Suchan0127** [comment]
Yes, that’s because you are not using iPadOS 15.0~15.1.1
Hypervisor on iPad M1 is only supported on iPadOS 15.0~15.1.1.

**Comment by osy** [comment]
iOS 14 requires different hypervisor offsets. I am working on that right now and will provide an IPA to test soon.

**Comment by osy** [comment]
Please test https://github.com/utmapp/UTM/suites/8313076043/artifacts/365026554 and post crash log if it still crashes.

**Comment by meerkatriptide** [comment]
It is still crashing but looks like some progress made. Before it would crash instantly after tapping start button but now it gets to grey screen with loading icon in middle that appears before booting.

[UTM-2022-09-15-145258.txt](https://github.com/utmapp/UTM/files/9578178/UTM-2022-09-15-145258.txt)
[debug.2.log](https://github.com/utmapp/UTM/files/9578177/debug.2.log)

**Comment by osy** [comment]
@meerkatriptide please try https://github.com/utmapp/UTM/suites/8322812338/artifacts/365745890

**Comment by meerkatriptide** [comment]
Getting below screen, no loading bar or any further text appeared after waiting for 10+ minutes.

![screen](https://user-images.githubusercontent.com/113571262/190636000-4b4138c7-1f0d-471c-b190-9e876331c889.PNG)

[debug.3.log](https://github.com/utmapp/UTM/files/9583827/debug.3.log) (This log I just quit the VM almost immediately to generate it)

**Comment by osy** [comment]
Fixed in f1997bc976e18ebf31f94f169461a35f2f5c4859
