### ISSUE TITLE
Add support for 5120 × 1440 Ultra Wide Resolution

### ISSUE THREAD

**Issue by wamra** [utmapp/UTM#4418]
Hi, 
Would you please add support for the 5120 x 1440 resolution to support Samsung 49" Odyssey G9 wide-screen monitors? 

I would add it if I had access to branch and create pull requests. 

https://vscode.dev/github/utmapp/UTM/blob/main/Platform/macOS/VMConfigAppleDisplayView.swift#L115
 
```
        NamedResolution(name: "5120 × 1440 — 5K Ultra Wide HD",
                        resolution: Resolution(width: 5120, height: 1440))
```

![image](https://user-images.githubusercontent.com/3786934/190412140-22429dba-79eb-434f-871b-d8db5457279e.png)

**Comment by conath** [comment]
@wamra you can always open a PR by forking the UTM project, creating a new branch there with your changes, and then opening the PR like this: https://github.com/utmapp/UTM/pull/4444
