### ISSUE TITLE
UTM white screen then crash on iPad

### ISSUE THREAD

**Issue by CodeFlow20** [utmapp/UTM#442]
When I open UTM (Trusted) On the latest iOS for iPad, 13.7,
It gives me a white screen for about half a second then crashes. It is trusted, I used AltSigner to sign and install it. I cannot use AltStore / Alt Server to install it because it says "Unknown services response error (-1)"

How to reproduce:

Install AltSigner
Install UTM .ipa and run it through alt signer
Install via alt signer
Trust the application on your iOS device
Run the UTM app installed

**Comment by IIWare** [comment]
You force quitted haven't you? if so then reboot your device and the next time you exit UTM click (X)
