### ISSUE TITLE
Cursor options doesn't work

### ISSUE THREAD

**Issue by Halo-Michael** [utmapp/UTM#4424]
**Describe the issue**
Cursor options doesn't work. The touch input mode will always be drag cursor mode, even I choose touch mode (always show cursor) or touch mode (try hiding cursor).

**Configuration (required)**
* UTM Version: 4.0.4~4.0.5
* OS Version: 15.3.1
* Device Model: iPhone SE(2nd)
* Is it jailbroken (name jailbreak used)? no
* How did you install UTM? sideload

**Upload VM**
[config.plist](https://github.com/utmapp/UTM/files/9586439/config.plist.txt)

**Comment by Halo-Michael** [comment]
To be clear: this issues may not start from 4.0.4, but must start from 4.0.

**Comment by osy** [comment]
@Halo-Michael Make sure that QEMU -> Force PS/2 Controller is not checked. I think during the migration to v4 settings, it toggled the setting.

**Comment by Halo-Michael** [comment]
> @Halo-Michael Make sure that QEMU -> Force PS/2 Controller is not checked. I think during the migration to v4 settings, it toggled the setting.

It is not checked, I have already uploaded my config file, you can also check it.

**Comment by Halo-Michael** [comment]
> @Halo-Michael Make sure that QEMU -> Force PS/2 Controller is not checked. I think during the migration to v4 settings, it toggled the setting.

But it is un-ckecked; I have already uploaded my config file, you can check it.

**Comment by osy** [comment]
You have USB bus disabled though.

**Comment by osy** [comment]
That’s actually intended if USB bus is disabled. It used to be called “legacy input”
