### ISSUE TITLE
Updated French localization for 4.0.5

### ISSUE THREAD

**Issue by FRtranslator** [utmapp/UTM#4428]
Hi,

I have attached the updated French translation for 4.0.5 beta.
A few typo fixes, new strings, huge file cleanup in this update.

If someone finds not yet translated strings, typos, please contact me! :)

[UTM-french 4.0.5.zip](https://github.com/utmapp/UTM/files/9591942/UTM-french.4.0.5.zip)

**Comment by osy** [comment]
@FRtranslator As I asked you to multiple times before, please submit a pull request in the future. And please make sure your files are in UTF-8 format.
