### ISSUE TITLE
Internet not Working

### ISSUE THREAD

**Issue by chrisjithui** [utmapp/UTM#4450]
**Describe the issue**  
No internet, I've installed Spice Guest Tools and tried few different settings. Any clue?

**Configuration**  
* UTM Version: 4.0.6
* macOS Version: 12.3.1
* Mac Chip M1: 
* 
![CleanShot 2022-09-27 at 2 52 43](https://user-images.githubusercontent.com/114436662/192357335-f4df393b-5f0e-4224-a363-f0c698f619a4.jpg)

![CleanShot 2022-09-27 at 2 54 50](https://user-images.githubusercontent.com/114436662/192357452-57ae9c60-c651-4e3c-b97f-df0a25c08198.jpg)

**Comment by conath** [comment]
Can you test by opening https://1.1.1.1/ in a web browser in the VM? If that works, you are running into a DNS issue (maybe similar to #2353). If that does not work, your VM did not pick up the ethernet adapter or TCP/IP settings correctly.
