### ISSUE TITLE
Login to Windows using Ctrl, Alt & Del on a Mac Keyboard

### ISSUE THREAD

**Issue by TicT0ck** [utmapp/UTM#4451]
I have a MacBook Air M1.  I have Server 2022 installed in UTM Virtual Machine.  I have successfully installed Server 2022 and it is asking me to press CTRL, ALT & DEL but how do I this from a MacBook Air laptop?

**Comment by conath** [comment]
On Mac you can get the DEL key by pressing fn and delete together.
So you want to press  fn ⌃ ⌥ delete
