### ISSUE TITLE
No option for touchscreen on iOS 

### ISSUE THREAD

**Issue by cer1234567-bit** [utmapp/UTM#446]
Once I create a virtual machine with an android OS there is no option for touchscreen,only gestures and once I load up the VM I click boot and it freezes

**Comment by zbliiiiii** [comment]
Prompt "could not allocate dynamic translator buffer"

**Comment by cs-sugar** [comment]
Well, this should be a bug.

**Comment by osy86** [comment]
Cannot reproduce.
