### ISSUE TITLE
Unable to edit macOS guest config

### ISSUE THREAD

**Issue by scheblein** [utmapp/UTM#4465]
**Describe the issue**  
I'm trying to change shared networking to bridged and after opening the config window, clicking on the network option or anything (system, boot, etc) doesn't change to that option.

**Configuration**  
* UTM Version: 4.0.6
* macOS Version: 13.0 b9
* Mac Chip (Intel, M1, ...): M1 

**Visual Demo**
https://youtu.be/CVMoAOhodsk

**Debug log**  
[utm process from console app.txt](https://github.com/utmapp/UTM/files/9677272/utm.process.from.console.app.txt)

**Comment by hcpcrose** [comment]
I am using the same version of UTM, and macOS. I am having the same issue and can replicate it consistently.

**Comment by hcpcrose** [comment]
@osy I originally had this problem with an existing VM.  After reading through the release notes, I saw that this was a known issue.  So then I deleted the legacy VM's and created two new ones directly from the UTM Virtual Machine Gallery.  One Mac OS 9.2.1 and the other Windows 11 x64.  I have included both the config.plist files.  
[MacOS921-config.plist.txt](https://github.com/utmapp/UTM/files/9689219/MacOS921-config.plist.txt)
[Win11-x64-config.plist.txt](https://github.com/utmapp/UTM/files/9689220/Win11-x64-config.plist.txt)

**Comment by scheblein** [comment]
New ones created in 4.x. I’ll send the plist along when I get back to my Mac.

**Comment by osy** [comment]
@scheblein @hcpcrose Can you try **4.0.6** (the last version, the one this issue was reported on) on the latest macOS 13 Ventura Beta 11? There's reports of SwiftUI fixes so I was wondering if maybe apple fixed this issue.

If it's still broken, then please try 4.0.7. Thanks.

**Comment by osy** [comment]
Okay so Ventura did fix the issue. I think I’ll remove the workaround that was added here (showing a blank page when you open settings).

**Comment by scheblein** [comment]
@osy - confirmed working even on 4.0.5.

**Comment by hvanniek** [comment]
I'm on Ventura 13.0.1, with UTM v 4.0.9 and running into this issue again. Can anyone confirm if it's returned?

**Comment by hcpcrose** [comment]
I'm currently running Ventura 13.2 Public Beta (22D5027d) and UTM Version 4.1.0 (69).  No issues for me.

**Comment by hvanniek** [comment]
Recreated the VM and problem was solved for a new VM. Works fine for the older VM's generated from the catalogue as well.
