### ISSUE TITLE
Can’t select W11 VHDX file on set up screen (iOS)

### ISSUE THREAD

**Issue by realrodri** [utmapp/UTM#4466]
![72354032-42FD-408F-BAD4-2C73D7FD6500](https://user-images.githubusercontent.com/40494400/193114825-58ed5405-9014-4333-9fd8-16ca1e53f218.png)
![5AF61C6D-6F9B-442B-9684-3F78F1D0F422](https://user-images.githubusercontent.com/40494400/193114834-c38a0dda-1b17-4a21-b1d4-ebc39ce06244.jpeg) 

Information about my device:

- iPad Air 4th Gen
- iOS 14.4 jailbroken with Fugu14
- Installed UTM through Cydia
- Downloaded the VHDX from Microsoft’s official site (following the link on the UTM app)

LMK any more info I can provide and I’d be pleased to so!

**Comment by conath** [comment]
Unfortunately you are running into an iOS limitation, we can't use the file if it's in the iCloud Drive folder. You need to move the file from iCloud Drive to the "On My iPad" storage first, then select it in UTM.

FYI you can change the Safari download folder to be On My iPad, it is in Settings app => Safari.
