### ISSUE TITLE
Networking not working after upgrade

### ISSUE THREAD

**Issue by WMRamadan** [utmapp/UTM#4468]
**Describe the issue**  
After upgrading from UTM 3.1.5 to UTM 3.2.4 networking has stopped working for all Linux based VM's yet works for Windows.

**Configuration**  
* UTM Version: 3.2.4
* macOS Version: 12.6
* Mac Chip (Intel, M1, ...): Apple Silicon M1
* Linux Distors: (Ubuntu 20.04.4 LTS) & (Debian 10.4)

**Comment by splaquet** [comment]
I'm on an M1 machine.

I discovered an odd issue... before updating to the latest RC (from latest stable), I disabled advanced graphics. while this allowed me to then copy/paste (checking off allow copy/paste didn't work), it then broke my networking.

I swapped back graphics and networking worked again.

I installed the latest RC, hoping that'd fix my networking, but now it's not working on either window (2 windows open now.  1 w/o advanced graphics and one with)

**Comment by ktprograms** [comment]
What Linux distro are you using? Did you see the release notes for the RC? It explains how the network device was moved to be the first PCI device, and how to fix it on Ubuntu.

**Comment by splaquet** [comment]
thanks, but still not working.

I disabled the Advanced Graphics in the stable release.  That option doesn't appear to be present in the latest RC.

also, with the latest RC, I'm able to copy/paste in the console window, but not in the graphic window.
<img width="1039" alt="Screenshot 2022-09-30 at 10 57 32 AM" src="https://user-images.githubusercontent.com/6146508/193298684-61aa4661-6800-4ed0-9969-7ebbb8c7a7f2.png">

**Comment by WMRamadan** [comment]
Has anyone tried the following with success:

```
Networking is unavailable
When switching between display modes or changing hardware settings, the network adapter may be renamed by Ubuntu. To fix this, you need to set up networking again.

Run ip link show and look at the last adapter name. For example, it may be listed as enp0s9.
Edit /etc/netplan/00-installer-config.yaml and copy your configuration for enp0s8 (or whatever the old adapter was named) and paste it immediately after for enp0s9 (or whatever the new adapter is named).
Reboot and you should be able to use networking in both display modes.
On older versions of Ubuntu and other Linux distributions, you may not have Netplan. In that case, refer to support documents for your distribution on how to set up a new network adapter as the name of the adapter may have changed.
```

**Comment by ktprograms** [comment]
What is not working? Did you edit the netplan configuration as mentioned in the release notes?

**Comment by splaquet** [comment]
> What Linux distro are you using? Did you see the release notes for the RC? It explains how the network device was moved to be the first PCI device, and how to fix it on Ubuntu.

I DID NOT see that! Thank you so much!

with a bare install of Ubuntu 22, I didn't seem to have any text editors. very odd IMO... but, sobeit

I used:
`sed -i 's/enp0s6/enp0s1/g' /etc/netplan/00-installer-config.yaml`

Which, after a reboot, did appear to fix things.  Thank you @ktprograms !

**Comment by splaquet** [comment]
That was it. Thank you!
