### ISSUE TITLE
[feature request] Add the Special qemu-system-arm & bios for Windows RT to UTM

### ISSUE THREAD

**Issue by Liiziip** [utmapp/UTM#4470]
Can you add the special qemu-system-arm & bios for Windows RT to UTM? The normal qemu-system-arm can't emulate Windows RT,but this qemu-system-arm can do it
https://github.com/binarymaster/qemu/releases
Result should look like this: https://twitter.com/x86corez/status/1523303255438028800

I emulate Windows RT 8.1 build 6.3.9600.17328.armfre.winblue_r3.140827-1500 on my Windows10 Laptop, it works very well, just like running on the real Surface RT, but I can't find the drivers for it :( 
I think it may be a good idea to emulate Windows RT on iPad iPhone or Mac, so plz add it to UTM!!!!!
PS: sorry for my bad English

**Comment by conath** [comment]
@Liiziip Thanks for the suggestion.

Generally, you can use custom EFI firmware in UTM by importing it as a drive and changing the type to BIOS. However I believe the one you linked to requires the code changes in that specific QEMU variant, as I was not able to get the firmware to start up in UTM.

However, it is possible to use more recent Windows 11 for ARM in UTM, as long as you get hold of an install ISO. There are guest tools available, as well. Check the new [Windows 11 guide](https://docs.getutm.app/guides/windows-11/) for more information.

**Comment by binarymaster** [comment]
> The normal qemu-system-arm can't emulate Windows RT, but this qemu-system-arm can do it

Well ideally, the changes done there needs to be polished, and probably separated into a new machine target. Then it could be attempted to send patches upstream. Same for the EDK2 UEFI firmware.

Once the upstream has accepted the patches, it would be easy for downstream projects to pick this up.
