### ISSUE TITLE
ubuntu server 20.04.05 on m2 MacBook

### ISSUE THREAD

**Issue by Thesis0504** [utmapp/UTM#4480]
**Describe the issue**  

I want to create 20.04.5 version of ubuntu server. The archive I downloaded is the amd version of `.iso`. Use `fs0:\efi\boot\bootaa64.efi` but get erro. 
<img width="1470" alt="截圖 2022-10-07 下午7 45 04" src="https://user-images.githubusercontent.com/115269183/194595010-f0f3c659-fe99-4096-919c-50f95514baa2.png">

I had tried the following ways:
1. [#4002](https://github.com/utmapp/UTM/issues/4002)
<img width="1103" alt="截圖 2022-10-08 上午12 20 41" src="https://user-images.githubusercontent.com/115269183/194601707-93640e8a-281d-4371-908a-ba1068681776.png">

2. [#2333](https://github.com/utmapp/UTM/issues/2333)
in the way provided by djwhatle, but still can't succeed.

 =>  ubuntu server 22.04.01  :  everything works fine.

Is there any way to install version 20.04.05 on the M2 computer?

**Configuration**  
* UTM Version: 3.2.4
* macOS Version: 12.5
* Mac Chip (Intel, M1, ...): M2

**Comment by conath** [comment]
The VM image you downloaded is `x64` while you need to use `aarch64` which is available from the [Ubuntu 20.04.05 release](https://cdimage.ubuntu.com/releases/20.04.5/release/) website (on there, select "64-bit ARM (ARMv8/AArch64) server install image").
