### ISSUE TITLE
Add documentation for rosetta

### ISSUE THREAD

**Issue by SuperKenVery** [utmapp/UTM#4485]
When mounting the rosetta volume (following instructions on apple.com), you need to specify a tag, which is not shown anywhere in UTM. 

By reading the source code, I learnt that the tag is `rosetta`. 

Could you please put this somewhere so that the user can see it?

**Comment by osy** [comment]
This will be added in the future. https://docs.getutm.app/advanced/rosetta/

**Comment by SuperKenVery** [comment]
Great!
