### ISSUE TITLE
Document how to use Apple Virtualization with examples

### ISSUE THREAD

**Issue by Sitin** [utmapp/UTM#4486]
At the moment it is not clear how to use Apple Virtualisation for UTM. A simple HOWTO that describes how to run latest Ubuntu/Debian/Fedora will be very helpful.

**Comment by osy** [comment]
Yes that is planned for 4.0 release. It will be at https://docs.getutm.app/

**Comment by Sitin** [comment]
Great! Are there any docs I can start reading now?

**Comment by osy** [comment]
I mean whatever’s online you can read.

**Comment by osy** [comment]
https://docs.getutm.app/guides/debian/
