### ISSUE TITLE
oobe/bypassnro not working

### ISSUE THREAD

**Issue by DiegoSalvador27** [utmapp/UTM#4487]
I was trying to bypass the network screen by typing oobe/bypassnro but it was not working. I used brew to change the vhdx file to qcow2 and its just saying oobe is not recognized as an internal or external command

**Comment by conath** [comment]
You need to put a backslash instead of a forward slash: `oobe\bypassnro`

Check out the [new Windows in UTM guide](https://docs.getutm.app/guest-support/windows/#windows-10-and-higher) for easier installation steps.
