### ISSUE TITLE
M1 14.6 installed with TrollStore cannot run VMs

### ISSUE THREAD

**Issue by JamesLewisLiu** [utmapp/UTM#4493]
**Describe the issue**
M1 iPad Pro running iPadOS 14.6 installed UTM with TrollStore cannot run VMs,will stuck start boot options forever

**Configuration (required)**
* UTM Version: 4.0.6RC
* OS Version: 14.6
* Device Model: 5th Gen 12.9 iPad Pro
* Is it jailbroken (name jailbreak used)? No 
* How did you install UTM? TrollStore

**Crash log**
No

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/9747174/debug.log)

**Comment by osy** [comment]
Should be fixed in v4.0.7

**Comment by JamesLewisLiu** [comment]
Okay its working now thanks
