### ISSUE TITLE
UTM crashes when I open a vm created in UTM

### ISSUE THREAD

**Issue by pointlessduffin** [utmapp/UTM#45]
After I create a VM and installed Windows and Linux on it in UTM, I close the app and open it again after a couple of hours and the vm dosen't open anymore instead UTM crashes.

The device that I am using to test this is an iPhone XR running iOS 13.3 jailbroken with unc0ver v4.0.3.

**Comment by Garlicvideos** [comment]
Have you tried rebooting and then re-jailbreaking afterwards?

**Comment by rogerus** [comment]
Hi, I encountered the same problem. As a workaround, I reboot my iPad every time UTM shows white screen.

**Comment by Nicholassena8190** [comment]
I been having this problem too, after I created one, I pressed on it, it crashes instantly.

Device: iPad 7th Generation with iOS 13.3 Not Jailbroken

My PC is not compatible with Linux and other operating systems, but is compatible with Windows since my PC’s BIOS doesn’t have a option to switch.

**Comment by Garlicvideos** [comment]
If you’re jailbroken, the VMs will only crash if there’s a issue with your ISO or Configuration.

If you’re not jailbroken and you’re below iOS 13.3.1, you need to sign the app with a **Free Developer Certificate** for the *VM* to run.

If you’re not jailbroken and are on iOS 13.3.1 or above, you need to sign the app with a **PAID Developer Certificate** for the *VM* to run

The app will run just fine, but the VM will not

**Comment by osy86** [comment]
#32
