### ISSUE TITLE
Wrong Content-Type on AltStore repository

### ISSUE THREAD

**Issue by Assfugil** [utmapp/UTM#450]
**Describe the bug**
The content-type header should be `application/json` but in reality it is `text/html`.

**To Reproduce**
1. `curl -I https://alt.getutm.app/`
2. > content-type: text/html; charset=utf-8

**Crash log**
N/A

**Debug log**
N/A

**Upload VM**
N/A

**Comment by osy86** [comment]
Is that really an issue? It’s hosted on GitHub pages so there’s no way to change it.
