### ISSUE TITLE
QEMU exited from an error: Could not allocate dynamic translator buffer

### ISSUE THREAD

**Issue by IIWare** [utmapp/UTM#451]
I am using **UTM v2.0b1**

Here are my Phone's Specs:
iOS Version: **13.6.1**
Jailbroken: **False**
RAM: **3 GB of RAM**
iPhone: **iPhone X (iPhone10,6)**

I decided to create a test VM in UTM, and when I try to start the VM, this happened:

![Screenshot 2020-09-13 at 16 58 27](https://user-images.githubusercontent.com/66434686/92935750-e46b7f80-f451-11ea-81e4-d219b5cbde1c.png)

I don't know how did this even happened, I just applied the following VM specs:
‌
> N A M E

Name: **Virtual Machine 1**
‌
‌
> H A R D W A R E

Architecture: **x86_64**
System: **PC**
Memory/RAM: **256 MB**
CPU Count: **1**
‌‌
‌
> B O O T

Boot: **HDD**
‌
‌
> Q E M U

JIT Cache: **32 MB**
Force Multicore: ON
‌
‌
> H O S T‌ ‌ ‌ I N F O R M A T I O N

Total RAM: **2471 MB**
Estimated Usage: **128 MB**
CPU Cores: **6**

so can you please fix the bug? or if it's just me, can you please tell me how to fix the issue, thanks!

**Comment by ssangkong** [comment]
same issue.
iPad Pro 11 (2nd Gen.)
iPadOS 13.5 (Jailbroken)

**Comment by EvilAirborn** [comment]
Same Issue.
iPhone 11
Using Android 9.0 from https://getutm.app/vms/

**Comment by qunwang6** [comment]
problem still in iphone7 iphone11 ios13 utm v2.0b2

**Comment by osy86** [comment]
Can you delete and reinstall?

**Comment by qunwang6** [comment]
> Can you delete and reinstall?

delete utm and reinstall sitll have problem in ios 13.7

**Comment by qunwang6** [comment]
> Can you delete and reinstall?

i use Individual certificate to re-sign

**Comment by osy86** [comment]
Make sure you’ve redownloaded the ipa from github.

**Comment by qunwang6** [comment]
> Make sure you’ve redownloaded the ipa from github.

utm v2.0b2

**Comment by osy86** [comment]
What is the MD5 hash of the IPA you downloaded?

**Comment by ssangkong** [comment]
The error message was disappeared. But it still crash.
I can boot windows xp in safe mode.
safe mode with networking, fail.
Normal boot, fail.

so I use version 1.0 instead beta. :(
It’s working well.

**Comment by osy86** [comment]
Open a new issue with the requested information. This is why it’s called a beta.

**Comment by Oliver2213** [comment]
I still encounter this issue on betas 3 and 4.
iPhone: SE 2020, iOS 13.4.1, jailbroken.

**Comment by osy86** [comment]
@Oliver2213 how did you install it? Does v1.0 work?

**Comment by Oliver2213** [comment]
@osy86 I installed it through altstore. Haven't tried 1.0. Downloading it now and will mention if that version works.

**Comment by Oliver2213** [comment]
@osy86 version 1.0 works.

**Comment by osy86** [comment]
@Oliver2213 I should make this clearer but if you’re jailbroken you should install UTM.ipa directly with Filza or something. I think AltStore strips the entitlements.

**Comment by ThatsNiceGuy** [comment]
Sorry to butt in but installing UTM with Filza or appinst breaks UTM’s settings in Settings.app and prevents it from being visible in the Files app. I use ReProvision to do it on-device and it doesn’t break any of UTM’s functionality

**Comment by Oliver2213** [comment]
@osy86 I can try that. Altstore does ask about a code execution special permission or something, at least for 2.0 betas, not for 1.0, though 1.0 is the one that works.

**Comment by Oliver2213** [comment]
@osy86 installing 1.0 via filza errors with "failed to verify signature <path >, no code signature found", and I assume 2.0 betas will encounter the same. Haven't tried ReProvision. I'd guess the difference here is that Altstore (and presumably ReProvision) signs.

**Comment by kkk669** [comment]
I can reproduce this error by the following steps.

1. Create a new virtual machine
1. Turn on "Advanced: Bypass configuration and manually specify arguments" in Settings > QEMU
1. Save the settings
1. Run it

However, if I add `-accel` and `tcg,tb-size=32,mirror-rwx=on` to QEMU arguments, it works.

UTM v2.0b5 (installed from an IPA file with Xcode's "Devices and Simulators")
iPadOS 14.2 Developer Beta 2 (18B5061e) (non-jailbroken)

**Comment by osy86** [comment]
Uh that’s not an issue that’s exactly how that feature is designed.
