### ISSUE TITLE
This is important for UTM users!!

### ISSUE THREAD

**Issue by an-iOS-user** [utmapp/UTM#452]
(i dont know the crash log for this)
When you kill UTM DO NOT lock your phone while its loading  but not actually loading. This has frozen my phone and is unable to do ANYTHING!! You have to wait until your phone is out of battery then put it on charge to use it again. This has happened twice now. I do not know if this i something to do with iOS 13 or UTM so i will close this when i have figured it out.

**Comment by an-iOS-user** [comment]
this is real but i cant get video from my phone :(

**Comment by saagarjha** [comment]
You can just restart your device to get out of it, you know

**Comment by an-iOS-user** [comment]
> You can just restart your device to get out of it, you know

Yes I know that but if you lock it while it’s “loading” it makes your phone unusable on iOS. I’ve even tried rebooting with no luck. Nothing. Just able to go to the Notification Center and control center.

**Comment by saagarjha** [comment]
Once you reboot, your phone should be back to normal. Is it not?
