### ISSUE TITLE
4.0.8 qemu-aarch64-softmmu: : drive with bus=0, unit=0 (index=0) exists

### ISSUE THREAD

**Issue by stutiredboy** [utmapp/UTM#4526]
after upgrade from v3.2.4 to v4.0.8, I got this error while I try to boot my virtual machine

> qemu-aarch64-softmmu: : drive with bus=0, unit=0 (index=0) exists

Host: Macbook Air M1
Guest: Windows 11 ARM64

**Comment by osy** [comment]
Please post your vm’s config.plist

**Comment by stutiredboy** [comment]
[config.plist.txt](https://github.com/utmapp/UTM/files/9835051/config.plist.txt)

config.plist. thx.

**Comment by osy** [comment]
You have a drive named “shrink.sh”. You need to remove it as it doesn’t do anything.

**Comment by stutiredboy** [comment]
> You have a drive named “shrink.sh”. You need to remove it as it doesn’t do anything.

it works. thank you @osy
