### ISSUE TITLE
Black screen on launch

### ISSUE THREAD

**Issue by jun-tim** [utmapp/UTM#453]
My device is ios14beta1. I just tested version 2.0. I don't know why it will flash back when I open it. Is it a signature problem? I use @ JS_ John's signature. Let's go back and try it. Is it a code problem? Hope to fix it. Thank you

**Comment by osy86** [comment]
That’s not an issue. I haven’t designed a loading screen yet.

**Comment by Taek-2** [comment]
did you jailbraked?
iOS14 must be jailbroken to run VM

**Comment by DwifteJB** [comment]
Yeah, have you jailbroken or used Xcode? Otherwise it won't work.
