### ISSUE TITLE
Duplicate after creating a new VM

### ISSUE THREAD

**Issue by Ty-programmer** [utmapp/UTM#455]
**Describe the bug**
I create a new blank virtual machine in the normal way and log it. I know that the UTM virtual machine on IOS 14 cannot be allowed to run without prison break or debug. But after the flash back, re open UTM, there are two blank virtual machines, but there is only one UTM file in the folder. When I delete a virtual machine in UTM and try to delete the second virtual machine, it shows that it cannot be deleted. Then I turn off UTM and turn it back on again. The so-called second virtual machine is gone.

![IMG_0136](https://user-images.githubusercontent.com/61855011/93008095-91094680-f5a3-11ea-934f-44469d84bd62.PNG)
![IMG_0137](https://user-images.githubusercontent.com/61855011/93008096-949ccd80-f5a3-11ea-8df5-2e6641ee33e4.PNG)
![IMG_0138](https://user-images.githubusercontent.com/61855011/93008108-b8601380-f5a3-11ea-8029-1b9e19f2566b.PNG)

**To Reproduce**
N/A

**Crash log**
N/A

**Debug log**
[the debug.log](https://github.com/utmapp/UTM/files/5213485/debug.log)

**Upload VM**
N/A

**Comment by cs-sugar** [comment]
This is a bug in IOS 14.

**Comment by yqs-github** [comment]
> This is a bug in IOS 14.

I know , but our task is to fix bugs.
