### ISSUE TITLE
UTM SE crashes while booting Mac OS 9.2.1 from the UTM Gallery

### ISSUE THREAD

**Issue by jaydenridley4** [utmapp/UTM#4559]
**Describe the issue**
A clear and concise description of what the issue is. **BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Configuration (required)**
* UTM Version: SE 4.0.9
* OS Version: 16.1 RC, 15.7 RC
* Device Model: iPhone XS, iPad 9
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? AltStore repository 

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here. [Google Drive link](https://drive.google.com/file/d/15ksOGTKJem7Tw45qjIn7n9qgK5O8SO1O/view?usp=drivesdk) 

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the bottom of the configuration options (or at the top of the `QEMU` page) is `Debug Log`. Turn it on and save the VM. After you experience the issue, quit the VM and re-launch UTM. Open the VM settings again and select `Export Log...` and attach it here. [Google Drive link](https://drive.google.com/file/d/175dtptUdCoCkWVNhNbJRsRupM5eM8oTD/view?usp=drivesdk) 

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since GitHub has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here. It’s Mac OS 9.2.1 from the gallery, untouched

**Comment by Konstantinos395** [comment]
Me to, I try to emulate on my iPad 9th generation it crashes 
 
 Crash Log 
N/A
Debug Log
N/A
Upload VM
From Gallery

**Comment by osy** [comment]
@Konstantinos395 open a new issue with a crash log, this one is outdated

**Comment by Alphonse-kun** [comment]
I am trying to use the prebuilt machine on an iPhone 14 pro, not jailbroken, just using the app store version. And it crashes instantly on startup.
