### ISSUE TITLE
[Feature] Import images or VM from network directly in UTM

### ISSUE THREAD

**Issue by js-john** [utmapp/UTM#456]
A friend of mine said that he can provide VMs download server for UTM. I want to write some code for UTM: when creating a new virtual machine, we can choose to download it from the network, such as the VMs from https://getutm.app/vms

What do you think of this idea?

**Comment by osy86** [comment]
I don’t want to add too much complexity to UTM. You can always download from Safari and open it. I don’t think the app should do downloads.

**Comment by cs-sugar** [comment]
In my opinion, UTM can directly create a virtual machine one click book. You can download the UTM image from the official image station of UTM and other saved third-party servers, and you can choose one key book, that is, you can start the virtual machine directly without complicated configuration.
I think this may be better for Xiaobai.
