### ISSUE TITLE
Mini 4: Slow "Reboot"

### ISSUE THREAD

**Issue by HL52840** [utmapp/UTM#458]
When I "Shut down" with iPadOS's normal shutdown mechanism, it takes a good while to power off, then reboot. It never actually shuts down. Is this intended behavior?

**Comment by osy86** [comment]
Shut down the VM or shut down the iPad?

**Comment by HL52840** [comment]
The tablet itself.

**Comment by osy86** [comment]
You should quit UTM (use the X/Power on the top left) before powering off your iPad.

**Comment by HL52840** [comment]
Ok. I guess I didn't read the documentation fully. Thanks.

**Comment by IIWare** [comment]
yes, this is what happens when you force quit utm while it's in the middle of the process running a vm, and if you start utm right after you force quitted it, force quit it again, and shut down your ipad right after, this happens
