### ISSUE TITLE
QEMU exited with an error:Could not allocate dynamic translator buffer

### ISSUE THREAD

**Issue by none-null-blank** [utmapp/UTM#459]
QEMU exited with an error:Could not allocate dynamic translator buffer
utm version:2.0b2

**Comment by yqs-github** [comment]
Maybe this is a bug of UTM2.0 in the systems less than iOS14

**Comment by IIWare** [comment]
Duplicate of #451

**Comment by osy86** [comment]
True but I’ve confirmed the root cause is different and only seen on jailbroken devices. Next release should address this.

**Comment by IIWare** [comment]
ok now I know it isn't a duplicate
