### ISSUE TITLE
Shared Directories don't work for macOS 12 guests

### ISSUE THREAD

**Issue by mhdhejazi** [utmapp/UTM#4594]
**Describe the issue**  
You can setup shared directories for macOS guests but they don't actually work for macOS 12.

**Configuration**  
* UTM Version: 4.1.0
* macOS Version: 13.0
* Mac Chip (Intel, M1, ...): M1

Upon checking [Apple documentation](https://developer.apple.com/documentation/virtualization/shared_directories), it seems shared directories only work if macOS 13 guests.
<img width="957" alt="image" src="https://user-images.githubusercontent.com/121827/199464418-286af3b1-bb51-4232-b00f-03cea1d4d27b.png">

It'd be less confusing if we can hide the setting for shared directories for macOS < 13 guests.

**Comment by mhdhejazi** [comment]
Follow up question: I was able to share files with the guest macOS using File Sharing (SMB), but it's a relatively slow solution and you can see `smbd` using 100% of the CPU power:
<img width="352" alt="image" src="https://user-images.githubusercontent.com/121827/199466345-5eed8b2c-b297-4d81-92c4-244b3c9b053a.png">

Is there any better/faster solution to share files with the guest macOS?

**Comment by seen76** [comment]
Shared directories are not available for 13.x guests with 12.x hosts, either

**Comment by osy** [comment]
Added clarifying note about macOS guest support. Also added the following documentation page clarifying how shares work: https://docs.getutm.app/guest-support/macos/
