### ISSUE TITLE
Freshly created macOS VM cannot be started

### ISSUE THREAD

**Issue by LostInCompilation** [utmapp/UTM#4595]
**Describe the issue**  
When creating a new macOS VM (virtualization) with no IPSW file provided, after the download completed,  the VM has no name and no possibility to access the settings (image 1). When trying to start the VM, an error appears, saying this VM cannot be run on this machine (image 2).

**Configuration**  
* UTM Version: 4.0.9 (68)
* macOS Version: macOS 13.0
* Mac Chip: M1 Pro

<img width="1001" alt="Screenshot 2022-11-02 at 18 34 23" src="https://user-images.githubusercontent.com/12819635/199570268-b593ce08-337e-4cc5-983f-d95d2e5c595f.png">

<img width="367" alt="Screenshot 2022-11-02 at 19 14 02" src="https://user-images.githubusercontent.com/12819635/199570296-88ab61a5-afa0-4e0f-870e-9b043f636713.png">

**Comment by parrotmac** [comment]
I encountered the same issue using the same CPU and UTM version but on macOS 12.4. After quitting UTM and re-opening it worked -- is that the same for you?

**Comment by LostInCompilation** [comment]
Restarting UTM makes it possible to start the VM and open it's settings. However the VM produces absolutely no display output, just a black screen, no matter how long I wait. I never encountered this behaviour before, something seems very off.

**Comment by okkdev** [comment]
Having the same issue. Error message after creation. Restarted UTM. Now boots into black screen.

I'm on:

- UTM 4.0.9 (68)
- macOS 12.6 (21G115)
- M1 Pro

**Comment by tophermonty73** [comment]
UniversalMac_13.0_22A380_Restore.ipsw (24th October 2022)  results in a black screen. 

UniversalMac_12.6_21G115_Restore.ipsw (12th September 2022) works, but is not the latest os.

**Comment by stephenamills** [comment]
Also having the same issue and error message. Also restarted UTM, and it boots into a black screen.
<img width="1883" alt="image" src="https://user-images.githubusercontent.com/1857804/200383887-27f7b850-e39f-4c05-b238-760dbf5a421d.png”>
(VM is paused; can't screenshot the VM while attempting to run the VM due to it taking over the keyboard shortcut).

- UTM 4.0.9 (68)
- macOS 13.0 (22A380)
- M1

**Comment by okkdev** [comment]
To get a working VM I downgraded to UTM 4.0.1 created a VM and upgraded back to 4.0.9

**Comment by daggerfall** [comment]
Having the same problem here.

**Comment by Ahsan-R-Kazmi** [comment]
I was able to get around this issue. Linking comment from other ticket: https://github.com/utmapp/UTM/discussions/4653#discussioncomment-4126546.
