### ISSUE TITLE
Are there builds available of the macOS app?

### ISSUE THREAD

**Issue by geoff-nixon** [utmapp/UTM#460]
**Describe the bug**
I'm months late to the party here, but are there any released or CI builds of the UTM macOS, or does the phrase "an issue with the macOS app" mean something else entirely?

**Comment by IIWare** [comment]
[here](https://github.com/utmapp/UTM/actions/runs/262203248), works in 11.0 and newer, click on UTM-macos-x86_64, a file will download, extract the xcarchive and go to Products > applications, and click on utm.app

**Comment by brunocastello** [comment]
> [here](https://github.com/utmapp/UTM/actions/runs/262203248), works in mac os 11.0 and newer, click on UTM-macos-x86_64, a file will download, extract the xcarchive and go to Products > applications, and click on utm.app

Does this build have QXL VGA? Even homebrew QEMU for macOS doesn't have it, I was wondering how you or someone managed to compile it. UTM for iOS does have QXL though, I was able to use it with a Windows XP VM there and SPICE Guest Tools once. IMO QXL is the best available option:
1) QXL 2) Cirrus 3) VMWare SVGA II...

**Comment by obbcth** [comment]
> [here](https://github.com/utmapp/UTM/actions/runs/262203248), works in mac os 11.0 and newer, click on UTM-macos-x86_64, a file will download, extract the xcarchive and go to Products > applications, and click on utm.app

Not working on beta 7. Is there any additional commands (or somewhat files) to run UTM?

**Comment by osy86** [comment]
It’s a pain in Catalina and Big Sur to run anything not notarized. But you should be able to do it. Otherwise open Console and see if there’s any error message.
