### ISSUE TITLE
'Export QEMU Command' includes '-spice' flag

### ISSUE THREAD

**Issue by dtpoirot** [utmapp/UTM#4603]
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Describe the issue**  
Selecting 'Edit' then 'QEMU' the 'Export QEMU Command' creates a command line which can not be executed. The available QEMU binary does not include the '-spice' command option:
$ bash < command.txt
qemu-system-x86_64: -spice: invalid option

**Configuration**  
* UTM Version: 4.1.0
* macOS Version: 12.6.1
* Mac Chip (Intel, M1, ...): Intel

**Crash log**  
No crash log 

**Debug log**  
n/a

**Upload VM**  
No reference in config.plist

**Comment by danielpoirot** [comment]
I built the source code and still get the `qemu-system-x86_64: -spice: invalid option` error.

**Comment by dtpoirot** [comment]
ping...

**Comment by osy** [comment]
This is not an error because the command is used for debugging UTM issues. We use a fork of QEMU that does not have the same command line arguments.

**Comment by danielpoirot** [comment]
What is the point of exporting a command line with unsupported switches?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by osy** [comment]
1. Advanced users debugging an QEMU issue can find support online by knowing what options are passed in "under the hood"
2. Advanced users who know how to use QEMU can quickly learn what each of the settings do and how that matches the QEMU behaviour

It is not intended for people to copy and paste into the terminal. In fact it doesn't even make sense to do so. For example, UTM uses SPICE so if it doesn't generate the SPICE options, then it wouldn't work anyways in QEMU.

**Comment by danielpoirot** [comment]
…that being the title of the support request…

It would be handy to be able to use UTM to configure and test general QEMU commands.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by osy** [comment]
Yes that's exactly my point. If you don't generate the `-spice` options, it won't work in QEMU. If you decide to look at the QEMU command, it's up to you to know what options are relevant and what is not. If you don't know this, then this is not the functionality that can help you.

**Comment by danielpoirot** [comment]
I was looking for the ‘headless’ facility that we see in some of the other Type 2 hypervisors.

I don’t see the utility of UTM if I must craft the command line myself.

It is pretty, however.

Best of luck.
