### ISSUE TITLE
MacDevelopment.md has a format error

### ISSUE THREAD

**Issue by danielpoirot** [utmapp/UTM#4606]
**Describe the issue**  
Trying to build UTM. Line breaks are missing in setting up the dependencies on Step 2. 
Steps could possibly be formatted as command lines.

```
Dependencies
  Building Dependencies (Advanced)
    2. Install the following build prerequisites brew install bison pkg-config gettext glib-utils libgpg-error nasm meson pip3 install six 
       pyparsing Make sure to add bison to your $PATH environment variable! export 
       PATH=/usr/local/opt/bison/bin:/opt/homebrew/opt/bison/bin:$PATH
```
Should be:
```
2. Install the following build prerequisites: 
      $ brew install bison pkg-config gettext glib-utils libgpg-error nasm meson 
      $ pip3 install six pyparsing 
   Make sure to add bison to your $PATH environment variable! 
      $ export PATH=/usr/local/opt/bison/bin:/opt/homebrew/opt/bison/bin:$PATH
```

**Configuration**  
* UTM Version: 4.1.0
* macOS Version: 12.6.1
* Mac Chip (Intel, M1, ...): Intel

**Crash log**  
n/a

**Debug log**  
n/a

**Upload VM**  
n/a

**Comment by LostInCompilation** [comment]
The commands are formatted as single line inline code. Looks good to me. Or what did you mean?


<img width="1530" alt="Screenshot 2022-11-03 at 22 02 17" src="https://user-images.githubusercontent.com/12819635/199833506-f717f22d-2c32-4639-8246-8da2cf04acee.png">

**Comment by danielpoirot** [comment]
...not what I see in Chrome when I go to that page.
Screen shot below:
<img width="1046" alt="Screen Shot 2022-11-03 at 4 31 55 PM" src="https://user-images.githubusercontent.com/10454244/199838496-818388be-0428-408d-8f61-8dc0187d6cf8.png">

**Comment by LostInCompilation** [comment]
I made a fix for it and added the ability to directly copy the commands with the copy button.
Check PR #4613
