### ISSUE TITLE
Is iOS supported as a *guest* OS by UTM?

### ISSUE THREAD

**Issue by geoff-nixon** [utmapp/UTM#461]
(Assuming it would take a bit of sleight of hand) but is iOS itself (say, an earlier, no longer signed version) supported as a guest?

Along roughly the same lines, does UTM build/run equally on say, any of the x86 iOS simulators, or under Catalyst?

**Comment by geoff-nixon** [comment]
Perhaps a more specific question would be helpful here; another way to ask the above: does the utmapp spice fork developed for this project support iOS both the client and server?

**Comment by brunocastello** [comment]
Answer to both: No.

**Comment by saagarjha** [comment]
It doesn't out-of-the-box, but I can't imagine why UTM couldn't work in the simulator (although, why would you want to?) and there's a native Mac app in the works. Booting iOS in QEMU takes work but is possible to some extent: https://github.com/alephsecurity/xnu-qemu-arm64
