### ISSUE TITLE
Copying text in OS X with two Apple virtualization VM's running causes UTM to crash

### ISSUE THREAD

**Issue by dwangoac** [utmapp/UTM#4612]
Pressing Cmd+C to copy text in OS X while more than one Apple virtualization VM is open can result in an instant UTM crash.

**Steps to reproduce**
1. Open two Apple virtualization stack VM's
2. Copy text in each of them
3. Copy text in OS X

**Result**
UTM will instantly crash as soon as the copy starts, such as the instant Cmd+C is pressed. The attached crash log includes the following:

```
Crashed Thread:        10  Dispatch queue: com.apple.virtualization.spice-agent
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
```

I can reliably reproduce this crash with two VM's open.

**Configuration** 
UTM Version: 4.0.9 (68)
macOS Version: macOS 13.0 (22A380)
Mac Chip (Intel, M1, ...): M1 Max

**Crash log**  
Attached:
[UTM-2022-11-04-142305.ips.zip](https://github.com/utmapp/UTM/files/9942058/UTM-2022-11-04-142305.ips.zip)

**Comment by osy** [comment]
Filed FB11815988

**Comment by osy** [comment]
Apple fixed this in macOS 14 beta:

> Please verify this issue with macOS 14 beta and update your bug report with your results by logging into https://feedbackassistant.apple.com/ or by using the Feedback Assistant app.
> 
> macOS 14 beta (23A5257q)
> https://developer.apple.com/download/
> Posted Date: June 5, 2023
> 
> If the issue persists, please attach a new sysdiagnose captured in the latest build and attach it to the bug report. Thank you.
