### ISSUE TITLE
Implement Trollstore JIT

### ISSUE THREAD

**Issue by zeroxoneafour** [utmapp/UTM#4624]
IPAs through trollstore can be configured to launch custom binaries, including JITs. This can eliminate the need for Jitterbug or other apps on trollstore-compatible devices. This has already been implemented in PojavLauncher, another app that requires a JIT to run.

[Link to commit that implemented this in PojavLauncher](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/commit/ccaa9416f182dad0bc26832cbec85b799ae47dad)

**Comment by osy** [comment]
It’s already implemented in v4.1.0
