### ISSUE TITLE
SPICE WebDAV Copying is Slow/Unreliable

### ISSUE THREAD

**Issue by wingcomm** [utmapp/UTM#4626]
**Describe the issue**  
Whenever I go to copy/move large numbers of files to/from the WebDAV share created by SPICE tools, some of the files will not copy to/from the folders and the copy dialog freezes for extended periods of time.

**Configuration**  
* UTM Version: 4.0.9 (68)
* macOS Version: 12.6.1
* Mac Chip (Intel, M1, ...): M1 Max

**Comment by osy** [comment]
Unfortunately, WebDAV is not perfect. There needs to be work in the SPICE backend for it to be more stable. I would recommend trying VirtFS as an alternative. (I think on Windows though, you need to install some drivers for it to work).
