### ISSUE TITLE
clipboard does not work with macos 13.1 guest

### ISSUE THREAD

**Issue by seen76** [utmapp/UTM#4635]
**Describe the issue**  
You cannot use clipboard between host and guest

**Configuration**  
* UTM Version: 4.1 BETA
* macOS Version: host: 12.5 guest 13.1
* Mac Chip (Intel, M1, ...): M1

**Comment by atticus-trellix** [comment]
on UTM 4.0.9, macos 13.0 guest, 12.4 host. Can confirm, clipboard sharing is not working. but I was under the impression spice guest tools (which is not available on macos) were required for this. Despite the release notes for 4.0.9 stating that clipboard sharing works with ventura guests now. 

Do you need to update to ventura on the host as well perhaps?

**Comment by seen76** [comment]
Unfortunately, I cannot upgrade the host yet, because of software incompatibilities. I was not aware of the guest tools required, but I indeed read it should work.

**Comment by osy** [comment]
> Despite the release notes for 4.0.9 stating that clipboard sharing works with ventura guests now

The release notes do not say that for 4.0.9. It said that in an earlier beta but was an error and was removed in subsequent release notes. Apple does not provide driver support on macOS even though they support it in the APIs.

**Comment by briskerkazoos** [comment]
As mentioned in https://github.com/utmapp/UTM/issues/3567#issuecomment-2457325281, after two and a half years, it seems that Apple may not be planning to implement shared clipboard support for the Apple Virtualization backend, especially considering that other VM software like Parallels already supports it through their guest tools. Given this, it might be worth considering if UTM could implement its own guest tools to enable this feature.
