### ISSUE TITLE
AppleScript / Shortcut deep integration

### ISSUE THREAD

**Issue by lowrisk75** [utmapp/UTM#4640]
It would be really handy to interact with a VM (outside the call URLX)
especially to connect specific USB devices, start/reboot/clone/backup

**Comment by ideologysec** [comment]
@lowrisk75 v4.1.5 (and several earlier ones) allow for AppleScript control, and `utmcli` is probably workable with Shortcuts.

**Comment by osy** [comment]
Forgot to link to this issue but it has indeed been implemented in 4.1.5

**Comment by lowrisk75** [comment]
that's perfect thank you.
