### ISSUE TITLE
Ctrl+Alt+Del not working (NT4 only?)

### ISSUE THREAD

**Issue by FRtranslator** [utmapp/UTM#4643]
I tried to log in on a Windows NT4 guest (macOS host), but I couldn't go through the "Press Ctrl+Alt+Del to log in" screen.

It used to work on UTM 3.x, but it seems to be broken on all 4.x versions.
I used the same key set as before: ctrl+alt+fn+backspace.

I found a ugly workaround: open the VM backup on UTM 3, apply a registry patch to auto-login, then open the VM back with UTM 4.

This should be checked, unless I've missed something.
FYI, I'm using a French keyboard with a French NT4, I don't know if it is related or not (didn't change since UTM 3.x)

Maybe a feature could be added (it exists in other virtualization/emulation software): the "send" keys, like "send ctrl+alt+del" to guest.

**Comment by conath** [comment]
Can not reproduce this, neither with French, U.S. or German keyboard layout selected in the macOS host. Tested with a Windows XP guest in UTM 4.0.9. 

To be clear, you're pressing the same keys as you were in UTM 3 and it's now not working anymore? Does the keyboard work in the guest, otherwise?

**Comment by FRtranslator** [comment]
Right.

I tested more settings.
It looks like to fix this, I have to disable USB support for NT4 *and* change the capture mouse hotkey.
Then it works.

Thanks @conath for your answer.
