### ISSUE TITLE
single click treated as double click in macos 13.1 guest

### ISSUE THREAD

**Issue by seen76** [utmapp/UTM#4645]
It seems that every 2nd/3rd click is treated as double click in the guest OS, probably a timing issue? is it related to the slipping clock issue? :)

* UTM Version: 4.1.0
* macOS Version: host 12.5, guest 13.1
* Mac Chip (Intel, M1, ...): m1

**Comment by osy** [comment]
I suspect this is an Apple issue. Any way you can testing host 13.x and guest 13.x?

**Comment by seen76** [comment]
you mean apple virtualization issue? unfortunately I cannot test it with a 13.x host yet, I have software which is not updated

**Comment by osy** [comment]
Okay, I will try to test when I have time.

**Comment by osy** [comment]
@seen76 how are you testing this? Are you using a mouse or trackpad? If mouse, is it an apple mouse or a third party mouse?

**Comment by seen76** [comment]
I use the build in track pad. When I click in "Mail" it opens the e-mail, instead of just selecting it 1/2 the time. Also, I have noticed that command key seems to be stuck sometimes, as clicking will not issue a right click but a command+click

**Comment by osy** [comment]
I’m testing by going into Applications directory and trying to single click every icon and see if it double clicks. Can you try that?

**Comment by seen76** [comment]
yea, happens like that as well, the app opens

**Comment by seen76** [comment]
an additional thing, what I have noticed: sometimes its not even double click, but just an additional left click. the effect is that if I right click in the VM by using the pad, it shows the menu and immediately closes it. Sometimes I can only right click 3-4. times

**Comment by osy** [comment]
I am still unable to reproduce this issue. Can you try installing a brand new VM on the latest UTM beta and see if it still happens?

**Comment by seen76** [comment]
i am always up to date on UTM with the releases (using all the beta) and if it was chanced I would have commented it :)

its really easy to reproduce: try to right click on anything in the VM, the menu shows up and disappears immediately, also where i see it a lot is in the mail app: you single click on a mail to read it, and it opens it up

**Comment by osy** [comment]
Like I said that does NOT happen on my M1 MacBook Air.

**Comment by brettp** [comment]
This is also happening to me with both the current stable and beta releases (4.0.9 and 4.1.3) on my M1 MBA on Ventura 13.0.1. Trying to move a window by click-dragging on its title bar causes it to maximize about 1/3 of the time. I also see the same behavior with the right click menu as @seen76 reports.
