### ISSUE TITLE
No optical drive support on macOS guest

### ISSUE THREAD

**Issue by syntien** [utmapp/UTM#4647]
No optical drive support on macOS guest.

* UTM Version: Version 4.0.9 (68)
* macOS Version: Ventura 13.0 (22A380)
* Mac Chip (Intel, M1, ...): M1 Max

There does not seem to be any support in a macOS guest VM for optical drives (e.g., DVD or Blu-Ray). Yikes! Can this be added?

**Comment by DJZSwag** [comment]
Are you using Virtualization or Emulation? I believe the former has no optical support because it's not using QEMU, but Apple's own Virtualization.framework.

**Comment by DJZSwag** [comment]
But then again, it is Apple that made the framework, not the UTM or QEMU devs.

**Comment by syntien** [comment]
Perhaps. I’ll have to look over the API and documentation. These optical drives are USB devices and virtualization without USB support would be a major shortcoming.

**Comment by syntien** [comment]
I found [issue #3778](https://github.com/utmapp/UTM/issues/3778). I will close this.
