### ISSUE TITLE
how  it  config  xml  like  kvm && virt-manager like  linux？

### ISSUE THREAD

**Issue by summer-father** [utmapp/UTM#4649]
Please browse the existing issues and filter by 'enhancement' to make sure this has not already been suggested!
how  it  use  qemu  or  kvm  hypervisor ？  learn  is  possible  like  virt-manager，VMware  GUI easy  ，i  hope

**Comment by conath** [comment]
UTM does not include kvm or virt-manager features. The kvm accelerator is not available on macOS (ARM), and we have a mac-native configuration format (PLIST) which is an XML-like file format. You can locate the `.plist` file for each VM like this: 

> right-click the VM in UTM and choose "Show in Finder". Then right-click the selected file in Finder and choose "Show Package Contents". The config.plist file is now visible
