### ISSUE TITLE
Leopard VM fails to stop

### ISSUE THREAD

**Issue by DJZSwag** [utmapp/UTM#4661]
**Describe the issue**  
So I was installing iLife 09 on a PPC Leopard VM, and thanks to QEMU's insanely low hard drive r/w on macOS, I left my iMac for a couple of hours on. Came back, and the VM froze on the restart page, so I shut down the vm. Nothing, so I closed the window, which should've done the same thing (p.s. What's the difference between shutting down the VM and closing the window?), still nothing. So I brute forced the shutdown by quitting UTM. I made this issue because I also suffered the issue from the past, but never got around to make an issue about it.
**Configuration**  
* UTM Version: 4.1.0 (69)
* macOS Version: 13.1 Beta (22C5033e)
* Mac Chip (Intel, M1, ...):  M1 8 core GPU

**Debug log**  
[debug.log](https://github.com/utmapp/UTM/files/9994774/debug.log)

**Upload VM**  
[config.plist.zip](https://github.com/utmapp/UTM/files/9994776/config.plist.zip)

**Comment by conath** [comment]
Unfortunately can't give any advice on the VM freeze, the log doesn't show any errors. There currently (UTM 4.1) no difference between the power off-button in the toolbar and closing the window. In both cases it's like what happens to a real computer if you hold down the power button until it forcibly shuts off.

A hint regarding performance: you could try and assign two cores to the VM, that is in the VM configuration → System section. Make sure to enable "Force multicore", as well.

**Comment by DJZSwag** [comment]
Damn, that sucks.
