### ISSUE TITLE
Option to disable capturing system keys in macOS VMs

### ISSUE THREAD

**Issue by jtran19** [utmapp/UTM#4667]
**Describe the issue**  
Other issues reporting that capturing keyboard/mouse within the VM is not working.  For me, it's not even an enabled option (see screenshot).  Without this option, global shortcuts like CMD + TAB to switch windows does not work.  

This used to work, and I'm wondering if it was the upgrade from macOS 13 to 13.0.1 that broke it.  I've tried UTM 4.0.7-4.1.0 with the same results.  I've also tried creating a new macOS 13.0.1 VM from scratch (download .ipsw file from Apple).

![Screenshot 2022-11-14 at 10 58 45 AM](https://user-images.githubusercontent.com/1160478/201720614-acf1ed86-e4b1-45fd-b4ad-2537645823c2.png)

**Configuration**  
* UTM Version: 4.0.9 (68)
* macOS Version: 13.0.1
* Mac Chip (Intel, M1, ...): M1 Max

**Comment by DJZSwag** [comment]
You probably don't need it, as the VM auto-captures the mouse when it's in the window.
