### ISSUE TITLE
Add support for 3440x1440 widescreen 21:9 monitors

### ISSUE THREAD

**Issue by Tandolf** [utmapp/UTM#4668]
I love the software, its great, but i usually use UTM with an external widescreen monitor.

Tried out the apple virtualization feature and found out that the widescreen resolution 3440x1440 aspect ratio 21:9 wasn't supported. 

So creating this issue to raise awareness. Will also submit a PR that links to this issue.

Great software, keep up all the great work!

**Comment by Tandolf** [comment]
PR is submitted here #4669

**Comment by bzuruce** [comment]
Install SPICE Guest Tools on your VM. Go to VM settings>Display>Resize display to window size automatically.
Enter Full Screen

**Comment by Tandolf** [comment]
> Install SPICE Guest Tools on your VM. Go to VM settings>Display>Resize display to window size automatically. Enter Full Screen

I already have SPICE guest tools installed, and the settings you are suggesting do not exist when running apple virtualization. They might exist when running QEMU, but im not running QEMU. Please look at my PR.
