### ISSUE TITLE
Interface broken on edit Port Forward

### ISSUE THREAD

**Issue by meteoro** [utmapp/UTM#4690]
**Describe the issue**  
Interface broken, all port forward edit open at same time.

<img width="655" alt="Screenshot 2022-11-17 at 15 48 07" src="https://user-images.githubusercontent.com/1403424/202532888-d97fd908-9df9-4dd7-98e2-a37c18e6ab0d.png">

**Configuration**  
* UTM Version: 4.1.0
* macOS Version: 13.01
* Mac Chip (Intel, M1, ...): Intel 

**Crash log**  
N/A

**Debug log**  
N/A

**Upload VM**  
N/A

**Comment by freebrowser1** [comment]
Same issue here, using UTM 4.09 and macOS 13 Ventura.



<img width="501" alt="Screenshot 2022-11-18 at 13 25 34" src="https://user-images.githubusercontent.com/26625141/202706195-ecd4f45a-779a-4e79-818c-eed20fab9720.png">
<img width="464" alt="Screenshot 2022-11-18 at 13 27 40" src="https://user-images.githubusercontent.com/26625141/202706204-fe42238a-c2b4-4c13-95ed-7f1189180b11.png">
<img width="594" alt="Screenshot 2022-11-18 at 13 27 55" src="https://user-images.githubusercontent.com/26625141/202706206-41193718-fc59-4b5f-9edf-e4e155707eef.png">
