### ISSUE TITLE
UTM Crashes When Launching x86_64 VMs

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [utmapp/UTM#47]
Device: iPad Pro (10.5-inch)
Operating System: iPadOS 13.4 Developer Beta
UTM Versions: This occurs with both [the ipa file in the releases page](https://github.com/utmapp/UTM/releases/tag/v0.1) and the [latest built Xcode archive](https://github.com/utmapp/UTM/actions/runs/43771553)

Steps to reproduce:
1. Install UTM using Cydia Impactor with my paid Apple Developer account.
2. Launch it and add a VM with x86_64 architecture.
3. Launch the VM and enjoy the crash.

The log is attached below.

[UTM-2020-02-23-184743.txt](https://github.com/utmapp/UTM/files/4241196/UTM-2020-02-23-184743.txt)

**Comment by qpomelo** [comment]
Exactly the same bug occurs here on my iPhone 7 which is running iOS 13.3.1. A log is attached below.
[Crash.log](https://github.com/utmapp/UTM/files/4241211/Crash.log)

**Comment by CaptainYukinoshitaHachiman** [comment]
This would be fixed by using other means of installation.
