### ISSUE TITLE
VM Freezed Randomly

### ISSUE THREAD

**Issue by ImLoadingUuU** [utmapp/UTM#4739]
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Describe the issue**  
VM Sometimes Freezed Randomly (Linux) I think its not System Problem.
I Tried Ubuntu Desktop,Server. It Freeze Randomly too
**Configuration**  
* UTM Version: 4.1.0(69)
* macOS Version: Ventura 13.1
* Mac Chip (Intel, M1, ...): M1

**Crash log**  
If the app crashed, you need a crash log. To get your crash log, open Console.app, go to `Crash Reports`, and find the latest entry for either UTM, QEMU, QEMUHelper, or qemu-\*. Right click and choose `Reveal in Finder`. Attach the report here.

**Debug log**  
For all issues related to running a VM, _including_ crashes, you should attach a debug log. (This is unavailable for macOS-on-macOS VMs. Attach an excerpt of your system log instead.)
To get the Debug log: open UTM, and open the settings for the VM you wish to launch. Near the top of the `QEMU` page is `Debug Log`. Turn it on and save the VM. After you experience the issue, open the VM settings again and select `Export Log...` and attach it here.

**Upload VM**  
If your issue is related to a specific VM, please upload the config.plist from your VM's .utm directory. To get this, right-click the VM in UTM and choose "Show in Finder". Then right-click the selected file in Finder and choose "Show Package Contents". The config.plist file is now visible. Right-click it and choose "Compress". Attach the resulting config.plist.zip file here.
You can upload the entire .utm if needed, but note this includes your VM's drive image and may contain personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by RipperSK** [comment]
This keeps happening to me too - please reopen. Seems more people report this even recently: https://forums.macrumors.com/threads/utm-virtualisation-of-ubuntu-20-04-randomly-freezes-on-apple-silicon-m2.2388950/

attaching debug log:
[debug-2023-11-22.log](https://github.com/utmapp/UTM/files/13433361/debug-2023-11-22.log)

it happens with virtio-ramfb-gl but also with virtio-ramfb settings.

some odd debug messages:

```
(qemu-aarch64-softmmu:88332): Spice-DEBUG: 04:47:25.229: ../server/reds.c:1232:reds_on_main_agent_monitors_config: monitors_config->num_of_monitors: 16

...
2023-11-22 04:48:20,947 DEBUG GSpice-../src/channel-port.c:232 port-10:1: port event: 1
QMP disconnected
```

I'm reporting intermittent freezes on Debian Linux running on QEMU7.2 ARM (aarch64) .

The freeze time is somewhere from 1 second to 5 seconds at a time. For me this started after upgrading from Debian11 to Debian12 - I've looked on the OS directly - could not find anything. This seems to be related to the Virtualization on the UTM.
