### ISSUE TITLE
Crash in NSPasteboard

### ISSUE THREAD

**Issue by osy** [utmapp/UTM#4745]
Hi UTM crashed unexpectedly and interrupted a workflow. The crash log (attached) looks similar to this one though I can't know for sure whether it's the same. Is it? Do you have an expected solution or update to resolve? Thank you!

[UTM_crash_log_12-1-22.txt](https://github.com/utmapp/UTM/files/10135361/UTM_crash_log_12-1-22.txt)

Configuration:

UTM Version: 4.0.9
OS Version: 11.6
Apple M1

_Originally posted by @zachyf in https://github.com/utmapp/UTM/issues/4135#issuecomment-1334207685_

**Comment by osy** [comment]
@zachyf Please provide more details on what you were doing when the crash happened. Did you copy/paste something (or Cmd+C on something)?

**Comment by zachyf** [comment]
Hi thank you for directing the issue to the right place. I'll open a new issue next time. 

I was not actively using the machine. I left a VM running with caffeine so that a different script could listen for input, and I checked on it almost a day later to discover the crash.

**Comment by zachyf** [comment]
One more crash log attached similarly arising from leaving the application running. 
[UTM_crashlog_12-2-22_2.txt](https://github.com/utmapp/UTM/files/10145214/UTM_crashlog_12-2-22_2.txt)
