### ISSUE TITLE
Slow disk performance when using Apple Virtualization and Ubuntu 22.10, latency ?

### ISSUE THREAD

**Issue by sokurenko** [utmapp/UTM#4748]
Slow disk performance when using Apple Virtualization and Ubuntu 22.10

**Configuration**  
* UTM Version: 4.1.0
* macOS Version: 13.0.1
* Mac Chip  M1

This one is when using Apple Virtualization 
time dd if=/dev/zero of=/tmp/test2.img bs=512 count=1000 oflag=dsync
1000+0 records in
1000+0 records out
512000 bytes (512 kB, 500 KiB) copied, 11.4724 s, 44.6 kB/s

real	0m11.475s
user	0m0.018s
sys	0m0.161s

This one is when using Qemu
time dd if=/dev/zero of=/tmp/test2.img bs=512 count=1000 oflag=dsync
1000+0 records in
1000+0 records out
512000 bytes (512 kB, 500 KiB) copied, 0.828362 s, 618 kB/s

real	0m0.831s
user	0m0.000s
sys	0m0.035s

**Comment by sokurenko** [comment]
Same issue on Debian:
Linux debian 5.10.0-19-arm64 #1 SMP Debian 5.10.149-2 (2022-10-21) aarch64 GNU/Linux
vso@debian:~$ time dd if=/dev/zero of=/tmp/test2.img bs=512 count=1000 oflag=dsync
1000+0 records in
1000+0 records out
512000 bytes (512 kB, 500 KiB) copied, 12.2398 s, 41.8 kB/s

real	0m12.242s
user	0m0.009s
sys	0m0.291s

**Comment by OmgDef** [comment]
Same issue on Ubuntu 22.04 
Configuration:
UTM Version: 4.0.9
macOS Version: 13.1
Mac Chip M1

**Comment by sokurenko** [comment]
I don't experience issue anymore, something has been fixed
