### ISSUE TITLE
Import button in v2.0b3 doesn’t work

### ISSUE THREAD

**Issue by rylyguy** [utmapp/UTM#475]
When pressing the import drive button nothing happens. 

Steps to reproduce 
1.Install via tethered launch method
2.launch utm from macOS terminal 
3.click +
4.go to drives 
5.press the import button

**Comment by cs-sugar** [comment]
Well, this should be a bug that makes it unrecognizable.

**Comment by rylyguy** [comment]
> Well, this should be a bug that makes it unrecognizable.

What do you mean by that
