### ISSUE TITLE
Offline user manual

### ISSUE THREAD

**Issue by ty-yqs** [utmapp/UTM#477]
We can write an offline HTML page on the home page for users to get guidance. In some countries or regions, if you link directly to _getutm.app_ , the loading speed is too slow.

**Comment by osy86** [comment]
Where would this HTML be hosted if not on getutm.app?

**Comment by yqs-github** [comment]
> Where would this HTML be hosted if not on getutm.app?

We can save the HTML web page on the device, and update the webpage every time we update the UTM

**Comment by yqs-github** [comment]
Changing the path to the path of the device is equivalent to loading a web page on your own device

**Comment by yqs-github** [comment]
[host.zip](https://github.com/utmapp/UTM/files/5320807/host.zip)

**Comment by saagarjha** [comment]
Have you considered saving the page as a web archive or similar, or perhaps using a local caching service?

**Comment by yqs-github** [comment]
> Have you considered saving the page as a web archive or similar, or perhaps using a local caching service?

I don't know how to open the web archive on iOS devices , But I think we can cache the HTML in the iOS services.
s

**Comment by ThatsNiceGuy** [comment]
why not just store the user guide in UTM’s app container (not data container) and call it with Quick Look if needed? Although I’m not sure the latter can be done on stock iOS

**Comment by Ty-programmer** [comment]
> why not just store the user guide as HTML in UTM’s app container (not data container) and call it with Quick Look if needed? Although I’m not sure the latter can be done on stock iOS

That's a good idea.

**Comment by Ty-programmer** [comment]
I think we have two ways. The first is to open the port of the device to add a website service. The second way is to save the HTML in UTM directory and load the HTML with _WebView_ . I think the second way is simpler and more feasible.

**Comment by itselijahciali** [comment]
> why not just store the user guide as HTML in UTM’s app container (not data container) and call it with Quick Look if needed? Although I’m not sure the latter can be done on stock iOS

Would a WebView work in this case? I think that might be better for the user since it has more navigation functionality.

**Comment by ThatsNiceGuy** [comment]
Yea that'd be much better but I'm still not too sure if you can call files located inside the application's app container (not the data container) on stock iOS. Anyway since UTM is likely to become a jailbreak app, this likely won't matter for us. Another method would be to implement a user guide inside the application with the native UI, as in not using any html file and instead having it be an actual part of the app

**Comment by osy** [comment]
With the new design, the hope is we don't "need" a user guide. If things are confusing, we should improve the UI rather than take Microsoft's example of just attaching a large manual to every app.
