### ISSUE TITLE
Add support for 3840x2560 3:2 monitor

### ISSUE THREAD

**Issue by mapleloop** [utmapp/UTM#4773]
Similar to https://github.com/utmapp/UTM/issues/4668 I want to add an additional monitor resolution to the Apple Hypervisor.

In file: https://github.com/utmapp/UTM/blob/main/Platform/macOS/VMConfigAppleDisplayView.swift
Just add the additional NamedResolution to resolutions list
NamedResolution(name: "3840 × 2560 — 4K+ 3:2", resolution: Resolution(width: 3840, height: 2560))

**Comment by osy** [comment]
Added support for custom resolutions in https://github.com/utmapp/UTM/commit/3a79d06f729fff7b55d58e145a93a936530128e6
