### ISSUE TITLE
French translation update for UTM 4.1.1

### ISSUE THREAD

**Issue by FRtranslator** [utmapp/UTM#4775]
Hi,

Updated French localization for UTM 4.1.1:
[UTM-french.zip](https://github.com/utmapp/UTM/files/10175168/UTM-french.zip)

**Comment by FRtranslator** [comment]
@osy You forgot to update the French localization in 4.1.2 ;)
If you prefer any other way to send you the updates, please tell me.

**Comment by osy** [comment]
Yes I forgot since everyone else sends pull requests which is the preferred way. I’ll make sure to include it in the next update.
