### ISSUE TITLE
Bug in Beta | Can't create vm's on v4.1.X from the main menu

### ISSUE THREAD

**Issue by DevCoud18** [utmapp/UTM#4776]
**Describe the issue**
If i want to create a new vm from the main menu the button won't works. Versions v4.1.X are affected
**Configuration (required)**

* UTM Version: v4.1.X
* OS Version: iPadOS 14/ iOS 14
* Device Model: iPad Pro 2020 and iPhone 8 Plus
* Is it jailbroken (name jailbreak used)? Non-Jailbreak
* How did you install UTM? TrollStore

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here.

N/A

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the bottom of the configuration options (or at the top of the `QEMU` page) is `Debug Log`. Turn it on and save the VM. After you experience the issue, quit the VM and re-launch UTM. Open the VM settings again and select `Export Log...` and attach it here.

N/A

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since GitHub has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

N/A

**Comment by osy** [comment]
@DevCoud18 I am am unable to reproduce this on a iOS 14.5 simulator. Can you provide more information? What specific iOS version are you testing on? Can you attach a screen recording of the issue? Thanks

**Comment by osy** [comment]
Okay I was able to reproduce on a 14.0.1 simulator.

**Comment by DevCoud18** [comment]
> @DevCoud18 I am am unable to reproduce this on a iOS 14.5 simulator. Can you provide more information? What specific iOS version are you testing on? Can you attach a screen recording of the issue? Does the function work on older versions of UTM? Thanks

I'm on iPad v14.0.1 and iPhone v14.4. I have tested both betas. The non-betas works, only the betas are affected by me.
