### ISSUE TITLE
Name of shared folder changed from "shared" to "share"

### ISSUE THREAD

**Issue by lelegard** [utmapp/UTM#4801]
**Describe the issue**  
On a Ubuntu VM, in UTM configuration, I declare a shared folder the name of which is `shared` (a subdirectory of my home directory in the macOS host). In the Ubuntu guest, the name of the device becomes `share`, without the trailing `d`.

Is this intended?

**Configuration**  
* UTM Version: UTM 4.0.9 (68)
* macOS Version: 13.1
* Mac Chip (Intel, M1, ...): M1 

In the UTM settings for the VM, we see this (UI in French, sorry, but we clearly see the name "shared"):
![image](https://user-images.githubusercontent.com/5641922/207574376-b05ab3ab-6e16-43a6-83dc-92c582f0c7c6.png)

I try to mount it in the guest:
~~~
# mkdir /shared
# mount -t 9p -o trans=virtio -o version=9p2000.L shared /shared
mount: /shared: special device shared does not exist.
       dmesg(1) may have more information after failed mount system call.
# dmesg
...
[  345.016441] 9p: Installing v9fs 9p2000 file system support
[  345.016827] 9pnet_virtio: no channels available for device shared
#
~~~
The mount message "special device shared does not exist" may indicate that the definition of the shared folder was not passed to the VM. In the qemu command, as generated by UTM, the related options are:
~~~
  -fsdev local,id=virtfs0,path=/Users/lelegard/shared,security_model=mapped-xattr
  -device virtio-9p-pci,fsdev=virtfs0,mount_tag=share
~~~
Note the `mount_tag=share`.

Using the name `share` instead of `shared` works:
~~~
# mount -t 9p -o trans=virtio -o version=9p2000.L share /shared
# mount | grep share
share on /shared type 9p (rw,relatime,sync,dirsync,access=client,trans=virtio)
#
~~~

This issue is not severe because a workaround is obvious. But it took time to identify the difference between `shared` and `share`. This may be a valid behaviour but some explanations would be welcome.

**Comment by lelegard** [comment]
After several tests, it seems that UTM can only declare one single shared folder and that the mount tag is always named `share`, regardless of the original directory name on the host.

I was confused by the name of my shared directory, named `shared`, for which `share` seems to be a truncated version.

I was used to other hypervisors such as VirtualBox or Parallels where you can define multiple shared folders and the name of the corresponding "device" in the guest is, by default, the name of the original directory.

You may close this issue if there is no other useful information to provide.

**Comment by osy** [comment]
Right, the name will always be "share". I thought that allowing the name to be changed would be more confusing because a) if there's spaces in the name what happens to the share? and b) the name of the tag doesn't matter much because when you are mounting it you specify the mount point on the VM.

**Comment by lelegard** [comment]
Thanks @osy for the answer. With only one possible shared folder, using a hard-coded name makes sense. And "only one possible" is not a real limitation since all my VM's on VirtualBox and Parallels have only one shared folder anyway, despite the possibility to have more.

**Comment by abulka** [comment]
Seems all my many shared directories are within my one mounted volume `sudo mount -t virtiofs share /Volumes/stuff`.

**Comment by ckujau** [comment]
Interesting, I had assumed that the share name is the shortname that's displayed in the UI, i.e. the last part of the path name. But it's even [documented](https://docs.getutm.app/guest-support/linux/#virtfs "Guest Support Linux: VirtFS") to be _literally_ `share`:

> Note: share is the name UTM uses for the VirtIO device and you should not change it. 

Surprisingly, the share is configured in `com.utmapp.UTM.plist`, and not in `config.plist` of the VM:

```
$ plutil -p ~/Library/Containers/com.utmapp.UTM/Data/Library/Preferences/com.utmapp.UTM.plist | grep -A5 SharedDirectories
      "SharedDirectories" => [
        0 => {
          "Bookmark" => {length = 764, bytes = 0x626f6f6b fc020000 00000410 30000000 ... 04000000 00000000 }
          "Path" => "/Users/christian/Downloads/"
          "ReadOnly" => 0
        }
```

**Comment by naveenrajm7** [comment]
> Surprisingly, the share is configured in `com.utmapp.UTM.plist`, and not in `config.plist` of the VM:

You are right. The shared folder is part of the VM config that is not saved to disk i,e config.plist of the VM. 
It is part of the registry that UTM maintains for each VM, to store bookmarks for file permissions of directory or drive paths, these config are the ones you see in `com.utmapp.UTM.plist`. The registry entry is necessary for qemu to access these files when used in its arguments. 

`share` is the id used by UTM for the single directory share that it allows through the UI. 

By updating UTM VM registry and using unique share ids , you can achieve multiple shared directories. 
PR https://github.com/utmapp/UTM/pull/6977 is a proposal to allow user to do that via scripting.
