### ISSUE TITLE
Connecting audio from linux guest to host bluetooth headphones also enables microphone by default

### ISSUE THREAD

**Issue by Lovelaces** [utmapp/UTM#4807]
**Configuration (required)**
* UTM Version: 4.1.1
* OS Version: iPadOS 15.3.1
* Device Model: iPad Pro 11" 3rd generation (M1) - MHMV3LL/A 
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? Trollstore

When virtualizing Ubuntu desktop 20.04.5 LTS (ARMv8/AArch64), any audio sent from the guest to my bluetooth headphone coincides with activation of the headphone's microphone as well, which produces a loud and unadjustable "BING" sound, each time. Even if the microphone is disabled for UTM in settings (Settings > Privacy > Microphone > UTM), the function ignores the denied microphone access and does the same thing ("BING").

I tried using `pavucontrol` on Ubuntu and adjusting the volume configuration to see if I can disable the microphone and only get audio. However, the Analog Duplex/Output/Input setting creates no differences while the Off setting turns off audio completely.

All in all, could there perhaps be a way to differentiate between an "only receiving audio" and a "receiving audio along with microphone enabled" setting when using a bluetooth headphone as a listening device on UTM Ubuntu guest? Thanks!

**Comment by osy** [comment]
Does the setting "Prefer device to external microphone" do anything?

**Comment by claudeLovelace** [comment]
Enabling that setting seems to fixed the issue. Thanks!!

**Comment by Lovelaces** [comment]
Enabling that setting seems to fixed the issue. Thanks! Could you elaborate on the mechanism of that setting?
