### ISSUE TITLE
Suggestion: just add a cli mode,

### ISSUE THREAD

**Issue by demhademha** [utmapp/UTM#481]
So we have [ish](https://ish.app) which is quite slow, could you add a utm feature  that would specifically only allow cli? This would also allow emulation of x86_64, rather than ish's x86_32. 
Thanks.

**Comment by IIWare** [comment]
I heard that UTM already has CLI mode, I will check if it has CLI.

**Comment by demhademha** [comment]
Thanks

**Comment by demhademha** [comment]
@osy86  you closed this,but didn't link to the duplicate question.

**Comment by osy86** [comment]
As others stated, it's an existing feature. Read the user guide or something.

**Comment by gagarine** [comment]
Can someone add a link. Thanks. I try to access the UTM's QEMU embedded binary in CLI so I can convert an image. Didn't find the "user guide or somethings", to my defence UTM (3 letters) is not easy to google.

(@osy life is too short for this kind of low value)

**Comment by osy** [comment]
This was 2 years ago and was a very different project. There's no way to add a CLI mode to an App Store sandboxed app.
