### ISSUE TITLE
Multiple entries in VM list show up when cloning fails

### ISSUE THREAD

**Issue by ktprograms** [utmapp/UTM#4815]
**Describe the issue**  
Due to an earlier crash, one of my VMs (call it `A.utm`) got moved to `A 2.utm` (but it's still called `A` in the VM list). When I now try to clone `A`, I got an error that it couldn't be moved since `A 2.utm` already exists. After that (I did it again to see if it was a fluke), I now have 2 more VMs called `A` in the VM list.

**Configuration**  
* UTM Version: 4.0.9
* macOS Version: 12.5.1
* Mac Chip (Intel, M1, ...): M1

**Comment by ktprograms** [comment]
I also had this similar thing happen a different way:
I cloned a VM, and after that both have the same name. I then clicked edit on the clone, but didn't change the name. Then, I either clicked cancel or save (can't remember which) and it gave an error that "<vm-name> 2.utm" couldn't be created as it already exists, and then after quitting and reopening the app I had three VMs (seemingly one "ghost" vm from the failed save)

**Comment by osy** [comment]
Forgot to close it with https://github.com/utmapp/UTM/commit/05bb6d3546e256a46a7549136023c1040bac1a66

**Comment by ktprograms** [comment]
Thanks, will test this with the next release.

**Comment by ktprograms** [comment]
Yeah, seems to correctly use the "- 2" name in the UI.
