### ISSUE TITLE
`utmctl help attach` fails with an ArgumentParser error

### ISSUE THREAD

**Issue by jrjsmrtn** [utmapp/UTM#4817]
**Describe the issue**  
`utmctl help attach` fails with an ArgumentParser error. All other help pages do work correctly.

**Configuration**  
* UTM Version: 4.1.2
* macOS Version: 13.1
* Mac Chip (Intel, M1, ...): M1

**Crash log**  
```sh
$ utmctl help attach
ArgumentParser/Parsed.swift:59: Fatal error: Trying to get the argument set from a resolved/parsed property.
Trace/BPT trap: 5
```

**Comment by ktprograms** [comment]
@osy it seems to be because of the `init()` block for Attach. Removing it fixes the crash.
