### ISSUE TITLE
Cannot Delete Virtual Hard Drives

### ISSUE THREAD

**Issue by Denisxiang** [utmapp/UTM#4821]
**Describe the issue.** 
I can not delete a virtual hard disk, every time I hit delete, it does nothing

**MacBook Air (M1, Late 2020)**  
* UTM Version: 4.1.2
* macOS Version: 13.1
* Mac Chip (Intel, M1, ...): M1

https://user-images.githubusercontent.com/94837981/208292466-02a35a51-9454-45b1-8d39-9ee7907d4e52.mov

**Comment by osy** [comment]
I'm unable to reproduce the issue. Do you still get this after restarting UTM?

**Comment by Denisxiang** [comment]
Uploading Screen Recording 2022-12-29 at 1.51.00 pm.mov…

Sadly, it still does nothing @osy

**Comment by Denisxiang** [comment]
Maybe we might have to remove the are you sure you want to delete the drive dialogue and do a one-click removal

**Comment by osy** [comment]
We would be going in circles.... #4687

I'm still not sure why it's not working for you but it works for me. What if you right click the drive on the sidebar and choose delete?

**Comment by Denisxiang** [comment]
https://user-images.githubusercontent.com/94837981/209902586-73eab881-b15a-4a5e-8f51-5d848a644e53.mov

**Comment by osy** [comment]
Are you using an external mouse or the trackpad?

**Comment by Denisxiang** [comment]
trackpad

**Comment by Denisxiang** [comment]
I am using the trackpad

**Comment by Denisxiang** [comment]
I also tried an external mouse and it does the same thing

**Comment by Denisxiang** [comment]
no matter what method I try @osy, it just will not show up a confirmation dialogue for me saying if I want to remove the drive

**Comment by Denisxiang** [comment]
Ok so, it has been two days since the last comment, so now I want to update on this issue, I tried hard resetting my computer back to factory settings, reinstalled UTM and now the delete button now works

https://user-images.githubusercontent.com/94837981/210125309-17fc33ce-ab66-4560-b215-cc84e5873434.mov
