### ISSUE TITLE
Auto capture mouse on Windows 11 VMs

### ISSUE THREAD

**Issue by GoonerBrian** [utmapp/UTM#4830]
I have both a Ubuntu and a Windows 11 VM. I've noticed that my mouse is auto-captured in the Ubuntu VM but not my Windows 11 VM. It would be really nice if auto-capture worked on the Windows 11 VM too. I've searched for solutions online but really haven't come across anything that even mentions this for UTM. I'm aware of the control+option shortcut but I think it would be better for this to preform the same across each VM.

**Comment by LostInCompilation** [comment]
Please don't. Auto capture is the most annoying option ever. I constantly work with my VM and host in parallel. The current function that the mouse and keyboard get forwarded to the VM when the VM window has focus is a great solution, no need to capture the mouse and loose the ability to quickly switch to the host by just moving the mouse.

**Comment by GoonerBrian** [comment]
> Please don't. Auto capture is the most annoying option ever. I constantly work with my VM and host in parallel. The current function that the mouse and keyboard get forwarded to the VM when the VM window has focus is a great solution, no need to capture the mouse and loose the ability to quickly switch to the host by just moving the mouse.

Perhaps I used the wrong terminology. If I'm understanding you correctly, mouse and keyboard forwarding does work ideally for my Linux VM. (No additionally steps are needed to switch between host/guest. Just click the desired environment that the user wants to work in.) I created this issue to ask that the same thing happens when working in my Windows VM. If this is a settings/configuration issue, please let me know how I can change this. I would then update this issue to just a matter of updating the documentation to make this information more accessible.

**Comment by LostInCompilation** [comment]
OK there was a misunderstanding.
However I cannot confirm your issue. I can use the mouse and keyboard seamlessly on Windows too (Win11 ARM and Win10 x86/64). Under input I selected USB3 (XHCI) and have USB sharing enabled.

**Comment by GoonerBrian** [comment]
Closing issue. Apparently all I needed to do was reinstall spice-guest-tools and the mouse issue was resolved. I should've thought of that earlier. I installed all my VMs several months ago, had to give my MacBook to my son to use, and am just now getting it back. So, I completely forgot spice-guest-tools was a thing.
