### ISSUE TITLE
iPhone - Stretch Screen

### ISSUE THREAD

**Issue by upintheairsheep** [utmapp/UTM#4835]
Please browse the existing issues and filter by 'enhancement' to make sure this has not already been suggested!
Please make an option to stretch and zoom the emulator to fit the iPhone screen on various GUIs. It would be useful for porting Android to iPhones and making it feel like an Android device.

**Comment by osy** [comment]
This is already a feature. Option 5 https://docs.getutm.app/basics/controls/
