### ISSUE TITLE
Add current UTM version to website download page

### ISSUE THREAD

**Issue by LostInCompilation** [utmapp/UTM#4837]
The current UTM version is no where to be found. Not in the GitHub ReadMe nor on the UTM website under downloads. There is no easy way to check if a newer version got released.
At least adding the current version info to the download button would be very helpful.
Clicking on "Changes" just leads to an outdated page which stopped at V4.0.

<img width="1369" alt="Screenshot 2022-12-23 at 16 30 54" src="https://user-images.githubusercontent.com/12819635/209360623-08017c2b-c678-44ee-923f-cf0f9b4e11b0.png">

**Comment by osy** [comment]
It’s not outdated the latest version is 4.0.9. The beta releases are not listed on purpose… because they’re not stable.

**Comment by LostInCompilation** [comment]
Yes I know. But when V4.1 will get released, there is no place to see that a new version got released.

**Comment by osy** [comment]
Oh do you’re asking about #3378

**Comment by LostInCompilation** [comment]
#3378 would be the ultimate solution, but it seems like this is not planned in the near future.

I'm asking for a small text on the UTM websites download page, which displays what version you'll download. Or just any small version string anywhere, to see which version is the current version.
Either in the GitHub readme (Current version: VX.X.X), or the download page (Next to the download button for example: Download (VX.X.X)).
There is just no way to see, what the current version is.
