### ISSUE TITLE
Can't mount read-only ISOs

### ISSUE THREAD

**Issue by winterqt** [utmapp/UTM#4838]
**Describe the issue**  

When creating a VM, and the selected ISO is read-only, the VM fails to start, saying that it can't open the file. The image is by nature read-only anyways, so it doesn't make much sense to enforce that the file is writable (unless it's a QEMU thing).

**Configuration**  
* UTM Version: 4.0.9
* macOS Version: 13.1
* Mac Chip (Intel, M1, ...): M1

To reproduce:
1. `chmod -r path/to/iso`
2. Try to create a new VM and run it, using `path/to/iso` as the ISO image

**Comment by HarryVasanth** [comment]
👍 Bump: 
I have the same issue as well while mounting the `.iso` image from a read-only NFS share.

**Comment by vaynewoo** [comment]
utm
