### ISSUE TITLE
Enable QEMU support for more than 8 cores in HVF

### ISSUE THREAD

**Issue by osy** [utmapp/UTM#4847]
The QEMU issue to track GICv3 support which would enable -smp > 8 is this: https://gitlab.com/qemu-project/qemu/-/issues/743. I would appreciate Tested-by / Reviewed-by tags on the mailing list to push it forward :).

_Originally posted by @agraf in https://github.com/utmapp/UTM/issues/3180#issuecomment-1366146213_

**Comment by agraf** [comment]
Awesome. If you also want Windows support with GICv3, you'll need the following on top: https://patchwork.kernel.org/project/qemu-devel/list/?series=706704. Again, upstream comments / tags appreciated.
