### ISSUE TITLE
Beta 2.0b5 on IOS 13 crashing instantly after white screen

### ISSUE THREAD

**Issue by Krummer** [utmapp/UTM#485]
I have installed 2.0b5 on my 2020 iPad Pro 12.9 with iOS 13.7 using AltStore.  Once installed and signed the app crashes immediately during load.  Since the app will not load I cannot enable the debug log to provide.  Version 1.0 loads without issue as a comparison.  2.0Betas have stopped loading and displaying this issue on my device since 2.0b3.

During installation through Altsore i have allowed the dynamic code signing.

**Comment by IIWare** [comment]
where's the log?

**Comment by IIWare** [comment]
ok then you can't get the log and I couldn't find any solutions, just wait for the bug to be fixed in UTM v2.0b6, I wish I could help but you couldn't get a log.

**Comment by osy86** [comment]
@Krummer from the issue template you didn’t follow

> If the app crashed, you need a crash log. To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here.

Please do this.

**Comment by osy86** [comment]
Is your iPad jailbroken?

**Comment by Krummer** [comment]
Good evening.  No I am. It currently jailbroken.

**Comment by osy86** [comment]
Instead of using altstore can you try installing the IPA directly?

**Comment by Krummer** [comment]
Signing and installing using Xcode was successful!  I am guessing that points to an issue using AltStore as the signer.  Thank you so much for the help!

A quick test of my VM shows that Right Click with magic keyboard is not registering (On Screen works) and Networking is not working.  Could that be a result if how I signed or simply bugs to report?

**Comment by ThatsNiceGuy** [comment]
Right click with trackpads (I use a Magic Trackpad 2) is extremely spotty for me and as for networking, check the OS has drivers built in for the network card you chose.
