### ISSUE TITLE
Install Windows guest tools option shown in CD icon menu from toolbar on Linux VM

### ISSUE THREAD

**Issue by ktprograms** [utmapp/UTM#4854]
**Describe the issue**  
On my Linux VM, when I click the CD icon in the window's toolbar, there's an option for "Install Windows Guest Tools" along with the actual CD drive that's attached.

**Configuration**  
* UTM Version: 4.1.3
* macOS Version: 12.5.1
* Mac Chip (Intel, M1, ...): M1

**Comment by osy** [comment]
Yes that’s why it says “Windows”. It’s not possible to identify what OS you’re running in a consistent way.

**Comment by ktprograms** [comment]
Oh, I see. I assumed it could hide it based on which OS was selected in the Wizard.

**Comment by osy** [comment]
That information isn't saved anywheres. Besides, what if you choose Windows and then mounted a Linux ISO?

**Comment by ktprograms** [comment]
I see, makes sense.
