### ISSUE TITLE
Emulation stopped working

### ISSUE THREAD

**Issue by Delamcode** [utmapp/UTM#4859]
**Describe the issue**
On the newest version (4.1.3) emulation and jit is not supported through trollstore. It was in a previous version (I think it was 4.1.1) but after upgrading it stopped working and gave me an alert.

**Configuration (required)**
* UTM Version: 4.1.3
* OS Version: 15.5b4
* Device Model: iPad Air 5
* Is it jailbroken (name jailbreak used)? No (TS)
* How did you install UTM? TrollStore 

**Crash log**
n/a

**Debug log**
n/a

**Upload VM**
n/a

**Comment by osy** [comment]
It’s been fixed in https://github.com/utmapp/UTM/commit/cd77a5ef0611faaadc6144066773e57af6903ae7
