### ISSUE TITLE
Support pausing with GPU accelerated display devices

### ISSUE THREAD

**Issue by LostInCompilation** [utmapp/UTM#4870]
Is it planned to support VM pausing with GPU display devices? Currently pausing using them only results in an error stating this is not supported.

**Comment by osy** [comment]
It is not planned since it’s not supported in QEMU and in the long term we are moving to a different QEMU graphics backend.

**Comment by LostInCompilation** [comment]
Could you give some short info about the planned backend? Features, advantages and such things. Thx :)

**Comment by osy** [comment]
Not at the moment because I haven't thought it through fully but the gist of it is to take Android Emulator's gfxstream system. It's really complicated and may not be possible but there's no good way forward with Windows support using virglrenderer+ANGLE.

**Comment by osy** [comment]
Basically I don't want to invest any effort in improving the QEMU virgl backend if we are going to move away from it.
