### ISSUE TITLE
Slow rendering on virtio-ramfb and UTM 4.1.4

### ISSUE THREAD

**Issue by sokurenko** [utmapp/UTM#4880]
Slow rendering on virtio-ramfb and UTM 4.1.4 and ubuntu 22.10 , and none of accelerations work 

**Configuration**  
* UTM Version: 4.1.3
* macOS Version: 13.0.1
* Mac Chip M1

Steps:
Open Firefox, google something and start scrolling, notice screen tearing that did not occur on previous versions

**Comment by brad-x** [comment]
Becomes especially noticeable with 4.1.4 launching an app like Celestia or playing a video with lots of action. This is with `virtio-ramfb` not `virtio-ramfb-gl`

**Comment by brad-x** [comment]
This is also occurring on Intel with `virtio-gpu-pci` or `virtio-vga` as shown below

https://user-images.githubusercontent.com/5598039/210585583-52f3bb5c-7b09-4c6a-80a1-711f556ad8bc.mov

**Comment by osy** [comment]
@brad-x are you sure that’s not a guest side issue? Remember there’s no HW accelerated decoding. Another possibility is that the guest is drawing too fast. Check what the refresh rate is on the guest.

**Comment by brad-x** [comment]
> @brad-x are you sure that’s not a guest side issue? Remember there’s no HW accelerated decoding. Another possibility is that the guest is drawing too fast. Check what the refresh rate is on the guest.

Agreed actually. Also the -gl video cards work fine if one wants to disable VirGL in the guest and still get the framerate benefits by setting `"AccelMethod" "none"` in xorg.conf. I'll avoid claimjumping @sokurenko's issue here
