### ISSUE TITLE
virtio-gpu-gl-device not working with new v4.1.5 release

### ISSUE THREAD

**Issue by LostInCompilation** [utmapp/UTM#4893]
**Describe the issue**  
Since the new release 4.1.5 the virtio-gpu-gl-device prevents all VMs from booting. Happens in OpenGL and METAL setting. Looks like the display doesn't get initialized.

It works with the virtio-gpu-gl-pci setting.

**Configuration**  
* UTM Version: 4.1.5
* macOS Version: 13.1
* Mac Chip: M1 Pro

<img width="803" alt="Screenshot 2023-01-04 at 19 38 02" src="https://user-images.githubusercontent.com/12819635/210626429-230b189b-05c2-49b2-abba-7d9304a64db8.png">

**Comment by osy** [comment]
Has virtio-gpu-gl-device ever worked?

**Comment by LostInCompilation** [comment]
As far as I remember yes with 4.0.9. I did a lot of testing and selected every option at least once with Windows/Linux.
It is not an issue thats problematic, since I always use the gpu-pci one.

**Comment by osy** [comment]
Maybe it’s a change in QEMU 7.2 because you’re not supposed to use that (it’s an internal device). I’ll actually remove this from the list in the future.

**Comment by LostInCompilation** [comment]
OK I'll close this.

**Comment by LostInCompilation** [comment]
According to my backup the Windows 7 VM used the virtio-ramfb-gl device. I will try to roll back to 4.0.9 and see if it'll boot.
