### ISSUE TITLE
Multiple cursors on Windows VM when mouse is not captured

### ISSUE THREAD

**Issue by LostInCompilation** [utmapp/UTM#4896]
**Describe the issue**  
When the mouse is not captured, multiple cursors are displayed. For one, the MacOS native cursor (not visible in screenshot), under it the current Windows cursor and the last displayed windows cursor. As soon as mouse capture is enabled, only the correct Windows cursor gets displayed.
I'm using ANGLE (Metal) and virtio-gp-gl-pci. This issue seems to be new since 4.1.5, did not see that before.

**Configuration**  
* UTM Version: 4.1.5
* macOS Version: 13.1
* Mac Chip: M1 Pro

<img width="1728" alt="Screenshot 2023-01-04 at 20 34 55" src="https://user-images.githubusercontent.com/12819635/210636430-16bfc402-3e3a-4b69-93f0-8a1a66feefb2.png">

**Comment by osy** [comment]
I think it’s the same issue as #4683 and is caused by the windows virtio driver not properly sending the signal to hide the cursor.

**Comment by LostInCompilation** [comment]
Strange I never encountered this on 4.0.9. Maybe just a coincidence.

**Comment by osy** [comment]
Found the issue. It is in the viogpu driver: https://github.com/utmapp/virtio-gpu-wddm-dod/blob/main/viogpudo/viogpudo.cpp#L430

When Windows tries to set the cursor to not be visible, the driver code ignores it. We need to modify the driver to pass the info to virtio-gpu and QEMU to properly handle it.

**Comment by osy** [comment]
Read above: https://github.com/utmapp/UTM/issues/4896#issuecomment-1477305628

The issue has been fixed. Just haven't had time to find a way to sign the drivers for distribution. I was hoping to get some other driver fixes in first before going through the trouble of signing.

**Comment by osy** [comment]
The guest tools has been updated. If you're on the latest UTM, you can re-download the latest with the CD icon -> Install Windows Guest Tools. Otherwise you can download it directly https://github.com/utmapp/UTM/releases/download/v4.4.4/utm-guest-tools-0.229.iso
