### ISSUE TITLE
Network configuration not working

### ISSUE THREAD

**Issue by rogerus** [utmapp/UTM#49]
Hi,
There is "IP CONFIGURATION" in "Networking", but I still wonder how to get it work. Is the virtual networking adapter working in NAT mode or bridge mode?

My local network is 192.168.1.0/24, 192.168.1.1 as the gateway. After Windows is installed in the VM, I find the default gateway "192.168.2.2" which is automatically configured even when I leave it blank in "IP CONFIGURATON".

**Comment by Umiiii** [comment]
A temporal solution for Windows:
Network 10.0.1.0/24 Start Address 10.0.1.0 
Windows side:
Set DNS to 8.8.8.8

**Comment by rogerus** [comment]
> A temporal solution for Windows:
> Network 10.0.1.0/24 Start Address 10.0.1.0
> Windows side:
> Set DNS to 8.8.8.8

Thank you @Umiiii

**Comment by osy86** [comment]
Sometimes DNS doesn't automatically work. This is a qemu issue.

**Comment by brunocastello** [comment]
@osy86 just for clarification, bridged networking still does not work? No way to ssh into the VM? Because I did a linux server VM working great, but currently I cannot ssh or access the web server I configured there, on my iPhone X. I thought bridged networking would fix this issue. It's ubuntu server 16.04 32-bit (xenial xerus), btw.

**Comment by osy86** [comment]
You need to set up port forwarding in the settings.

**Comment by brunocastello** [comment]
> You need to set up port forwarding in the settings.

Thank you! It did the trick. My dad is so happy now with his new development "machine".

**Comment by mapedraza** [comment]
@osy @brunocastello 
> > You need to set up port forwarding in the settings.
> 
> Thank you! It did the trick. My dad is so happy now with his new development "machine".

Could you provide more info about how to configure forwarding? I am having an error while triying to configure it in UPM for MacOS

**Comment by OlofT** [comment]
> Could you provide more info about how to configure forwarding? I am having an error while triying to configure it in UPM for MacOS

Just fill in e.g, guest: 22 host: 222
Then you can connect to the VM like so:

ssh localhost -p 222

**Comment by saimurali619** [comment]
> > Could you provide more info about how to configure forwarding? I am having an error while triying to configure it in UPM for MacOS
> 
> Just fill in e.g, guest: 22 host: 222
> Then you can connect to the VM like so:
> 
> ssh localhost -p 222

what ip and dns should I use in my windows VM? currently below is what I have. I'm trying to ssh into my windows vm but never got it in working. Pls help!

my current details ---
Mac
host ip : 192.168.0.111
host dns : 192.168.0.1

Windows VM on UTM (guest has automatically configured ip in network settings and dns alone set to 1.1.1.1)
guest ip : 10.0.2.15
guest dns : 10.0.2.2

UTM network settings : 
port forwarding guest 22 ---> host 222

**Comment by osy** [comment]
https://github.com/utmapp/UTM/discussions
