### ISSUE TITLE
Windows XP installation leads to BSOD (STOP: 0x0000007B)

### ISSUE THREAD

**Issue by retrofreak83** [utmapp/UTM#4901]
**Describe the issue**  
I want to install Windows XP x86 emulated.
I create a fresh VM, setting architecture to i386 (x86).
When I boot the system from the ISO (`de_windows_xp_professional_with_service_pack_3_x86_cd_x14-80444.iso`), the system freezes with a BSOD as described by #2299 (STOP: 0x000000A5). So I change the system type to pc-q35-2.10 as suggested in that issue, but it only leads to a different looking BSOD.

**Configuration**  
* UTM Version: 4.1.5 (74)
* macOS Version: 12.6.2
* Mac Chip (Intel, M1, ...): M1 Pro

**Crash log**  
UTM does not crash.

**Debug log**  
"Export Debug Log" button is deactivated after running the VM and experiencing the issue.
![error](https://user-images.githubusercontent.com/1217763/210770034-d8d8ee8c-877d-415b-acb5-bd3162a6780a.png)

**Comment by osy** [comment]
Can you reproduce on 4.0.9?

**Comment by retrofreak83** [comment]
Yes. Exactly the same behavior.

**Comment by osy** [comment]
I think there's a template in the gallery for Windows XP. Are you using that? I think specifically you need to change the machine from q35 to pc or something like that.

**Comment by LostInCompilation** [comment]
Are you having an ISO with included SATA drivers? Without them, the setup will crash. The error code look to be a ACPI compliant issue.

**Comment by retrofreak83** [comment]
@osy : I didn't take the template because it says "x64". I thought it was not the right one since I did'nt want to have a x64 system, nor install Windows XP 64-bit edition.
However, I gave it a try and installation worked. Thanks!

**Comment by Crane-Mocker** [comment]
I met the same problem when emulating x64 Win XP using UTM Version 3.2.4 (58).
Env and config:
UTM Version 3.2.4 (58)
Mac M1
pc-q35-2.10

**Comment by AnakinBrownridge** [comment]
I want to install Windows longhorn 4053 x86 emulated. I create a fresh VM, setting architecture to x86. When I boot the system from the ISO (`6.0.4053.main.031022-1720_x86fre_client-professional_retail_en-us`), the system freezes with a BSOD as described by
STOP: 0x0000007B).
> **Configuration**
> * UTM Version: 4.5.3
> * iOS version: 15.8.1
> * Prosessor: Apple A9
