### ISSUE TITLE
Windows 7 x86_64 emulation VM won't boot with different display devices

### ISSUE THREAD

**Issue by LostInCompilation** [utmapp/UTM#4906]
**Describe the issue**
My Windows 7 VM (emulated x86_64) won't boot with either virtio-gpu-(gl)-pci or virtio-ramfb-(gl).
**virtio-gpu-(gl)-pci** doesn't work at all. The display of the VM stays empty (seems to be expected, as no Win 7 support).
**virtio-ramfb-(gl)** hangs at the BIOS screen. I can only boot the VM with virtio-vga-(gl), which is quiet laggy.
I'm using the ANGLE (Metal) option.

I previously used the virtio-ramfb-gl device with Windows7 x86_64 in v4.0.9 which worked fine as far as I remember.

**Configuration**  
* UTM Version: 4.1.5
* macOS Version: macOS 13.1
* Mac Chip: M1 Pro

<img width="512" alt="Screenshot 2023-01-06 at 00 34 04" src="https://user-images.githubusercontent.com/12819635/210902429-d60b79c7-f5d6-4f47-a07e-50b92585bba4.png">

**Comment by LostInCompilation** [comment]
No I meant the virtio-ramfb-gl device, copied the wrong line in my post. At least that was the saved setting in the VM configuration, however I haven't started this VM in a long time. So no guarantee this worked 100%.

I'm just experimenting with the new 4.1.5 release and different settings. These are not issues that are critically for me.

**Comment by osy** [comment]
Okay please double check because my recollection is that only virtio-vga works. But other vga cards also work and QXL is preferred on older Windows.

**Comment by LostInCompilation** [comment]
I'll check it tomorrow, need to load a backup.
However the QXL devices are unusable for me. It crashes the VM very frequent. Any way I can create a log for you?

**Comment by LostInCompilation** [comment]
Version 4.0.9 also doesn't boot with virtio-ram-fb. I can't test it with V3, since I don't have the VMs for that Version.
But it seems like that was a configuration issue on my side. I close this issue now.
