### ISSUE TITLE
Internet not working on Debian vm

### ISSUE THREAD

**Issue by Jas-Grace** [utmapp/UTM#4907]
I have a debian vm which I have been using for a few days. Today I logged in and found that internet was not working in Firefox or even in the terminal. Please help.

**Comment by LostInCompilation** [comment]
It's possible the network adapter name changed, not really an issue with UTM.
Run `ip a` and check what's the name of your adapter.
Then change the adapter name in the config file: `sudo nano /etc/network/interfaces`.

**Comment by Jas-Grace** [comment]
My interfaces file looks something like this - 
`source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback`
I think that lo is the correct adapter name or whatever your call it for 'loopback'. Yet still I tried replacing it with what seemed to be the correct adapter name - enp0s1 but still it did not work.

**Comment by LostInCompilation** [comment]
I wrote which line you need to add: iface enp0s1 inet dhcp

**Comment by Jas-Grace** [comment]
Nope, still didn't work

**Comment by LostInCompilation** [comment]
OK, the last idea I would have is trying to install debian in a new VM. I'm pretty sure this is an error on debians side.
