### ISSUE TITLE
New version is inconsistent with previously created VMs

### ISSUE THREAD

**Issue by amirseyedian** [utmapp/UTM#4910]
**Describe the issue**  
<img width="235" alt="Screen Shot 2023-01-06 at 15 13 47" src="https://user-images.githubusercontent.com/105858041/211009086-543e3bea-fecc-4379-8080-c5c87a38e6c4.png">

After upgrading from 4.0.8 to 4.1.5 the existing VMs are greyed (unavailable) out with the error context of: this vm must be readded to utm from finder "location to VM"

however locating and opening it by finder will do nothing since nothing happens after you click the file.

** temporary and undesirable fixes**
downgrading to 4.0.8 will work but also I was able to boot a windows VM by extracting the qcow file from .utm file and creating a new vm in the latest utm version however I cant risk doing the same with my work VM since It has luks encryption and can break the boot configuration

**Configuration**  
* UTM Version: 4.1.5
* macOS Version: 12.3.1
* Mac Chip (Intel, M1, ...):m1 MBA 2020

**Comment by Terabyte1385** [comment]
Have you tried removing and then opening it by clicking it? That did it for me.

**Comment by amirseyedian** [comment]
removing and opening it by finder will result in the following error.
Cannot import this VM. Either the configuration is invalid, created in a newer version of UTM, or on a platform that is incompatible with this version of UTM.

**Comment by osy** [comment]
Can you provide your config.plist?

**Comment by amirseyedian** [comment]
`
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Backend</key>
	<string>QEMU</string>
	<key>ConfigurationVersion</key>
	<integer>4</integer>
	<key>Display</key>
	<array>
		<dict>
			<key>DownscalingFilter</key>
			<string>Linear</string>
			<key>DynamicResolution</key>
			<true/>
			<key>Hardware</key>
			<string>virtio-ramfb</string>
			<key>NativeResolution</key>
			<true/>
			<key>UpscalingFilter</key>
			<string>Linear</string>
		</dict>
	</array>
	<key>Drive</key>
	<array>
		<dict>
			<key>Identifier</key>
			<string>0</string>
			<key>ImageName</key>
			<string>data.qcow2</string>
			<key>ImageType</key>
			<string>Disk</string>
			<key>Interface</key>
			<string>VirtIO</string>
		</dict>
		<dict>
			<key>Identifier</key>
			<string>cdrom0</string>
			<key>ImageType</key>
			<string>CD</string>
			<key>Interface</key>
			<string>USB</string>
		</dict>
	</array>
	<key>Information</key>
	<dict>
		<key>Icon</key>
		<string>backtrack</string>
		<key>IconCustom</key>
		<false/>
		<key>Name</key>
		<string>Kali Linux</string>
		<key>UUID</key>
		<string>860C35AF-364D-471C-A01F-5122F7D6722F</string>
	</dict>
	<key>Input</key>
	<dict>
		<key>MaximumUsbShare</key>
		<integer>3</integer>
		<key>UsbBusSupport</key>
		<string>3.0</string>
		<key>UsbSharing</key>
		<true/>
	</dict>
	<key>Network</key>
	<array>
		<dict>
			<key>BridgeInterface</key>
			<string>en0</string>
			<key>Hardware</key>
			<string>virtio-net-pci</string>
			<key>IsolateFromHost</key>
			<true/>
			<key>MacAddress</key>
			<string>4A:25:0E:A4:7E:C3</string>
			<key>Mode</key>
			<string>Bridged</string>
			<key>PortForward</key>
			<array/>
		</dict>
	</array>
	<key>QEMU</key>
	<dict>
		<key>AdditionalArguments</key>
		<array/>
		<key>BalloonDevice</key>
		<false/>
		<key>DebugLog</key>
		<false/>
		<key>Hypervisor</key>
		<true/>
		<key>PS2Controller</key>
		<false/>
		<key>RNGDevice</key>
		<true/>
		<key>RTCLocalTime</key>
		<false/>
		<key>TPMDevice</key>
		<false/>
		<key>UEFIBoot</key>
		<true/>
	</dict>
	<key>Serial</key>
	<array/>
	<key>Sharing</key>
	<dict>
		<key>ClipboardSharing</key>
		<false/>
		<key>DirectoryShareMode</key>
		<string>WebDAV</string>
		<key>DirectoryShareReadOnly</key>
		<false/>
	</dict>
	<key>Sound</key>
	<array/>
	<key>System</key>
	<dict>
		<key>Architecture</key>
		<string>aarch64</string>
		<key>CPU</key>
		<string>host</string>
		<key>CPUCount</key>
		<integer>0</integer>
		<key>CPUFlagsAdd</key>
		<array/>
		<key>CPUFlagsRemove</key>
		<array/>
		<key>ForceMulticore</key>
		<true/>
		<key>JITCacheSize</key>
		<integer>0</integer>
		<key>MemorySize</key>
		<integer>6144</integer>
		<key>Target</key>
		<string>virt</string>
	</dict>
</dict>
</plist>
`

**Comment by ahamlinman** [comment]
In my case this was related to setting the CPU model to `host`, and the linked plist shows the same configuration. Hand-editing the plist to change `host` to `default` resolved the issue for me.

**Comment by osy** [comment]
@ahamlinman Interesting. If you change it back to "host" from settings UI, does it still show up broken?

**Comment by ahamlinman** [comment]
@osy the option seems to be gone from the UI entirely.

For reference, this is a 2021 M1 Max MacBook Pro running macOS 13.1. [Here's my full `config.plist`.](https://gist.github.com/ahamlinman/d7a703b45ecf59f8c49969b8ef604af7).

<img width="980" alt="Screenshot of UTM 4.1.5 displaying the CPU options dropdown in the settings UI" src="https://user-images.githubusercontent.com/603974/211226897-9eda67e7-9855-4784-9980-b76cd79c75cc.png">

**Comment by osy** [comment]
Oh I see this makes sense. I think QEMU removed the option. I’ll have to work out a way to migrate the setting.

**Comment by osy** [comment]
Please do not close issues that have not been resolved, thanks!

**Comment by amirseyedian** [comment]
Changing CPU model to `default` fixes the problem

**Comment by Aiqin-Aiven** [comment]
I am also getting this import unavailable error after update mac os to Sonoma, but I don't have a way to change CPU model to default in my case. the VM can't be launched and right-clicked, how should I able to change it? 
my config.plist file: https://github.com/Aiqin-Aiven/misc/blob/master/config.plist.backup
