### ISSUE TITLE
CLI or an Shortcuts action to automatically start VM

### ISSUE THREAD

**Issue by Terabyte1385** [utmapp/UTM#4911]
It would make life just a little easier to have my Mac automatically open my Windows VM when I run my Development shortcut. I am now tinkering with AppleScript and simulating keyboard taps is very unstable as of my use case. If only I could use the "Run shell script" action to launch my VM instantly... an actual Shortcut Intent would be even better!

**Comment by LostInCompilation** [comment]
Since 4.1.5 there is a CLI tool called utmctl, located in UTM.app/Contents/MacOS/utmctl.
You can start a VM with it: ./utmctl start NAME_OF_VM

**Comment by Terabyte1385** [comment]
I guess this is what happens when you don't read the release notes. Thanks!
