### ISSUE TITLE
Add support for shared clipboard to macOS 13 guests on macOS 13 hosts

### ISSUE THREAD

**Issue by ideologysec** [utmapp/UTM#4913]
Apple Virtualization supports clipboard sharing between macOS 13 hosts and guests. It would be great to have this added; I utilize a lot of macOS VMs for testing, malware detonation, etc, and copying and pasting bidirectionally between host and VM would be very helpful.

Developer documentation:
https://developer.apple.com/documentation/virtualization/clipboard_sharing

**Comment by osy** [comment]
Duplicate of #4635

**Comment by osy** [comment]
The API you linked to is used by UTM. It is only supported by Linux VMs.

**Comment by osy** [comment]
We will support clipboard sharing when Apple supports it.
