### ISSUE TITLE
Ship newer version of guest tools for Windows (10/11)

### ISSUE THREAD

**Issue by stonerl** [utmapp/UTM#4915]
Currently, UTM ships version 0.1.164 of the guest utilities, which are almost 3 years old. This might be suitable for older Windows guests (e.g., Windows7/8), but these tools are missing some components/features like: `QEMU Guest Agent Service` and `QEMU Guest Agent VSS Provider Service`. The latter one is necessary for working clipboard sharing when using QEMU VNC.

I installed the latest version (0.1.255) [1] and haven't encountered any severe issues. The only “drawback” I can see so far is, that the new video card driver doesn't allow for arbitrary resolutions anymore and only reports the resolutions supported by the host, directly to the guest.

[1] [virtio-guest-tools](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.225-2/)

**Comment by osy** [comment]
We currently don’t use QEMU guest agent at all but there are plans to do so. Once we do we will update it.

**Comment by osy** [comment]
We didn't end up using any GA features that requires a newer version. However I have opened #5134 to track porting the GA to ARM64.
