### ISSUE TITLE
Resolve: Error resetting device: LIBUSB_ERROR_NOT_FOUND  for non-jailbreaked iOS

### ISSUE THREAD

**Issue by yoBoss283** [utmapp/UTM#4919]
It seems that UTM with Windows at the moment can't detect / connect to an non-jailbroken iOS (https://docs.getutm.app/guest-support/sharing/usb/), it provides the error in the title. I was hoping this could be (re)solved. I wonder what Parallels had to do to make it work. 

Thanks!

**Comment by osy** [comment]
Duplicate of #3063
