### ISSUE TITLE
You can't use this version of the application 

### ISSUE THREAD

**Issue by siarez** [utmapp/UTM#4922]
**Describe the issue**  
I get the following pop up when I try to run UTM.
<img width="242" alt="Screen Shot 2023-01-07 at 5 17 56 PM" src="https://user-images.githubusercontent.com/636471/211176410-18a9a2d9-54fd-4efe-9212-f520ec04fdd6.png">

**Configuration**  
* UTM Version: Just downloaded the latest. Not sure about the version.
* macOS Version: 11.2.3
* Mac Chip (Intel, M1, ...): M1 MBA

**Comment by osy** [comment]
This is mentioned in the release notes.
