### ISSUE TITLE
UTM crashes one opening

### ISSUE THREAD

**Issue by jmbenedetto** [utmapp/UTM#4931]
**Describe the issue**
The app crashes immediately after opening. It started when I tried to open a debian image download from UTM library. I tried to delete the app and repeat the process (install the app using AltStore, downloading debian image, trying to open the image from Files app).

**Configuration (required)**
* UTM Version: UTM SE v4.1.5
* OS Version: iPadOS 16.2
* Device Model: Ipad Pro 11-inch 3rd generation
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? Altstore sideload

**Crash log**
{"app_name":"UTM SE","timestamp":"2023-01-11 23:27:43.00 -0300","app_version":"2.1.1","slice_uuid":"ecac94f1-ba43-3a50-ad4c-2d5901c18ccf","build_version":"30","platform":2,"bundleID":"com.utmapp.UTM-SE.7MWTU66269","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 16.2 (20C65)","roots_installed":0,"name":"UTM SE","incident_id":"3A098F3C-3D57-4C4C-A46F-9EBDE3905BDB"}
{
  "uptime" : 590,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPad13,4",
  "coalitionID" : 564,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 16.2",
    "releaseType" : "User",
    "build" : "20C65"
  },
  "captureTime" : "2023-01-11 23:27:42.7651 -0300",
  "incident" : "3A098F3C-3D57-4C4C-A46F-9EBDE3905BDB",
  "pid" : 393,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-01-11 23:18:43.9413 -0300",
  "procStartAbsTime" : 1398899550,
  "procExitAbsTime" : 14330641940,
  "procName" : "UTM SE",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/F6588C4E-0C2A-43DB-A47C-9CCCB666000F\/App.app\/UTM SE",
  "bundleInfo" : {"CFBundleShortVersionString":"2.1.1","CFBundleVersion":"30","CFBundleIdentifier":"com.utmapp.UTM-SE.7MWTU66269"},
  "storeInfo" : {"deviceIdentifierForVendor":"8B03DC3F-352C-43F6-B8E0-E1DD5365E95D","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.utmapp.UTM-SE.7MWTU66269",
  "crashReporterKey" : "94cfbc812413bfe70dfd1a51fbb1d7e2ba38f350",
  "wasUnlockedSinceBoot" : 1,
  "isLocked" : 0,
  "throttleTimeout" : 2147483647,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "lastExceptionBacktrace" : [{"imageOffset":40520,"symbol":"__exceptionPreprocess","symbolLocation":164,"imageIndex":3},{"imageOffset":96472,"symbol":"objc_exception_throw","symbolLocation":60,"imageIndex":0},{"imageOffset":1566764,"symbol":"+[NSObject(NSObject) _copyDescription]","symbolLocation":0,"imageIndex":3},{"imageOffset":130912,"symbol":"___forwarding___","symbolLocation":1592,"imageIndex":3},{"imageOffset":557872,"symbol":"_CF_forwarding_prep_0","symbolLocation":96,"imageIndex":3},{"imageOffset":74064,"imageIndex":6},{"imageOffset":72148,"imageIndex":6},{"imageOffset":415088,"imageIndex":6},{"imageOffset":415460,"imageIndex":6},{"imageOffset":294224,"imageIndex":6},{"imageOffset":293004,"imageIndex":6},{"imageOffset":865864,"imageIndex":6},{"imageOffset":871220,"imageIndex":6},{"imageOffset":518988,"imageIndex":6},{"imageOffset":881912,"imageIndex":6},{"imageOffset":479412,"imageIndex":6},{"imageOffset":9396,"symbol":"_dispatch_call_block_and_release","symbolLocation":32,"imageIndex":12},{"imageOffset":16348,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":12},{"imageOffset":88972,"symbol":"_dispatch_root_queue_drain","symbolLocation":684,"imageIndex":12},{"imageOffset":90756,"symbol":"_dispatch_worker_thread2","symbolLocation":164,"imageIndex":12},{"imageOffset":3516,"symbol":"_pthread_wqthread","symbolLocation":228,"imageIndex":9},{"imageOffset":2968,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":9}],
  "faultingThread" : 1,
  "threads" : [{"id":5866,"queue":"com.apple.main-thread","frames":[{"imageOffset":7248,"symbol":"objc_msgSend","symbolLocation":80,"imageIndex":0},{"imageOffset":453320,"symbol":"-[UIView(Rendering) contentMode]","symbolLocation":60,"imageIndex":1},{"imageOffset":447536,"symbol":"+[_UIImageContentLayout layoutForSource:inTarget:withSize:]","symbolLocation":304,"imageIndex":1},{"imageOffset":446848,"symbol":"-[UIImageView _layoutForImage:inSize:cachePerSize:forBaselineOffset:]","symbolLocation":444,"imageIndex":1},{"imageOffset":199952,"symbol":"-[UIImageView _baselineOffsetFromBottom]","symbolLocation":204,"imageIndex":1},{"imageOffset":198628,"symbol":"-[UIImageView _invalidateImageLayouts]","symbolLocation":152,"imageIndex":1},{"imageOffset":200912,"symbol":"-[UIImageView _updateState]","symbolLocation":128,"imageIndex":1},{"imageOffset":1396624,"symbol":"-[UIImageView _setOverridingSymbolConfiguration:]","symbolLocation":412,"imageIndex":1},{"imageOffset":1493636,"symbol":"-[_UIModernBarButton traitCollectionDidChange:]","symbolLocation":148,"imageIndex":1},{"imageOffset":1481136,"symbol":"-[UIView _traitCollectionDidChangeInternal:]","symbolLocation":696,"imageIndex":1},{"imageOffset":1479884,"symbol":"-[UIView _wrappedProcessTraitCollectionDidChange:forceNotification:]","symbolLocation":156,"imageIndex":1},{"imageOffset":1480316,"symbol":"-[UIView _wrappedProcessTraitCollectionDidChange:forceNotification:]","symbolLocation":588,"imageIndex":1},{"imageOffset":1480316,"symbol":"-[UIView _wrappedProcessTraitCollectionDidChange:forceNotification:]","symbolLocation":588,"imageIndex":1},{"imageOffset":1480252,"symbol":"-[UIView _wrappedProcessTraitCollectionDidChange:forceNotification:]","symbolLocation":524,"imageIndex":1},{"imageOffset":1480252,"symbol":"-[UIView _wrappedProcessTraitCollectionDidChange:forceNotification:]","symbolLocation":524,"imageIndex":1},{"imageOffset":1480252,"symbol":"-[UIView _wrappedProcessTraitCollectionDidChange:forceNotification:]","symbolLocation":524,"imageIndex":1},{"imageOffset":600960,"symbol":"-[UIView(AdditionalLayoutSupport) _withUnsatisfiableConstraintsLoggingSuspendedIfEngineDelegateExists:]","symbolLocation":96,"imageIndex":1},{"imageOffset":593988,"symbol":"-[UIView _processDidChangeRecursivelyFromOldTraits:toCurrentTraits:forceNotification:]","symbolLocation":212,"imageIndex":1},{"imageOffset":18280,"symbol":"-[UIView(CALayerDelegate) layoutSublayersOfLayer:]","symbolLocation":1732,"imageIndex":1},{"imageOffset":39692,"symbol":"CA::Layer::layout_if_needed(CA::Transaction*)","symbolLocation":500,"imageIndex":2},{"imageOffset":119232,"symbol":"CA::Layer::layout_and_display_if_needed(CA::Transaction*)","symbolLocation":148,"imageIndex":2},{"imageOffset":189748,"symbol":"CA::Context::commit_transaction(CA::Transaction*, double, double*)","symbolLocation":444,"imageIndex":2},{"imageOffset":407856,"symbol":"CA::Transaction::commit()","symbolLocation":652,"imageIndex":2},{"imageOffset":4797188,"symbol":"__34-[UIApplication _firstCommitBlock]_block_invoke_2","symbolLocation":36,"imageIndex":1},{"imageOffset":275748,"symbol":"__CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__","symbolLocation":28,"imageIndex":3},{"imageOffset":703868,"symbol":"__CFRunLoopDoBlocks","symbolLocation":368,"imageIndex":3},{"imageOffset":506784,"symbol":"__CFRunLoopRun","symbolLocation":856,"imageIndex":3},{"imageOffset":528064,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":3},{"imageOffset":4968,"symbol":"GSEventRunModal","symbolLocation":164,"imageIndex":4},{"imageOffset":3807340,"symbol":"-[UIApplication _run]","symbolLocation":888,"imageIndex":1},{"imageOffset":3806416,"symbol":"UIApplicationMain","symbolLocation":340,"imageIndex":1},{"imageOffset":1893224,"imageIndex":5},{"imageOffset":1242012,"imageIndex":5},{"imageOffset":1148752,"imageIndex":5},{"imageOffset":941940,"imageIndex":6},{"imageOffset":935016,"imageIndex":6},{"imageOffset":88416,"symbol":"start","symbolLocation":2528,"imageIndex":7}]},{"triggered":true,"id":5881,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":9110302965},{"value":6160214560},{"value":110},{"value":18446744069414588672},{"value":765195553085248145},{"value":765195549412926097},{"value":512},{"value":11},{"value":11},{"value":2095104},{"value":2043},{"value":3248607304},{"value":328},{"value":6160216064},{"value":0},{"value":6},{"value":3843},{"value":6160216288},{"value":0},{"value":15},{"value":10755998720},{"value":0},{"value":276},{"value":0},{"value":6160216288}],"flavor":"ARM_THREAD_STATE64","lr":{"value":9111077292},"cpsr":{"value":1073745920},"fp":{"value":6160214416},"sp":{"value":6160214384},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":8835977568,"matchesCrashFrame":1},"far":{"value":9212249216}},"queue":"com.apple.root.user-initiated-qos","frames":[{"imageOffset":45408,"symbol":"__pthread_kill","symbolLocation":8,"imageIndex":8},{"imageOffset":29100,"symbol":"pthread_kill","symbolLocation":268,"imageIndex":9},{"imageOffset":134284,"symbol":"abort","symbolLocation":180,"imageIndex":10},{"imageOffset":72588,"symbol":"abort_message","symbolLocation":132,"imageIndex":11},{"imageOffset":6784,"symbol":"demangling_terminate_handler()","symbolLocation":336,"imageIndex":11},{"imageOffset":122172,"symbol":"_objc_terminate()","symbolLocation":144,"imageIndex":0},{"imageOffset":69416,"symbol":"std::__terminate(void (*)())","symbolLocation":20,"imageIndex":11},{"imageOffset":69316,"symbol":"std::terminate()","symbolLocation":56,"imageIndex":11},{"imageOffset":16368,"symbol":"_dispatch_client_callout","symbolLocation":40,"imageIndex":12},{"imageOffset":88972,"symbol":"_dispatch_root_queue_drain","symbolLocation":684,"imageIndex":12},{"imageOffset":90756,"symbol":"_dispatch_worker_thread2","symbolLocation":164,"imageIndex":12},{"imageOffset":3516,"symbol":"_pthread_wqthread","symbolLocation":228,"imageIndex":9},{"imageOffset":2968,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":9}]},{"id":5883,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]},{"id":5885,"name":"com.apple.uikit.eventfetch-thread","frames":[{"imageOffset":19112,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":8},{"imageOffset":94148,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":8},{"imageOffset":94724,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":8},{"imageOffset":20460,"symbol":"mach_msg","symbolLocation":24,"imageIndex":8},{"imageOffset":502484,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":3},{"imageOffset":507160,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":3},{"imageOffset":528064,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":3},{"imageOffset":270548,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":212,"imageIndex":13},{"imageOffset":270268,"symbol":"-[NSRunLoop(NSRunLoop) runUntilDate:]","symbolLocation":64,"imageIndex":13},{"imageOffset":5072684,"symbol":"-[UIEventFetcher threadMain]","symbolLocation":436,"imageIndex":1},{"imageOffset":374184,"symbol":"__NSThread__start__","symbolLocation":716,"imageIndex":13},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":9},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":9}]},{"id":5886,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]},{"id":5888,"queue":"com.apple.Pasteboard.notification-queue","frames":[{"imageOffset":21372,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":8},{"imageOffset":32876,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":9},{"imageOffset":262332,"symbol":"-[NSOperation waitUntilFinished]","symbolLocation":508,"imageIndex":13},{"imageOffset":309772,"symbol":"_CFXNotificationPost","symbolLocation":772,"imageIndex":3},{"imageOffset":380316,"symbol":"-[NSNotificationCenter postNotificationName:object:userInfo:]","symbolLocation":92,"imageIndex":13},{"imageOffset":67272,"symbol":"__67+[PBServerConnection beginListeningToPasteboardChangeNotifications]_block_invoke_2","symbolLocation":156,"imageIndex":14},{"imageOffset":13184,"imageIndex":15},{"imageOffset":78100,"symbol":"_dispatch_block_async_invoke2","symbolLocation":148,"imageIndex":12},{"imageOffset":16348,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":12},{"imageOffset":46740,"symbol":"_dispatch_lane_serial_drain","symbolLocation":672,"imageIndex":12},{"imageOffset":49632,"symbol":"_dispatch_lane_invoke","symbolLocation":384,"imageIndex":12},{"imageOffset":93712,"symbol":"_dispatch_workloop_worker_thread","symbolLocation":652,"imageIndex":12},{"imageOffset":3576,"symbol":"_pthread_wqthread","symbolLocation":288,"imageIndex":9},{"imageOffset":2968,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":9}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7697661952,
    "size" : 278048,
    "uuid" : "d6ecfb73-0ca2-3a21-a3a9-19e450d3b49c",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7847219200,
    "size" : 25083904,
    "uuid" : "59cbc9b5-30ae-396e-a269-a986640001bc",
    "path" : "\/System\/Library\/PrivateFrameworks\/UIKitCore.framework\/UIKitCore",
    "name" : "UIKitCore"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7835480064,
    "size" : 3534848,
    "uuid" : "e0e47b5d-2805-361d-88c4-875002b0244d",
    "path" : "\/System\/Library\/Frameworks\/QuartzCore.framework\/QuartzCore",
    "name" : "QuartzCore"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7811743744,
    "size" : 4087808,
    "uuid" : "725e49f4-653b-39bf-9a7a-8a3250911ecb",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/CoreFoundation",
    "name" : "CoreFoundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8776605696,
    "size" : 36864,
    "uuid" : "5adda888-f387-35f7-87a7-e01fcb9bb928",
    "path" : "\/System\/Library\/PrivateFrameworks\/GraphicsServices.framework\/GraphicsServices",
    "name" : "GraphicsServices"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7872303104,
    "size" : 26542080,
    "uuid" : "6e8b3886-687c-3716-80c1-ab32efbc575c",
    "path" : "\/System\/Library\/Frameworks\/SwiftUI.framework\/SwiftUI",
    "name" : "SwiftUI"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4307222528,
    "size" : 3145728,
    "uuid" : "ecac94f1-ba43-3a50-ad4c-2d5901c18ccf",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/F6588C4E-0C2A-43DB-A47C-9CCCB666000F\/App.app\/UTM SE",
    "name" : "UTM SE"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8323960832,
    "size" : 536720,
    "uuid" : "7b63c573-6161-3b33-a3a2-9944ba59722f",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8835932160,
    "size" : 241636,
    "uuid" : "9daa5c29-93e0-3768-a3e1-e139995dc4af",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 9111048192,
    "size" : 49152,
    "uuid" : "f2ba7ec0-f75a-3345-b4f6-f7da4979b902",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7935852544,
    "size" : 524280,
    "uuid" : "f088d98d-f2a1-3452-996f-9e6bb5139f52",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 9110216704,
    "size" : 98300,
    "uuid" : "a0028fdf-20f4-3a76-a43d-f0fa725bee9f",
    "path" : "\/usr\/lib\/libc++abi.dylib",
    "name" : "libc++abi.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7935561728,
    "size" : 290816,
    "uuid" : "24db930d-870b-31ce-ac69-534d7896b4a8",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7715229696,
    "size" : 9740288,
    "uuid" : "07a92f05-d8ec-327e-ab33-41db9f77ba16",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Foundation",
    "name" : "Foundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7968350208,
    "size" : 221184,
    "uuid" : "803dd147-d672-376e-aa95-2d1a74e196b6",
    "path" : "\/System\/Library\/PrivateFrameworks\/Pasteboard.framework\/Pasteboard",
    "name" : "Pasteboard"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8435789824,
    "size" : 45048,
    "uuid" : "7bf7b5be-4202-3ae0-b2fa-8daeddd400ea",
    "path" : "\/usr\/lib\/system\/libsystem_notify.dylib",
    "name" : "libsystem_notify.dylib"
  }
],
  "sharedCache" : {
  "base" : 7696941056,
  "size" : 2885779456,
  "uuid" : "4a17a992-df1e-3a8d-849c-9f73c0662339"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=607.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=607.7M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nCG raster data                     192K        4 \nColorSync                           96K        4 \nCoreAnimation                      240K       12 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           602.1M      126 \nMALLOC guard page                  128K        8 \nSQLite page cache                  256K        2 \nSTACK GUARD                         96K        6 \nStack                             3728K        6 \nVM_ALLOCATE                       1200K        4 \n__AUTH                            3460K      447 \n__AUTH_CONST                      27.5M      688 \n__CTF                               756        1 \n__DATA                            13.7M      719 \n__DATA_CONST                      34.1M      695 \n__DATA_DIRTY                      3457K      586 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       305.9M       41 \n__OBJC_CONST                      6626K      473 \n__OBJC_RO                         78.3M        1 \n__OBJC_RW                         2404K        1 \n__TEXT                           709.8M      744 \ndyld private memory                256K        1 \nmapped file                      177.1M       21 \nshared memory                       48K        3 \n===========                     =======  ======= \nTOTAL                              1.9G     4597 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.root.user-initiated-qos"
  }
},
  "trialInfo" : {
  "rollouts" : [

  ],
  "experiments" : [

  ]
}
}

**Debug log**
Impossible to open the app.

**Upload VM**
Basic Debian 11 (LDXE) from UTM site.

[config.plist.zip](https://github.com/utmapp/UTM/files/10397794/config.plist.zip)

**Comment by osy** [comment]
You are using an extremely old version of UTM SE (v2.1.1). Please try the latest version.
