### ISSUE TITLE
OptionsList for Flags doesn't show pretty values, but rather raw values

### ISSUE THREAD

**Issue by stonerl** [utmapp/UTM#4940]
I was toying around with UTM and wanted to change some prettyValue in the Flag list. But I noticed that these are never used and the raw values are shown instead.

https://github.com/utmapp/UTM/blob/46f1f22b22a45cc73d0377f57ea812fcf8ac9b02/Platform/Shared/VMConfigSystemView.swift#L217-L235

E.g. change line 4938 from `3dnow` to `3dyesterday`

https://github.com/utmapp/UTM/blob/46f1f22b22a45cc73d0377f57ea812fcf8ac9b02/Configuration/QEMUConstantGenerated.swift#L4936-L4938

It should now show `3dyesterday` in the UI but it uses the raw value from line 4616 instead.

https://github.com/utmapp/UTM/blob/46f1f22b22a45cc73d0377f57ea812fcf8ac9b02/Configuration/QEMUConstantGenerated.swift#L4615-L4616

Version/Platform: git-master on macOS

**Comment by osy** [comment]
While you are technically right, there is not a single flag which doesn't have the same text for rawValue and prettyValue.
