### ISSUE TITLE
Version 4.1.5 (74): "Error trying to restore external drives and shares: Failed to access drive image path."

### ISSUE THREAD

**Issue by Ondjultomte** [utmapp/UTM#4957]
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Describe the issue**  
Replace this text with a clear and concise description of what the issue is.

**Configuration**  
* UTM Version: Version 4.1.5 (74)
* macOS Version: 12.6.1 (21G217)
* Mac Chip (Intel, M1, ...): M1

**Crash log**  
no crash

**Debug log**  
Error message when trying to launch my existing windows VM from UTM 4.0.2:
"Error trying to restore external drives and shares: Failed to access drive image path."

**Upload VM**  
Windows arm VM, but should not be related to this specific VM, more of a setting/config mismatch in UTM.

**Comment by Ondjultomte** [comment]
![image](https://user-images.githubusercontent.com/16661547/213661024-55be2a6c-06ef-4669-accd-43983342320f.png)

**Comment by Ondjultomte** [comment]
I solved it by just edit the VM and saved the exact same settings.

So some missing path or something ?

**Comment by osy** [comment]
Yeah this error happens sometimes when the underlying file is deleted. In this case, it's probably the guest tools which is stored in the cache. Saving it automatically removes broken links.

**Comment by michaelyousrie** [comment]
> I solved it by just edit the VM and saved the exact same settings.
> 
> So some missing path or something ?

Worked perfectly for me thanks!
