### ISSUE TITLE
Make toolbar movable

### ISSUE THREAD

**Issue by cuj** [utmapp/UTM#496]
The VM toolbar needs some good improvement. Improvements will be below.

first, the vm toolbar will have some corners at each edge (4 combos, depending on where the user drags the toolbar to) (i've used mspaint, I am not a professional at drawing in computers, but atleast you can make it better when you decide to implement it):
[Number 1](https://user-images.githubusercontent.com/66434686/96693577-14326f00-1390-11eb-9f83-35de2f7d184c.png), [Number 2](https://user-images.githubusercontent.com/66434686/96694115-b18da300-1390-11eb-8995-3287ca20343c.png), [Number 3](https://user-images.githubusercontent.com/66434686/96693564-11377e80-1390-11eb-8534-ffbbfef8546b.png), [Number 4](https://user-images.githubusercontent.com/66434686/96694122-b3576680-1390-11eb-8885-8d8848eca202.png),

second, make the tool draggable in any ipads, and any horizontal positioned iphones/ipods
(I've used bandicam and mspaint since IDK how to animate at all but please don't hate, atleast you know what I mean);

https://user-images.githubusercontent.com/66434686/142724386-5398a636-cdb8-4dff-a45f-c29a1d004518.mp4

edit: ignore the mouse in the animation, what I meant is that when I drag the toolbar to another inside screen border whilst I am very close hitting a corner it will snap to the other inside screen border.

**Comment by ThatsNiceGuy** [comment]
The animated version isnt publicly accessible so I cant see it.

**Comment by IIWare** [comment]
@ThatsNiceGuy fixed and you can mark your first comment to this issue as off-topic.

**Comment by osy** [comment]
Will be done as part of the toolbar re-work in v3.0.

**Comment by osy** [comment]
Implemented in v3.0
