### ISSUE TITLE
No 'PCI' bus found for device 'virtio-serial-pci'

### ISSUE THREAD

**Issue by maver1ck** [utmapp/UTM#4961]
**Describe the issue**  
Hi,
I'm trying to run Windows 95 using isapc.
After configuring VM I'm getting error:
QEMU exited from an error: qemu-i386-softmmu: -device virtio-serial: No 'PCI' bus found for device 'virtio-serial-pci'

**Configuration**  
* UTM Version:  4.1.5
* macOS Version:  13.1
* Mac Chip (Intel, M1, ...): M1 Pro

**Comment by xp5-org** [comment]
Hello, i ran into this issue after updating UTM to version 4.1.5 . Any new Emulated ISA PC config would fail to start with the same PCI serial bus error.

UTM incorrectly sets the architecture type to x86_64, when setting ISA-PC type
<img width="912" alt="archtype" src="https://user-images.githubusercontent.com/18539839/218643882-e56861b8-0cce-4b08-accb-c1086f783786.png">
also sets a PCI video device and PCI network, which is invalid for isapc. 

The incorrect architecture type is the cause of the No 'PCI' bus found for device 'virtio-serial-pci' error . 

I have found the following workaround for UTM, when creating a new emulated ISA x86 pc config:
- change architecture (under System tab) from x86_64 to i386 . **this will reset all settings for this VM**
- change video device to ISA vga or ISA cirrus
- change network device to ISA such as ne2k or pcnet

with these workarounds you should be able to start a isapc - i386 emulated vm in UTM

**Comment by tifasoftware** [comment]
The workaround is not working in 4.2.5
