### ISSUE TITLE
Unable to disable backing up vms to icloud

### ISSUE THREAD

**Issue by lavavex** [utmapp/UTM#4966]
**Describe the issue**
VMs are backed up to icloud without any way to disable, causing icloud storage to max out. If a toggle to disable this in settings could be added that would be appreciated.

**Configuration (required)**
* UTM Version: 4.1.5
* OS Version: 15.4.1
* Device Model: iPad M1 11"
* Is it jailbroken (name jailbreak used)? Trollstore?
* How did you install UTM? Trollstore

**Comment by osy** [comment]
@lavavex Can you try using TrollStore to temporarily mark UTM as User and then disabling UTM from iCloud Backups?
