### ISSUE TITLE
Prevent the user from importing most file types as disk images

### ISSUE THREAD

**Issue by ThatsNiceGuy** [utmapp/UTM#497]
**Describe the feature**
A user in the Discord server was asking why the prebuilt android VM wasn’t working.

This ended up being because the user had added the `.utm` file to a virtual machine as a *disk image*.

We need to prevent the user from importing most file types as disk images. Potentially limit it to `.bin`, `.qcow`, `.qcow2`, `.iso` and `.img`, then display a pretty printed information message when the user tries to import anything else, maybe like this:
![2DE30B29-2CCF-43EF-BFB2-56790E5A5269](https://user-images.githubusercontent.com/10524728/97029849-35739680-151b-11eb-81ad-941db65730a0.jpeg)

And for when the user tries importing a `.utm` file as a disk image, display something like this instead:
![4F449915-6DFE-4DDE-937A-2093D3BE400A](https://user-images.githubusercontent.com/10524728/97030256-bfbbfa80-151b-11eb-8ffe-7a29f4d9da2b.jpeg)

**Comment by osy86** [comment]
Good idea, I really don’t know why people do this but it seems to be a big issue.

**Comment by osy86** [comment]
Okay I can't limit the file extension because file extension != file type (you can rename an iso to anything for example) and it's too much work to parse valid files. I'm assuming that rejecting .utm specifically can filter out a lot of support requests.

**Comment by ThatsNiceGuy** [comment]
eh this should still go a long way towards helping this issue
