### ISSUE TITLE
Mouse issues on older operating systems

### ISSUE THREAD

**Issue by brunocastello** [utmapp/UTM#498]
I don’t really know if its an issue with the app, QEMU, my VM or mouse DOS driver. But here is the case, I hope someone can shed some light on this for me.

I have a DOS 6.22/Windows 3.11 VM with some games and a DOS mouse driver (mouse.com). This is what happened to me:

I booted the VM and decided to play a few minutes on old “Where in the World is Carmen Sandiego?”, the first DOS version, black and white so that game never had mouse support, OK. I did not remember how to quit that game so I hit CTRL+ALT+DEL to reboot, and after reboot I decided to try a more recent version of the same game (the colorful one, 1992 or 1994 version I think) that version had mouse support but the mouse did not work. This time I knew how to quit the game with the keyboard controls.

A few minutes later, I decided to try “Grand Prix 2” (a MicroProse F1 game sequel released in 1996, even though the game came with 1994 F1 teams and tracks). The menus did not have mouse working for some reason (???). I played a quick race for a few minutes and decided to quit back to DOS. Then I started Windows 3.11. Much to my surprise, the mouse was not working either.

I then managed to quit Windows with the keyboard, and decided to shut down the VM and restart it. Once it restarted, I was suspecting about some driver or something else as the culprit of the problem so I decided to start Windows 3.11 again. This time, the mouse was working as expected. I’m pretty sure that if I decided to relaunch any other game with mouse support (such as GP2), then the mouse would not work again unless I reboot the VM.

Is there any explanation for this issue? I have input legacy mode turned on, because with it turned off, my keyboard and mouse would not work. I thought about trying later a different DOS mouse driver such as CuteMouse, but I think I have ran into this issue before with a previous 0.x beta UTM version months ago and I forgot what was made of it later. If there is no solution, I can understand that, but I would just like to hear the explanation at least.

My other VMs (macOS 10.5 Leopard, Windows 98, macOS 9.2.1) do not suffer from the same problem, macOS 9.2.1 I was able to get keyboard working by turning on the legacy input mode too.

BTW: I see that with UTM 2.0b3 (the version I have installed) I was finally able to play GP2 with the iPad Smart Keyboard as expected, throttle and brake with the keys are now working, thanks! If we could resolve the mouse issue, then I can finally ditch iDOS2 from my iPadPro and use UTM exclusively for retro gaming.

Once again, thanks for a great emulation experience!
Bruninho

**Comment by osy86** [comment]
Can you test in QEMU on a desktop to see if it suffers from similar issues?

**Comment by brunocastello** [comment]
Yeah QEMU on desktop has similar issues. At first I thought it was related to the release mouse thing, but no, I rebooted, repeated the steps and yea, nothing to do with the release mouse thing. I try a game, mouse works, then I go to Windows, mouse stops. The opposite yields the same results (windows works then game don't).

I was suspecting of a mouse driver issue before I updated UTM for 14.2. I had downloaded a cutemouse driver to try out. I'll test the driver and report back.

**Comment by brunocastello** [comment]
It's not a driver issue, it's definitely QEMU. Here's the thing: I loaded cutemouse (replacing the old driver). Then I loaded Grand Prix 2, mouse works. Quit game. Load Windows, mouse doesn't work. I quit Windows by keyboard. I decided to load Grand Prix 2 again to see if the mouse still works there. Yeah, the mouse works there. It's like if the mouse is "locked" to the first thing I open on this particular machine (MS DOS 6.22/Windows 3.11). The workaround is to restart the machine to "release" the mouse for another application or game.

VMware and DOSBox does not suffer from the same problem.

**Comment by osy86** [comment]
That’s unfortunate but if it’s a QEMU issue it’s better to report it to QEMU project.

**Comment by brunocastello** [comment]
I understand. OK, no problem. I haven't found anything about the issue on Google and I doubt that the QEMU project devs would want to look after something for a such old OS; they seem to be focused on running much more powerful OSes. Anyway, you can close this issue if you want.
