### ISSUE TITLE
QEMU arguments won't update after moving the VM to another location

### ISSUE THREAD

**Issue by KrisCris** [utmapp/UTM#4985]
**Describe the issue**  
I want to move the VM to another location after creation (Because I can't find a way to set its stored location during the creation).
I click on the "Move" button on the right-click menu of the VM to move it to the desired location, however, the VM can no longer be launched because the QEMU arguments are still using the old location.

<img width="1012" alt="Screenshot 2023-02-02 at 12 41 57 AM" src="https://user-images.githubusercontent.com/38860226/216251243-5e29ad2b-58e1-457f-9fbf-793a9ef84614.png">

**Configuration**  
* UTM Version: 4.1.5 (74)
* macOS Version: 13.1
* Mac Chip: M2

**Upload VM**  
[Kali.utm.zip](https://github.com/utmapp/UTM/files/10565963/Kali.utm.zip) (I haven't even started installing the OS)

**Comment by osy** [comment]
Did you close the VM window before moving?
