### ISSUE TITLE
Can't open files(ios files open button)

### ISSUE THREAD

**Issue by SpaimaFemeilor** [utmapp/UTM#4993]
**Describe the issue**
When I try to open a file(utm file, iso, selecting a shared folder), the open button doesn't work. It just doesnt do anything
Yes I did try uninstalling
Video: https://share.icloud.com/photos/00ay66_wJC_h6G1E6dVQTeF2w

**Configuration (required)**
* UTM Version: 4.1.5
* OS Version: 16.1
* Device Model: iPhone 12
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? ESign

**Upload VM**
https://github.com/utmapp/vm-downloads/releases/tag/android-x86-9.0

**Comment by osy** [comment]
This is a known issue when UTM isn't signed properly with a supported tool. Check https://docs.getutm.app/installation/ios for supported install methods.
