### ISSUE TITLE
UTM crash on jailbreak iphone6s with iOS 13.3.1 

### ISSUE THREAD

**Issue by TangMonk** [utmapp/UTM#50]
I copy UTM.app  to /Applications/ , and crashed when open

**Comment by ThatsNiceGuy** [comment]
This is because the IPA isn’t even fakesigned, you’ll have to install with ReProvision. If you have AppSync then the signing shouldn’t expire

**Comment by osy86** [comment]
#32

**Comment by TangMonk** [comment]
> #32

I have AppSync  installed
