### ISSUE TITLE
utmctl list gives error: OSStatus error -1743

### ISSUE THREAD

**Issue by wivaku** [utmapp/UTM#5001]
**Describe the issue**  
`/Applications/UTM.app/Contents/MacOS/utmctl list` does not list my VM and shows error instead:  
`Error from event: The operation couldn’t be completed. (OSStatus error -1743.)`

**Configuration**  
* UTM Version: 4.1.5 (74)
* macOS Version: 13.2
* Mac Chip (Intel, M1, ...): M2

**Details**  
I have one running VM (Home Assistant).
The output:

```
$ /Applications/UTM.app/Contents/MacOS/utmctl list
Error from event: The operation couldn’t be completed. (OSStatus error -1743.)
UUID                                 Status   Name
```

**Comment by wivaku** [comment]
appears to have been a glitch. Is working now.

**Comment by junosuarez** [comment]
I ran into this issue as well - when I'm physically on my mac, using the builtin Terminal.app, `utmctl list` works after popping up a macos permissions dialog box. When I'm logged in via ssh from another machine, I consistently get `Error from event: The operation couldn’t be completed. (OSStatus error -1743.)`.

### Configuration

UTM Version: 4.1.5 (74)
macOS Version: 13.2.1
Mac Chip (Intel, M1, ...): M1

**Comment by flintlei** [comment]
@wivaku  May I ask which version has this fixed? I got the same issue on UTM 4.1.6 (75) running on Mac mini M2.

**Comment by osy** [comment]
Scripting bridge requires you to be logged in. You need to be able to launch a gui app

**Comment by logopk** [comment]
So actually the cli is almost useless if I try to manage machines remotely? Actually I am trying to run headless servers with utm and need to handle them via vpn/ssh.

**Comment by max-wittig** [comment]
Same happens here with the latest beta version.

**Comment by InferiusFurious** [comment]
For me this error happens on my OCLP iMac15,1 running macOS 13.3.1 22E261. It happens regardless of whether I am logged in using SSH or physically typing this command in at the terminal. I tested on another machine and it worked fine there after showing a permissions dialog. For some reason, on my iMac the permissions dialog never shows (I cannot recall whether I might have accidentally dismissed it in the past, which could very well be why this is happening). It would be great if you can "reset" the permissions somehow.

**Comment by muzzah** [comment]
Going to chime in here and also complain :) 

Im currently in Japan trying to manage some VMs located at home. I assumed this would work before I left and now discover that this does not work with the same error message. So now its useless. I think the fact that this does not work over ssh is a pretty big omission. 

@wivaku Can you please reopen this issue. I feel like this should be fixed somehow.

**Comment by osy** [comment]
I think the new issue is fine, this one seemed to have a different root cause.
