### ISSUE TITLE
Clone VMs with utmctl

### ISSUE THREAD

**Issue by nre-ableton** [utmapp/UTM#5004]
I did look in the backlog for this, and was surprised to see it hadn't been mentioned yet (apologies if I've missed something). As far as I can tell, it's not possible to create new clones via the CLI. For an unattended CI system (for example), that makes UTM unusable.

It would be really nice if I could make clones with `utmctl`. Or, if there is a workaround, such as copying the files in `~/Library/Containers/com.utmapp.UTM/Data/Documents` and somehow registering the VM with UTM so that it would show up in `utmctl list` etc.

**Comment by greeneg** [comment]
Basic deletion functionality would also be appreciated as well in furtherance of making UTM a valid tool for CI as well

**Comment by ideologysec** [comment]
@nre-ableton you could conceivably clone it via `cp` or other operations, and then call `open` on the bundle path to register it (which will launch it in UTM)

**Comment by osy** [comment]
FYI: As of v4.2.2, there is support for clone and creating new VM using the scripting interface. `utmctl` has not been updated yet.

**Comment by greeneg** [comment]
> FYI: As of v4.2.2, there is support for clone and creating new VM using the scripting interface. `utmctl` has not been updated yet.

Can you point me to docs for the scripting interface? I'm looking at hacking up a vagrant plugin to use utm instead of vBox to get local development working again for my team (M1 hw, but our target OS is x86_64)

**Comment by osy** [comment]
https://github.com/hashicorp/vagrant/issues/12518#issuecomment-1478607592

**Comment by max-wittig** [comment]
Thanks!

**Comment by max-wittig** [comment]
@greeneg We're using this applescript to be able to use UTM inside CI for deletion as a workaround:

```applescript
on run argv
	tell application "UTM"
	    set vm_name to item 1 of argv
		delete virtual machine named vm_name
		log "Deleted '" & vm_name & "'"
	end tell
end run
```

```sh
osascript ${currentDir}/delete.oascript vm-name
```
