### ISSUE TITLE
Signing certificate expired

### ISSUE THREAD

**Issue by parasaito** [utmapp/UTM#5011]
Not sure if this causes any immediate problems, but the software signing certificate for UTM has expired. My copy is from the App Store.

https://developer.apple.com/support/expiration/

<img width="799" alt="Screenshot 2023-02-12 at 12 57 40 AM" src="https://user-images.githubusercontent.com/97852663/218277465-435d562f-23e5-4515-8d9f-d9c476be20e6.png">

**Comment by osy** [comment]
I don't believe this should be an issue for users as the timestamp for when the app was modified was before the expiration date. Let me know if you get an error from macOS.
