### ISSUE TITLE
iPad Pro M1: Fedora 37 arm64, iOS UTM HV Issues, & WIndows Sound SOLVED

### ISSUE THREAD

**Issue by Primeboy77** [utmapp/UTM#5026]
# 5026.A
Fedora 37 Workstation arm64 fails to install to hard drive crashes and causes the whole app to crash and cause a device resping and/or reboot upon click install to hard drive on Live ISO mode.  Basic graphical install also yeilds a blank black screen.
I was really impressed at how Fedora 37 ran even on a live ISO.  Fedora 37 and Windows 11 really complements iPadOS really well.  I hope to see in a future update that it is alas possible to install and boot Fedora arm64 from a virtual disk drive some day. 

# 5026.B
Some bug reports when using Win11 on UTM HV 4.1.5;
 - The VM doesn’t run in background
 - Changes of landscape to portrait mode on ipad crashes the app.
 - No screenshots of VM are saving.
 - Exiting the app when entering homescreen or app switching crashes the VM.
 - All sound in Windows 11 is significantly more stuttering and jarring to the speakers than in Windows 10.  Even After spice guests tools.

-If one absolutely stays put in the VM without any interaction with iPadOS VM is stable.

# 5026.C
Also if anyone knows how to get windows 10 arm64 working in 2023 as the ISO results in Blue screen of death errors during new VM installation procedures.  According to UUP scripts and users below version has been discontinued by Microsoft Servers.
Does anyone have a Windows 10 multi_creatingISO_21390.2025_en-us_arm64_professional ISO file in order to preserve keeping alive UTM Windows 10 Virtualization Alive. Please Post a cloud link of such an ISO.

Device is iPad Pro 5th Gen 12.9 M1 with iPadOS 15.1 Xina jailbreaken and Trollstore Included.
**Configuration (required)**
* UTM Version: 4.1.5 HV
* OS Version: iPadOS 15.1        Fedora 37, WIndows 10, Windows 11
* Device Model: iPad Pro 12.9 M1
* Is it jailbroken (name jailbreak used)? Xina
* How did you install UTM? Trollstore

**Comment by Primeboy77** [comment]
5026.A SOLVED

[mijorus] commented
Disabling GPU acceleration was enough to make it work!

Display > Display Card > Virtio RamFb

well, GPU acceleration is hit or miss in my experience.
On Ubuntu for example, some apps just won't launch when GPU acceleration is enabled.

About fedora, UTM should either default to virtio ramrb or add a paragraph about this workaround. Out of the box is just unusable.

Primeboy77 Comments - That this little maneuver has rectified functionality of the Fedora 37 Workstation arm64 VM.

**Comment by Primeboy77** [comment]
# 5026.B Semi-Solved

Once again the >>>>
Disabling GPU acceleration was enough to make it work!
Display > Display Card > Virtio RamFb

*Fixes All F' up delayed video and sound in Windows 11 from being significantly more stuttering and jarring to the speakers

**Comment by Primeboy77** [comment]
# 5026.C Solved

Damn Once again the >>>>
"Disabling GPU acceleration was enough to make it work!
Display > Display Card > Virtio RamFb"

*This modification of defaults settings supplants the desire of Windows 10 as a superior in video and sound.
Due to improving virtualization of video and sound by so much.

**Comment by liuyandashen** [comment]
"Disabling GPU acceleration was enough to make it work!
Display > Display Card > Virtio RamFb"
it's work!! thanks
