### ISSUE TITLE
Error, Failed to verify code signature (0xe800801c)

### ISSUE THREAD

**Issue by IIWare** [utmapp/UTM#506]
**Describe the bug**
I tired to install UTM v2.0b7 in my phone via filza, IDK why but when I install the IPA via filza it says "Error: Failed to verify code signature... (0xe800801c).

**To Reproduce**
1. Download UTM v2.0b7 IPA
2. copy to filza
3. click the IPA in filza
4. Click install

![](https://user-images.githubusercontent.com/66434686/98083688-c8052580-1e8b-11eb-97d8-e7ecce46bcc2.PNG)

Can you please fix the bug or If I am doing it wrong, can you please tell me a solution? thanks.

**Comment by osy86** [comment]
It looks like a filza bug. Can you contact the devs for filza to see if that’s the case?

**Comment by Assfugil** [comment]
Are you on ios 14? AppSync don't work on that version and you need a proper signature.

**Comment by IIWare** [comment]
I'm in ios 13.5.1

**Comment by IIWare** [comment]
@osy86 where can I contact them?

**Comment by Assfugil** [comment]
@IIWare do you have appsync unified installed?

**Comment by IIWare** [comment]
@Assfugil no, should I install AppSync so that I can install the IPA via Filza?

**Comment by Assfugil** [comment]
> @Assfugil no, should I install AppSync so that I can install the IPA via Filza?

Yes

**Comment by IIWare** [comment]
@Assfugil I will try.

**Comment by osy86** [comment]
Closing because it is not an UTM issue.

**Comment by iscodeeasyornot** [comment]
@IIWare  I have the same problem,did you solve it?

**Comment by IIWare** [comment]
@iscodeeasyornot I didn't have a chance to try but you can install AppSync
