### ISSUE TITLE
UI bug - not possible to change from Shared Network type

### ISSUE THREAD

**Issue by mistermantas** [utmapp/UTM#5078]
**Describe the issue**  

It looks like it's not possible to change  from Shared Network type to any other type (or change the network card).

Is this expected behavior?

If it helps, I was troubleshooting Windows 10/11 network issues and had to manually add the 1.1.1.1 / 8.8.8.8 DNS servers then internet started working so I didn't even need those options but its strange I could not change them in the first place.

Video here:

![02-28 at 21 50 12](https://user-images.githubusercontent.com/11616378/221971490-c6515443-5f9f-4817-8634-07c20f143a57.gif)

**Configuration**  
* UTM Version: Version 4.1.6 (75)
* macOS Version: 13.2.1 
* Mac Chip (Intel, M1, ...): m1

**Comment by wingcomm** [comment]
I'm unable to replicate this on an M1 Max running 4.1.6 on 13.2.1. You'll need to add some more details about the VM.
