### ISSUE TITLE
Save ISO file bookmark for Apple Virtualization Linux VMs

### ISSUE THREAD

**Issue by ktprograms** [utmapp/UTM#5093]
Should be the same fix as #4938. I've only tested this happens on non-EFI VMs, but I think it'd happen with EFI VMs as well.

**Comment by osy** [comment]
I'm unable to reproduce this. I tried both EFI (only select a boot ISO) and non-EFI (select a vmlinux and a boot ISO). In both cases I was able to see the ISO listed in the home screen as well as start the VM after both moving to Downloads and also after quitting/starting UTM again. I am on macOS 13 though.

**Comment by ktprograms** [comment]
Hmm, I can't seem to reproduce it either.
Sorry for the noise
