### ISSUE TITLE
Unable to enable the "Raw Image" button

### ISSUE THREAD

**Issue by HybridBits** [utmapp/UTM#5100]
While inside "Emulate > Custom > Other" I'm unable to enable the "Raw Image" button inside the "New Drive" area when using UTM 4.1.6 (75) on M1 Silicon Mac.

**Comment by HybridBits** [comment]
While you check that oddity out, is there a temporary method I could use to create a raw disk to use within the VM? Thanks in advance

**Comment by osy** [comment]
You can always create a qcow2 disk, then open the .utm bundle and replace that .qcow2 file with a raw image file you've created manually (like with dd if=/dev/zero or something).

**Comment by HybridBits** [comment]
That workaround worked like a charm! I used "qemu-img" to create the qcow2 disk -- thanks enormously :-)

**Comment by wim-vandijck-sp** [comment]
@HybridBits , did you have to do anything to boot into it? I converted the .img to qcow2 and put in the bundle, but the machine just hangs on the UEFI shell.

I have a script that will boot the img and a create a working system on a qcow2, but when I import that one, I just get a black screen.

Don't mean to hijack this thread ;) , is there a way to convert a qemu-system command line into a UTM config?
