### ISSUE TITLE
Does it support SUSE ?

### ISSUE THREAD

**Issue by ivan2375** [utmapp/UTM#5108]
**Describe the issue**  
It closes UTM app automatically after starting the SUSU server.
I installed the SUSE Linux Enterprise Server for SAP Application 12 sp4.  

**Configuration**  
* UTM Version: 4.1.6(75)
* macOS Version: 12.6.4
* Mac Chip (Intel, M1, ...): M1

**Debug log**  
Running:  -L /Applications/UTM.app/Contents/Resources/qemu -S -spice "unix=on,addr=/Users/ivan.hsu/Library/Group Containers/WDNLXAD4W8.com.utmapp.UTM/78352BDD-A294-4C3B-9A2D-F23FCCF4BB1C.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off" -chardev spiceport,id=org.qemu.monitor.qmp,name=org.qemu.monitor.qmp.0 -mon chardev=org.qemu.monitor.qmp,mode=control -nodefaults -vga none -device e1000,mac=4A:08:95:E9:96:9F,netdev=net0 -netdev vmnet-shared,id=net0 -device qxl-vga,vgamem_mb=2 -smp cpus=4,sockets=1,cores=4,threads=1 -machine q35,vmport=off,i8042=off -accel tcg,tb-size=3072 -global PIIX4_PM.disable_s3=1 -global ICH9-LPC.disable_s3=1 -drive if=pflash,format=raw,unit=0,file=/Applications/UTM.app/Contents/Resources/qemu/edk2-x86_64-code.fd,readonly=on -drive "if=pflash,unit=1,file=/Users/ivan.hsu/Library/Containers/com.utmapp.UTM/Data/Documents/SAP Hana Express.utm/Data/efi_vars.fd" -m 12288 -device intel-hda -device hda-duplex -usb -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device nec-usb-xhci,id=usb-controller-0 -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 -device ide-cd,bus=ide.0,drive=driveBE2A99C6-3CB1-4553-9DB6-E4D36104FBFC,bootindex=0 -drive if=none,media=cdrom,id=driveBE2A99C6-3CB1-4553-9DB6-E4D36104FBFC,readonly=on -device ide-hd,bus=ide.1,drive=driveB4E59A87-3CA8-4D11-BD82-658DDB08C46D,bootindex=1 -drive "if=none,media=disk,id=driveB4E59A87-3CA8-4D11-BD82-658DDB08C46D,file=/Users/ivan.hsu/Library/Containers/com.utmapp.UTM/Data/Documents/SAP Hana Express.utm/Data/B4E59A87-3CA8-4D11-BD82-658DDB08C46D.qcow2,discard=unmap,detect-zeroes=unmap" -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -name "SAP Hana Express" -uuid 78352BDD-A294-4C3B-9A2D-F23FCCF4BB1C -device virtio-rng-pci
qemu-x86_64-softmmu: warning: global PIIX4_PM.disable_s3=1 not used
qemu-x86_64-softmmu: warning: Spice: playback:0 (0x1490a9a70): setsockopt failed, Operation not supported on socket
qemu-x86_64-softmmu: warning: Spice: record:0 (0x1490a9b10): setsockopt failed, Operation not supported on socket

**Upload VM**

**Comment by osy** [comment]
Can you provide a crash log?

**Comment by ivan2375** [comment]
[Archive.zip](https://github.com/utmapp/UTM/files/10939775/Archive.zip)

**Comment by osy** [comment]
This is addressed in #4629

You can download https://github.com/utmapp/UTM/releases/tag/v4.2.0
