### ISSUE TITLE
Scammers shows a tutorial on how to install your app without pc without jb.

### ISSUE THREAD

**Issue by IIWare** [utmapp/UTM#511]
I was in YouTube and I saw scammers make a tutorial on how to install UTM without JB or pc (video [Here](https://www.youtube.com/watch?v=LXbHFJaIS_U) and other one [Here](https://www.youtube.com/watch?v=dTil3p55Gys)) normally I wouldn't create 2 issues at once, but since they're scamming and making UTM look like scammers did it, I needed you to know, I just wanted you to know so that you can do something about the videos, it's your app so I wanted to let you know about the UTM scams. thanks.

**Comment by saagarjha** [comment]
These are hilarious to watch, it's like very YouTube trope combined in a single video…

**Comment by osy86** [comment]
Yes, they’re hilarious and it’s not worth anybody’s time to deal with them.
