### ISSUE TITLE
It still crash when I install SUSE in UTM.

### ISSUE THREAD

**Issue by ivan2375** [utmapp/UTM#5114]
**Describe the issue**  
It still crashes. and I can't select another CPU during the installation period, It stopped the installation process and show " initial ramdisk" if I change the non-default CPU.

**Configuration**  
UTM Version: 4.2
macOS Version: 12.6.4
Mac Chip (Intel, M1, ...): M1

[debug.log](https://github.com/utmapp/UTM/files/10953229/debug.log)
[Archive.zip](https://github.com/utmapp/UTM/files/10953238/Archive.zip)

**Comment by osy** [comment]
Thanks, will re-open #4629

**Comment by osy** [comment]
Can you list what devices are plugged into your mac?

**Comment by osy** [comment]
Does your monitor have any audio built in?

**Comment by ivan2375** [comment]
Two monitors, one through HDMI and another through Type-C, all include audio also.
