### ISSUE TITLE
Can't mount shared directory

### ISSUE THREAD

**Issue by tomershukhman** [utmapp/UTM#5131]
**Describe the issue**  
Followed the instraction shown in https://docs.getutm.app/guest-support/linux/#macos-virtiofs
But still having no luck.

**Configuration**  
* UTM Version:   4.1.6 (75)
* macOS Version: 13.2.1 
* Mac Chip (Intel, M1, ...): M1

**Crash log**  
```
sudo mount -t virtiofs share /mnt
wrong fs type, bad option, bad superblock on share, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
```

**Comment by asoltesz** [comment]
~~~
pacman -S --needed spice-vdagent phodav
~~~

This does not seem to install virtiofs support on Manjaro ARM.
The mount command fails afterwards as well.

**Comment by sufehmi** [comment]
Seconding this - dmesg output shows the following error message:

`virtio-fs: tag <share> not found`

`pacman -S --needed spice-vdagent phodav` shows: 

`warning: spice-vdagent-0.22.1-3 is up to date -- skipping
warning: phodav-3.0-2 is up to date -- skipping
`
