### ISSUE TITLE
No submodules?

### ISSUE THREAD

**Issue by dgdosen** [utmapp/UTM#5135]
I've got Apple Developer credentials, and am trying to build UTM for iOS that has extended memory entitlements.

As I go through the readme, one thing I notice - when I clone the project, I'm not seeing any submodules.  There's no mention of them in the .git/config file nor is there a .gitmodules file in the repo.  Can you provide guidance as to what we should be seeing in terms of submodules?

It looks like qemu should be one of those projects, correct?

**Configuration (required)**
* UTM Version:  4.2.1
* OS Version:  iPadOS 16.3.1
* Device Model: M1 iPad Pro 11 2TB (16GB)
* Is it jailbroken (name jailbreak used)? 
* How did you install UTM? 
- multiple! via AltStore, via Xcode install

**Comment by osy** [comment]
Oh those instructions are outdated, there’s no more submodules. Everything else still applies though.
