### ISSUE TITLE
`virtio-net-device` in block list, even though my VM won't get a network connection without it

### ISSUE THREAD

**Issue by Intecpsp** [utmapp/UTM#5137]
https://github.com/utmapp/UTM/blob/d4139433585f4c3f1bd5d918bf4fc6484cb0dc7b/scripts/const-gen.py#L97-L102

I see `virtio-net-device` in the block list created under 3a54dab6f36d118d1c35f5f6c6d0e30bf1c5704a. My VM has had this configured for quite a while. I was in the settings on the VM this morning and noticed a blank drop-down. I couldn't remember which device I had been using, but `virtio-net-pci` sounded familiar, so I went with it. My VM booted up, but was not able to get an IP in bridged mode. After doing some research I came across this change and changed my plist file back to `device` and it was able to come up correctly. 

I wanted to open this issue to ask why it was put in the blocklist with a "we do not support" comment. This is working for me on MacOS, so the app supports this functionality. Was this comment for no support from the community will be provided, or the app itself didn't support it? Also, what can I/we do to get this removed from the blocklist?

**Comment by osy** [comment]
Can you post your config.plist? I was under the impression that the -device entries don’t work because they require a virtio bus.
