### ISSUE TITLE
qemu-system: -append only allowed with -kernel option

### ISSUE THREAD

**Issue by Nanoc-ice** [utmapp/UTM#515]
I have updated my 2018 iPad Pro 12.9 to 14.2 and running UTM 2.0b7.  
I had downloaded the ArchLinux ARM from the list of official VMs and have heavily modified it to run a GUI.  I copied it to a backup directory before upgrading to 2.0b7.  After upgrading I copied it back to the UTM directory, restarted UTM got the nice pretty new interface and started this VM.  It stopped without showing anything.  My x86_64 VMs work ok.  My Debian ARM did not start either.  I downloaded the Debian UTM from the official downloads and it started up.  So, back to my ArchLinux ARM.  I removed mine and re-downloaded the console ArchLinux ARM from the official VM location and tried it.  It crashed too.

I will add the debug and the crash log.  However, since it does it from the VM from the official site, it might be easier to get it from there and see if it does the same for you.

Debug log:

at debug.log
UTMTerminalIO does not support debug mode.
2020-11-05 09:48:36.894 UTM[929:523841] UTMTerminalIO does not support debug mode.
Loading libqemu-system-aarch64.utm.dylib
2020-11-05 09:48:36.942 UTM[929:523841] Loading libqemu-system-aarch64.utm.dylib
Running:  -L /private/var/containers/Bundle/Application/69E96230-85DE-46B8-AD4B-E8CC28CE753C/UTM.app/qemu -S -qmp tcp:localhost:4000,server,nowait -nographic -chardev pipe,id=term0,path=/private/var/mobile/Containers/Data/Application/46096553-A24A-4B2F-B113-50F32CB77EAC/tmp/ArchLinux-ARM.terminal -serial chardev:term0 -smp cpus=4,sockets=1 -machine virt, -accel tcg,mirror-rwx=on -cpu cortex-a72 -device virtio-gpu-pci -boot order=d -m 2048 -soundhw ac97 -name ArchLinux-ARM -drive if=virtio,media=disk,id=drive2,file=/var/mobile/Containers/Data/Application/46096553-A24A-4B2F-B113-50F32CB77EAC/Documents/ArchLinux-ARM.utm/Images/disk.qcow2 -device rtl8139,netdev=net0 -netdev user,id=net0 -device usb-ehci -device usb-tablet -device usb-mouse -device usb-kbd -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid E3459327-D6AC-409C-ABCA-08EAAC345F57 -rtc base=localtime -append "root=/dev/vda rw"
2020-11-05 09:48:36.958 UTM[929:523841] Running:  -L /private/var/containers/Bundle/Application/69E96230-85DE-46B8-AD4B-E8CC28CE753C/UTM.app/qemu -S -qmp tcp:localhost:4000,server,nowait -nographic -chardev pipe,id=term0,path=/private/var/mobile/Containers/Data/Application/46096553-A24A-4B2F-B113-50F32CB77EAC/tmp/ArchLinux-ARM.terminal -serial chardev:term0 -smp cpus=4,sockets=1 -machine virt, -accel tcg,mirror-rwx=on -cpu cortex-a72 -device virtio-gpu-pci -boot order=d -m 2048 -soundhw ac97 -name ArchLinux-ARM -drive if=virtio,media=disk,id=drive2,file=/var/mobile/Containers/Data/Application/46096553-A24A-4B2F-B113-50F32CB77EAC/Documents/ArchLinux-ARM.utm/Images/disk.qcow2 -device rtl8139,netdev=net0 -netdev user,id=net0 -device usb-ehci -device usb-tablet -device usb-mouse -device usb-kbd -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid E3459327-D6AC-409C-ABCA-08EAAC345F57 -rtc base=localtime -append "root=/dev/vda rw"
Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
QMP connection failed, retries left: 29
2020-11-05 09:48:36.960 UTM[929:525096] Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-05 09:48:36.960 UTM[929:525096] QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-05 09:48:36.960 UTM[929:525096] QMP connection failed, retries left: 29
qemu-system: -append only allowed with -kernel option
changeFont error: (null)
2020-11-05 09:48:37.070 UTM[929:523841] changeFont error: (null)
setCursorBlink error: (null)
2020-11-05 09:48:37.072 UTM[929:523841] setCursorBlink error: (null)
RPC: Error Domain=com.osy86.utm Code=-1 "No connection for RPC." UserInfo={NSLocalizedDescription=No connection for RPC.}
2020-11-05 09:48:37.110 UTM[929:525096] RPC: Error Domain=com.osy86.utm Code=-1 "No connection for RPC." UserInfo={NSLocalizedDescription=No connection for RPC.}
Terminal resize: (
    189,
    66
)
2020-11-05 09:48:37.524 UTM[929:523841] Terminal resize: (
    189,
    66
)
Connected to stream
QMP connection successful! (readStream:1)
Connected to stream
2020-11-05 09:48:38.059 UTM[929:525097] Connected to stream
QMP connection successful! (readStream:0)
2020-11-05 09:48:38.059 UTM[929:525097] QMP connection successful! (readStream:1)
2020-11-05 09:48:38.059 UTM[929:525097] Connected to stream
2020-11-05 09:48:38.059 UTM[929:525097] QMP connection successful! (readStream:0)
Stop operation timeout
2020-11-05 09:49:07.156 UTM[929:524865] Stop operation timeout
Successfuly disconnected!
2020-11-05 09:49:07.156 UTM[929:524865] Successfuly disconnected!
Input dispatch_io is being closed
Successfuly disconnected!
2020-11-05 09:49:07.157 UTM[929:525292] Input dispatch_io is being closed
2020-11-05 09:49:07.157 UTM[929:525291] Successfuly disconnected!
Cleanup completed!
Source got cancelled
2020-11-05 09:49:07.158 UTM[929:525291] Cleanup completed!
2020-11-05 09:49:07.158 UTM[929:525291] Source got cancelled
Exit operation timeout

Crash log file 1
at UTM-2020-11-05-093349.ips 
{"app_name":"UTM","timestamp":"2020-11-05 09:33:49.00 -0600","app_version":"2.0b7","slice_uuid":"fb4a076f-4026-36ff-85ce-e0a84f69ff87","adam_id":0,"build_version":"7","platform":2,"bundleID":"com.osy86.UTM.Beta","share_with_app_devs":0,"is_first_party":0,"bug_type":"109","os_version":"iPhone OS 14.2 (18B91)","incident_id":"C09BC7BC-AD25-4344-9163-5508E6BF67F5","name":"UTM"}
Incident Identifier: C09BC7BC-AD25-4344-9163-5508E6BF67F5
CrashReporter Key:   9980b7b35239f60a1b6bda075fb837e46bb7b628
Hardware Model:      iPad8,7
Process:             UTM [907]
Path:                /private/var/containers/Bundle/Application/69E96230-85DE-46B8-AD4B-E8CC28CE753C/UTM.app/UTM
Identifier:          com.osy86.UTM.Beta
Version:             7 (2.0b7)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.osy86.UTM.Beta [643]

Date/Time:           2020-11-05 09:33:49.1502 -0600
Launch Time:         2020-11-05 09:28:13.7532 -0600
OS Version:          iPhone OS 14.2 (18B91)
Release Type:        User
Baseband Version:    3.01.01
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000008
VM Region Info: 0x8 is not in any region.  Bytes before following region: 4343939064
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                   102eb4000-103178000 [ 2832K] r-x/r-x SM=COW  ...C/UTM.app/UTM

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [907]
Triggered by Thread:  7
...
Thread 5 name:  com.apple.uikit.eventfetch-thread
Thread 5:
0   libsystem_kernel.dylib              0x00000001bd7632d0 0x1bd75f000 + 17104
1   libsystem_kernel.dylib              0x00000001bd762660 0x1bd75f000 + 13920
2   CoreFoundation                      0x0000000190f09c30 0x190e69000 + 658480
3   CoreFoundation                      0x0000000190f03c14 0x190e69000 + 633876
4   CoreFoundation                      0x0000000190f0321c 0x190e69000 + 631324
5   Foundation                          0x00000001921afdf0 0x1921a7000 + 36336
6   Foundation                          0x00000001921afcbc 0x1921a7000 + 36028
7   UIKitCore                           0x00000001939effe4 0x192d75000 + 13086692
8   Foundation                          0x0000000192321a34 0x1921a7000 + 1550900
9   libsystem_pthread.dylib             0x00000001d9682b40 0x1d9681000 + 6976
10  libsystem_pthread.dylib             0x00000001d968b768 0x1d9681000 + 42856

Thread 6 name:  Dispatch queue: com.apple.root.background-qos
Thread 6:
0   libsystem_kernel.dylib              0x00000001bd76330c 0x1bd75f000 + 17164
1   libdispatch.dylib                   0x0000000190b83318 0x190b7f000 + 17176
2   libdispatch.dylib                   0x0000000190b839e0 0x190b7f000 + 18912
3   UTM                                 0x0000000102ec3e18 0x102eb4000 + 65048
4   libdispatch.dylib                   0x0000000190b8124c 0x190b7f000 + 8780
5   libdispatch.dylib                   0x0000000190b82db0 0x190b7f000 + 15792
6   libdispatch.dylib                   0x0000000190b93a68 0x190b7f000 + 84584
7   libdispatch.dylib                   0x0000000190b94120 0x190b7f000 + 86304
8   libsystem_pthread.dylib             0x00000001d96847c8 0x1d9681000 + 14280
9   libsystem_pthread.dylib             0x00000001d968b75c 0x1d9681000 + 42844

Thread 7 Crashed:
0   libphodav-2.0.0.utm.dylib           0x0000000104d616a4 0x104d1c000 + 284324
1   libphodav-2.0.0.utm.dylib           0x0000000104d6169c 0x104d1c000 + 284316
2   libphodav-2.0.0.utm.dylib           0x0000000104d61650 0x104d1c000 + 284240
3   ...client-glib-2.0.8.utm.dylib      0x000000010565d28c 0x10563c000 + 135820
4   ...client-glib-2.0.8.utm.dylib      0x000000010565d008 0x10563c000 + 135176
5   libgio-2.0.0.utm.dylib              0x0000000105303a00 0x105274000 + 588288
6   libgio-2.0.0.utm.dylib              0x00000001053027e4 0x105274000 + 583652
7   libgio-2.0.0.utm.dylib              0x0000000105302e54 0x105274000 + 585300
8   ...client-glib-2.0.8.utm.dylib      0x000000010567bed4 0x10563c000 + 261844
9   libglib-2.0.0.utm.dylib             0x00000001058c5920 0x10587c000 + 301344
10  libglib-2.0.0.utm.dylib             0x00000001058c9ab4 0x10587c000 + 318132
11  libglib-2.0.0.utm.dylib             0x00000001058c98ec 0x10587c000 + 317676
12  libglib-2.0.0.utm.dylib             0x00000001058c9e20 0x10587c000 + 319008
13  libglib-2.0.0.utm.dylib             0x00000001058ca330 0x10587c000 + 320304
14  UTM                                 0x0000000102ecc1d4 0x102eb4000 + 98772
15  libsystem_pthread.dylib             0x00000001d9682b40 0x1d9681000 + 6976
16  libsystem_pthread.dylib             0x00000001d968b768 0x1d9681000 + 42856

Thread 8:
0   libsystem_kernel.dylib              0x00000001bd7871ac 0x1bd75f000 + 164268
1   libsystem_pthread.dylib             0x00000001d9686458 0x1d9681000 + 21592
2   ...mu-system-aarch64.utm.dylib      0x000000011bfbe840 0x11b9b4000 + 6334528
3   ...mu-system-aarch64.utm.dylib      0x000000011bfc6710 0x11b9b4000 + 6366992
4   ...mu-system-aarch64.utm.dylib      0x000000011bfbea10 0x11b9b4000 + 6334992
5   libsystem_pthread.dylib             0x00000001d9682b40 0x1d9681000 + 6976
6   libsystem_pthread.dylib             0x00000001d968b768 0x1d9681000 + 42856

**Comment by IIWare** [comment]
what specifications of the VM did you use?

**Comment by Nanoc-ice** [comment]
I didn't set anything different then what the downloaded ArchLinux ARM UTM already had.  I did try using the graphic console rather then the text console once to see if that would make any difference.  Otherwise, that UTM has a QEMU option: -append "root=/dev/vda rw" which is different then the Debian ARM UTM VM.  Also, it had the kernel initrd and base disk all set to whatever was set originally.  Bottom line I didn't change anything, just downloaded the VM start UTM and tried to start the VM
