### ISSUE TITLE
Include the option to add USB devices on completely headless systems

### ISSUE THREAD

**Issue by parasaito** [utmapp/UTM#5157]
Currently, in order to add USB devices to headless VMs, you need to have at least some kind of terminal open. But with a setup such as no terminal or Pseudo-TTY, the only option is to turn off the VM, change the config to built-in-terminal and finally be able to mount USB device from it's menubar.

If the option to add USB devices could be added to the main UTM window, or the macOS global menu bar, it would be huge convenience.

Why would you need mount/remount USB devices on headless machine? Headless VMs are a great way to get Linux environment for programming, without having to deal with graphical glitches of a DE. Programming and debugging Microcontrollers is one of the application I am interested in, where this feature would come extremely handy.

**Comment by phraemer** [comment]
@osy I did see this issue before creating my own but since this isn't quite what I was requesting does your closing of my issue mean that something is coming to `utmctl` and this issue covers that?

Thanks for any clarification.

**Comment by osy** [comment]
Yes, the idea is to add to `utmctl` and the scripting interface a way to list, attach, and detach USBs as you said.

**Comment by phraemer** [comment]
It works! Thank you very much.
