### ISSUE TITLE
Windows 11 arm64 showing blank screen after starting on UTM

### ISSUE THREAD

**Issue by princessdharmy** [utmapp/UTM#5161]
After creating Windows 11 arm64 VM using the `22000.160` build, I started the VM but showed a blank screen.

**Configuration**  
* UTM Version: 4.1.6
* macOS Version: Monterey 12.6.4
* Mac Chip (Intel, M1, ...): M1

**Screenshots**  

<img width="500" alt="Screenshot 2023-03-31 at 20 43 40" src="https://user-images.githubusercontent.com/27359181/229231733-032087ab-617e-42fa-a800-83348cbc6255.png">
<img width="500" alt="Screenshot 2023-03-31 at 20 33 25" src="https://user-images.githubusercontent.com/27359181/229231720-ad8902dd-6a28-4cc2-9045-26529df7d9e9.png">

**Comment by brenoraffa22** [comment]
Solved?

**Comment by princessdharmy** [comment]
> Solved?

Yes.

**Comment by grgar** [comment]
Please could you explain how @princessdharmy I have the same problem

**Comment by princessdharmy** [comment]
> Please could you explain how @princessdharmy I have the same problem

@grgar I wrote [an article](https://medium.com/@princessdharmy/installing-windows-11-on-macbook-m1-arm64-e1e7e0f52ce0) on it.

**Comment by prosperot** [comment]
> > Please could you explain how @princessdharmy I have the same problem
> 
> @grgar I wrote [an article](https://medium.com/@princessdharmy/installing-windows-11-on-macbook-m1-arm64-e1e7e0f52ce0) on it.

thats of no use. did you solve it, or just spamming your website?

**Comment by maxim-smirnov** [comment]
@prosperot 
Just check "Use Hypervisor" checkbox to be enabled under QEMU options of the VM. Did the trick for me.

**Comment by j3ko** [comment]
The problem is that you have to bypass the internet connection screen.  When you get to the "Let's connect you..." screen you must:

1. Press shift + F10 (or shift + fn + F10 depending on your settings)
2. Type 
   ```
   oobe\bypassnro
   ```
3. Press Enter and it will restart
4. Redo the process and when you get to the same screen select the new option "I don't have internet"
5. Continue with installation

Install the drivers at `D:\utm-guest-tools-x.xxx` to connect to the internet after you are up and running.  

When you first get to the "Let's connect you..." screen and try to install drivers from `D:\`, it will not work and when it reboots it hangs on a black screen.  That was my problem at least.

**Comment by mustafaabobakr** [comment]
> * Press shift + F10 (or shift + fn + F10 depending on your settings)
> * Type
>   ```
>   oobe\bypassnro
>   ```
> * Press Enter and it will restart
> * Redo the process and when you get to the same screen select the new option "I don't have internet"
> * Continue with installation

# @j3ko THANK YOU 🫡 

![image](https://github.com/user-attachments/assets/7d6268ee-6052-4dda-883b-d28a10e4c22d)

**Comment by mustafaabobakr** [comment]
## For future reference 
> [!TIP]
> To solve this `The file size exceeds the limit allowed and cannot be saved`
> ![image](https://github.com/user-attachments/assets/f5d0605e-4cd7-4017-8a90-da2a8642a035)

1. Open regedit by 
   - Press `command + R` 
   - Type `regedit`
3. in the address bard go copy the following and press enter
```
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WebClient\Parameters
```
4. Open the `FileSizeLimitinBytes`
5. Add max value `ffffffff`

![image](https://github.com/user-attachments/assets/2105f691-78fd-4946-9abc-665d94813ea2)

**Comment by d33p-dev** [comment]
Hmm, having same issue.  Checked all references above but my VM still has black screen after boot.  I went through setup (it never prompted for Connect to Network in my setup) and it downloaded updates during install.  It booted fine and then it auto-installed the guest tools.  After guest tools installed it rebooted and now I have the black screen.  I can hear Windows sign in sound notification so I guess technically it booted into the desktop  or the login screen.  But, the screen is all black...  Verified my settings have QEUM settings as noted above, the correct display driver but no luck...

**Comment by megumin31** [comment]
> Hmm, having same issue. Checked all references above but my VM still has black screen after boot. I went through setup (it never prompted for Connect to Network in my setup) and it downloaded updates during install. It booted fine and then it auto-installed the guest tools. After guest tools installed it rebooted and now I have the black screen. I can hear Windows sign in sound notification so I guess technically it booted into the desktop or the login screen. But, the screen is all black... Verified my settings have QEUM settings as noted above, the correct display driver but no luck...

hello, have you find a solution for this? I am having the same issue too
