### ISSUE TITLE
Error libusb_open: No such device (it may have been disconnected) [-4]

### ISSUE THREAD

**Issue by UInt2048** [utmapp/UTM#5164]
**Describe the issue**  
Attempted to bring iPad into macOS guest VM but failed

**Configuration**  
* UTM Version: 4.2.2 (78)
* macOS Version: 13.1
* Mac Chip (Intel, M1, ...): Intel

**Crash log**  
UTM did not crash.

**Comment by osy** [comment]
Duplicate of #3063
