### ISSUE TITLE
Cannot print

### ISSUE THREAD

**Issue by JeffVader1** [utmapp/UTM#5175]
I am not computer savvy, but I managed to get UTM and Windows 10 Arm version going on my new MacBook.  Windows 10 seems to run find except I cannot get it to find a printer.  Not my Epson printer or even a PDF printer.  I've been searching here and the internet to see if anyone can tell me what I am doing wrong.

MacBook Pro M2 running Ventura 13
UTM Version 4.1.6 (75)
Venturea 13.0
M2

There is no crash log. It just says cannot find printer.

I know this is probably something stupid for the wiz's that are on this site, but I really could use some help.   I've been trying for hours to get it to work.  

Jeff

Thanks for any help you can provide.

**Comment by conath** [comment]
Which kind of connection does your MacBook have to your printer? Is it WiFi, LAN, USB? 

If the printer is on your network (WiFi or Ethernet/LAN) you'll have to also place your VM on the same network. In UTM this is achieved by the "Shared" or "Bridged" network mode. To enable this, shut down your VM and select it in UTM, then click the right-most button in the toolbar to edit the VM configuration. Choose Network in the Devices section and then change the mode to Shared Network:
![Screenshot 2023-04-09 at 11 49 56](https://user-images.githubusercontent.com/12073163/230766085-a092d6e8-be85-4803-baa2-e1e9eb8b9e61.jpg)
Click Save, then start the VM again and try to add your printer in Windows.

If the printer is connected via USB cable, you'll want to use the USB Sharing feature instead. This should be enabled by default, but you can double-check in the VM configuration → Sharing: 
![Screenshot 2023-04-09 at 12 01 26](https://user-images.githubusercontent.com/12073163/230766530-a9339314-d46d-46f1-8710-d3332ed6a58f.jpg)
Then just unplug and re-plug the printer while the VM is running, and you'll get a popup asking if it should be connected to the VM.

Hope this helps!

**Comment by JeffVader1** [comment]
Thank you for replying to my plea for help.  I am trying to get my printer to work over Wi-Fi .  I looked at the setting you suggested and it was already set to shared . I tried toggling off and on and that didn’t help either.  Also I don’t know if this is relevant but with in windows arm64, I can’t find the Wi-Fi settings where they normally would be . Any further suggestions you might have would be very appreciated.Thanks , JeffSent from my iPhoneOn Apr 9, 2023, at 5:05 AM, CONATH ***@***.***> wrote:﻿
Closed #5175 as completed.

**Comment by conath** [comment]
Please try again and choose the "Bridged" network mode instead.

Indeed, you can't see the usual Wi-Fi settings in Windows because your VM is using the existing network connection of your Mac, and not creating its own connection to the Wi-Fi.

**Comment by hpstr2023** [comment]
I had the same problem. Open settings on the Mac, go to printers and scanners. Switch on the option ‘share to network’ after that the printer was available in windows

**Comment by MacGuy99** [comment]
> Which kind of connection does your MacBook have to your printer? Is it WiFi, LAN, USB?
> 
> If the printer is on your network (WiFi or Ethernet/LAN) you'll have to also place your VM on the same network. In UTM this is achieved by the "Shared" or "Bridged" network mode. To enable this, shut down your VM and select it in UTM, then click the right-most button in the toolbar to edit the VM configuration. Choose Network in the Devices section and then change the mode to Shared Network: ![Screenshot 2023-04-09 at 11 49 56](https://user-images.githubusercontent.com/12073163/230766085-a092d6e8-be85-4803-baa2-e1e9eb8b9e61.jpg) Click Save, then start the VM again and try to add your printer in Windows.
> 
> If the printer is connected via USB cable, you'll want to use the USB Sharing feature instead. This should be enabled by default, but you can double-check in the VM configuration → Sharing: ![Screenshot 2023-04-09 at 12 01 26](https://user-images.githubusercontent.com/12073163/230766530-a9339314-d46d-46f1-8710-d3332ed6a58f.jpg) Then just unplug and re-plug the printer while the VM is running, and you'll get a popup asking if it should be connected to the VM.
> 
> Hope this helps!

Helloo,

My VM (UTM) is running Windows 11 and I am using a USB printer. The VM is not able to detect the printer and I am not able to install the driver that I downloaded from HP website for Windows 11.

How would you address this issue?
