### ISSUE TITLE
Cannot capture mouse with Apple Virtualization

### ISSUE THREAD

**Issue by vincent-olivert-riera** [utmapp/UTM#5176]
**Describe the issue** 
 
This is something that works fine when using QEMU:
- `ctrl` + `alt` captures the mouse.
- Clicking the "Capture mouse cursor" button captures the mouse.

However, when using Apple Virtualization:
- `ctrl` + `alt` does not capture the mouse.
- The "Capture mouse cursor" button is disabled.

---

* UTM Version: 4.1.6
* macOS Version: Ventura 13.3 
* Mac Chip: M1
* Guest: Debian 11

**Comment by osy** [comment]
That feature is not supported by Apple Virtualization and has been removed in 4.2.x
