### ISSUE TITLE
macOS) UTM is damaged and can't be opened

### ISSUE THREAD

**Issue by obbcth** [utmapp/UTM#518]
**Describe the bug**

UTM is damaged and can't be opened

**Version**

UTM v2.0.8, macOS Big Sur 11.0.1 Beta (20B5012d)

**To Reproduce**
1. Download UTM v2.0.8 dmg
2. Move app to application folder
3. Launch

**Screenshots**

![스크린샷 2020-11-06 오후 2 49 28](https://user-images.githubusercontent.com/12216587/98331320-afd60780-203f-11eb-8bbd-fe39a63e1edb.png)

(In English, 'UTM is damaged and can't be opened'. Blue button is 'Move to Trash'.)

**Comment by osy86** [comment]
You must sign it or bypass gatekeeper somehow.

**Comment by obbcth** [comment]
Solved with this command: sudo spctl --master-disable
Thanks.
