### ISSUE TITLE
Windows 11 image Setup loop

### ISSUE THREAD

**Issue by asyba** [utmapp/UTM#5199]
Every time that I shutdown the Windows 11 virtual and turn on again, I have to install windows 11 again, always. it doest persist

**Comment by asyba** [comment]
and some times doing a new install, it makes a loop of constantly installing and rebooting.

**Comment by asyba** [comment]
found the issue, if you click any key during BIOS when it ask please click any key to boot from CD...
dont do that, just wait.

**Comment by aiyogg** [comment]
> found the issue, if you click any key during BIOS when it ask please click any key to boot from CD... dont do that, just wait.

Thank you, nobody told me this.
