### ISSUE TITLE
Black screen when start a VM (iOS 14.2)

### ISSUE THREAD

**Issue by W-MS** [utmapp/UTM#520]
When starting a VM, it keeps a black screen no matter what it is or it has a disk or not.
iOS 14.2, 2.0.8 IPA from Github release, signed by ios-app-signer from dantheman827.

**Comment by brunocastello** [comment]
Unless your iDevice SoC is newer than A11, you're out of luck.

**Comment by osy86** [comment]
Please attach a crash log

**Comment by osy86** [comment]
Please test with an empty VM (new vm, change nothing, save).

**Comment by gongcf** [comment]
test empty VM:  black screen. nothing change. 
ipad pro 2020. ipadOS 12.4. resign ipa.

**Comment by W-MS** [comment]
14.2 or 12.4?





------------------ Original ------------------

**Comment by osy86** [comment]
I’ve managed to reproduce this. You need to sign with a development certificate. Not a distribution certificate. More info at bottom of https://getutm.app/install/

**Comment by gongcf** [comment]
> 14.2 or 12.4?
> […](#)
> ------------------ Original ------------------ From: gongcf <notifications@github.com&gt; Date: Mon,Nov 9,2020 1:01 PM To: utmapp/UTM <UTM@noreply.github.com&gt; Cc: W-MS <w.ms@qq.com&gt;, Author <author@noreply.github.com&gt; Subject: Re: [utmapp/UTM] Black screen when start a VM (iOS 14.2) (#520) test empty VM: black screen. nothing change. ipad pro 2020. ipadOS 12.4. resign ipa. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

sorry.  14.2.

**Comment by gongcf** [comment]
> I’ve managed to reproduce this. You need to sign with a development certificate. Not a distribution certificate. More info at bottom of https://getutm.app/install/

running ok! 3ks!
