### ISSUE TITLE
Issue with Polish translation [macOS]

### ISSUE THREAD

**Issue by matgaj** [utmapp/UTM#5212]
There is an error in the "Monitor" tab in the app settings.

Is: "Rozmiar ekranu wirtualnej maszyny jest naprawiony"
Should be: "Rozmiar ekranu wirtualnej maszyny jest zablokowany"

zablokowany - fixed, locked
naprawiony - fixed, repaired

If there's an option to help translate the app, I'd happily contribute

**Comment by osy** [comment]
Thanks for the feedback. If you want to contribute more changes, feel free to fork the repository and make modifications to https://github.com/utmapp/UTM/blob/main/Platform/pl.lproj/Localizable.strings as well as other localization files.

**Comment by osy** [comment]
Fixed with 83eeefc969fd18f6b5a25ab5c51416a9b1987e82
