### ISSUE TITLE
Application menu unresponsive after launching UTM console

### ISSUE THREAD

**Issue by cgbin24** [utmapp/UTM#5235]
**Describe the issue**  

Some exceptions occur when starting the UTM console, as follows:
> ps: This has not happened in comparison with other applications, and it cannot be resolved after restarting the operating system
1. After opening the console, the application menu item in the upper left corner does not display the corresponding information of the UTM application [0-10 seconds means that the application menu is not displayed normally]
2. After switching the window, the UTM application menu information appears [10-13 seconds is the switching window, and the application menu is displayed]
3. The application menu after it appears cannot be clicked, and the response cannot be triggered [13-16 seconds are all click operations]
4. The virtual machine cannot enter the full screen state, but can only be zoomed [18-23 seconds is the zoom operation]

**Configuration**
* UTM Version:  4.1.6 (75)
* macOS Version:  Ventura 13.0
* Mac Chip (Intel, M1, ...):  M1

**Crash recurrence**  

https://user-images.githubusercontent.com/46283404/233851267-4ccdc4cd-23f0-487e-b149-5ea99a8b59bc.mp4

**Comment by osy** [comment]
In preferences (Cmd+,) do you have "show dock icon" checked?

**Comment by cgbin24** [comment]
> 

It was unchecked before, when I checked it and restarted UTM the problem was solved, thanks a lot.

![image](https://user-images.githubusercontent.com/46283404/233913952-6a0b6963-fc93-4e3a-ad18-f186974e88e9.png)


But I have another question, how can I edit the memory size for an installed virtual machine, for example: I previously allocated `64 GB` and now I want to adjust it to `100 GB`, when I try to modify `Resize` under `NVMe Drive` it doesn't change

![image](https://user-images.githubusercontent.com/46283404/233916705-b43b0a84-e215-4319-a6f4-771426b277ea.png)

**Comment by osy** [comment]
It seems like you already changed it to 100GB. You then need to expand your file system in the guest operating system. It’s the same thing if you physically buy a harder hard drive and you clone your old drive. You need to expand the file system.

**Comment by cgbin24** [comment]
> It seems like you already changed it to 100GB. You then need to expand your file system in the guest operating system. It’s the same thing if you physically buy a harder hard drive and you clone your old drive. You need to expand the file system.

Okay, I'll try, thanks.
