### ISSUE TITLE
Version 4.2.4 could not control the mouse pointer

### ISSUE THREAD

**Issue by ChengLuffy** [utmapp/UTM#5237]
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Describe the issue**  
I only have one macOS 12 virtual machine and when I upgraded UTM to 4.2.4, I could not control the mouse pointer in the virtual machine, when I reverted back to the previous version (4.1.6) everything was back to normal

**Configuration**  
* UTM Version: 4.2.4
* macOS Version: 13.3.1
* Mac Chip (Intel, M1, ...): M1

**Crash log**  

**Debug log**  

**Upload VM**

**Comment by osy** [comment]
We recently changed the mouse/trackpad device due to issues people had with double clicking. Curious if the issue persists if you reinstall a new vm?
