### ISSUE TITLE
VM disk size doesn't change

### ISSUE THREAD

**Issue by LostInCompilation** [utmapp/UTM#5241]
**Describe the issue**  
I already opened an issue regarding the disk size shown in the main window and in the VM settings window not matching #4741. However now it got worse: The size displayed now shows a constant value which is always an integer for all VMs (which cannot be right). Every VM now shows 3GB or 6GB, nothing else, even if the actual disk size is something completely different. Also reclaiming or compressing doesn't change this value. I still suspect the cause somehow linked to compressing the drive.

EDIT: After clicking `Edit` on one VM the disk sizes suddenly changed. Now they show decimal values again. But the values are still different with the size displayed in the VM settings window and the actual file size of the VM. I don't know what's happening there, something seems really randomly wrong.

EDIT2: And now after starting one VM, all other VM again are back to displaying only 3GB or 6GB. That's really strange.

**Configuration**  
* UTM Version: 4.1.6
* macOS Version: 13.3.1
* Mac Chip: M1 Pro

**Comment by osy** [comment]
Can you provide screenshots of where the inconsistency are seen along with a screenshot of the get info screen from finder on the disk image?

**Comment by osy** [comment]
Okay, that is different from what you described in your issue. What you showed here is what's reported in #4741 not in this one?

**Comment by LostInCompilation** [comment]
Yes somehow I cannot get UTM to show the 3GB and 6GB values anymore. It appears quite random, I don't know how to cause the issue. I'll try to make it happen again.
The screenshots show the issue like reported in #4741.

**Comment by osy** [comment]
I will close this issue and will re-open when you can provide screenshots.

**Comment by LostInCompilation** [comment]
Sounds good. I'll mention you here when I have screenshots.
