### ISSUE TITLE
Crash when selecting boot iso image in the creation wizard

### ISSUE THREAD

**Issue by Flameborn** [utmapp/UTM#5250]
After selecting a boot iso image in the creation wizard, the file browse window closes and UTM (v4.2.4 and v4.2.5) quit unexpectedly.

The crash happens regardless of the selected image, tested via a  Windows (10/11 22H) and an official Arch Linux image.

This is on a late 2014 Mac Mini, using macOS Monterey 12.6.5.

I use VoiceOver, in case this makes a difference.

**Comment by osy** [comment]
Is it possible to get a crash log?

**Comment by Flameborn** [comment]
[UTMCrashReport.log](https://github.com/utmapp/UTM/files/11334527/UTMCrashReport.log)

**Comment by Flameborn** [comment]
Attached: [UTMCrashReport.log](https://github.com/utmapp/UTM/files/11334546/UTMCrashReport.log)

**Comment by osy** [comment]
That's strange. I tried on a 2018 Mac mini running 12.6.5 with VoiceOver enabled (English). Opened UTM, clicked the +, chose Virtualize, Windows, and selected an ISO and pressed next. I did not get a crash. Is there anything else you're doing?

**Comment by Flameborn** [comment]
No, these are the exact steps I am doing as well, except I use the keyboard to navigate and click (ctrl+option+arrows to move, ctrl+option+shift+down to interact with containers, and ctrl+option+space to click)..

**Comment by Flameborn** [comment]
It might be a keyboard focus or accessibility issue. The exact steps after selecting Virtualisation and Windows are (ctrl+option = vo):

1. Find the scroll area with vo+right, and interact with it with vo+shift+down.
2. Move right with vo+right until you find the list (should be one control away). Interact with vo+shift+down.
3. Navigate with vo+right until VoiceOver says *Path, Browse… button* and interact with vo+shift+down.
4.  The *Browse* button should be one vo+right away. Click with vo+space.
5. Select the iso image via tab, arrows, and confirm with enter. 
The crash should happen there.

**Comment by osy** [comment]
Okay I tracked down the issue. It’s (surprise) a problem with SwiftUI. There’s a race caused by isBusy=true when you select an image and the browse button disabled with isBusy. My guess is that when you navigate with the keyboard it changes the order of operations. I am only able to reproduce it though by artificially introducing delay with Task.sleep so I think the issue is also because your machine is too slow. If your machine is faster, then the right thread would win the race :)

I also found that the issue no longer shows up on latest Ventura so FWIW, that could be a workaround. Will try to work on a fix though but it won’t be pretty…

**Comment by Flameborn** [comment]
Thank you very much for tracking this down.

Unfortunately, late 2014 Minis do not receive updates anymore, so Ventura is not a viable path for me.

Without looking at where and when *isBusy* is set, would it solve the issue if there was a small delay after selecting the image on anything lower than Ventura? Or perhaps locking a thread until the conditions are right for it to continue?
 I know it's not pretty, but even one crash in ten would be great 😀

Thanks again.

**Comment by osy** [comment]
The problem in searching for a solution is to try not making things worse for other people who don’t have VoiceOver enabled. The issue fundamentally stems from something happening (data race) that SwiftUI was explicitly designed to not have and so trying to fix it is a lot of trial and error.

**Comment by SeedyThreeSixty** [comment]
I'm using UTM 4.2.5 on a 2017 Macbook Air running Monterey 12.6.2 with VoiceOver enabled, and also experiencing the crash.

**Comment by SeedyThreeSixty** [comment]
I'm using UTM 4.2.5 on a 2017 Macbook Air running Monterey 12.6.2 with VoiceOver enabled and I'm also experiencing the crash.
