### ISSUE TITLE
Update clock when host wakes up from sleep

### ISSUE THREAD

**Issue by osy** [utmapp/UTM#5252]
Please browse the existing issues and filter by 'enhancement' to make sure this has not already been suggested!

**Comment by asoltesz** [comment]
I have updated to 4.5 for this but I do not think it works.

My Debian VM de-synchronizes just like before.

Are there some special steps that are needed to get the correct time into the VMs after the Macbook resuming from sleep ?

**Comment by umanwizard** [comment]
This is also not working for me on 4.5.0. aarch64 Fedora guest.

**Comment by kenji21** [comment]
Source code in commit https://github.com/utmapp/UTM/commit/6f07ed07829121b3983c56984c34e814dc3674d5 is only referring to Qemu, and not Apple Virtualization, I think that's why it does not work

**Comment by maartendijkstra** [comment]
This is also not working for me on QEMU on a Mac with Version 4.4.5 (94) and a Ubuntu 22.04 image.
The UTM date is out of sync when the Macbook is waking up from sleep.

**Comment by ahrex** [comment]
@osy, can we re-open this issue? Please and thank you!

**Comment by osy** [comment]
@ahrex if you are experiencing this issue, open a new one and provide all the requested information from the issue template

**Comment by tomrobbo** [comment]
For people who come here still experiencing like I was, 
Clock drifted after host sleep until I installed `qemu-guest-agent `in the guest
See QEMU agent in https://docs.getutm.app/guest-support/linux/
