### ISSUE TITLE
Unable to open UTM

### ISSUE THREAD

**Issue by shanxiong-wei** [utmapp/UTM#526]
There is no response to clicking the UTM icon on the desktop.

**Comment by IIWare** [comment]
if you're in mac os big sur did you update your mac os big sur? I think beta 6 is broken.
what version of utm did you use?

**Comment by shanxiong-wei** [comment]
> 如果您在Mac OS Big Sur中，您是否更新了Mac OS Big Sur？我认为Beta 6已损坏。
> 您使用的是哪个版本的utm？

in ipados14.1;Use version 2.0.9 of UTM

**Comment by shanxiong-wei** [comment]
> if you're in mac os big sur did you update your mac os big sur? I think beta 6 is broken.
> what version of utm did you use?

in ipados14.1;Use version 2.0.9 of UTM

**Comment by IIWare** [comment]
in iOS/iPadOS 14.0, 14.0.1 and 14.1, You need to Jailbreak, and then you can install and run UTM (You can also use Xcode tethering, but that's not really convenient).

in iOS/iPadOS 14.2, You don't need Jailbreak, you can install UTM using AltStore 1.4.2, or you can also install UTM using [iOS App Signer](https://dantheman827.github.io/ios-app-signer/) in your mac to your iOS.

**Comment by shanxiong-wei** [comment]
> in iOS/iPadOS 14.0, 14.0.1 and 14.1, You need to Jailbreak, and then you can install and run UTM (You can also use Xcode tethering, but that's not really convenient).
> 
> in iOS/iPadOS 14.2, You don't need Jailbreak, you can install UTM using AltStore 1.4.2, or you can also install UTM using [iOS App Signer](https://dantheman827.github.io/ios-app-signer/) in your mac to your iOS.

My iPad device has been jailbreaked.

UTM has been installed, but it can't be opened (clicking on the icon does not respond).

**Comment by IIWare** [comment]
does it open and then suddenly close?

**Comment by shanxiong-wei** [comment]
No, clicking on the UTM icon doesn't respond to anything.
No flashback.

**Comment by IIWare** [comment]
Where's the log

**Comment by shanxiong-wei** [comment]
where workbench errors are logged,please?

**Comment by IIWare** [comment]
go to settings in your phone
go to privacy
go to Analytics and Improvements
go to Analytics Data
scroll until you find a utm log
tell me the log

**Comment by shanxiong-wei** [comment]
![~C1@YZ@{_KEU U(YG$G A O](https://user-images.githubusercontent.com/54581253/98811335-a7c10200-245b-11eb-8fa8-ad62b600fbe2.png)


The log of UTM was not found,
 only this one

**Comment by shanxiong-wei** [comment]
> go to settings in your phone
> go to privacy
> go to Analytics and Improvements
> go to Analytics Data
> scroll until you find a utm log
> tell me the log

[RPReplay_Final1605101301.zip](https://github.com/utmapp/UTM/files/5524257/RPReplay_Final1605101301.zip)

This is the Screenshot
You can see the click without responding

**Comment by IIWare** [comment]
Reinstall UTM, Try installing via AltStore or [iOS App Signer](https://dantheman827.github.io/ios-app-signer/) or install ipa using xcode. (installing via xcode isn't like xcode tethering) if the problem persists, you can update to 14.2, don't worry, you can jailbreak ios 14.2 like ios 14.1, but the nvram is locked in jailbreak, but you can still jb, if you don't prefer to update then wait for the issue to be fixed.

**Comment by Deniz1433** [comment]
Same exact problem for me (IOS 14.0.1)

**Comment by osy86** [comment]
Have appsync and install with reprovision.

**Comment by shanxiong-wei** [comment]
> Have appsync and install with reprovision.

Appsync already exists.
What does "install with reconstruction" mean?

**Comment by osy86** [comment]
https://github.com/Matchstic/ReProvision

**Comment by IIWare** [comment]
@shanxiong-wei to install reprovision:

1. open cydia
2. go to sources
3. click the edit button
4. click the add button
5. type in: **https:‌//repo.incendo.ws/**
6. click Add source
7. once finished go to search at the bottom right
8. search for ReProvision
9. click ReProvision
10. click Install and click confirm
11. once finished, at the home screen you can see ReProvision

**Comment by shanxiong-wei** [comment]
> @shanxiong-wei to install reprovision:
> 
> 1. open cydia
> 2. go to sources
> 3. click the edit button
> 4. click the add button
> 5. type in: **https:‌//repo.incendo.ws/**
> 6. click Add source
> 7. once finished go to search at the bottom right
> 8. search for ReProvision
> 9. click ReProvision
> 10. click Install and click confirm
> 11. once finished, at the home screen you can see ReProvision

What does "invalid neg prot HMAC" mean?
Please tell me the meaning of this sentence

**Comment by osy86** [comment]
This is getting off topic, please resolve this outside of the issue tracker. Thanks.
