### ISSUE TITLE
Trackpad scroll direction is inverted in a macos guest

### ISSUE THREAD

**Issue by seen76** [utmapp/UTM#5272]
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Describe the issue**  
Trackpad scroll direction is inverted in a macos guest and cannot be changed as there is no trackpad device in system settings

**Configuration**  
* UTM Version: 4.2.5
* macOS Version: host 13.2.1 guest 13.3.1
* Mac Chip (Intel, M1, ...): M2

**Comment by seen76** [comment]
additional info: probably its not reverted, but its "natural" always. I use unnatural in my host os, and its not being respected in the guest, neither can i set it.

**Comment by fmsjd** [comment]
The trackpad settings is inaccessible, but you can go into _the mouse settings option_ and untick the "Scroll direction: Natural" checkbox.

**Comment by seen76** [comment]
Unfortunately, that is not the case as there is no mouse settings either:

**Comment by seen76** [comment]
I accidentally closed the issue. 
<img width="525" alt="Screenshot 2023-05-05 at 9 43 56 AM" src="https://user-images.githubusercontent.com/6997557/236403036-1a5fe34a-87b7-4460-8f82-1a83acef0be6.png">

**Comment by fmsjd** [comment]
> I accidentally closed the issue. <img alt="Screenshot 2023-05-05 at 9 43 56 AM" width="525" src="https://user-images.githubusercontent.com/6997557/236403036-1a5fe34a-87b7-4460-8f82-1a83acef0be6.png">

Oh, I can't help with that then sorry.

**Comment by dnyrivera** [comment]
I use this command in the terminal and works for me 

You can use the Terminal to disable natural scrolling (also known as reverse scrolling) on macOS by changing the relevant system preference using the `defaults write` command. Here's how to do it:

1. Open the Terminal application. You can find it in the Utilities folder within the Applications folder, or you can use Spotlight Search to find and open it.

2. To disable natural scrolling, use the following command:
   
   ```bash
   defaults write -g com.apple.swipescrolldirection -bool false
   ```

   This command sets the "com.apple.swipescrolldirection" preference to "false," which turns off natural scrolling.

3. After running the command, you may need to log out and log back in, or restart your Mac for the changes to take effect.

If you ever want to enable natural scrolling again, you can use the following command:

```bash
defaults write -g com.apple.swipescrolldirection -bool true
```

Again, you may need to log out or restart for the changes to be applied.
