### ISSUE TITLE
Right click in macOS VM got worse

### ISSUE THREAD

**Issue by LostInCompilation** [utmapp/UTM#5288]
As far as I know there where reports about right clicking in a macOS VM didn't work correctly. I think I read there where some changes with the last release.
However right clicking got worse for me now. I sometimes have to right click three times before it registers. Previously it was rare if I had to click two times.

**Configuration**  
* UTM Version: 4.2.5
* macOS Version: 13.3.1 (VM too)
* Mac Chip: M1 Pro

**Comment by osy** [comment]
Have you tried changing to trackpad in settings?

**Comment by LostInCompilation** [comment]
Oh, that seems to solve it. Classic RTFM, didn't check what this option does.

**Comment by masag1** [comment]
Worked for me if you use two fingers (index and middle finger) to tap on the pad at the same time?
