### ISSUE TITLE
Two small bugs

### ISSUE THREAD

**Issue by dysl357085918** [utmapp/UTM#529]
Utm is a really nice software. But I may found two issues.
1. after airdrop the vm to my mac. The sharing windows can't be close, it repeatly pop up. 
2. Even if I delete the iso file with in a vm, it seems it is still here. I found this after I open the .utm file which airdroped to my mac. 

ipad pro 2020, ios 14.2

**Comment by osy86** [comment]
1. You mean the iOS pop up? UTM doesn’t control airdrop so this is an iOS issue.
2. This should be fixed in 2.0.9. Can you confirm if you’re running 2.0.9?
