### ISSUE TITLE
Spice works on Ubuntu, not on Debian guests

### ISSUE THREAD

**Issue by lelegard** [utmapp/UTM#5314]
**Configuration**  
* UTM Version: 4.2.5
* macOS Version: 13.3.1
* Mac Chip: M1

Ubuntu 23.04 guest:
- Installed several months ago with a previous version of UTM.
- `spice-vdagent` 0.22.1-3 is installed.
- It works correctly:
  - The display is reconfigured on resize.
  - The shared folder is correctly mounted.

Debian 11.7 guest:
- Just installed using UTM 4.2.5.
- `spice-vdagent` 0.20.0-2 is installed.
- Does not work:
  - The display is not reconfigured on resize, it proportionally shrinks or enlarges.
  - The shared folder cannot be mounted

~~~
# modprobe 9pnet_virtio
# mount -t 9p -o trans=virtio share /shared
mount: /shared: special device share does not exist.
~~~

Is this due to Ubuntu vs Debian? Spice agent 0.22 vs. 0.20 (the standard versions on their respective distro)? Something else?

**Comment by dmarmor** [comment]
I'm having the same problem with the shared directory on Debian. I get the following error:

```bash
$ sudo mount -t 9p -o trans=virtio share test -oversion=9p2000.L
mount: /home/XX/XXXX: special device share does not exist.
       dmesg(1) may have more information after failed mount system call.
```

Here's the relevant output from dmesg:

```
9pnet_virtio: no channels available for device share
```

Any ideas how to fix this? Thanks!
