### ISSUE TITLE
Opening vitrual machines using files does not work

### ISSUE THREAD

**Issue by Connorvator** [utmapp/UTM#5339]
**Describe the issue**
When I click the open button in the vitrual machine creator and click my downloaded VM and press open it does not do anything so can you please fix that?

**Configuration (required)**
* UTM Version: 4.2.5
* OS Version: 16.5
* Device Model: iPad Air 5th gen
* Is it jailbroken? no
* How did you install UTM? Scarlet

**Crash log**
No crash log

**Debug log**
No debug log

**Upload VM**
No

**Comment by osy** [comment]
Scarlet is not a supported install method. It does not sign UTM properly and leads to errors such as this. https://docs.getutm.app/installation/ios/ for supported install methods.
