### ISSUE TITLE
iOS App Signer

### ISSUE THREAD

**Issue by QiuYueBaiJXW** [utmapp/UTM#534]
ERROR：A valid provisioning profile for this executable was not found.

**Comment by js-john** [comment]
You need to create a provisioning profile for utm on developer.apple.com, if you are a developer, you should know how to do it

**Comment by QiuYueBaiJXW** [comment]
> You need to create a provisioning profile for utm on developer.apple.com, if you are a developer, you should know how to do it

Do I need to enroll in ‘Apple developer program’ which is 99$ per year?

**Comment by js-john** [comment]
> > You need to create a provisioning profile for utm on developer.apple.com, if you are a developer, you should know how to do it
> 
> Do I need to enroll in ‘Apple developer program’ which is 99$ per year?

Yes

**Comment by js-john** [comment]
> > > You need to create a provisioning profile for utm on developer.apple.com, if you are a developer, you should know how to do it
> > 
> > 
> > Do I need to enroll in ‘Apple developer program’ which is 99$ per year?
> 
> Yes



> > You need to create a provisioning profile for utm on developer.apple.com, if you are a developer, you should know how to do it
> 
> Do I need to enroll in ‘Apple developer program’ which is 99$ per year?

噗..你可以来中国UTM群，QQ群：1051884885

**Comment by cs-sugar** [comment]
> > > > You need to create a provisioning profile for utm on developer.apple.com, if you are a developer, you should know how to do it
> > > 
> > > 
> > > Do I need to enroll in ‘Apple developer program’ which is 99$ per year?
> > 
> > 
> > Yes
> 
> > > You need to create a provisioning profile for utm on developer.apple.com, if you are a developer, you should know how to do it
> > 
> > 
> > Do I need to enroll in ‘Apple developer program’ which is 99$ per year?
> 
> 噗..你可以来中国UTM群，QQ群：1051884885
I don't quite understand. Can you speak English?

**Comment by cs-sugar** [comment]
> > > > You need to create a provisioning profile for utm on developer.apple.com, if you are a developer, you should know how to do it
> > > 
> > > 
> > > Do I need to enroll in ‘Apple developer program’ which is 99$ per year?
> > 
> > 
> > Yes
> 
> > > You need to create a provisioning profile for utm on developer.apple.com, if you are a developer, you should know how to do it
> > 
> > 
> > Do I need to enroll in ‘Apple developer program’ which is 99$ per year?
> 
> 噗..你可以来中国UTM群，QQ群：[1051884885](tel:1051884885)

I don't quite understand. Can you speak English?

**Comment by IIWare** [comment]
@cs-sugar I used google translate to translate and here it is in english:

Puff.. You can come to China UTM group, QQ group: 1051884885
