### ISSUE TITLE
UTM refuses to install on iOS 14.2 with Odyessyra1n (Checkra1n with Sileo) Jailbreak 

### ISSUE THREAD

**Issue by Vishram1123** [utmapp/UTM#537]
UTM refuses to install on my iPhone 7 with iOS 14.2 and jailbroken with Checkra1n. When I try to install it with Filza, it fails and says `Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.FVF0y5/extracted/Payload/UTM.app : 0xe800801C (No code signature found.)` Could someone please help me understand what I am doing wrong?

**Comment by osy86** [comment]
The current jailbreak install instructions are out of date. I don’t have a jailbroken device to test with so if anyone has a good guide I can steal from it.

**Comment by Vishram1123** [comment]
Otherwise, is it possible to port this to Cydia, as a jailbreak tweak?

**Comment by osy86** [comment]
You’ll run into the same problem.

**Comment by Vishram1123** [comment]
What is this error actually caused by?

**Comment by osy86** [comment]
Older jailbroken iOS allows you to install apps that are missing a signature. From your and other people’s report it seems like on iOS 14 even if you’re jailbroken you still need a signature. One way is to use iOS app signer or AltStore or reprovision to generate a valid signature.

**Comment by Vishram1123** [comment]
![48F3573C-968B-456B-BBDF-E8D695EB6AAB](https://user-images.githubusercontent.com/64966832/99202897-bde20180-277e-11eb-872b-ae00f35b276a.jpeg)
I seem to have found this in the Filza app under the Scripts subcategory when I enter the context menu (3D touch). Could it help?

**Comment by osy86** [comment]
idk did you try it?

**Comment by Vishram1123** [comment]
Yeah, it made a separate ipa file named UTM_resigned.ipa. While that took longer and progressed further, it still ended up with the same error.

**Comment by Vishram1123** [comment]
I figured it out. Using [this](https://www.reddit.com/r/jailbreak/comments/7aswu7/tutorial_convert_ipa_app_to_deb_with_ifilefilza/) tutorial, I converted the ipa to a .deb, and then I installed it using Sileo and resprung. After that, it works perfectly. I will attach the .deb file shortly

**Comment by TheAwesome98-Real** [comment]
Are you on checkra1n or odysseyra1n? Just wondering, am confused

**Comment by IIWare** [comment]
@TheAwesome98-Real In the title, it says odysseyra1n, it's checkra1n, but a little modified, odysseya1n is a custom checkra1n that jailbreaks your iDevice and installs sileo, instead of cydia, so in conclusion, he isn't using checkra1n, he is using odysseyra1n

**Comment by Vishram1123** [comment]
Yeah, that may be part of the problem; when I jailbroke with Checkra1n (the one that installs Cydia), I installed Sileo on top of that, but Sileo didn't show some tweaks that Cydia had.

**Comment by TheAwesome98-Real** [comment]
> @TheAwesome98-Real In the title, it says odysseyra1n, it's checkra1n, but a little modified, odysseya1n is a custom checkra1n that jailbreaks your iDevice and installs sileo, instead of cydia, so in conclusion, he isn't using checkra1n, he is using odysseyra1n

I know what odysseyra1n is, I was just confused at the title haha

**Comment by TheAwesome98-Real** [comment]
> Yeah, that may be part of the problem; when I jailbroke with Checkra1n (the one that installs Cydia), I installed Sileo on top of that, but Sileo didn't show some tweaks that Cydia had.

Yeah, if you have checkra1n you should install sileo through there since it can un/reinstall cydia

**Comment by Randomblock1** [comment]
One thing you should be able to do is install UTM as a System App by extracting UTM.app from the ipa and copying it to /Applications/. Then, you just run UICache -a. I don’t have a device to test it on though.

**Comment by Vishram1123** [comment]
This is essentially what I did by making it a .deb; it copied the UTM.app to the Applications folder, then `sbreload` refreshes the uicache, doing essentially the same thing.

**Comment by TheAwesome98-Real** [comment]
Does doing that make an icon on the Home Screen? I never thought it did, I was gonna try that for an _*experiment*_.

**Comment by Vishram1123** [comment]
It does. The only thing it doesn't do is that it doesn't show the app settings in the Settings app.

**Comment by Vishram1123** [comment]
The .deb file can be found [here](https://drive.google.com/file/d/1rh3WHiAzH5oXzPKhiR6lSi6OliqYqxkI/view?usp=drivesdk)

**Comment by TheAwesome98-Real** [comment]
I'll try doing that with one of my apps that won't install. Thanks again for the .deb, i'll make sure to install it when checkra1n senses my iPhone :)

**Comment by Vishram1123** [comment]
> I'll try doing that with one of my apps that won't install. Thanks again for the .deb, i'll make sure to install it when checkra1n senses my iPhone :)

What do you mean by "when checkra1n senses my iPhone"? What iPhone do you have?

**Comment by TheAwesome98-Real** [comment]
> What do you mean by "when checkra1n senses my iPhone"? What iPhone do you have?

Sometimes, checkra1n won't sense my iPhone. It only displays `Connect your iPhone, iPod touch, iPad, or AppleTV to begin.` It's an iPhone 6s. It's seen by `usbmuxd`, which lets me browse files, but checkra1n won't display it atm. it has worked in the past, i've tried killing and relaunching `usbmuxd` but nothing happened, even after quitting checkra1n.

**Comment by burntscarr** [comment]
I’ll be able to comment the exact command but my fix for this was to run checkrain in terminal mode and connect my iPad already in DFU mode

**Comment by TheAwesome98-Real** [comment]
> I’ll be able to comment the exact command later but my fix for this was to run checkrain in terminal mode and connect my iPad already in DFU mode

How do i put it into DFU w/out checkra1n being open? do i just follow the normal instructions??

**Comment by Vishram1123** [comment]
I am currently in the process of creating a Cydia tweak with both the legacy and the modern UTM app in it.

**Comment by Vishram1123** [comment]
I have successfully created a repository and here it is: [https://vishram1123.gitlab.io/utm-cydia/](https://vishram1123.gitlab.io/utm-cydia/). I used gitlab because I found github too cumbersome.

**Comment by Vishram1123** [comment]
Does anyone have any thoughts on my repo?

**Comment by TheAwesome98-Real** [comment]
Thanks for making the repo, the deb wouldn't install in zebra because of a blank dependency, ill install it from you repo and should solve the problem!

**Comment by Vishram1123** [comment]
I think that is why it doesn't install properly with Sileo either... I will update it so that it requires mobilesubstrate <14.4 or something

**Comment by Vishram1123** [comment]
Actually, what I would love to do is create an add on for Filza that automatically converts an IPA to a .deb

**Comment by Vishram1123** [comment]
I know the commands, I am just trying to figure out how to do the implementation

**Comment by IIWare** [comment]
@Vishram1123 I have some thoughts about your repo, so what's the difference between UTM and UTM-Legacy?

**Comment by Vishram1123** [comment]
UTM-Legacy is for iOS 13 and below (it is UTM 1.0) and normal UTM is UTM 2.0,10

**Comment by IIWare** [comment]
@Vishram1123 is it safe if I try to install utm (non legacy) in iOS 13, iOS 12 and iOS 11?

**Comment by Vishram1123** [comment]
You can, but it will have the same functionality as UTM-Legacy, but if you install UTM-Legacy on iOS 14, it will still work, but the VMs are not backwards compatible (UTM VMs will not work in UTM-Legacy)

**Comment by TheAwesome98-Real** [comment]
> I have successfully created a repository and here it is: https://vishram1123.gitlab.io/utm-cydia/. I used gitlab because I found github too cumbersome.
> 
> EDIT: If you could help me figure out how to make the installation respring the iPhone, please do so. Thanks
> EDIT #2: Go [here](https://vishram1123.gitlab.io/utm-cydia) to find directions on how to install on jailbroken iPhone and follow the README there

I’m not sure where, but there’s a bit inside of debian packages where you can specify what to do after install, and by default (usually) it’s “killall -9 SpringBoard” which restarts SpringBoard.

**Comment by Vishram1123** [comment]
> > I have successfully created a repository and here it is: https://vishram1123.gitlab.io/utm-cydia/. I used gitlab because I found github too cumbersome.
> > EDIT: If you could help me figure out how to make the installation respring the iPhone, please do so. Thanks
> > EDIT #2: Go [here](https://vishram1123.gitlab.io/utm-cydia) to find directions on how to install on jailbroken iPhone and follow the README there
> 
> I’m not sure where, but there’s a bit inside of debian packages where you can specify what to do after install, and by default (usually) it’s “killall -9 SpringBoard” which restarts SpringBoard.

Could you please tell me how? I don't understand

**Comment by Vishram1123** [comment]
I think I fixed the Zebra issue because I made it depend on firmware-sbin. Try it now

**Comment by Vishram1123** [comment]
Btw Happy Thanksgiving everyone

**Comment by TheAwesome98-Real** [comment]
> Btw Happy Thanksgiving everyone

I’m British but thanks anyway

**Comment by TheAwesome98-Real** [comment]
> I think I fixed the Zebra issue because I made it depend on firmware-sbin. Try it now

Redownloading the deb now. Thanks!

**Comment by Vishram1123** [comment]
No problem

**Comment by Vishram1123** [comment]
Is anyone having bad luck running UTM 2.0.12 on the iPhone, repository or no?

**Comment by IIWare** [comment]
@Vishram1123 I have one small problem, the Settings for UTM from your cydia repo doesn't show in the iOS settings app.

**Comment by Vishram1123** [comment]
I described that on my repo page; you have to go to /Applications/UTM(-Legacy or -New).app/Settings.Bundle/Root.plist in Filza and manually go into the Items and search for the setting you want. Right now, I am trying to integrate UTM's settings into PreferenceLoader. If someone could help me that would be great, but right now I am trying to sort out why the app won't launch. I think it is because of its unnecessary reliance on MobileSubstrate (Dependencies: firmware-sbin, MobileSubstrate), so I will try to get rid of that dependency and see if it works. If you are on an older version right now, do not upgrade.

**Comment by Vishram1123** [comment]
Strange-when I install it with APT, it does not install properly, leaving behind the UTM executable. If anyone has a problem with UTM installed from the repository, download the IPA from getutm.app and replace the executable.

**Comment by TheAwesome98-Real** [comment]
I got UTM btw (from the deb not the repo), and it works great!

**Comment by Vishram1123** [comment]
You should update to v2.0.12, the one in the .deb is 2.0.09

**Comment by TheAwesome98-Real** [comment]
> You should update to v2.0.12, the one in the .deb is 2.0.09 or something

alright, I’ll do that at some point

**Comment by IIWare** [comment]
@TheAwesome98-Real you can always get the latest deb from @vishram1123 's repo in https://gitlab.com/Vishram1123/utm-cydia/-/raw/master/deb/com.utmapp.UTM-new.deb

**Comment by IIWare** [comment]
@Vishram1123 is it possible to make the UTM tweak deb think that I'm in iOS 14 in order to show the new design while in reality I am in iOS 13?

**Comment by Vishram1123** [comment]
You will see [here](https://github.com/utmapp/UTM/releases/tag/v2.0.13) why this won't be done. Maybe try [this](https://www.reddit.com/r/jailbreak/comments/3zyvur/guide_how_to_spoof_your_ios_version_temporally/?utm_source=amp&utm_medium=&utm_content=post_body)? I don't know if it will work, however.

**Comment by IIWare** [comment]
@Vishram1123 is it possible install the iOS 14 API (GUI) Files in iOS 13 in Jailbroken devices so that it can display the iOS 14 API in iOS 13?

**Comment by ThatsNiceGuy** [comment]
> > > I have successfully created a repository and here it is: https://vishram1123.gitlab.io/utm-cydia/. I used gitlab because I found github too cumbersome.
> > > EDIT: If you could help me figure out how to make the installation respring the iPhone, please do so. Thanks
> > > EDIT #2: Go [here](https://vishram1123.gitlab.io/utm-cydia) to find directions on how to install on jailbroken iPhone and follow the README there
> > 
> > 
> > I’m not sure where, but there’s a bit inside of debian packages where you can specify what to do after install, and by default (usually) it’s “killall -9 SpringBoard” which restarts SpringBoard.
> 
> Could you please tell me how? I don't understand

See this. [https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html](https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html) and potentially [https://iphonedevwiki.net/index.php/Packaging#DEBIAN_folder](https://iphonedevwiki.net/index.php/Packaging#DEBIAN_folder)

**Comment by Vishram1123** [comment]
@ThatsNiceGuy Thank you so much
@IIWare You must manually do that if you want to, and I don't think it is possible even if you wanted to as iOS 14's frontend is done slightly differently, so it will not be possible to do that.

**Comment by TheAwesome98-Real** [comment]
also make sure to set it to `uicache && killall -9 SpringBoard` so the uicache is refreshed

**Comment by Vishram1123** [comment]
Could somebody check if [this](https://www.reddit.com/r/jailbreak/comments/akuey6/tutorial_install_any_ipa_with_filza_and_terminal/) tutorial works? My phone is currently not jailbroken

**Comment by Vishram1123** [comment]
I finally got around to fixing my packages in my repository. Can someone please check if it works? (I got rid of the UTM-Legacy, as it provides the same functionality as UTM).

**Comment by TheAwesome98-Real** [comment]
Ima try uninstalling the UTM I’ve got and installing yours, hopefully it doesn’t delete my MS-DOS with Windows 3.1 and DOOM

**Comment by Vishram1123** [comment]
@TheAwesome98-Real Your VMs are stored in a different location, but you shouldn't do that now as the repository is not working properly. I am having problems building the packages.

**Comment by Vishram1123** [comment]
I fixed the broken packages, but could someone help me figure out how to not make it hang infinitely when attempting to install it using Sileo?

**Comment by TheAwesome98-Real** [comment]
> I fixed the broken packages, but could someone help me figure out how to not make it hang infinitely when attempting to install it using Sileo?

I don’t have another device that supports sileo, and I use checkra1n on my main, so I can’t, sorry.

**Comment by 0sy-is-ssucch-a-s-st-puid-idio-t-l-l-l** [comment]
po-sti-ng po-sts th,at a.re,n't ev,e!n p0sts

**Comment by Vishram1123** [comment]
Wow thanks for adding the repo so I guess I can close my repo and this thread thanks

**Comment by osy** [comment]
@Vishram1123 It seems like running it outside the sandbox has some subtle issues like Preferences not working. Does AltStore + AltDaemon work for you? If it's working, I think I'll revert the Cydia repo as it creates more confusion (people getting errors about permissions for Documents and no Files integration and etc).

**Comment by Vishram1123** [comment]
Tomorrow I will share a guide on workarounds for this, and I am also looking for an alternate to AppSync Unified on iOS 14 (which will allow the UTM.ipa to double-click install within Filza)

**Comment by osy** [comment]
There’s https://www.pandahelp.vip/blog/appsync-unified-repo-for-ios-14-ios-14-1-ios-14-2/

but I still think altdaemon is better.

**Comment by Vishram1123** [comment]
[Here](https://1drv.ms/v/s!AsoHk6bek_KetDRF3AV9Tp-gwabH) is the guide. AltDaemon was quite finicky (I had to reinstall it every time I respringed) and the Appsync didn't work.

**Comment by Vishram1123** [comment]
@osy Did you see my last comment?

**Comment by osy** [comment]
Yeah, I know there's workarounds but it's not user friendly. I'm going to keep the jailbreak build for now because possible features in the future like usb support would require it. But supporting it is low priority right now.

**Comment by Vishram1123** [comment]
Ok

**Comment by osy** [comment]
UTM DEB now uses AppSync Unified which should work everywhere without issues.
