### ISSUE TITLE
[Feature Request] Make it possible to start UTM with args from 3rd party installed Terminals in iOS

### ISSUE THREAD

**Issue by IIWare** [utmapp/UTM#538]
This could be useful for those who prefer starting UTM with args from 3rd party installed Terminals (Like iSH, and NewTerm, not the terminal built in UTM), and for those who want to start a UTM VM for testing, without having to create a UTM VM, Example:

`$> UTM -cpu pentium3 -m 128 -drive file=/path/to/hard_disk.qcow2,index=0,media=disk,locked -drive index=1,media=cdrom,file=/path/to/disc_image.iso -display sdl`

The command above is just an example, people can just add any valid QEMU arguments after the command `UTM` in terminal.

UTM starting from terminal with args animation is [Here](https://drive.google.com/file/d/1mEGIQ-xl0JbDhB5fNdPUmbHwC07Ujf7S/view)

Note: In the animation, UTM won't start INSIDE the terminal, It will exit terminal, and start UTM app directly into the VM with the settings from the args from terminal.

So hopefully this feature will be implemented, Thanks.

**Comment by ThatsNiceGuy** [comment]
this sounds pretty difficult and UTM would need to drop an executable inside /usr/local/bin for this to work in any form. Would only work on jailbroken devices as well.

**Comment by osy86** [comment]
If you’re jailbroken and can use terminal I suggest running QEMU directly and connecting with a VNC client.

**Comment by IIWare** [comment]
@osy86
> If you’re jailbroken and can use terminal I suggest running QEMU directly and connecting with a VNC client.
But how can I do that?

**Comment by ThatsNiceGuy** [comment]
UTM’s GitHub issues are not a forum. Please look in the appropriate locations for help with this. (Not a UTM issue)
