### ISSUE TITLE
Not able to install macOS guest on Apple Silicon - hangs at start "Installation 0 %"

### ISSUE THREAD

**Issue by ChristophM2000** [utmapp/UTM#5389]
Hi,

I am on a MacBook Pro M1 Max with 64GB Unified Memory with newest macOS Ventura.
I need UTM to run a guest of macOS Ventura on my MacBook Pro.

I bought UTM via Mac App Store.
Started it, and went threw the creation process of a macOS VM.
"Create new Virtual Machine" -> "Virtualise" -> "macOS 12+" and let it use the IPSW from Apple.
I let all VM Settings as default. 4GB Memory, Processor Cores default, 64GB image size.
After the summary I press "Save".
Than it downloads the IPSW.
After that I try to run the VM, the window opens and asks for confirmation that the first disk will be erased. I press OK and a spinner appears in the window and in the header bar "Installation 0 %" appears. But nothing happens after that. It stays like this for hours.

To get more information I started UTM via terminal and tried again.
After downloading it prints "error com.utmapp.UTM : [UTM] Failed to migrate drive 70652032-969A-468F-B7DA-85E63BFA4D9B from config."
The "Virtual Machine Service" process stays at 100% CPU usage while UTM is spinning.

How do I get it to work?

Greetings,
Christoph

**Comment by ChristophM2000** [comment]
It turned out, that it was my network connection via WLAN. As soon as I plugged in my ethernet cable it counted up above "Installation 0 %". Maybe it was a verifying process of the image that did not work. I have this same problem also with system updates of macOS. It is able to download but after that the installation is frozen until I plug in my ethernet cable.

**Comment by jmstacey** [comment]
I think this should be re-opened as a bug because I just encountered this issue and on a hunch disabled LuLu firewall and then UTM installation worked. So UTM should report that it needs Network access to perform a macOS guest installation.
