### ISSUE TITLE
Mac with both Intel and Apple Silicon says UTM is damaged and cannot be opened.

### ISSUE THREAD

**Issue by kjwamlex** [utmapp/UTM#539]
**Describe the bug**
When trying to install release version of UTM for macOS, both Intel and Apple Silicon Mac thinks the app is damaged.
**Version**
In the menu bar select UTM -> About to see the version and build number.
The Latest Release version
**To Reproduce**
Simple extract and attempt opening UTM on any Mac.

**Expected behavior**
UTM Opens.

**Screenshots**
![Screen Shot 2020-11-18 at 8 40 21 PM](https://user-images.githubusercontent.com/12839351/99609617-47dbd580-29de-11eb-8fd2-22608bbcac21.png)

**Additional context**

**Comment by osy86** [comment]
It’s not notarized but currently it’s broken even if you notarize it due to an apple bug.

**Comment by IIWare** [comment]
Open terminal in macOS, then type in: `xattr -cr /Applications/UTM.app`
