### ISSUE TITLE
Add link to the webside in the repo describtion

### ISSUE THREAD

**Issue by kubenstein** [utmapp/UTM#54]
Hello!
Its a beautiful project but as many projects it lacks this final "showoff" touch.
So much work has been put in it already I believe yet half of people wont see it because there is no link to website or screenshot in readme pinning attention while scrolling.

I suggest adding a link to a website to the repo description. Easy yet very important thing.
wdyt?

cheers!

**Comment by osy86** [comment]
Done https://github.com/utmapp/UTM/commit/9288ce616072d8afb59418e014c40009bd815157
