### ISSUE TITLE
[Feature Request] ability to change default QEMU arguments without having to bypass configuration and losing existing data there

### ISSUE THREAD

**Issue by Vishram1123** [utmapp/UTM#540]
Hello, when I was trying to add an alternate BIOS (.fd) argument, it wouldn't work as it conflicted with SPICE. I think the argument needs to be moved higher up. Is it possible to make the default configuration read-write? Thanks

**Comment by osy86** [comment]
You can select BIOS file in the disk settings by choosing bios as the image type.

**Comment by Vishram1123** [comment]
Ok thank you
