### ISSUE TITLE
Cannot creat Linux VM: Could not open '/efi_vars.fd': No such file or directory

### ISSUE THREAD

**Issue by fegue** [utmapp/UTM#5419]
**Describe the issue**  
UTM always shows an error in a pop-up when trying to start the VM for the first time with the following message:

```
QEMU exited with the following error: qemu-aarch64-softmmu: -drive if=pflash,unit=1,file=/efi_vars.fd: Could not open '/efi_vars.fd': No such file or directory
```
This happened with all Linux Distros I have tried so far:
- Fedora-Workstation-Live-aarch64-37-1.7.iso
- ubuntu-22.04.2-live-server-arm64.iso
- debian-12.0.0-arm64-netinst.iso

I followed the instructions when creating a VM and didn't touch the defaults.

I tried both the .dmg and the App-Store version 

**Configuration**  
* UTM Version: 4.2.5 (81)
* macOS Version: 13.4.1 (22F82)
* Mac Chip: M1 Pro 

**Crash log**  
No crash log exists

**Debug log**  
The export Log button is greyed out

**Comment by osy** [comment]
Can you share your config.plist inside the .utm package?

**Comment by fegue** [comment]
Well, there is no folder and no config.plist because the VM was never created. When I restart UTM, the VM in the sidebar is greyed out and clicking on it shows the following message:
`This virtual machine cannot be found at: /Users/ME/Library/Containers/com.utmapp.UTM/Data/Documents/fedora_workstation.utm`

**Comment by osy** [comment]
That’s really bizarre. Can you try v4.3.1 beta and see if that makes a difference?

**Comment by umjammer** [comment]
so do i

host
- UTM Version: 4.2.5
- macOS Version: 13.4.1
- Mac Chip: M2 Ultra 

guest
- ubuntu-22.04.2-live-server-arm64.iso

---

i tried UTM v4.3.1, it said
"You do not have permission to save the file "XXXXX.utm" in the folder "UTM" (like that because my locale is Japanese).

next i did `chmod og+rwx ~/Documents/UTM`, but i got the same message.
(`~/Library/Containers/com.utmapp.UTM/Data/Documents`  is symbolic linked to `~/Documents/UTM`)

in my `~/Documents/UTM` directory there is `Windows11.utm` and it works.

**Comment by osy** [comment]
> ~/Library/Containers/com.utmapp.UTM/Data/Documents is symbolic linked to ~/Documents/UTM

There's your problem.

**Comment by umjammer** [comment]
oh that's it. my linux virtual machine is created successfully.

do you mean UTM doesn't support symbolic linked directory?

**Comment by osy** [comment]
UTM is an macOS sandboxed app. This is the case for every app that use Containers.

@fegue does this apply to you as well?

**Comment by fegue** [comment]
I have tried version 4.3.1 and it's failing even faster. 
When I click on 'Save' on the last page 'summary', I immediately get an error pop-up saying
`The file 'NAME_OF_VM.utm' does not exist`.

**Comment by osy** [comment]
You did not make any symlinks?

**Comment by fegue** [comment]
No, I just used the app as intended (at least I think I did). 
There is no folder `~/Documents/UTM`

**Comment by osy** [comment]
Can you make sure `~/Library/Containers/com.utmapp.UTM/Data/Documents` exists and is accessible? If not, at least `~/Library/Containers/com.utmapp.UTM/Data` should exist.

**Comment by fegue** [comment]
The folder `~/Library/Containers/com.utmapp.UTM/Data` exists but it does not contain a folder `Documents`.
I only found that folder via the terminal. In Finder it shows up as `~/Library/Containers/UTM`.
Should it symlink to `~/Documents` ?

**Comment by osy** [comment]
No, why don’t you try deleting the container and then open the app again? It should recreate the container

**Comment by fegue** [comment]
Deleting `~/Library/Containers/UTM` did the trick!

Thank you so much for your great help and quick response! 
Buying the app was definitely worth it!

**Comment by osy** [comment]
I will make sure Documents is created automatically in the future.

**Comment by startergo** [comment]
The app downloaded from the Appstore creates the folder automatically (Intel Processor):
<img width="1229" alt="image" src="https://github.com/utmapp/UTM/assets/7897244/32a0fa1f-9fb3-405d-b0c3-42f94a16a0b9">
