### ISSUE TITLE
Feature request: Add support for dynamic resolution

### ISSUE THREAD

**Issue by tobiaskohlbau** [utmapp/UTM#5421]
In macOS 14 Sonoma Apple added Support for automatic screen resolution within MacOS and Linux VMs.

See [1] and [2] for more information.

- [1] https://developer.apple.com/documentation/virtualization/vzvirtualmachineview/4168520-automaticallyreconfiguresdisplay
- [2] https://developer.apple.com/videos/play/wwdc2023/10007/

**Comment by DUOLabs333** [comment]
You don't even need Apple's Virtualization Framework for this: before switching, I've used [akihikodaki's](https://github.com/akihikodaki) fork, which has this.

**Comment by osy** [comment]
Fixed by https://github.com/utmapp/UTM/commit/332a66206166cdc8248250d89e3d26573643a945
