### ISSUE TITLE
Unable to access oracle database installed on UTM windows 11 

### ISSUE THREAD

**Issue by CSEKU160212** [utmapp/UTM#5442]
I have installed the Oracle database on the virtual Windows 11. 

I have found below IP address on the Windows virtual machine: 

<img width="853" alt="Screenshot 2023-07-09 at 12 50 38 PM" src="https://github.com/utmapp/UTM/assets/23745270/5f670618-6914-408d-a456-09dadb81701f">

The IP address is: 192.168.102.158

From the Mac host, I can ping the address. Below is the ping result. 
<img width="603" alt="Screenshot 2023-07-09 at 12 52 45 PM" src="https://github.com/utmapp/UTM/assets/23745270/da4cfe98-49f7-491a-80f5-6c1a58aeb4f1">

And the networking configuration for my virtual windows: 
<img width="853" alt="Screenshot 2023-07-09 at 12 48 07 PM" src="https://github.com/utmapp/UTM/assets/23745270/79d34f67-3296-49f8-9c96-1f7ca8c9f4eb">

But when I want to access 1521 port from my host pc then the connection got refused. I can't be able to access Oracle database from the host SQLDeveloper. Here is the result: 
<img width="1064" alt="Screenshot 2023-07-09 at 12 54 42 PM" src="https://github.com/utmapp/UTM/assets/23745270/4962e2cb-2707-460e-b492-ae091828fa94">

Please help me to solve the issue. 

Also, checked the Oracle database using sqlplus on the virtual windows and found okay. also windows firewall is deactivated.

**Comment by CSEKU160212** [comment]
Now it is working. 
I had to change "localhost" to the windows machine IP on listener.ora and tnsnames.ora files.

**Comment by BaneSameer** [comment]
@CSEKU160212 
I've changed localhost to IP address in both tnsnames.ora and listener.ora (in Virtual Machine Windows 11)
Also, I'm able to ping my virtual machine windows 11 (Using UTM) from Mac OS machine.
I'm using Oracle SQL Developer (Version 23.1.0.097) in MacBook Pro.
Still, I'm getting error as "The Network Adaptor could not establish the connection"
Do we need to configure tnsnames.ora or listener.ora in Mac OS? 
Could you please help me on this?
