### ISSUE TITLE
UTM error on macOS 13.4.1 (c)

### ISSUE THREAD

**Issue by prairiewalker** [utmapp/UTM#5456]
I have **UTM 4.2.5 (81)** installed on **macOS 13.4.1 (c)** with an iMac M1 system.

I downloaded the UniversalMac_14.0_23A5286i_Restore.ipsw.

Tried to create a new virtual machine by importing an IPSW for macOS 14 public beta and get the error shown in the attached image.  When I indicate that the software update should be downloaded after a few minutes I get another message saying it can't find the update on the server.
I am a UTM novice. Hope someone has an idea how to proceed.

![ERROR](https://github.com/utmapp/UTM/assets/80177297/9d163260-5399-43bf-a5f7-20e251acfac8)

**Comment by shouri10** [comment]
Install the latest xcode developer beta, you can move it to trash afterwards.
System files need to be updated to support macOS 14 (and iOS 17).

**Comment by prairiewalker** [comment]
Doing that got me past the 'update required..." but have one more error to surmount.  Thanks for your suggestion.

**Comment by prairiewalker** [comment]
UTM installing the Public beta of macOS 14.  Also after installing the Xcode beta (now deleted) I was successful in using Howard Oakley's Viable software to create macOS.  UTM seems to run macOS 14 more slowly than Viable so I'm going  keep with it and have UTM as a fall back option.
