### ISSUE TITLE
when you instalk utm se in altstore it crashes at 75%

### ISSUE THREAD

**Issue by bradycodemaster** [utmapp/UTM#5473]
**Describe the issue**
A clear and concise description of what the issue is. **BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.** when i tired to install utm se in altstore it crashes at 75%

**Configuration (required)**
* UTM Version: 4.2.5 se
* OS Version: ipad os16.1.1
* Device Model: ipad pro 9.7
* Is it jailbroken (name jailbreak used)? no
* How did you install UTM? altstore

**Comment by osy** [comment]
This is an AltStore issue and not UTM

**Comment by bradycodemaster** [comment]
they will not respond
