### ISSUE TITLE
UTM crashes when Windows 11 guest updates

### ISSUE THREAD

**Issue by neldredge-unco** [utmapp/UTM#5477]
**Describe the issue**  
Using the UTM 4.3.2 beta release, I installed a Windows 11 guest from the VHDX for build 25346.  I then tried to use Windows Update to get the latest Canary build (first I needed to update the two WindowsSelfHost registry keys described [here](https://gist.github.com/wrmack/29d580a0bd665bace21609d5ef675ba1)).  During the install process, UTM crashed.

I tried it three times, and UTM crashed at three different points during the installation (20%, 28%, 38%) so more likely this is related to overall load than anything specific that the guest is doing.

On the third attempt, I had left it running overnight, and woke up to find UTM still running, but the install progress only showing 38% (normally it should complete in well under an hour).  Then as soon as I tried to move the mouse cursor into the VM window, UTM immediately crashed.  I think the symptom was similar on the first two tries but I'm not completely sure about that.

The logs below are from that third attempt.  I also have crash logs from the first two attempts, which I can add if they would be helpful, but I don't have debug logs for them.

**Configuration**  
* UTM Version: 4.3.2 (84)
* macOS Version: Ventura 13.4.1 (c)
* Mac Chip (Intel, M1, ...): M1 Pro

**Crash log**  
[UTM-2023-07-18-083553.ips.zip](https://github.com/utmapp/UTM/files/12081938/UTM-2023-07-18-083553.ips.zip)

**Debug log**  
[debug.log](https://github.com/utmapp/UTM/files/12081951/debug.log)

**Upload VM**  
[config.plist.zip](https://github.com/utmapp/UTM/files/12081979/config.plist.zip)

**Comment by osy** [comment]
Btw you no longer need to do any registry hacks if you enable TPM 2.0 and reset UEFI vars.

**Comment by neldredge-unco** [comment]
@osy This VM was freshly created with UTM 4.3.2, so I believe the TPM and UEFI stuff should have been set up correctly?  Out of the box I still was not able to do Windows Update (it reported no updates available).  The Windows Insider page reported "Your PC does not meet the minimum hardware requirements for Windows 11. Your channel options will be limited." and was stuck on the Release Preview channel.  I ran PC Health Check which complained "The processor isn't currently supported for Windows 11. Processor: virt-8.0".  However it did give green check marks for Secure Boot and TPM 2.0, as well as  RAM, disk space and number of cores.

So I am not sure what that is about.  Is it worth a separate bug report?  However, I was able to circumvent it with the following two registry hacks:

- `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsSelfHost\Applicability` : `BranchName` -> `CanaryChannel`
- `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsSelfHost\UI\Selection` : `UIBranch` -> `CanaryChannel`

This was enough to let Windows Update get started (until the crash described above). I didn't need any of the other registry hacks listed [here](https://gist.github.com/wrmack/29d580a0bd665bace21609d5ef675ba1) nor the TPM bypass script.

**Comment by osy** [comment]
Interesting, maybe it’s worth filing another issue. I can easily rename the CPU to something Windows likes

**Comment by neldredge-unco** [comment]
Thanks, I'll test it when the next beta is released.

**Comment by neldredge-unco** [comment]
Just for anyone's future reference, the actual change is to qemukit: https://github.com/utmapp/QEMUKit/commit/d979cb5249f34e18de07e82496a004f8ff3bbd0e
