### ISSUE TITLE
Not able to load ISO or VDHX files on UTM SE.

### ISSUE THREAD

**Issue by FluffyBear358** [utmapp/UTM#5491]
Describe the issue
Hey, if anyone does read this I’d like to mention that I’ve been trying to get windows 11 (ARM64) installed on my iPad Air 5th generation but nothing will load, I went to load the path to my VDHX file but when i tap open it wont load and stays stuck on the file window. Is there any way to fix this issue? (This happens to ISO files too!)

Configuration (required)

UTM Version: 4.2.5
OS Version: iPadOS 16.5.1 (c)
Device Model: iPad Air 5th generation M1
Is it jailbroken (name jailbreak used)? No
How did you install UTM? Using the UTM SE ipa and installed it with Scarlet.
No crash, debug or .utm file/log. Just an issue.

**Comment by misaka-fans** [comment]
i got stuck on the same step :(

**Comment by osy** [comment]
Scarlet is not a supported install method as they mess up the entitlement bundle identifier.
