### ISSUE TITLE
Port is not opened error

### ISSUE THREAD

**Issue by osy** [utmapp/UTM#5507]
<img width="810" alt="Снимок экрана 2023-07-29 в 14 39 35" src="https://github.com/utmapp/UTM/assets/2687319/b981c270-efb8-4875-8096-ab8eb3c60139">

After upgrading to UTM 4.3.3 UTM itself doesn't crush, however virtual guest hangs on with the following error (see first picture). No external devices were attached. 

UTM 4.3.0 runs without any errors.

The only 'non-standart' configuration is the following (second picture):

<img width="789" alt="Снимок экрана 2023-07-29 в 14 46 05" src="https://github.com/utmapp/UTM/assets/2687319/840cd015-520c-4e14-81f1-dfe376066cd8">

_Originally posted by @gglluukk in https://github.com/utmapp/UTM/issues/5472#issuecomment-1656712426_

**Comment by mx1up** [comment]
i had the same error today, after upgrading to 4.3.3. However, at that point, the vm was already hanging (no keyboard or mouse input possible), so I figured it was normal that I got this error when trying to access the console.

(btw, the way I managed to release input control back to macOS was to press the hardware on/off button on my laptop which causes it to lock the screen).

I was thinking the auto input capture was not working properly when going full screen (icon remained in inactivated state)

**Comment by neldredge-unco** [comment]
Dup of #5505?

**Comment by osy** [comment]
Duplicate of #5505

**Comment by gglluukk** [comment]
In my case I don’t use no keyboard nor monitor since I manage Linux guest via SSH. 
The only output I need is serial console to get early Linux kernel warnings/errors. 
This error might be related to QEMU running under the management of UTM and not to UTM itself.
