### ISSUE TITLE
ARM64 Linux not booting with Apple Virtualization

### ISSUE THREAD

**Issue by selimsandal** [utmapp/UTM#5517]
**Describe the issue**  
Using Apple Virtualization and Rosetta enabled arm64 linux virtualization does not start at all. There is an error message displayed for few frames: EFI Boot Options returned. Exiting VM

I tested the iso using Apple's developer examples and it works there.

<img width="312" alt="Screenshot 2023-08-03 at 14 55 04" src="https://github.com/utmapp/UTM/assets/49725809/ba515ff2-f5ce-4bbc-a13a-ce60a0e7170c">

**Configuration**  
* UTM Version: 4.3.4
* macOS Version: Sonoma Developer Beta 4
* Mac Chip (Intel, M1, ...): M2 Max

**Debug log**  
Not available because of Apple Virtualization I think.

**Upload VM**  
[config.plist.zip](https://github.com/utmapp/UTM/files/12250499/config.plist.zip)

**Comment by osy** [comment]
Are you sure this isn't a macOS Sonoma issue? Does v4.2.5 work?

**Comment by selimsandal** [comment]
@osy tried it, 4.2.5 booted the same iso just fine

**Comment by osy** [comment]
Well that was dumb. When I fixed the issue for QEMU in 5730f984df425b76e0d954441987118b26e44c28 I forgot to include it for AVF as well. So the issue is just that the selected boot image didn't get saved from the wizard. You need to select the ISO again before starting the VM.

**Comment by slycke** [comment]
I have the same issue on 4.3.4. Tested with NixOS 23.05 aarch64. 

UTM 4.2.5 works fine.

**Comment by osy** [comment]
Did you read the comment above?

**Comment by slycke** [comment]
Now I did, thanks. re-installed 4.3.4 and I can confirm it works.
