### ISSUE TITLE
4.3.4: Blank screen or "Guest has not initialized the display (yet)." on start

### ISSUE THREAD

**Issue by fabiensanglard** [utmapp/UTM#5523]
**Describe the issue**  
I am unable to install Windows 11. After following instructions found here https://docs.getutm.app/guides/windows/, I run the VM and the screen remains blank.

**Configuration**  
* UTM Version: Version 4.3.4 (86)
* macOS Version: Ventura 13.5
* Mac Chip: M1

**Crash log**  
UTM does not crash.

**Debug log**  
[debug.log](https://github.com/utmapp/UTM/files/12257292/debug.log)

**Upload VM**  
[config.plist.zip](https://github.com/utmapp/UTM/files/12257301/config.plist.zip)

Screenshot of blank:
<img width="1218" alt="Screenshot 2023-08-03 at 10 26 42 PM" src="https://github.com/utmapp/UTM/assets/1219472/01ad0f11-7dea-40ad-b83f-0499c4bc6496">

**Comment by fabiensanglard** [comment]
Note that I tried to use both Windows11_InsiderPreview_Client_ARM64_en-us_23506.VHDX or 22621.1_MULTI_ARM64_EN-US.ISO and got the same result each time.

**Comment by erayd** [comment]
I am experiencing the same no-display issue when attempting to boot an existing Win11 (virtio-ramfb-gl) and Gentoo (virtio-gpu-pci) following the update of UTM to v4.3.4 - so this may not be just a new-VM problem. Host is a M1 running Ventura 13.4.1(c).

**Comment by osy** [comment]
Does restarting your computer help?

**Comment by osy** [comment]
Also can you try adding a serial port to the VM and starting it and see if anything shows up in the terminal? There may be an error message there.

**Comment by maederm** [comment]
> Does restarting your computer help?

Unfortuantely no.

**Comment by maederm** [comment]
> Also can you try adding a serial port to the VM and starting it and see if anything shows up in the terminal? There may be an error message there.

There isn't any output in the serial device.

Btw., I use the AppStore Version of UTM 4.3.4 (86)

**Comment by osy** [comment]
This is a bizarre bug. I can only reproduce it on App Store/TestFlight builds but not on the GitHub DMG or development builds...

**Comment by alybally04** [comment]
I also just updated to 4.3.4 on the App Store and have the same issue with all of my existing Windows 11 and Ubuntu VMs (except Windows XP for some reason).

The VM uses approx 40% of CPU while displaying "Guest has not initialized the display (yet)." indefinitely and never boots.

All of the VMs were working perfectly before updating.

**Comment by florianschendel** [comment]
I have the same problem. App was installed via Apple App Store. Version 4.3.4 (86)

**Comment by yevmel** [comment]
as others mentioned in similar posts, only UTM from app store is affected. My workaround at the moment is using UTM from the website: https://mac.getutm.app

**Comment by osy** [comment]
The issue with the Mac App Store build has been identified as QEMU reading the UEFI BIOS as all 00s while the DMG build reads it properly. This is extremely weird because we use the *exact same binary* for both with the same entitlements. The only difference is the code signature. My hunch is that there is some weird race condition in QEMU when trying to read the UEFI BIOS and so the current thinking is to downgrade to QEMU 7.2.0. I am trying to build it right now and test it and if it works, I'll submit an update to the MAS ASAP to get this resolved. This is super frustrating because I could have never imagined that the MAS build would act differently and I am still trying to figure out exactly why. As it currently stands **every VM that uses UEFI will not boot** so this is a pretty big issue and I apologize for not catching it earlier.

**Comment by fabiensanglard** [comment]
The irony of the timing. Having used UTM for a while, I decided yesterday to buy it via the AppStore...only to find out it was broken :P ! Thank you for all your hard work, UTM rules.

**Comment by osy** [comment]
v4.3.5 has been tested and should resolve the issue by downgrading QEMU to v7.2.0 and EDK2 to edk2-stable202102. As soon as Apple approves it, the update should go out to App Store users.

**Comment by yevmel** [comment]
@osy thank you very much 👍 

i already migrated my VMs yesterday to version of UTM i downloaded from [https://mac.getutm.app/](https://mac.getutm.app/) and removed the one i downloaded from the App Store. Is there any benefit using the version from App Store beside getting notified about new versions of the app?

**Comment by deciphr102** [comment]
Any luck with this? i am facing similar issue, 3 weeks back opened and issue but dont see any recommendation or solution on that.

https://github.com/utmapp/UTM/issues/5479

**Comment by ClausHansn** [comment]
i switched to version 3.15 and install ubuntu (it was the one i had no screen on) then upgraded to the latest version and all work now win11 macos 14 and 9 :)

**Comment by deciphr102** [comment]
> i switched to version 3.15 and install ubuntu (it was the one i had no screen on) then upgraded to the latest version and all work now win11 macos 14 and 9 :)
> 
> mac m1

Are you using dual screen in your machine

**Comment by ClausHansn** [comment]
no just 1 
it was only when I had to reinstall ubuntu the others have worked all the time 4.3.4 and 4.3.5

**Comment by hrpomrx** [comment]
FWIW I have that message if I try to boot a Win 11 guest (MBA 15 M2 host) with a projector connected. 

Without the projector connected to the MBA, Win 11 boots fine but, when I subsequently plug in the projector the screen in the guest window goes blank (white).

Hopefully this 4.4.0 version is officially released soon. Thanks.

**Comment by Michi-Graf** [comment]
Im having the same problem with UTM on my M1 Mac with UTM 4.3.5 trying to run Linux with QEMU. 
I tried different versions of QEMU (7.2, 7.1, .. a few), but am still getting the "Guest has not initialized the display (yet). 

Any news or suggestions? 
I possible, I'd like to keep the App Store version because of the automatic updates...

**Comment by hrpomrx** [comment]
Tried 4.4.3 beta dmg but still getting the "Guest has not initialized the display (yet)". M2 MBA, Win 11 Guest.

**Comment by Bonnie39** [comment]
@hrpomrx What display settings ended up working? I'm getting the same issue too

**Comment by hrpomrx** [comment]
> @hrpomrx What display settings ended up working? I'm getting the same issue too

Hi, @Bonnie39.

At some point I had used another display like VGA and had set the VGA Device RAM to something other than the (grayed out) default which, in my case was 16. I had set it higher than that and saved. On switching back to virtio-ramfb, I got the error....until I switched back to VGA, deleted my custom VGA Device RAM setting, saved, and went back to virtio-ramfb. Then it magically worked. YMMV, but I think there's maybe a rogue ram variable floating around somewhere. I'd suggest going to other display types and removing any custom RAM settings you might have.

**Comment by noahwo** [comment]
For me, I had the similar issue and could not solve with the solutions mentioned in this Issue page. I actually found that was due to an option checked without I fully understanding it. 
<img width="450" alt="image" src="https://github.com/utmapp/UTM/assets/26848129/df39214a-1d16-49a4-99c0-8694f82f2647">

The option "Boot from kernel image" in the page when setting up should be unchecked. Then I entered the VM successfully.

**Comment by joekrump** [comment]
> > @hrpomrx What display settings ended up working? I'm getting the same issue too
> 
> Hi, @Bonnie39.
> 
> At some point I had used another display like VGA and had set the VGA Device RAM to something other than the (grayed out) default which, in my case was 16. I had set it higher than that and saved. On switching back to virtio-ramfb, I got the error....until I switched back to VGA, deleted my custom VGA Device RAM setting, saved, and went back to virtio-ramfb. Then it magically worked. YMMV, but I think there's maybe a rogue ram variable floating around somewhere. I'd suggest going to other display types and removing any custom RAM settings you might have.

thanks @hrpomrx . This worked for me:

1. Set to VGA and custom VGA device ram: 
<img width="805" alt="image" src="https://github.com/utmapp/UTM/assets/3317231/c9309f65-d740-4d8a-8f39-fa9d89ce0688">

2. Saved this setting
3. Opened settings again. Set display hardward as `virtio-ramfb`
4. Saved this setting
5. Opened up the VM and it worked!

**Comment by serifcetin** [comment]
My resolution was simple. I clicked the shut down button on the black window and turned on again. And it worked. I wasn't expecting that. :)

**Comment by roya9762** [comment]
I'm facing same issue, try all action which posted above still facing same issue. Guest has not initialised the display yet. Can any suggest the remedy ? How to get rid of this issue ?

**Comment by salmantec** [comment]
Hey, I tried this and it worked for me

https://github.com/utmapp/UTM/issues/5525#issuecomment-2294831090

**Comment by FoxLy1312** [comment]
Same problem here im running iPhone 15
Latest IOS UTM from appstore
