### ISSUE TITLE
Can't change display scale on Kali

### ISSUE THREAD

**Issue by PolLamothe** [utmapp/UTM#5524]
**Describe the issue**  

Ok so the probleme is that when using Kali i changed my screen resolution and it worked perfectly but element were to small so i tried to change the scale but it display a black screeen when applied but luckly it cancel afterward because i can't confirm the modification.

**Configuration**  
* UTM Version: 4.2.5
* macOS Version: 13.4.1
* Mac Chip (Intel, M1, ...): M2 

[config.plist.zip](https://github.com/utmapp/UTM/files/12257369/config.plist.zip)

**Comment by deciphr102** [comment]
Execute this command after starting your kali box this will resize your kali screen, but you have to execute this each time you want to resize your screen its a daunting task but this is the only workaround.

sudo xrandr --output Virtual-1 --auto

**Comment by deciphr102** [comment]
Execute this command which is shared below, each time when you want to resize the screen you need to run it..
Bit daunting task but this is the only workaround for now.

sudo xrandr --output Virtual-1 --auto

**Comment by PolLamothe** [comment]
Thanks

**Comment by godbout** [comment]
> sudo xrandr --output Virtual-1 --auto

argh was hoping that it would solve it for me but it didn't. sad.

**Comment by twentysixhugs** [comment]
Aug 2024, kali 2024.2 build running on m2 mac with UTM

Had the same problem

Found Kali HiDPI Mode in settings (xfce). Turn it on, then navigate to Display and play with resolution to find the one most comfortable. I used 2940x1840, worked nicely on a small mac display.

I had also turned on retina mode or something in display settings in UTM itself while the VM was not running. Don't know if it helped but the picture is pretty clear now. Display scaling still produces black screen, but I don't need it anymore.

**Comment by JamesBrodski** [comment]
> Aug 2024, kali 2024.2 build running on m2 mac with UTM
> 
> Had the same problem. Found a solution
> 
> Found Kali HiDPI Mode in settings manager (xfce). Turn it on, then navigate to Display and play with resolution to find the one most comfortable. I used 2940x1840, worked nicely on a small mac display.
> 
> I had also turned on retina mode or something in display settings in UTM itself while the VM was not running. Don't know if it helped but the picture is pretty clear now. Display scaling still produces black screen, but I don't need it anymore.
> 
> Additionally, I suggest you increase cursor size. It can be done in Mouse and Touchpad (xfce)
> 
> Also, I run the system in fullscreen
> 
> <img alt="image" width="267" src="https://private-user-images.githubusercontent.com/70529223/356888925-be38e3c0-8ebd-4472-9950-97af7974534e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI3Mzc4NDQsIm5iZiI6MTc0MjczNzU0NCwicGF0aCI6Ii83MDUyOTIyMy8zNTY4ODg5MjUtYmUzOGUzYzAtOGViZC00NDcyLTk5NTAtOTdhZjc5NzQ1MzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzIzVDEzNDU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwY2YzNGVmYmY4NzcxNjYyYmU4OGQxZDcwOGZlYjkwNzA0MTUyZWI0NjhmNWZkMGM2NDAxYWE0NWUzMmE5MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A2P6iSf1yEnoR4xCEstL0NEdErHH9Ow4Z-Ayx_uY0Uw">

This worked for me! Thank you!
