### ISSUE TITLE
UTM 4.3.4 stuck on "Guest has not initialized the display (yet)"

### ISSUE THREAD

**Issue by nickdowell** [utmapp/UTM#5525]
**Describe the issue**

After upgrading UTM to version 4.3.4 (86) via the App Store, I am unable to boot my VMs. The VMs still boot if I run UTM version 4.2.5.

My Windows 11 VM remains stuck showing "Guest has not initialized the display (yet)" and never shows the BIOS boot screen. QEMULauncher is using lots of CPU while this is happening. My Linux VM gets stuck with a blank light grey window, without a message. Again QEMULauncher is using lots of CPU.

The new "TPM 2.0 Device" setting is **not** enabled.

The same problem occurs with a freshly created ARM64 Alpine Linux VM in 4.3.4 - stuck on "Guest has not initialized the display (yet)". 

**Configuration**  
* UTM Version: 4.3.4 (86)
* macOS Version: 13.5
* Mac Chip (Intel, M1, ...): M1

**Debug log**

Linux VM: [debug.log](https://github.com/utmapp/UTM/files/12258853/debug.log)

**Upload VM**  

Linux VM: [config.plist.zip](https://github.com/utmapp/UTM/files/12258857/config.plist.zip)

**Comment by otizi** [comment]
I'm getting the same black screen: "Guest has not initialized the display (yet)"
I tried to change back to QEMU 7 but that did not work so I tried to reinstall my VM's 
but unable to do even the reinstallation - still stuck on the black screen.

**Comment by osy** [comment]
Duplicate of #5523

**Comment by nickdowell** [comment]
Sorry for opening a duplicate, the original title of #5523 made it seem like a different issue

**Comment by rS7Y** [comment]
Anyone found a fix to this?

**Comment by joshmarto** [comment]
Hello everyone. I had the same issue. Unfortunately, I could not find a way to fix it. I think you should delete that VM and create a new one. You can follow step by step., I worked perfectly for me
[Install Ubuntu in MacOS with UTM](https://www.youtube.com/watch?v=O19mv1pe76M)

**Comment by Mr-Robot-10101** [comment]
Anyone find a fix to this?

I found a solution for this This worked me; try So in UTM, change the Emulated Display Card (VGA) in drop-down list 

I'll attach the image in below 

<img width="1012" alt="Screenshot 2023-12-26 at 08 36 42" src="https://github.com/utmapp/UTM/assets/64756024/2b1e4bf3-01c3-4114-bdad-5e9027a07294">

**Comment by mgh24** [comment]
Unfortunately, changing emulated display card did not work for me.

**Comment by digitaldarkzone** [comment]
Under Edit > System I changed the QEMU version and it worked again.

**Comment by anonyme012** [comment]
> Under Edit > System I changed the QEMU version and it worked again.

To what version do you change ?

**Comment by tdewolf** [comment]
I just restarted the VM with the UTM restart button and that worked fine.
![Screenshot 2024-07-12 at 07 55 49](https://github.com/user-attachments/assets/1a99a8f2-9827-4a47-a181-5eff1a5c24a7)

**Comment by salmantec** [comment]
I downloaded UTM from App Store and faced this **_Guest has not initialized the display (yet)_** issue first time. I configured once again by unchecking (by default it has selected in the first time) this `Legacy hardware` option and it started working fine for me

<img width="449" alt="Screenshot 2024-08-17 at 4 47 17 PM" src="https://github.com/user-attachments/assets/9ca4306a-eed4-4030-8b16-c7a65d034248">

**Comment by janstieler** [comment]
@Basantdwd2 what do you mean with serial default settings? Or what did you prompt in the terminal after?

**Comment by kondevMobile** [comment]
I'm using Vectras VM (QEMU), and too have the same problem. This is how i solve:
1. Optional run settings
2. Replace `-device VGA` -> `-nographic`
3. Run VM

I don't know why its appears when use `VGA`, but anyway its works for me with `-nographic`.

**Comment by kondevMobile** [comment]
I'm using Vectras VM (QEMU for Android).
After a many hours i solve this problem with changing display device:

1. VM run settings
2. Change `-device VGA` -> `-device virtio-gpu-pci`
3. Save settings and Run VM

I hope its solve not only my problem.
