### ISSUE TITLE
v4.3.5 broke my Windows VM. Subsequent installs have the same issue.

### ISSUE THREAD

**Issue by N3XI5** [utmapp/UTM#5530]
<img width="800" alt="Screenshot 2023-08-04 at 11 04 40 PM" src="https://github.com/utmapp/UTM/assets/72477709/348df9b1-d044-4d5a-a12b-8016c526bc00">
<img width="800" alt="Screenshot 2023-08-04 at 11 05 25 PM" src="https://github.com/utmapp/UTM/assets/72477709/6ccc43fd-1a20-4fc6-88a6-50a79e8e9ed0">
<img width="800" alt="Screenshot 2023-08-04 at 11 05 35 PM" src="https://github.com/utmapp/UTM/assets/72477709/54f90f1f-953e-465d-b70a-1dad50a80645">
<img width="797" alt="Screenshot 2023-08-04 at 11 05 45 PM" src="https://github.com/utmapp/UTM/assets/72477709/56011f82-e03b-440b-9bea-ae1a6a3d8d31">

14" Macbook Pro with a M1 Pro trying to use my windows 11 VM thats been working perfectly.

Just the glassy looking screen no matter what I do. (forgot to save the logs before deleting, but they looked completely normal).
When I swap the gpu to a non-accelerated one, it gives the "Guest has not initialized the display (yet)" error.

If you guys need the logs I'll redownload the VM and log them, but hopefully someones aware of this

**Comment by osy** [comment]
Are you sure you’re on 4.3.5 and not 4.3.4?

**Comment by N3XI5** [comment]
> Are you sure you’re on 4.3.5 and not 4.3.4?

Just checked I am in fact on 4.3.4

I purchased UTM from the AppStore, is 4.3.5 not live there yet?

**Comment by osy** [comment]
4.3.5 was literally released hours ago precisely to address this issue. You need to manually refresh App Store’s updates tab to see it.

**Comment by N3XI5** [comment]
> 4.3.5 was literally released hours ago precisely to address this issue. You need to manually refresh App Store’s updates tab to see it.

Thank you so much man! Appreciate the insanely fast response. Also just realized there are plenty of threads about this is in the issues tab my bad lol
