### ISSUE TITLE
Directory share  Mode dropdown needs to be explicitly clicked to generate fsdev args

### ISSUE THREAD

**Issue by nabiltntn** [utmapp/UTM#5531]
**Describe the issue** 

Directory share  Mode dropdown needs to be explicitly clicked, otherwise default VirtFS  mode won't result to required qemu arguments to be generated. When mount the volume, the share is not available.

The missing args are : -fsdev local,id=virtfs0,path=MY_FOLDER,security_model=mapped-xattr -device virtio-9p-pci,fsdev=virtfs0,mount_tag=share

<img width="476" alt="image" src="https://github.com/utmapp/UTM/assets/223719/240910ac-bde9-4b6f-bf4a-406c0d26fdc1">

Every time, I make a change to VM settings, I need to click and choose again the same VirtFS value to make sure Qemu command args are correct.

Previous 4.2.5 version was OK

 **Configuration**  
* UTM Version: 4.3.4
* macOS Version: Venture 13.0
* Mac Chip (Intel, M1, ...):  M1

**Comment by nabiltntn** [comment]
It looks like this is related to this code ( but not the result of this commit since it was working with version 4.2.5)

https://github.com/utmapp/UTM/commit/40187dc4f12ea6b162276fee48feff21b340f5d4

**Comment by nabiltntn** [comment]
This was fast, thanks !

**Comment by code-a-cola** [comment]
I am still experiencing this issue on v4.3.5

**Comment by code-a-cola** [comment]
This is odd issue for me if open settings when first launching UTM the shared directory does not persist, but if i close settings and open it back up the shared directory persists. I have to do this after each relaunch of UTM.

**Comment by osy** [comment]
> I am still experiencing this issue on v4.3.5

Hi, this is fixed in v4.4
