### ISSUE TITLE
VM Startup (QEMU RAM Allocation) Errors with High (>32GB) RAM on M2 Max Macbook

### ISSUE THREAD

**Issue by Aeonitis** [utmapp/UTM#5537]
When attempting to start a virtual machine using a large amount of RAM (e.g. 81,920MB or 65,536MB) on my physical 96GB RAM M2 Max MacBook through UTM, I intermittently receive one of two error messages. Purpose is to build Android OS code.

The first is: 
`QEMU error: QEMU exited from an error: qemu-aarch64-softmmu: Error: HV_BAD_ARGUMENT` 

and the second: 
`QEMU error: QEMU exited from an error: qemu-aarch64-softmmu: -drive if=none,media=cdrom,id=drive6EA5E6A4-0E92-4C50-9C56-405C793F1C8E,file=/Users/aeonitis/Downloads/ubuntu-22.04.2-live-server-arm64.iso,readonly=on: Could not open '/Users/aeonitis/Downloads/ubuntu-22.04.2-live-server-arm64.iso': Operation not permitted.` 

The issue does not persist when the RAM allocation is set to 32,768MB or less. Everything seems to run fine within that limit.

Additionally, upon inspecting the code, I noticed that the [RAMSlider](https://github.com/utmapp/UTM/blob/449bee449aefc13f8c9015535f20dd30e53da4eb/Platform/Shared/RAMSlider.swift#L20) is limited to 32GB maximum. Considering modern Macs now support up to 192GB RAM, I suggest updating this slider for better alignment with the latest hardware capabilities. I stopped troubleshooting past going through the [systemMemory](https://github.com/search?q=repo%3Autmapp%2FUTM%20systemMemory&type=code) variable which might also play a role in this limitation...

**Configuration**  
* UTM Version: 4.3.5
* macOS Version: 13.5
* Mac Chip: M2 Max
* Storage: 300GB
* Cores: 20 out of 24

Sorry I can't provide logs as the folders didn't seem to produce them pre-boot I guess, and for some reason the mac app reporting popup stopped appearing. I'm kinda glad this is the case as I don't wanna share more private device data.

**Comment by osy** [comment]
@agarf Is there a HVF limitation on the amount of RAM that can be allocated?

**Comment by osy** [comment]
@oscarbg I thought you're on Apple Silicon? That change only applies to x86_64

**Comment by Aeonitis** [comment]
Thank you guys!!! @oscarbg & @osy 

So I guess it'll be available in v9.2.0 release right?
