### ISSUE TITLE
utmctl over ssh doesn't work

### ISSUE THREAD

**Issue by CamJN** [utmapp/UTM#5557]
Running `utmctl` in an ssh session, results in `Trace/BPT trap: 5`, no matter what flags are passed. It may matter that I disable PAM and log in using only an ssh cert, this seems to affect other things as there is no associated [security session](https://developer.apple.com/documentation/security/sessions).

**Configuration**  
* UTM Version: 4.3.5
* macOS Version: 13.5 (22G74)
* Mac Chip: M2

**Comment by osy** [comment]
utmctl over SSH doesn't work (see #5377 and related). This is due to macOS limitation with the apple events interface. However, you shouldn't be getting a crash but an error message. If you get a crash log, open an new issue and we'll see how to replace it with an error message.
