### ISSUE TITLE
Unusable on iOS 17. 

### ISSUE THREAD

**Issue by BH-Playz** [utmapp/UTM#5559]
I tried to install UTM on iOS 17. (dev beta) BUT! I cannot get AltStore to JIT UTM! Even though iOS 17 is only for members of the Apple Beta Software Program. (Which I call the Apple Insider Program) Still. I would rather have this bug fixed than downgrade BACK to iOS 16.5. Also, Thank you.
**Techy stuff:**
* UTM Version: 4.3.4
* OS Version: iOS 17 Devploper Beta
* Device Model: iPhone XR MT492LL/A
* Is it jailbroken: no
* How did you install UTM? AltStore

**Comment by osy** [comment]
Is this an AltJIT issue? Do other apps work with AltJIT?

**Comment by BH-Playz** [comment]
I don’t think so.

**Comment by osy** [comment]
I asked two questions, which one are you answering?

**Comment by BH-Playz** [comment]
Other apps on AltJIT don’t work:

AltStore
Delta
UTM

Again, I think iOS 17 has no JIT support yet.

**Comment by BH-Playz** [comment]
Hey osy, I am sorry for sending that last comment at 7AM, I didn't release that it was 7AM. Again, i'm sorry, Also other apps on AltJIT don't work by the way.

**Comment by BH-Playz** [comment]
osy?? Are you there?

**Comment by osy** [comment]
Sorry, this is not the right place to report AltJIT issues. Please follow up with AltStore.

**Comment by BH-Playz** [comment]
OH Okay then, Sorry for wasting your time.

**Comment by Edgecrusherr160** [comment]
The JIT compiler warns that the UTM URL is bad. I think it really does need to get fixed on the AtlStore side, as they do say that JIT is working via Macs or directly in the AtlStore, and it's failing on other side loading apps too. However, maybe they need some updated info from the developers for each app? I'm not sure.

Hopefully it gets worked out soon, I just got an iPad Pro, and if I can get this working, I'm going to renew may paid Apple Dev account so I can install more than 3 sideloaded apps and not worry about connecting my iPad to my computer every 7 days.

**Comment by gkpln3** [comment]
AltJit is seemingly working for iOS 17 now, but UTM doesn't seem to be able to work with it, any updates on this?
