### ISSUE TITLE
Unable to load Windows 11 x64 on macOS arm64 (error: "0xc0000428 Windows cannot verify the digital signature for this file")

### ISSUE THREAD

**Issue by lewixlabs** [utmapp/UTM#5560]
**Describe the issue**  
I'm trying to install Windows 11  x64, build number 22621.1702.230505-1222, on my mac mini M1:
- installation complete without issue
- first reboot after installation show BSOD screen with this error: `0xc0000428 Windows cannot verify the digital signature for this file`
Seems to be related to vioscsi.sys system file.

Has anyone encountered my same problem? If so, has he solved it?
Thank you for any suggestion, here below all infos about my environment and screen error image.
P.S.: I tried other windows 11 x64 iso build versions, but result is the same.

Thanks,
Lewix

**Configuration**  
* UTM Version: 4.3.5 (87)
* macOS Version: Ventura 13.4.1
* Mac Chip: M1

**UTM log**  
Attached utm.log

**Upload VM**  
Attached config.plist.zip

![image](https://github.com/utmapp/UTM/assets/7371215/469238bf-98b2-4e08-a491-5a212e696343)

[config.plist.zip](https://github.com/utmapp/UTM/files/12330283/config.plist.zip)
[utm.log](https://github.com/utmapp/UTM/files/12330284/utm.log)

**Comment by BH-Playz** [comment]
x64 doesn't work with ARM64. You need a ARM64 ISO.

**Comment by BH-Playz** [comment]
x64 will work fine on Intel Macs.

**Comment by lewixlabs** [comment]
Hi @BH-Playz ,
UTM uses QEMU and can (slowly) emulate x64 on ARM64 M1.
I confirm I tried official UTM Windows 7 X64 image and it works on ARM64 (like mine, M1 chip)
https://mac.getutm.app/gallery/windows-7

If Windows x64 didn' work, I couldn't even launch Windows 11 x64 installer

**Comment by tifasoftware** [comment]
Did you use the latest version of CrystalFetch?

**Comment by BH-Playz** [comment]
x64 **DOES** work, but it is emulating a x64 processor, Which I don't think the vCPU is powerful enough, I also tried installing Windows 7 on my Macbook, however I could barely get chrome to even install. That's why.

If you use a ARM ISO, you can natively run Windows 11 smoothly.

**Comment by BH-Playz** [comment]
The Installer can run bc it is a Windows 10 PE. Idk why M$ didn't use a Windows 11 PE, but who cares.

**Comment by lewixlabs** [comment]
> Did you use the latest version of CrystalFetch?
> 

Yes! v2.0.0

**Comment by lewixlabs** [comment]
> x64 **DOES** work, but it is emulating a x64 processor, Which I don't think the vCPU is powerful enough, I also tried installing Windows 7 on my Macbook, however I could barely get chrome to even install. That's why.
> 
> If you use a ARM ISO, you can natively run Windows 11 smoothly.

Yes arm iso works I know, I have already a vm windows arm64.
I need to emulate x64 for a particular x64 app of my job.

"x64 **DOES** work, but it is emulating a x64 processor" exactly,  before I write my reply only to clarify this (in your first post seems the opposite 

Thank you anyway for your help.
As I described in my first post, issue is not emulating (x64 win works in arm64) but is to solve a final configuration issue of Windows, probably just tuning utm vm configuration.

Thanks to all
Lewix

**Comment by freebrowser1** [comment]
For Win11, TPM2 is required.
Go to Settings => QEMU => Check TPM 2.0.

For me, it works (Win11 x86-64 on an M1 machine).

Read this: https://github.com/utmapp/UTM/releases/tag/v4.3.5

"TPM 2.0 and Secure Boot This is required for Windows 11 updates to 22H2. To enable TPM on an existing virtual machine (only x86_64, i386, and ARM64 architectures are supported), open the VM settings, go to the QEMU page and select "UEFI Boot", "TPM 2.0 Device", and "Reset UEFI Variables." Any new VM created through the wizard will have TPM 2.0 and Secure Boot enabled by default if Windows 10+ support is checked."

**Comment by lewixlabs** [comment]
> For Win11, TPM2 is required. Go to Settings => QEMU => Check TPM 2.0.
> 
> For me, it works (Win11 x86-64 on an M1 machine).
> 
> Read this: https://github.com/utmapp/UTM/releases/tag/v4.3.5
> 
Thank you, yes I noticed this in release notes of v4.3.5. 
I did also this setup but same issue
![image](https://github.com/utmapp/UTM/assets/7371215/e47ccb73-8139-4077-a40f-a8db8416a136)

> > "TPM 2.0 and Secure Boot This is required for Windows 11 updates to 22H2. To enable TPM on an existing virtual machine (only x86_64, i386, and ARM64 architectures are supported), open the VM settings, go to the QEMU page and select "UEFI Boot", "TPM 2.0 Device", and "Reset UEFI Variables." Any new VM created through the wizard will have TPM 2.0 and Secure Boot enabled by default if Windows 10+ support is checked."
> 
> And in emulation, enable force Multicore and set to 8 cores, then the speed is acceptable, otherwise it is not workable.
I had 6 cores, I upgraded to 8

I will try another win 11 x64 iso without using Crystal Fetch, just to clear a doubt.

**Comment by BH-Playz** [comment]
Some x64 apps can be emulated on ARM64 Windows.

**Comment by lewixlabs** [comment]
Ok found a workaround (disabling this windows feature on tech boot menu)
https://www.wintips.org/how-to-fix-windows-cannot-verify-the-digital-signature-for-this-file-error-in-windows-8-7-vista/

**Comment by eEQK** [comment]
> For Win11, TPM2 is required. Go to Settings => QEMU => Check TPM 2.0.
> 
> For me, it works (Win11 x86-64 on an M1 machine).

I kept getting error about missing `vioscsi.sys` when trying to install x86-64 windows in UTM, but it finally let me in after disabling TPM 2.0 in QEMU settings. 

I had the same error on both win11 and win10 but I only tried disabling TPM 2.0 on win10, not sure if it will work for 11 as well

(the performance is poor but I specifically need to use x86-64 since there seems to be no ARM drivers for what I want to do)

**Comment by freebrowser1** [comment]
> > For Win11, TPM2 is required. Go to Settings => QEMU => Check TPM 2.0.
> > For me, it works (Win11 x86-64 on an M1 machine).
> 
> I kept getting error about missing `vioscsi.sys` when trying to install x86-64 windows in UTM, but it finally let me in after disabling TPM 2.0 in QEMU settings.
> 
> I had the same error on both win11 and win10 but I only tried disabling TPM 2.0 on win10, not sure if it will work for 11 as well
> 
> (the performance is poor but I specifically need to use x86-64 since there seems to be no ARM drivers for what I want to do)
Set the CPU to 'Force multicore' and select 8 cores. That will increase speed considerably and make workable, but obviously not to native speed.

**Comment by BH-Playz** [comment]
Glad I could help!

**Comment by triberichard** [comment]
@eEQK 's comment (https://github.com/utmapp/UTM/issues/5560#issuecomment-1680886391) solved the problem for me. Thank you! 🙏 

For other newcomers to UTM, you can open the QEMU settings by clicking the "Edit selected VM" button in the top right corner of the main UTM window:

<img width="345" alt="image" src="https://github.com/utmapp/UTM/assets/123093585/6efe6aff-ee28-423e-9ce9-52ba479433c3">
