### ISSUE TITLE
Way to set Hypervisor Vendor in guest OS

### ISSUE THREAD

**Issue by joshtbernstein** [utmapp/UTM#5565]
I have a virtual appliance that looks at the hw.hv_vendor kernel parameter (FreeBSD) to determine which hypervisor it's running on.

When using TCG this is set to "TCGTCGTCGTCG" and when using HVF this is blank. Is there a way to provide an override so that I could set this to "KVMKVMKVM" (what it's set to on a machine running KVM)? The appliance doesn't actually need KVM, it just uses that to determine it's virtual and not physical.

**Comment by osy** [comment]
Can you figure out how to do this in QEMU? If it's possible in QEMU, we can probably add an option.

**Comment by joshtbernstein** [comment]
@osy Sorry for the delay, it seems that there's a `-cpu` [option](https://www.qemu.org/docs/master/system/i386/hyperv.html) that should do this, but I couldn't get it to work.

`-cpu kvm64,hv-avic,hv-vendor-id=KVMKVMKVM`

I'm not sure if it's not doing what I think it does or if it's not implemented in UTM.

**Comment by osy** [comment]
So it is currently not implemented in UTM but I need a reference on how to do it in QEMU in order to implement it. That means installing `brew install qemu` and running with the right command line options to achieve what you want to do and then pasting that command here.

**Comment by joshtbernstein** [comment]
It looks like this won't work without changing the code in QEMU. Want me to close this out?

**Comment by osy** [comment]
Feel free to keep it open if you want just know that it’ll be blocked on QEMU’s implementation.
