### ISSUE TITLE
IDE bus drive 2 in QEMU forces a stop in the vm.

### ISSUE THREAD

**Issue by BokBoy** [utmapp/UTM#5566]
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Describe the issue**  
Having more than 3 drives causes the message to appear.
QEMU error: QEMU exited from an error: qemu-x86_64-softmmu: -device ide-cd,bus=ide.2,drive=drive5D147C8C-5E1A-4CD2-8FBB-D7737A89A974,bootindex=2: Bus 'ide.2' not found
Please help...

**Configuration**  
* UTM Version: 4.3.5 (also happened in 4.2.5
* macOS Version: 14.0 (Beta 3 i think)
* Mac Chip (Intel, M1, ...): ARM M2 8 core cpu and gpu.
* Using 3 IDE Drives, spice, hard disk and iso for win 8.1
* Standard PC (i440FX + PIIX 1996) (pc-i440fx-7.1)
* Default CPU, 4096 mb ram and  4 cpu cores
* Configured storage for 64gb

**Crash log**  
If the app crashed, you need a crash log. To get your crash log, open Console.app, go to `Crash Reports`, and find the latest entry for either UTM, QEMU, QEMUHelper, or qemu-\*. Right click and choose `Reveal in Finder`. Attach the report here.

**Debug log**  
Attachment
How to attach log?? will try to attach in comment later.

**Upload VM**  
If your issue is related to a specific VM, please upload the config.plist from your VM's .utm directory. To get this, right-click the VM in UTM and choose "Show in Finder". Then right-click the selected file in Finder and choose "Show Package Contents". The config.plist file is now visible. Right-click it and choose "Compress". Attach the resulting config.plist.zip file here.
You can upload the entire .utm if needed, but note this includes your VM's drive image and may contain personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by BokBoy** [comment]
Debug refusing to upload, help pls??

**Comment by BokBoy** [comment]
[Debug Windows 8.1.log](https://github.com/utmapp/UTM/files/12364071/Debug.Windows.8.1.log)
YES FINALLY IT UPLOADED!!

**Comment by osy** [comment]
I believe that `pc-i440fx` does not support > 2 IDE drives. You would need to use `qmp` target or a different interface (like SCSI or something).

**Comment by BokBoy** [comment]
Tysm for answer, will switch to the default one.
