### ISSUE TITLE
Cannot create a macOS vm using apple script

### ISSUE THREAD

**Issue by gnasr** [utmapp/UTM#5590]
**Describe the issue**  
I'm trying to script a macOS vm creation following the example in the CheatSheet but the resulting VM is always a linux VM, the documentation seems to be incomplete too, since it doesn't show how to specify boot or operating system parameters in configuration (if it's possible at all).
I don't know if i understand correctly but it seems to be hardcoded that the VM created with scripting will always be linux, am i right? https://github.com/utmapp/UTM/blob/main/Scripting/UTMScriptingCreateCommand.swift#L106

**Configuration**  
* UTM Version: 4.2.5
* macOS Version: 13.3.1
* Mac Chip:  M1

If someone can show me how to script a macOS vm would be really helpful.
Thanks

**Comment by gustaf71** [comment]
In AppleScript property of object could have property of other object. In other words a nested property.
In normal case the specified object that contents property you use the same method set for target object.
UTM have a special method to update configuration.

Here is example how to change memory for VM from 8GB to 4GB.
```
tell application "UTM"
	set theVMs to name of virtual machines
	if "Fedora 38 ARM" is in theVMs then
		tell virtual machine "Fedora 38 ARM"
			log {"Current memory: ", memory of (get configuration)}
			set newConf to {memory:4096}
			update configuration with newConf
		end tell
	end if
end tell
```
