### ISSUE TITLE
IPSW Install Image File Is Not Saved in .UTM package

### ISSUE THREAD

**Issue by runwaygoats** [utmapp/UTM#5596]
**Describe the issue**  

Create a macOS VM using "Virtualize" without running it.
Remove the VM from UTM.
Re-Add the same VM to UTM.
IPSW Install Image under Boot tab is empty.

This behavior is similar to Sharing tab.

**Configuration**  
* UTM Version: 4.3.5
* macOS Version: 14.0 Beta (23A5328b)
* Mac Chip (Intel, M1, ...): M1

**Comment by osy** [comment]
Yes this is intended. Why would you remove a VM without installing it?

**Comment by runwaygoats** [comment]
I use it as a template.
I create it in one macOS, and use it on different versions of macOS.
Even if .IPSW file name seems the same, I replace the .IPSW file with the updated one.

I was also trying to replicate the issue.

**Comment by osy** [comment]
Don’t use the auto-download feature then. Download the ipsw yourself and mount it for each image. There’s no point wasting space on every VM for an installer that only runs once.

**Comment by runwaygoats** [comment]
I totally agree.
I don't use the download IPSW feature of UTM.
I download IPSW files myself and then select them within UTM.
