### ISSUE TITLE
Graphical acceleration in AVF Linux VMs

### ISSUE THREAD

**Issue by NateyB** [utmapp/UTM#5602]
I installed an Arch ARM64 VM using the Apple Virtualization Framework. In this case, UTM attaches a VZVirtioGraphicsDeviceConfiguration to the VM.

Graphics work, and I can see from the output of `lspci` that a VirtIO GPU is attached. I've installed mesa, but `glxinfo | grep OpenGL` shows that `llvmpipe` is still being used. Is this because of a lack of driver support on the Linux side for supporting Apple's virtualized GPU?

**Comment by osy** [comment]
There is no VirGL in Apple's VF. This is something you can file a feedback for with them.
