### ISSUE TITLE
Mouse cursor disappears completely (from the UTM main window) if the cursor is inside the window of a closing macOS 14 VM (while it's saving its state)

### ISSUE THREAD

**Issue by rxhfcy** [utmapp/UTM#5607]
**Describe the issue**  
The mouse cursor disappears completely (edit: from the UTM main window) if you close a macOS 14 (beta) VM window and then *immediately* move the mouse cursor inside that same VM window (while the window is still in the process of closing / saving the VM state)

edit: The mouse cursor only comes back after quitting and reopening UTM.app

**Configuration**  
* UTM Version: v4.4.0 (Beta) / 4.4.0 (88)
* macOS Version: 14.0 Beta (23A5328b)
* Mac Chip (Intel, M1, ...): M1 (MacBook Air M1, 16 GB RAM)

Steps to reproduce:
0. Make a new macOS 14 Beta VM (see below for details)
1. Start a macOS 14 Beta VM, login into macOS normally
2. Close the macOS UTM VM window from the red close button (top left corner) (UTM begins to save the state of the VM)
3. (a) Immediately move the mouse cursor down and right so that the cursor is hovering *inside* the VM window you just clicked to close

What happens: the mouse cursor disappears completely (!) and doesn't reappear until you switch to another application or quit UTM.app
Expected: normal mouse cursor

3. (b) If after clicking close you keep the mouse cursor *outside* the VM window, the cursor doesn't disappear.

The mouse cursor only seems to disappear if it's hovering inside the VM window while it's closing / saving the state of the VM.

PS. Here's how I made the macOS 14 beta VM, it's as standard/uninteresting as possible:
1. Download "UniversalMac_14.0_23A5328b_Restore.ipsw" (14.0 beta 6) from here: https://ipswbeta.dev/macos/14.x/
2. In UTM, click "+" (New)
3. Virtualize
4. macOS 12+
5. Browse... (choose the ipsw file downloaded previously)
6. Continue -> Continue -> Save
7. Edit the VM settings -> Virtualization -> disable "Enable entropy device" and "Enable Sound" -> Save
8. Start the new VM
9. Install macOS normally

**Comment by osy** [comment]
This is an issue with Virtualization.framework. You can probably report the issue to Apple but if not, at some point, I will compile all the issues filed here and send them to Apple.

**Comment by osy** [comment]
Let me try

**Comment by johnnyshankman** [comment]
I still have this issue constantly. Randomly the cursor just disappears and i cannot get it back.

**Comment by curtismccaw** [comment]
Same issue here.

**Comment by Willsondrojas** [comment]
Hola, mi problemas es que al entrar a la VM UTM tengo que seleccionar (captura cursor del mouse) en la parte superior derecha de la maquina para poder trabajar dentro y para salir tengo que seleccionar CTRL + option, sabrán como eliminar este comando y pueda trabajar libre entre el local y ma VM como se hacia antes de la última actualización?

**Comment by munntjlx** [comment]
At least in alpine desktop if you switch from wayland to x the problem goes away.
