### ISSUE TITLE
Save and restore custom resolutions

### ISSUE THREAD

**Issue by rxhfcy** [utmapp/UTM#5609]
**Describe the issue**  
macOS 14 (beta) VM doesn't remember its custom Display size (dynamic resolution) after restoring a saved VM state

**Configuration**  
* UTM Version: v4.4.0 (Beta) / 4.4.0 (88)
* macOS Version: 14.0 Beta (23A5328b)
* Mac Chip (Intel, M1, ...): M1 (MacBook Air M1, 16 GB RAM)

Steps to reproduce:
0. Make a new macOS 14 Beta VM (see below for details)
1. Start a macOS 14 Beta VM, login into macOS normally
2. From the menu (inside the VM): System Settings... / Displays
3. Look at the current display settings: something x something (Default)
4. Resize the VM window so that the size becomes something like "600 x 600 (Default)"
5. Save the VM state by clicking the red close button (top left corner of the VM window)
6. From UTM, restore the VM
7. From the menu (inside the VM): System Settings... / Displays
8. Look at the display settings again: shouldn't it still be something like "600 x 600 (Default)"?

What happens: the size is not "600 x 600 (Default)" anymore
What I expected: Shouldn't the size remain the same? I didn't expect the VM display size to change

PS. Here's how I made the macOS 14 beta VM, it's as standard/uninteresting as possible:
1. Download "UniversalMac_14.0_23A5328b_Restore.ipsw" (14.0 beta 6) from here: https://ipswbeta.dev/macos/14.x/
2. In UTM, click "+" (New)
3. Virtualize
4. macOS 12+
5. Browse... (choose the ipsw file downloaded previously)
6. Continue -> Continue -> Save
7. Edit the VM settings -> Virtualization -> disable "Enable entropy device" and "Enable Sound" -> Save
8. Start the new VM
9. Install macOS normally

**Comment by osy** [comment]
This is something that we need to implement for both QEMU and AVF at some point.
