### ISSUE TITLE
Cloning a VM on a Non-Boot Partition Actually Imports the VM into System Partition

### ISSUE THREAD

**Issue by runwaygoats** [utmapp/UTM#5610]
**Describe the issue**  

I have partitioned the internal disk like this.

- All partitions are on the same APFS Container.
- One data partition that stores all VM packages (.UTM folders)
- A separate partition for every macOS system I want to test.

This way, I do not need to move hundreds gigabytes of VMs every time I install a new macOS to use as a host.

Cloning a 137GB VM in Sandbox (/Users/~/Library/Containers/UTM) is instantaneous as expected.

But cloning the same 137GB VM on a Non-Boot Partition takes 13 minutes and 20 seconds.
UTM copies 137GB of data from the Non-Boot Partition to Boot Partition (to /Users/~/Library/Containers/UTM).

If I try to copy the same 137GB of .UTM folder using Finder, it takes 12 seconds.

When I need to clone a VM, I use Finder to duplicate .UTM and it is instantaneous as expected.

I would expect the clone option in UTM would duplicate the VM at its location.

The current function may be kept under a different name like "Import to System Partition".

**Configuration**  
* UTM Version: 4.4.0 (88)
* macOS Version: 14.0 Beta (23A5328b)
* Mac Chip (Intel, M1, ...): M1

**Comment by osy** [comment]
Unfortunately, due to app sandboxing, we don't have access to the directory the VM is stored in once it's outside the sandbox. I think it's fine to just manually "clone" the VM in Finder and open it as a shortcut. We can probably add an UI for this but it'll probably be low priority.

**Comment by runwaygoats** [comment]
No problem for me.

If the VM is out of sandbox, a message box with the text "Due to app sandboxing restrictions, Virtual Machines out of app sandbox can't be cloned. Please clone within Finder.app" may prevent future issues with other users.
