### ISSUE TITLE
CD/DVD Drive DiskImage.iso path: Could not open, Operation not Permitted

### ISSUE THREAD

**Issue by runwaygoats** [utmapp/UTM#5615]
**Describe the issue**  

VM Name:  QemuEmulatedDebian.UTM
                    Used within UTM.app all the time.

VM Backup Name: QemuEmulatedDebianBackup.UTM
                                Always used as an offline backup and never used within UTM.app to prevent recreation of VM UUID.
                                When needed, while UTM.app is closed, QemuEmulatedDebian.UTM is deleted and a new QemuEmulatedDebian.UTM is duplicated from QemuEmulatedDebianBackup.UTM

Steps to Reproduce

While UTM.app is closed, duplicate QemuEmulatedDebian.UTM as QemuEmulatedDebianBackup.UTM within Finder.
When something goes wrong with the QemuEmulatedDebian.UTM, quit UTM.app.
Delete QemuEmulatedDebian.UTM
Duplicate QemuEmulatedDebianBackup.UTM as QemuEmulatedDebian.UTM
Open UTM.app
Start QemuEmulatedDebian.UTM

Error

QEMU exited from an error: qemu-x86_64-softmmu: -drive if=none,media=cdrom,id=driveF177DB5E-953E-4CE1-8829-FEA9EC3C4694,file=/Volumes/data/DiskImage.iso,readonly=on: Could not open '/Volumes/data/DiskImage.iso': Operation not permitted

Fix

Edit QemuEmulatedDebian.UTM
Drives > IDE Drive > Path
Even if you see the DiskImage.iso file in Path Box, Browse... and select DiskImage.iso again.
Start QemuEmulatedDebian.UTM

**Configuration**  
* UTM Version: 4.4.0
* macOS Version:  14.0 Beta (23A5328b)
* Mac Chip (Intel, M1, ...):  M1

**Comment by osy** [comment]
It was included in v4.4.1 so you're probably hitting another issue. Also FDA doesn't mean anything in a sandboxed app.

**Comment by ernstki** [comment]
@osy, I was able to work around it using the advice from [https://github.com/utmapp/UTM/discussions/5837 this discussion], but I'll keep an eye out and if it's something reproducible, I'll collect more information for a proper bug report. Thanks!
