### ISSUE TITLE
QEMU 8 support

### ISSUE THREAD

**Issue by sm-moshi** [utmapp/UTM#5622]
Hi! 

Is there any QEMU 8 support planned or worked on? Because when creating VMs in UTM the latest one is QEMU 7.2 for example, while QEMU 8.1.0 is out for macOS via Homebrew.

Thanks!  I hope I'm not insulting anyone by this question. I love your work? (or should I try to contribute why trying to add support by myself?)

Greets

**Comment by tifasoftware** [comment]
We did have it based on QEMU 8, but the developers are holding off of QEMU 8 due to issue #5516

**Comment by osy** [comment]
There are multiple issues with 8.x that makes me think it’s not ready for prime time. There’s been reports of speed regressions, broken VMs, etc.

What specific feature do you need from the 8.x release? It’s likely we can port it over. I’m honestly thinking of hard forking QEMU from 7.2.0 and just picking in changes we want.

**Comment by sm-moshi** [comment]
I just researched a bit and checked my Gentoo VM. It seems like it could be about Gentoo currently only packing the qemu-guest-agent 6.00, 7.1.0, 8.0.0, 8.02 and 8.03. I'll write an ebuild for the guest agent version 7.2.0 and report back.

My concern is about the clipboard-sharing, because it simply does not work, but I'm not sure if it's, because of spice-vdagent 0.22.1 or qemu-guest-tools.

I'll report back after compiling the 7.2.0 one. 
Thanks!

**Comment by tifasoftware** [comment]
> There are multiple issues with 8.x that makes me think it’s not ready for prime time. There’s been reports of speed regressions, broken VMs, etc.
> 
> What specific feature do you need from the 8.x release? It’s likely we can port it over. I’m honestly thinking of hard forking QEMU from 7.2.0 and just picking in changes we want.

For QEMU 8, I was able to get sound working on NT 4. Previously on UTM with earlier versions of QEMU, it gave me an error saying that there was no sound blaster there.

**Comment by osy** [comment]
Interesting, I'll take note of that. Honestly, I think it's probably best to just wait for QEMU to "stabilize" and try again.

**Comment by osy** [comment]
I would if I can reproduce it... If I can reproduce it, I could probably fix it myself and send the patches

**Comment by otsuka-kohei** [comment]
> There are multiple issues with 8.x that makes me think it’s not ready for prime time. There’s been reports of speed regressions, broken VMs, etc.
> 
> What specific feature do you need from the 8.x release? It’s likely we can port it over. I’m honestly thinking of hard forking QEMU from 7.2.0 and just picking in changes we want.

The reason why I would like to use QEMU 8 is to avoid the issue #4924.
If [fix of this issue](https://gitlab.com/qemu-project/qemu/-/issues/1471) is ported, I appreciate very much.

**Comment by NickJLange** [comment]
I wouldn't mind picking the following (which may or may not have evolved) for raspberry pi4 support.

https://github.com/qemu/qemu/compare/master...0xMirasio:qemu-patch-raspberry4:master

**Comment by silvanshade** [comment]
> What specific feature do you need from the 8.x release?

QEMU 8 brings significantly improved RISC-V support, especially for recent vector and crypto related extensions. I think there may be some additions regarding SVE and also improved AVX support too. I would make use of these if available in UTM.

**Comment by mohd-akram** [comment]
QEMU 9 is out now.

**Comment by osy** [comment]
We have updated the backend to v9.1.2
