### ISSUE TITLE
Outdated Spice Guest Tools Windows Drivers (Windows cannot verify the digital signature for the drivers required for this device)

### ISSUE THREAD

**Issue by jimsmith** [utmapp/UTM#5623]
**Describe the issue**  

Outdated Spice Guest Tools Windows Drivers.

Using Spice Guest Tools ISO `spice-guest-tools-0.164.4.iso` (Windows Drivers):`Windows cannot verify the digital signature for the drivers required for this device`
- You will see **Digital Signer: Red Hat, Inc**

When using `virtio-win-0.1.229.iso` drivers work as expected.
- You will see **Digital Signer: Microsoft Windows Hardware Compatibility Publisher**

**Configuration**  
* UTM Version: 4.3.5 (87)
* macOS Version: Ventura 13.5.1
* Mac Chip (Intel, M1, ...): Apple M2 Max (Macbook Pro 16-inch 2023)

Split out from [Trusted Platform Module 2.0 - This device cannot find enough free resources that it can use (Code 12) - #5619](https://github.com/utmapp/UTM/issues/5619#issuecomment-1695780523)

A fresh new installation of Windows 10 Pro Intel x64 installer from Microsoft site: `Win10_22H2_EnglishInternational_x64v1.iso`

---
This took quite a significant amount of time over the weekend that has been invested in this.
I'm putting this in here for future people who stumble on this as it took me a good amount of time to track this down.
I found that the spice guest tools iso the drivers don't have a digital signature

I then came across this https://pve.proxmox.com/wiki/Windows_VirtIO_Drivers and used `virtio-win-0.1.229.iso` for loading the digitally signed drivers by Red Hat. It would be good to have these as part of UTM or documented that the spice one's fail to load as they don't have a digital signature.

From (above proxmox.com site)
> Windows OS Support

> Windows does not have native support for VirtIO devices included. But, there is excellent external support through opensource drivers, which are available compiled and signed for Windows:

> https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/?C=M;O=D

> Note that this repository provides not only the most recent, but also many older versions. Those older versions can still be useful when a Windows VM shows instability or incompatibility with a newer driver version.

> The binary drivers are digitally signed by Red Hat, and will work on 32-bit and 64-bit versions of Windows 
---

Using the windows drivers from `spice-guest-tools-0.164.4.iso` results in the following:

**Screenshots of the windows drivers installed from the windows guest tools from `spice-guest-tools-0.164.4.iso` (No Digital Signer)**
- Network Driver
 <img width="366" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/cc200ecc-4ae0-4ed6-8860-f09d0a8b8919">

  <img width="908" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/ec7ac736-e59d-464b-8e69-bd655c2591bc">
  
<img width="592" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/4544ac55-c8b4-4536-b13f-61cf24460399">

 <img width="593" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/3c2a852b-c950-4394-9a65-cc9a21d4382d">

- PCI Simple Communications Controller (VirtIO Serial Driver)

 <img width="223" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/b3462f33-6c32-42b4-897d-09b3eec6291d">

 <img width="234" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/76b0302d-6209-4ee3-9abe-005503d366a0">

 <img width="438" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/36d8ed9b-9c1c-4476-9838-086bcfb34bfe">

 <img width="904" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/d7588394-9149-43aa-88d2-7f63c846110f">
 
 <img width="594" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/0af2cf0a-cad1-447b-a9d0-7be943bfe8c0">

 <img width="590" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/6fa51030-17c3-465d-afa2-c01f2a5b72f0">

- PCI Device (VirtIO RNG Device)
 <img width="199" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/db9cb4b6-762c-4cc6-9cc3-a8705f34e1c0">

 <img width="909" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/d3363557-edc0-49f9-8f6c-67b4c72a1dd9">

 <img width="593" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/4b21f552-75f4-436d-96e3-76b920dfcf6b">

<img width="594" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/4d936388-f474-4a60-8dc6-7ec5ae99d3b4">

---

- The Trusted Platform Module 2.0 fails to load.
This device cannot find enough free resources that it can use. (Code 12)

If you want to use this device, you will need to disable one of the other devices on this system.

<img width="391" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/ad2c4ee3-b5a8-425a-9e50-5ee8844033c2">

<img width="515" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/84040c02-c48e-4edd-9f18-ae025d94a15d">

<img width="513" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/b4ef3cec-af31-4fde-b259-7ba111552aa6">

<img width="515" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/dc9e4b33-147f-4a58-88b7-1155da222640">

<img width="517" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/7caeecda-3ac6-4397-b326-44e6063b6f10">

- Display Driver (Red Hat QXL controller)
 <img width="273" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/7d7a4abc-9472-47bc-80ff-c1123b3b65b9">

 <img width="547" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/2bc6f439-a8e0-4aa1-8039-f94cfd303d00">

 <img width="548" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/98087bc2-28e5-462c-9a03-5189d018bb60">

---

## Screenshots of the windows drivers from `virtio-win-0.1.229.iso` (Have Digital Signer)
<img width="1401" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/ca84b0cf-524f-4e86-a5bc-5e321f7d5a21"> 

<img width="1410" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/7a2d02cf-4540-4de8-b420-f4db28193aa6">

<img width="550" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/6d2fe9cd-8216-4552-97df-f91764ebc468">

<img width="545" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/bdfae35f-b87b-4f75-93a6-21b3fa253aab">

<img width="550" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/10315fdd-4170-49e6-81dc-c5bc948ae9f8">

<img width="546" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/5f4be361-995d-4fe1-bfa0-9016a6d73b3c">

<img width="550" alt="image" src="https://github.com/utmapp/UTM/assets/2676701/e576a4ac-6967-40c5-9ace-8f66f61e4944">

**Comment by kroko** [comment]
FYI, it seems that [0.1.240](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.240-1/) has issues with signing, [0.1.229](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.229-1/) works though

**Comment by osy** [comment]
The guest tools has been updated. If you're on the latest UTM, you can re-download the latest with the CD icon -> Install Windows Guest Tools. Otherwise you can download it directly https://github.com/utmapp/UTM/releases/download/v4.4.4/utm-guest-tools-0.229.iso
