### ISSUE TITLE
ARM64 Linux VM's don't work correctly in 4.4.0 beta

### ISSUE THREAD

**Issue by rxhfcy** [utmapp/UTM#5624]
**Describe the issue**  
ARM64 Linux VM's don't work correctly in 4.4.0 beta (used to work in 4.3.5)

*Steps to reproduce:*

(first make the VM and verify that it's working in UTM 4.3.5)

1. Use UTM Version 4.3.5 (87) (https://github.com/utmapp/UTM/releases/download/v4.3.5/UTM.dmg)
2. Click (+) to make a New VM
3. Choose "Download prebuilt from UTM Gallery..."
4. Click "ArchLinux ARM (ARM64)" on the web page (https://mac.getutm.app/gallery/archlinux-arm)
5. Click "Open in UTM"
6. (start the new "ArchLinux" from UTM.app -> works)

(then download and install UTM 4.4.0 beta)

7. Download and install UTM 4.4.0 (Beta) (https://github.com/utmapp/UTM/releases/download/v4.4.0/UTM.dmg)
8. Open the new "ArchLinux" in UTM.app Version 4.4.0 (88)

What happens: doesn't work correctly in 4.4.0 beta anymore
Expected it to still work

PS. I also tried to launch an openSUSE Tumbleweed ARM64 VM, that one doesn't work either.
Here's a screenshot of an error I got once, I think after manually killing the (not working) VM (doesn't happen every time):
![errormessage](https://github.com/utmapp/UTM/assets/42669366/ff861842-cf82-4a32-8ee4-8c055eaabb01)

**Configuration**  
* UTM Version: v4.4.0 (Beta) / 4.4.0 (88)
* macOS Version: 14.0 Beta (23A5328b)
* Mac Chip (Intel, M1, ...): M1 (MacBook Air M1, 16 GB RAM)

**Comment by osy** [comment]
Can you post the crash log? It should be either in Console or after you click "Report"
