### ISSUE TITLE
Special character in file name prevents transfer over SPICE webdav share ("unexpected error")

### ISSUE THREAD

**Issue by Qhilm** [utmapp/UTM#5630]
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Describe the issue**  
"unexpected error" when copying file with ß character from Windows 11 ARM guest to macOS M1 host. (I did not test any additional characters, but replacing the "ß" with "ss" works around the issue.)

**Configuration**  
* UTM Version: 4.3.5
* macOS Version: 13.5.1
* Mac Chip (Intel, M1, ...): M1
* macOS host is in british english, windows 11 guest is in US english, if that's relevant.

If it is not easily reproducible, I will produce debug logs, let me know.

**Comment by osy** [comment]
Please test v4.6.1

**Comment by Qhilm** [comment]
> Please test v4.6.1

When will it be available for macOS?

**Comment by osy** [comment]
https://github.com/utmapp/UTM/releases

**Comment by Qhilm** [comment]
ha, on mobile the betas are somehow below the v4.5.4, I didn't see them, apologies.

**Comment by osy** [comment]
Should be fixed in v4.6.0, please re-open if you still get an error
