### ISSUE TITLE
"Size" has two completely different meanings in the UI: size of virtual drive (when using Apple Virtualization) vs. actual size on host disk (QEMU)

### ISSUE THREAD

**Issue by rxhfcy** [utmapp/UTM#5637]
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**
(I did find #3362, but I think this is different enough to make a new issue, although I also agree that it would be great to have *both* the size of the virtual drive *and* the actual size on disk in the VM details)

**Describe the issue**  
"Size" has two completely different meanings in the UTM UI (VM details):
- it's either size of the virtual drive (when the VM is using Apple Virtualization)
- ...or actual size on (host) disk (when it's a QEMU VM)

Steps to reproduce:
- Make 2 "native" (arm64) Linux VM's:
- one using Apple Virtualization (default settings otherwise) -> "test 1" 
- the other using QEMU virtualization (default settings otherwise) -> "test 2"
- choose "test 1", look at "Size" in the UI
(shows the size of the virtual drive (64 GB)
- choose "test 2", look at "Size" in the UI
(shows the actual size the drive takes on the host filesystem, much less than 64 GB)

What happens: "Size" has two completely different meanings
What I expected: have the same meaning everywhere

From the point of view of a normal user who doesn't know what happens under the hood, it's very surprising that using Apple Virtualization suddenly changes the meaning of "Size" in the VM details UI

**Configuration**  
* UTM Version: Version 4.3.5 (87)
* macOS Version: 14.0 Beta (23A5337a)
* Mac Chip (Intel, M1, ...): M1

**Comment by osy** [comment]
I mean that’s typically what “size” means.

**Comment by osy** [comment]
Yes you made that post and it’s fixed in https://github.com/utmapp/UTM/commit/d6ddf5a86c688587fea4c96e21116f4523959c23 I don’t know what the issue is?
