### ISSUE TITLE
Typo in tooltip: UTM / Settings... / Input / Invert scrolling ('whell' -> 'wheel')

### ISSUE THREAD

**Issue by rxhfcy** [utmapp/UTM#5646]
**Describe the issue**  
Typo in tooltip: UTM / Settings... / Input / Invert scrolling ('whell' -> 'wheel')

https://github.com/search?q=repo%3Autmapp%2FUTM+whell&type=code

**Configuration**  
* UTM Version: Version 4.4.0 (88)
* macOS Version: 14.0 Beta (23A5337a)
* Mac Chip (Intel, M1, ...): M1

**Comment by osy** [comment]
The point of the option is to invert whatever the system reports. Idk if the system settings for natural vs inverted affects it but its purpose is to force whatever the system reports to be inverted.
