### ISSUE TITLE
Creating a virtual disk image on Apple Silicon Mac fails

### ISSUE THREAD

**Issue by landonh12** [utmapp/UTM#565]
**Describe the bug**
Creating a virtual disk on macOS 11 (M1 MacBook Air) fails with an empty error popup.

**Version**
Version 2.0.10 (10)

**To Reproduce**
1. Attempt to create a new Virtual Machine
2. Attempt to create a new virtual disk image 

**Expected behavior**
A new virtual disk image should be created successfully.

**Screenshots**
Dialog to create a new disk image.
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/2881506/99913890-c6c35d80-2cbf-11eb-9754-b7e435009117.png">

When pressing create, this dialog comes up and UTM does not create a new virtual disk image.
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/2881506/99913971-3afe0100-2cc0-11eb-990a-599e6acbdc68.png">

**Additional context**
This is on an M1 MacBook Air with 16GB RAM, 256GB SSD, and 7 GPU cores. 

In addition, it seems that every error popup is empty.

**Comment by xvimichele** [comment]
Can reproduce this exact issue on an Intel Mac, iMac19,2 w/ i5. macOS 11.0.1.

**Comment by LumingYin** [comment]
Workaround: Import a pre-made hard drive img, and change the Image Type to Disk Image.

[blank-80g.img.zip](https://github.com/utmapp/UTM/files/5580542/blank-80g.img.zip)

**Comment by saagarjha** [comment]
> In addition, it seems that every error popup is empty.

Are there other error alerts that are coming up empty?

**Comment by landonh12** [comment]
> > In addition, it seems that every error popup is empty.
> 
> Are there other error alerts that are coming up empty?

Every error alert that I've seen comes up empty. I tried booting an Ubuntu 20.04 Server (aarch64) image and did not have success. I'll make a separate issue for that.
