### ISSUE TITLE
Sometimes, 4.3.x users are unable to edit macOS 14 beta VM details in the UTM UI (after using UTM 4.4.x beta)

### ISSUE THREAD

**Issue by rxhfcy** [utmapp/UTM#5657]
**Describe the issue**  
In some cases, 4.3.x users are unable to edit macOS 14 beta VM details in the UTM UI

This bug only bites 4.3.x users who installed a 4.4.x beta version, suspended their macOS 14 beta VM with that beta, but right after that downgraded back to 4.3.x.

Until 4.4.x comes out of beta, the latest ***official release*** (currently 4.3.5) is buggy.

(Not sure if related, but while repeating the steps a couple of times (not sure if *exactly* or with slight variation), I completely broke my macOS 14 beta VM, I will open a new issue about that)

Steps to reproduce:
1. Install and use UTM 4.4.1 (beta)
2. Open a macOS 14 beta VM
3. Click the close button (upper left corner of the VM window)
4. Try to click "Edit selected VM"

(can't edit because the VM is Suspended, this is expected)

5. Install and use UTM 4.3.5 (latest non-beta version)
6. Open the still suspended macOS 14 beta VM
7. Click the close button (upper left corner of the VM window)
8. Ignore the warning, "OK" to really kill it
9. Try to stop the VM from the UI (right click -> Stop -> Stop)

(VM still suspended, expected it to become "Stopped")

10. Open the still suspended macOS 14 beta VM
11. Shut it down "nicely" from Apple menu / Shut Down...
12. Try to stop the VM from the UI (right click -> Stop -> Stop)
13. Try to click "Edit selected VM"

What happens: unable to Stop or Edit the VM
Expected: to be able to stop or edit normally

...steps continue from above:

14. Use UTM 4.4.1 (beta) again
15. Open the still suspended macOS 14 beta VM
16. Shut it down "nicely" from Apple menu / Shut Down...
17. Use UTM 4.3.5 again (latest released version)
18. Try to click "Edit selected VM"

What happens: after reinstalling and downgrading, now the VM is stopped and able to edit VM
Expected: not having to reinstall beta and jump through hoops

**Configuration**  
* UTM Version: 4.3.5 (87)
* macOS Version: 14.0 Beta (23A5337a)
* Mac Chip (Intel, M1, ...): M1

**Comment by osy** [comment]
Unfortunately, we don't ever officially support downgrading. I will add a note in the release warning of this issue.
