### ISSUE TITLE
Unable to save macOS 14 VM state if "Use Trackpad" not enabled

### ISSUE THREAD

**Issue by rxhfcy** [utmapp/UTM#5659]
**Describe the issue**  
Unable to save macOS 14 (beta) VM state if "Use Trackpad" is not enabled in VM settings

Steps to reproduce:

1. Select a macOS 14 beta VM
2. Edit VM details / Virtualization / uncheck "Enable Entropy Device" & uncheck "Enable Sound" (everything else checked)
3. Open the VM
4. Click the red close button in the upper left corner of the VM window

(suspending works, as expected)

5. Edit VM details
6. Edit VM details / Virtualization / also uncheck "Use Trackpad"
7. Open the VM
8. Click the red close button in the upper left corner of the VM window

What happens: UTM complains that closing the window will kill the VM 
Expected: save the state and close

![Trackpad disabled](https://github.com/utmapp/UTM/assets/42669366/71e7dad6-3d73-4e34-9570-341a69c573d7)
![Failed to save suspend state](https://github.com/utmapp/UTM/assets/42669366/c33165f5-2047-4880-9eb3-b282dbbc4069)

**Configuration**  
* UTM Version: 4.4.1 (89)
* macOS Version: 14.0 Beta (23A5337a)
* Mac Chip (Intel, M1, ...): M1

**Comment by osy** [comment]
Yes, this is expected and is an unfortunate requirement imposed by Apple.

**Comment by osy** [comment]
So there's a handful of options that Apple doesn't support and they've been changing this throughout the betas so I don't know if this is a bug or something that will be fixed. For example shared directory doesn't work either.
