### ISSUE TITLE
Problems closing / suspending / resuming "ArchLinux" ARM64 Linux VM (from the UTM Gallery)

### ISSUE THREAD

**Issue by rxhfcy** [utmapp/UTM#5660]
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**
(edit: I originally mentioned #5624 here because the steps to reproduce were originally very similar)

**Describe the issue (edited)**
Problems closing / suspending / resuming Arch Linux ARM64 Linux VM (from the UTM Gallery)

*Steps to reproduce: (edited)*

1. Use UTM 4.4.1 (Beta)
2. Press "+", "Download prebuilt from UTM Gallery..." -> click "ArchLinux ARM" -> "Open in UTM" from the web page
3. Open the new "ArchLinux" VM
4. Wait for the login prompt, don't login
5. Close the VM window abruptly from the red close button (upper left corner of the VM window)

(doesn't ask for confirmation, why?)

6. Open the VM again (doesn't work)

What happens: VM doesn't start. Also: closing the VM didn't ask for confirmation earlier, and also note that the VM state is "Suspended"
Expected: ask for confirmation (or suspend and restore successfully)

PS. Once, the VM opened correctly but after I killed it, UTM.app crashed, crash log here: 
[crash_log.txt](https://github.com/utmapp/UTM/files/12523663/crash_log.txt)

**Configuration**  
* UTM Version: 4.4.1 (89)
* macOS Version: 14.0 Beta (23A5337a)
* Mac Chip (Intel, M1, ...): M1 (MacBook Air M1, 16 GB RAM)

**Comment by osy** [comment]
Hmm, I was able to get it to boot after that change. Did you get the same error message?

**Comment by osy** [comment]
I don't think this is related to #5624 then unless I'm missing something?

Any chance you can provide a screen capture?

**Comment by osy** [comment]
"Kind of random" but you mentioned specifically ARM64 Linux. Does this mean you ONLY see it for ARM64 Linux VMs?

**Comment by osy** [comment]
@rxhfcy okay so in you recording, nothing is actually broken. What happened is that ArchLinux booted and is at the login prompt waiting for you to type in a username. When you suspended (by closing) and resumed, the prompt text is not shown but you should be able to type in the user name.

**Comment by osy** [comment]
The second issue which you saw as a crash will be fixed soon.
