### ISSUE TITLE
Where does the Guest Additions ISO come from?

### ISSUE THREAD

**Issue by wjk** [utmapp/UTM#5665]
As far as I can tell, this file is downloaded at runtime, but I do not know from where. Also, is this file truly UTM-specific, or does it work with any build of QEMU if the right runtime flags are supplied? I am asking because one of the maintainers on the OS project I contribute to [has requested](https://github.com/reactos/reactos/pull/5652#issuecomment-1706296463) a download link, so they can be test it officially and possibly add it to their “supported software” list. Thanks!

**Comment by Zero3K** [comment]
https://getutm.app/downloads/utm-guest-tools-latest.iso. The contents have directory names like the ones of components found in QEMU.

**Comment by wjk** [comment]
Thanks!

**Comment by SergeGautherie** [comment]
See also
https://docs.getutm.app/guest-support/guest-support/
https://docs.getutm.app/guest-support/windows/
https://github.com/utmapp/qemu/releases/download/v7.0.0-utm/spice-guest-tools-0.164.4.iso

**Comment by naveenrajm7** [comment]
I guess this is the build script that packages the ISO.
https://github.com/utmapp/spice-nsis
