### ISSUE TITLE
Port forwarding for virtual machines(macOS VM)

### ISSUE THREAD

**Issue by rootkiter** [utmapp/UTM#5667]
I hope to expose a port of the virtual subnet to the host and provide external services.

**Comment by nabiltntn** [comment]
I think this is currently available. You need to use "Emulated VLAN" as network type instead of default "Shared network" , then you can define the port forwards.

Docs here :
https://docs.getutm.app/settings-qemu/devices/network/port-forwarding/

**Comment by ManuW** [comment]
If you are using the Apple Virtualizer, then you can use the [bridged interface](https://docs.getutm.app/settings-apple/devices/network/) network mode. Then the VM is located in the network you selected. No need to forward a port.

If you are using the [Shared Network](https://docs.getutm.app/settings-apple/devices/network/) mode, then look into the manage of pfctl or google for it.

**Comment by naveenrajm7** [comment]
Hi @ManuW 

I have a VM with Apple Virtualizer, I would like to connect to the VM via ssh over  127.0.0.1 (So I don't need to extract IP)
In a QEMU VM, I use an Emulated VLAN to port forward guest port 22 to Host port 2200, and then ssh user@127.0.0.1:2200 

How can I do this with Apple Virtualizer's bridged interface network mode ? You say `VM is located in the network you selected. No need to forward a port`, what does this mean ? How can I access the VM using a bridged mode

**Comment by ManuW** [comment]
> How can I access the VM using a bridged mode

In bridged mode, host and guest sharing the same network interface. With this configuration, you need to know the IP address of your guest system. If your guest has a fixed network address, then you can setup port forwarding on the host system. But that does not bring any advantage.
