### ISSUE TITLE
macOS 14 VM window contents look weird while resizing (blurred and stretched)

### ISSUE THREAD

**Issue by rxhfcy** [utmapp/UTM#5669]
**Describe the issue**  
macOS 14 VM window contents look weird while resizing (blurred and stretched window contents while resizing)

Here's a screen recording that shows the issue (large file, video length 18 seconds):
https://github.com/utmapp/UTM/assets/42669366/b915026a-d357-4be8-9f39-4a43a7ee4e10

Steps to reproduce:
1. Start resizing a macOS 14 VM that supports automatic resizing with the mouse but...
2. ...don't release the mouse button yet, look at the (blurred and stretched) window contents
3. Release the button, window contents update

What happens: blurred and stretched window contents during resizing are not a reliable approximation of what the window will look like after the mouse button is released

Expected: dynamically resize the VM window contents *while* resizing

...or if that's impossible, don't blur (or otherwise change) the VM content while resizing, just resize the window frame
(here's an example video from Windows 7 when the "show window contents while dragging" setting is disabled): https://github.com/utmapp/UTM/assets/42669366/621187f0-2957-407d-a61b-cf02a804acc2

**Configuration**  
* UTM Version: 4.4.1 (89)
* macOS Version: 14.0 Beta (23A5337a)
* Mac Chip (Intel, M1, ...): M1

**Comment by osy** [comment]
This is apple virtualization behaviour and we cannot change it.

**Comment by osy** [comment]
Correct, nothing inside the window is controllable by us.
