### ISSUE TITLE
Ubuntu 20.04 Server (aarch64) VM fails to start on Apple Silicon Mac

### ISSUE THREAD

**Issue by landonh12** [utmapp/UTM#567]
**Describe the bug**
When trying to boot an Ubuntu 20.04 Server (aarch64) image, an error occurs preventing the VM from starting. This error is happening on an M1 MacBook Air.

**Version**
Version 2.0.10 (10)

**To Reproduce**
1. Create a Virtual machine with the settings seen in the "Screenshots" section below.
2. Attempt to boot the VM.
3. Error occurs. If the error alert is closed, the loading wheel perpetually spins.

**Expected behavior**
The VM should boot the Live ISO.

**Screenshots**
Error on VM start:
<img width="912" alt="image" src="https://user-images.githubusercontent.com/2881506/99928980-0f573700-2d11-11eb-8e16-4a7d9baadf46.png">

System settings:
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/2881506/99928813-61e42380-2d10-11eb-80f0-21db4f165f99.png">

Drive settings:
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/2881506/99928955-f6e71c80-2d10-11eb-8b36-c8491e54e3f6.png">

The drive "blank-80g.img" is from https://github.com/utmapp/UTM/issues/565#issuecomment-731860634.

**Additional context**
All other settings are default.

**Comment by osy86** [comment]
Can you open Console and go to crash logs and see if there’s a recent entry for qemu?

**Comment by landonh12** [comment]
> Can you open Console and go to crash logs and see if there’s a recent entry for qemu?

Here's a pastebin of the Console output: https://pastebin.com/J4SN2vm3

No crash logs for QEMU.

**Comment by osy86** [comment]
Seems like you’re looking at the logs section. In the sidebar there should be a section for crash reports.

**Comment by landonh12** [comment]
Yes, I looked, and there were no crash reports there for QEMU or UTM.

**Comment by osy86** [comment]
This is related to #575, from your configuration it seems like you didn't set up the VM properly. But because the log capture wasn't working, you aren't seeing a useful error message. My advice is to either use a [prebuilt vm](https://getutm.app/vms/) or to setup the VM from an iOS device (or use the IPA on your M1 Mac) where you can see the error message and debug accordingly.
