### ISSUE TITLE
UTM UI (VM info): rename "Size" -> "Size on Disk" (because macOS Finder uses "Size" to report something *very* different)

### ISSUE THREAD

**Issue by rxhfcy** [utmapp/UTM#5670]
**Describe the issue**  
UTM UI (VM info): "Size" actually shows "actual size on disk", which is unnecessarily confusing, because macOS Finder (and UNIX ls) uses the same term "Size" to report something ***very*** different (when it's an Apple Virtualization VM).

This will lead to unnecessary confusion that can be avoided by renaming the "Size" label in UTM -> "Size on Disk" (or something like that, to more accurately describe what the number actually means).

edit: "Size" could also mean "the size of the drive". This is another reason to clarify which of the many "Sizes" is meant here (-> "Size on Disk")

Steps to reproduce:
1. Select an Apple Virtualization VM in UTM
2. Look at "Size" in the UTM VM details ("e.g. 3.64 GB")
3. Right click, "Show in Finder"
4. Look at "Size" in Finder ("e.g. 68.72 GB")

What happens: Finder and UTM report very different "Size" ("3.64 GB" vs. "68.72 GB")

Suggestion: Rename the "Size" label in the UI to "Size on disk" (or something like that, to clarify that UTM means "the actual used size on disk" and this differs greatly from what the OS reports as "Size")?

Here's a screen shot that shows that Finder shows the "Size" as 68.72 GB because of the 64 GiB drive (not the actual size on disk)

![Size in Finder](https://github.com/utmapp/UTM/assets/42669366/afa1f206-1b5e-4ecc-8b34-8d2cb9ed5f63)

(this is a follow-up to #5637)

**Configuration**  
* UTM Version: Version 4.4.1 (89)
* macOS Version: 14.0 Beta (23A5337a)
* Mac Chip (Intel, M1, ...): M1

**Comment by osy** [comment]
Thanks for the feedback but we will stick to “Size” as it is concise.
