### ISSUE TITLE
macOS says the App is Damaged

### ISSUE THREAD

**Issue by swaggio7** [utmapp/UTM#5679]
**Describe the issue**  
Simple. I updated from 4.4.0 to 4.4.1. I launched the app, and macOS says it's damaged, and I cannot use it! This has to do with the release, as previous versions were working fine before.

**Configuration**  
* UTM Version: 4.4.1
* macOS Version: macOS 14.0 (23A5337a)
* Mac Chip (Intel, M1, ...): iMac M1

**Comment by osy** [comment]
Can you try redownloading it?
