### ISSUE TITLE
iPad: GL-capable video adapter won't autodetect resolution

### ISSUE THREAD

**Issue by jsonmona** [utmapp/UTM#5695]
**Describe the issue**
Screen resolution is not autodetected and defaults to '1280x800' ever since (including) 4.3.2. This only happens with GL-capable video adapters (`virtio-ramfb-gl` and `virtio-gpu-gl-pci`).

Running `xrandr --output Virtual-1 --auto` won't fix it.

I have tested following versions:
* 4.2.5 (OK)
* 4.3.0 (OK)
* 4.3.1 (OK)
* 4.3.2 (Bad)
* 4.3.4 (Bad)
* 4.3.5 (Bad)
* 4.4.1 (Bad)

Also, Windows VM with "virtio-ramfb" video adapter won't update display. I'm not sure if it's related to this issue. Will create another one after more investigation.

**Configuration (required)**
* UTM Version: from 4.3.2 to 4.4.1
* OS Version: 15.4.1
* Device Model: M1 iPad (12.9 inch, 5th gen)
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? TrollStore

**Debug log**
Will collect one if you need it.

**Upload VM**
Followed instructions on documentation to install ubuntu.
JIT enabled, retina mode doesn't matter. Using video adapter "virtio-gpu-gl-pci".

Edit (2023/10/10): Confirmed that this bug triggers only with GL-capable video adapters.

**Comment by Sijiahui** [comment]
In my ipadpro2021, I test the UTM Version(4.2.5-4.4.2).Only UTM(4.2.5) can use the correct resolution(2388x1668) in both windows 11 and ubantu22.04,also I don't need to change any setting,it can choose the most suitable resolution automatically.

UTM Version: from 4.2.5 to 4.4.2
OS Version: 15.3.1
Device Model: M1 iPad (11 inch, 2021)
Is it jailbroken (name jailbreak used)? No
How did you install UTM? TrollStore

**Comment by jsonmona** [comment]
So it does work with 4.4.2? Hmm. I guess I would try again with a fresh guest OS install. I'll reply soon.

**Comment by jsonmona** [comment]
I did reinstall and it still doesn't work. I can change resolution, but the correct resolution (whatever x 2048) is not in the list.

@Sijiahui Just to be clear, do you use opengl acceleration?

**Comment by jsonmona** [comment]
I tested with latest beta (4.4.2), and confirmed that only GL-capable video adapters are broken. I did not test Windows.

`virtio-ramfb` and `virtio-gpu-pci` -> works as expected (correct resolution)  
`virtio-ramfb-gl` and `virtio-gpu-gl-pci` -> broken (does not autodetect resolution, defaults to 1280x800)

Retina mode doesn't seem to effect this issue.

**Comment by Sijiahui** [comment]
> I did reinstall and it still doesn't work. I can change resolution, but the correct resolution (whatever x 2048) is not in the list.
> 
> @Sijiahui Just to be clear, do you use opengl acceleration?

Yes,I use the opengl acceleration.

I choose the "virtio-gpu-gl-pci(GPU Supported)" in the win11,tiny11,ubantu22.ubantu20.They can all work correctly.

In the resolution ,there is a choice of "2388x1668“

![d0ac845065bdd9de6320a277b5201d3](https://github.com/utmapp/UTM/assets/108074723/a85bb30f-d239-43cc-bde1-097824bf337f)

**Comment by jsonmona** [comment]
Ah, I see. So you are just confirming this issue.

**Comment by klumberge** [comment]
@jsonmona Did you ever get to solve this? I am facing this issue with Ubuntu as well.

**Comment by jsonmona** [comment]
@klumberge No. I just didn't use UTM for few months.

Maybe I should close this issue because apparantly this doesn't get much attention and I'm not using this app anymore.
