### ISSUE TITLE
Old Mac OS PPC versions aren't scaling properly. Add a 'Fit to Screen' without SPICE tools?

### ISSUE THREAD

**Issue by VirtualMachineMan** [utmapp/UTM#5696]
I have a Mac OS X 10.3 guest, and would like to have it in 1920x1080, but, when I put the UTM window in fullscreen, the dock goes off-screen and I can't see time and stuff like that.
I noticed #533, however it requires SPICE tools which I don't know if it's supported on Mac OS X 10.3.
I have VM display size is fixed enabled, however that doesn't help either.
<img width="50%" alt="image" src="https://github.com/utmapp/UTM/assets/121574296/1246fe9f-457b-4bcf-a7ec-bbf2304a6f2d">
(This is a screenshot of the fullscreened UTM window. I didn't crop it at all.)
Here is another image, but with the UTM toolbar showing:
<img width="50%" alt="image" src="https://github.com/utmapp/UTM/assets/121574296/6d57434f-d690-4fa7-bb76-4cf2bb178c7a">
Here is a screenshot of using the 'take screenshot of window' function (note: I don't see this on my screen):
<img width="50%" alt="image" src="https://github.com/utmapp/UTM/assets/121574296/a3a12a5b-9df0-4eca-a2b2-1d832cd6403a">

(Note: Click on the images to enlarge them)

**Comment by osy** [comment]
"Fit to screen" requires spice tools or something similar to communicate to the guest to change resolution.
