### ISSUE TITLE
please allow full editing of QEMU config.

### ISSUE THREAD

**Issue by huntercr42** [utmapp/UTM#5713]
I appreciate the newer versions ( 4.3.5 ) having a "new" button to add a new configure line, but it is extremely inconvenient to not be able to modify the existing configuration lines.  I understand leaving it alone by default, but there should be an "advanced mode" where it unlocks the entire config for editing, and has a "revert to default"  option.

Thank you for considering this!

**Comment by osy** [comment]
It is not possible to support something like this because 1) we use a custom build of QEMU and 2) the GUI depends on certain arguments. This is an XY problem though. You're asking to modify the QEMU config but actually there is probably something you want to do that isn't working on UTM right? Please make an issue with precisely what you want to do and the QEMU command that enables it.

**Comment by huntercr42** [comment]
I understand what you're saying. But I'd at lest like to be able to have it for testing or something... maybe make it hidden unless you hold down Option when selection the page or something like Apple does with the Libraries folder.

My needs do come from wanting to fix something that's not working in UTM, yes... 
For instance, I want to be able to use custom OVMF files. As far as I know, I can't do this in UTM. ( nor could I ever get any disk to boot with it... for example Mojave with OpenCore can run completely fine direct from stock QEMU, but I could never get it working with UTM.

And I want to use virtio with x86 Mac, At minimum virtue-blk-pci,  in this case the same Mojave system which does support it on the guest side. I think that the value of your work on xxl probably outperforms virtio-vga, but that support is in Monterey too.  and works fine in QEMU 8.x.

I realize there are current existing issues with going to 8.x but I just want to point that out and was hoping I could try to find work arounds, but without the ability to fully edit the config to experiment, my ability to contribute is weak.

**Comment by osy** [comment]
> For instance, I want to be able to use custom OVMF files. As far as I know, I can't do this in UTM.

You can by creating a new "drive" and setting the image type to BIOS

> And I want to use virtio with x86 Mac, At minimum virtue-blk-pci

You can do this by setting the interface to VirtIO

> and works fine in QEMU 8.x.

No arguments you change can make it 8.x

**Comment by osy** [comment]
Like I said, it's not that I don't want to do this. It physically cannot be done. UTM dynamically generates settings based on options. I have some vague plans in the future to make a UTM Lite which just acts as a SPICE client but that's not anytime soon.
