### ISSUE TITLE
Crash in nvme_dsm_cb

### ISSUE THREAD

**Issue by yasingunaydiin** [utmapp/UTM#5728]
**Describe the issue**  
I'm using a Windows 11 VM on Mac OS Ventura 13.5.2 only for SVN.
I have no programs installed other than the programs and settings that came when you install Windows fresh.
Sometimes after a while, sometimes right when Windows boots, the following error shows.

QEMU error: QEMU exited from an error: (qemu-aarch64-softmmu:6333): Spice-WARNING **: 17:40:25.880: record:0 (0x15986f1d0): setsockopt failed, Operation not supported on socket

Mostly this happens when I want to update my SVN, I go work on my host Mac, do some stuff and find the VM with this error. Also happened a lot when I wanted to delete a few folders worth a few gb's.

You may see that I have only allocated 2GB's of RAM, it also happens on 4GB's.

**Configuration**  
* UTM Version: 4.3.5
* macOS Version: Ventura 13.5.2
* Mac Chip (Intel, M1, ...): M2

**Crash log**  
[crash log](https://github.com/utmapp/UTM/files/12706729/crash.log)

Attached

**Debug log**  
[debug.log](https://github.com/utmapp/UTM/files/12706727/debug.log)

**Comment by osy** [comment]
> VM - (arg = 0x0) pmap_enter retried due to resource shortage

Is it possible another process on your computer is eating up RAM?

**Comment by osy** [comment]
I think the fix is this https://gitlab.com/qemu-project/qemu/-/commit/818b9b8f5efb728793b9a2c124adab371d2c16e5

It will be included in the next QEMU update.

**Comment by yasingunaydiin** [comment]
> > VM - (arg = 0x0) pmap_enter retried due to resource shortage
> 
> Is it possible another process on your computer is eating up RAM?

Hi,
Not really. It even happens with everything closed.
I decided to use a different program.
Thank you for you reply and help mate.

**Comment by osy** [comment]
Please this on v4.6.0 https://github.com/utmapp/UTM/releases

**Comment by osy** [comment]
Fixed in v4.6
