### ISSUE TITLE
Trying to virtualize MacOS, low performance?

### ISSUE THREAD

**Issue by pedrocarvalhlima** [utmapp/UTM#5736]
Virtualizing MacOS from a mbp M2 with 16gb, tried 6 cpu + 10 gb RAM virtualization, straight from the box from UTM. Performance of streaming apps is very subpar, but youtube and social media videos do not suffer. Anyone have any thoughts on how to improve it? It seems like UTM is really not performant for video decoding, even if it's virtualizing essentially the same OS as the machine it's running on.

**Comment by DrDonk** [comment]
UTM uses Apple’s Virtualisation framework so suspect there is not much they can do if the problem is in Apples API.
