### ISSUE TITLE
Show USB Hubs as devices available to attach.

### ISSUE THREAD

**Issue by GRMrGecko** [utmapp/UTM#5738]
I am having issues getting USB devices attached to this USB hub to attach properly, it ends up resulting in a crash. I think I saw another issue relating to USB devices crashing UTM so I am not reporting that isssue. However, I believe if I could attach the whole USB HUB to the emulator, my issue would go away and I would be able to use that device. I have a USB to ethernet extender that appears as a USB hub, so its not as simple as me attaching the device directly to my computer as it is 114 feet away.  If I could attach that hub, that would be nice as Windows has drivers for hubs and could just work with the hub directly.

**Comment by osy** [comment]
Unfortunately the macOS kernel does not allow us to do this.
