### ISSUE TITLE
Mac99 does not work

### ISSUE THREAD

**Issue by Andrupka** [utmapp/UTM#574]
**Describe the bug**
In PowerPC emulation Mac99 machine does not work

**Version**
2.0.10

**To Reproduce**
1. Create VM
2. Select PPC architecture and mac99 machine
3. See internal error

**Expected behavior**
The machine should boot to Mac OS 9

**Screenshots**
<img width="912" alt="Снимок экрана 2020-11-23 в 17 47 00" src="https://user-images.githubusercontent.com/74910987/99975979-ecca2a00-2db3-11eb-8fe7-c41a8adcc057.png">

**Comment by IIWare** [comment]
Which macOS version are you in right now?
Which Mac computer you used?

**Comment by Andrupka** [comment]
I am at macOS 11.0.1 release. My host is iMac 2019, Core i5, 8GB ram, Radeon Pro 560X 4GB.

**Comment by Andrupka** [comment]
Also, thank you very much for fast reply.

**Comment by IIWare** [comment]
what were the VM specs?

**Comment by Andrupka** [comment]
512mb ram, 1 cpu, Mac99 machine, 1 ide HDD

**Comment by IIWare** [comment]
was soundcard off? mac99 doesn't support sound cards.

**Comment by Andrupka** [comment]
It was on, thank you for reply!

**Comment by IIWare** [comment]
no problem, just turn the soundcard off and start the vm
