### ISSUE TITLE
Unable to boot Fedora live CD on v4.4.1

### ISSUE THREAD

**Issue by osy** [utmapp/UTM#5745]
> What does this mean? You pressed start and nothing happened?

Pretty much that. Here's a screen shot:
<img width="912" alt="Screenshot" src="https://github.com/utmapp/UTM/assets/42669366/0645716f-766c-406a-9d23-3d33b9fbc29b">

> Did it crash and you have a crash log? Did you see an error message?

No crash, no crash log, no error message.

> Okay I understand the part about "didn't start at all" but I need to know _precisely_ what that means. Ideally provide a screen recording if you don't know how to explain it.

OK here's a [screen recording](https://github.com/utmapp/UTM/assets/42669366/0f1cb983-1fef-4db6-baaf-041773abe19e):

> Did you see any error message? Did you see a crash report dialog pop up?

No. 
...but here is a debug log, is it userful? I have 2 Fedora test VMs and I had a little bit of trouble acquiring a debug log for some reason. Let me know if you need something else?
[debug.log](https://github.com/utmapp/UTM/files/12742769/debug.log)

_Originally posted by @rxhfcy in https://github.com/utmapp/UTM/issues/5703#issuecomment-1737996550_

**Comment by 4WvgqJu** [comment]
> Actually, here's another debug log, this should be from unsuccessfully trying to open a VM that had a Fedora installation inside, no live CD image attached. Please let me know if you need any more information, I will get back to you as soon as possible (hopefully tomorrow)
> 
> [debug2.log](https://github.com/utmapp/UTM/files/12742951/debug2.log)

I‘ve observed a lazy initialization for M2 CPU  too with Fedora 36 Live ISO image. It took for first time couple of minutes. What was the requirement for the VM?
