### ISSUE TITLE
Mouse issues on Mac host

### ISSUE THREAD

**Issue by Andrupka** [utmapp/UTM#576]
**Describe the bug**
When I use capture mouse pointer (when it locks pointer inside VM), Y axis is inverted and I can't hold button and move cursor at same time

**Version**
2.0.10

**To Reproduce**
Boot VM and press on cursor button located next to insert image button. Then this will happen. I can't proceed without this option because Mac OS 9 and Windows XP require this. Else cursor just goes to lower right corner. (On newer OS it works fine)
**Expected behavior**
Mouse should work normally

**Comment by brunocastello** [comment]
I had the same issue on Windows 3.11 and 98SE. The mouse cursor goes crazy. (macOS host).
