### ISSUE TITLE
Can't import existing disk in a non-standard location

### ISSUE THREAD

**Issue by fiore42** [utmapp/UTM#5770]
**Describe the issue**  
I can't seem to connect a new VM to an existing disk.
1. I clone a VM -> the VM gets created in the default folder /Users/[me]/Library/Containers/UTM/Data/Documents/
2. From UTM, I right click on VM and select "Move" to move the VM files in the folder I prefer
3. I create a new Linux VM, and before it even starts, in Drives I select "New", "Import", and select the cloned disk from step 1 and 2
4. Whenever I check (tried at least 5 times) the file size of the cloned disk is always zero and if I try to run the VM I get an error showing me the UTM default folder name, not the folder name where I moved the cloned VM

**Configuration**  
* UTM Version: 4.3.5
* macOS Version: 14.0
* Mac Chip (Intel, M1, ...): M2

Thank you

**Comment by osy** [comment]
Show a screenshot of the drive page in the settings.

**Comment by fiore42** [comment]
This is the screenshot of the empty drive created by the wizard:
<img width="811" alt="image" src="https://github.com/utmapp/UTM/assets/7117346/32eddacc-eb31-44a0-964f-f8ad25b05ab5">

This is the screenshot of the cloned drive after I try to attach it using "import":
<img width="812" alt="image" src="https://github.com/utmapp/UTM/assets/7117346/d148cbc8-1355-438e-a903-1be53ebf18cd">

**Comment by osy** [comment]
You're trying to import a .utm. That is not a drive. That's a vm bundle. It's a directory. If you open finder and right click it and select view contents you can see the files.

**Comment by fiore42** [comment]
Thanks - I couldn't find "view contents" in finder but I managed to move the actual disk file out of the folder from terminal and use it that way
