### ISSUE TITLE
How to install applications from AppStore?

### ISSUE THREAD

**Issue by paulocoutinhox** [utmapp/UTM#5780]
Hi,

How to install applications from Apple App Store?

It is giving me error when i try log into my iCloud account.

<img width="1778" alt="image" src="https://github.com/utmapp/UTM/assets/395096/edbd4714-7c84-410e-9128-8e8dd914457d">

I need install Xcode and Command Line tools.

Thanks.

**Comment by osy** [comment]
Duplicate of #3617

**Comment by paulocoutinhox** [comment]
If we run in x86_64 using Rosetta, it works?
