### ISSUE TITLE
I can’t control zoom out and zoom in the display

### ISSUE THREAD

**Issue by TNTxiaoluo** [utmapp/UTM#5789]
When I try to zoom in the display, I can't control the zoom out and zoom in the display

**Configuration (required)**
* UTM Version: 4.4.0 and newest
* OS Version: 15.6 RC1
* Device Model: iPhone 11 Pro Max
* Is it jailbroken (name jailbreak used)?  No
* How did you install UTM? Altstore

**Comment by TNTxiaoluo** [comment]
And the video:
https://github.com/utmapp/UTM/assets/143845807/66e8b68d-d12a-4d7d-93a1-fb90e0cf0d02

**Comment by pythonr0ck** [comment]
Turning on retina mode fixes this problem for me for some reason.

**Comment by TNTxiaoluo** [comment]
This also works for me, thanks!
> Turning on retina mode fixes this problem for me for some reason.
