### ISSUE TITLE
UTM.app 4.3.5 fails to launch on Ventura

### ISSUE THREAD

**Issue by ballo** [utmapp/UTM#5790]
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Describe the issue**  
It will just bounce on the Dock and do nothing

**Configuration**  
* UTM Version: 4.3.5
* macOS Version: Venutra
* Mac Chip (Intel, M1, ...): M1 macbook pro

**Crash log**  
There are no crash reports

**Debug log**  
UTM won't launch so the instructions are nonsense

**Upload VM**  
Can't even get to that point

**Comment by ideologysec** [comment]
Does the issue persist with 4.4.4?

What specific version of Ventura?

Have you tried deleting and redownloading the app?

Has it ever worked?

**Comment by osy** [comment]
Not able to reproduce.
