### ISSUE TITLE
Keyboard input does not work anymore with 4.4.3

### ISSUE THREAD

**Issue by stefcarlens** [utmapp/UTM#5810]
All my macOS12 VM's are working fine with UTM 4.3.5
But when using UTM 4.4.3 there is no keyboard input possible.

Happens on my iMac running macOS13 and MacBook Pro running macOS14

**Comment by Alkenso** [comment]
Same for me.
After upgrade to 4.4.3 keyboard does not work anymore

**Comment by stefcarlens** [comment]
I compiled the latest UTM beta and it doesn't work either. This needs a quick fix imo.

**Comment by osy** [comment]
I see what the issue is, will fix asap.
