### ISSUE TITLE
keyboard not available for old macOS guest on macOS 14 host since UTM 4.4.0

### ISSUE THREAD

**Issue by zhangyoufu** [utmapp/UTM#5814]
**Describe the issue**  
In virtualization mode, the keyboard is not available and cannot proceed in the setup assistant after fresh installation. The setup assistant prompts user to power on bluetooth keyboard. I am not aware of any workaround to skip this step.

This bug was introduced in UTM 4.4.0. It seems that old macOS guest does not support VZMacKeyboardConfiguration. I have no idea which macOS version is the minimal version that supports VZMacKeyboardConfiguration.
https://github.com/utmapp/UTM/blob/180c67e5858705bd2400df8b53ba5004cf76dd57/Configuration/UTMAppleConfigurationVirtualization.swift#L141-L148

**Configuration**  
* UTM Version: v4.4.3
* macOS Version: 14.0 (23A344) host, 12.X guest
* Mac Chip (Intel, M1, ...): M1

**Crash log**  
no crash

**Debug log**  
not needed for this issue

**Upload VM**  
not needed for this issue

**Comment by zhangyoufu** [comment]
duplicate of #5810

**Comment by asikry** [comment]
Thx
