### ISSUE TITLE
Unable to save macOS 14 VM state if 'Pointer' device is in use

### ISSUE THREAD

**Issue by Alkenso** [utmapp/UTM#5815]
Cannot save VM state of macOS 14 guest running under macOS 14 host.
Checked twice, I've left enabled only Keyboard and Pointer devices in Virtualization settings.
(without the Pointer there is no much sense to use the VM)
![image](https://github.com/utmapp/UTM/assets/8972879/02d15f9e-dcf9-4472-acb6-3892463eb765)
![image](https://github.com/utmapp/UTM/assets/8972879/c806d1ff-0ec4-48e5-8be9-eefa116f4d12)

**Configuration**  
* UTM Version: 4.4.3
* macOS Version: 14.0
* Mac Chip (Intel, M1, ...): M1

**Comment by osy** [comment]
You need to enable trackpad. On the next build, this will be renamed to "Mac Trackpad" and will be the default option when creating a macOS 14 guest.
