### ISSUE TITLE
VirtioFS not an option under "Directory Share Mode," docs imply it should be 

### ISSUE THREAD

**Issue by sangaline** [utmapp/UTM#5821]
**Describe the issue**  

The [documentation](https://docs.getutm.app/guest-support/linux/#macos-virtiofs) states

> When using Apple Virtualization backend, [directory sharing](https://docs.getutm.app/settings-apple/sharing/) is enabled through VirtioFS.

and has a whole section about VirtioFS beside those on the WebDAV and VirtFS share modes.

The VirtioFS is not an option in the UI

<img width="820" alt="image" src="https://github.com/utmapp/UTM/assets/8236564/8f4337f9-b3b3-4538-81fa-18ee6bedd9c3">

and [code](https://github.com/utmapp/UTM/blob/5df9e6381634d11b37a975b29ea7142eb1fcce68/Configuration/QEMUConstant.swift#L375) from the project also seems to only refer to WebDAV and VirtFS.

```swift
enum QEMUFileShareMode: String, CaseIterable, QEMUConstant {
    case none = "None"
    case webdav = "WebDAV"
    case virtfs = "VirtFS"
    
    var prettyValue: String {
        switch self {
        case .none: return NSLocalizedString("None", comment: "UTMQemuConstants")
        case .webdav: return NSLocalizedString("SPICE WebDAV", comment: "UTMQemuConstants")
        case .virtfs: return NSLocalizedString("VirtFS", comment: "UTMQemuConstants")
        }
    }
}
```

Is the documentation here incorrect? Is something additional required to enable VirtioFS as a share mode?

**Configuration**  
* UTM Version: 4.4.4 (92)
* macOS Version: 14.0
* Mac Chip (Intel, M1, ...): M2

**Comment by osy** [comment]
You're not using Apple Virtualization backend. You can see it is the QEMU backend.
