### ISSUE TITLE
QEMU error: QEMU exited from an error: Is another process using the image 

### ISSUE THREAD

**Issue by DanMelbourne** [utmapp/UTM#5830]
**Describe the issue**  
After upgrading from 4.4.2 to 4.4.3 I have been unable to reopen my VM due to this error message. Has persisted with upgrade to UTM Version 4.4.4 (92) as well. 

QEMU error: QEMU exited from an error: Is another process using the image [/Users/dan/Library/Containers/com.utmapp.UTM/Data/Documents/Home Assistant OS.utm/Data/haos_generic-aarch64-11.0.qcow2]?

I've rebooted the Mac so it can't be a stray process. Must be something in the VM file itself or in UTM's settings. Is there some kind of lock file for VMs I can delete?

**Configuration**  
* UTM Version: 4.4.4 (92)
* macOS Version: Sonoma 14.0
* Mac Chip (Intel, M1, ...): M1

**Debug log**  
This seems to be the relevant part of the debug log... 

(qemu-aarch64-softmmu:40149): Spice-DEBUG: 09:30:42.776: ../server/char-device.c:797:red_char_device_start: char device 0x1418c83a0
qemu-aarch64-softmmu: -drive if=none,media=disk,id=driveB6F8F7D3-30C7-484A-9858-8D861F34C600,file=/Users/dan/Library/Containers/com.utmapp.UTM/Data/Documents/Home Assistant OS.utm/Data/haos_generic-aarch64-11.0.qcow2,discard=unmap,detect-zeroes=unmap: Failed to get "write" lock
Is another process using the image [/Users/dan/Library/Containers/com.utmapp.UTM/Data/Documents/Home Assistant OS.utm/Data/haos_generic-aarch64-11.0.qcow2]?

Here's the full debug.log: [debug.log](https://github.com/utmapp/UTM/files/13171231/debug.log)

**Upload VM**  

Here's the config.plist [config.plist.zip](https://github.com/utmapp/UTM/files/13171230/config.plist.zip)

**Comment by mitsukiyouko555** [comment]
I'm getting the same issue.. any luck with this so far? @DanMelbourne 

I noticed this issue after the latest sonoma update.. it was working fine before :(

I've tried uninstalling and reinstalling UTM twice, rebooted, tried to open both my windows and my Kali linux VM and both are having this error (including a backup that i downloaded from my dropbox) so I know it is not the vms themselves that have the issue.

I would imagine this is something within the UTM core app...

![2023-12-24_19-09](https://github.com/utmapp/UTM/assets/25854884/43be6060-f08b-449b-81e5-58e03d3d2ec9)

Aside from that, UTM the app, takes like a min or two to open from when i clicked on it - much slower than usual.

At one point, 2 UTM's showed up in my dock even though I only opened one. I suspect there is a second one running in the bg that I can't see and that's making it think that there's another thing opening the file..

I also ran into this error: "UI error: Could not connect: Connection refused".

Interestingly, as I am typing this, the windows vm now works, but I'm still getting both of the above issues with my Kali.

![image](https://github.com/utmapp/UTM/assets/25854884/fdebc4f0-9b78-4b91-bd8b-ee8b9f660fc3)

Debug Log:
[UTM Debug Log.txt](https://github.com/utmapp/UTM/files/13764903/UTM.Debug.Log.txt)
