### ISSUE TITLE
Crash when using opengl renderer backend

### ISSUE THREAD

**Issue by cg10036** [utmapp/UTM#5838]
**Describe the issue**
On renderer ANGLE (OpenGL), The VM crashes about a minute after the low memory notification is displayed (sometimes no notification is displayed). Could it be a memory leak on renderer? I've tested it in an ANGLE (Metal) environment and didn't encounter any issues there.
![IMG_0021-2](https://github.com/utmapp/UTM/assets/30382481/96425f3d-b877-4dbd-a6af-72a4029f3d26)
https://youtu.be/0YZfF-rzsjg

**Configuration (required)**
* UTM Version: 4.3.5
* OS Version: 15.1
* Device Model: ipad 12.9 5th
* Is it jailbroken (name jailbreak used)? dopamine (same issue with non-jailbroken)
* How did you install UTM? : trollstore

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here.
[UTM.wakeups_resource-2023-10-28-211502.txt](https://github.com/utmapp/UTM/files/13195740/UTM.wakeups_resource-2023-10-28-211502.txt)

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the bottom of the configuration options (or at the top of the `QEMU` page) is `Debug Log`. Turn it on and save the VM. After you experience the issue, quit the VM and re-launch UTM. Open the VM settings again and select `Export Log...` and attach it here.
[debug.log](https://github.com/utmapp/UTM/files/13195741/debug.log)

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since GitHub has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.
[config.plist.txt](https://github.com/utmapp/UTM/files/13195764/config.plist.txt)

**Comment by cg10036** [comment]
I ran benchmarks to reproduce the issue as quickly as possible. When I first encountered the issue, it happened when I ran Firefox.
In the new video, I have YouTube running in Firefox, and the same issue occurs with 360p videos.
I set the VM ram to 1g and used UTM version 4.4.4.
https://youtu.be/Ffez2_i8icY
[debug 2.log](https://github.com/utmapp/UTM/files/13197070/debug.2.log)
[UTM.wakeups_resource-2023-10-29-112949.ips.txt](https://github.com/utmapp/UTM/files/13197071/UTM.wakeups_resource-2023-10-29-112949.ips.txt)

**Comment by osy** [comment]
1G may be too much. The GPU memory doesn't count towards the host RAM. So you're using a MINIMUM of 1GB for the VM and then the GPU rendering uses memory on top of that. You're easily going to use like 2-4GB of memory. If you see the low memory notification that means the crash is due to OOM condition.

**Comment by cg10036** [comment]
When I watch youtube in firefox and close it, the ram is not reclaimed, so I thought it might be a memory leak issue. Is the ram for graphics acceleration not reclaimed when not in use?

**Comment by osy** [comment]
"When not in use" is hard to determine because of guest side caching as such. If you want to use GPU acceleration, you need to use less host RAM or use a device that supports higher RAM.

**Comment by cg10036** [comment]
okay, thanks :)
