### ISSUE TITLE
Device not found after upgrade to 4.4.4

### ISSUE THREAD

**Issue by gianpaolocunha** [utmapp/UTM#5845]
I am getting error Device 'drive(ID)' not found after upgrade to 4.4.4.
I have Windows 11 VM that was working fine.
I also disconnected any USB but didn't fix the issue.

**Configuration**  
* UTM Version: 4.4.4
* macOS Version: Sonoma 14.0 (23A344)
* Mac Chip (Intel, M1, ...): M1

<img width="725" alt="Screenshot 2023-10-30 at 4 28 56 PM" src="https://github.com/utmapp/UTM/assets/7915717/ab96c5e2-d770-43b0-99c8-f3ead4cd1ca2">

[debug.log](https://github.com/utmapp/UTM/files/13209604/debug.log)

**Comment by osy** [comment]
What version of UTM were you running before? I think you can work around this issue by cloning the VM, checking it works, then deleting the original. The you can rename the clone.

**Comment by gianpaolocunha** [comment]
It was the previous version from Apple Store (auto update).
I created a clone but same issue pops up

**Comment by osy** [comment]
Can you provide your config.plist inside the .utm?

**Comment by gianpaolocunha** [comment]
[config.plist.txt](https://github.com/utmapp/UTM/files/13210829/config.plist.txt)

Attached

**Comment by osy** [comment]
Why do you have a third drive that has no interface associated with it? Can you remove it?

**Comment by gianpaolocunha** [comment]
:-)   I removed and it resolved the issue! Thanks!!!
One note is that when I click the Delete button to delete the drive I get the message "Are you sure you want to permanently delete this disk image?"
That's the reason I didn't delete it before, worried that it would delete the VM.

**Comment by osy** [comment]
I'll add a check in the next version so it will ignore drives not on any interface.
