### ISSUE TITLE
UTM on intel doesn't display the ability to make Mac OS VM

### ISSUE THREAD

**Issue by stephane-archer** [utmapp/UTM#5872]
<img width="457" alt="Screenshot 2023-11-05 at 10 50 57" src="https://github.com/utmapp/UTM/assets/2981437/f8d1300e-71c9-4dc5-8986-8024bcb41975">

**Comment by osy** [comment]
Yes because it doesn't support it.

**Comment by stephane-archer** [comment]
I'm not an expert but why would it be able to run Linux and Windows and not Mac OS? It's the same thing? booting on an iso and loading the program into memory?
