### ISSUE TITLE
Unable to unmount "My Shared Files" auto mounting at login

### ISSUE THREAD

**Issue by cazendium** [utmapp/UTM#5887]
**Describe the issue**  

The auto mount feature is nice, but I have an ongoing/pending queue at a particular path. "My Shared Files" keeps mounting my shared directories and I see no way to disable this before starting my VM or unmounting it in guest.

**Configuration**  
* UTM Version: 4.4.4
* macOS Version: macOS 14.1
* Mac Chip (Intel, M1, ...):  M2

**Comment by osy** [comment]
Can you not deselect the shared directory?

**Comment by cazendium** [comment]
> Can you not deselect the shared directory?

@osy in the guest macOS, I don't see a way to unmount it from Finder and it doesn't appear in Disk Utility either. Mounting my previous shared directories leads to "mount_virtiofs: fs_tag share not found"

**Comment by osy** [comment]
Can't you just do a symlink?

**Comment by cazendium** [comment]
> Can't you just do a symlink?

@osy I’ve never heard of that until you mentioned it, but that worked! Thanks for the suggestion.

And I just wanted to propose a feature request if we could rename “My Shared Files” to anything we want in settings, I would prefer to keep it simple like “Shared”.
