### ISSUE TITLE
[Help] Missing libraries with i386 and ARM/ARM64

### ISSUE THREAD

**Issue by aar0n10** [utmapp/UTM#59]
When I try to launch an i386 x86 vm, or an ARM or ARM64 machine, I get an error message telling me that I’m missing libraries. I am on iOS 13.1.3 using an iPad Pro 8,1 (2019 11” 64GB model) Using latest version of UTM.
![613CC777-FE16-4DC7-9526-2AFED275DCDE](https://user-images.githubusercontent.com/55704396/75157243-bacf4e80-56e1-11ea-8d82-e313f9551011.png)

**Comment by officemart** [comment]
Whenever I try to make a VM, it will not launch after creation, no matter what OS I use. Ive tried 32 and 64 bit Windows 10 as well as 32 bit Ubuntu 16.04 and nothing. You tap on the VM and it crashes the app instantly. iPad 11" 256gb cellular and iPhone XS Max 256gb. Same exact issue? Are we only limited to Windows XP, 7, and Archlinux? What version of iOS are you on?

**Comment by aar0n10** [comment]
> Whenever I try to make a VM, it will not launch after creation, no matter what OS I use. Ive tried 32 and 64 bit Windows 10 as well as 32 bit Ubuntu 16.04 and nothing. You tap on the VM and it crashes the app instantly. iPad 11" 256gb cellular and iPhone XS Max 256gb. Same exact issue? Are we only limited to Windows XP, 7, and Archlinux? What version of iOS are you on?

That also happens to me. I normally try to change some settings and then restart my device and then get the app to not crash on VM launch, at least.

**Comment by officemart** [comment]
> > Whenever I try to make a VM, it will not launch after creation, no matter what OS I use. Ive tried 32 and 64 bit Windows 10 as well as 32 bit Ubuntu 16.04 and nothing. You tap on the VM and it crashes the app instantly. iPad 11" 256gb cellular and iPhone XS Max 256gb. Same exact issue? Are we only limited to Windows XP, 7, and Archlinux? What version of iOS are you on?
> 
> That also happens to me. I normally try to change some settings and then restart my device and then get the app to not crash on VM launch, at least.

Rebooting doesn't help me at all. Still crashes. This doesn't make any sense. why can some devices work but others don't

**Comment by osy86** [comment]
Did you make the VMs before or after upgrading to v0.2?

**Comment by officemart** [comment]
> Did you make the VMs before or after upgrading to v0.2?

No, I installed the latest IPA today with cydia impactor since Xcode won't side load it, even though I signed the IPA. The app launches and you can make VMs etc, but will immediately crash when you tap play on any of them.

**Comment by osy86** [comment]
I was asking @aar0n10 you have a different issue. Please do not spam other people’s open tickets with unrelated info.

**Comment by officemart** [comment]
> I was asking @aar0n10 you have a different issue. Please do not spam other people’s open tickets with unrelated info.

My bad. Didn’t see him mentioned.

**Comment by aar0n10** [comment]
@osy86 I made them after upgrading to 0.2.

**Comment by osy86** [comment]
Can you delete the app and restart and install again making sure it’s v0.2?

**Comment by aar0n10** [comment]
I will right away when I am able to get to my computer.

**Comment by osy86** [comment]
Any update @aar0n10

**Comment by sukualam** [comment]
just find and rename libqemu-system-i386.dylib to libqemu-system-i386 (x86).dylib in your ipa... and repack..

or use the latest version...

just from my experience..

**Comment by osy86** [comment]
OP hasn’t responded but I’m pretty sure they were on the wrong version.

**Comment by osy86** [comment]
Closing due to lack of response. Likely duplicate of #86
