### ISSUE TITLE
Adding a new IDE drive fails to launch with error Bus 'ide.2' not found

### ISSUE THREAD

**Issue by WesSouza** [utmapp/UTM#5915]
**Describe the issue**  
I added a new IDE Hard Drive and tried starting the VM, and an error is displayed:

> QEMU error: QEMU exited from an error: qemu-i386-softmmu: -device ide-cd,bus=ide.2,drive=drivecdrom0,bootindex=2: Bus 'ide.2' not found

The machine prior had a floppy drive, a hard drive and a CD Rom drive.

**Configuration**  
* UTM Version: 4.4.4 (92)
* macOS Version: 14.2 Beta 23C5047e
* Mac Chip (Intel, M1, ...): M3 Max

**Debug log**  
[debug.log](https://github.com/utmapp/UTM/files/13430243/debug.log)

**Upload VM**  
[config.plist.zip](https://github.com/utmapp/UTM/files/13430247/config.plist.zip)

**Comment by WesSouza** [comment]
Clicking "Update Interface" on each IDE Drive fixed the problem.

**Comment by callumgare** [comment]
@WesSouza Where did you find "Update Interface"? This is the error message I get:
![image](https://github.com/utmapp/UTM/assets/346340/3bb5f368-f530-442d-87e0-6fa4c69e2f31)

And this is the settings for the second drive in UTM:
![image](https://github.com/utmapp/UTM/assets/346340/157a98fe-7d32-4e76-9941-90617ffcacf5)
