### ISSUE TITLE
Ubunto 20.04 Image is actually 22.04 image?

### ISSUE THREAD

**Issue by EdgeSync** [utmapp/UTM#5918]
Hey team,

Wasn't sure exactly where to highlight this, so will try here.

Basically on the list of images on the UTM website - the Ubuntu 20.04 download is actually a 22.04 image. 
https://mac.getutm.app/gallery/ 

<img width="1101" alt="image" src="https://github.com/utmapp/UTM/assets/15020931/d36924db-0749-486b-a5d1-faa77bdf2656">

Can we get the 20.04 image fixed, and get 22.04 added to it's own option in the gallery?

Thanks!

**Comment by cky** [comment]
Given how much freezing happens with Ubuntu 22.04 (as has been reported repeatedly: #5855, #5886), it’s definitely important to have other options, such as a working 20.04 image.

(FWIW, I switched over to Fedora 39 to avoid the freezing. So far it’s been freeze-free; long may it last. 🤞)

**Comment by osy** [comment]
IMO Ubuntu/Linux/Mesa needs to fix their code to not crash instead of making everyone use an older version.

**Comment by cky** [comment]
@osy 100%, though I haven’t seen those issues with KVM on Linux hosts, so I presume there’s some interaction with either Mac hosts, M1 hosts, and/or the UTM fork of QEMU specifically that’s making it show up. The Ubuntu/Linux/Mesa developers most likely do not have M1 Macs to test with, so it could be difficult reproducing the conditions that would allow them to triage things at their end.

If it’s any help at all, I’ve seen the freezes happen with the video sometimes (happens whether or not virgl is enabled), and with the network other times. The common factor seems to me to be virtio. I don’t know the specifics of the UTM fork of QEMU; does it change the way virtio “messages” are sent or received compared to vanilla QEMU?

To be clear, I’m not a kernel developer, a QEMU developer, or a Mesa developer. But in case those developers lack a way to repro the problem, I’m trying to figure out the next steps I can help triage the issue without barking up too many wrong trees.

**Comment by osy** [comment]
Context https://github.com/utmapp/UTM/issues/5749#issuecomment-1749982517

**Comment by cky** [comment]
#5749 does not affect Ubuntu 22.04; this is a different situation.

I just posted some logs in #5886 that can hopefully help figure out what’s going on; from what I can observe, at the time of the freeze, the `cs_gl_draw` and `cs_gl_scanout` messages also stop appearing in the logs. As to whether that’s the cause, the effect, or neither, I don’t know.

**Comment by osy** [comment]
I never said this is the same issue as #5749. I referred to it as context for why you're seeing Linux issues not seen in KVM. Because mesa keeps breaking virgl and kvm does not use it.

**Comment by cky** [comment]
Got it, sorry about the misunderstanding. Yeah, all the more reason why we sort of become the de facto guinea pigs for virgl.

**Comment by osy** [comment]
Long term we want to move to google's gfxstream and then hopefully not be under the mercy of virgl

**Comment by EdgeSync** [comment]
> Given how much freezing happens with Ubuntu 22.04 (as has been reported repeatedly: #5855, #5886), it’s definitely important to have other options, such as a working 20.04 image.
> 
> (FWIW, I switched over to Fedora 39 to avoid the freezing. So far it’s been freeze-free; long may it last. 🤞)

Oh that's interesting - I haven't had any issues with 22.04 myself (Macbook Pro M1) but honestly I haven't used it that much. In this case I need 20.04 to do some testing for that distro. 

Either way it would be nice to have separate 20.04 and 22.04 options in the gallery :)

**Comment by MotorBottle** [comment]
I would suggest downloading the 20.04 arm server image (there's not a 20.04 desktop arm image now) and install it, then manually install ubuntu desktop (you could follow the docs). Had the same issue with you, and imanually installed 20.04. And it's much stabler than 22.04

**Comment by EdgeSync** [comment]
@MotorBottle 

Okay yeah, that is a work around if you want a 20.04 image. The problem is in the gallery they are showing Ubuntu 20.04, but when you download it, you get a 22.04 image. So you waste time and bandwidth downloading an image you want only to get a different one. 

Of course I can build my own image, but the UTM gallery is incorrect and should be fixed.

**Comment by osy** [comment]
The name has been changed to 22.04
