### ISSUE TITLE
add support for macos 10.15.7

### ISSUE THREAD

**Issue by JoshuaClark14** [utmapp/UTM#5923]
Please browse the existing issues and filter by 'enhancement' to make sure this has not already been suggested!
![Screen Shot 2023-11-28 at 10 43 38 am](https://github.com/utmapp/UTM/assets/152097347/2a37db98-391c-41a9-9bb4-60c4e91e4a9c)

i can't upgrade to Macos 11 because i use a 2012 macbook pro.

**Comment by JoshuaClark14** [comment]
do you have a version of UTM that works on Macos 10.15.7

**Comment by osy** [comment]
Duplicate of #2708
