### ISSUE TITLE
Failed to run VM with virtualization via Trollstore2

### ISSUE THREAD

**Issue by liukaixiang817** [utmapp/UTM#5924]
**Describe the issue**
The UTM App crashed after launched an ARM VM with UTM HV via trollstore2

**Configuration (required)**
* UTM Version: 4.4.4
* OS Version: iPadOS16.1.1
* Device Model: iPad Pro 12.9 M1
* Is it jailbroken (name jailbreak used)? No, Just installed the trollstore2
* How did you install UTM? 
* TrollStore Version:2.0.5
Installed UTM-HV via trollstore2.
**Crash log**
Cannot find “UTM” or ”UTM-HV” in settings.

**Debug log**
The debug log is empty.

**Upload VM**
I have used the default settings. Every VMs cannot be launched.

**Comment by xiaoxi654** [comment]
Here the log is.
VM Debug log: [debug.log](https://github.com/utmapp/UTM/files/13484948/debug.log)

**Comment by SoY0ung** [comment]
![72B2F75A-CCFE-417A-97BF-FD0CE1535EB9](https://github.com/utmapp/UTM/assets/32095074/cb973f2f-cbbc-454d-8cfd-3454b555a074)

**Comment by IzaiahSun** [comment]
Is there a plan to support iOS 16 with the hypervisor?

**Comment by osy** [comment]
Yes, it requires some changes to https://github.com/utmapp/Hypervisor

**Comment by PAN740623** [comment]
发自我的 iPhone在 2023年11月28日，18:03，osy ***@***.***> 写道：﻿
Yes, it requires some changes to https://github.com/utmapp/Hypervisor

**Comment by MalxWare47** [comment]
dude can you guys please fix the onscreen buttons bar i cant manage to make the keyboard pop out for shit! ive tried multiple different isos to boot from tryng different settings toggling shit on and off. the little arrow to click on is unclickable and its grayed out meaning its not even trying to accept input touch because its grayed out!!! plz fix im on the latest version too.

**Comment by aspauldingcode** [comment]
Hows the progress on this?

**Comment by osy** [comment]
If you look up you can see that the issue is still "Open"

**Comment by d-dandrew** [comment]
Is that possible to bypass this limitation and call Hypervisor syscalls directly? A jailbreak that get around the HV_UNSUPPORTED error?

**Comment by xiaoxi654** [comment]
> Is that possible to bypass this limitation and call Hypervisor syscalls directly? A jailbreak that get around the HV_UNSUPPORTED error?

Well, Hypervisor will work if https://github.com/utmapp/Hypervisor/pull/3 get merged.
It works on my iPad Air (5th Generation) with iPadOS 16.1.1

**Comment by d-dandrew** [comment]
> > Is that possible to bypass this limitation and call Hypervisor syscalls directly? A jailbreak that get around the HV_UNSUPPORTED error?
> 
> Well, Hypervisor will work if [utmapp/Hypervisor#3](https://github.com/utmapp/Hypervisor/pull/3) get merged. It works on my iPad Air (5th Generation) with iPadOS 16.1.1

Is that mean the kernel space code is still there in the release xnu binary?

**Comment by mzccn** [comment]
> > > Is that possible to bypass this limitation and call Hypervisor syscalls directly? A jailbreak that get around the HV_UNSUPPORTED error?
> > 
> > 
> > Well, Hypervisor will work if [utmapp/Hypervisor#3](https://github.com/utmapp/Hypervisor/pull/3) get merged. It works on my iPad Air (5th Generation) with iPadOS 16.1.1
> 
> Is that mean the kernel space code is still there in the release xnu binary?

The kernel code is still there til 16.3.1 from what I've read. Also the method mentioned in above link worked perfectly

**Comment by crstestacc** [comment]
I just found a way to install TS2 to my iPad Air M1 and came across information that HV is not supported on 16.4.x :( ... Is there any chance to make it work on 16.4.x versions in future?

**Comment by liukaixiang817** [comment]
> I just found a way to install TS2 to my iPad Air M1 and came across information that HV is not supported on 16.4.x :( ... Is there any chance to make it work on 16.4.x versions in future?

No. >iOS 16.3.1 will NEVER be supported

**Comment by PAN740623** [comment]
真的不懂 不要

**Comment by PAN740623** [comment]
你

**Comment by aspauldingcode** [comment]
Is this to be marked as closed?

**Comment by Matzoh** [comment]
> [utmapp/Hypervisor#3](https://github.com/utmapp/Hypervisor/pull/3)
> 
> It works well on my M2 iPad Pro with iPadOS 16.1它在我的配备 iPadOS 16.1 的 M2 iPad Pro 上运行良好

this version still cannot be opened on my iPad Pro 2021 (M1 16.2)

failed to open com.utmapp.UTM

**Comment by liukaixiang817** [comment]
> Is this to be marked as closed? 

yep
