### ISSUE TITLE
UTM SE crashing when using Legacy BIOS with i386

### ISSUE THREAD

**Issue by wtfcxt** [utmapp/UTM#5925]
**Describe the issue**
When creating an i386 (x86) virtual machine using Legacy BIOS mode, the app crashes immediately after trying to launch it.
Trying to use Legacy BIOS with x86_64 works, and trying to run i386 using EFI works as well. 

**Configuration (required)**
* UTM Version: 4.4.4 (SE)
* OS Version: iOS 17.1.1
* Device Model: iPad Pro M2
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? AltStore

**Crash log**
[UTM SE-2023-11-28-121443.txt](https://github.com/utmapp/UTM/files/13487237/UTM.SE-2023-11-28-121443.txt)

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/13487248/debug.log)

**Comment by kirb** [comment]
Can this be fixed / is there any intention to fix this? Or at least show a message explaining what needs to be changed?

I just hit this after importing a Windows 98 VM from Mac. While trying to figure out the exact problem, I created a new VM, turning on the Legacy Hardware switch, and this crashes too. Toggling things one by one I was able to make it boot by disabling UEFI, but obviously not useful for a BIOS-only OS. After finding this issue I was able to get it to boot as BIOS by switching to x86_64, but again, not super obvious a workaround.

**Comment by osy** [comment]
@kirb can you open a new issue with crash log and debug log attached? Whoever opened this one closed it and so it's not being actively tracked.

**Comment by kirb** [comment]
@osy Done - #6479. And thanks so much for dealing with Apple’s antics, this app is a big deal to have on the App Store even in its current state.

**Comment by wtfcxt** [comment]
> @kirb can you open a new issue with crash log and debug log attached? Whoever opened this one closed it and so it's not being actively tracked.

I am actually wondering as to why I closed this issue. I have opened it again - if there is now a conflict with the new issue feel free to close it again.

**Comment by osy** [comment]
Let's track it here.

**Comment by StellaLovesTech** [comment]
crashes whenever i even try to use ANYTHING thats not x86_64, ppc doesn't work for some reason(crashes just like i386)

**Comment by jlj945** [comment]
I just discovered this problem on UTM SE on my iPhone. iOS 17.6.1 latest App Store UTM SE.

I do not remember this happening when I was using the side loaded version. 

I am able to use other Arch’s. aarch64 seems to work just fine.

**Comment by osy** [comment]
Fixed with v4.6

**Comment by kvenden** [comment]
Awesome, thanks for the update and the fix! :)KrisSent from my iPadOn Nov 27, 2024, at 1:24 PM, osy ***@***.***> wrote:﻿
Fixed with v4.6
