### ISSUE TITLE
qemu file cannot be saved and cant add source

### ISSUE THREAD

**Issue by sirbaconyt** [utmapp/UTM#5943]
i tried to install utm-se on sidestore and when installing the ipa file from the latest release on this github i get this error ```The file "qemu-x86_64-softmmu" couldn't be saved in the folder "qemu-x86_64-softmmu.framework".```

and it does not install. also when trying to add the utm alt source to sidestore i get this error

```The data couldn't be read because it isn't in the correct format. E downloadURL:String or downloadURLs: [[Platform:URL]] key required.```

and of course, it does not add the source.

**configuration**
- utm version:none
- os version: iOS 17.2 beta (21C5046c)
- device model: iPhone 11 64 GB (will upgrade soon)
- no jailbreak
- installed/not installed through [Sidestore](https://github.com/SideStore/SideStore)
- space available: 61.69 GB of 64 GB used

**Images attached here**
![image](https://github.com/utmapp/UTM/assets/122573446/ad4641a3-d289-441d-a63e-63faa35bd197)

![image](https://github.com/utmapp/UTM/assets/122573446/887d7d92-2b52-4d13-b44d-a5d860363073)

**Comment by osy** [comment]
This is not an issue with UTM, please contact SideStore devs.
