### ISSUE TITLE
TrollStore2 and iOS17 support

### ISSUE THREAD

**Issue by rllbe** [utmapp/UTM#5944]
**Describe the issue**
Advanced features like virtulization and JIT doesn't work on iOS17 with TrollStore2. It simply pops up a dialog telling that I have to be jailbroken on my iOS version to enable these features. I can confirm the IPA I have downloaded is UTM.HV.ipa for TrollStore.

**Configuration (required)**
* UTM Version: 4.4.4
* OS Version: iPadOS 17.0
* Device Model: iPad Pro 12.9" 5th-gen
* Is it jailbroken (name jailbreak used)? No but with TrollStore2 installed
* How did you install UTM? TrollStore2

**Crash log**
N/A

**Debug log**
N/A

**Upload VM**
(Optional) N/A

**Comment by liukaixiang817** [comment]
Hypervisor on >iOS16.3.1 will NEVER be supported
