### ISSUE TITLE
Apple Business Manager

### ISSUE THREAD

**Issue by ugurkocde** [utmapp/UTM#5945]
Hi everyone,

I have created a MacOS VM (Sonoma 14.2) and want to import it to Apple Business Manager with the Apple Configurator App on my iPhone.

Normally this is possible by scanning a code in the Setup Assistant on the "Select Country and Region" Window.

The problem is that I dont see this code on a virtualized MacOS VM.

This is the Step I am reffering to:

![Assign-this-Mac-ABM](https://github.com/utmapp/UTM/assets/43906965/a6934b1c-3db7-4e4d-83b4-6d80367ab132)

Guide I am following: https://www.hexnode.com/mobile-device-management/help/add-macos-devices-to-abm-using-apple-configurator/

Does anybody have a Idea and could help me?

Best regards
Ugur

**Comment by ugurkocde** [comment]
More details about the host:

    UTM Version: 4.4.4
    macOS Version: Sonoma 14.1.2
    Mac Chip (Intel, M1, ...): M1

**Comment by benthere79** [comment]
Running into this same need/issue, running Sonoma 14.3, Macbook Pro M1, UTM 4.4.5

**Comment by osy** [comment]
I don't think it's possible to do this in a VM and that's limited by Apple's virtualization framework.

**Comment by ugurkocde** [comment]
I thought so. I guess there is nothing we can do if Apple is limiting this feature. Closing this Issue for now.

**Comment by y0d4a** [comment]
Hi, are there any updates on this? I’d like to generate a virtual machine and connect it to Apple Business Manager for lab purposes.
