### ISSUE TITLE
macOS download broken since 4.4.5 release

### ISSUE THREAD

**Issue by core-code** [utmapp/UTM#5957]
because the latest release 4.4.5 does not contain a macOS download, your official download link is now broken:

<img width="546" alt="Screenshot 2023-12-10 at 15 26 00" src="https://github.com/utmapp/UTM/assets/1261954/11320073-2805-4829-986e-c89d344a7dc6">

that button now leads to a 404 "page not found" error

**Comment by osy** [comment]
Fixed

**Comment by M-Rick** [comment]
The 4.4.5 isn't available on the GitHub download page.

**Comment by osy** [comment]
@M-Rick https://github.com/utmapp/UTM/issues/5957#issuecomment-1848992395

**Comment by core-code** [comment]
doesn't seem fixed. both download buttons on the page https://mac.getutm.app lead to 

<Message>The specified key does not exist.</Message>

**Comment by M-Rick** [comment]
It hasn't been fixed apparently.

<img width="791" alt="Capture d’écran 2023-12-10 à 16 14 09" src="https://github.com/utmapp/UTM/assets/2520948/9e2435e0-108d-4133-a046-ec652f5a16f3">

**Comment by core-code** [comment]
thats what i see too even after clearing caches

**Comment by osy** [comment]
Can you clear your browser cache?

**Comment by core-code** [comment]
i did

**Comment by core-code** [comment]
cleaned it again, now it works, thanks!

**Comment by M-Rick** [comment]
Works this time.
