### ISSUE TITLE
Automatically capture cursor and keyboard on window focus

### ISSUE THREAD

**Issue by acheronfail** [utmapp/UTM#5970]
**Description of the Feature**

I'd like to have an option to automatically capture the cursor and keyboard whenever my VM window is activated (gains focus).

Right now, I have to remember each time to tap the modifier combination, and it's quite frustrating when constantly switching between the host and the VM.

**Attempted workarounds**

I've tried to script with this applescript/hammerspoon, but since the key combination is modifiers only, these applications can't seem to trigger it.

**Suggestions**

This could be solved in a few ways:

1. allow changing the key combination to trigger the capture mode, or at least offer another variant which includes a non-modifier key (this would allow other script apps like hammerspoon, etc to be able to hook into it)
2. add an option "**auto-capture on VM window focus**" which will automatically capture the cursor and mouse whenever the window is activated (to 'un-capture' the original key combination could be used)
3. simply add a menu item which "captures cursor and keyboard" (if there's a menu item, then some apps can read those and trigger them - System Preferences can do this, applescript, etc)

**Comment by ylluminate** [comment]
In conjunction with this, it would be nice to have some kind of an open source hook that could be utilized in Linux, FreeBSD and elsewhere to auto-release when moving outside of the VM-guest...
