### ISSUE TITLE
Full screen resolution not working on iOS 16.3

### ISSUE THREAD

**Issue by Carmen-Carmen** [utmapp/UTM#5975]
**Describe the issue**
Full-screen resolution not working on neither ubuntu nor win11, with spice-tool installed.
The screen size is always bigger than my real screen. 
The guest machines are running under hypervisor.
I tried installing ubuntu through jammy-desktop distro, also through installing ubuntu-desktop after the installation of ubuntu server, but faced the same issue. 
![IMG_0047](https://github.com/utmapp/UTM/assets/90448188/4f9069c3-db84-4443-9731-af6ebd91627f)
![IMG_0046](https://github.com/utmapp/UTM/assets/90448188/79db909b-f7a9-4aa2-9b58-fd511dbf3c1b)
Note: I did not enable retina-display

**Configuration (required)**
* UTM Version: 4.4.5
* OS Version: iPadOS 16.3
* Device Model: iPad Pro M1 11 inch
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? TrollStore2

**Upload VM**
[config.txt](https://github.com/utmapp/UTM/files/13671064/config.txt)

**Comment by CypherVault** [comment]
What fixed this issue for me, is after installing the proper spice tools, i had to ensure the display zoom was set to default. If set to MORE CONTENT the zoom will never be correct.

<img width="1194" alt="Screenshot 2023-12-18 at 12 08 01 AM" src="https://github.com/utmapp/UTM/assets/98853849/c4e2e9a1-7e92-41e9-94cc-6fe09748d382">

**Comment by Carmen-Carmen** [comment]
> What fixed this issue for me, is after installing the proper spice tools, i had to ensure the display zoom was set to default. If set to MORE CONTENT the zoom will never be correct.
> 
> <img alt="Screenshot 2023-12-18 at 12 08 01 AM" width="1194" src="https://private-user-images.githubusercontent.com/98853849/291156770-c4e2e9a1-7e92-41e9-94cc-6fe09748d382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NTUyNjcsIm5iZiI6MTcwMjk1NDk2NywicGF0aCI6Ii85ODg1Mzg0OS8yOTExNTY3NzAtYzRlMmU5YTEtN2U5Mi00MWU5LTk0Y2MtNmZlMDk3NDhkMzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDAzMDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZDhlNTZiMjI2MjA1ODM0NDBiMGI4OTM3MzQ3MWY3MDU2MTU2NzNjNDliMDg5YWZkMWE4M2VmNjM1Mzg4ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wYq4tYdwUYthQMQr7Rfljjn_6Px2oybIuawq6-ERC98">

Thank you, changing the display zoom to default also fixed this issue for me.

**Comment by Carmen-Carmen** [comment]
Issue solved.
