### ISSUE TITLE
Crashes On VM Launch

### ISSUE THREAD

**Issue by officemart** [utmapp/UTM#60]
Whenever I try to make a VM, it will not launch after creation, no matter what OS I use. Ive tried 32 and 64 bit Windows 10 as well as 32 bit Ubuntu 16.04 and nothing. You tap on the VM and it crashes the app instantly. iPad 11" 256gb cellular and iPhone XS Max 256gb. Same exact issue? Are we only limited to Windows XP, 7, and Archlinux?

**Comment by jkss88** [comment]
Haha, me too, I am iPad Pro2018, 6g + 1tb, can't run anyway

**Comment by officemart** [comment]
> Haha, me too, I am iPad Pro2018, 6g + 1tb, can't run anyway

This is so strange man! I wonder if its an A12 limitation? Kinda like how Unc0ver is only on A12 and A13 for now

**Comment by jkss88** [comment]
My friend is iPhonepromax and he can actually run win7?  ?  ?

**Comment by officemart** [comment]
> My friend is iPhonepromax and he can actually run win7? ? ?

Do you know what his settings are?

**Comment by jkss88** [comment]
Um, first download a Microsoft system, then import, partition, very simple

**Comment by jkss88** [comment]
Maybe he is a13

**Comment by officemart** [comment]
> Um, first download a Microsoft system, then import, partition, very simple

lol I know how to make a VM, but how much ram is he using, how many cores, how big of a drive, is he using x86_64 or x86 only, is he using IDE or something else etc lol

**Comment by jkss88** [comment]
Where did you know this virtual machine software,
 I learned from a sharing video

**Comment by officemart** [comment]
> Where did you know this virtual machine software,
> I learned from a sharing video

Ive used Virtualization software for 7+ years, but I found this particular one this morning on Reddit

**Comment by jkss88** [comment]
I just want to quickly install the iPad around me, this annoying ipados is too difficult to use！

**Comment by jkss88** [comment]
I think it is my installation error, then jailbreak and then install utm, I installed it with appcake.

**Comment by jkss88** [comment]
Does it have anything to do with software signatures?

**Comment by officemart** [comment]
> Does it have anything to do with software signatures?

If it was a signing issue, it wouldn’t run at all. My iPhone XS Max is jailbroken on 13.3 with Unc0ver and my iPad isn’t. So I’m not sure.

**Comment by jkss88** [comment]
Maybe I need a phone with an A13 chip.

**Comment by osy86** [comment]
Try allocating less memory

**Comment by officemart** [comment]
> Try allocating less memory

Still crashes. even with 1 core and 256mb of ram.

**Comment by officemart** [comment]
Would it matter that it was loaded with Cydia Impactor instead of Xcode?

**Comment by osy86** [comment]
Can you figure out how to get crash logs and post the crash log?

**Comment by officemart** [comment]
> Can you figure out how to get crash logs and post the crash log?

I’ve been looking, but I can’t find the crash logs anywhere. Ideas of where they are stored?

**Comment by osy86** [comment]
https://stackoverflow.com/questions/24400414/how-to-locate-app-crash-logs-in-iphone-ipad#29511374

**Comment by officemart** [comment]
Here you go. this one is from my XS max. 

[UTM-2020-02-24-085828.ips.zip](https://github.com/utmapp/UTM/files/4245650/UTM-2020-02-24-085828.ips.zip)

**Comment by officemart** [comment]
This is my iPad Pro 11
[UTM-2020-02-24-085133.ips.zip](https://github.com/utmapp/UTM/files/4245657/UTM-2020-02-24-085133.ips.zip)

**Comment by Purpleistacky** [comment]
This is my crash log from my IPP 2019 (13.3.1)
[UTM-2020-02-24-185318.zip](https://github.com/utmapp/UTM/files/4245998/UTM-2020-02-24-185318.zip)

**Comment by jkss88** [comment]
Haha, I found out what caused the vm to crash！

**Comment by mulra02** [comment]
@jkss88 is there any quick fix you can share with us? I’m struggling with the same issue.

**Comment by WindowsBetaTest** [comment]
Hey, how did you solve the problem? Can you please share?

**Comment by WindowsBetaTest** [comment]
@jkss88 Hey, how did you solve the problem? Can you please share?

**Comment by jkss88** [comment]
I went through a tutorial by a Chinese friend and he was in # 72

**Comment by mulra02** [comment]
@jkss88 is there any chance you could elaborate? Were there any specific settings or procedures?

**Comment by jkss88** [comment]
You can look at this.
https://b23.tv/av91664985

**Comment by WindowsBetaTest** [comment]
@jkss88 Thank you,I can use windows 10 on my iPad now.

**Comment by WindowsBetaTest** [comment]
It worked!

**Comment by mulra02** [comment]
Thank you. Unfortunately, it does not seem to help those of us that use online signing services.

**Comment by Purpleistacky** [comment]
> You can look at this.
> https://b23.tv/av91664985

So what was the issue? Could please elaborate further? You're not being very helpful, and the Chinese video doesn't tell us much.

**Comment by Nicholassena8190** [comment]
For me, starting a vm without jailbreak crashes the app instantly after pressing on the vm.

I just jailbreak my ipad 7 with unc0ver (now supports A8-A11), and installed the app with AppCake, and opened the app, and then made a vm with a Windows 7 50MB Live CD ISO from archive, and saved it, and then started the vm, and the app didn't crash after starting the vm.

It looks like starting VMs requires jailbreak.

**Comment by Purpleistacky** [comment]
> For me, starting a vm without jailbreak crashes the app instantly after pressing on the vm.
> 
> I just jailbreak my ipad 7 with unc0ver (now supports A8-A11), and installed the app with AppCake, and opened the app, and then made a vm with a Windows 7 50MB Live CD ISO from archive, and saved it, and then started the vm, and the app didn't crash after starting the vm.
> 
> It looks like starting VMs requires jailbreak.

The person who made this app, isn't jailbroken. Many are using it and aren't jailbroken.

**Comment by osy86** [comment]
This issue is off topic. Seems like the original issue was solved in latest release due to dylib issues. New ticket should be opened for any additional problems.
