### ISSUE TITLE
failed to open. Crash on M1 16.2 trollstore2

### ISSUE THREAD

**Issue by Matzoh** [utmapp/UTM#6006]
**Describe the issue**
After installing with Trollstore, the application crashes upon running on iPad M1 16.2, with immediate closure upon opening, and no error logs generated.

**Configuration (required)**
* UTM Version: 4.4.5 and 4.4.4; HV version 
* OS Version: 16.2
* Device Model: iPad Pro 2021, M1 
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? trollstore2.0.8

**Crash log**
No crash log

![IMG_3C7AA464DE9D-1](https://github.com/utmapp/UTM/assets/19823952/011537ba-dadf-48a1-b23b-7355c3a826f3)

**Debug log**
Unable to open utm

![IMG_EF15B8089C21-1](https://github.com/utmapp/UTM/assets/19823952/e4abc539-7b17-463e-aa87-d75809460f17)

**Comment by ydwbio** [comment]
也是m1 16.2 ipad pro 巨魔2.0.8，4.4.5正常打开使用。

**Comment by Matzoh** [comment]
developmemt mode needs to be enabled！
