### ISSUE TITLE
Windows 98 "this program has performed a illegal operation" error

### ISSUE THREAD

**Issue by Gamerboo0fficial** [utmapp/UTM#6023]
[config.txt](https://github.com/utmapp/UTM/files/13930180/config.txt)

I renamed it to .txt because github didnt let me upload it

**Describe the issue**  
I got a iso from Winworldpc.com of windows 98se i got through the install process and made it to the user creation screen and i type my name and it says this this program has performed a illegal operation

**Configuration**  
* UTM Version: Latest
* macOS Version: 12.7
* Mac Chip (Intel, M1, ...): Intel

**Crash log**  
N/A (no crashes)

![Screenshot 2024-01-13 at 8 40 42 pm](https://github.com/utmapp/UTM/assets/115195256/0a8f1b39-e758-4a17-93a4-6dc991b0c9a8)

**Comment by mcayland** [comment]
This is now solved upstream (see https://gitlab.com/qemu-project/qemu/-/issues/1759)

**Comment by Gamerboo0fficial** [comment]
im nt all that tech savvy and it gives me very little detail could you help explain it a bit better

**Comment by mcayland** [comment]
It means that if you want to run pre-NT versions of Windows in UTM then you'll need to wait for the corresponding patch to be applied to UTM, or for a future version of UTM rebased upon the next upstream 9.0 release.

(tagging @osy for reference)

**Comment by Gamerboo0fficial** [comment]
Ok thank you so i cant install wIn98se at all until a new release gotcha

**Comment by janek202** [comment]
As a workaround, you can download UTM 3.1.5, which has an older version of QEMU. It should work fine for older Windows versions.

**Comment by Gamerboo0fficial** [comment]
> As a workaround, you can download UTM 3.1.5, which has an older version of QEMU. It should work fine for pre-NT versions of Windows.

how do i find older versions i cant find them

**Comment by matthewyang204** [comment]
The problem's still around.
<img width="637" alt="Screenshot 2024-07-15 at 8 05 19 PM" src="https://github.com/user-attachments/assets/9b726902-0ab0-4d88-9853-197ffffb6545">

**Comment by Moresteck** [comment]
v4.6.0 works! I booted up my Windows 98 VM that previously got stuck on that error and it stopped occurring with the update. Accessing Display properties is also possible now too.
