### ISSUE TITLE
Boot 32-bit ISO

### ISSUE THREAD

**Issue by DougSteiert** [utmapp/UTM#6028]
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Describe the issue**  
I have been trying to create a VM from the bootable ISO (namely, this one [found here](https://resources.oreilly.com/examples/9781593271442). The ISO is an older 32-bit Ubuntu host. What happens when I try to create a VM with the ISO is that it creates but fails to boot into it.

<img width="793" alt="Screenshot 2024-01-15 at 6 32 10 PM" src="https://github.com/utmapp/UTM/assets/4563308/ab63bd6d-ce54-4297-b571-9156b7d241a9">

Checking boot options yield:

<img width="635" alt="Screenshot 2024-01-15 at 6 32 43 PM" src="https://github.com/utmapp/UTM/assets/4563308/9f9f96ef-2089-4e66-ae82-416939ddcd55">

Where I have tried each option and none boot into the guest.

**Configuration**  
* UTM Version:  4.4.5
* macOS Version: 14.2.1
* Mac Chip (Intel, M1, ...): M1 Pro

**Crash log**  
If the app crashed, you need a crash log. To get your crash log, open Console.app, go to `Crash Reports`, and find the latest entry for either UTM, QEMU, QEMUHelper, or qemu-\*. Right click and choose `Reveal in Finder`. Attach the report here.

**Debug log**  

[debug.log](https://github.com/utmapp/UTM/files/13944083/debug.log)

**Upload VM**  

[config.plist.zip](https://github.com/utmapp/UTM/files/13944075/config.plist.zip)

UPDATE: I tried creating a 32-bit Ubuntu VM with a downloaded ISO and that gave the same error sequence as described above, so likely not solely an issue with that particular bootable ISO.

**Comment by alicela1n** [comment]
You are using UEFI, which is 64bit if you are using a 64bit VM configuration (default), and if you are using 32bit you run into the issue of most distros not supporting 32bit UEFI. You should disable UEFI boot if you aren't using a distro that supports 32bit UEFI or if you're using a 64bit VM configuration.

**Comment by DougSteiert** [comment]
Thanks for that tip. Changing that setting allowed it to get to a different screen where it says the display has not been registered, yet. I will try to look into that issue soon.
