### ISSUE TITLE
Allow control over disk image location

### ISSUE THREAD

**Issue by stroiman** [utmapp/UTM#6034]
First of all, thanks for making this app! Having a virtualized linux on ARM architecture is very helpful for my work.

But I would have liked to be able to customize the location of the disk image files, for at least two reasons:

* Be able to cleanup orphaned files. The Library folder tends to accumulate a lot of waste on a Mac that has been running for years. This is not so much of a problem for most data, but when having disk image files at > 20Gb it does become a problem.
* Easy exclusion from backup software. I really don't want these files to be backed up, neither to my on-site time machine, nor my secondary cloud base backup solution.

I would kinda argue, that virtual disks is for virtualization software a bit like document files for a word processor, the user should have full control over their location.

Also, finding the files is not easy, I couldn't find anywhere in the app, that actually displays the file location. It took a google search to learn where they are located, so I could add the backup exclusions.

**Comment by BlakeOttinger** [comment]
This would also be a very useful improvement for users who might need to run VMs off of an external disk. (Users of 256GB machines who have external disks mounted, etc).

**Comment by osy** [comment]
This is a limitation of the app sandbox. You can manually move the .utm bundles to another location and they should automatically get updated as shortcuts.

**Comment by edhemphill** [comment]
I think the team should reconsider this issue. Not being able to move the VM disk files easily is pretty much a non-starter for any serious user of large VMs. I know most people are just doing development off their laptop and don't care - but if UTM envisions themselves really replacing VMWare and Parallels on Mac entirely, then this issue must be resolved. Frankly, the product comes off more like a toy virtualization tool than a serious replacement for VMWare or Parallels without this.

**Comment by cross** [comment]
I also agree.  I am just starting to use this, and the first thing I was missing in the creation of VM process was a "where do you want to store this?" question.
Even if there is some reason you can't just place it elsewhere, which seems most reasonable, I think the U/I should provide instructions, or automatically perform the operations, to ask you where you want it and if you specify a location other than default it should put it there for you.  If it has to do it as a separate step for some reason, akin to earlier suggestion that the user can move the `.utm` file, then it can just do that for you at the end of the VM creation process.
