### ISSUE TITLE
Improve graphics quality and performance

### ISSUE THREAD

**Issue by timkgh** [utmapp/UTM#6070]
**Describe the issue**  
Improve graphics quality and performance.
I compared the quality and performance of UTM vs VMWare Fusion with both Windows 11 and Ubuntu 23.10 as guests and the graphics quality in UTM could be improved vs Fusion.

It also feels more sluggish and see some tearing on UTM when simply dragging windows around or opening menus.

I used `virtio-ramfb-gl (GPU Supported)` and did not try any other emulations.

**Configuration**  
* UTM Version: 4.4.5
* macOS Version: Sonoma 14.3
* Mac Chip: M2

**Comment by ThatStella7922** [comment]
This not a fault of UTM, it uses QEMU under the hood which does not currently emulate any GPU that Windows haz proper 3D drivers for.

You are going to want to set the Spice QXL GPU as the display adapter and install UTM’s guest tools to get basic 2D support with automatic resolution switching.

**Comment by timkgh** [comment]
@ThatStella7922 thank you. I do have UTM Guest Tools installed in Win 11. Which one is Spice QXL GPU in UTM? I use the default:
<img width="630" alt="image" src="https://github.com/utmapp/UTM/assets/23507658/928a9c51-c720-4f21-8855-92835ac7ccd4">

Automatic resize works and it's usable but compared to VMware Fusion it feels slightly sluggish and lower quality in terms of sharpness (I have Retina Mode enabled in UTM and use 2x scaling in Win 11).

**Comment by ThatStella7922** [comment]
Seems like the gpu you have selected now supports all of the features of the old Spice GPU. My bad for not keeping up to date!

unfortunately there is no real fix to make it feel less sluggish, with the current gpu drivers in Windows you have to do CPU rendering

**Comment by timkgh** [comment]
Thank you for clarifying, this makes sense and at least now I know it's not a configuration issue on my side.
