### ISSUE TITLE
MacOS VM on MacOS, trying to mount shared folder, getting mount_virtiofs: fs_tag share not found

### ISSUE THREAD

**Issue by kokoskiwi** [utmapp/UTM#6078]
Hello, so i am following these instructions
<img width="831" alt="image" src="https://github.com/utmapp/UTM/assets/45340729/5288c4dc-9788-4996-9410-cdcbb9e3cf06">
but it does not work

<img width="514" alt="image" src="https://github.com/utmapp/UTM/assets/45340729/1b5b077c-9d5d-4b21-9fb0-a20dca417a8e">

please help me 😭
```
potatoe@xxx-MacBook-Pro ~ % mount_virtiofs share /Volumes/Share
mount_virtiofs: fs_tag share not found
```

**Configuration**  
* UTM Version: newest
* macOS Version: newest
* Mac Chip (Intel, M1, ...): M1

**Comment by kokoskiwi** [comment]
lol it works now. i fixed it by just using UTM's functionality 

no need to use any terminal commands apparently lol i just wasted 2h hours of my life... Please update the documentation @UTM Team 

<img width="671" alt="image" src="https://github.com/utmapp/UTM/assets/45340729/6843f8ad-2ca8-4825-aad3-cab4063f557c">

**Comment by cmyk** [comment]
> lol it works now. i fixed it by just using UTM's functionality
> 
> no need to use any terminal commands apparently lol i just wasted 2h hours of my life... Please update the documentation [@utm](https://github.com/utm) Team
> 
> <img alt="image" width="671" src="https://private-user-images.githubusercontent.com/45340729/303458485-6843f8ad-2ca8-4825-aad3-cab4063f557c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc1Mzk0OTgsIm5iZiI6MTczNzUzOTE5OCwicGF0aCI6Ii80NTM0MDcyOS8zMDM0NTg0ODUtNjg0M2Y4YWQtMmNhOC00ODI1LWFhZDMtY2FiNDA2M2Y1NTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIyVDA5NDYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhYzA5MWY3MTg0MjZlYzY1ZTA4MDY1MWVkMTg1YzEwM2MwNzBkNjA5ZDJjOWE5MTc0MmRmYjJkNTE2NTM5ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D-NeLKWSQ2-g7_ETONBU_GcigR5aNSvfgmb4u4BlDHw">

Can you elaborate how you fixed it? I am running into the exact same issue.
I followed this guide: https://docs.getutm.app/guest-support/linux/#virtfs

**Comment by drdaz** [comment]
You fixed it, but didn't explain how? I don't see that screenshot in the UI?

**Comment by windmaple** [comment]
Got tripped on this as well. UTM automatically loads the shared folder, as it turns out. No need to run the `mount_virtiofs` command.
