### ISSUE TITLE
Add link to Firefox 52.9 direct download in WinXP  gallery Notes

### ISSUE THREAD

**Issue by merlos** [utmapp/UTM#6088]
Currently in within the gallery in the [Windows XP](https://mac.getutm.app/gallery/windows-xp) item, in the Notes, section there is a reference recommending to install Firefox 52.9. 

> Due to the age of this operating system, Internet Explorer 6 will NOT work at loading most websites even if internet is working. You should download [Firefox 52 ESR](https://www.mozilla.org/en-US/firefox/52.9.0/system-requirements/), the last version to support Windows XP and use UTM’s directory sharing feature to install it.

The link https://www.mozilla.org/en-US/firefox/52.9.0/system-requirements/ displays some release notes, however in that page there is no link to download the installer and the link to download redirects to current version. It takes a few steps to find the actual installer...

The request is to, in addition to the info link, to add a link to the installer download which could be one of these:

1) https://ftp.mozilla.org/pub/firefox/releases/52.9.0esr/win32/en-US/Firefox%20Setup%2052.9.0esr.exe
2) https://ftp.mozilla.org/pub/firefox/releases/52.9.0esr/win32/en-US/
3) https://ftp.mozilla.org/pub/firefox/releases/52.9.0esr/win32/

**Comment by osy** [comment]
Done
