### ISSUE TITLE
Google Vulnerability Report: insecure URI handling scheme

### ISSUE THREAD

**Issue by osy** [utmapp/UTM#6155]
Remove the URI scheme for performing VM operations because they can be triggered from the web browser.

**Comment by conath** [comment]
Kind of unfortunate to see this removed, given there's no AppleScript on iOS. This also breaks some of my Shortcuts which control UTM using the URL scheme. Maybe I can look into adding Shortcuts-API-based automation.

**Comment by osy** [comment]
Maybe we should implement a new API in iOS just for shortcuts. You want to open a new issue for that? The problem with the URL scheme is there's no way to authenticate the actions.

**Comment by conath** [comment]
I opened #6245 about Shortcuts support.
