### ISSUE TITLE
UTM v4.5.0 Beta reports the same identical "Size" for every VM (in the VM details on the right)

### ISSUE THREAD

**Issue by rxhfcy** [utmapp/UTM#6166]
**Describe the issue**  
UTM v4.5.0 Beta reports the same identical "Size" for every VM (in the VM details on the right)

**Steps to reproduce**
1. Launch UTM 4.5.0 Beta
2. Left click to select a VM (from the list on the left)
3. Look at the "Size" on the right
4. Left click to select another VM
5. Look at the "Size" on the right again

What happens: every VM has the same reported "Size" in the VM details

Expected: show the actual correct size
(works fine in earlier versions, e.g. UTM 4.4.5)

**Configuration**  
* UTM Version: Version 4.5.0 (95)
* macOS Version: 14.3.1 (23D60)
* Mac Chip (Intel, M1, ...): M1

**Comment by brunocastello** [comment]
I was going to open the same ticket issue here.

Sonoma 14.3.1, Mac Studio M1 Max

Using the latest 4.5 release
