### ISSUE TITLE
Windows 95 Install and Post-Setup Crashes (SUWIN, RUNDLL32, BSOD, Restart freezes)

### ISSUE THREAD

**Issue by NorseIvan** [utmapp/UTM#6170]
This issue was reported previously but closed and brushed off with a this isn't a UTM problem response. I didn't know if commenting on a closed issue would result in a fix so I posted here. No harm, no foul.

There is a Qemu patch that hasn't been pulled to work with the latest version of UTM 2.5.0 beta. This bug has been present since 4.0.0+ versions.

This allows Windows 95 to run without additional 3rd party fixes, both during setup and within the OS while changing certain drivers and settings. Installing and using Windows 95 is halted and crashes consistently without this fix. This fix also affects Windows 98 Installs and post setup changes as well.

The fix detailed:
https://patchew.org/QEMU/20240117155143.172890-1-pbonzini@redhat.com/

Pull
git fetch https://github.com/patchew-project/qemu tags/patchew/20240117155143.172890-1-pbonzini@redhat.com

Resolves the following 3 issues:
https://gitlab.com/qemu-project/qemu/-/issues/1759
https://gitlab.com/qemu-project/qemu/-/issues/1964
https://gitlab.com/qemu-project/qemu/-/issues/2012

**Comment by coffeedrnkr** [comment]
Seeing the same issue with version 4.x exactly as described in the previously closed issue.

**Comment by NorseIvan** [comment]
> Seeing the same issue with version 4.x exactly as described in the previously closed issue (5760)

I was told if I wanted it fixed I should work on helping to fix the other bugs first. I feel like not being able to install an OS is a major bug. If you can’t install it, you obviously can’t use it. I get it, but it’s been like dozens of releases and this is still there. I supplied links to the fix and it’s incorporated in the latest versions of qemu. Maybe one day but I’ve done all I’m apt to do. Not a programmer

**Comment by osy** [comment]
Please this on v4.6.0 https://github.com/utmapp/UTM/releases

**Comment by osy** [comment]
Fixed in v4.6
