### ISSUE TITLE
Impossible to resize screen with pinch on iPhone

### ISSUE THREAD

**Issue by vedmant** [utmapp/UTM#6179]
**Describe the issue**

Impossible to resize screen with pinch, it just resizes to all white or all black screen immediately.

https://github.com/utmapp/UTM/assets/5052406/4d6b7cbb-13fc-4906-940c-cfd330cedef0

I use base Linux image https://mac.getutm.app/gallery/debian-10-4-i3

**Configuration (required)**
* UTM Version: 4.4.5
* OS Version: 17.3.2
* Device Model: iPhone 13 pro max
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? AltStore

**Comment by osy** [comment]
Can you test with 4.5.0 beta?

**Comment by tOSdude** [comment]
Mine does the same, any attempt to zoom in or out by even the slightest amount makes the display disappear in the distance or zoom into a single pixel.

**Comment by gabrielf11** [comment]
I'm having the same issue trying to use UTM Remote on iOS.

iOS 17.4 (21E219)
UTM Remote v4.5.0
UTM (running server) 4.5.0 (95); macOS 14.4 (23E214)
