### ISSUE TITLE
[MacOS] - Headless with Apple Virtualization

### ISSUE THREAD

**Issue by toddlindner** [utmapp/UTM#6188]
Unable to start a Linux VM headless with Apple Virtualization

* UTM Version:  4.4.4
* macOS Version: Sonoma 14.4
* Mac Chip: M1

As solved in https://github.com/utmapp/UTM/issues/2280 - I have QEMu VMs that start headless by removing the display adaptor.

When trying the same for a VM that uses Apple Virtualization, the VM starts fine but I am never able to access it (by SSH in my case). I don't really know where to look for logs, but i'm guessing it isn't getting past the boot loader.

If I re-add the display adaptor and restart, it connects fine.

**Comment by osy** [comment]
This may just be an Apple limitation/bug. Try setting it up with a serial port and map it to PTTY (not terminal). You won't get any window popup, but you should be able to connect to the PTTY.

**Comment by toddlindner** [comment]
PTTY worked, thanks!

**Comment by samtfischer** [comment]
I'm trying this fix to try to get Screen Sharing to work, but it seems that the same thing is happening. Any ideas on a workaround?
