### ISSUE TITLE
Add support for running QEMU as root for vmnet interfaces.

### ISSUE THREAD

**Issue by DUOLabs333** [utmapp/UTM#6198]
As I look for ways to speed up vulkan-stream, I found that TCP is a bottleneck. vmnet should be faster than virtio-net-pci, but currently requires root. So, I propose that instead of failing to start QEMU if a vmnet interface is constructed (what happens now), QEMU should run as root. Alternatively, QEMU can be set with a setuid bit.

**Comment by osy** [comment]
vmnet doesn't require root if you have the right entitlements (UTM does in the release). We do use vmnet by default.

**Comment by DUOLabs333** [comment]
I couldn't enable it without failing due to not having root.

**Comment by osy** [comment]
Yes, because you don't have the entitlement.

**Comment by DUOLabs333** [comment]
Oh, is the entitlement only for the Apple Store release, and not for GitHub releases?

**Comment by osy** [comment]
It should be for both
<img width="609" alt="image" src="https://github.com/utmapp/UTM/assets/50960678/f702fb89-7fb6-499c-b234-37de4f56f415">

You need a paid apple developer account + manual approval from Apple to use it.

**Comment by DUOLabs333** [comment]
Oh, I meant I don't have the entitlement as a user --- I'm not modifying UTM locally.

**Comment by DUOLabs333** [comment]
Ok, good news: UTM did have enough permissions. Bad news: I uncovered an issue.

The error itself was `QEMU error: QEMU exited from an error: qemu-aarch64-softmmu: -netdev vmnet-bridged,id=net1,ifname=en3: cannot create vmnet interface: general failure (possibly not enough privileges)`. The part to notice is `en3` --- my main internet interface is `en0`. In UTM's GUI, only en3 and en4 is available (if 'Automatic' is selected, `en3` is selected). How does UTM discover internet interfaces?

**Comment by osy** [comment]
https://developer.apple.com/documentation/virtualization/vzbridgednetworkinterface/3656608-networkinterfaces
