### ISSUE TITLE
OSX guest unable to read YubiKey

### ISSUE THREAD

**Issue by useradmn** [utmapp/UTM#6205]
Unable to use YubiKey in guest VM. Guest VM is OS X Sonoma 14.2.1. macOS on macOS.  

**Configuration**  
* UTM Version: 4.4.5
* macOS Version: Sonoma 14.2.1
* Mac Chip (Intel, M1, ...): M2

**Comment by osy** [comment]
There is no USB support for macOS guests currently. Apple needs to implement it.
