### ISSUE TITLE
UTM doesn't work when symlinking the VM folder to another drive

### ISSUE THREAD

**Issue by ltecheroffical** [utmapp/UTM#6215]
**Describe the issue**  
When symlinking the vm directory to another drive and trying to load UTM, I get this error:(from logs):

```
2024-03-23 18:05:37.502 UTM[81700:1276687] [QEMULogging(0x6000021161c0)] 2024-03-23T18:05:37-0400 error com.utmapp.UTM : The file “UTM Virtual Machines” couldn’t be opened.
2024-03-23T18:05:37-0400 error com.utmapp.UTM : [UTM] The file “UTM Virtual Machines” couldn’t be opened.
```

And it doesn't list any virtual machines, when I create a new VM, it says "Permission denied" and doesn't create the VM

**Configuration**  
* UTM Version: 4.4.5
* macOS Version: 14.4
* Mac Chip (Intel, M1, ...): Intel

**Crash log**  
App didn't crash

**Debug log**  
Not an issue for a VM

**Upload VM**  
Not a VM issue and doesn't happen within a VM

**Comment by osy** [comment]
UTM is a sandboxed app and does not support symlinks. You can either use the "move vm" feature to move an entire VM to another drive, or you can create a virtual external drive as removable and mount the image from the home screen.

**Comment by ltecheroffical** [comment]
An idea is the way many other apps do it. When an application spawns a **macOS** open dialog then the user can choose a file or folder, if a user chooses a file/folder in a sandboxed app then macOS will add that file/folder to the list of allowed locations.

**Comment by osy** [comment]
That's literally how it works

**Comment by ltecheroffical** [comment]
My point is because of this there can be a full picker for where to put the VM's

**Comment by ltecheroffical** [comment]
I'm talking about adding a ability to choose where the VMs are created, otherwise a workaround is giving UTM Full Disk Access

**Comment by osy** [comment]
Just move your VMs to wherever you want and it's the same thing.

**Comment by danshaw** [comment]
> Just move your VMs to wherever you want and it's the same thing.

No, not really. If your internal drive doesn't have enough space, you can't create the VM in the first place.
