### ISSUE TITLE
ArcaOS 5.1 installer crashes with a TRAP 000E in OS2LVM

### ISSUE THREAD

**Issue by dennisdietrich** [utmapp/UTM#6243]
**Describe the issue**  
ArcaOS 5.1 installer crashes with a TRAP 000E in OS2LVM
<img width="832" alt="Screenshot 2024-04-01 at 18 11 02" src="https://github.com/utmapp/UTM/assets/44212152/c7093222-0664-4ab2-a529-28d3bcb3fdaa">

**Configuration**  
* UTM Version: 4.4.4 (93)
* macOS Version: 14.4.1
* Mac Chip (Intel, M1, ...): Intel Core i7

**Debug log**  
[debug.log](https://github.com/utmapp/UTM/files/14826213/debug.log)

**Upload VM**  
[config.plist.zip](https://github.com/utmapp/UTM/files/14826248/config.plist.zip)

**Notes**  
Running OS/2 4.52 is currently broken in QEMU. It seems likely that ArcaOS 5.1 is broken for the same reasons. One confirmed issue is the incorrect emulation of the `SGDT` instruction, but there might be more (see QEMU issue 2198 [_Unable to run OS/2 Warp4.52_](https://gitlab.com/qemu-project/qemu/-/issues/2198) for details).

**Comment by QianNangong** [comment]
In fact, it's quite an old issue for QEMU since 2009...
The main reason may be there are some incorrect statements in Intel's manual, but QEMU implements them 'accurately'.
https://www.os2world.com/oldforum/index.php?topic=2035.0
https://www.os2world.com/forum/index.php?topic=1092.0

**Comment by xadammr** [comment]
I've been keeping an eye on this...

There has been a bit of movement on this over the past few months in upstream QEMU: a patch exists in QEMU 9.1 that resolves the OS2LVM TRAP 000E crash (https://gitlab.com/qemu-project/qemu/-/issues/2198 and https://patchew.org/QEMU/20240419195147.434894-1-mark.cave-ayland@ilande.co.uk/).

This then led to another fault in networking stack using TCG emulation backend. A patch was written (https://patchew.org/QEMU/20240606095319.229650-1-mark.cave-ayland@ilande.co.uk/), which allegedly resolves but isn't accepted in to upstream yet.

It seems like it is just a matter of time though until we get OS/2 and modern derivatives working in QEMU (and UTM once they use a later QEMU version).

**Comment by LeZalata** [comment]
any solution to this issue?

**Comment by osy** [comment]
Please this on v4.6.0 https://github.com/utmapp/UTM/releases

**Comment by xadammr** [comment]
![image](https://github.com/user-attachments/assets/f22bc737-7d32-4317-92f6-8586127bf851)
Looking good on 4.6.0!
