### ISSUE TITLE
Slight modification to documentation — EFI Shell when installing Windows 11

### ISSUE THREAD

**Issue by SmilingGit** [utmapp/UTM#6271]
Hello,

This is a tiny suggestion to improve the documentation on this page:

https://docs.getutm.app/guides/windows/#boots-into-efi-shell-instead-of-windows-installer

Another reason for the VM not to boot into Windows might simply be that one hasn’t pressed a key while there is the prompt to press a key to boot from CD / DVD. 

Also, in item 10 of the instructions, you could add the information to press a key during startup to go into the Windows installer:

https://docs.getutm.app/guides/windows/#instructions

That’s it, have a great day!

**Comment by osy** [comment]
Done
