### ISSUE TITLE
Can utm SE go on the App Store now?

### ISSUE THREAD

**Issue by 76534** [utmapp/UTM#6279]
Please browse the existing issues and filter by 'enhancement' to make sure this has not already been suggested!
Since Apple now allows emulators on the App Store, could UTM SE not be allowed since it's basically just an emulator?

**Comment by Samuel525432** [comment]
Now it does

**Comment by Samuel525432** [comment]
https://apps.apple.com/us/app/utm-se-retro-pc-emulator/id1564628856
