### ISSUE TITLE
QEMU issues with 32-bit applications and floating math

### ISSUE THREAD

**Issue by arekkusu42** [utmapp/UTM#6283]
As discussed in #5371 and #4990 QEMU 7.2 introduced a TCG regression which:
* causes some guest OS (macOS El Capitan, at least) to crash during login
* causes some guest applications (any 32-bit GUI app in macOS Mavericks or later) to crash
* potentially crashes ANY macOS application using float math

Until this is resolved, I suggest rolling UTM's QEMU back to 7.1.

I can not find an open QEMU bug tracking this, so possibly they are unaware.
The root cause is probably [this commit](https://gitlab.com/qemu-project/qemu/-/commit/958e1dd1300f37f18b2161dfb4eb806fc8c19b44), but I have not debugged it to confirm.
It also looks like the TCG i386 emulator has seen [many changes after 7.2](https://gitlab.com/qemu-project/qemu/-/commits/master/target/i386/tcg/translate.c?ref_type=heads), so before filing a new bug someone needs to reproduce the problem with a current QEMU release or TOT.

[Minimal reproducers are here](https://github.com/utmapp/UTM/issues/5371#issuecomment-2059544768).

**Comment by osy** [comment]
We plan to update QEMU to the latest version in the next release. Do you know if it's fixed upstream?

**Comment by arekkusu42** [comment]
I do not know; QEMU does not provide Mac binaries, and I do not currently have a build environment to build/test/debug it.

Reviewing the TCG commits I do not see any obvious fix, so I suspect the problem is still there, but as I mentioned, someone needs to reproduce with QEMU TOT.  If a new UTM beta with updated QEMU is released before I set up a build environment, I can test it that way.

(updating QEMU should fix [this annoying assertion](https://gitlab.com/qemu-project/qemu/-/issues/1834) though, so that'd be nice.)

**Comment by arekkusu42** [comment]
If you come from Linux, this may seem normal, but brew is... _very far_ from what I would call "providing Mac binaries".
On a Mac, downloading a .dmg and double-clicking the app does not require:
* installing anything (/opt/local, the Xcode dev tools, etc)
* installing _anything_ (thousands of redundant-but-slightly-different dependancies)
* installing **_anything_** (the app itself can run from the compressed .dmg)
* giving sudo permission to install anything
* opting in to analytics by default


Anyhow... I did set up homebrew (in a Sonoma VM, thank you UTM!) and it installed qemu 8.2.1 (so I can't speak to the 9.0rc or TOT). Then, after copying VMs around and cobbling together invocations, I verified that the three minimal reproducers do **NOT** crash, in Mavericks or Sierra.  I was able to run my ancient (compiled as i386) emulators, inside the qemu-system-x86_64 emulator, inside the UTM arm64-virtualized-on-arm64 Sonoma.  Woot.

So, that means that TCG looks fixed, circa QEMU 8.2.1?  I guess you should go ahead and update in the next release, and we'll see if anything else in the UTM build causes problems.

**Comment by osy** [comment]
Please this on v4.6.0 https://github.com/utmapp/UTM/releases

**Comment by arekkusu42** [comment]
I verified this with UTM v4.6.0 (Beta). QEMU 9.1 update looks good to me:

On M3 Max MBP running Sonoma 14.7 host:
- Sierra 10.12.6 guest (built via [this recipe](https://github.com/utmapp/UTM/discussions/6049#discussioncomment-9091929), and configured with "cpus=12,sockets=3,cores=4,threads=1"): 
 		* [minimal reproducers](https://github.com/utmapp/UTM/issues/5371#issuecomment-2059544768) no longer crash as in v4.5.4
 		* various other i386 apps (HexEdit, Rezilla, Audio Overload, M1, Jammin' Racer, etc) no longer [crash in CG](https://github.com/utmapp/UTM/issues/4990)
 			...although still no audio device or HW OpenGL...
 		* x86_64 apps (Photoshop CS6, Xcode 9.2) continue to function as well as they did in v4.5.4...
 		* annoying [intermittent boot assertion](https://gitlab.com/qemu-project/qemu/-/issues/1834) also fixed
- El Capitan 10.11.6 no longer [crash-loops at loginwindow](https://github.com/utmapp/UTM/issues/5371)
- light touch-testing of PPC 10.2.8/10.5.8, x86_64 Mavericks 10.9.5, arm64 Sonoma 14.7/win11 also looks OK
