### ISSUE TITLE
Crashing when try install UTM SE

### ISSUE THREAD

**Issue by Ilya114** [utmapp/UTM#6297]
**Describe the issue**
When I try sideload UTM SE (latest), AltStore crashing, tried old versions also

**Configuration (required)**
* UTM Version: v4.4.5 SE
* OS Version: 16.7.7
* Device Model: iPhone 8
* Is it jailbroken (name jailbreak used)? 
* How did you install UTM? AltStore

**Comment by osy** [comment]
Please attach crash logs

**Comment by Ilya114** [comment]
AltStore crashing logs? There is a no, I can record video. Normal UTM installing fine, but need JIT

**Comment by osy** [comment]
1. If AltStore is crashing, that's an AltStore issue.
2. If UTM is crashing, there's nothing we can do without crash logs.
