### ISSUE TITLE
Update UTM version on the App Store

### ISSUE THREAD

**Issue by yougotwill** [utmapp/UTM#6318]
Hey, love this app and bought it on the app store to show support but that version hasn't been updated in 6 months (currently is v4.4.4). Any reason why? Can swap over to the github release if you don't plan on updating it but wanted to check first 🙏

<img width="1916" alt="Screenshot 2024-05-01 at 10 13 19" src="https://github.com/utmapp/UTM/assets/14887287/f9e2b361-8258-42bd-8db0-8fb0fb2890dd">

**Comment by osy** [comment]
The reason is that Apple has to approve it

**Comment by yougotwill** [comment]
Okay and I guess they haven't approved any releases from 6 months until now. Damn that sucks. Will move to the github release. Thanks and feel free to close the issue.

**Comment by osy** [comment]
The release was yesterday...

**Comment by yougotwill** [comment]
Yeah no worries. My message might have come across more stronger than I intended. 🙏 I said that since https://github.com/utmapp/UTM/releases/tag/v4.4.5 didn't get approved and not sure how long the approval process would take. Will give it a few days to see.

**Comment by osy** [comment]
v4.4.5 is iOS only and therefore not submitted to the Mac App Store
