### ISSUE TITLE
URL VM start (utm://start?) does not work on 4.5.2

### ISSUE THREAD

**Issue by Mister-A** [utmapp/UTM#6323]
remote control utm://start does not work on 4.5.2

**Configuration**  
* UTM Version: 4.5.2
* macOS Version: 14.4.1
* Mac Chip (Intel, M1, ...): M2 Pro MacMini

Using the URL remote control to run a named VM does not work in this version.

Triggering:
    utm://start?name=VMNameHere

Opens the UTM app but does not start the named VM

Downgrading back to 4.4.4 restores this functionality with no other changes.

**Comment by osy** [comment]
Did you read the release notes? The URI control interface was removed for security reasons and you are recommended to use Apple Script or CLI

**Comment by Mister-A** [comment]
Apologies, thanks for your time pointing me in the right direction.
