### ISSUE TITLE
Virtualization is significantly slower than emulation

### ISSUE THREAD

**Issue by VVgamer135** [utmapp/UTM#6325]
**Describe the issue**  
When I try to virtualize any x86/64 software (windows and os/2), it is very, very slow. Under virtualization, it takes nearly 3 hours to install Windows XP when I download the config from the UTM website plus the recommended ISO. But, when I use emulation, all of these versions of Windows install much quicker. Instead of 3 hours, it took only 50 minutes to install Windows XP. I am still very new to VMs and emulation in general, but could there be some configuration issue that I could be having? I read online that virtualization should be faster than emulation, but I have the opposite problem! I'm using a 2019 Macbook Pro 16"

**Configuration**  
* UTM Version: 4.4.5 (94)
* macOS Version: 11.7.10
* Mac Chip: Intel Core i9 9980HK

**Crash log**  
There was no crash

I tried to upload my debug log but the button constantly was greyed out so I couldn't see it

I tried looking for my config.plist file, but I couldn't find it where they said it was

**Comment by osy** [comment]
I think this is a QEMU issue that's been fixed upstream. Will revisit this once we update QEMU.

**Comment by osy** [comment]
Please this on v4.6.0 https://github.com/utmapp/UTM/releases

**Comment by VVgamer135** [comment]
> Please this on v4.6.0 https://github.com/utmapp/UTM/releases

trying it now, will update soon

**Comment by VVgamer135** [comment]
> Please this on v4.6.0 https://github.com/utmapp/UTM/releases

Alright well this was interesting
So I did two tests with identical settings, with the only change being selecting virtualizing vs. selecting emulation on the first prompt when making a new virtual machine, and I ran Windows XP x86 setup on both two separate times. Both machines took nearly the exact same amount of time, which was yet again taking around 3 hours to install
So overall, the only change with this new update is that Virtualization and Emulation are both slow as molasses to install and use on my Mac, basically the same as version 4.4.5 unfortunately
