### ISSUE TITLE
no network after upgrading macos from 14.4.1 to 14.5

### ISSUE THREAD

**Issue by jgarces-pd** [utmapp/UTM#6355]
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Describe the issue**  
no network after upgrading macos from 14.4.1 to 14.5. Using Shared Network

**Configuration**  
* UTM Version: Version 4.4.5 (94)
* macOS Version: 14.5 (23F79)
* Mac Chip (Intel, M1, ...): M3 Pro

**Crash log**  
If the app crashed, you need a crash log. To get your crash log, open Console.app, go to `Crash Reports`, and find the latest entry for either UTM, QEMU, QEMUHelper, or qemu-\*. Right click and choose `Reveal in Finder`. Attach the report here.
<img width="488" alt="image" src="https://github.com/utmapp/UTM/assets/74255967/165fc581-bd6e-4a76-8b3f-57c4ba9ee34a">

**Debug log**  
For all issues related to running a VM, _including_ crashes, you should attach a debug log. (This is unavailable for macOS-on-macOS VMs. Attach an excerpt of your system log instead.)
To get the Debug log: open UTM, and open the settings for the VM you wish to launch. Near the top of the `QEMU` page is `Debug Log`. Turn it on and save the VM. After you experience the issue, open the VM settings again and select `Export Log...` and attach it here.

**Upload VM**  
If your issue is related to a specific VM, please upload the config.plist from your VM's .utm directory. To get this, right-click the VM in UTM and choose "Show in Finder". Then right-click the selected file in Finder and choose "Show Package Contents". The config.plist file is now visible. Right-click it and choose "Compress". Attach the resulting config.plist.zip file here.
You can upload the entire .utm if needed, but note this includes your VM's drive image and may contain personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

Rocky Linux 9.3 ARM

**Comment by jgarces-pd** [comment]
Issue still present on UTM Version 4.5.2 (97)

**Comment by jgarces-pd** [comment]
laptop issue

**Comment by andreygubarev** [comment]
@jgarces-pd what was it? it seems like I just hit the very same problem with QEMU
