### ISSUE TITLE
UTM run in App Translocation downloaded from App Store

### ISSUE THREAD

**Issue by simbados** [utmapp/UTM#6378]
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Describe the issue**  
Version 4.5.2 of UTM from the App Store will run in App Translocation. Why is that so?
To see that it is run in App Translocation you can run 'ps xw | grep UTM'

**Configuration**  
* UTM Version: 4.5.2
* macOS Version: 14.5
* Mac Chip (Intel, M1, ...): M3

**Comment by simbados** [comment]
Tried reinstalling it, but still in App Translocation.
Issue started with upgrade from 4.4.5 -> 4.5.2

**Comment by adespoton** [comment]
Have you tried dragging UTM.app to the desktop and back to the Applications folder?

Seems odd that Translocation would be enabled for an App Store app though.  Somehow the OS thinks it's a new app with questionable notarization instead of a properly signed and notarized app update.

**Comment by simbados** [comment]
Yes I tried that and the app is no longer opened in Translocation. However if I uninstall and reinstall it, then it will start again in Translocation (tried this multiple times). Maybe I broke some config files, because I copied some VMs outside their location. But normally Translocation should not happen on apps downloaded from the App Store and I never installed UTM outside of the App Store.

**Comment by simbados** [comment]
If anyone is interested why this happens, here is a good article explaining it: https://eclecticlight.co/2024/05/27/app-store-apps-can-be-translocated/

This is probably an unintended side effect from apples own translocation rules

**Comment by rsaldinger** [comment]
In particular, see the comment thread there.

Short version: it seems like the package submitted to the App Store for v4.5.2 _might_ have had a com.apple.quarantine EA on the app bundle. Why the backend App Store processing did not strip that (if it was really there) is an open question. But the default for productbuild(1) is to preserve any EAs that are present in the package payload, so if Apple **didn't** strip it, it probably would get installed. Which is what appeared to be happening with that version (maybe?) but not with v4.5.3.

**Comment by osy** [comment]
This is fixed in v4.5.3
