### ISSUE TITLE
Discrepancy between UTM and Qemu video devices

### ISSUE THREAD

**Issue by Behinder** [utmapp/UTM#6409]
**Describe the issue**  
Trying to install ubuntu arm64 and have to choose option `virtio-ramfb-gl` to make it work( for now). However trying to launch qemu with options:
````
qemu-system-aarch64 \
  -machine virt,accel=hvf,highmem=on \
  -cpu host \
  -smp 4 \
  -m 4096 \
  -device virtio-gpu-pci \
  -device virtio-keyboard \
  -device virtio-mouse \
  -drive file="/Volumes/T7/SteamOS/mysteamdisk.qcow2",if=virtio \
  -cdrom /Volumes/T7/ubuntu.iso \
  -L qemu-bundle/usr/local/share/qemu  
````
is giving me "display not ready yet" error. changing virtio-vga or virtio ramfb-gl results it "unknown device" error. 
my qemu is compiled from source with all options enabled. Why UTM which is based on qemu uses additional drivers that are not available for qemu???

**Configuration**  
* UTM Version: latest from github
* macOS Version:  latest ventura
* Mac Chip (Intel, M1, ...):  M2 Pro

**Comment by osy** [comment]
The problem is you aren't passing in the UEFI BIOS so there is nothing to boot from. Also, this is an QEMU issue and not UTM.

**Comment by Behinder** [comment]
But UTM contains older version of Qemu instead of the latest one, so yes
this is also UTM issue.

wt., 20 sie 2024 o 02:11 osy ***@***.***> napisał(a):
