### ISSUE TITLE
Clicking the help icon in iOS App leads to 404 page

### ISSUE THREAD

**Issue by LostInCompilation** [utmapp/UTM#6422]
**Describe the issue**
Clicking on the help question mark opens the URL https://docs.getutm.app/remote/ which leads to a 404 page.
![image](https://github.com/utmapp/UTM/assets/12819635/9fbedeba-6ba3-44b5-90de-8dfa3c7b572e)

**Configuration (required)**
* UTM Version: 4.5.3
* OS Version: iOS 17.5.1
* Device Model: iPhone 15 Pro Max
* Is it jailbroken: No
* How did you install UTM? App Store

**Comment by osy** [comment]
Yeah I need to get to that...
