### ISSUE TITLE
Autostart?

### ISSUE THREAD

**Issue by wjk** [utmapp/UTM#6429]
**Describe the issue**  
I see the UI for the new server-autostart feature when I run UTM. However, when I click the checkbox to enable autostart, nothing seems to happen. I looked in the code, and as far as I can tell this value is stored in the user defaults but not used anywhere. Am I missing something?

**Configuration**  
* UTM Version: 4.5.3 (99)
* macOS Version: 14.5
* Mac Chip (Intel, M1, ...): M1

**Comment by wannafedor4** [comment]
I'd like to add to this a bit:
<br>
I think UTM Server should function as if it were a separate program, other than just UTM's main app. The server seems to stop working as soon as you quit the app, or put your Macintosh into sleep mode. This isn't much of a problem on Macbooks, but on the Mac mini, Mac Pro, and Mac Studio this is a huge issue.
