### ISSUE TITLE
Cannot enable JIT for UTM on iPhone 15 iOS 17.5.1

### ISSUE THREAD

**Issue by yohu123** [utmapp/UTM#6430]
I’m using the following Reddit guide to enable JIT, which I successfully did for DolphiniOS, but for reasons unknown I cannot enable it for UTM:

https://www.reddit.com/r/EmulationOniOS/comments/1d0t7qe/how_to_enable_jit_on_ios_171751/

Although it says ‘Done’ in the end, the ‘Virtualize’ option of the UTM app remains greyed out. I have tried to enable JIT for UTM using the SideStore version and then I tried the AltStore version with the same results. I just now used the debugging ‘True’ mode while enabling it and got the below full log: ————————————

C:\Users\yohan\Desktop\IOS17-~1>python jit_enabler_better.py com.utmapp.UTM.86Z2JC2A3J True Getting bundle ID... DEBUG mode specified. Got bundle ID: com.utmapp.UTM.86Z2JC2A3J starting tunnel to device... This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC. Sucessfully created tunnel: fdc7:29ee:b2df::1 50981 Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)... 2024-06-09 09:57:57 YRI-WinPC pymobiledevice3.cli.mounter[2212] ERROR DeveloperDiskImage already mounted

Diskimage already mounted. Starting app... (b'Process launched with pid 2964\r\n', b'') Started app. PID: 2964 Starting debug server... (b"\r\nFollow the following connections steps from LLDB:\r\n\r\n(lldb) platform select remote-ios\r\n(lldb) target create /path/to/local/application.app\r\n(lldb) script lldb.target.module[0].SetPlatformFileSpec(lldb.SBFileSpec('/private/var/containers/Bundle/Application/<APP-UUID>/application.app'))\r\n(lldb) process connect connect://[fdc7:29ee:b2df::1]:52181 <-- ACTUAL CONNECTION DETAILS!\r\n(lldb) process launch\r\n\r\n", b'') Started debug server with connection details: [fdc7:29ee:b2df::1]:52181 Run debugging commands... This might take a few minutes. (lldb) command source -s 0 cmdfile.txt Executing commands in 'C:\Users\yohan\Desktop\IOS17-~1\cmdfile.txt'. (lldb) gdb-remote [fdc7:29ee:b2df::1]:52181 (lldb) settings set target.memory-module-load-level minimal (lldb) attach -p 2964 Process 0 exited with status = 9 (0x00000009) killed (lldb) error: attach failed: The parameter is incorrect.

done. DEBUG mode specified. This script won't quit automatically. Press CTRL + C to stop it.

————————————

I have read the ‘cmdfile.txt’ and it has the exact same contents as mentioned in the above debug log. I’m doing this on a Windows 10 PC. Please help as I’ve exhausted all possible options. Thanks, in advance.

**Configuration (required)**
* UTM Version: 4.5.3
* OS Version: iOS 17.5.1
* Device Model: iPhone 15 (128 GB)
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? AltStore

**Comment by osy** [comment]
Virtualization is only supported on jailbroken or trollstore installs.

**Comment by yohu123** [comment]
Since there is no jailbreak for iOS 17.5.1 and TrollStore does not support iOS 17.0.1 (or later), please advise how do I install the JIT-enabling supported version of UTM on an iPhone 15 running iOS 17.5.1 ?

Thanks, in advance.


Thanks & Regards,

Yohan Irani

________________________________
