### ISSUE TITLE
Apple Rosetta emulation for QEMU backend

### ISSUE THREAD

**Issue by freebrowser1** [utmapp/UTM#6465]
**Describe the issue**  
Not an issue, but a question.
After trying to convert an existing VM (Ubuntu x86-64 emulated on M1) I could not find the option 'Rosetta emulation' in the settings of the VM.

**Configuration**  
* UTM Version: 4.4.5
* macOS Version: 14.5
* Mac Chip: M1

**Upload VM**  
[config.plist.zip](https://github.com/user-attachments/files/16120391/config.plist.zip)

**Comment by UrkiMimi** [comment]
Rosetta x86_64 emulation only works for ARM64 Virtual Machines using Apple Virtualization. You can't use Rosetta with x86_64 VMs.

**Comment by Behinder** [comment]
Yes you can, if you use Qemu you may launch qemu-aarch-x86_64 in rosetta mode first changing environment in terminal `env /usr/bin/arch -x86_64 /opt/local/bin/zsh --login` so same behaviour should be available on UTM.

**Comment by freebrowser1** [comment]
> Rosetta x86_64 emulation only works for ARM64 Virtual Machines using Apple Virtualization. You can't use Rosetta with x86_64 VMs.

No, that is not how it works.
Rosetta is meant to run x86-64 apps on ARM architecture and Apple now supports even Linux VMs on an ARM powered Mac. This documentation : https://docs.getutm.app/advanced/rosetta/ tells about this, but what I don't know and want to know is how to convert an existing VM to Rosetta.

**Comment by osy** [comment]
In macOS 15, hypervisor.framework should support this but we'll have to add it to QEMU

**Comment by freebrowser1** [comment]
> In macOS 15, hypervisor.framework should support this but we'll have to add it to QEMU

What does that mean ? That UTM should be updated to a new, yet to release, version when I update my Mac to Sequoia ?

**Comment by osy** [comment]
Yeah it'll need to be added to QEMU first and then UTM. So probably in the next release.

**Comment by osy** [comment]
Completed in 164e3126d28f0d04d482bf808ef999346918fe8a

**Comment by osy** [comment]
First of all TSO is currently broken pending fix for #6836 (next update). Second, Rosetta is proprietary licensed technology from Apple and you're not allowed to run it from QEMU so we provide no support for doing this. Third party emulators like FEX can also take advantage of TSO mode.
