### ISSUE TITLE
Too large screen resolution, can't change back

### ISSUE THREAD

**Issue by lgrachov** [utmapp/UTM#6466]
**Describe the issue**  
When setting the MacOS 9.2.1 resolution to a high one, it is not possible to scale down the window. If a high resolution is set, the only way to reset is reinstalling the virtual machine. The resolution cannot be set back because the options are on the bottom of the screen, the screen resolution on the host is too small, but the guest resolution is large, so the options are out of the screen bounds. The window cannot be drag either because the dock, bottom and top of the screen are sticky, it cannot be moved out.

**Solution**
Make the window scaling not limited to a specific size (Keep the scaling by just changing the size, not changing the aspect ratio, but remove the limits)

**How to reproduce**
Startup a macOS 9.2.1 virtual machine, and set the resolution to 1920x1080 on a small screen.

**Configuration**  
* UTM Version: 4.2.5
* macOS Version: 14.0
* Mac Chip: M3

**Debug log**  
I did not have "Debug Logging" on.

**Upload VM**  
[config.plist.zip](https://github.com/user-attachments/files/16132070/config.plist.zip)

**Comment by osy** [comment]
Can you try on latest UTM version? I believe it should properly scale down now.

**Comment by lgrachov** [comment]
> Can you try on latest UTM version? I believe it should properly scale down now.

Thanks! It works.
