### ISSUE TITLE
ios install tutorial for Development needs some updates

### ISSUE THREAD

**Issue by 100tomer** [utmapp/UTM#6469]
**Describe the issue**
Hi, I have a few problems / suggestions with the iOS readme.md tutorial. 
1. The build command have a wrong flag. There isn't a "-p" flag in the "./scripts/build_utm.sh" script
2. I think in general the instructions are not clear enough, like where should we put the downloaded artifacts? should we extract it? is the Command Line method is instead of the xCode method or we need both? 
3. I had some problems like xcode think there should be a qemu file, and also wants to upgrade some settings automatically, should we let it do it?

I will be happy to rewrite the readme for future iOS developers, when we resolve this.

**Configuration (required)**
* UTM Version: 4.5.3
* OS Version: 17.5.1
* Device Model: iPhone 15 Pro
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? I didn't managed to install it

**Comment by 100tomer** [comment]
@osy I see you closed this issue but the readme changes did not improve the xCode installation part which is not working, I would still love some help with this

**Comment by 100tomer** [comment]
Also I think in the readme the part of "Replace ios with ios-tci to build UTM SE." meant to be 
"Replace iphoneos with <something?> to build UTM SE"

**Comment by osy** [comment]
> @osy I see you closed this issue but the readme changes did not improve the xCode installation part which is not working, I would still love some help with this

I mentioned you need to install Xcode. What else do you need

**Comment by 100tomer** [comment]
> > @osy I see you closed this issue but the readme changes did not improve the xCode installation part which is not working, I would still love some help with this
> 
> 
> 
> I mentioned you need to install Xcode. What else do you need 

I tried to run the UTM using the Xcode option for iOS. It seems not working even tho I followed everything laid out in the iOS development doc. (That was my original question in this issue) 

The new changes to the doc only changed the part about building it without Xcode. 
Can you maybe help with running it in Xcode? 

(Also by the way the latest assets from the latest build are expired (I already got them but I'm telling you for other people)

**Comment by osy** [comment]
There is no way to build without Xcode that's why I'm confused. The document assumes you have the latest Xcode installed.

**Comment by 100tomer** [comment]
> There is no way to build without Xcode that's why I'm confused. The document assumes you have the latest Xcode installed.

Sorry my English may not be accurate. I do have the Xcode installed but from my understanding you can install the UTP app using Xcode (little clicking play inside Xcode) or building it not in Xcode (using Xcode tools or something)

Assuming I'm correct so far then the option of installing it using Xcode (clicking play inside Xcode ) is not working. Lots of files are missing even after downloading the artifacts and even more weird errors.

**Comment by osy** [comment]
I see. If you extracted the sysroot .zip to the root directory of the repository, and you follow the section "Xcode Development" in the documentation, it should work.

**Comment by 100tomer** [comment]
> I see. If you extracted the sysroot .zip to the root directory of the repository, and you follow the section "Xcode Development" in the documentation, it should work.


So I did just that and it's not working. For example Qemu file still missing but there are more errors. 
For you it's working just putting the artifacts inside the folder and run it?

**Comment by osy** [comment]
Can you paste one of the not found errors?

**Comment by 100tomer** [comment]
> Can you paste one of the not found errors?

<img width="1194" alt="Screenshot 2024-08-23 at 4 48 48 PM" src="https://github.com/user-attachments/assets/309869bc-f752-4575-841f-d788e49a6258">

<img width="262" alt="Screenshot 2024-08-23 at 4 50 22 PM" src="https://github.com/user-attachments/assets/324a6779-542f-4eba-bbe6-5d270ff3fee0">


Also it seems like tons of files are missing even tho I copied all the artifacts to the folder (When I tried to remove these references and import all the artifacts manually it still had some files missing)

<img width="237" alt="Screenshot 2024-08-23 at 4 54 06 PM" src="https://github.com/user-attachments/assets/0333a3cd-3d75-4957-8e86-790a1d7b7d14">

**Comment by osy** [comment]
That's not what I mean. Attempt to build with Cmd+B and you should get a compile log with the errors.

**Comment by 100tomer** [comment]
> That's not what I mean. Attempt to build with Cmd+B and you should get a compile log with the errors.

<img width="1202" alt="Screenshot 2024-08-23 at 5 04 27 PM" src="https://github.com/user-attachments/assets/44d5192b-5c55-4382-bcd3-90f404279b2c">

**Comment by osy** [comment]
<img width="448" alt="image" src="https://github.com/user-attachments/assets/4868cea5-bb3a-4a4c-a143-85eace275e9f">
<img width="1015" alt="image" src="https://github.com/user-attachments/assets/6545d466-3ecd-45af-bd21-1600b1f01698">
Click export. Attach log.

**Comment by 100tomer** [comment]
> <img alt="image" width="448" src="https://private-user-images.githubusercontent.com/50960678/360954578-4868cea5-bb3a-4a4c-a143-85eace275e9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjIzNDEsIm5iZiI6MTcyNDQyMjA0MSwicGF0aCI6Ii81MDk2MDY3OC8zNjA5NTQ1NzgtNDg2OGNlYTUtYmIzYS00YTRjLWExNDMtODVlYWNlMjc1ZTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE0MDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNjQ4OTQ3YjQwMTAzOTNjZTFiNDUwMGIzNDYwN2I0ZDIzZTY1MTgwN2EwYTBkMDkxNDMxNGYwMjQ4ZjBhNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V9WlxjFhUdGNnRxOnHyap3siCUXstJyfLDuiY4ooa2A"> <img alt="image" width="1015" src="https://private-user-images.githubusercontent.com/50960678/360954662-6545d466-3ecd-45af-bd21-1600b1f01698.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjIzNDEsIm5iZiI6MTcyNDQyMjA0MSwicGF0aCI6Ii81MDk2MDY3OC8zNjA5NTQ2NjItNjU0NWQ0NjYtM2VjZC00NWFmLWJkMjEtMTYwMGIxZjAxNjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE0MDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YmFjYjgxNWRiYjNmODM5MzJjN2Y4OTMzYjA3YzkxYjhkY2ZmMzI4OTc4MTVkNTM2MDZmMjRiOGQ5NjU4NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6zaNCZlsmuUIezTVoRo6wt6dUsQXQJboX70yc4QC-u4"> Click export. Attach log.



cool thanks here is the log

[Build iOS_2024-08-23T17-07-56.txt](https://github.com/user-attachments/files/16729832/Build.iOS_2024-08-23T17-07-56.txt)

**Comment by osy** [comment]
What's the output of `ls /Users/tomercohen/Downloads/UTM-main/`?

**Comment by 100tomer** [comment]
> What's the output of `ls /Users/tomercohen/Downloads/UTM-main/`?

Build.xcconfig			README.zh-Hant.md
CodeSigning.xcconfig		Remote
CodeSigning.xcconfig.sample	Renderer
Configuration			Scripting
Documentation			Services
Frameworks			UTM.xcodeproj
Icons				bin
JailbreakInterposer		host
LICENSE				include
Platform			lib
QEMUHelper			libexec
QEMULauncher			patches
README.cz.md			sbin
README.es.md			screen.png
README.fr.md			screenmac.png
README.ja.md			scripts
README.ko.md			share
README.md			ssl
README.pl-PL.md			utmctl
README.ru.md			zh-HK.lproj
README.uk.md			zh-Hans.lproj
README.zh-HK.md			zh-Hant.lproj
README.zh-Hans.md

**Comment by osy** [comment]
You're missing `sysroot-iOS-arm64`.

**Comment by osy** [comment]
`sysroot-iOS-arm64` should be in `/Users/tomercohen/Downloads/UTM-main`. You should be able to do `ls /Users/tomercohen/Downloads/UTM-main/sysroot-iOS-arm64` and not get any error.

**Comment by 100tomer** [comment]
> `sysroot-iOS-arm64` should be in `/Users/tomercohen/Downloads/UTM-main`. You should be able to do `ls /Users/tomercohen/Downloads/UTM-main/sysroot-iOS-arm64` and not get any error.

Wow! I can't believe this was the problem. Thanks for helping. now it did install it but I got this error. I'll try to solve it becuase it the first time I'm here. If you know how to solve it, it would save me lots of time probebly. (I do have paid Apple developer account)

<img width="508" alt="Screenshot 2024-08-23 at 5 23 58 PM" src="https://github.com/user-attachments/assets/1cf2a788-fc8b-4fe3-a002-80c7da15e4d6">

**Comment by 100tomer** [comment]
> I thought the instructions were clear:
> 
> > After downloading the prebuilt artifacts of your choice, extract them to the root directory where you cloned the repository.
> 
> Where did you end up copying it?

So I extracted it and copied the folders inside of it to the root directory. 
I think the most confusing part for me was seeing to many missing files in the xcode project.

Sorry for the trouble and I really appreciate your kind help ! 
(If in any chance you know how to solve the last Apple developer problem it would be even better (I'm still trying))

**Comment by 100tomer** [comment]
> I thought the instructions were clear:
> 
> > After downloading the prebuilt artifacts of your choice, extract them to the root directory where you cloned the repository.
> 
> Where did you end up copying it?

When I try to run any VM even like arch linux from the gallery I get this? (debugger is still attached)
![IMG_BB76FA623D2F-1](https://github.com/user-attachments/assets/1caafab6-6c91-47d2-b5cb-d7c16d705dec)
