### ISSUE TITLE
Debian LXDE Input/Output error with virtual machine on SSD connecting same SSD

### ISSUE THREAD

**Issue by lgrachov** [utmapp/UTM#6470]
**Describe the issue**  
When a virtual machine is on an SSD, trying to connect the same SSD that the virtual machine is on, it will result in a **Input/Output** error. When this happens, the SSD is disconnected for a few seconds, and reconnects back. If a file was transferred before connection, the file would be deleted permanently, with no recovery unless it was copied. The virtual machine used was the Debian LXDE virtual machine provided on the [UTM Gallery](https://https://mac.getutm.app/gallery/).

**How to Reproduce**

> [!CAUTION]
> If you transferred a file to a drive and then too quickly connected the drive to the virtual machine, the transferred file will be deleted.

- Move a virtual machine to an external drive (can be anything, just make sure it's external)
- Create a shortcut to that virtual machine (double click the file)
- Startup the virtual machine from the drive
- Connect the external drive (same one that the virtual machine is on) and connect it to the virtual machine.
- See the **Input/Output** error appear.

**Configuration**  
* UTM Version: 4.2.5
* macOS Version: 14.0
* Mac Chip: M2
* SSD: Samsung T7 Shield 1TB

**Crash log**  
The app did not crash.

**Debug log**  
I did not have `Debug Logging` on.

**Upload VM**  
[config.plist.zip](https://github.com/user-attachments/files/16199274/config.plist.zip)

**Comment by osy** [comment]
When you connect to the VM, it will disconnect from the host. This is expected behaviour

**Comment by lgrachov** [comment]
> When you connect to the VM, it will disconnect from the host. This is expected behaviour

The thing is, the SSD did not connect to the VM.

**Comment by osy** [comment]
I mean what do you expect? Your VM is stored on the ssd so if you pull the plug from your computer (virtually), your VM doesn't run anymore
