### ISSUE TITLE
UTM VM's not backed up by Time Machine

### ISSUE THREAD

**Issue by romlu2024** [utmapp/UTM#6474]
**Describe the issue**  
I rely on Apple's built-in Time Machine for my backups and recently noticed due to a VM corruption that I was not able to recover the VM from the backups. Instead of having a recent backup, I only had the backup of the initial VM setup. In fact, when running a VM in UTM and closing it, UTM does not modify the time stamp and therefore Time machine does not backup the changed VM. 

This happens for VM's stored in the default location and for VM's moved in a custom location.

**Configuration**  
* UTM Version: 4.5.3
* macOS Version: macOS Sonoma 14.5
* Mac Chip (Intel, M1, ...): Apple Silicon M1

**Comment by osy** [comment]
I think this is an issue with Time Machine. Did you exclude ~/Library or anything by chance?

**Comment by romlu2024** [comment]
No, nothing is excluded.

As I mentioned in the initial post, even the VM's that are moved through the "Move" feature in UTM to a custom location are not backed up.

When I modify the VM and stop UTM, the date of the VM bundle is not changed and the modification date of the qcow2 files are not changed as well.

**Comment by osy** [comment]
I just tested this and indeed the bundle modified date did not change but the qcow2 file did change modified date. Can you post the output of https://eclecticlight.co/2018/05/31/new-version-of-the-time-machine-mechanic-t2m2/

**Comment by romlu2024** [comment]
Hi osy, please find attached the log files.

I think I was confused about the time stamp of the bundle while creating the bug report. I now took a test VM, backup the VM with TM and restored the whole VM.

In fact, it gets restored but the time stamp of the bundle is still showing a very old date (date of creation of VM). When you browse the TM history, you always see the same date (when the VM was created). You never see an updated date and time.

Maybe this confused me.

In TM history, the date should change each time the VM gets backup'ed up when powered on previously.

[TM-Logs.txt](https://github.com/user-attachments/files/16707203/TM-Logs.txt)

**Comment by osy** [comment]
I think the bundle timestamp doesn't change but the files inside of it does. And that does get backed up right?
