### ISSUE TITLE
Serial output overlaps floating keyboard buttons/rounded corners

### ISSUE THREAD

**Issue by MaxPelly** [utmapp/UTM#6482]
**Describe the issue**
When connecting to a VM via serial the serial output goes all the way from the very top to the very bottom of the screen and thus is hidden both by the rounded corners at the top of the dipslay and the floating extra keyboard buttons at the bottom. The second is particularly anoying as after filling the screen the cursor is behind the floating keyboard buttons as well making it impossible to see what is being typed without clearing the screen.

![IMG_1301](https://github.com/user-attachments/assets/84492dfc-8db8-40a8-8443-bd68303e481b)

**Configuration (required)**
* UTM Version: 4.5.3 build 99
* OS Version: 18.0 beta 3
* Device Model: 11 inch M1 ipad pro
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? Appstore

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the bottom of the configuration options (or at the top of the `QEMU` page) is `Debug Log`. Turn it on and save the VM. After you experience the issue, quit the VM and re-launch UTM. Open the VM settings again and select `Export Log...` and attach it here.

**Comment by wmorgue** [comment]
+1 for me.
It's great to add some padding or make an item in the menu to customize the horizontal/vertical padding.
