### ISSUE TITLE
weird font / symbols trying to install Windows 11 ARM

### ISSUE THREAD

**Issue by maxulm** [utmapp/UTM#6483]
Hi, trying to install Windows 11 ARM on iPadOS the installer displays this weird font / symbols.
Anyone can help?

![iPadOS Installer](https://github.com/user-attachments/assets/cd7975b8-7585-4f73-a2dd-2507e84dc603)

**Comment by vernonstinebaker** [comment]
Same here. Trying to install on an 11" iPad Pro (M4) running iPadOS Version 18 (beta v3).

**Comment by krystofkrticka** [comment]
I also have this issue. This makes installing Windows impossible.

**Comment by kulogix** [comment]
Same

**Comment by AppStudioLB** [comment]
me too

**Comment by mspeicher** [comment]
same here

**Comment by a2she** [comment]
Same here!

**Comment by RoadsterAlex** [comment]
Same issue here with the install 
But then I get this 
![Uploading image.jpg…]()

Not sure what this means lol

**Comment by maxulm** [comment]
Not sure wether this is a problem of using a non-vga-vm...
But selecting a vga-graphics, the vm doesn't start on ipadOS.
Maybe any developer, who could help? Seems there are many users having the same problem.

**Comment by dbacks2196** [comment]
Same here. Very weird

**Comment by augustomaiorino** [comment]
Same problem

**Comment by maximtitovich** [comment]
Any news from devs on this one? I also have it

**Comment by pedestriantactics** [comment]
Same issue

**Comment by nicco** [comment]
Same here with a M2 Ipad Pro... Same image works like a charm in a M2 Mac

**Comment by osy** [comment]
Hi, please don't follow the issue template:

```
**Configuration (required)**
* UTM Version: 
* OS Version: 
* Device Model: 
* Is it jailbroken (name jailbreak used)? 
* How did you install UTM? 
```

I cannot debug without this info

**Comment by osy** [comment]
Also saying "same" does not help. If you can reproduce the issue, please provide more context.

**Comment by osy** [comment]
Okay, I was able to reproduce it. It seems to only occur on UTM SE and not in JIT UTM. We do not support or recommend installing Windows 11 on UTM SE (it is a *retro* emulator). It is probably related to #5925

**Comment by maxulm** [comment]
So you recommend using UTM from Altstore?

**Comment by osy** [comment]
Fixed in v4.6

**Comment by maxulm** [comment]
Still reproducable in 4.6.2

**Comment by osy** [comment]
Can you provide more info? Specific iso used and etc

**Comment by maxulm** [comment]
`qemu-system-aarch64 -L "/private/var/containers/Bundle/Application/12A1E7F1-5834-46ED-A591-0015E3E3114C/UTM SE.app/qemu" -S -spice unix=on,addr=54FBCB86-757C-416C-8F47-EB8B909273E2.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off -chardev spiceport,name=org.qemu.monitor.qmp.0,id=org.qemu.monitor.qmp -mon chardev=org.qemu.monitor.qmp,mode=control -nodefaults -vga none -device virtio-net-pci,mac=B6:21:6F:8A:62:74,netdev=net0 -netdev user,id=net0 -device virtio-gpu-pci -cpu cortex-a72 -smp cpus=3,sockets=1,cores=3,threads=1 -machine virt,virtualization=on -accel tcg,tb-size=512 -drive "if=pflash,format=raw,unit=0,file.filename=/private/var/containers/Bundle/Application/12A1E7F1-5834-46ED-A591-0015E3E3114C/UTM SE.app/qemu/edk2-aarch64-code.fd,file.locking=off,readonly=on" -drive "if=pflash,unit=1,file=/private/var/mobile/Containers/Data/Application/B857CA5E-5386-49A8-9963-762DCA056792/Documents/Win 11.utm/Data/efi_vars.fd" -m 2048 -audiodev spice,id=audio0 -device intel-hda -device hda-duplex,audiodev=audio0 -device nec-usb-xhci,id=usb-bus -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device usb-storage,drive=driveB242B441-15A4-4262-B0A1-CCD844614BBD,removable=true,bootindex=0,bus=usb-bus.0 -drive "if=none,media=cdrom,id=driveB242B441-15A4-4262-B0A1-CCD844614BBD,file.filename=/private/var/mobile/Containers/Shared/AppGroup/B35E7A0C-3555-42D9-9B1E-C8DF1B0C4CFC/File Provider Storage/22631.2861.231204-0538.23H2_NI_RELEASE_SVC_REFRESH_CLIENTCONSUMER_RET_A64FRE_de-de.iso,file.locking=off,readonly=on" -device virtio-blk-pci,drive=driveCA3F2F54-BDE8-47DC-B553-6DA0E39DBFE6,bootindex=1 -drive "if=none,media=disk,id=driveCA3F2F54-BDE8-47DC-B553-6DA0E39DBFE6,file.filename=/private/var/mobile/Containers/Data/Application/B857CA5E-5386-49A8-9963-762DCA056792/Documents/Win 11.utm/Data/CA3F2F54-BDE8-47DC-B553-6DA0E39DBFE6.qcow2,discard=unmap,detect-zeroes=unmap" -device virtio-serial -device virtserialport,chardev=org.qemu.guest_agent,name=org.qemu.guest_agent.0 -chardev spiceport,name=org.qemu.guest_agent.0,id=org.qemu.guest_agent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -device virtserialport,chardev=charchannel1,id=channel1,name=org.spice-space.webdav.0 -chardev spiceport,name=org.spice-space.webdav.0,id=charchannel1 -name "Win 11" -uuid 54FBCB86-757C-416C-8F47-EB8B909273E2 -device virtio-rng-pci`

Does this help?

**Comment by osy** [comment]
Can you try the x64 version?

**Comment by maxulm** [comment]
> Can you try the x64 version?

Maybe I could, but due to performance reasons, I'd prefer the ARM-version.
Is there any reason to try the x64-version?

**Comment by osy** [comment]
On SE, the ARM version isn't any faster if you check Force Multicore
