### ISSUE TITLE
Import non-removable disk images on iOS is broken

### ISSUE THREAD

**Issue by HunterBoy344** [utmapp/UTM#6485]
I’ve already got a 3GB raw hard disk image for QEMU that I want to use with UTM SE, but I can’t use it because I can only import it as a removable drive. I can only set the interface type to USB or None without a crash on startup (wherein QEMU complains that a drive on a non-removable interface has the removable flag set) and if I do it doesn’t even boot into the OS, just the BIOS shell.

I’d like to be able to import a disk image (specifically a raw IMG file, but other formats like qcow2 would be nice as well) as a non-removable drive on iOS. This seems to already be a feature in UTM for macOS, so I don’t know why it’s not in UTM and UTM SE on iOS.

**Comment by jorgebugon** [comment]
I have the same problem currently, I tried creating the virtual machine in osx and importing it but it didn't work. I want to get Home Assistant working on an iPhone. Has it worked for you to import and get the machine working in UTM Se?

**Comment by osy** [comment]
"Import Drive" is supposed to do this. It is a bug that it creates a removable drive.
