### ISSUE TITLE
Recommended method/unable to install this app?

### ISSUE THREAD

**Issue by larryqiann** [utmapp/UTM#65]
Hi

I've tried both methods noted here to install this application, but it looks like there are some issues I'm hoping someone may have some insight into.

1) Compiling with Xcode
I've followed the instructions in the readme, and the build completes successfully. However, on launch, a white screen shows and Xcode indicates that there was an issue with the code signing of libgmodule-2.0.0. I've tried removing the code signature and manually codesigning it, and this does not resolve this issue.

2) Resigning IPA
I have used various provisioning profiles and certificates to attempt to sign the app package IPA downloaded from the GitHub. Installation from Xcode and from iTunes/Finder fails.

The device is running iOS 13.3.1, and I am using a paid developer account.

Thanks!

**Comment by osy86** [comment]
Can you double check your provision profile and make sure it does not expire in 7 days? Xcode may have not generated the right profile.

**Comment by larryqiann** [comment]
The provisioning profile used with Resigner expires in 2021. The provisioning profile used with Xcode is managed automatically and doesn't appear to be an issue.

**Comment by ThatsNiceGuy** [comment]
Same crash happens for me on iOS 13.3 iPad Pro 11” when I use PreProvision to sign (with a free dev account) and install the app but do not have AppSync. If I use AppSync, the app does not crash at all.

**Comment by larryqiann** [comment]
iPhone Cake (free signing solution) is able to sign and launch this (crashes on VM start though, not sure if seperate issue or related)

**Comment by ThatsNiceGuy** [comment]
Yep it is related, has to do with this
[utm.txt](https://github.com/utmapp/UTM/files/4247596/utm.txt)

**Comment by larryqiann** [comment]
I have attempted manual codesigning of the dylib but that seems still not working

**Comment by ThatsNiceGuy** [comment]
Yea I have tried that as well but it will keep crashing unless the device is jailbroken and has AppSync Unified installed on it. Weird issue that I can’t find the cause of

**Comment by osy86** [comment]
What about launching it via Xcode? If it crashes you'll at least get a message.

**Comment by saagarjha** [comment]
Do you have a free developer account? I believe there were some changes that went into iOS 13.3.1 that prevents these accounts from signing dylibs.

**Comment by osy86** [comment]
My understanding is that @larryqiann has a paid account and @ThatsNiceGuy has a 13.3.0 device. But they should confirm.

**Comment by ThatsNiceGuy** [comment]
Yep I have a 13.3.0 device, didn’t update to 13.3.1

**Comment by larryqiann** [comment]
I have a paid account and I am on iOS 13.3.1, iPhone Xs Max. Both versions of the IPA exhibit issues using both the resigner and iPhone/App Cake.

Which combination of procedures and software versions are known working (allow both install and VM launch)?

**Comment by osy86** [comment]
I'm on 13.3.1 and have a paid account. It should work. Try these instructions from the README

> The recommended way to obtain the dependencies is to use the built artifacts from [Github Actions](https://github.com/utmapp/UTM/actions?query=workflow%3ABuild). Look for the latest build and download the Sysroot artifact from either the arm64 build (for iOS) or x86_64 build (for iOS Simulator). Then unzip the artifact to the root directory of UTM. You can then open UTM.xcodeproj, select your signing certificate, and then run UTM from Xcode.

**Comment by saagarjha** [comment]
The build instructions should work, I was able even able to get it working with a MacPorts installation. Check the signatures on the embedded libraries and see if they’re correct.

**Comment by larryqiann** [comment]
Those instructions from the README were the ones I tried. What is the recommended way to check the signatures?

**Comment by osy86** [comment]
Can you try to disable automatic signing from Xcode and manually pick a profile you generate from Apple?

**Comment by larryqiann** [comment]
I've tried building the dylibs from source instead of downloading them as mentioned in the readme. This works, and the app can launch VMs.
