### ISSUE TITLE
Virtualization is not available

### ISSUE THREAD

**Issue by StonkReal** [utmapp/UTM#6506]
**Describe the issue**
Hello, I am on an iPad 6th Gen and UTM doesn’t allow me to use virtualization.

**Configuration (required)**
* UTM Version: * UTM_HV.ipa (v4.5.3)
* OS Version:*  iPadOS 16.6 
* Device Model: * iPad 6th Gen
* Is it jailbroken (name jailbreak used)? * Yes. Dopamine.
* How did you install UTM?* TrollStore

**Comment by lgrachov** [comment]
Which one? If you are trying to use the Apple Silicon virtualisation for macOS, then it won’t work. You can only install Windows and Linux virtual machines on UTN for iOS.

**Comment by osy** [comment]
Yes it's not available because iOS doesn't support it.
