### ISSUE TITLE
Sporadic crashes of UTM when shutting down Windows ARM VM

### ISSUE THREAD

**Issue by LostInCompilation** [utmapp/UTM#6511]
**Describe the issue**  
I experienced some random crashes the last weeks I can't consistently reproduce.
This crash happens sometimes while shutting down a Windows11 ARM64 VM. Before the OS shut down, UTM crashes. No USB devices were plugged in or out, only an AppleWatch charger was plugged in.

**Configuration**  
* UTM Version: 4.5.3 (99)
* macOS Version: 14.5.1
* Mac Chip: M1 Pro

**Crash log**  
[View Crashlog on Pastebin](https://pastebin.com/DHEH08Wz)

**Debug log**  
Not yet available.

**Upload VM**  
[config.plist.zip](https://github.com/user-attachments/files/16356327/config.plist.zip)

**Comment by LostInCompilation** [comment]
The crash happened again at the second a Windows 11 VM (x86_64 this time) finished the shutdown process.
Crash log: https://pastebin.com/qaTM347e

**Comment by osy** [comment]
```
Thread 5 Crashed:: org.libusb.device-hotplug
0   ???                           	       0x11a0e4cb0 ???
1   usb-1.0.0                     	       0x100f4a924 usbi_log + 64
2   usb-1.0.0                     	       0x100f598b8 darwin_event_thread_main + 700
3   libsystem_pthread.dylib       	       0x18a401f94 _pthread_start + 136
4   libsystem_pthread.dylib       	       0x18a3fcd34 thread_start + 8
```

Seems to be in libusb. Does this happen without the apple watch charger plugged in?

**Comment by osy** [comment]
@LostInCompilation Please test v4.6.0 beta, a race condition was fixed that may resolve this https://github.com/utmapp/UTM/releases

**Comment by osy** [comment]
Closing this because of the update to SPICE. Please open a new issue with a new crash log if the issue occurs again.
