### ISSUE TITLE
WeWishYouABigGaeChristmas Eclipse

### ISSUE THREAD

**Issue by Clownfly** [utmapp/UTM#653]
**Describe the bug**

**Version**
In the menu bar select UTM -> About to see the version and build number.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yaboinextd00r** [comment]
Listen here cunt, your a fucking 10 year old, your an unborn deer feetus you fucking retard go fuck some gay horny men you fuckhead

**Comment by Clownfly** [comment]
But I’m not a kid. You are. Let’s all have fun. Cheerios are a good staring point.
