### ISSUE TITLE
Virtualization tab gone

### ISSUE THREAD

**Issue by RonGros** [utmapp/UTM#6540]
Trying to enable rossetta, I cannot find the "virtualization tab".
I saw it before, so I decided to install a new VM to try it on, but then the tab wasn't there, I went back to my old machine and it's gone there also. I removed the new machine, and tried with the old machine again, and it's not there
 
**Configuration**  
* UTM Version: 4.5.3 and 3.1.5 
* macOS Version: 14.5
* Mac Chip (Intel, M1, ...): M1 Pro

<img width="830" alt="image" src="https://github.com/user-attachments/assets/e7a48e7a-f416-442a-bace-4f543dc9a543">

**Comment by osy** [comment]
Rosetta currently only works on Apple virtualization backend.

**Comment by RonGros** [comment]
@osy what do you mean? I saw this tab and it's also in the help, but it doesn't exist what am I missing?

**Comment by osy** [comment]
https://docs.getutm.app/settings-apple/virtualization/

See https://docs.getutm.app/settings-apple/settings-apple/ for what apple backend is
