### ISSUE TITLE
utm se has no buttons when using virtual machine

### ISSUE THREAD

**Issue by SusDTSteve** [utmapp/UTM#6548]
**Describe the issue**
utm and utm se has no toolbar in the virtual machine except for the button that brings up the toolbar that doesent do anything

**Configuration (required)**
* UTM Version: 4.5.3
* OS Version: 15.8.1
* Device Model: iphone 7
* Is it jailbroken (name jailbreak used)? no
* How did you install UTM? app store

**Comment by osy** [comment]
Duplicate of #6178
