### ISSUE TITLE
Deleting the app seems to delete VMs

### ISSUE THREAD

**Issue by haveamission** [utmapp/UTM#66]
As far as I can tell, deleting the app seems to delete the .img files that the app uses for drives.

This seems like a bad idea as anytime you need to uninstall and reinstall the app, you have to roll your VMs again.

**Comment by osy86** [comment]
That's the expected behavior for all iOS apps and is a side effect of the iOS file system sandbox. You should move your VMs out of the sandbox with the Files app before deleting it.
