### ISSUE TITLE
a Fast Forward Feature for UTM SE

### ISSUE THREAD

**Issue by Swarde11** [utmapp/UTM#6629]
we already know that UTM SE's emulation is really slow, so why not add a feature called “Fast Forward”?

it is a button that speeds up the emulation to skip long booting and slow emulation, just like the Fast Forward Feature in RetroArch to skip Cutscenes!

the fast forward speeds can be from 2x all the way to 1000x, which can be configured during emulation in a text box!

and add a “reset” button so we can reset the fast forward speed to 1x!

**Comment by osy** [comment]
UTM SE isn't slow because we thought that was a fun thing to do. UTM SE is slow is because your device's processor isn't fast enough to emulate a PC at full speed.

**Comment by Swarde11** [comment]
> UTM SE is slow is because your device's processor isn't fast enough to emulate a PC at full speed.

You’re right, that’s why i think that the Fast Forward Feature should be added!

**Comment by osy** [comment]
Okay once you download some more RAM for your device, we'll add it.

**Comment by Swarde11** [comment]
> Okay once you download some more RAM for your device, we'll add it.

i have an M1 ipad pro with 8GB of RAM, so it’s good for emulation for old OSes (e.g Windows XP, Ubuntu 12.04)
