### ISSUE TITLE
ISO not selecting

### ISSUE THREAD

**Issue by DTGuy** [utmapp/UTM#6644]
**Describe the issue**
Ok so when I try to select my iso file it don't select I click it over and over again but I can not get the iso to be mounted

* UTM Version: UTM 4.5.4
* OS Version: iOS 18
* Device Model: iPhone 13
* Is it jailbroken (name jailbreak used)? no
* How did you install UTM? By sideloading it with Scarlet

**Comment by osy** [comment]
Known issue of Scarlet

Duplicate of #4466
