### ISSUE TITLE
Download progress is gone the second internet goes out

### ISSUE THREAD

**Issue by BezierCurves** [utmapp/UTM#6662]
I wasn't sure whether to put this as a bug or a feature request, but I chose the latter one because this is probably not a bug (with UTM).

Right now, my Mac's Wi-Fi seems to disconnect randomly. This has the side effect of UTM stopping the download because "The Internet connection appears to be offline." This is an issue when downloading MacOS virtual machines (other ones can be downloaded from a web browser) I would like a feature that saves the download progress. I don't know _if_ this is possible, but I think it is.

I know the writing is terrible. I couldn't think of how to fix it (the writing).

**Comment by ideologysec** [comment]
As a workaround, you can download the IPSW images from Apple with a download manager that supports resuming (like wget for example), and then tell UTM which image to use.

https://mrmacintosh.com/apple-silicon-m1-full-macos-restore-ipsw-firmware-files-database/
