### ISSUE TITLE
Rootless jailbreak using sileo to install UTM prompts missing firmware sbin dependency 

### ISSUE THREAD

**Issue by myz129** [utmapp/UTM#6667]
Hello UTM development team

I encountered an exception while installing the UTM program through Sileo. Remind me that a dependency named firmware sbin is missing. My device details are as follows

Device: iPhone13 ProMax
System: iOS 15.1.1
JailBreak Tool: Dopamine-2.2.2
Install UTM version: UTM-4.5.4

The interface prompt is as follows

May I ask how I can install this dependency package for my device

Thank you very much for your reply

**Comment by Xernium** [comment]
Confirmed. Will work to rectify soon.

**Comment by sulthannaf** [comment]
> Confirmed. Will work to rectify soon. 

any update deb for rootless?
