### ISSUE TITLE
Installer doesn't work for 15.0 guest on 15.0 host

### ISSUE THREAD

**Issue by pwnee** [utmapp/UTM#6685]
Choosing the ipsw to install, but nothing happens (no installation progress percentage is shown even). However VirtualApple is able to install it, so this isn't a host issue.

No crashes in the console, nor a connection request to apple. Just a sequence of:

```
com.apple.Virtualization.VirtualMachine	interrupt <private>
com.apple.Virtualization.VirtualMachine	interrupt <private>
com.apple.Virtualization.VirtualMachine	doorbell Device 1 Endpoint 0x02
com.apple.Virtualization.VirtualMachine	interrupt <private>
```

Another thing is, when you generate a 15.0 VM, it doesn't show up in the navigation bar until UTM is restarted.

**Configuration**  
* UTM Version: v4.5.4 (from github releases)
* macOS Version: 15.0
* Mac Chip (Intel, M1, ...): M1

**Comment by mymbrooks** [comment]
@pwnee Try 15.1 beta 4, it works fine for me on M1, host is also 15.1 beta 4

**Comment by osy** [comment]
I think this is related to #6639

It works fine for me on my machine.

**Comment by pwnee** [comment]
Okay, host being 15.0.1 resolves the issue for my case. Even though the 15.0 host issue is not resolved, I will close the issue.
