### ISSUE TITLE
Karen’s repo unavailable for appsync unified 

### ISSUE THREAD

**Issue by crazyp** [utmapp/UTM#6693]
I’m trying to install utm on my jailbroken iPad Pro 10.5 running 17.7 and I find that the Karen’s repo has been down for quite some time so I’m unable to install appsync unified. I know that the repo is out of you control but are there any other ways to get appsync

**Comment by ok-coder1** [comment]
Yes, add `https://bigfloppa234.github.io/repo/` to your sources list in Cydia, and then search for AppSync Unified. You will find it.

**Comment by crazyp** [comment]
I did a Palera1n rootfull jailbreak. I’ve just had trouble obtaining the current version of appsync unified. I also have been unable to build it from source

**Comment by osy** [comment]
We now include appsync unified in the UTM repo
