### ISSUE TITLE
[qemu] Out of memory faster with bulletproof JIT

### ISSUE THREAD

**Issue by osy86** [utmapp/UTM#67]
From @saagarjha https://saagarjha.com/blog/2020/02/23/jailed-just-in-time-compilation-on-ios/
> Unlike processes with dynamic-codesigning which get access to [“jumbo VA spaces”](https://github.com/apple/darwin-xnu/blob/a449c6a3b8014d9406c2ddbdc81795da24aa7443/bsd/kern/kern_exec.c#L3061), iOS applications can normally only allocate a limited amount of virtual memory (which is determined using [a fairly elaborate calculation](https://github.com/apple/darwin-xnu/blob/a449c6a3b8014d9406c2ddbdc81795da24aa7443/osfmk/arm/pmap.c#L9868) based on the size of physical memory).

TCG allocates from 1024KiB to up to 2GiB of JIT cache. By default it uses ram size / 4. Because of the mirror mapping, iOS thinks we use 2x the amount of space we actually do for this JIT cache and therefore kills the app much quicker than before.

We should experiment with lowering the size of the JIT cache by default and/or allow the user to configure it. Make sure that the performance lost is less than the gains from the bulletproof JIT implementation. Otherwise, we should allow the old JIT as an option for those who value larger memory over faster speeds.

**Comment by osy86** [comment]
Can someone with jailbreak test this? https://github.com/utmapp/UTM/releases/download/v0.2-fakesign/UTM.ipa

I added the dynamic-codesign entitlement to the fake signed IPA. Let me know if that fixes this issue on jailbroken devices.

**Comment by saagarjha** [comment]
Was this built off of master?

**Comment by osy86** [comment]
Yes (at the time).

**Comment by saagarjha** [comment]
If so, we should disable the `ptrace` hacks on these builds. Unless you already took care of that?

**Comment by osy86** [comment]
I haven't but right now I haven't committed to having a separate "JB only" build yet. Just want to test it out. If there are benefits (such as supporting higher memory limits) then I will create a proper build config. The JB version could also use `fork()` and support multiple VMs and other features. I kinda want to get everything else working before doing stuff like that though as I would have to obtain a JB device to test with.

**Comment by saagarjha** [comment]
Is there anything in particular that is a good test?

**Comment by osy86** [comment]
If you have VM booting (Windows specifically since I haven't tried much other ones), bump the memory up until you get to a point where it boots but goes out of memory once it gets to the desktop. Then try that same config with the fakesigned version which has the dynamic-codesign entitlement. Even though it doesn't use `MAP_JIT`, I wonder if the entitlement is enough to bypass the limits.

**Comment by saagarjha** [comment]
Turns out my iPhone 6 doesn't have enough storage space to run Windows :(

**Comment by obbcth** [comment]
> Can someone with jailbreak test this? https://github.com/utmapp/UTM/releases/download/v0.2-fakesign/UTM.ipa
> 
> I added the dynamic-codesign entitlement to the fake signed IPA. Let me know if that fixes this issue on jailbroken devices.

Crashes on startup. Reboot did not solve the issue. On iPad Air 3 iOS 13.3 Jailbroken unc0ver 4.0.3.

**Comment by ThatsNiceGuy** [comment]
![BA853B53-A1BF-4516-AACC-B1127F76AB71](https://user-images.githubusercontent.com/10524728/75252690-6936ca80-579a-11ea-8b5e-37444a15f31f.jpeg)
Installs correctly but crashes on startup.
```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Library not loaded: @rpath/libgpg-error.0.dylib | Referenced from: /private/var/containers/Bundle/Application/632C8241-83A3-42D3-9191-7F1D49974C11/UTM.app/UTM | Reason: Incompatible library version: UTM requires version 28.0.0 or later, but libgpg-error.0.dylib provides version 25.0.0
Triggered by Thread:  0

**Comment by osy86** [comment]
Does jailbreak + jailbreak apps install additional libs? That’s probably the issue for many people.

I’m not sure how to fix this though.

**Comment by baconglucose** [comment]
Did not crash for me, fresh jailbreak with the necessary tools on an iPad Pro first gen on iOS 13 jailbroken with checkra1n.
However, I cannot test using Windows because I do not have an image. I am testing arch and ubuntu, will report back.

**Comment by js-john** [comment]
I found that using an older version of sysroot(download from "Actions" in 22/02/2020) to compile UTM can reduces memory usage by 200+MB. With the new version of sysroot, I set 1GB of memory for the iPad mini 5 and UTM always crashes, but with the old version I can set 1GB of memory.

**Comment by osy86** [comment]
Uh you do realize that it’s because you’re using the older slower JIT code right. That’s literally what this issue is about. The new jit code is faster but makes iOS think it’s using more memory.

**Comment by osy86** [comment]
Update: I'm punting this issue until the future. I looked into implementing a QEMU solution where not everything is mirror mapped but no solution can solve all the following problems:

* To link TBs with jumps, you would require the TB to be mirror mapped or turn off direct jumps. Either way there's a performance downgrade.
* TB metadata is stored before the code as an optimization. If we move the metadata we run into the old issue of having to statically allocate space for TB metadata with a best guess. Also cache locality.
* In MTTCG one thread could execute a TB created by another thread. If that other thread decides to unmap the mirror and the first thread decides to modify the jump list or page list or anything, it will crash. Adding locks will degrade performance.

So here's the situation: on iDevices, you are limited to about 50% of the physical RAM per app. If you allocate all of that to the VM, then about 8% of that is guest JIT and 8% is wasted and 34% is host RAM. If you want that 8%, either jailbreak or decrease the JIT cache (decreases performance somewhat).

**Comment by professorIsaac** [comment]
There is this new sandbox escape that works in AltStore https://twitter.com/rileytestut/status/1256321645930663936 it may be useful for faster performance

**Comment by osy86** [comment]
The sandbox escape has no relevance here.

**Comment by saagarjha** [comment]
I wonder who enforces dynamic-codesigning…

**Comment by osy86** [comment]
I don't think `dynamic-codesigning` gives any improved performance? The alias mapping technique seems as good as we can get. Maybe you can find some cache locality improvements but I'm willing to bet those improvements are minimal.

**Comment by saagarjha** [comment]
Not only does dynamic-codesigning give you the ability to map RWX, you also get a larger virtual address space.

**Comment by osy86** [comment]
Hmm, true. I was only thinking of computation since they mentioned "faster performance." I guess you can get more host memory. But this is a bug Apple already fixed so it would only work on lower iOS versions. In that case, the jailbroken version of UTM already requests `dynamic-codesigning` entitlement. I don't really want to maintain a "improper entitlement" build just for < 13.5 builds just for this one issue.

**Comment by osy86** [comment]
Thinking a bit more on this. Does anyone know what happens on 13.5? Does the app get killed or does it just not get the entitlement? If it doesn’t kill it I see no harm in just always including the fake entitlement.

**Comment by professorIsaac** [comment]
The app gets killed what I suggest is a setting that you enable if you are jailbroken or on 13.4.1

**Comment by osy86** [comment]
I tested with and without `dynamic-codesigning` and there was no difference in reported memory usage or when it was killed.

**Comment by saagarjha** [comment]
Interesting; the code in XNU seems to make it appear like the jumbo mapping is entirely dependent on the ability to `MAP_JIT`: https://github.com/apple-open-source-mirror/xnu/blob/65d5be84e21bccbae44730ddb3b307a701b0351a/bsd/kern/kern_exec.c#L3604. You're able to successfully make such a page but are still killed?

**Comment by osy86** [comment]
I tested `mmap` with RWX (both with and without `MAP_JIT`) and it only works with `dynamic-codesign` so no surprises there.

But when I do the mirror mapping stuff, it crashes with code sign error on the icache flush. If I apply the ptrace trick as well, then Xcode’s memory usage is still the same during Windows boot and crashes at the same spot (after ~2.7GB of memory usage according to Xcode).

**Comment by saagarjha** [comment]
Which device are you testing this on? I think you may have to deal with APRR if it's something new. (You shouldn't need the ptrace trick…?)

**Comment by osy86** [comment]
iPad 2018. I was able to get JIT to work with APRR changes. But I don’t know if that affects the memory usage.

**Comment by osy86** [comment]
After farther tests it seems like “jumbo vm” != “allow more memory usage”. All it means is that you are allowed allocate more memory through vm_allocate or mmap. It does not let you *use* more memory. Unfortunately it seems from these tests that XNU’s internal bookkeeping of how much memory is “used” does not take account if mirror mapped addresses. It gets double counted.

The only way around this is to implement APRR in QEMU and when we detect dynamic-codesign to disable the mirror mapping and use APRR instead.

**Comment by saagarjha** [comment]
Right, I don't think Jetsam is disabled for such processes; if I had to guess the feature was probably added to support WebKit's Gigacage. I was assuming you were running out of virtual memory address space instead of physical memory. (Actually, I wonder if there's an entitlement to opt out of Jetsam?)

**Comment by osy86** [comment]
Yeah iOS thinks I’m using ~2.7GB of memory and kills it even though 1/3 of that is mirror mapped.

**Comment by professorIsaac** [comment]
Thanks to Jan kaiser I found 2 entitlements of jetsam that may opt you out com.apple.private.jetsam.modify-priority
com.apple.private.kernel.jetsam

**Comment by osy86** [comment]
On iOS 14 and macOS 11, this is no longer an issue (on jailbroken devices) with addition of qemu option to disable mirror mapping when proper entitlements are obtained. Since the ptrace hack was fixed and does not work on iOS 14, we will no longer consider this an issue.

**Comment by ThatsNiceGuy** [comment]
Potentially a last iOS 13 UTM update to take advantage of having full root access with those proper entitlements? This will help us A12/A13/A12X/A12Z users until a jailbreak for 14.0 is found that isn’t checkra1n. Although you said that you likely won’t update UTM for iOS 13 anymore

**Comment by osy86** [comment]
It doesn't have anything to do with root access. The issue is that there's missing APIs in iOS 13 (added in iOS 14 with macOS 11). Even with the proper entitlements, the APRR calls would have to be hard coded in QEMU. It seems like the CPU instructions to do so differs in each Ax generation. It would be really ugly to put all of that into QEMU. Of course it's doable but it's not maintainable and therefore seems like too much hassle.

The goal ultimately is to get the QEMU changes merged upstream. Then we don't have to maintain a separate QEMU fork. The same QEMU version can be used in both UTM v1 and UTM v2. Adding this change would complicate the picture.

**Comment by ThatsNiceGuy** [comment]
Wait a minute, I’m thinking completely wrong here. Since we’re jailbroken with full root access, sufficiently savvy users can manually modify jetsam configurations themselves to allow UTM to run with unlimited or very lenient limits. Sorry oof
