### ISSUE TITLE
Metal not supported on device. Cannot render display. 2011 MacBook Pro open core legacy patcher

### ISSUE THREAD

**Issue by JustSomeGitHubUser693** [utmapp/UTM#6710]
When i try starting any machine, the error shows up and the display doesn't work.

**Comment by osy** [comment]
Sorry, we do not support non-Metal devices.

**Comment by robertkirkman** [comment]
I know it was stated this is not supported here but I just wanted to let anyone else finding this issue know that technically, if the guest operating system is fully Serial compatible (like Debian), and everything you need can be done with a Serial connection only (and later an SSH or other Network connection after getting the guest installed), if you remove the Display device in UTM and add a Serial device with the default settings, then press E at the GRUB screen and add the kernel parameters `console=tty0 console=ttyS0,115200n8r`, then actually UTM does work on the non-Metal Mac and the UTM window turns into a working Serial window. but this only works for Serial and Network connections, no direct Display output, so people using that technique should **not** expect Display to easily work, it would be necessary for the user to set up manually-configured headless Network-based Display solutions like Xrdp or the many diverse implementations of VNC that can be found online.
