### ISSUE TITLE
Property 'hvf-accel.tso' not found with v4.6.0

### ISSUE THREAD

**Issue by luciodaou** [utmapp/UTM#6719]
**Describe the issue**  
Enabling TSO option gives me the following error:
"QEMU error: QEMU exited from an error: qemu-aarch64-softmmu: -accel hvf,tso=on: Property 'hvf-accel.tso' not found"
<img width="291" alt="image" src="https://github.com/user-attachments/assets/74d5ba74-4981-4a6b-83e1-97c3f6837a4d">

**Configuration**  
* UTM Version: 4.6.0
* macOS Version: 15.0.1
* Mac Chip (Intel, M1, ...): M3 Pro 11-core

**Debug log**  
[debug.log](https://github.com/user-attachments/files/17263153/debug.log)

**Upload VM**  
config.plist in txt extension
[config.plist.txt](https://github.com/user-attachments/files/17263173/config.plist.txt)

**Comment by osy** [comment]
Oh I forgot to rebuild the backend. It'll be fixed next update.

**Comment by osy** [comment]
Please test v4.6.1

**Comment by osy** [comment]
Sorry see #6836 this will be fixed in the next update

**Comment by osy** [comment]
Fixed in v4.6.2
