### ISSUE TITLE
Windows XP 64-bit boots to blank screen in 4.6.0

### ISSUE THREAD

**Issue by xadammr** [utmapp/UTM#6722]
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Describe the issue**  
Windows XP x64 boots to blank screen after updating to 4.6.0. 

Splash screen displays normally:
![image](https://github.com/user-attachments/assets/964d0b9a-c852-433e-b9e6-afaf75fcb294)

After splash screen, there is just a blank screen:
![image](https://github.com/user-attachments/assets/7987bfe7-1479-4b31-a2c2-bd823a91d93f)

The VM continues to work as expected in 4.5.4. 

**Configuration**  
* UTM Version: 4.6.0
* macOS Version: 15.0
* Mac Chip (Intel, M1, ...): M2 Pro

**Crash log**  
Not associated with crash. 

**Debug log**  
[debug.log](https://github.com/user-attachments/files/17267934/debug.log)

**Upload VM**  
[config.plist.zip](https://github.com/user-attachments/files/17267936/config.plist.zip)

**Comment by osy** [comment]
@xadammr I noticed in your config that you are using `pc-q35-2.9` which I have never gotten to work. When I try to run windows setup with your config, I get BSOD (0x0000007B) on both 4.5.4 and 4.6.0. Meanwhile, my Windows XP x64 install uses i440fx (pc) which still works. Any way you can either upload your VM or create a new VM and share it with me?

**Comment by xadammr** [comment]
@osy I created a new virtual machine using the same config (pc-q35-2.9), reinstalled Windows XP x64 and everything is working. It must be some weirdness localised that particular Windows install. 

Thanks for taking a look though -- but I blame Windows!
