### ISSUE TITLE
Accidentally clicked "don't ask again" for USB passthrough

### ISSUE THREAD

**Issue by myrrhkhan** [utmapp/UTM#6726]
**Describe the issue**  
Running a Windows 11 VM. Needed to connect a USB device to interact with a piece of software in my Windows VM. USB sharing would work fine, I'd always receive a dialog box saying "would you like to allow UTM to access [device]" with a "do not ask again" checkbox. At one point, I decided to click on the checkbox, after which USB sharing stopped working, maybe because I accidentally clicked "don't allow" instead of "allow" (don't think I did, but it is a possibility). Tried connecting later, wouldn't work, at one point UTM crashed (see log)
Either way, I was wondering if there was a way to undo this action (removing something from a "do not ask again list" or something) from the terminal or something. Device doesn't show up in Finder either (don't know if it did before though). USB device is working on a Windows machine.

**Configuration**  
* UTM Version: 4.5.4
* macOS Version: 15.0 (24A335)
* Mac Chip (Intel, M1, ...):  M2 MacBook Air

**Crash log**  
see crash.log file (output was too long for GitHub)
[crash.log](https://github.com/user-attachments/files/17272397/crash.log)

**Upload VM**  
[config.plist.zip](https://github.com/user-attachments/files/17272381/config.plist.zip)

**Comment by osy** [comment]
This popup is handled by macOS and we have no control over it. There is probably some plist somewhere that stores this info but I don't know. Maybe check the Console to see if there's any info there? I'll try to investigate it when I have time.

**Comment by osy** [comment]
@myrrhkhan I forgot, there is a way to reset it. The last checkbox in the settings will need to be unchecked
<img width="712" alt="image" src="https://github.com/user-attachments/assets/d72c6757-26e9-4cd0-9496-d55feb3c0592">

**Comment by perspectmc** [comment]
Thanks I had same issue - works now
