### ISSUE TITLE
Mirror for images hosted in archive.org

### ISSUE THREAD

**Issue by moham96** [utmapp/UTM#6735]
[Archive.org is down and hacked](https://www.theverge.com/2024/10/9/24266419/internet-archive-ddos-attack-pop-up-message) can you provide mirrors for images like kali linux 
Regards

**Comment by brc-dd** [comment]
I found this - https://mirror.bouwhuis.network/utm/

I'm not sure though if it's reliable. If someone can get the sha checksums of original files we can confirm.

**Comment by osy** [comment]
I believe archive.org is back now
