### ISSUE TITLE
Guest display zooms incorrectly if iPad display zoom not set to Default

### ISSUE THREAD

**Issue by rrgeorge** [utmapp/UTM#6736]
**Describe the issue**
When iPadOS has "Display Zoom" set to "Larger Text" or "More Space", the guest will not zoom in correctly. When set to "Default" the display will zoom correctly. When Display Zoom is set to "Larger Text", the guest display will be scaled down, rather than filling the screen. When DisplayZoom is set to "More Space", the guest display will be zoomed in too far, causing the outer perimeter to be cropped. See also #5975 

**Configuration (required)**
* UTM Version: UTM Remote 4.5.4 (101) to UTM 4.5.2 (97) on macOS 15.0.1
* OS Version: iPadOS 18.1
* Device Model: iPad Pro 13" (M4)
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? UTM Remote via AppStore / UTM on macOS via homebrew

**Crash log**
N/A

**Debug log**
N/A

**Upload VM**
N/A

**Comment by vitru** [comment]
I am hitting the same issue. I was struggling to get the auto-resolution to work thinking that there is something wrong with the SPICE tools but then saw this issue. "More Space" is essential to use Stage Manager on a smaller iPad 11", so having UTM do correct scaling would greatly improve usability.
