### ISSUE TITLE
Not run UTM 4.6.0 in my iPad Pro m1

### ISSUE THREAD

**Issue by Ramdutt298** [utmapp/UTM#6740]
**Describe the issue**
A clear and concise description of what the issue is. **BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Configuration (required)**
* UTM Version: 
* OS Version: 
* Device Model: 
* Is it jailbroken (name jailbreak used)? 
* How did you install UTM? 

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here.

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the bottom of the configuration options (or at the top of the `QEMU` page) is `Debug Log`. Turn it on and save the VM. After you experience the issue, quit the VM and re-launch UTM. Open the VM settings again and select `Export Log...` and attach it here.

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since GitHub has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by Ramdutt298** [comment]
UTM 4.6.0 not open and full feature in my iPad Pro m1
![IMG_0003](https://github.com/user-attachments/assets/1a134158
![IMG_0003](https://github.com/user-attachments/assets/c80b7e84-39a5-4298-b2a8-d4fad2b0c428)
-9bf5-40d8-8b81-462e470d84da)

**Comment by sulthannaf** [comment]
use ios 16.3.1 and lower

**Comment by osy** [comment]
Please provide a crash log (as explained in the template you forgot to fill out). Once you do, we can reopen this.
