### ISSUE TITLE
Can't Install macOS 15.2 Beta 1 on UTM 4.6.0

### ISSUE THREAD

**Issue by runwaygoats** [utmapp/UTM#6766]
**Describe the issue**  
What I tried to install macOS 15.2 Beta 1 with UTM 4.6.0 on macOS 15.2 Beta 1 host I got the following error message:

<img width="259" alt="Screenshot 2024-10-24 at 2 16 22 PM" src="https://github.com/user-attachments/assets/cad85919-6e6e-4109-8959-ede087197e86">

**Configuration**  
* UTM Version: 4.6.0
* macOS Version: 15.2 Beta 1
* Mac Chip (Intel, M1, ...): M1 Max

**Comment by Andware** [comment]
I have the samme problem. Install Xcode 16.2 beta not fix the problem.

**Comment by runwaygoats** [comment]
It seems that new macOS update fixed the problem.

**HOST**
Version 15.2 Beta (24C5073e)

**GUEST**
Version 15.2 Beta (24C5073e)
