### ISSUE TITLE
Windows 11 24H2 Installer goes into a boot loop on Intel Mac

### ISSUE THREAD

**Issue by mikegarciam** [utmapp/UTM#6772]
**Describe the issue**  
Windows 11 24H2 Installer does not work on Intel Mac, while installer for w11-23H2 does work.

When starting the VM and booting from the ISO image (downloaded using CrystalFetch), the UTM logo appears and then it just restarts after about 10 seconds. Attached recording of this behavior.

Tried with latest-available (26100.2161) and earliest-available (26100.2) builds for w11-24H2.

Using latest-available build for w11-23H2 works without issue (i.e. utm logo appears and installation process continues).

This only happened on an Intel-based Mac. Could not reproduce on M3 Mac.

**Configuration**  
* UTM Version: 4.5.4
* macOS Version: 15.0.1
* Mac Chip: Intel

**Crash log**  
-
**Debug log**  
Exported debug.log file is empty.

https://github.com/user-attachments/assets/8dd0932d-edc3-47ad-88b0-f61916c53ada

**Comment by Marty56** [comment]
same here.

**Comment by Anobodyasme** [comment]
me too，appear《 display out 》，how do i solve.

**Comment by osy** [comment]
Can you try on 4.6.0? We updated the QEMU backend which may address other issues like this

**Comment by Marty56** [comment]
Where can I download 4.6.0?

**Comment by Marty56** [comment]
Not working with 4.6.0 either.

**Comment by mikegarciam** [comment]
Tested with 4.6.0 and confirmed it still has the same issue.

**Comment by marcabele** [comment]
I'm using 4.54 UTM on MAC 15.1 M3 and was running Windows 11 latest and managed to complete the update to Windows 11  24H2 but after reboot I get UTM logo and then I just get a black screen and nothing happens. The screen flickers once and that's it.

**Comment by marcabele** [comment]
started a new VM on UTM 4.54 and used the latest iso using CrystalFetch and I have managed to install and working in Windows 11 24H2
<img width="548" alt="image" src="https://github.com/user-attachments/assets/d3082451-e549-4788-ad2c-bd39ac2cb39f">

**Comment by marcabele** [comment]
this is the iso file for reference
<img width="1221" alt="image" src="https://github.com/user-attachments/assets/0cc78240-3f1c-43fd-8068-1d5f1aae08f8">

**Comment by xunlinkx** [comment]
Also occurring, i5, Version 4.5.4 (100), tried both x64 24h2 2600.2448 and 24h2 2600.2240

**Comment by vshuraeff** [comment]
same problem.

**Comment by Ralph-Lee** [comment]
same here too.
