### ISSUE TITLE
yaboinextd00r FAT GAE

### ISSUE THREAD

**Issue by Clownfly** [utmapp/UTM#678]
**Describe the bug**

**Version**
In the menu bar select UTM -> About to see the version and build number.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Clownfly** [comment]
@ yaboinextd00r

**Comment by Clownfly** [comment]
@yaboinextd00r

**Comment by IIWare** [comment]
so do you really have to do all these issues?
