### ISSUE TITLE
I Found a way on how to go back to normal issues [Osy close or delete all spam issues and this if you see this]

### ISSUE THREAD

**Issue by IIWare** [utmapp/UTM#679]
go to  (https://github.com/utmapp/UTM/issues?page=5&q=is%3Aissue+is%3Aopen)  @osy86 if you close all spam issues you can close or delete this, this issue was meant to help others who want to see their issues, and who has hard time finding, this is never meant to be another spam issue.

**Comment by osy86** [comment]
@IIWare please so not respond to these. It’s fairly easy to get rid of these but having people respond to them or talk about it complicates the procedure. It takes like 15 seconds to delete everything.
