### ISSUE TITLE
MacBook Pro M4: QEMU error: QEMU exited from an error: With SME enabled, at least one vector length must be enabled.

### ISSUE THREAD

**Issue by rosch100** [utmapp/UTM#6790]
**Describe the issue**  
QEMU error: QEMU exited from an error: With SME enabled, at least one vector length must be enabled.
The VM was working before on a M1 MacBook Pro and transferred to an M4 MacBook Pro using Apples System migration tool.

**Configuration**  
* UTM Version: 4.5.4
* macOS Version: 15.2 Beta (24C5073e)
* Mac Chip (Intel, M1, ...): M4Pro

**Debug log**  
[QEMU-debug.log](https://github.com/user-attachments/files/17680563/QEMU-debug.log)

**Upload VM**  
[config.plist.zip](https://github.com/user-attachments/files/17680569/config.plist.zip)

**Comment by tjd-dev** [comment]
Experiencing this as well.

**Comment by Johnny9828** [comment]
Hello, I have the same problem.

**Comment by osy** [comment]
This is a bug in QEMU https://gitlab.com/qemu-project/qemu/-/issues/2665 but we will add a workaround in the next release.

**Comment by nayabryan** [comment]
Any idea on when the next release will take place?

Thank you.

**Comment by RealHuman20** [comment]
I'm also experiencing this on my M4 Mac mini. Hope to see a fix soon. Thanks!

**Comment by AgainstGreaterOdds** [comment]
Same issue here following public macOS 15.2 release. Where's the fix?

**Comment by AgainstGreaterOdds** [comment]
> Same issue here following public macOS 15.2 release. Where's the fix?

Please disregard. My UTM app was out of date. Resolved with the latest release. Thanks, team!

**Comment by AkihiroSuda** [comment]
Would you be possible to submit this patch to the upstream?

Context:
- https://github.com/Homebrew/homebrew-core/pull/201613#pullrequestreview-2519580577

**Comment by osy** [comment]
@AkihiroSuda No, because as the patch states "DO NOT MERGE" because it is not a proper fix. We (UTM) do not use SME so it does not matter. Upstream needs to handle more than Apple Mx processors.

**Comment by winsonet** [comment]
so may I know how to fix this issue? all of my VM are not be able to started after I upgraded the MacOS patches :(

**Comment by osy** [comment]
Update to the latest UTM

**Comment by winsonet** [comment]
> Update to the latest UTM

Oh, there is a new version! Thank you so much!
