### ISSUE TITLE
POWER OFF VM AND RESTART CAUSE THE APP TO FREEZE 

### ISSUE THREAD

**Issue by a3lharbi** [utmapp/UTM#68]
I Pad pro 11( jailbroken)

when u tried to power off and restart it will freeze. Therefore, killing the app causing white screen.

Note:
All the bug related with white screen and freezing is related to unc0ver.
Confirmed that never faced any issue with iPhone X (Jail Checkra1n) .

**Comment by osy86** [comment]
#32
