### ISSUE TITLE
"Shared folder" button blurred  when booting MacOS Sequoia guest

### ISSUE THREAD

**Issue by arianvp** [utmapp/UTM#6807]
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Describe the issue**  

Directory sharing is a feature that is supported by Virtualization.framework for MacOS guests, however I can't seem to share any directories in UTM from the host too the guest. The button is greyedo ut.

<img width="382" alt="Screenshot 2024-11-13 at 11 11 55 AM" src="https://github.com/user-attachments/assets/48f4a15b-d36d-4e73-80f5-7b99155a34ca">

**Configuration**  
* UTM Version:  4.5.4
* macOS Version:  15.1
* Mac Chip (Intel, M1, ...): M2 Max

**Crash log**  

**Debug log**  

**Upload VM**

**Comment by ideologysec** [comment]
This looks like it might be affecting all macOS Virtualization guests. It works fine for Linux Apple Virtualization guests, but I can reproduce this on:

UTM 4.6.0 beta
macOS 15.1 host
Apple M1 Max
macOS 13, 14, and 15 guests

occurs on all three guests.

**Comment by arianvp** [comment]
Hey thanks!

I tried out the change and the button is clickable now. However no mount shows up under `/Volumes/My Shared Folders` as documented here: https://developer.apple.com/documentation/virtualization/vzvirtiofilesystemdeviceconfiguration#4052497

so this still seems broken.
