### ISSUE TITLE
M4 Max MacBook Pro wont boot emulated x86_64 VM

### ISSUE THREAD

**Issue by coremedic** [utmapp/UTM#6814]
**Describe the issue**  
Emulated x86_64 VM wont boot. The VM repeatedly boots into the EFI shell. I have tried to boot it manually from the EFI shell to no avail.

**Configuration**  
* UTM Version: 4.5.4 (100)
* macOS Version: macOS 15.1 (24B2082)
* Mac Chip (Intel, M1, ...): M4 Max

**Comment by brekov** [comment]
@coremedic hi，how do you solve it?
