### ISSUE TITLE
Win11 on Mac OS - Guest has not initialized the display (yet)

### ISSUE THREAD

**Issue by ds-tommaso** [utmapp/UTM#6837]
**Describe the issue**  
UTM show _Guest has not initialized the display (yet)_

![screenshot](https://github.com/user-attachments/assets/8d776841-4b37-490a-8876-1c8bef31cfc0)

**Configuration**  
* UTM Version: 4.5.4 (100)
* macOS Version: Beta di 15.2 (24C5089c)
* Mac Chip: M4 on Mb PRO 14"

**Upload VM**
Please, remove .txt
[config.plist.txt](https://github.com/user-attachments/files/17893885/config.plist.txt)

**Comment by ds-tommaso** [comment]
config.plist (remove .TXT)

[config.plist.txt](https://github.com/user-attachments/files/17893876/config.plist.txt)

**Comment by skapsarali** [comment]
getting same error "Display Output Not Active"
