### ISSUE TITLE
Interest to provide UTM(4.7?) alpha release with new Qemu 9.2RC?

### ISSUE THREAD

**Issue by oscarbg** [utmapp/UTM#6839]
Hi,

QEMU 9.2rc0 is released and this week rc1 expected..
QEMU 9.2 it's interesting because of support for >32gb RAM for Mac VMs:
https://github.com/utmapp/UTM/issues/6805
can wait for Qemu 9.2 final release but anyway interest to provide "alpha" release builds with latest Qemu RC?

thanks..

**Comment by osy** [comment]
Duplicate of #5537
