### ISSUE TITLE
QEMU Error on every VM start: function qemu_spice_gl_scanout_texture

### ISSUE THREAD

**Issue by LostInCompilation** [utmapp/UTM#6854]
**Describe the issue**  
Yesterday I updated to the newest UTM version (4.6.2). I booted up a Win11 ARM64 VM, installed the new UTM guest tools and shut down the VM. Since then I cant start the VM anymore. As soon as the Win11 Log-In screen should appear, I get the error message down below. Shortly before the error message, the macOS window for the VM gets extremely large, way wider than the actual Mac display.

<img width="436" alt="Screenshot 2024-11-30 at 09 42 56" src="https://github.com/user-attachments/assets/440fa7cc-d2a8-4a06-a7eb-2869b35dd604">

**Configuration**  
* UTM Version: 4.6.2
* macOS Version: 15.1.1
* Mac Chip: M1 Pro

**Crash log**  
[QEMULauncher-2024-11-30-094233.ips.zip](https://github.com/user-attachments/files/17964783/QEMULauncher-2024-11-30-094233.ips.zip)

**Comment by osy** [comment]
Can you upload `~/Library/Containers/com.utmapp.UTM/Data/Library/Preferences/com.utmapp.UTM.plist` as well as the vm's config.plist? Note com.utmapp.UTM.plist will contain UTM Remote Server fingerprint and password so you should remove those before uploading if you are using remote server. I only need the data in Registry.

**Comment by osy** [comment]
As a workaround, you can find the Registry inside `com.utmapp.UTM.plist` and then locate the UUID of your VM and delete the entry ResolutionSettings (after uploading it here).
