### ISSUE TITLE
virtualization doesn't work after updating utm to the latest version

### ISSUE THREAD

**Issue by michalzablocki319** [utmapp/UTM#6861]
I have a problem with windows virtualization in the latest version of utm. I have a mac with an apple m3 chip, and I am running macOS 15.2.
The last non beta version of utm worked fine for me, but after upgrading to the latest one, I can't run any virtual machines with windows.
The I cannot boot into windows for arm (I tried with windows 10 as well as 11, both new and existing virtual machines, even if I boot with an empty CD drive) I just get a blank screen and I can't do anything about that.
What's interesting is that I don't have this problem with emulating other architectures, it's just virtualization.

**Comment by osy** [comment]
Can you provide a debug log as the issue template asked for?

**Comment by efroemling** [comment]
I might be running into the same thing. Just got the 4.6.2 update through the Mac App Store and now my Windows 11 arm VM just gives me a blank window when trying to start it.  I created the VM a week or two ago using the recently released arm installer iso from Microsoft. I'm on an M4 Max MBP.

Debug log:
[debug.log](https://github.com/user-attachments/files/17982759/debug.log)

Trying to create a fresh VM using the Microsoft installer iso seems to hang in the same way.

**Comment by markghayden** [comment]
My debian AMD64 VM won't startup after updating.  I'm running on MacOS with M1 chip.  QEMULauncher is stuck running at 300% CPU.

[Sample of QEMULauncher.txt](https://github.com/user-attachments/files/17982966/Sample.of.QEMULauncher.txt)

**Comment by michalzablocki319** [comment]
efroemling I have also updated by the mac app store if this might be of help.
Also, here is the debug log
[debug.log](https://github.com/user-attachments/files/17983196/debug.log)

**Comment by jheinen** [comment]
Same for me, both with Debian 12 and Ubuntu 24.04.

**Comment by osy** [comment]
Can someone provide a screenshot of this "blank screen"?

**Comment by osy** [comment]
I am able to reproduce it. Weirdly it's only an issue on the App Store build so I have no idea what's up.

**Comment by markghayden** [comment]
I can confirm the problem seems to be with the app-store version (which is what I was using).  When I download directly from web site, the problem does not occurs.

**Comment by osy** [comment]
Yup, the problem has been addressed but Apple needs to approve the new update...

**Comment by markghayden** [comment]
Thanks!  We'll try it out when the update is available.

**Comment by bitbemol** [comment]
I'm experiencing a black screen with the text "Display output is not active" when trying to emulate or virtualize any OS.

I'll be waiting for the update on the AppStore for macOS mentioned before my post.

Thanks a lot for the hard work, I hope the update also fixes my issue.

<img width="752" alt="Screenshot 2024-12-03 at 6 04 02 AM" src="https://github.com/user-attachments/assets/3c72501b-1aff-4fd1-9819-72e11f9ab7b1">

**Comment by osy** [comment]
Heads up v4.6.3 is now out on the App Store. Please manually update it if you didn't automatically get the update.

**Comment by michalzablocki319** [comment]
@osy Thanks. It works fine now. But what exactly did you do to fix the issue. Apparently it was only mac app store issue.

**Comment by osy** [comment]
I have no idea what the issue was and it was a huge pain to debug because you can't attach the debugger to App Store apps. But the issue was that the BIOS was being read as 0 size and it only affected the App Store version because of something weird with how macOS installs app store apps. I'm guessing it had something to do with the fact that the BIOS was read-only inside the app bundle so I just copied all the BIOS to a read-writable location and it works now but I don't know why.
