### ISSUE TITLE
UTM SE USING 62-82% power

### ISSUE THREAD

**Issue by Tim-sansom** [utmapp/UTM#6863]
Hi there I have a iPhone 16 pro max 1TB I have downloaded the app from the App Store….. I’m on iOS 18.1 I have created a vm with 2Gb ram 80gb HDD and am trying to install the latest version of kali Linux .. I know the phone has 8gb of ram so I looked up what is the minimum requirements are on the kali website now I can install but it’s incredibly slow and seriously drains my battery just on the install.

some times it’s between 62 -82% power usage this is incredibly high for an app on the phone to be honest . It takes ages to install and several times I have ran out of power and I have to start the install all over again this is terribly frustrating to say the least.

the only way round this so far is to pause the vm power up the phone and then continue again.  If you need me to provide you with anything please let me know and I will do.

**Comment by osy** [comment]
Yes this is all because we can't use JIT in the App Store.
