### ISSUE TITLE
Ability to disable screenshot captures used for setting the thumbnail for VMs.

### ISSUE THREAD

**Issue by ghost** [utmapp/UTM#6873]
UTM could accidentally capture sensitive content in the VM which would then be displayed upon opening UTM as a VM thumbnail. One can already delete these screenshots by pressing on `Show Package Contents` for the VM file and deleting it from there but it would be nice to have the option to fully disable the thumbnails.

**Comment by naveenrajm7** [comment]
+1 for this feature. 
I have set up a toolchain for building and distributing UTM VMs and found that the VM bundle has a `screenshot.png` file, which might have sensitive content from the VM screen. When the VM is distributed others will see this image, which the creator might not want to share.  
We can delete it manually before Sharing the VM, but a flag in the config and a checkbox in the UI will be convenient.

**Comment by osy** [comment]
There is an option to disable saving screenshots in the app settings.

**Comment by naveenrajm7** [comment]
oh found it. Thanks!
