### ISSUE TITLE
No cursor or keyboard input possible after upgrading to Windows 11 24H2

### ISSUE THREAD

**Issue by Eekrs** [utmapp/UTM#6883]
**Describe the issue**  
1. Issue happened after Upgrading to Windows 11 24H2 and activating BitLocker
 Blank window issue #6332 has been fixed via workaround (display device: virtio-ramfb-gl >> virtio-gpu-gl-pci)
2. Logging in via password worked fine, but on the next screen ("Microsoft und Apps den Standort verwenden lassen" / Let Microsoft and apps use the location) cursor or keyboard input is not possible anymore.

![Bildschirmfoto 2024-12-06 um 17 40 52](https://github.com/user-attachments/assets/c8079b9f-3e59-4715-b154-f04843b2a0a4)

3.  I rebooted and tried quiet a while, when suddenly at least the keyboard input worked again, so I could move forward using keyboard commands (TAB; ENTER).
4. Mouse input still won't work.

**Configuration**  
* UTM Version: 4.6.3 (106)
* macOS Version: 15.1.1
* Mac Chip (Intel, M1, ...): M3

**Crash log**  

[debug.log](https://github.com/user-attachments/files/18041316/debug.log)

**Comment by Eekrs** [comment]
Re-Installing guest tools fixed the issue.

**Comment by TheDiamond3435** [comment]
Worked for me. Thanks.

**Comment by cytan299** [comment]
Confirmed that Win11 24H2 works on 

- UTM 24.6.3
- MacOS 15.1.1
- M3 chip

when upgrading from 23H2 to 24H2 mouse is only available *after* the Windows Guest Tools are installed.

When first boot after 24H2 has successfully been upgraded from 23H2, the mouse completely disappears and only the keyboard works. Here's what I did to get past not having a mouse:
- On the CD icon on the virtual machine toolbar, click on "Install Guest Tools ..." to mount the CD drive.
- Once windows boots to the login screen. Hit "Enter" and type in your user name and password.
- There is a nag screen that win11 asks for you to select options. Unfortunately, it seems that the only thing that can be done is to hit enter key.
- Once on the desktop, hit command,spacebar (Mac keyboard) while inside win11. This pops up the "Search" box/panel. Type in "command" to bring up a command prompt (i.e. a command line).
-  type "e:" to get to the CD drive that has the guest tools.
- type ".\utm-guest-tools-0.229.exe" to start the guest tools install.
- Once installed, win11 will want to reboot. Use "Tab" key to cycle through options for reboot. Hit "Enter" to reboot.

After wi11 reboots and shows the login screen, voila, mouse is now available!

Hopefully, the above is sufficient to get people upgraded from win11 23H2 to 24H2

cytan

**Comment by alex-izaac** [comment]
> Confirmed that Win11 24H2 works on
> 
> * UTM 24.6.3
> * MacOS 15.1.1
> * M3 chip
> 
> when upgrading from 23H2 to 24H2 mouse is only available _after_ the Windows Guest Tools are installed.
> 
> When first boot after 24H2 has successfully been upgraded from 23H2, the mouse completely disappears and only the keyboard works. Here's what I did to get past not having a mouse:
> 
> * On the CD icon on the virtual machine toolbar, click on "Install Guest Tools ..." to mount the CD drive.
> * Once windows boots to the login screen. Hit "Enter" and type in your user name and password.
> * There is a nag screen that win11 asks for you to select options. Unfortunately, it seems that the only thing that can be done is to hit enter key.
> * Once on the desktop, hit command,spacebar (Mac keyboard) while inside win11. This pops up the "Search" box/panel. Type in "command" to bring up a command prompt (i.e. a command line).
> * type "e:" to get to the CD drive that has the guest tools.
> * type ".\utm-guest-tools-0.229.exe" to start the guest tools install.
> * Once installed, win11 will want to reboot. Use "Tab" key to cycle through options for reboot. Hit "Enter" to reboot.
> 
> After wi11 reboots and shows the login screen, voila, mouse is now available!
> 
> Hopefully, the above is sufficient to get people upgraded from win11 23H2 to 24H2
> 
> cytan

Thanks a lot !
