### ISSUE TITLE
Can't enable KVM - Please add!

### ISSUE THREAD

**Issue by ImAQwertyGuy** [utmapp/UTM#6885]
Hello,
I recently tried to install Android-x86 Pie in UTM on my M1 Mac. However, once I install it, it won't boot and goes to a black screen. Apparently the issue here is that you need to have KVM enabled to run Android in a QEMU VM. But UTM has no KVM option!
I know and completely understand that the UTM devs gave up on Android-x86 a long time ago, but I would still like to see KVM implemented because some Linux distros require KVM to work properly.

**Comment by aparashk** [comment]
Guest-side KVM requires nested virtualisation, which is not supported unless you have M3 or M4 CPU and Sequoia, see #6700.

**Comment by osy** [comment]
KVM is a Linux feature and will never be supported by UTM which runs on macOS
