### ISSUE TITLE
VM Gone after removing App Store version and installing downloaded version

### ISSUE THREAD

**Issue by trollfred** [utmapp/UTM#6886]
I have removed App Store UTM app and then installed downloaded UTM app
What is expected:
VM is still there
What happened
VM was gone and no where to be found

Is this behaviour by design or was it a bug?

MacOS: 15.1.1
UTM: 4.6.3
Guest OS: MacOS 15.1.1

**Comment by osy** [comment]
Deleting just the app shouldn't affect the data. How did you delete it?

**Comment by freebrowser1** [comment]
When one deletes an app from the /Applications folder using the Finder, the Finder will prompt whether you want to delete the associated files. The default is YES, so all VMs will be deleted.
So watch out !

**Comment by osy** [comment]
When you delete an App Store app from Launchpad, all its data will be deleted. This is not something we control and is how both iOS app store and macOS app store works. If you drag an app to the trash, this will not happen. You can also overwrite the app with the downloaded version and this will not happen. I wish Apple was more clear in the popup when you delete something from Launchpad but this is something you may report to https://www.apple.com/feedback/
