### ISSUE TITLE
Emulating RHEL x86 machine, running reposync causes "Inconsistency detected by ld.so".

### ISSUE THREAD

**Issue by odinb** [utmapp/UTM#6900]
**Describe the issue**  
When running the reposync command, it errors out with the error: "Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 538: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == ' failed!"
Running the x86 version of RHEL8 in "Emulate" mode.

**Configuration**  
* UTM Version: 4.6.3
* macOS Version: Sonoma 14.7.1
* Mac Chip (Intel, M1, ...): M3

**Crash log**  
N/A

**Debug log**  
For all issues related to running a VM, _including_ crashes, you should attach a debug log. (This is unavailable for macOS-on-macOS VMs. Attach an excerpt of your system log instead.)
To get the Debug log: open UTM, and open the settings for the VM you wish to launch. Near the top of the `QEMU` page is `Debug Log`. Turn it on and save the VM. After you experience the issue, open the VM settings again and select `Export Log...` and attach it here.

**Upload VM**  
If your issue is related to a specific VM, please upload the config.plist from your VM's .utm directory. To get this, right-click the VM in UTM and choose "Show in Finder". Then right-click the selected file in Finder and choose "Show Package Contents". The config.plist file is now visible. Right-click it and choose "Compress". Attach the resulting config.plist.zip file here.
You can upload the entire .utm if needed, but note this includes your VM's drive image and may contain personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by odinb** [comment]
[RHEL8_UTM_config.plist.log](https://github.com/user-attachments/files/18151927/RHEL8_UTM_config.plist.log)
[RHEL8_UTM-debug.log](https://github.com/user-attachments/files/18151928/RHEL8_UTM-debug.log)

**Comment by osy** [comment]
This seems like an QEMU issue. Can you try to reproduce it with QEMU and if so, submit a bug in their tracker: https://gitlab.com/qemu-project/qemu/-/issues

If you cannot reproduce it in QEMU, I will reopen the issue.
