### ISSUE TITLE
'Finder' cannot complete the operation because it cannot read or write certain data in 'qemu hppa softmmu'. (Error code-36)

### ISSUE THREAD

**Issue by rigel0212** [utmapp/UTM#6906]
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Describe the issue**  
无法安装应用，报错“访达”不能完成该操作，因为不能读取或写入“qemu-hppa-softmmu”中的某些数据。
（错误代码-36）
'Finder' cannot complete the operation because it cannot read or write certain data in 'qemu hppa softmmu'. (Error code-36)

**Configuration**  
* UTM Version:  v4.6.3
* macOS Version: 15.2
* Mac Chip (Intel, M1, ...): Macmini M4 chip

**Comment by osy** [comment]
You are trying to use HPPA? I don't think that's been tested. Can you provide a screenshot of the error?

**Comment by rigel0212** [comment]
> You are trying to use HPPA? I don't think that's been tested. Can you provide a screenshot of the error?

![screenshot-20241223-114524](https://github.com/user-attachments/assets/7083a465-15d9-4e3a-a45a-cbcce1f226e2)
![screenshot-20241223-114524](https://github.com/user-attachments/assets/db65fbe9-c207-4110-a39c-68d6c896d89c)

**Comment by rigel0212** [comment]
> You are trying to use HPPA? I don't think that's been tested. Can you provide a screenshot of the error?

I am unable to install the UTM app

**Comment by osy** [comment]
This does not appear to be a UTM related error. Something is wrong with macOS or with the file you downloaded.

**Comment by rigel0212** [comment]
> You are trying to use HPPA? I don't think that's been tested. Can you provide a screenshot of the error?



> This does not appear to be a UTM related error. Something is wrong with macOS or with the file you downloaded.

Although v4.6.3 cannot be installed, it can be run directly by double clicking. However, versions below v4.6 can be installed normally but cannot run. I don't know why
