### ISSUE TITLE
View/manage/export vm's that were started using the qemu-system-arm or qemu-system-x86_64 cli

### ISSUE THREAD

**Issue by mattboston** [utmapp/UTM#6907]
There are two things I haven't found a way to do. First, there are times that I need to start a vm from the cli by using the qemu-system-arm or qemu-system-x86_64 cli such as when I use Packer to build vm's. It would be nice for these vm's to appear in UTM and be able to be viewed or managed.

Second, it would be nice to be able to take an existing vm that was built in UTM and export as a qemu-system-* command.

**Comment by mattboston** [comment]
I was looking at packer-plugin-utm, but it looks like it's missing the ability to create a vm from iso. I found an example in the author's repo, but looks like it hasn't been implemented yet.

As far as monitoring another directory or context, I'm not sure how UTM's qemu differs from the standard macos version. If it were possible, it would be a nice feature.

For the second, that's perfect.  I didn't see that before.

**Comment by naveenrajm7** [comment]
Hello, 

## Packer 

Thank you for checking out the UTM Packer plugin. The iso builder has been implemented and it resides in the branch [utm-iso](https://github.com/naveenrajm7/packer-plugin-utm/tree/utm-iso). We want to show one solid example of how to use iso builder end-to-end, after that it will be merged and released. We will update here when its merged. 

While the most components required for packer functionality exists, there are few APIs still lacking from UTM side. eg: Ability to add/remove/update displays (required for vnc). Until these are done the build process will be semi-automatic , where you will be prompted to add displays etc.

Beyond this, from our experience of trying to build several base images using this plugin for our [vagrant plugin](https://naveenrajm7.github.io/vagrant_utm/) , we found while the plugin automation works great, it is hard and time consuming to figure out which packer recipe suites which VM. eg: As evident by other issues here, it is difficult to know which display works well for which OS installation. However, once you have the steps for proper autoinstall it is easy to let packer do it.

## Difference between UTM Qemu and Standard Qemu

UTM uses a custom fork of [qemu](https://github.com/utmapp/qemu). More specifics are detailed in the [UTM Documentation](https://github.com/utmapp/UTM/blob/main/Documentation/Architecture.md)

**Comment by naveenrajm7** [comment]
Just released a new version of UTM packer plugin with ISO builder support
https://github.com/naveenrajm7/packer-plugin-utm/releases/tag/v0.1.0

Example with packer recipe: 
https://github.com/naveenrajm7/utm-box?tab=readme-ov-file#example

**Comment by osy** [comment]
Closing this because as indicated in the comment above, the ability to export the QEMU command is already a feature. However, be warned that we use a fork of QEMU so some devices may not work as-is on QEMU. Additionally, we use SPICE which isn't built with brew's QEMU. So the arguments should be seen more as a reference for debugging than something you can copy-paste and expect to work.
