### ISSUE TITLE
Machine preview only updates when pausing

### ISSUE THREAD

**Issue by Andrupka** [utmapp/UTM#699]
**Describe the bug**
Instead of screenshot it shows blank purplish square

**Version**
2.0.10

**To Reproduce**
1. Title says it all
**Expected behavior**
There should be VM's screenshot

**Screenshots**
<img width="1012" alt="Снимок экрана 2020-11-26 в 14 16 35" src="https://user-images.githubusercontent.com/74910987/100344541-048ef180-2ff2-11eb-96c7-47364b33f413.png">

**Comment by osy86** [comment]
It only takes a screenshot when you pause a VM. Maybe the rules can be improved (I would have to detect when you are "booted").

**Comment by Andrupka** [comment]
Ok

**Comment by 0sy-is-ssucch-a-s-st-puid-idio-t-l-l-l** [comment]
𝐈𝐖𝐚𝐧𝐧𝐚𝐊𝐢𝐥𝐥𝐀𝐧𝐝𝐫𝐮𝐩𝐤𝐚!!!

**Comment by 0sy-is-ssucch-a-s-st-puid-idio-t-l-l-l** [comment]
𝐈𝐀𝐥𝐬𝐨𝐖𝐚𝐧𝐧𝐚𝐊𝐢𝐥𝐥𝐎𝐬𝐲𝐓𝐨𝐨!!!!

**Comment by osy** [comment]
We now update the screenshot at a timed interval.
