### ISSUE TITLE
Missing Sound cards and network cards for PPC.

### ISSUE THREAD

**Issue by snslpa** [utmapp/UTM#706]
On UTM v1.0 RC3 and RC4 the app implemented some sound cards (Screamer / Burgundy) and network card (Sungem) for Power PC Mac OS 9 emulation but in 2.x aren’t listed as an option.
What happened? Thanks.

**Comment by osy86** [comment]
The missing soundcards are not resolved (#312) because it requires a fork of QEMU which is not under consideration at this time. The missing network card is a label problem (it shows up as "None") and will be fixed.
