### ISSUE TITLE
Mouse issues with older OS are still there.

### ISSUE THREAD

**Issue by Andrupka** [utmapp/UTM#710]
**Describe the bug**
Mouse does not go to lower-right corner, but it just goes to right edge and right-clicks by itself.

**Version**
2.0.11

**To Reproduce**
1. Boot VM
2. See strange behaviour
**Expected behavior**
It should work normally
**Additional context**
Also, there is no ability to hold mouse button and move pointer at same time. Really strange.

**Comment by osy86** [comment]
Can you post the VM you are having issues with?

**Comment by Andrupka** [comment]
Here it is: 
https://drive.google.com/drive/folders/17iksumlOQSdjZOVKziZgDbp1EZ8dopxx?usp=sharing

**Comment by osy86** [comment]
@Andrupka for the mouse jumping around issue, it seems like your Windows installation doesn't have the proper drivers for USB HID tablet installed. I made a fresh OEM Windows XP (English) installation and it had the right drivers included, but I don't know if your installation disk has it as well. In mouse capture mode, it seems to work fine.

**Comment by Andrupka** [comment]
Ok, thanks

**Comment by osy86** [comment]
Actually I got some similar behaviour with a fresh VM by swapping between capture and non-capture mode so I'll keep this open.
