### ISSUE TITLE
Only 256MB of 2GB RAM usable?

### ISSUE THREAD

**Issue by UInt2048** [utmapp/UTM#718]
**Describe the bug**
On my iPad6,3 (9.7-inch iPad Pro), I can only use 256MB (out of the 2GB total RAM on-device) without experiencing the pop-up explaining that the VM won't be able to allocate enough memory and crash. _Is it possible to give the VM more RAM, say 1024MB?_

**To Reproduce**
1. Go to the settings to change the RAM amount
2. Change it to anything above 256MB

**Crash log**
N/A

**Debug log**
N/A

**Upload VM**
Android 9.0 UTM on official website

**Comment by IIWare** [comment]
[According](https://android.stackexchange.com/questions/34958/what-are-the-minimum-hardware-specifications-for-android#:~:text=Here%20follows%20a%20somewhat%20simpler,at%20least%20416%20MB%20memory.) to android.stackexchange.com:
> Here follows a somewhat simpler answer regarding the RAM memory requirements. According to the above mentioned docs, all versions from "Lollipop" (Android 5.0) up to "Pie" (Android 9.0) need at least 416 MB memory.

so android 9.0 needs at least 416 MB of memory, I would give it 512MB for the best performance. if it shows the popup, decrease the amount of memory until it doesn't show the popup, if you are decreasing until you reached 416MB of memory and the popup still shows up, that's where you can try other versions of android virtual machines from UTM that doesn't consume a lot of memory.

**Comment by UInt2048** [comment]
@IIWare My question was if there was anything that could be done to increase the amount of RAM that could be given before the pop-up comes up.

**Comment by osy86** [comment]
On jailbroken phones, I've heard from others that there are ways to bypass the memory limit by tinkering with jetsam but I don't have any experience with that. You may have luck asking around in the discord.
