### ISSUE TITLE
Strange error on booting any VM

### ISSUE THREAD

**Issue by Andrupka** [utmapp/UTM#721]
**Describe the bug**
Every VM instead of booting says "Reason: image not found"

**Version**
2.0.12

**To Reproduce**
1. Boot VM
2. See error
**Expected behavior**
It should boot

**Screenshots**
<img width="912" alt="Снимок экрана 2020-12-01 в 08 32 20" src="https://user-images.githubusercontent.com/74910987/100700964-c279fd00-33af-11eb-82df-3888c17c22f5.png">

**Comment by rloomans** [comment]
I have another one that only happens with 2.0.12 and not 2.0.11
<img width="695" alt="Screen Shot 2020-12-01 at 17 20 39" src="https://user-images.githubusercontent.com/92133/100719643-9fc80280-3408-11eb-8576-3c04e91ef2ac.png">

**Comment by osy86** [comment]
@rloomans did you run the release or did you build it yourself?

**Comment by osy86** [comment]
@Andrupka Can you lookin in Console -> Crash Reports and see if there's any recent entry for QEMU?

**Comment by Andrupka** [comment]
Here:
Process:               qemu-system-x86_64 [730]
Path:                  /Applications/UTM.app/Contents/XPCServices/QEMUHelper.xpc/Contents/MacOS/qemu-system-x86_64
Identifier:            qemu-system-x86_64
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        QEMUHelper [729]
Responsible:           UTM [728]
User ID:               501

Date/Time:             2020-12-01 12:31:16.067 +0300
OS Version:            macOS 11.0.1 (20B29)
Report Version:        12
Anonymous UUID:        2C92FED2-B099-694E-17C4-6A5510A9640E


Time Awake Since Boot: 1500 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 9F6FFF1F-4096-355B-B037-8DCE73A7AA42
Library not loaded: /usr/local/opt/curl/lib/libcurl.4.dylib
  Referenced from: /Applications/UTM.app/Contents/XPCServices/QEMUHelper.xpc/Contents/MacOS/qemu-system-x86_64
  Reason: image not found

Binary Images:
       0x10f228000 -        0x10fc7bfff +qemu-system-x86_64 (0) <255C2D7F-D2F3-3B2C-A0F8-694BB9B331F0> /Applications/UTM.app/Contents/XPCServices/QEMUHelper.xpc/Contents/MacOS/qemu-system-x86_64
       0x10ffc4000 -        0x1103c3fff +libpixman-1.0.utm.dylib (0) <56BA3B8E-439C-3F01-809E-8940566DFDCD> /Applications/UTM.app/Contents/Frameworks/libpixman-1.0.utm.dylib
       0x1103f9000 -        0x11053cfff +libspice-server.1.utm.dylib (0) <A194E395-C19A-3EDF-A2ED-54D7D264F249> /Applications/UTM.app/Contents/Frameworks/libspice-server.1.utm.dylib
       0x110591000 -        0x11072cfff +libgio-2.0.0.utm.dylib (0) <A843846C-A37D-376C-B719-58130966D358> /Applications/UTM.app/Contents/Frameworks/libgio-2.0.0.utm.dylib
       0x110860000 -        0x1108abfff +libgobject-2.0.0.utm.dylib (0) <F8CC9661-4F04-3EBD-8900-8A844FF7ED92> /Applications/UTM.app/Contents/Frameworks/libgobject-2.0.0.utm.dylib
       0x1108e1000 -        0x110a4cfff +libglib-2.0.0.utm.dylib (0) <7F8EC575-CB77-37E0-A34A-7347327BF5B0> /Applications/UTM.app/Contents/Frameworks/libglib-2.0.0.utm.dylib
       0x110acf000 -        0x110b0efff +libpng16.16.utm.dylib (0) <5083B2A3-7C16-3673-8DCD-F7586E59DABF> /Applications/UTM.app/Contents/Frameworks/libpng16.16.utm.dylib
       0x110b28000 -        0x110c1ffff +libgcrypt.20.utm.dylib (0) <3DFA3347-67E4-32E2-8B7B-B7E0811E028F> /Applications/UTM.app/Contents/Frameworks/libgcrypt.20.utm.dylib
       0x11295b000 -        0x1129f6fff  dyld (832.7.1) <2705F0D8-C104-3DE9-BEB5-B1EF6E28656D> /usr/lib/dyld
    0x7fff20391000 -     0x7fff2082cfff  com.apple.CoreFoundation (6.9 - 1770.106) <7EBD4941-5978-33EF-98FB-724BB81E92C8> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff21b23000 -     0x7fff221c6fff  com.apple.audio.CoreAudio (5.0 - 5.0) <6A945D2C-386F-375C-8343-845012AAA414> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff22ae5000 -     0x7fff22b92fff  com.apple.framework.IOKit (2.0.2 - 1845.50.1) <18A1F263-4AE2-3F9B-A38F-50BEB00B43D1> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff2a434000 -     0x7fff2a446fff  libz.1.dylib (76) <0AF4F195-1F20-3F59-B09F-31E7249890D5> /usr/lib/libz.1.dylib
    0x7fff2a4fc000 -     0x7fff2a4fdfff  libSystem.B.dylib (1292.50.1) <14E3BB7B-B95F-3700-8D12-B9B2012C0AF8> /usr/lib/libSystem.B.dylib
    0x7fff2a76f000 -     0x7fff2a773fff  libpam.2.dylib (28.40.1) <4C7D4B94-5CBA-3480-9BA0-D52B5C675D2A> /usr/lib/libpam.2.dylib
    0x7fff2cd9f000 -     0x7fff2cdb7fff  libresolv.9.dylib (68) <6C18FE1C-EB05-3E02-925D-DE09157C55F9> /usr/lib/libresolv.9.dylib
    0x7fff6e3e2000 -     0x7fff6e3e9fff  com.apple.Hypervisor (1.0 - 1) <9EE88357-286E-3145-97DE-40EE68087526> /System/Library/Frameworks/Hypervisor.framework/Versions/A/Hypervisor

**Comment by osy86** [comment]
@Andrupka can you confirm you're using the .dmg downloaded from the Release page? I don't know why it's looking for libcurl. Can you run `shasum /Applications/UTM.app/Contents/XPCServices/QEMUHelper.xpc/Contents/MacOS/qemu-system-x86_64`? It should be `d96bd0dba7b772f27cd0fa9eb9c72e716b8648d0`

**Comment by rloomans** [comment]
> @rloomans did you run the release or did you build it yourself?

I used the release version.

**Comment by osy86** [comment]
Okay there's an issue in the build. Temp workaround is to install https://brew.sh and `brew install curl`. Will be fixed next release.

**Comment by rloomans** [comment]
@osy86 It looks like the workaround doesn't work on Big Sur... I already have brew and curl installed.

**Comment by Andrupka** [comment]
Curl does not help.
<img width="912" alt="Снимок экрана 2020-12-02 в 08 35 22" src="https://user-images.githubusercontent.com/74910987/100832696-6ed3e600-3479-11eb-9a40-372d4fd5cfae.png">
