### ISSUE TITLE
“Native” Unix/MacOS Programs?

### ISSUE THREAD

**Issue by zaptrem** [utmapp/UTM#73]
Could the same JIT peculiarity abused to run VMs in this app be used to create a sandboxed terminal that could download and run OSX CLI tools natively using a WINE-like system call translator?

**Comment by osy86** [comment]
Yeah, look at the iSH project. You can probably take that and introduce "proper" JIT.

**Comment by zaptrem** [comment]
I think iSH just uses whacky user mode semi-almost-not-JIT to run x86 Alpine. I was talking about avoiding the emulation layer entirely and running compiled-for-ARM Unix apps.

**Comment by osy86** [comment]
Yes I'm saying you can fork iSH and adding such a thing.

**Comment by zaptrem** [comment]
@osy86 
Mildly related: Does QEMU/Tiny Code Generator have a "passthrough" type mode where it wouldn't bother interpreting ARM VM instructions and pass them through as is? That way if I'm running an OS compiled for A64 (A12X's instruction set) it would run a little closer to native speed.

**Comment by osy86** [comment]
No it doesn’t.

**Comment by zaptrem** [comment]
@osy86 After learning a bit more about this what I proposed is essentially a paravirtualization-based user mode hypervisor. We don’t have access to ARM’s virtualization extensions (correct me if I’m wrong but they aren’t even implemented on A series CPUs). A couple researchers actually developed this for KVM/QEMU:

http://systems.cs.columbia.edu/files/wpid-ols2010-kvmarm.pdf

http://www.cse.unsw.edu.au/~cs9242/12/exam/paper1.pdf


But they ran into performance problems with their trap-and-emulate/memory virtualization implementations, and their implemented the hypervisor directly into KVM’s piece of the Linux kernel (instead of as a user mode app like UTM). I wonder if any of the contributors to those papers would be interested in contributing to this project?

**Comment by osy86** [comment]
You may want to check out pongoOS and https://mobile.twitter.com/CorelliumHQ/status/1235251256895123456 which is exactly what you are talking about.

**Comment by zaptrem** [comment]
Thanks, I’ve looked into this and it requires a specific jailbreak (which
isn’t available for the latest iPad Pro on the latest iOS).

**Comment by osy86** [comment]
Well any solution would require the same level of access.
