### ISSUE TITLE
There is no way to create kvm enabled vms

### ISSUE THREAD

**Issue by Watking01** [utmapp/UTM#74]
I want to run android on utm, but it doesn’t, because it requires kvm.
I have run windows and Ubuntu perfectly, but it’s just android which I really want, but cannot fully install. Please could you add a toggle for kvm vms
Thank you

**Comment by osy86** [comment]
Yes

**Comment by zaptrem** [comment]
What does “Yes” — wontfix mean?

**Comment by osy86** [comment]
Yes, there is no way to create kvm enabled vms because that is a feature that depends on Intel Virtualization Extensions.
