### ISSUE TITLE
UTM app has the problem of white screen,when I turn on VM, it will flash back to the desktop.

### ISSUE THREAD

**Issue by WindowsBetaTest** [utmapp/UTM#76]
I created a wrong VM. I want to delete it, but I couldn't find any files (All types of files, someone told me that the suffix of VM's filename was: "*.utm")in the UTM app directory in the file application.

I have some additional information here. I hope it can help you repair this app:

iPad system version: iPad OS 13.3.1
iPad model : iPad 5 WiFi
iPad jailbreak with checkra1n

If I don't use my iPad for checkra1n jailbreak, UTM app will flash back (the IPA file of UTM is use the fake design, I think the flash back should be an IPA signature problem).

Sometimes the UTM app also has the problem of white screen.

When I turn on VM, it will flash back to the desktop.

**Comment by WindowsBetaTest** [comment]
Who can help me fix it？

**Comment by obbcth** [comment]
#32
