### ISSUE TITLE
Stuck on white screen even after reboots

### ISSUE THREAD

**Issue by Watking01** [utmapp/UTM#78]
I crashed it once, and since then I can’t open the app 
I am jail broken, but I have tried with and without jailbreak

**Comment by osy86** [comment]
How did you reboot?

**Comment by WindowsBetaTest** [comment]
Don't use your Apple phone for software jailbreak

**Comment by WindowsBetaTest** [comment]
You can use altstore to install UTM. The jailbreak installation will cause unexpected errors.

**Comment by Watking01** [comment]
> How did you reboot?

I just rebooted, then rejailbroke

**Comment by osy86** [comment]
I mean how specifically? Did you hold the button combo? Did you go into settings?

**Comment by Watking01** [comment]
> I mean how specifically? Did you hold the button combo? Did you go into settings?

I just held the power button and slid the slider

**Comment by Watking01** [comment]
> You can use altstore to install UTM. The jailbreak installation will cause unexpected errors.

I used appcake, still stuck

**Comment by Watking01** [comment]
Actually I just rebooted one more time, just to see if it would work, and it worked, don’t know why or how
