### ISSUE TITLE
[CocoaSpice] Support cursor click and drag

### ISSUE THREAD

**Issue by qdljerry** [utmapp/UTM#82]
Does the UTM support to keep the mouse down in VM?

**Comment by qdljerry** [comment]
If not, the vm system can not drag the file and more operations

**Comment by qdljerry** [comment]
If not, the vm system can not drag the file and more operations

**Comment by osy86** [comment]
Mouse support needs to be improved.

**Comment by filfat** [comment]
@osy86 would it be possible to have the display report as touchscreen? That would make some touch-optimized operating systems more useable.

**Comment by osy86** [comment]
Yeah that’s planned.
