### ISSUE TITLE
After enabling the network, the VM will crash when it is powered on, and then flash back to the desktop.

### ISSUE THREAD

**Issue by WindowsBetaTest** [utmapp/UTM#84]
I created a Windows VM, but when I turned it on, UTM flashed back to the desktop.
I tried several times, but it didn't work. After I turn off the sound card and network card, windows VM can be used normally.
My iPad system version is a developer preview of iPad OS 13.4

**Comment by osy86** [comment]
Most likely memory issue #67 #24

**Comment by WindowsBetaTest** [comment]
@osy86 Can you add a virtual memory function to UTM,just like system swapfile file.

**Comment by osy86** [comment]
If there is such a feature in qemu I can try to support it. Otherwise you need to get such a feature in qemu first. I am not a qemu developer.
