### ISSUE TITLE
Cannot choose ISO file when importing disks

### ISSUE THREAD

**Issue by MaTianlai** [utmapp/UTM#85]
I want to create a VM:

```
name: Fedora Linux
architecture: x86_64
memory: 2048MB
CPU Count: 2
Open configuration after Creation: false
```
Then I went to `Setup Drives -> New Drive -> Select Disk -> Import Disk`

Then I tried to choose a Win10 .iso file (about 5 GB), but it doesn’t work. I tried to choose a Fedora Linux file (about 1GB), and it doesn’t work. The file was gray.

![IMG_4824](https://user-images.githubusercontent.com/38977108/75623274-56c9f000-5be3-11ea-92b2-9a7a7aac260f.jpeg)

I watched others’ tutorials on web, why they can choose a ISO file?

**Comment by humboldtjs** [comment]
There's a bug in VMConfigDrivePickerViewController.m. It tells the document-picker to allow files of type "public.data" which indicates a specific subset of files that are OS-level known data containers (things like PDF, MP4, DOCX, etc.). However the document picker should allow files of type "public.item" which indicates any publicly accessible item (including ISO, IMG and any other file-format).

The change:
```
        UIDocumentPickerViewController *picker = [[UIDocumentPickerViewController alloc] initWithDocumentTypes:@[@"public.data"] inMode:UIDocumentPickerModeImport];
```
To:
```
        UIDocumentPickerViewController *picker = [[UIDocumentPickerViewController alloc] initWithDocumentTypes:@[@"public.item"] inMode:UIDocumentPickerModeImport];
```

As a workaround until this is fixed you can rename you ISO to a different (supported) extension such as .PDF, and the import will work.

**Comment by osy86** [comment]
Thanks for figuring that out. I will look into it.

**Comment by MaTianlai** [comment]
@humboldtjs, Thank you for your reply, but if I import an `.ISO` as a `.PDF` document, does that work? Do I need to change the suffix to `.ISO` after import?
