### ISSUE TITLE
[qemu] Implement network forwarding

### ISSUE THREAD

**Issue by SpinningK** [utmapp/UTM#88]
According to the existing issues, it seems that the vm's ip is always like 10.0.x.x. I'm a novice at network and configuration on iPad(as host) gets things even harder. Should there be a way that host(iPad), even the local network, can reach the vm.

**Comment by osy86** [comment]
Sometimes, you need to manually set the DNS to 8.8.8.8

**Comment by SpinningK** [comment]
> Sometimes, you need to manually set the DNS to 8.8.8.8

Yes, I have already set it. I can connect to the Internet. But the input of UTM is not good enough, so I want to connect the vm from iPad(host) by ssh. Or if you know code-server, which is an amazing project that allows me to code in broewser. If iPad could reach the vm through http protocol, I can run a vscode totally on my iPad. But now my ipad or the devices in the local network can't connect to the vm. Their addresses are 192.168.x.x, however, the vm is in 10.0.x.x. To my research, qemu has the NAT implementation totally by itself, which enables the vm to connect to the Internet, however, also separates the vm from the host or other local devices. I think, maybe not right, we are just in this way.  Another way called 'bridge networking', which exposes vm to the local network, but requires configuration in host. The question is that the host now is an iPad, I can do nothing to configue the bridge networking. That's where I stuck at.

**Comment by osy86** [comment]
Yeah that’s not currently supported.

**Comment by WongIong** [comment]
@SpinningK 
Can you help me to setup the network?
Cause i have tried to set the DNS server 1.1.1.1 inside a Windows 7 VM.
But network still doesn't work.
Thank you!

**Comment by SpinningK** [comment]
> @SpinningK
> Can you help me to setup the network?
> Cause i have tried to set the DNS server 1.1.1.1 inside a Windows 7 VM.
> But network still doesn't work.
> Thank you!

Sorry, but I only tried to configure network on Linux,  and why not use 8.8.8.8?

**Comment by WongIong** [comment]
Ok, i will try on ubuntu later.
I have used 8.8.8.8 for a long time. But i think 1.1.1.1 is more stable. Or, am I wrong?

**Comment by professorIsaac** [comment]
A bigger incentive for this would be the possibility of running alt server on UTM to refresh UTM and AltStore especially since osy released a AltStore repo

**Comment by Leask** [comment]
@osy86 I installed Debian, but can not get network access, what can I do?

**Comment by Leask** [comment]
@osy86 I tried DHCP and static IP config with IP 10.0.2.15, GW 10.0.2.2 followed default QEMU guide. I still can not access the network.

**Comment by Leask** [comment]
@osy86 OK, I configured DNS and it works now. Thanks!

**Comment by Leask** [comment]
Can I ssh into the VM? I tried but failed. @osy86
